elastic/eui

- src/components/table/_table.scss
- src/global_styling/theme_dark_variables.scss
Tables didn't have a hover state when they were also selected. I also went ahead and adjusted some of the dark theme coloring around this as well.
> Adjust table selection / hover states

- src/components/tabs/_tabs.scss
After the sidenav, only tabs had the teal active state. It's now set to the primary coloring. Hat tip @cjcenizal for calling this one out.
> Remove secondary color from active states

- src/components/icon/assets/copy_clipboard.svg
cc @gjones
Small tip for icons. Run them through SVGO (there's a sketch plugin). Usually past that you'll also need to remove any fills in the actual code of the SVG (this means you can't use strokes, just paths / shapes).
This allows them to be colored by CSS / work with our theming system. Otherwise they'll only have the one color no matter what we try to do to it (in example below the clipboard should have been white).
> Reformat / fix clipboard icon

- src-docs/src/views/tabs/tabs.js
- src-docs/src/views/tabs/tabs_example.js
- src/components/tabs/_tabs.scss
- src/components/tabs/tabs.js
Although I don't think it should be used that often, the smaller tabs will be needed if we ported visualization over as is. It's also useful for placing within popovers or other tight places.
> Tabs can now pass a size prop, small tabs added

- src-docs/src/views/table/compressed.js
- src-docs/src/views/table/table.js
- src-docs/src/views/table/table_example.js
- src/components/table/__snapshots__/table_row_cell.test.js.snap
- src/components/table/_table.scss
- src/components/table/table_row_cell.js
- src/components/table/table_row_cell.test.js
This has caused enough headaches in Cloud that it makes sense to flip the argument. The naming change will make it easier to fix (propTypes warning) and more straightforward (when off nothing occurs, when on text becomes single-line and truncated)
The styling is also more straightforward thanks to this flippening.
Added a few simple snapshot tests.
> Change `wrapText={ false }` to `truncateText={ false }` by default

- CHANGELOG.md
- src/components/button/button_empty/_button_empty.scss
Closes https://github.com/elastic/eui/issues/134 at the request of @zinckiwi
For the moment, I'm keeping it on EmptyButtonIcon. I can't really underline the icons, so this solution doesn't work well for them. Likely I'll think up a better way to handle those then doing the background, but that can be a later PR.
> Remove styling from hover state of empty buttons

- CHANGELOG.md
- src/components/code/__snapshots__/_code_block.test.js.snap
- src/components/code/__snapshots__/code.test.js.snap
- src/components/code/__snapshots__/code_block.test.js.snap
- src/components/code/_code_block.js
- src/components/code/_code_block.scss
- src/components/code/_code_block.test.js
- src/components/code/code.js
- src/components/code/code.test.js
- src/components/code/code_block.js
- src/components/code/code_block.test.js
Block goes `<div><pre><code>`:
Inline goes `<span><code>`:
Public interface left unchanged:
> Keep using <pre> for code blocks.

- src/components/code/__snapshots__/_code_block.test.js.snap
- src/components/code/__snapshots__/code.test.js.snap
- src/components/code/__snapshots__/code_block.test.js.snap
- src/components/code/_code_block.js
This would trigger CSP warnings if `unsafe-inline` is not set, so better remove it, no harm done. `auto` is already default in CSS.
> Remove `auto` inline style from code blocks

- CHANGELOG.md
- src-docs/src/views/form/form_controls_loading.js
- src-docs/src/views/form/form_example.js
- src/components/form/_index.scss
- src/components/form/field_number/__snapshots__/field_number.test.js.snap
- src/components/form/field_number/_field_number.scss
- src/components/form/field_number/field_number.js
- src/components/form/field_password/_field_password.scss
- src/components/form/field_password/field_password.js
- src/components/form/field_search/_field_search.scss
- src/components/form/field_search/field_search.js
- src/components/form/field_text/__snapshots__/field_text.test.js.snap
- src/components/form/field_text/_field_text.scss
- src/components/form/field_text/field_text.js
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/form_control_layout.js
- src/components/form/select/_select.scss
- src/components/form/select/select.js
Closes https://github.com/elastic/eui/issues/146
Add `isLoading` to any text based form field to signify the input is in a loading state. This can be provided in combo with props like `disabled` if needed.
> Form fields now have a loading state

- CHANGELOG.md
- src/components/progress/__snapshots__/progress.test.js.snap
- src/components/progress/_progress.scss
- src/components/progress/progress.js
Otherwise it breaks layout. Cleaned up spacing, thus the diff looks bigger than what actually changed.
> Render <EuiProgress> as display block

- CHANGELOG.md
- src-docs/src/views/code_editor/code_editor_example.js
- src-docs/src/views/code_editor/read_only.js
- src/components/code_editor/__snapshots__/code_editor.test.js.snap
- src/components/code_editor/_code_editor.scss
- src/components/code_editor/code_editor.js
- src/components/code_editor/code_editor.test.js
* Place cursor at beginning of code editor if it's read-only.
* Surface prompt for isReadOnly mode. Only show cursor when the editor is focused.
Ports https://github.com/elastic/kibana/pull/14804
> Add isReadOnly prop to EuiCodeEditor.

- CHANGELOG.md
- src/components/table/__snapshots__/table.test.js.snap
- src/components/table/__snapshots__/table_header_cell.test.js.snap
- src/components/table/__snapshots__/table_header_cell_checkbox.test.js.snap
- src/components/table/table_header_cell.js
- src/components/table/table_header_cell_checkbox.js
Port of https://github.com/elastic/kibana/pull/15079
> Add scope prop to EuiTableHeaderCell and EuiTableHeaderCellCheckbox.

- src-docs/src/components/guide_page/guide_page_chrome.js
- src-docs/src/services/routes/routes.js
- src-docs/src/views/app_view.js
- src-docs/src/views/guidelines/writing.js
@gchaps Will this work for you?
@snide Gail mentioned that it'd be nice to break up the content on the front page and add additional guidelines pages here regarding our design principles, e.g. rationales and guidance on colors, spacing, typography. Maybe some other stuff, like UI and UX principles we really care about.
> Add Guidelines section with a stub for writing guidelines.

- CHANGELOG.md
- src/components/page/page_side_bar/_page_side_bar.scss
Originally the width would change as you navigate from page to page. Now it stays fixed. Seems related to https://github.com/philipwalton/flexbugs#flexbug-1.
CC @snide
> Fix bug with EuiPageSideBar width.

- src-docs/src/services/routes/routes.js
- src-docs/src/views/tooltip/examples.js
- src-docs/src/views/tooltip/tooltip_example.js
- src/components/index.js
- src/components/index.scss
- src/components/tooltip/_index.scss
- src/components/tooltip/_tooltip.scss
- src/components/tooltip/index.js
- src/components/tooltip/tooltip.js
- src/components/tooltip/tooltip_constants.js
- src/components/tooltip/tooltip_trigger.js
- src/services/index.js
- src/services/overflow/index.js
- src/services/overflow/no_overflow_placement.js
Adds tooltip component
Adds new service `noOverflowPlacement` that contains reusable logic for determining placement (top, right, bottom, left) that avoids clipping by window view port
> tooltip component

- src/components/flex/__snapshots__/flex_grid.test.js.snap
- src/components/flex/__snapshots__/flex_group.test.js.snap
- src/components/flex/__snapshots__/flex_item.test.js.snap
- src/components/flex/flex_grid.test.js
- src/components/flex/flex_group.test.js
- src/components/flex/flex_item.js
- src/components/flex/flex_item.test.js
- src/test/index.js
- src/test/react_warnings.js
References #177
Adds tests for:
- FlexGroup
- FlexGrid
- FlexItem
> Flex tests

- CHANGELOG.md
- src-docs/src/views/icon/icon_sizes.js
- src/components/icon/__snapshots__/icon.test.js.snap
- src/components/icon/_icon.scss
- src/components/icon/icon.js
- src/components/side_nav/__snapshots__/side_nav.test.js.snap
- src/components/side_nav/side_nav_item.js
The arrows in the sidenav was pretty overbearing.
> New icon size of small, adjust coloring of sidenav arrows

- CHANGELOG.md
- src-docs/src/views/tooltip/examples.js
- src/components/tooltip/_index.scss
- src/components/tooltip/_mixins.scss
- src/components/tooltip/_tooltip.scss
- src/components/tooltip/tooltip.js
- src/components/tooltip/tooltip_trigger.js
- src/global_styling/reset/_reset.scss
- src/global_styling/variables/_typography.scss
- Re-worked Tooltip.js to conform to component style guide
- Styling is all done except for positioning and transitions
- TooltipTrigger.js still needs to be re-worked
- Examples use EuiLink component to get styling for a trigger element.
> Tooltips Style

- src/components/code_editor/code_editor.test.js
- src/components/context_menu/context_menu_panel.test.js
- src/components/modal/confirm_modal.test.js
- src/test/find_test_subject.js
- wiki/testing.md
During a review of findTestSubject in https://github.com/elastic/kibana, it was suggested that getDOMNode be removed from findTestSubject.
> remove getDOMNode function call from findTestSubject

- src/components/health/health.js
- src/components/popover/popover.js
- src/components/table/table_pagination/table_pagination.js
This causes a bug when this dependency is consumed because files in ES5 `lib` will try to import the ES6 files in `src`. We should guard against this in the future by using something like [create-react-app's ModuleScopePlugin](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/ModuleScopePlugin.js) ([docs](https://github.com/facebookincubator/create-react-app/blob/e8a3e4b2995f4c6e49c0a7ed653a1646a7b5e515/packages/react-dev-utils/README.md#new-modulescopepluginappsrc-string-allowedfiles-string)).
> Fix import paths for EuiTable, EuiHealth, and EuiPopover.

- src/components/call_out/_call_out.scss
- src/components/description_list/_description_list.scss
- src/components/header/header_alert/_header_alert.scss
- src/components/side_nav/_side_nav_item.scss
- src/components/text/_text.scss
- src/components/toast/_toast.scss
- src/components/tooltip/_tooltip.scss
- src/global_styling/mixins/_typography.scss
- src/global_styling/variables/_typography.scss
- src/themes/k6/k6_globals.scss
Tired of dealing with our small titles being the same as our text size. Went ahead and replaced usages of $euiFontSizeM with $euiFontSize, then declared $euiFontSizeM as a slightly larger version.
Long story short, Small titles are now distinguishable from regular text. Also went and made some adjustments in the K6 thing to match better with current Kibana look and feel.
> Make EuiTitleS usable, make $euiFontSizeM a real thing

- CHANGELOG.md
- src-docs/src/services/routes/routes.js
- src-docs/src/views/steps/heading_element_steps.js
- src-docs/src/views/steps/steps.js
- src-docs/src/views/steps/steps_example.js
- src/components/index.js
- src/components/index.scss
- src/components/steps/__snapshots__/step.test.js.snap
- src/components/steps/__snapshots__/steps.test.js.snap
- src/components/steps/_index.scss
- src/components/steps/_steps.scss
- src/components/steps/index.js
- src/components/steps/step.js
- src/components/steps/step.test.js
- src/components/steps/steps.js
- src/components/steps/steps.test.js
Needs some CSS work to use variable instead of hard coded colors and sizes but otherwise is complete
> add Steps component

- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/form_control_layout.js
- src/components/form/form_control_layout/form_control_layout.test.js
- src/components/form/form_error_text/__snapshots__/form_error_text.test.js.snap
- src/components/form/form_error_text/form_error_text.test.js
- src/components/form/form_help_text/__snapshots__/form_help_text.test.js.snap
- src/components/form/form_help_text/form_help_text.test.js
Relates to #177
Adds tests for:
- FormHelpText
- FormErrorText
- FormControlLayout
> Form tests - Phase 2

- CHANGELOG.md
- src-docs/src/views/flex/flex_justify.js
- src/components/flex/__snapshots__/flex_group.test.js.snap
- src/components/flex/_flex_group.scss
- src/components/flex/flex_group.js
> Creating new CSS class: euiFlexGroup--justifyContentSpaceEvenly

- CHANGELOG.md
- src/components/form/form_error_text/_form_error_text.scss
- src/components/form/form_help_text/_form_help_text.scss
Use the mixins to generate help / error text in forms so that they have proper line-height.
> Give help / error text proper line-height

- scripts/release.sh
I think our common set up is to fork a repo and have the `origin` remote pointing to the fork and `upstream` pointing to the original. The way the script is currently written results in a divergence between the fork and the original because the new release only gets pushed to the fork, but it should be pushed to the original.
> Update release scripts to push to upstream instead of origin.

- CHANGELOG.md
- src-docs/src/views/button/button.js
- src-docs/src/views/button/button_empty.js
- src-docs/src/views/button/button_empty_flush.js
- src-docs/src/views/button/button_ghost.js
- src-docs/src/views/button/button_icon.js
- src-docs/src/views/button/button_with_icon.js
- src-docs/src/views/text/text_color.js
- src/components/flex/_flex_group.scss
- src/components/text/_text_color.scss
- src/components/text/text_color.js
Miscellaneous fixes brought to light by https://github.com/elastic/kibana/pull/15722
> Rename EuiFlexGroup classes to reflect CSS values, remove primary TextColor

- CHANGELOG.md
- package-lock.json
- package.json
- scripts/release.sh
- src-docs/src/components/guide_theme_selector/guide_theme_selector.js
- src-docs/src/views/button/button.js
- src-docs/src/views/button/button_empty.js
- src-docs/src/views/button/button_empty_flush.js
- src-docs/src/views/button/button_ghost.js
- src-docs/src/views/button/button_icon.js
- src-docs/src/views/button/button_with_icon.js
- src-docs/src/views/form/inline_form_popover.js
- src-docs/src/views/popover/popover_example.js
- src-docs/src/views/popover/popover_with_title.js
- src-docs/src/views/popover/popover_with_title_padding.js
- src-docs/src/views/text/text_color.js
- src/components/button/_index.scss
- src/components/flex/_flex_group.scss
- src/components/form/form_error_text/_form_error_text.scss
- src/components/form/form_help_text/_form_help_text.scss
- src/components/panel/_index.scss
- src/components/panel/_panel.scss
- src/components/panel/_variables.scss
- src/components/popover/_mixins.scss
- src/components/popover/_popover_title.scss
- src/components/text/_text_color.scss
- src/components/text/text_color.js
Popovers with titles no longer require padding to be manually added to the popover's child that follows the title.
The panel's padding is still applied to the entire popover. Based on the panel padding class applied to the popover, ie `.euiPanel--paddingMedium`, the title has negative margins to expand  to cover that padding amount.
The popover's title also adjusts the horizontal padding to match so that the content and the title align horizontally.
The popover's title always has some padding and only the content's padding is affected by the "none" padding property on the panel.
I, personally, feel that borders around shading are duplicative and noisy, so I also removed the bottom border from the title. I can easily change back if others disagree.
> Updating Popovers to use Panel Padding vars

- CHANGELOG.md
- src-docs/src/views/error_boundary/error_boundary.js
- src/components/error_boundary/__snapshots__/error_boundary.test.js.snap
- src/components/error_boundary/error_boundary.js
- src/components/error_boundary/error_boundary.test.js
> Support newlines in EuiErrorBoundary.

- src-docs/src/views/guidelines/writing.js
Provides descriptions and examples of how to write UI text
> Add Writing guidelines

- src/components/form/form_row/__snapshots__/form_row.test.js.snap
- src/components/form/form_row/form_row.js
- src/components/form/form_row/form_row.test.js
This PR ensures we only show form row errors if `isInvalid:true`. Right now, they show all the time.
> Only show error messages if the form row is invalid

- src/components/flex/_flex_group.scss
- src/components/flex/_flex_item.scss
Fixes https://github.com/elastic/eui/issues/247
Negative horizontal margins need to be cleared when flex groups become responsive.
> Fix responsive flex group margins

- CHANGELOG.md
- src/components/form/checkbox/__snapshots__/checkbox.test.js.snap
- src/components/form/checkbox/checkbox.js
- src/components/form/switch/__snapshots__/switch.test.js.snap
- src/components/form/switch/switch.js
Fixes https://github.com/elastic/eui/issues/225
Passes `{rest}` onto the inputs themselves rather than the wrappers. Ran some quick tests to make sure we weren't using those props against the wrappers. This is how we pass it to our text based inputs as well.
> Apply additional props to checkbox/switch inputs rather than wrappers

- CHANGELOG.md
- src-docs/src/views/accordion/accordion_form.js
- src-docs/src/views/form/disabled.js
- src-docs/src/views/form/form_controls.js
- src-docs/src/views/form/form_full_width.js
- src-docs/src/views/form/form_popover.js
- src-docs/src/views/form/form_rows.js
- src-docs/src/views/form/inline_form.js
- src-docs/src/views/form/inline_form_popover.js
- src-docs/src/views/form/inline_form_sizing.js
- src-docs/src/views/form/validation.js
- src-docs/src/views/modal/modal.js
- src/components/form/form_row/__snapshots__/form_row.test.js.snap
- src/components/form/form_row/form_row.js
- remove any duplicative `makeId()` function constructors
- remove `makeId()` from form-row id’s as form-rows will automatically use that function to create id’s
- made sure to import the `makeId` function if needed (like when creating id’s for radio/checkbox groups)
> Appending '-row' to form-row id

- CHANGELOG.md
- src/components/flex/__snapshots__/flex_group.test.js.snap
- src/components/flex/flex_group.js
The class being used in the component was not the one being used in the sass. This uses the proper one used in the sass. Since the css is not effected, this is a non-breaking change.
> Proper classname for flexGroup alignItems prop

- CHANGELOG.md
- src-docs/src/views/tabs/tabs.js
- src/components/tabs/_tabs.scss
- src/components/tabs/tab.js
Fixes https://github.com/elastic/eui/issues/179
@bmcconaghy needed this for something within Kibana index management.
> Disabled tab styling

- src/components/overlay_mask/overlay_mask.js
fixes https://github.com/elastic/eui/issues/260
Do not add event handlers to dom element with setAttribute method. Instead, add directly to dom element properties.
> OverlayMask onClick error

- CHANGELOG.md
- src-docs/src/services/routes/routes.js
- src-docs/src/views/icon/icon_colors.js
- src-docs/src/views/image/image.js
- src-docs/src/views/image/image_example.js
- src-docs/src/views/image/image_size.js
- src-docs/src/views/image/image_zoom.js
- src/components/icon/_icon.scss
- src/components/icon/icon.js
- src/components/image/__snapshots__/image.test.js.snap
- src/components/image/_image.scss
- src/components/image/_index.scss
- src/components/image/image.js
- src/components/image/image.test.js
- src/components/image/index.js
- src/components/index.js
- src/components/index.scss
Work in progress on an Image component. Need to discuss with @cchaos and figure out some stuff around sizing.
cc @alexfrancoeur @nreese. This will give you what you need for the expandable screenshots in the homepage v2.
1. Should `hasShadow` be on by default?
2. Should `allowFullScreen` be on by default?
3. Should a default `size` be set?
> Image component

- src/components/context_menu/context_menu.js
This change preserves the `onClick` handler's signature of `<T>(event: React.MouseEvent<T>) => void` even if a `panel` is given. Additionally, the event will be removed from the React event pooling system due to the async nature of the `requestAnimationFrame` callback.
> Preserve contextMenuItem onClick event handler argument

- CHANGELOG.md
- src-docs/src/views/call_out/call_out_example.js
- src-docs/src/views/call_out/info.js
- src/components/call_out/_call_out.scss
- src/components/call_out/call_out.js
For issue: https://github.com/elastic/kibana/issues/15713
The `EuiCallOut` now accepts a property of `size` which for now can only be `s` or `m` and defaults to `m`.
I realized that just adjusting the padding of the CallOut wasn't significant enough to create a more unobtrusive component. I had to adjust the heading size as well. That is why the property is not `paddingSize` but just `size` in general.
> Added a small version of the EuiCallOut

- CHANGELOG.md
- src/components/code/__snapshots__/_code_block.test.js.snap
- src/components/code/__snapshots__/code_block.test.js.snap
- src/components/icon/__snapshots__/icon.test.js.snap
This fixes some test failures caused by https://github.com/elastic/eui/pull/283, which were in turn caused by an outdated Jest cache.
> Add viewBox attribute to icon snapshots

- src-docs/src/views/text/text.js
- src-docs/src/views/text/text_color.js
- src-docs/src/views/text/text_example.js
This is just a bandaid for the underlying problem, which is that the `renderToHtml()` service uses `render` instead of `mount` to render the code snippet. Unfortunately, `mount` causes memory consumption to balloon and significantly degrade the performance of the doc site. I couldn't figure out how to free up memory using either Enzyme's `detach` and/or `unmount` methods or React's `unmountComponentAtNode` method (per [the way material-ui does it](https://github.com/mui-org/material-ui/blob/v1-beta/src/test-utils/createMount.js)). Seems related to https://github.com/airbnb/enzyme/issues/1055.
> Improve HTML snippets created for EuiText docs.

- src-docs/src/index.html
- src/global_styling/variables/_typography.scss
- src/themes/k6/k6_globals.scss
Relevant to https://github.com/elastic/kibana/issues/15814
Makes the K6 EUI theme use Open Sans. The other themes remain unaffected.
Kibana can't move over to system fonts because of issues that arise around dashboards and pdf reports (and somewhat our testing strategy). Briefly, variable fonts can cause the computed heights to get a little wobbly in repeatable elements like tables. While this isn't something we can fix 100% ever, using a singular font helps minimize the problem.
The reason we decided to go back to Open Sans is mainly for current consumer ease of use. Keeping the same font means Kibana dashboard items should retain their same computed height values as they were in 6.1.
The plan is that when we move to v7, we'll be allowed to make a more "breaking" change to these heights …
> K6 back to open sans font stack

- CHANGELOG.md
- src/test/index.js
- src/test/syncify.js
@cjcenizal recommended adding this from [this discussion](https://github.com/elastic/kibana/pull/15936#discussion_r160832170)
This helper allows you to properly test async functions that throw exceptions.
Here is working code using the helper:
```
const fn = await syncify(() => asyncFn());
expect(fn).toThrow();
```
> Add syncify test helper

- CHANGELOG.md
- src/components/code/_code_block.scss
- src/components/form/switch/switch.js
- src/components/link/_mixins.scss
- src/components/pagination/pagination.js
- src/components/table/_table.scss
- src/components/table/table_header_cell.js
- src/global_styling/reset/_reset.scss
Fixes https://github.com/elastic/eui/issues/297, https://github.com/elastic/eui/issues/268 and https://github.com/elastic/eui/issues/289, https://github.com/elastic/eui/issues/300, https://github.com/elastic/eui/issues/299
Small stylistic changes.
Pagination no long shows a single item
Table heads no longer show vague "is sortable" state. Things just have hover states or not. Only one sort shows.
Codeblock sizing increasing with additional padding per feedback form designers
> Single page pagination, button reset, table header sorting, codeblock styling

- CHANGELOG.md
- src/components/toast/_toast.scss
- src/global_styling/variables/_z_index.scss
This sets a z-index for toasts so they will appear above things like modals. cc @bmcconaghy 
TODO
> Z-index for toasts

- CHANGELOG.md
- src/components/flex/_flex_group.scss
Fixes https://github.com/elastic/eui/issues/286
IE has an issue with flex-basis when a % value isn't used.
> Fix nested flexitems in IE

- src-docs/src/views/flex/flex_nest.js
- src/components/flex/_flex_group.scss
This is more a bug that popped up in Kibana, then an EUI bug, but this makes usage a little more fault tolerant. IE11 has trouble with nesting flex groups. The 0% fix from https://github.com/elastic/eui/pull/308 actually works as it should, but Kibana was using a wrapping `display: flex` element (to provide an href) around `EuiFlexItems` which caused the groups to not size correctly when nested.
Applying a `flex-grow: 1` to groups themselves fixes that issue and causes no harm to the functionality of our system. For IE11, it'll act as you'd expect, even if you happen to add some flexy wrappers around our components.
I've tested this in every browser and also updated our docs to use a more rigorous nesting scenario (mostly wanted to make sure the bugfix didn't force growth against …
> Set FlexGroup to grow: 1 to be more friendly with IE11

- CHANGELOG.md
- src-docs/src/views/code/code_example.js
- src/components/code/__snapshots__/_code_block.test.js.snap
- src/components/code/__snapshots__/code_block.test.js.snap
- src/components/code/_code_block.js
Codeblock will only show expand when overflowHeight is set.
Codeblock forces large font / large padding when in fullscreen mode.
> Codeblock fullscreen adjustments

- src-docs/src/components/guide_section/guide_section.js
Red for required, back to strong in default color for prop.
> Styling of required props in docs

- src-docs/src/views/form/form_controls.js
- src/components/form/field_number/__snapshots__/field_number.test.js.snap
- src/components/form/field_number/field_number.js
- src/components/form/field_number/field_number.test.js
There needs to be a way to create an EuiFieldNumber with no initial value. You can not pass `undefined` in because when switching from `undefined` to numbers react throws the error `A component is changing an uncontrolled input of type number to be controlled. Input elements should not switch from uncontrolled to controlled`. The recommended react way to have an input with no value is to pass an empty string as discussed [here](https://github.com/facebook/react/issues/6222#issuecomment-194061477).
This PR updates the EuiFieldNumber component to accept an empty string or a number
> Allow EuiFieldNumber to take empty string in value prop

- CHANGELOG.md
- src/components/common.d.ts
- src/components/context_menu/index.d.ts
The TypeScript definitions for EuiContextMenu caused errors that seemed to result from usage of the `Omit<>` helper. It might be fixed with https://github.com/Microsoft/TypeScript/issues/21148, which is expected to be included in 2.7.1.
> Use more complete implementation of Omit in TypeScript definitions

- CHANGELOG.md
- src/components/form/form_row/index.d.ts
- src/components/form/index.d.ts
- src/components/form/radio/index.d.ts
- src/components/form/switch/index.d.ts
- src/components/index.d.ts
- src/components/loading/index.d.ts
- src/components/loading/loading_chart.js
- src/components/progress/index.d.ts
- src/components/progress/progress.js
This adds type definitions for
* `<EuiFormRow>`
* `<EuiRadioGroup>`
* `<EuiSwitch>`
* `<EuiLoadingSpinner>`
* `<EuiLoadingChart>`
* `<EuiProgress>`
> Add typescript definitions for more components

- src-docs/src/views/code_editor/code_editor.js
- src/components/code_editor/code_editor.js
Fixes https://github.com/elastic/kibana/issues/16139
>  Don't exit EuiCodeEditor when the ESCAPE key is being used to dismiss the autocompletion menu.

- CHANGELOG.md
- src-docs/src/views/table_of_records/full_featured.js
- src/components/table_of_records/__snapshots__/table_of_records.test.js.snap
- src/components/table_of_records/table_of_records.behavior.test.js
- src/components/table_of_records/table_of_records.js
Fixed two bugs:
1. Deleting selected items now resets the select all checkbox to an unchecked state
2. The select all checkbox only becomes checked when all selectable rows are checked, not just some of them
> Fix EuiTableOfRecords selection bug when selected items are deleted

- CHANGELOG.md
- src/components/code/_code_block.js
- src/components/context_menu/context_menu_panel.js
- src/components/flyout/flyout.js
- src/components/image/image.js
- src/components/modal/modal.js
- src/components/popover/popover.js
Whenever we handle a keydown event, we should properly prevent it's default behavior and also stop propagation to parent nodes. Otherwise the same Escape keypress could close multiple components.
I have the case where I have an `EuiCodeBlock` in an `EuiFlyout`. If you now open the code block fullscreen and press <kbd>Escape</kbd> both components will close, because the `EuiCodeBlock` doesn't stop propagation when handling its close event.
That same will be true for any of these components if you place them in something else, that tries to handle the same keypress. In general: if we handle a keyevent we should prevent it's default behavior and stop its propagation.
> Properly cancel keydown events after handling

- CHANGELOG.md
- src/components/flex/_flex_group.scss
One of the flex group classes was mis-named, so you couldn't actually set `align-items` to `flex-start.
> Fix flex group class name

- CHANGELOG.md
- src-docs/src/views/steps/steps.js
- src-docs/src/views/steps/steps_complex.js
- src-docs/src/views/steps/steps_example.js
- src-docs/src/views/steps/steps_horizontal.js
- src/components/index.js
- src/components/steps/__snapshots__/steps_horizontal.test.js.snap
- src/components/steps/__snapshots__/sub_steps.test.js.snap
- src/components/steps/_index.scss
- src/components/steps/_steps.scss
- src/components/steps/_steps_horizontal.scss
- src/components/steps/_sub_steps.scss
- src/components/steps/index.js
- src/components/steps/step_horizontal.js
- src/components/steps/steps_horizontal.js
- src/components/steps/steps_horizontal.test.js
- src/components/steps/sub_steps.js
- src/components/steps/sub_steps.test.js
- src/global_styling/mixins/_index.scss
- src/global_styling/mixins/_states.scss
- src/global_styling/mixins/_typography.scss
For use when forms/setup instruction can and should be split into multiple pages.
cc @gjones 
---
By complex, it just means that it allows for a subset of content to be contained in a shaded area to distinguish it between the rest of the step content.
cc @alexfrancoeur
> Horizontal & Complex Steps

- CHANGELOG.md
- src-docs/src/views/toast/danger.js
- src-docs/src/views/toast/info.js
- src-docs/src/views/toast/success.js
- src-docs/src/views/toast/warning.js
- src/components/toast/__snapshots__/global_toast_list.test.js.snap
- src/components/toast/__snapshots__/toast.test.js.snap
- src/components/toast/_toast.scss
- src/components/toast/toast.js
Prevents bugs like this:
Fixed:
> Prevent EuiToast text from overflowing.

- CHANGELOG.md
- src-docs/src/views/form/form_controls_readonly.js
- src-docs/src/views/form/form_example.js
- src/components/form/_index.scss
> Adding `readOnly` prop styles to form inputs

- CHANGELOG.md
- src/components/steps/_sub_steps.scss
Fixes #395
I see how those SASS functions work now.
> Using tintOrShade for subStep background color

- CHANGELOG.md
- src/components/health/index.d.ts
- src/components/index.d.ts
This adds typescript definitions for the `<EuiHealth>` component.
> Add typescript definitions for `<EuiHealth>`

- CHANGELOG.md
- src-docs/src/components/guide_section/guide_section.js
- src-docs/src/views/tables/actions/actions.js
- src-docs/src/views/tables/basic/basic.js
- src-docs/src/views/tables/paginated/paginated.js
- src-docs/src/views/tables/selection/selection.js
- src-docs/src/views/tables/sorting/sorting.js
This will make it easier for people to copy/paste examples.
>  Use a regex to swap out EUI import statements in code examples so that they look like they're importing from the EUI node module.

- CHANGELOG.md
- src/components/progress/_progress.scss
Fixes #362 
Issue had to do with `background-color: transparent;` of fixed style taking precedence over color styles:
Fix simply reorders the styles:
> Reorder selectors to fix fixed progress bar in Firefox

- CHANGELOG.md
- src/components/table/_index.scss
- src/components/table/_table.scss
Closes https://github.com/elastic/eui/issues/389
This removes some finicky code that tried to make tables widths a bit prettier, but came with some bad drawbacks.
Moving to table-layout: fixed seems to solve most of our problems, though it might require people to hand touch cell widths a bit more (which I think is fine).
> table-layout: fixed. Remove 20px max-width

- src/components/search_bar/query/default_syntax.js
- src/components/search_bar/query/default_syntax.test.js
- relaxed the support for phrases - we now accept spaces anywhere in the phrase as long as it contains at least one term - the phrases are trimmed
- it's now possible to have a single term OR clause
> Fixed search bar query parser

- .gitignore
- CHANGELOG.md
- src-docs/src/routes.js
- src-docs/src/views/delay_hide/delay_hide.js
- src-docs/src/views/delay_hide/delay_hide_example.js
- src/components/delay_hide/delay_hide.js
- src/components/delay_hide/delay_hide.test.js
- src/components/delay_hide/index.js
- src/components/index.js
Closes #382 
This component will conditionally show/hide a child component. It will ensure that the child is visible for at least 1000ms (default). This avoids UI glitches with loading spinners and other elements that are rendered conditionally.
```
<EuiDelayHide hide={!isLoading} render={() => <div>Loading...</div>} />
```
`EuiDelayHide` uses a [render props](https://reactjs.org/docs/render-props.html) to render the child component.
TODO:
> Add EuiDelayHide component

- CHANGELOG.md
- src-docs/src/views/card/card.js
- src-docs/src/views/panel/panel.js
- src/components/card/__snapshots__/card.test.js.snap
- src/components/card/_card.scss
- src/components/card/card.js
- src/components/panel/_index.scss
- src/components/panel/_mixins.scss
- src/components/panel/_panel.scss
EuiPanel now has a mixin that can be used by any component. EuiCard uses this mixin to inherit the styles of EuiPanel but doesn’t have specificity/order issues.
Fixes #408
> Changing the way EuiCard inherits EuiPanel

- src/services/sort/comparators.js
- src/services/sort/comparators.test.js
fixes https://github.com/elastic/eui/issues/442 by adding support for nested fields
> Comparators.property to support nested properties

- CHANGELOG.md
- src/components/side_nav/__snapshots__/side_nav.test.js.snap
- src/components/side_nav/__snapshots__/side_nav_item.test.js.snap
- src/components/side_nav/_side_nav_item.scss
- src/components/side_nav/side_nav_item.js
> Side nav items only behave clickable if they are

- CHANGELOG.md
- src-docs/src/views/form/form_rows.js
- src/components/form/select/select.js
Apparently React doesn’t use this property and uses `value`/`defaultValue` similar to other inputs.
> Fix error stemming from `selected` prop on `EuiSelect`

- src/components/code/_code_block.js
The large font size was driving me a little nuts because I kept trying to expand the code block to see more code, but the larger font-size meant I just ended up seeing the same amount of code, only larger!
> Make full screen code block use the same font-size on the original code block

- src-docs/src/views/color_picker/color_picker_example.js
eui/src-docs/src/views/color_picker/color_picker_example.js
Line 44 in c19a9b6
title: 'Color Picker without a color labe', 
"labe" instead of "label"
Misspelling #356
> fixed typo from 'labe' to 'label'  Misspelling #356

- src-docs/src/views/flex/flex_example.js
- src-docs/src/views/panel/panel_example.js
- src-docs/src/views/table_of_records/table_of_records_example.js
Fix links that broke from sidebar reorganization (#428).
> Fix broken links in docs

- src-docs/src/views/tables/in_memory/in_memory_search_callback.js
- src-docs/src/views/tables/in_memory/in_memory_search_callback_section.js
- src-docs/src/views/tables/in_memory/index.js
- src-docs/src/views/tables/in_memory/props_info.js
- src-docs/src/views/tables/tables_example.js
- src/components/basic_table/in_memory_table.js
I added an example in this PR in which the input handler is debounced so that the search is executed once you're done typing, instead of executed as you type. I'd like to improve this UX so that we can bypass the debounce and execute the search immediately if the user hits ENTER.
I think I'll implement this in a separate PR, in which we change `EuiFieldSearch` to accept an `onChange` prop (called as you type) and an `onSearch` prop (called when you hit enter).
> Add onChange callback to search config object.

- CHANGELOG.md
- src-docs/src/views/tables/in_memory/in_memory_selection.js
- src-docs/src/views/tables/in_memory/props_info.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Currently `EuiInMemoryTable` uses the first element in `pageSizeOptions` as the initial page size. This allows a different initial page size to be specified.
> Add ability to specify default page size for EuiInMemoryTable

- src-docs/src/views/tables/data_store.js
All rows are currently showing for paginated basic table examples, when on page 1 (broke from #449).
> Fix all table rows showing on page 1 for paginated table examples

- package.json
Without the `GID` being correctly set npm/yarn was setting the ownership of the `node_modules` directory to the root user. This was causing the build system to fail when attempting to clean up this directory. 
```
-rw-r--r--    1 jenkins jenkins 2.2K Feb 27 14:56 README.md
-rw-r--r--    1 jenkins jenkins  103 Feb 27 14:56 .npmignore
-rw-r--r--    1 jenkins jenkins    4 Feb 27 14:56 .node-version
-rw-r--r--    1 jenkins jenkins  553 Feb 27 14:56 LICENSE
-rw-r--r--    1 jenkins jenkins  113 Feb 27 14:56 .gitignore
-rw-r--r--    1 jenkins jenkins  266 Feb 27 14:56 .eslintrc.json
-rw-r--r--    1 jenkins jenkins 1.7K Feb 27 14:56 CONTRIBUTING.md
-rw-r--r--    1 jenkins jenkins  759 Feb 27 14:56 .babelrc
drwxr-xr-x    5 jenkins jenkins 4.0K Feb 27 14:56 generator-eui
drwxr-xr-x    2 jenkins …
```
> Set GID to build users group id so that npm doesn't default to the root GID

- src-docs/src/views/search_bar/search_bar.js
- src-docs/src/views/tables/in_memory/in_memory_selection.js
- src/components/search_bar/__snapshots__/search_bar.test.js.snap
- src/components/search_bar/search_bar.js
- src/components/search_bar/search_bar.test.js
Let's compare and contrast this with the config-object-based approach of https://github.com/elastic/eui/pull/452:
```js
const toolbar = {
leftTools: [
{
type: 'button',
name: 'Delete Items',
icon: 'trash',
color: 'danger',
available: (table) => table.selection && table.selection.length > 0,
onClick: (table) => {
store.deleteUsers(...table.selection.map(user => user.id));
table.refresh();
}
}
],
search: {
box: {
incremental: this.state.incremental
},
filters: !this.state.filters ? undefined : [
{
type: 'is',
field: 'online',
name: 'Online',
negatedName: 'Offline'
},
{
type: 'field_value_selection',
field: 'nationality',
name: 'Nationality',
multiSelect: false,
options: store.countries.map(country => ({
value: country.code,
name: country.name,
view: `${country.flag} ${country.name}`
}))
}
] …
```
> Provide tools to search bar as nodes

- CHANGELOG.md
- src-docs/src/views/pagination/customizable_pagination.js
- src/components/bottom_bar/bottom_bar.js
- src/components/bottom_bar/bottom_bar.test.js
- src/components/button/_index.scss
* Fixes #49 by adding `EuiPortal` to `EuiBottomBar`
* Fixes #45 by removing an unecessary prop on docs.
* Fixes #217 by upping the disabled button contrast in the dark theme.
> Misc. small fixes against outstanding issues

- CHANGELOG.md
- src/components/form/select/__snapshots__/select.test.js.snap
- src/components/form/select/select.js
- src/components/form/select/select.test.js
```
Warning: Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled select element and remove one of these props.
```
React throws the above if an `Input` element contains both `value` and `defaultValue` property. 
This PR updates EuiSelect to ensure `defaultValue` is never set when `value` is provided.
> do not set both value and defaultValue on select

- src-docs/src/components/guide_page/guide_page_chrome.js
Clicking a nav item in the side nav will now clear the search and toggle off the mobile menu. This also works in desktop rez as well.
Makes the mobile menu and search in general muuuuuch more usable.
> Clear search, reset nav display on nav item clicks

- CHANGELOG.md
- src/components/horizontal_rule/_horizontal_rule.scss
- src/components/panel/panel.js
- Don't propagate a null `onClick` on EuiPanels. This helps avoid noise in Jest snapshots.
- Use 1.1px for the default horizontal line height, in order to work around strange Chrome height calculations.
> Misc fixes

- CHANGELOG.md
- src-docs/src/views/home/home_view.js
- src/components/card/card.js
- src/components/flex/_flex_item.scss
When we added the `responsive={false}` prop to `EuiFlexGroup` we indirectly broke responsiveness to `EuiFlexGrid` which should _always_ be responsive. Added some CSS to target it specifically so it now works on mobile how we'd expect.
Also threw in a small fix for @bmcconaghy where the proptypes on `EuiCard` were too strict.
> Fix FlexGrid responsiveness

- CHANGELOG.md
- src-docs/src/views/modal/modal_example.js
- src-docs/src/views/modal/overflow_test.js
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/modal/__snapshots__/modal.test.js.snap
- src/components/modal/_modal.scss
- src/components/modal/modal.js
[Demonstration gif](http://snid.es/1W2c0k3f1b1l)
Fixes https://github.com/elastic/eui/issues/48
Makes the following changes:
1. `EuiModal` now has a max-height on desktop. `EuiBody` will overflow as needed if the content gets too long. This fixes a possible bug they had.
2. `EuiModal` now flips into a fixed position mode when on mobile screens. This treats it more like a takeover overflow.
3. Both of these concepts are similar to how we're handling `EuiFlyout`.
4. Adds an always there close button in the header.
> Modal responsive refactor

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.test.js
- src/components/search_bar/__snapshots__/search_bar.test.js.snap
- src/components/search_bar/__snapshots__/search_box.test.js.snap
- src/components/search_bar/search_bar.test.js
- src/components/search_bar/search_box.js
Allow consumers of `EuiInMemoryTable` a way to pass attributes to `EuiFieldSearch` used in `EuiSearchBox `
> EuiSearchBox - pass rest to EuiFieldSearch

- CHANGELOG.md
- src-docs/src/views/tables/in_memory/in_memory_selection.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
- src/components/basic_table/in_memory_table.js
Kibana needs the ability to pass in html nodes for the `noItemsMessage` property for displaying nice messages that give users calls to action to create items when none exist.
> [BasicTable] - allow noItemMessage to be node

- CHANGELOG.md
- src/components/page/page_content/_page_content.scss
This fixes a very old bug introduced when `EuiPanel` took on flex abilities based upon if it was placed in a flex item. That change broke a couple instances of positioning in `EuiPage`, where panels nest inside of flex layouts.
This change sets the grow to 0 for `EuiPageCOntent`, which itself is an `EuiPanel`.  The specificity is changed so we don't need to resort to !important tags.
> Fix EuiPageContent centering

- CHANGELOG.md
- src/components/button/button.js
- src/components/button/button_empty/button_empty.js
- src/components/button/button_icon/button_icon.js
- src/components/modal/confirm_modal.js
- src/components/modal/confirm_modal.test.js
Fixes https://github.com/elastic/eui/issues/526
> Add buttonRef props to all buttons, and fix bug with autoFocused buttons on EuiConfirmModal

- package.json
By default docker will use whatever image is available locally if the node:8 image already exists. This meant that different versions of npm/node were being run depending on which jenkins worker picked up the job.
> Always pull the latest docker image (node:8) before running the tests in docker

- CHANGELOG.md
- src/components/health/__snapshots__/health.test.js.snap
- src/components/health/health.js
Sets `responsive={false}` on the `EuiHealth` component.
> EuiHealth responsive fix

- CHANGELOG.md
- src-docs/src/views/side_nav/side_nav_example.js
- src-docs/src/views/side_nav/side_nav_force_open.js
- src/components/side_nav/__snapshots__/side_nav.test.js.snap
- src/components/side_nav/_side_nav_item.scss
- src/components/side_nav/side_nav.js
- src/components/side_nav/side_nav.test.js
- src/components/side_nav/side_nav_item.js
Fixes #497.
`items` passed to `EuiSideNav` can now receive an `item.forceOpen` boolean property, which forces that particular nav item (and all of its parents) to render in the "open" state. `.forceOpen` can be selectively applied to individual items, or can be applied to every item in the tree to force the entire tree to be open. This allows us to draw attention and convenience to certain navigation levels so that they are more easily discoverable by the user.
I chose the name `forceOpen` because my first choice, `isOpen`, when set to `undefined`, shadows the `isOpen` prop passed to `EuiSideNavItem`, which ironically can force the entire navigation tree closed. For example, if you use a `createItem()` function to create individual navigation items, it might include a line like this:
``` …
```
> Add ability to force open EuiSideNav items.

- CHANGELOG.md
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
- src/components/basic_table/in_memory_table.js
When sorting is not configured on the table, the `sortable` property on the configured column shouldn't really take effect.
Fixes: #440
> [EuiBasicTable] Fix sorting bug

- CHANGELOG.md
- src-docs/src/views/form/form_controls.js
- src/components/form/checkbox/__snapshots__/checkbox.test.js.snap
- src/components/form/checkbox/_checkbox.scss
- src/components/form/checkbox/checkbox.js
- src/components/form/radio/__snapshots__/radio.test.js.snap
- src/components/form/radio/_radio.scss
- src/components/form/radio/radio.js
Fixes #541 
@arkwright: Basically using your solution here but just the opposite and appending a `--noLabel` selector to the `--inList` selector.
> Using the same `--inList` styles for checkboxes and radios without labels

- CHANGELOG.md
- src/global_styling/reset/_reset.scss
Fixes https://github.com/elastic/kibana/issues/16662
This removes font-smoothing for webkit browsers as a base reset. @cchaos and I tend to prefer font-smoothing on, and it can be very subjective, but according to https://caniuse.com/#feat=font-smooth
> Though present in early (2002) drafts of CSS3 Fonts, font-smooth has been removed from this specification and is currently not on the standard track.
We should stick to standards when we can. cc @elastic/eui-design
> Remove font smoothing from reset

- CHANGELOG.md
- src-docs/src/views/tables/in_memory/in_memory.js
- src-docs/src/views/tables/in_memory/props_info.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Fixes #464
Allows user to specify initial sorting by passing an object to the `sorting` prop. `sorting` will still take boolean values. Passing an object will enable sorting (same as using `sorting={true}`). The object shape is the same as the sorting prop for `EuiBasicTable`.
> Add ability to specify initial sorting to EuiInMemoryTable

- CHANGELOG.md
- src/components/tool_tip/tool_tip.js
> Fix EuiToolTip bug which caused the tooltip to hide when moving the mouse around inside of the trigger element

- CHANGELOG.md
- src-docs/src/views/header/header_user_menu.js
- src-docs/src/views/modal/confirm_modal.js
- src-docs/src/views/modal/modal.js
- src-docs/src/views/modal/modal_example.js
- src-docs/src/views/modal/overflow_test.js
- src/components/button/button_empty/_button_empty.scss
- src/components/flex/__snapshots__/flex_group.test.js.snap
- src/components/flex/_flex_group.scss
- src/components/flex/flex_group.js
- src/components/flyout/_flyout_header.scss
- src/components/form/switch/_switch.scss
- src/components/header/__snapshots__/header_notification.test.js.snap
- src/components/header/_header_notification.scss
- src/components/header/_index.scss
- src/components/header/header_notification.js
- src/components/header/header_notification.test.js
- src/components/header/index.js
- src/components/index.js
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/modal/_modal.scss
- src/components/modal/confirm_modal.js
- src/components/overlay_mask/_overlay_mask.scss
- src/components/pagination/_pagination_button.scss
- src/components/pagination/pagination_button.js
- src/components/tabs/_tabs.scss
- src/global_styling/mixins/_shadow.scss
1. Adjusting modals for mobile
- Added drop shadows for overflows
- Added padding to header to accomodate close button
- Modal buttons should be normal size (not small) (docs only)
2. Fixes #334 - Lightening overlay color in dark theme
3. Fixes #520 Added a type prop to `EuiConfirmModal`
- Defaults to ‘confirm’ (positive/neutral), but can be ‘destroy’.
1. Overflowing tabs now scroll horizontally
1. Fixes #537 - Removing padding from *both* sides of `EuiEmptyButton` when flush
2. Fixes #474 - Added disabled prop to placeholder (ellipses) pagination
3. Fixes #423 - Added ‘baseline’ as option to `EuiFlexGroup`’s `alignItems` prop
- _’normal’ doesn’t do anything_
4. Fixes #87 - Converted `.euiHeader__notification` into `EuiHeaderNotification`
> Some random fixes

- CHANGELOG.md
- src/components/button/button_empty/_button_empty.scss
Fixed a bug where `EuiButtonEmpty` would offer a white background on hover when it was disabled, even when there was no such background transition on hover when the buttons are not disabled.
> Fixed a bug with `EuiButtonEmpty` disabled state

- CHANGELOG.md
- src-docs/src/views/tables/actions/actions.js
- src-docs/src/views/tables/basic/basic.js
- src-docs/src/views/tables/custom/custom.js
- src-docs/src/views/tables/data_store.js
- src-docs/src/views/tables/in_memory/in_memory.js
- src-docs/src/views/tables/in_memory/in_memory_search.js
- src-docs/src/views/tables/in_memory/in_memory_search_callback.js
- src-docs/src/views/tables/in_memory/in_memory_selection.js
- src-docs/src/views/tables/paginated/paginated.js
- src-docs/src/views/tables/selection/selection.js
- src-docs/src/views/tables/sorting/sorting.js
- src/components/basic_table/basic_table.js
- src/components/table/_table.scss
This should address some layout problems on https://github.com/elastic/kibana/pull/17344.
- `EuiBasicTable` now supports explicitly setting `truncateText` and `textOnly` on column definitions, and supports passing through unrecognized props to the cell (e.g. `data-test-subj`).
- Updated CSS so that long single-word cell content will break and wrap mid-word.
> Improve EuiBasicTable cell configuration and EuiTable cell content CSS

- src-docs/src/components/guide_components.scss
- src-docs/src/components/guide_rule/_guide_rule.scss
- src-docs/src/components/guide_rule/_guide_rule_description.scss
- src-docs/src/components/guide_rule/_guide_rule_title.scss
- src-docs/src/components/guide_rule/guide_rule.js
- src-docs/src/components/guide_section/_guide_section.scss
- src-docs/src/views/guidelines/button.js
- src-docs/src/views/guidelines/colors.js
- src-docs/src/views/guidelines/modals.js
- src-docs/src/views/guidelines/toasts.js
- src-docs/src/views/guidelines/writing.js
- src/components/text/_text.scss
- Smaller and lighter instruction text
- Better spacing on guide rules/examples
- Abs positioning on "go to component" button
_I'm on the fence about keeping the max-width on paragraphs in since we are now max-width-ing the entire page (so I left that in the css just commented for now). While I do think a shorter line length is more readable, it seemed like we were adding arbitrary stops at too many points._
_If we decide to un-max-width the entire page (#571) then we can just uncomment that line and all the line lengths should be good._
> Tweaking Documentation styles

- CHANGELOG.md
- src-docs/src/views/tool_tip/icon_tip.js
- src-docs/src/views/tool_tip/tool_tip_example.js
- src/components/tool_tip/__snapshots__/icon_tip.test.js.snap
- src/components/tool_tip/icon_tip.js
- src/components/tool_tip/icon_tip.test.js
`color` is now a prop for `EuiIconTip` to specify icon color.
> Allow color to be passed in for EuiIconTip

- CHANGELOG.md
- src/components/search_bar/query/default_syntax.js
- src/components/search_bar/query/default_syntax.test.js
Due to their commonality in object names, made it possible to use hyphens without escaping. The only caveat here is that a search term or a field name starts with a hyphen, then it'll have to be escaped with `\`.
Fixes: #577
> [EuiSearchBar] relaxed syntax around hyphens

- CHANGELOG.md
- src-docs/src/views/tables/expanding_rows/expanding_rows.js
- src-docs/src/views/tables/expanding_rows/expanding_rows_section.js
- src-docs/src/views/tables/expanding_rows/index.js
- src-docs/src/views/tables/tables_example.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
Fixes https://github.com/elastic/eui/issues/466
> Add support for expandable rows to EuiBasicTable.

- CHANGELOG.md
- src-docs/src/views/search_bar/search_bar.js
- src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.js.snap
- src/components/search_bar/query/__snapshots__/ast_to_es_query_string.test.js.snap
- src/components/search_bar/query/ast_to_es_query_dsl.js
- src/components/search_bar/query/ast_to_es_query_dsl.test.js
- src/components/search_bar/query/ast_to_es_query_string.js
- src/components/search_bar/query/ast_to_es_query_string.test.js
- src/components/search_bar/query/date_format.js
- src/components/search_bar/query/query.js
Example:
```js
const query = Query.parse(`john group:(eng or "marketing org") -date:'2004-03' -is:active`);
console.log(Query.toEsQueryString(query));
```
the above logs:
```
+john +(group:eng OR group:"marketing org") -date:(>=2004-03 AND <2004-04) +active:false
```
> [SearchBar] Added support for emitting a Query as an Elasticsearch query string

- CHANGELOG.md
- docs/index.html
- src-docs/src/index.html
- src/global_styling/variables/_typography.scss
- src/themes/k6/k6_globals.scss
Fixes https://github.com/elastic/eui/issues/568 on the EUI side. Will also require a Kibana PR.
Goes along with https://github.com/elastic/kibana/pull/17467 on the Kibana side.
cc @jen-huang, @cchaos 
This was only happening in the K6 theme. In EUI it was happening because we weren't pulling the weights we needed down. In Kibana, the weights are delivered with Kibana, so will need to be manually added. I'll add a separate PR for that.
@cchaos I also upped the medium weight to 600 because ~~500 wasn't strong enough for the labels~~ 500 isn't available in Open Sans, and the 700 was a little too bold. This seemed to be the most consistent value across our themes.
EUI native
EUI K6
> Font weight fix for k6

- src/components/header/__snapshots__/header.test.js.snap
- src/components/header/__snapshots__/header_logo.test.js.snap
- src/components/header/header.test.js
- src/components/header/header_alert/__snapshots__/header_alert.test.js.snap
- src/components/header/header_alert/header_alert.js
- src/components/header/header_alert/header_alert.test.js
- src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.js.snap
- src/components/header/header_breadcrumbs/header_breadcrumbs.test.js
- src/components/header/header_logo.test.js
- src/components/header/header_section/__snapshots__/header_section.test.js.snap
- src/components/header/header_section/__snapshots__/header_section_item.test.js.snap
- src/components/header/header_section/__snapshots__/header_section_item_button.test.js.snap
- src/components/header/header_section/header_section.test.js
- src/components/header/header_section/header_section_item.test.js
- src/components/header/header_section/header_section_item_button.test.js
Continuing to add more unit tests to EUI, in this case, I changed some elements in header_alert from `p` to `div` so that React (and HTML, for that matter) would allow a broader range of children (e.g. `h1` elements).
> Add more unit tests to the header component

- src/components/button/_button.scss
I busted hover states for disabled buttons in https://github.com/elastic/eui/pull/603
This adds the appropriate level of specificity to make sure disabled buttons don't get backgrounds regardless of their variation.
The black background just shows that it's hollow and not a transparent white.
> Apply more specificity to fix disabled states

- CHANGELOG.md
- src-docs/src/components/guide_components.scss
- src-docs/src/views/guidelines/colors.js
- src/components/button/_button.scss
- src/components/button/_index.scss
- src/components/context_menu/_context_menu_panel.scss
- src/components/flyout/_flyout.scss
- src/components/form/_index.scss
- src/components/key_pad_menu/_key_pad_menu.scss
- src/components/modal/_modal.scss
- src/components/panel/_mixins.scss
- src/components/panel/_variables.scss
- src/components/steps/_steps_horizontal.scss
- src/components/toast/_toast.scss
- src/global_styling/mixins/_shadow.scss
- src/global_styling/variables/_colors.scss
- src/themes/eui/eui_colors_dark.scss
- src/themes/k6/k6_colors_dark.scss
- Shadow mixins now accept optional color and opacity arguments
- Slight difference on small shadows
- Button shadows now get a tint of the button’s main color
- Small overlaying comps have slightly dark shadows but the also not bleed horizontally (not just below)
- Large overlaying comps (like Modals) have much more pronounced shadows. Also had to alter the border colors a bit on these so that there is a crisp line before the shadow starts. With the default border it was fuzzy.
- Had to add some new variables pertaining to shadows for better theming control.
**Primary button hover state.** See the slight blue tint to from the primary style.
**Context menu/popover** See the shadow is visible on the sides as well.
**Modals** Large stylized shadow
**And in dark mode too**
> Changing up the look of box-shadows

- CHANGELOG.md
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
@nreese Could you test this and verify this fixes your issue?
Fixes https://github.com/elastic/eui/issues/601
> Update EuiComboBox to match options list width to the input width.

- CHANGELOG.md
- src-docs/src/views/toast/toast_example.js
- src/components/toast/_global_toast_list.scss
With the new shadows, the toasts would look weird on hover because the overflow would cut them off. This adds some left padding so they will continue to show.
> Fix hover shadow on toasts

- CHANGELOG.md
- src/components/index.d.ts
- src/components/portal/index.d.ts
- src/components/text/index.d.ts
- src/components/title/index.d.ts
- src/services/index.d.ts
- src/services/popover/index.d.ts
This adds type definitions for the components
* `<EuiPortal>`
* `<EuiText>`
* `<EuiTitle>`
and the service
* `calculatePopoverPosition`
> Add TypeScript types for portal, text, title components, popover service

- CHANGELOG.md
- src/components/form/_mixins.scss
- src/components/form/checkbox/_checkbox.scss
- src/components/form/file_picker/_file_picker.scss
- src/components/form/radio/_radio.scss
- src/components/form/switch/_switch.scss
This PR mostly grays out labels when components are disabled, so that it's a bit more obvious that they're disabled.
File Picker Before/After
Select Before/After
Checkbox Before/After
Radio Before/After
Switch Before/After
Textarea Before/After
Password Before/After (all text fields change the same way)
> Gray out labels when disabled

- CHANGELOG.md
- src-docs/src/views/combo_box/combo_box.js
- src/components/combo_box/combo_box_options_list/_combo_box_option.scss
- src/components/combo_box/combo_box_options_list/combo_box_option.js
I am looking into the feasibility of replacing react-select with EuiComboBox in Kibana Visual Builder. One missing feature is the ability to disable options.
This PR just adds a disabled prop to `EuiComboBoxOption`
> add disabled prop to EuiComboBoxOption

- src/components/search_bar/query/date_format.test.js
Extracted from https://github.com/elastic/eui/pull/655
> Skip flaky date parsing tests

- src-docs/src/components/guide_page/guide_page_chrome.js
- src/components/search_bar/query/date_format.test.js
This small change turns `<button>` into `<a>` for side navigation links in the documentation site. The reasoning behind this is that anchor tags can be cmd+clicked to open in a new tab, have their URL copied, be right clicked, show the URL, and are generally good at UX for links, whereas buttons are none of that.
We can't do the same for sub-sections because we don't have unique identifiers for these, so we'll have to stick to buttons for the time being, but at least it's a step in the right direction.
> Side-nav routes on the docs site should be anchors, not buttons.

- CHANGELOG.md
- package.json
- scripts/compile-scss.js
- src/components/key_pad_menu/_index.scss
- src/index.d.ts
- src/themes/index.d.ts
- wiki/consuming.md
- yarn.lock
This PR enhances the script `scripts/compile-scss.js` to export also extract and export the sass variables from each theme into a corresponding json file in `dist/eui_theme_${THEME}.json`. The values in this file are in a format suitable for use in styled-components themes to keep the scss files as a single source of truth.
It also converts the script to use async I/O to improve parallelism.
The export of ready-to-use themes could be considered in a subsequent step.
> Export scss vars as json during compilation

- CHANGELOG.md
- CONTRIBUTING.md
#657 introduced some goofy grammar and got merged without review. Reverting for the moment and fixing the changelog to use H2s. If we go with past tense that's fine, but we'll prolly need to do some deeper rewriting to make it more readable.
cc @bevacqua @cchaos 
Closes https://github.com/elastic/eui/issues/659
> Manual revert of #657, changelog to h2s

- CHANGELOG.md
- src/components/combo_box/combo_box.js
The combo box selection list should be automatically closed when an item is selected in `singleSelection` mode.
> Close singleSelection EuiComboBox select list when item is selected

- CHANGELOG.md
- src-docs/src/views/steps/steps_horizontal.js
- src/components/steps/__snapshots__/step_horizontal.test.js.snap
- src/components/steps/__snapshots__/steps_horizontal.test.js.snap
- src/components/steps/_steps_horizontal.scss
- src/components/steps/step.test.js
- src/components/steps/step_horizontal.js
- src/components/steps/step_horizontal.test.js
- src/components/steps/steps_horizontal.test.js
I think we can handle variable-length text more gracefully by wrapping it instead of truncating it. This way the text is still legible and the UI remains usable. As consumers we'll have to be careful about choosing copy which isn't unreasonably long.
> Wrap EuiHorizontalStep titles instead of truncating them.

- CHANGELOG.md
- src-docs/src/views/text/text_example.js
- src-docs/src/views/text/text_width.js
- src/components/call_out/__snapshots__/call_out.test.js.snap
- src/components/card/__snapshots__/card.test.js.snap
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/text/__snapshots__/text.test.js.snap
- src/components/text/_text.scss
- src/components/text/text.js
- src/components/text/text.test.js
- src/components/toast/__snapshots__/global_toast_list.test.js.snap
- src/components/toast/__snapshots__/toast.test.js.snap
The default is a nice improvement, but sometimes we may need an escape hatch.
> Add grow prop to EuiText.

- CHANGELOG.md
- src-docs/src/views/tables/actions/actions.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/__snapshots__/collapsed_item_actions.test.js.snap
- src/components/basic_table/__snapshots__/custom_item_action.test.js.snap
- src/components/basic_table/__snapshots__/default_item_action.test.js.snap
- src/components/basic_table/__snapshots__/expanded_item_actions.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/collapsed_item_actions.js
- src/components/basic_table/collapsed_item_actions.test.js
- src/components/basic_table/custom_item_action.js
- src/components/basic_table/custom_item_action.test.js
- src/components/basic_table/default_item_action.js
- src/components/basic_table/default_item_action.test.js
- src/components/basic_table/expanded_item_actions.js
- src/components/basic_table/expanded_item_actions.test.js
- src/components/table/_table.scss
- src/components/table/table_row_cell.js
Fixes #441 
This PR fixes unnecessary re-rendering of the entire `EuiBasicTable` component upon hovering over table rows by:
* removing `hoverRow` state on `EuiBasicTable`
* adding the class `.euiTableCellContent--showOnHover` to `EuiTableRowCell` when prop `showOnHover` is true
The `.euiTableCellContent--showOnHover` class has styling rules to hide its content by default and show it when its parent `.euiTableRow` is hovered.
Normal/keyboard navigation for single and multiple action column remains the same (no functionality changes).
> Fix table re-rendering by showing/hiding actions column via CSS instead

- CHANGELOG.md
- src-docs/src/views/steps/status.js
- src-docs/src/views/steps/steps_example.js
- src/components/index.js
- src/components/steps/__snapshots__/step.test.js.snap
- src/components/steps/__snapshots__/steps.test.js.snap
- src/components/steps/_steps.scss
- src/components/steps/index.js
- src/components/steps/step.js
- src/components/steps/steps.js
Closes https://github.com/elastic/eui/issues/667
Adds a status prop from `EuiSteps` and `EuiStep`. This allows it to have some different styling for last item checks. Pretty sure this styling originally came from @formgeist so I kept it as is and just added a bit of animation.
@nreese if you're in a hurry with this, we can merge it, but expect @cchaos to possibly tweak the styling later.
> Step status props

- src/components/bottom_bar/bottom_bar.js
Fixes https://github.com/elastic/eui/issues/663
`EuiBottomBar` will now apply a bottom padding to the body that is the size of the bar itself. Since a user might also have fixed controls (like the docs sidenav for example), I made it so you can also attach a `bodyClassName` to the body when it is mounted. This should allow people to make any sort of style adjustments they need when the bar pops up.
> Bottom bar padding and optional body class

- CHANGELOG.md
- src/components/card/__snapshots__/card.test.js.snap
- src/components/card/card.js
- src/components/card/card.test.js
EuiCard icon prop overrides user provided className with `euiCard__icon`. This PR fixes the logic to add `euiCard__icon` to any user provided classNames.
> EuiCard icon prop preserve className

- CHANGELOG.md
- package.json
- src-docs/src/views/combo_box/combo_box_example.js
- src-docs/src/views/combo_box/render_option.js
- src-docs/src/views/combo_box/virtualized.js
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_options_list/_combo_box_option.scss
- src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
- src/components/combo_box/combo_box_options_list/_combo_box_title.scss
- src/components/combo_box/combo_box_options_list/combo_box_option.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
- src/components/combo_box/matching_options.js
- yarn.lock
fixes https://github.com/elastic/eui/issues/651
paired with @cjcenizal to convert EuiComboBox rendering to use react-virtualized. 
Rendering long lists was really slow because each list item was added to the DOM. With virtualization, only the list items that are visible in the EuiComboBoxOptionsList panel are in the DOM and there is great performance for large lists.
> use react-virtualized to virtualize EuiComboBox options list

- CHANGELOG.md
- src/components/form/form.js
- src/components/form/form_row/form_row.js
I've been getting a few of these warnings while running tests in Cloud. 
They're being caused because the error passed is a node (rather than the currently accepted string or array of strings. I spoke to @pugnascotia and @cjcenizal who agreed that we should allow node as a PropType too.
> Add support for nodes as a proptype for errors.

- CHANGELOG.md
- src-docs/src/views/accordion/accordion.js
- src-docs/src/views/accordion/accordion_example.js
- src-docs/src/views/accordion/accordion_extra.js
- src-docs/src/views/accordion/accordion_form.js
- src-docs/src/views/accordion/accordion_grow.js
- src-docs/src/views/accordion/accordion_open.js
- src/components/accordion/__snapshots__/accordion.test.js.snap
- src/components/accordion/_accordion.scss
- src/components/accordion/_accordion_form.scss
- src/components/accordion/accordion.js
Fixes https://github.com/elastic/eui/issues/695
This adds a new prop to `EuiAccordion` of `paddingSize` and accepts the usual array of named sizes. The issue @pugnascotia noticed happened because if you use a FlexGroup inside of an Accordion the negative margin will conflict with the accordions overflow attributes (which we use to hide the content). This causes a bunch of unnecessary scroll bars. Although I toyed with the idea of removing the negative margins from flexgroups entirely, they do have some really useful abilities that would be tough to replicate (wrapping an unknown amount of flexitems dynamically).
> Adds paddingSize prop to EuiAccordion

- CHANGELOG.md
- src/components/form/_mixins.scss
- src/global_styling/reset/_reset.scss
`line-height: inherited` from reset.scss was making inputs get their line-height from their container, which we really only want it to remain “normal”
Before: 
After:
>  Fix inherited line-height of inputs

- CHANGELOG.md
- src/components/toast/_toast.scss
> Reduced EuiToast title to “xs” title size

- CHANGELOG.md
- src/components/card/__snapshots__/card.test.js.snap
- src/components/card/_card.scss
- src/components/card/card.js
This also fixes an issue with margins when no icon is used.
> Card theme title parity and margin fix

- CHANGELOG.md
- src-docs/src/views/badge/badge_example.js
- src-docs/src/views/badge/beta_badge.js
- src-docs/src/views/card/card_beta.js
- src-docs/src/views/card/card_example.js
- src-docs/src/views/key_pad_menu/key_pad_beta.js
- src-docs/src/views/key_pad_menu/key_pad_menu_example.js
- src/components/badge/_badge.scss
- src/components/badge/_index.scss
- src/components/badge/beta_badge/__snapshots__/beta_badge.test.js.snap
- src/components/badge/beta_badge/_beta_badge.scss
- src/components/badge/beta_badge/_index.scss
- src/components/badge/beta_badge/beta_badge.js
- src/components/badge/beta_badge/beta_badge.test.js
- src/components/badge/beta_badge/index.js
- src/components/card/_card.scss
- src/components/card/card.js
- src/components/index.js
- src/components/key_pad_menu/_key_pad_menu.scss
- src/components/key_pad_menu/key_pad_menu_item.js
Fixes #682 
This adds a new component called `EuiBetaBadge` that only accepts a `label` and `description`. It will only add a tooltip if the `description` prop exists.
----
This will truncate to only one letter and ensure the full label is supplied to the tooltip as a title or if there is no tooltip (no description) it will add the title just as a norma `title` attribute.
cc @nreese
> Beta Badges

- src-docs/src/views/search_bar/search_bar.js
Removing misplaced backtick from https://elastic.github.io/eui/#/forms/search-bar
> Remove misplaced backtick

- package-lock.json
- package.json
* Update package.json.lock by doing a `npm install` to fix the leftover git merge conflict text that were inside the file
* An npm dependency update caused older git clients to start failing with the error "fatal: unable to look up current user in the passwd file: no such user". The workaround is to make sure that the environment variables `GIT_COMMITTER_EMAIL` and `GIT_COMMITTER_NAME` are set.
> Update package.json.lock by doing a `npm install` to fix the leftover git merge conflict text that were inside the file

- CHANGELOG.md
- src-docs/src/views/tabs/controlled.js
- src-docs/src/views/tabs/tabbed_content.js
- src-docs/src/views/tabs/tabs_example.js
- src/components/index.js
- src/components/tabs/index.js
- src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.js.snap
- src/components/tabs/tabbed_content/index.js
- src/components/tabs/tabbed_content/tabbed_content.js
- src/components/tabs/tabbed_content/tabbed_content.test.js
This component makes it easy to connect tabs with the content they display. You can either delegate state management to the component or provide props to control its state. Thanks @arkwright for building the initial version of this!
> Add EuiTabbedContent.

- CHANGELOG.md
- src/components/table/__snapshots__/table_row_cell.test.js.snap
- src/components/table/table_row_cell.js
- src/components/table/table_row_cell.test.js
Fixes #706 by merging `EuiTableRowCell`s childClasses into any already existing className on the child element, when `textOnly === false`.
> Merge EuiTableRowCell's childClasses into any existing className

- CHANGELOG.md
- src-docs/src/views/combo_box/combo_box.js
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/date_picker/__snapshots__/date_picker.test.js.snap
- src/components/date_picker/date_picker.test.js
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/form_control_layout.js
fixes https://github.com/elastic/eui/issues/681
> EuiComboBox: Add buttons for clearing and opening/closing the combo box

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Fixes #690 by passing the `itemIdToExpandedRowMap` prop down from `EuiInMemoryTable` to `EuiBasicTable`.
> Pass itemIdToExpandedRowMap prop from EuiInMemoryTable to EuiBasicTable

- package.json
- scripts/postinstall.js
- yarn.lock
The CI job fails when Jenkins tries to clear the old workspace if it contains a filename with non-latin characters, such as `这` from the `nodegit` dependency. I consider this a short-term fix to make CI happy again and then work with infra to support having such files in the workspace.
> Add postinstall script

- CHANGELOG.md
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
Fixes #692 by creating a unique `itemId` for table items that incorporates their position in a paginated dataset.
Also fixes a bug where the expanded rows were not being associated with the owning aria row.
> Prevent table row expansion to leak between table pages

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/combo_box/combo_box_input/combo_box_pill.js
> EuiComboBox - remove cross icon when singleSelection is enabled

- CHANGELOG.md
- src-docs/src/views/text/text_color.js
- src-docs/src/views/text/text_example.js
- src/components/text/_text.scss
- src/components/text/_text_color.scss
Fixes https://github.com/elastic/eui/issues/766
We're likely being a little too forceful with coloring with `EuiTextColor` and `EuiText`. This lessons the specificity and removes from brute force patterns. In place of the brute force I've applied `color: inherit` on `euiText` so it should play nicer with styling from parents. The default coloring would come from the `reset.scss` values anyway.
> Remove specificity on text coloring

- .npmignore
Kibana `yarn kbn bootstrap` tries to run `postinstall` script but this generates an error because the scripts directory is not part of the published package.
> remove scripts directory from .npmignore

- .npmignore
This keeps everything in `scripts` out of the npm package except `postinstall.js`
> Include the postinstall.js script when building the npm package

- CHANGELOG.md
- src-docs/src/routes.js
- src-docs/src/views/utility_classes/utility_classes.js
- src-docs/src/views/utility_classes/utility_classes_example.js
- src/global_styling/index.scss
- src/global_styling/utility/_index.scss
- src/global_styling/utility/_utility.scss
Fixes https://github.com/elastic/eui/issues/758
After seeing separate instances of people wanting to deal with text wrapping issues we decided it best to provide some CSS utility classes for common situations. Otherwise we'd need to add lots of optional props to our React components that might not target the individual piece of content (like a heading in a tooltip) that we want.
More discussion can be found in the issue above.
I'm purposefully keeping this list very small to start. For example, keeping out flexs and floats since we already have components that do a decent job at this type of thing.
> Adds utility CSS classes to EUI

- CHANGELOG.md
- src-docs/src/views/form_controls/field_number.js
- src-docs/src/views/form_controls/field_password.js
- src-docs/src/views/form_controls/field_search.js
- src-docs/src/views/form_controls/field_text.js
- src-docs/src/views/form_controls/range.js
- src-docs/src/views/form_controls/select.js
- src-docs/src/views/form_controls/text_area.js
- src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
- src/components/form/form_error_text/__snapshots__/form_error_text.test.js.snap
- src/components/form/form_error_text/form_error_text.js
- src/components/form/form_row/__snapshots__/form_row.test.js.snap
- src/components/form/form_row/form_row.js
Fixes https://github.com/elastic/eui/issues/782, https://github.com/elastic/eui/issues/784
* Our docs should show using aria-labels when no actual label tag is in use.
* `aria-invalid` passed to `EuiFormRow` items if the input is invalid.
I looked into using `aria-errormessage` as @timroes suggested but found that the errors would not be read by screenreaders in chrome / safari. It seemed safer to leave them on `aria-describedby`, even if they mix in with help text. At least with `aria-invalid` the messaging is more clear.
> Aria labeling for docs of plain form controls, aria-invalid attrib on EuiFormRow

- CHANGELOG.md
- src/components/badge/badge.js
- src/utils/prop_types/requires_aria_label.js
Updates the `requiresAriaLabel` proptype to be passed the name of its `action` property only, as the label property is already associated from the propname.
Also fixes its usage on `Badge`.
> update requiresAriaLabel custom proptype and its usages

- src/components/combo_box/combo_box.js
fixes https://github.com/elastic/eui/issues/794
I could not find a way to reproduce calling setState once the combo box component had been unmounted. This PR just avoids the potential of calling setState for 2 places where setState was called asynchronously.
> do not call setState if combo box is no longer mounted

- CHANGELOG.md
- src/components/combo_box/combo_box.js
I am occasionally getting an error when timeout function is getting called after component has unmounted.
> EuiComboBox - only call copyInputStyles when still mounted

- CHANGELOG.md
- src-docs/src/index.html
- src/components/accordion/_accordion.scss
- src/components/accordion/_accordion_form.scss
- src/components/accordion/accordion.js
Fixes https://github.com/elastic/eui/issues/805
Makes sure that the child content of an accordion gets a height if its set to be initially open.
cc @ppisljar and @timroes who ran into this issue in https://github.com/elastic/kibana/pull/18579
> Accordion needs a height calculation on mount

- CHANGELOG.md
- src-docs/src/views/context_menu/context_menu.js
- src-docs/src/views/context_menu/context_menu_example.js
- src/components/basic_table/__snapshots__/collapsed_item_actions.test.js.snap
- src/components/context_menu/__snapshots__/context_menu_panel.test.js.snap
- src/components/context_menu/context_menu.js
- src/components/context_menu/context_menu_item.js
- src/components/tool_tip/tool_tip.js
Fixed #808 
Context menus now allow a `toolTipTitle` and `toolTipContent` to apply a tooltip.
> Add tooltips to context menu

- CHANGELOG.md
- src-docs/src/components/guide_page/guide_page_chrome.js
- src-docs/src/components/guide_theme_selector/guide_theme_selector.js
- src-docs/src/views/guidelines/button.js
- src-docs/src/views/popover/popover.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/bottom_bar/__snapshots__/bottom_bar.test.js.snap
- src/components/bottom_bar/bottom_bar.js
- src/components/pagination/pagination.js
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/popover.js
- src/components/side_nav/__snapshots__/side_nav.test.js.snap
- src/components/side_nav/__snapshots__/side_nav_item.test.js.snap
- src/components/side_nav/side_nav.js
- src/components/side_nav/side_nav_item.js
- src/components/table/mobile/__snapshots__/table_sort_mobile.test.js.snap
- src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
Fixes #733 
Fixes #734
Fixes #735 
Fixes #621 
Fixes #736
Fixes #728 
Fixes #729
Fixes #723 
Fixes #616 
Fixes #687 
Fixes #617 
Fixes #746 
Grab bag of accessibility fixes. The following changes were made.
* Fixed a bug in our documentation where sidenav submenus had empty buttons if we were excluding the title (which we usually do for the first one in the page).
* Made `EuiPagination` more friendly for screen readers.
* Made `EuiSideNav` use menubar labeling. Of all the options (nav / tree...etc) it was the most agreeable with our current formatting.
* Fixed an issue with `EuiPopover` where `ownFocs` was required if it didn't wrap a context menu. Made `EuiPopover` use an `aria-live` label to announce its contents if it isn't set (with the assumption that if it is, the SR will read what …
> Fixes for accessibility tickets

- CHANGELOG.md
- src-docs/src/routes.js
- src-docs/src/views/breadcrumbs/breadcrumbs.js
- src-docs/src/views/breadcrumbs/breadcrumbs_example.js
- src-docs/src/views/breadcrumbs/max.js
- src-docs/src/views/breadcrumbs/responsive.js
- src-docs/src/views/breadcrumbs/truncate.js
- src/components/breadcrumbs/__snapshots__/breadcrumbs.test.js.snap
- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/breadcrumbs/_index.scss
- src/components/breadcrumbs/breadcrumbs.js
- src/components/breadcrumbs/breadcrumbs.test.js
- src/components/breadcrumbs/index.js
- src/components/index.js
- src/components/index.scss
- src/components/link/link.js
Came up with this design with @gjones:
> Add EuiBreadcrumbs.

- CHANGELOG.md
- src-docs/src/views/combo_box/combo_box_example.js
- src-docs/src/views/combo_box/disabled.js
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_input/combo_box_input.js
Fixes https://github.com/elastic/eui/issues/822
Adds `isDisabled` prop to `EuiComboBox`. Will properly disable the input and remove button actions on the pills, clears and dropdown arrows.
This does remove the item from screen readers since it isn't focusable. I tried a couple options but this is something sort of built into HTML and acts similar to our other inputs. I'm going to make an issue to try and think up something clever to fix this across our forms in general.
> Adds isDisabled prop to EuiComboBox

- README.md
- wiki/react-router.md
Fixes https://github.com/elastic/eui/issues/507
@mattapperson You're using RR v4 right? Could you verify that my guidance here is technically correct?
@bevacqua, @pugnascotia, @zinckiwi Would you mind sharing your thoughts on this?
> Add guidance on how to use EUI with react-router.

- src/components/basic_table/basic_table.js
- src/components/basic_table/custom_item_action.js
- src/components/basic_table/in_memory_table.js
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
- src/components/context_menu/context_menu.js
- src/components/context_menu/context_menu_panel.js
- src/components/delay_hide/delay_hide.js
- src/components/popover/popover.js
- src/components/search_bar/search_bar.js
- src/components/search_bar/search_box.js
Completes the first step in #763 by adding TODOs to the locations where EUI uses the React lifecycle methods that were deprecated in 16.3. Each comment includes a suggestion for how to move that instance off the deprecated method.
> added TODOs to the lifecycle methods deprecated in react 16.3

- src/webpack.config.js
Fixes #828 by adding `react-dom` and `moment` to webpack's `externals`. This only impacts the bundle published to npm, which is provided only for potential use by apps which pull scripts in from a CDN (like jsbin).
> update webpack config to exclude react-dom and moment from the bundle

- package.json
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
- yarn.lock
As part of #763, updates EUI to React 16.3 and converts `EuiBasicTable`'s lifecycle from `componentWillReceiveProps` to `getDerivedStateFromProps`. The table component's `itemId` instance method was not accessible from the static lifecycle method and was refactored into a stand-alone function.
> Upgrade to React 16.3 and convert EuiBasicTable's lifecycle

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Fixes #850 by extracting `items` from the rest prop instead of passing it through to `EuiBasicTable`. Also extracts `search` prop as that is meant to be consumed by `EuiInMemoryTable`. Added a unit test to prevent future regressions.
> Extract items and search from EuiInMemoryTable's ...rest prop

- CHANGELOG.md
- src-docs/src/views/button/button_as_link.js
- src/components/button/__snapshots__/button.test.js.snap
- src/components/button/button.js
- src/components/button/button.test.js
- src/components/button/button_empty/__snapshots__/button_empty.test.js.snap
- src/components/button/button_empty/button_empty.js
- src/components/button/button_empty/button_empty.test.js
- src/components/button/button_icon/__snapshots__/button_icon.test.js.snap
- src/components/button/button_icon/_button_icon.scss
- src/components/button/button_icon/button_icon.js
- src/components/button/button_icon/button_icon.test.js
If `href` was defined on a button, then it would be rendered as an `<a>`, which doesn't recognize the `disabled` attribute, and would therefore be unaffected by our styles which use this attribute in their selectors.
I fixed this by rendering a `<button>` element instead, when `isDisabled=true`. This is a bit of a hack, but I think it's the cleanest solution, and I couldn't think of any side effects.
> Fix bug in which disabled link buttons don't look and act disabled

- CHANGELOG.md
- src/services/time/timer.js
Fixes https://github.com/elastic/kibana/issues/19285
We could get fancy and fix this specific situation through more coordination, or we can be defensive and just not trigger the callback if it's been removed. I opted for the second because of its simplicity and it addresses any related bugs that may occur in the future.
This also fixes a second bug where the toast's countdown is not restarted for the correct amount of time after the second hover.
<details>
<summary>what causes the error</summary>
When a toast managed by `EuiGlobalToastList` reaches the end of its timer, the timer self-clears and triggers the callback, beginning the process of fading out the element. The toast fade-and-remove can be laid out as
- timer's timeout happens
- timer.callback()
- toast list tracks this toast as …
> Fix timer callback triggering after timer is cleared

- CHANGELOG.md
- src/components/toast/global_toast_list.js
Addresses https://github.com/elastic/kibana/issues/19263 by making `EuiGlobalToastList` make sure it hasn't already dismissed a toast when it goes to dismiss a toast.
> make sure a toast has not already been dismissed when dismissing it

- CHANGELOG.md
- src/components/card/_card.scss
- src/components/form/form_control_layout/_form_control_layout.scss
- src/global_styling/utility/_utility.scss
- Fixes #855: Add fallback to just break-all in FF and IE
- Fixed text color of descriptions in cards
- Fixed vertical alignment of combo box arrow icon (it was a couple pixels too low)
- Fixed `EuiCard` IE bugs
- `EuiBetaBadge` wasn't displying outside of card bounds
- Image bounds weren’t being correctly calculated
- IE doesn’t accept `calc` in transforms
> Some quick CSS fixes

- CHANGELOG.md
- src-docs/src/views/search_bar/controlled_search_bar.js
- src-docs/src/views/search_bar/props_info.js
- src-docs/src/views/search_bar/search_bar_example.js
- src-docs/src/views/tables/in_memory/in_memory_search_callback.js
- src/components/basic_table/in_memory_table.js
- src/components/search_bar/search_bar.js
- src/components/search_bar/search_bar.test.js
- fixed `EuiSearchBar`'s proptypes (had been changed to the wrong object at some point)
- refactored `componentWillUpdate` -> `getDerivedStateFromProps` / `componentDidUpdate` and updated support for externally-controlled query values
- corrected how the custom date parser property / parse option is passed
- `onChange` has changed from taking one argument, `queryText`, to taking an argument with the shape `{ query, queryText, error }`
- `onParse` has been removed
- added an example of a controlled search bar to the docs
> Update EuiSearchBar to React 16.3 lifecycle

- src/components/basic_table/custom_item_action.js
- src/components/basic_table/in_memory_table.js
For #763 
* _EuiInMemoryTable_ implements `getDerivedStateFromProps` to replace `componentWillReceiveProps`. Moved `items` into component state instead of accessing it from props.
* _EuiCustomItemAction_ `componentWillMount` -> `componentDidMount`
> Update EuiInMemoryTable's and EuiCustomItemAction lifecycle for React 16.3

- wiki/consuming.md
Stems from conversation in https://github.com/elastic/eui/pull/866#discussion_r190395284.
> Document requirement of an ES2015 polyfill.

- src/components/popover/popover.js
- src/components/search_bar/search_box.js
Part of #763 
- changed `EuiSearchBox`'s `componentWillUpdate` to `componentDidUpdate`.
- merged `EuiPopOver`'s `componentWillUpdate` into its existing `componentDidUpdate` and split some of it out into `getDerivedStateFromProps` (mostly because the no-setstate-in-componentdidupdate lint rule which is hilariously skirted around by the rest of this `componentDidUpdate`).
> refactored EuiSearchBox and EuiPopover to use React 16.3 lifecycle

- CHANGELOG.md
- src-docs/src/views/tables/basic/basic.js
- src-docs/src/views/tables/basic/basic_section.js
- src-docs/src/views/tables/data_store.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
- src/components/basic_table/in_memory_table.js
- src/components/table/__snapshots__/table_row_cell.test.js.snap
- src/components/table/table_row_cell.js
Closes https://github.com/elastic/eui/issues/867
This adds support for a `__props__` property on the item which defines a row. Alternatively we could define the row item like this:
```js
{
cells: { /* define each cell here */ },
/* Add pass-through props here */
}
```
Though this would be a breaking change, and I think adding pass-through props will be a rarity, so I decided to just create an additional property with the underscores to avoid colliding with any of the other properties.
While I was in this code I also slightly reorganized and simplified the tests. I can extract this to a separate PR if anyone objects.
> Add support for custom props for rows in EuiBasicTable and EuiInMemoryTable.

- CHANGELOG.md
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/form_control_layout.js
Fixes https://github.com/elastic/eui/issues/785
Fixes https://github.com/elastic/eui/issues/786
Adds some labeling to the buttons in form_layout / combo box.
> Combo box icon accessibility

- CHANGELOG.md
- src/components/breadcrumbs/_breadcrumbs.scss
> Fixed alignment of breadcrumb slashes when truncating

- src/components/flex/_flex_group.scss
The `&` used in the flex group sass didn't have a parent. Apparently this was causing problems with @zumwalt's libsass compile. This should be an overall non-change.
> Remove loose and in flex group

- src/components/delay_hide/delay_hide.js
Relates to #763 
For this one, simply moving the old lifecycle into `componentDidUpdate` created a nice infinite setState loop. I scrapped the old logic and rewrote so there is less for the DelayHide to keep track of, and it's easier to follow.
> Rewrote EuiDelayHide for React 16.3 lifecycle

- CHANGELOG.md
- src-docs/src/views/context_menu/content_panel.js
- src-docs/src/views/context_menu/context_menu_example.js
- src-docs/src/views/context_menu/context_menu_with_content.js
- src/components/context_menu/context_menu.js
- src/components/context_menu/context_menu_panel.js
Associated with #763 
* Refactored `EuiContextMenu` and `EuiContextMenuPanel` to React 16.3's lifecycle. This moves computed values in both components off of instance members and into React's state.
* Added 2 more examples to context menu docs
* Fixed some lurking bugs around allowing dynamic content in the menu panels
> Update context menu components to React 16.3 lifecycle

- .npmignore
- CHANGELOG.md
Fixes #891 by preventing the `.nvmrc` file from being included in the published npm package. I also added entries to keep `.idea` and `.vscode` configurations out of the package (they're already excluded in `.gitignore`)
> add .nvmrc .idea .vscode to .npmignore

- CHANGELOG.md
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
Part of #763 
`EuiComboBoxOptionsList` and `EuiComboBoxInput` were straight-foward changes. I moved two class members on `EuiComboBox` into its state. Updating `matchingOptions` state value in componentDidUpdate could create an infinite loop so I added a quick check to see if the matching options have changed. Existing tests pass and the examples work identically to the published docs.
> Update combo box components to React 16.3 lifecycle

- CHANGELOG.md
- src-docs/src/views/panel/panel_badge.js
- src-docs/src/views/panel/panel_example.js
- src/components/badge/beta_badge/_index.scss
- src/components/badge/beta_badge/_mixins.scss
- src/components/card/_card.scss
- src/components/card/_index.scss
- src/components/panel/_panel.scss
- src/components/panel/panel.js
Replaces https://github.com/elastic/eui/pull/884
Feature request of @nreese.
* Moved the beta badge sass from `EuiCard` to a more generic mixin, then imported into cards.
* Added badges to `EuiPanel`
> Beta badges on panels

- CHANGELOG.md
- src/components/form/file_picker/_file_picker.scss
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/_form_control_layout_clear_button.scss
- src/components/form/form_control_layout/_form_control_layout_custom_icon.scss
- src/components/form/form_control_layout/_form_control_layout_icons.scss
- src/components/form/form_control_layout/_index.scss
- src/components/form/form_control_layout/_mixins.scss
- src/components/form/form_control_layout/form_control_layout.js
- src/components/form/form_control_layout/form_control_layout_clear_button.js
- src/components/form/form_control_layout/form_control_layout_custom_icon.js
- src/components/form/form_control_layout/form_control_layout_icons.js
Fixes https://github.com/elastic/eui/issues/893
Thanks for catching this @cchaos!
I tested the following scenarios:
* Clicking the icon in a EuiSelect now opens the select and gives it focus
* Clicking the icon in a EuiFieldPassword gives focus to the input
* Clicking both the clear and caret icons in EuiComboBox still has the original desired behavior of clearing/toggling the EuiComboBox
I also added a note to the CHANGELOG under 0.0.50 noting this regression.
> Fix focus state regression of icons in EuiFormControlLayout.

- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout_custom_icon.scss
- src/components/form/form_control_layout/form_control_layout_custom_icon.js
Super slight visual regression happened in #894 / #898.
Before: 
After:
---
Gonna merge right away, just documenting here.
> Fixing form layout icon vertical alignment

- CHANGELOG.md
- src-docs/src/views/button/button_example.js
- src-docs/src/views/button/button_icon.js
- src/components/button/button_icon/__snapshots__/button_icon.test.js.snap
- src/components/button/button_icon/_button_icon.scss
- src/components/button/button_icon/button_icon.js
- src/themes/eui/eui_colors_dark.scss
- src/themes/k6/k6_colors_dark.scss
Fixes https://github.com/elastic/eui/issues/907
FWIW the screen @timroes  pointed to was of a disabled state icon, which was purposely low contrast. I went ahead though and added the full range of coloring to `EuiButtonIcon` including a proper subdued state and our other core palette colors.
> Full range of button icon colors

- CHANGELOG.md
- src-docs/src/views/context_menu/context_menu.js
- src/components/context_menu/__snapshots__/context_menu_item.test.js.snap
- src/components/context_menu/__snapshots__/context_menu_panel.test.js.snap
- src/components/context_menu/_context_menu_item.scss
- src/components/context_menu/context_menu_item.js
- src/components/context_menu/context_menu_item.test.js
@jen-huang This will give us the option to specify hrefs for the index pattern creation options, instead of using `onClick` in conjunction with `kbnUrl` (if we decide that's better).
> Add support for href, target, and rel properties for EuiContextMenu items.

- package.json
- yarn.lock
package.json was pulling in an older version of brace for no reason.  This explicit dependency is unnecessary as react-ace already pulls in the version of brace it needs.
> removing explicit brace dependency as react-ace already depends on it

- src/components/delay_hide/delay_hide.js
- src/components/delay_hide/delay_hide.test.js
A regression was introduced in https://github.com/elastic/eui/pull/879 which causes the component to be displayed indefinitely even though the `hide` parameter is `true` and the timeout has passed.
I added a tests that reproduces this scenario, where an update to the parent component will cause `getDerivedStateFromProps` to be called again, which will corrupt the internal state.
There is a good blog post about this exact pitfall here: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
@chandlerprall I'm not sure the solution presented here is the best. If you have anything more elegant I'm all ears!
fixes elastic/kibana#19785
> Ensure DelayHide component disappears correctly

- CHANGELOG.md
- src-docs/src/views/flyout/flyout.js
- src-docs/src/views/flyout/flyout_complicated.js
- src-docs/src/views/flyout/flyout_example.js
- src-docs/src/views/flyout/flyout_size.js
- src/components/flyout/__snapshots__/flyout.test.js.snap
- src/components/flyout/flyout.js
Fixes https://github.com/elastic/eui/issues/725
> Added role='dialog' to EuiFlyout and documented correct way to make it announce itself with aria attributes

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
- src/components/combo_box/combo_box_input/combo_box_input.js
This prevents focus from defaulting to the body. It's an accessibility problem if focus suddenly goes to the `body` element after clicking a button. The behavior introduced by this PR is also how [react-select](http://jedwatson.github.io/react-select/) solves this problem.
I also decorated `EuiComboBox` with data-test-subj selectors for the search input and clear button and tried to make the tests and snapshots a bit clearer regarding what's being tested.
> EuiComboBox now gives focus to the search input when the user clicks the clear button

- CHANGELOG.md
- src-docs/src/views/tables/data_store.js
- src/services/sort/comparators.js
- src/services/sort/comparators.test.js
Fixes #920 by checking if sort values are `null` or `undefined` and handling those separately. This change does not handle all "invalid" comparisons (e.g. `{} > {}` is always `false`, and there are other cases) but I don't think the default comparator should incorporate the necessary logic to handle all of the edge cases ([Symbol.toPrimitive](https://www.ecma-international.org/ecma-262/#sec-toprimitive) and [OrdinaryToPrimitive](https://www.ecma-international.org/ecma-262/#sec-ordinarytoprimitive)).
> Fix default sort comparator to logically handle null/undefined values

- CHANGELOG.md
- src-docs/src/views/flyout/flyout.js
- src-docs/src/views/flyout/flyout_complicated.js
- src-docs/src/views/flyout/flyout_example.js
- src-docs/src/views/flyout/flyout_size.js
- src/components/flyout/__snapshots__/flyout.test.js.snap
- src/components/flyout/__snapshots__/flyout_header.test.js.snap
- src/components/flyout/_flyout.scss
- src/components/flyout/_flyout_footer.scss
- src/components/flyout/_flyout_header.scss
- src/components/flyout/flyout.js
- src/components/flyout/flyout.test.js
- src/components/flyout/flyout_header.js
- src/components/flyout/flyout_header.test.js
- src/components/flyout/index.js
- Added “cross” close button to top right as default if (“onClose”) is present
- Added option for a border below header
- Altered doc examples to represent how we **want** the flyouts to display consistently
@snide I made some design decisions on the header, let me know if you think otherwise.
> Flyout alterations

- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
This fixes a bug I introduced in https://github.com/elastic/eui/pull/866. In previous discussions, we decided to block the user from tabbing off the combo box if they're navigating through the options list. This mimics how Chrome blocks the user from tabbing off an open select.
> Fix bug where users could tab away from EuiComboBox while navigating the options list

- CHANGELOG.md
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
- src/components/form/_mixins.scss
- src/components/form/file_picker/_file_picker.scss
The box-shadow that mimics the input’s border is now `inset`. This means the `40px` height is **actually** `40px` and the box-shadow ensure it's borders don't spill over the `400px` width.
It's very subtle, hence the zoomed in gif. I also tweaked the second box-shadow slightly to have a better edge to it.
This also touched the `EuiComboBoxList` styles since it was doing extra css to account for the extended border.
---
This originally was noticed as an issue when I saw this:
https://github.com/elastic/kibana/blame/master/src/core_plugins/input_control_vis/public/components/editor/controls_tab.less
So cc'ing @nreese : This will fix the problem you were running into with inputs inside of accordions. When this get's merged into Kibana, can you remove this extra style? It will cause visual …
> Fixing size of inputs via box-shadow

- CHANGELOG.md
- src-docs/src/views/tables/in_memory/in_memory_custom_sorting.js
- src-docs/src/views/tables/in_memory/in_memory_custom_sorting_section.js
- src-docs/src/views/tables/in_memory/index.js
- src-docs/src/views/tables/tables_example.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Closes #425. Allows the `sortable` value on `EuiInMemoryTable`'s columns to be a function which, when that column is sorted, is passed each `item` and the return value is used for sorting.
> Custom column sort values for EuiInMemoryTable

- CHANGELOG.md
- src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.js.snap
- src/components/tabs/tabbed_content/tabbed_content.js
- src/components/tabs/tabbed_content/tabbed_content.test.js
Fixes #930 
`EuiTabbedContent` previously stored the entire tab object in its `selectedTab` state, so any updates/changes to the passed-in tab content was ignored until the user switched away from and back to that same tab. This PR changes the component to track the selected tab by _name_ so it will always pull content from the prop instead of caching it in state.
> Refactor EuiTabbedContent to track its selected tab by name

- CHANGELOG.md
- src-docs/src/views/code_editor/code_editor_example.js
- src-docs/src/views/code_editor/custom_mode.js
- src/components/code_editor/code_editor.js
Resolves #933.
Allows the `mode` prop in the `EuiCodeEditor` component to take an `object` representing a custom Ace mode.
* Run this PR along with https://github.com/elastic/kibana/pull/20027.
* In Kibana, open Dev Tools > Grok Debugger
* In the Grok Pattern field (which uses a custom mode), enter:
```
%{WORD:foo}
```
* Verify that the syntax highlighting changes once you finish typing.
> EuiCodeEditor: make it take a custom mode

- CHANGELOG.md
- src/components/code_editor/__snapshots__/code_editor.test.js.snap
- src/components/code_editor/code_editor.js
With this change, functional tests of code consuming this component can select the `EuiCodeEditor` element.
You can see an example of this in action if you pull down https://github.com/elastic/kibana/pull/20027 along side this PR and run the functional tests for the Grok Debugger app. More specifically, you can see how the `data-test-subj` introduced in this PR is used for selection here:
https://github.com/elastic/kibana/pull/20027/files#diff-4621acc6e44779ce105ee52070f80bafR17
> [EuiCodeEditor] Provide selection target for functional tests

- CHANGELOG.md
- src/components/code_editor/code_editor.js
Before this change, this warning would be shown in the console:
`Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message`
> [EuiCodeEditor] Set $blockScrolling = Infinity to prevent console warning

- CHANGELOG.md
- src/components/tool_tip/tool_tip.js
- src/services/popover/popover_positioning.js
- src/services/popover/popover_positioning.test.js
fast follow for #924 
* `EuiTooltip` did not clear its previous knowledge of the tooltip content's size so a window resize & re-hover of the anchor would cause the new tooltip to be influenced by the previous instance's positioning
* small adjustment (1px) to tooltip's arrow position
* Popover service did not take scroll bars into account when finding available window size
* Popover service did not take `buffer` into account when calculating the content's fit value
@cchaos would you mind testing the visuals again to see if you can find any circumstances where tooltip breaks / is malformed?
> Fix tooltip re-position after content resize & respect scroll bars

- CHANGELOG.md
- src/components/avatar/_avatar.scss
- Reducing font sizing so 2 initials fits better
- Explicitly stating font weight so it doesn't get overridden by inheritence
> Altering the avatars a bit

- CHANGELOG.md
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
- src/services/popover/popover_positioning.js
- src/services/popover/popover_positioning.test.js
Fixes #895, fixes #633
This PR refactors `EuiComboBox` to use the new popover positioning service, and introduces a new flag for the service which forces the popover to stay on the initial axis (keeping the combobox in `top` or `bottom` positions).
> Update EuiComboBox to use tthe new popover service

- CHANGELOG.md
- src-docs/src/views/accordion/accordion_grow.js
- src/components/accordion/accordion.js
- src/components/accordion/accordion.test.js
EuiAccordion does not update height when children internal state changes. I updated the AccordionGrow example to demonstrate. When the counter is modified inside the sub-component than EuiAccordion's componentDidUpdate never gets called because none of the props passed to children changed.
This PR adds a MutationObserver to update height any time the children DOM tree changes.
> add MutationObserver to accordion to trigger setChildContentHeight when children change

- CHANGELOG.md
- src/components/combo_box/_combo_box.scss
- src/components/filter_group/_filter_button.scss
- src/components/form/_mixins.scss
- src/components/form/_variables.scss
- src/components/form/file_picker/_file_picker.scss
- src/components/form/select/_select.scss
- Made bottom colored border from linear-gradient
- Allowing parameters to determine if just the borders should render
- Allowing parameters to determine if all state styles should be added
- Fixing variable naming schemes
The one thing to note is that it no longer has a reverse transition. However, it now matches better with our other animations that also don't have a reverse transition.
> Simplifying form control styles

- CHANGELOG.md
- src-docs/src/views/popover/popover_anchor_position.js
- src/components/header/header_links/__snapshots__/header_links.test.js.snap
- src/components/outside_click_detector/outside_click_detector.js
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/_popover.scss
- src/components/popover/popover.js
- src/components/popover/popover.test.js
- src/components/portal/portal.js
- src/components/table/mobile/__snapshots__/table_sort_mobile.test.js.snap
- src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
- src/services/popover/popover_positioning.js
- src/services/popover/popover_positioning.test.js
Closes #873 
Refactored `EuiPopover` to use portals and take advantage of the positioning service. The service had to be expanded to include an `align` parameter to allow shifting content into a given corner if there's room.
> Refactor EuiPopover to use new positioning service

- CHANGELOG.md
- src/components/table/_table.scss
---
Addresses https://github.com/elastic/eui/issues/855#event-1709607391 and fixes #855 and fixes #943
cc @jen-huang
> Added word-break fallback for FF & IE in table cell

- CHANGELOG.md
- src-docs/src/views/flyout/flyout_complicated.js
- src/components/popover/popover.js
- src/services/popover/popover_positioning.js
Fixes #965 
This sets the content's z-index from the anchor element's z-index. The value must be calculated/copied instead of hard-coding in css as e.g. the popover may need to show behind a flyout from one button but be in front if it relates to content in the flyout.
_without setting z-index_
_with z-index_
adding
@cchaos sanity check, testing
@nreese / @cjcenizal to make sure the code change & comments are understandable
> Make EuiPopover copy the anchor's z-index to the popover content

- CHANGELOG.md
- src/components/form/field_password/field_password.js
Fixes #964 by adding the `inputRef` prop to `EuiFieldPassword`, making it match the other input components.
> Add inputRef prop to EuiFieldPassword

- CHANGELOG.md
- src-docs/src/components/guide_components.scss
- src-docs/src/views/flex/flex_example.js
- src-docs/src/views/home/home_view.js
- src-docs/src/views/image/image_zoom.js
- src/components/card/_card.scss
- src/components/card/card.js
- src/components/flex/_flex_grid.scss
- src/components/flex/_flex_group.scss
- src/components/image/_image.scss
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/modal/__snapshots__/modal.test.js.snap
- src/components/modal/_modal.scss
- src/components/modal/modal.js
- src/global_styling/utility/_utility.scss
- Fixed modal overflow issue
- Fixed flex wrapping elements in docs and added utility class (`.euiIEFlexWrapFix`) for consumers
- Fixed image shrink issues (fixes #971)
- Fixed home card layout that was still using `<Link>`. I added the `secureRel` stuff to `EuiCard` to support app linking.
- Added some callouts to mention where IE flex bugs may occur (especially for when a generalized fix cannot be implemented)
> IE Fixes (mostly flex box)

- CHANGELOG.md
- src-docs/src/views/tool_tip/icon_tip.js
- src-docs/src/views/tool_tip/tool_tip_example.js
- src/components/tool_tip/__snapshots__/icon_tip.test.js.snap
- src/components/tool_tip/icon_tip.js
- src/components/tool_tip/icon_tip.test.js
Fixes #986.
Similar to what #580 does for the `color` attribute, `size` is now a prop for `EuiIconTip` to specify icon size.
> Allow size to be passed in for EuiIconTip

- CHANGELOG.md
- src/services/index.d.ts
- src/services/key_codes.d.ts
Fixes https://github.com/elastic/eui/issues/984
> Add typings for keyCodes

- CHANGELOG.md
- src/components/accordion/accordion.js
Quick fix for https://github.com/elastic/eui/issues/981
Mostly a quick patch to the Accordion so that the mutation observer stops causing uncaught errors.
- in `setChildContentHeight`, check that `this.childContent` is truthy before trying to read the `clientHeight` property
- in `setChildContentHeight`, check that `this.childWrapper` is set before trying to use `setAttribute`
> Fix: accordion observer issues

- CHANGELOG.md
- src/components/button/index.d.ts
Tried to use `<EuiButtonEmpty />` in typescript but the `href` prop wasn't typed, pulled over the `isLoading` prop too because it seemed to be missing but is defined in the `propTypes`
> [types/EuiButtonEmpty] add missing isLoading and href props

- CHANGELOG.md
- src/components/flyout/index.d.ts
- src/components/index.d.ts
Then we can get rid of stuff like this: https://github.com/elastic/kibana/pull/20163/files#diff-e90413d01eed523422d8446b072e6f7eR26
cc @timroes
> Add basic typings for Flyout

- CHANGELOG.md
- src-docs/src/components/guide_components.scss
- src-docs/src/views/page/page.js
- src-docs/src/views/page/page_content_center_with_side_bar.js
- src-docs/src/views/page/page_simple.js
- src/components/page/_page.scss
- src/components/page/page_body/_page_body.scss
- src/components/page/page_content/__snapshots__/page_content_header.test.js.snap
- src/components/page/page_content/_page_content.scss
- src/components/page/page_content/_page_content_header.scss
- src/components/page/page_content/_page_content_header_section.scss
- src/components/page/page_content/page_content_header.js
- src/components/page/page_header/__snapshots__/page_header.test.js.snap
- src/components/page/page_header/_page_header.scss
- src/components/page/page_header/_page_header_section.scss
- src/components/page/page_header/page_header.js
- src/components/page/page_side_bar/_page_side_bar.scss
- src/components/panel/_mixins.scss
- src/components/panel/_variables.scss
This PR not only fixes the layout on small screens of `EuiPage` and it's sub components, but also shifts where the sidebar lives. @snide and I talked it over and most of our designs have gone this way and it makes the most sense to keep the page header away from the sidebar.
**And it still works with centered content**
_The non-existent padding around the sidebar is on purpose so that the toggle button would expand the whole width._
---
I checked Kibana master to make sure it wouldn't break too many layouts and, at least in master, no one has used the `EuiPageHeader` or `EuiPageSidebar`, so no current layouts should break. The only place it is used is in the plugin generator, but that's a quick fix.
> Page responsive fix

- CHANGELOG.md
- src/components/flyout/index.d.ts
Sorry for the quick merge @timroes, fixing my mistake here.
> Mark properties on EUIFlyout as optional in typings

- CHANGELOG.md
- src/components/context_menu/index.d.ts
fixes https://github.com/elastic/eui/issues/985 and https://github.com/elastic/eui/issues/950
> Add more EuiContextMenuItemProps typings

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
- src/components/pagination/pagination.js
Fixes #1007 
`EuiInMemoryTable::getDerivedStateFromProps` was incorrectly checking the current items against previous items to determine if it needed to reset. This caused the component to reset anytime it's parent updated the props (such as item selection getting cleared during pagination).
> Fixes EuiInMemoryTable resetting when props update

- CHANGELOG.md
- src-docs/src/views/form_layouts/described_form_group.js
- src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
- src/components/text/text.js
- src/components/text/text_color.js
This fixes a bug, so that now `EuiDescribedFormGroup` renders its `description` inside of a `div` instead of a `span`. The original behavior caused issues in advanced settings because divs would end up rendered inside the span.
> Add `component` prop to `EuiTextColor`.

- CHANGELOG.md
- src/components/context_menu/index.d.ts
- src/components/date_picker/__snapshots__/date_picker_range.test.js.snap
- src/services/key_codes.d.ts
Supports https://github.com/elastic/kibana/pull/20790#issuecomment-404936656
> Fix typescript syntax error

- src/components/context_menu/__snapshots__/context_menu_panel.test.js.snap
- src/components/context_menu/context_menu.test.js
- src/components/context_menu/context_menu_panel.js
- src/components/context_menu/context_menu_panel.test.js
Fixes #959 
Adds an animationFrame delay on the updateFocus function for context menus. This gives it enough time for the positioning to calculate first.
> Fix context menu focus jumping

- CHANGELOG.md
- src/components/page/page_body/__snapshots__/page_body.test.js.snap
- src/components/page/page_body/_page_body.scss
- src/components/page/page_body/page_body.js
- src/components/page/page_content/_page_content.scss
Ensures that the auto margins only apply to the sides that are being centered.
Also, I added the `restrictWidth` functionality to the `EuiPageBody` component as well to help with out layouts in Kibana where we're hacking the background color onto `EuiPage`.
> Fixing EuiPageContent layout

- CHANGELOG.md
- src/components/context_menu/context_menu_panel.js
Here is the kibana issue that highlights the problem https://github.com/elastic/kibana/issues/21004.
The problem is that the callback of `requestAnimationFrame` in `EuiContextMenuPanel` does not check that the component is still mounted.
> check for unmounted in requestAnimationFrame callback

- CHANGELOG.md
- src-docs/src/views/form_controls/switch.js
- src/components/form/switch/__snapshots__/switch.test.js.snap
- src/components/form/switch/switch.js
- src/components/form/switch/switch.test.js
Fixes https://github.com/elastic/eui/issues/748
Fixes https://github.com/elastic/eui/issues/1027
Switches now generate a random id if none are passed (similar to how we do it in `EuiFormRow`. This should only happen when used on their own, since most other situations will usually generate one.
This seemed like the best solution since I could not require ids to be provided, otherwise it would spit out errors when `EuiFormRow` cloned ids down.
> Make switch use a random id if none is provided

- CHANGELOG.md
- src/components/outside_click_detector/outside_click_detector.js
- src/components/outside_click_detector/outside_click_detector.test.js
Fixes #1037 by tracking all unique IDs of a bubbling event's encountered `EuiOutsideClickDetector`s. This prevents a wrapping outside click detector from interfering with any children detectors.
> Fix EuiOutsideClickDetector to work when its nested inside itself

- src/components/xy_chart/series/__snapshots__/area_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/line_series.test.js.snap
- src/components/xy_chart/xy_chart.js
The margins property is exposed but not documented in the propTypes.  It can be  used only for internal purposes until we have a the autosizing of margins.
The `margins` props takes either a "standard" margin object like:
```js
{
top: 10,
bottom: 20,
left: 50,
right: 10,
}
```
or a single number used for each margin.
@cchaos you can use this together with `showDefaultAxis={false}` prop to display a sparkline o any chart without margins and axis.
@chandlerprall since this is an internal use prop, do you think we need to add it to the changelog?
> Expose EuiXYChart margins prop

- CHANGELOG.md
- src/components/badge/index.d.ts
- src/components/index.d.ts
Add typings for the EuiBadge component.
Before these changes:
Export the changes from my local `node_modules`:
`EuiBadge` now a recognized type:
> Add typings for EuiBadge

- CHANGELOG.md
- src-docs/src/views/card/card_example.js
- src/components/badge/beta_badge/_mixins.scss
- src/components/card/_card.scss
- src/components/card/card.js
You can pass any heading level h2-h6 to wrap the title in. It will default to span but also force to span if inside a button.
cc @timroes 
---
IE screenshot:
cc @bhavyarm
> EuiCard updates

- CHANGELOG.md
- src-docs/src/views/date_picker/global_date_picker.js
- src-docs/src/views/flex/direction.js
- src-docs/src/views/flex/flex_example.js
- src/components/flex/_flex_item.scss
- src/components/popover/_popover.scss
Removed IE flex column fix, in favor of forcing the consumer to add a `grow` prop. 
Added a IE message to docs.
> Depending on the nested structure of your flex groups, it is possible that flex-items inside a column directed flex group will not show. To counter this, add the grow prop and set to either false or a number. Setting grow to true will not suffice. You may also need to adjust the flex-basis value.
---
AND removed max-width on universal selector of popover children which messed up the popover title.
> Fixed regressions from Global Time Picker

- CHANGELOG.md
- src/components/index.d.ts
- src/components/toast/index.d.ts
Adds types for the `<EuiToast />`, `<EuiGlobalToastList />`, and `<EuiGlobalToastListItem />` components.
> [types/toast] add types for EuiToast, EuiGlobalToastList(Item)

- CHANGELOG.md
- package.json
- src-docs/src/views/xy_chart/responsive_chart.js
- src-docs/src/views/xy_chart/xy_chart_example.js
- src-docs/src/views/xy_chart_area/area_example.js
- src-docs/src/views/xy_chart_axis/xy_axis_example.js
- src-docs/src/views/xy_chart_bar/bar_example.js
- src-docs/src/views/xy_chart_histogram/histogram_example.js
- src-docs/src/views/xy_chart_histogram/time_histogram_series.js
- src-docs/src/views/xy_chart_line/line_example.js
- src/components/xy_chart/_xy_chart.scss
- src/components/xy_chart/axis/__snapshots__/default_axis.test.js.snap
- src/components/xy_chart/axis/__snapshots__/horizontal_grid.test.js.snap
- src/components/xy_chart/axis/__snapshots__/vertical_grid.test.js.snap
- src/components/xy_chart/axis/__snapshots__/x_axis.test.js.snap
- src/components/xy_chart/axis/__snapshots__/y_axis.test.js.snap
- src/components/xy_chart/crosshairs/__snapshots__/crosshair_x.test.js.snap
- src/components/xy_chart/crosshairs/__snapshots__/crosshair_y.test.js.snap
- src/components/xy_chart/series/__snapshots__/area_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/horizontal_bar_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/horizontal_rect_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/line_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/vertical_bar_series.test.js.snap
- src/components/xy_chart/series/__snapshots__/vertical_rect_series.test.js.snap
- src/components/xy_chart/utils/flexible.js
- src/components/xy_chart/xy_chart.js
- yarn.lock
This drops the use of native `react-vis` `makeVisFlexible` HOC in favour of the ResizeObserver to support resizing of the chart container as in kibana dashboard.
It also fix some resizing problem in flexbox discrovered on the new editor POC by @cchaos.
> Make EUIXYChart responsive using ResizeObserver

- CHANGELOG.md
- src-docs/src/views/combo_box/combo_box.js
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
- src/components/icon/__snapshots__/icon.test.js.snap
This is so you can find a specific combo box instance's options list. This wasn't previously possible because the options list is attached to the body element, not the combo box element.
> Assign EuiComboBox data-test-subj to the options list with a '-optionsList' suffix

- CHANGELOG.md
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
Fixes #860 
`EuiInMemoryTable`'s sorting operated on the saved reference to its `items` prop, and JS's sorting mutates the source which meant the original `items` array was itself sorted. Visually this caused non-deterministic sorting behaviour on the tables.
> Fix bug in EuiInMemoryTable to not mutate the items prop

- CHANGELOG.md
- src/components/basic_table/collapsed_item_actions.js
Fixes https://github.com/elastic/eui/issues/1068
> EuiBasicTable actions close their context menu when clicked.

- CHANGELOG.md
- package.json
- scripts/compile-scss.js
- yarn.lock
Like the summary says. I thought it might be slow to re-run PostCSS but in practice I couldn't tell. We still only run sass once.
I struggled to generate source maps, so if we want them then I'd appreciate some input.
> Build a minified version of each theme file using cssnano

- CHANGELOG.md
- src-docs/src/views/tables/in_memory/props_info.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
- src/components/table/table_header_cell.js
Closes #923 by adding an `onTableChange` callback to `EuiInMemoryTable`. This callback fires when table sorting or pagination is changed, and is meant to be informational only.
@timroes for code review
@snide to make sure the doc change makes sense
> Add onTableChange callback function to EuiInMemoryTable

- src-docs/src/views/icon/icon_example.js
This fixes the load bootup we're seeing in EUI. Icons aren't really usable in HTML anyway because you'd need to do your own compiling for the assets. Rather than remove the tab, figured it was better to explain this.
> [DOCS] Disable html preview for icons

- CHANGELOG.md
- src/components/mutation_observer/mutation_observer.js
Closes #1073
`EuiMutationObserver` does not actually require children to be passed. In #1073 the warning was given because `EuiFieldValueSelectionFilter`'s `searchBox` or `content` could be null, which propagates to the mutation observer as a `null` child.
> EuiMutationObserver does not require children

- src-docs/src/views/button/button_toggle.js
- src/components/flyout/_flyout.scss
- src/components/form/range/_range.scss
- src/components/modal/_modal.scss
- src/components/panel/_mixins.scss
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/_popover.scss
- src/components/popover/popover.js
- src/components/toast/_toast.scss
- src/components/tool_tip/_tool_tip.scss
- src/global_styling/mixins/_shadow.scss
- src/global_styling/variables/_animations.scss
- src/global_styling/variables/_borders.scss
- src/global_styling/variables/_shadows.scss
Fixes #1072 and #1056 
I adjusted the slight hue color to just be a bit darker and less opaque for the large shadows. Here are some before and afters:
And dark mode pretty much stays the same:
--- 
Oh and I threw in that quick fix we saw with the toggle icon button in the docs.
> Add defaults to borders and adjust shadows

- CHANGELOG.md
- package.json
Fix #1084 Add the `resize-observer-polyfill` as a `dependency`, previously was a `devDependency` and causes missing dependency error.
> Add resize-observer-polyfill as a dependency

- CHANGELOG.md
- src-docs/src/views/tool_tip/tool_tip_example.js
- src/components/index.d.ts
- src/components/tool_tip/index.d.ts
Add typings for the `EuiToolTip` and `EuiIconTip` components.
Before changes:
After adding types to my `node_modules`:
- Ensure the types I've defined are appropriate for the two components in question
- [EuiToolTip PropTypes](https://github.com/elastic/eui/blob/master/src/components/tool_tip/tool_tip.js#L196)
- [EuiIconTip PropTypes](https://github.com/elastic/eui/blob/master/src/components/tool_tip/icon_tip.js#L13)
> Add typings for EuiToolTip and EuiIconTip

- src-docs/src/views/tables/custom/custom.js
The docs' custom table OutsideClickDetector currently sets the component state _anytime_ the user clicks, not only when a custom action popover is open. The resulting setState and re-render takes ~500ms and blocks all other UI like _any_ sorting or pagination on the docs page. This lag really bothers me, so I've updated the custom table to only setState if it needs to close.
> Update Custom Table docs to not re-render on every. single. click.

- CHANGELOG.md
- src-docs/src/components/guide_section/guide_section.js
- src/global_styling/mixins/_typography.scss
- src/global_styling/utility/_utility.scss
- Moved properties from `.eui-textTruncate` into a mixin and including that mixin in the utility class
- Added `.eui-textBreakNormal` in case consumers need to override a applied `word-break: break-all`
- Using the above class on props doc table contents to fix #678
> Added more css text utilities

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
- src/components/combo_box/combo_box_options_list/combo_box_options_list.js
Fixes #1062 
Link to gif: https://d.pr/free/i/SEuUIY
> Added support for `fullWidth` on `EuiComboBox`

- CHANGELOG.md
- src-docs/src/views/form_controls/checkbox.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/form/_mixins.scss
- src/components/form/checkbox/checkbox.js
- src/components/form/checkbox/index.d.ts
> Support for indeterminate checkboxes

- CHANGELOG.md
- src-docs/src/views/form_controls/radio_group.js
- src/components/form/radio/__snapshots__/radio_group.test.js.snap
- src/components/form/radio/radio_group.js
- src/components/form/radio/radio_group.test.js
I need a way to disable radio group options individually.
> disable radio group option

- CHANGELOG.md
- src/components/popover/wrapping_popover.js
There is a bug in Kibana where the anchor element gets re-attached on `componentWillUnmount` even if the anchor element has been removed from the DOM.
To see the bug in action, first open a dashboard in edit mode and click the `Options` top nav button to open the Options popover.
Then click the `Cancel` top nav button (while the Options popover is still open). Dashboard will remove the `Options` top nav from the menu bar. but then `componentWillUnmount` will add it back.
It should look like this.
This PR only re-mounts the button component when it still has a parent (is attached to the DOM). I have tested this in Kibana and this fixes the problem shown above
> [EuiWrappingPopover] Do not re-mount button on componentWillUnmount if button has been unmounted from DOM

- CHANGELOG.md
- package.json
- src/index.d.ts
- src/test/index.d.ts
- yarn.lock
Closes #1100 by adding a TypeScript definition to `findTestSubject`. This allows finding data-test-ref elements wrapped by enzyme's `shallow` and `mount` methods.
> Add TS definition for findTestSubject

- src/components/form/radio/radio.js
- src/components/form/radio/radio_group.js
`EuiRadioGroup` in the following situation exposes the need to pass autoFocus to `EuiRadio`
* Inside of EuiContextMenu (or another component that sets focus on open)
* EuiRadioGroup is first component in a panel
* The first option is disabled
* The first option has a `EuiIconTip` in the label
The problem is that the tooltip opens when the panel is opened.
Setting autoFocus on the first enabled option solves this problem
> Allow setting autoFocus on radio group option

- src/components/avatar/index.d.ts
- src/components/form/field_search/index.d.ts
- src/components/index.d.ts
- src/services/color/index.d.ts
- src/services/index.d.ts
This PR adds typedefs for the following:
- `EuiAvatar` component
- `color` service
> Add typedefs for EuiAvatar component and color service

- CHANGELOG.md
- src-docs/src/views/flyout/flyout_complicated.js
- src-docs/src/views/flyout/flyout_example.js
- src-docs/src/views/flyout/flyout_large.js
- src-docs/src/views/flyout/flyout_max_width.js
- src-docs/src/views/flyout/flyout_small.js
- src/components/flyout/_flyout.scss
Fixes https://github.com/elastic/eui/issues/1122
I also added examples for the `maxWidth` prop and the large size flyout. @elastic/kibana-design In general, are we still trying to add examples to the docs site whenever we add new props?
> Fix bug with EuiFlyout maxWidth interfering with responsive mode.

- src-docs/src/views/tables/basic/props_info.js
- src-docs/src/views/tables/custom/custom.js
- src-docs/src/views/tables/custom/custom_section.js
- src-docs/src/views/tables/in_memory/in_memory.js
- src-docs/src/views/tables/paginated/paginated.js
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/basic_table/__snapshots__/pagination_bar.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/basic_table.test.js
- src/components/basic_table/in_memory_table.js
- src/components/basic_table/in_memory_table.test.js
- src/components/basic_table/pagination_bar.js
- src/components/basic_table/pagination_bar.test.js
- src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
- src/components/table/table_pagination/table_pagination.js
- src/components/table/table_pagination/table_pagination.test.js
On the APM team we are hoping to be able to hide the "per page" select box in table pagination, while still leaving the right-aligned page navigation buttons. (The default would be to show those options, which leaves everything working as-is.)
In master:
vs in this PR:
This PR addresses a few things:
- Adds a new property on the `pagination` object, called `disablePerPageOptions`
- The underlying `EuiTablePagination` component accepts this property and, when true, renders `null` in the left-aligned `EuiFlexItem` where that select box usually shows up, which keeps the rest of the layout in place
- `EuiBasicTable` also accepts this same property on its `pagination` object, and passes it along
- `EuiInMemoryTable` accepts the same property on its `pagination` object, and also passes it along …
> Adds ability to hide per page options when enabling table pagination

- src/global_styling/variables/_z_index.scss
> Fix combobox zindex

- CHANGELOG.md
- src/components/form/switch/index.d.ts
Fixes #1134 
There's no reason to omit `onChange` from the `InputHTMLAttributes<HTMLInputElement>`, as the callback function is passed straight into the input. This change removes that song and dance, cleanly indicating what props are available.
> Update the typedef for EuiSwitch's onChange prop

- CHANGELOG.md
- src/global_styling/functions/_colors.scss
Fixes #1156 
The color contrast function had a bad variable in it that was causing it to do its contrast check against the wrong color.
Hat tip to @chandlerprall for spotting it over my shoulder.
> Fix color contrast function

- CHANGELOG.md
- src-docs/src/views/context_menu/context_menu.js
- src/components/tool_tip/_tool_tip.scss
- src/components/tool_tip/tool_tip.js
Fixes #1155 
Mouse events aren't reliable on disabled inputs[1]. In the context menu case, the DOM is setup as
```
span[euiToolTipAnchor]
button[disabled]
span
```
the inner-most span still fires `mouseover` and `mouseout` events. `mouseover` triggers the tooltip to show, but when `mouseout` fires the related target is the disabled button, which is contained by the anchor so the tooltip isn't dismissed. As the button is disabled, it does not emit a `mouseout` event which is needed to close the tooltip.
As a work around, I added `pointer-events: none` to any direct descendant of the anchor when that child is disabled, and moved the event handlers to the anchor span.
[1] https://jakearchibald.com/2017/events-and-disabled-form-fields/
> Disable pointer-events on disabled children within EuiTooltip

- CHANGELOG.md
- src/components/tool_tip/tool_tip.js
Fixes Kibana issue https://github.com/elastic/kibana/issues/22543
Putting an EuiToolTip in a popover, opening the popover, and then using `esc` to close the popover causes `hideToolTip` to set state on an unmounted component.
> fix EuiToolTip from setting state on unmounted component

- CHANGELOG.md
- src/components/combo_box/combo_box_input/_combo_box_pill.scss
- src/components/combo_box/combo_box_input/combo_box_pill.js
Fixes #1168
- pass `onClick` and `onClickAriaLabel` properly
- Fix plain text vertical alignment in IE
**Before**
**After**
> Combobox fixes

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/pagination/pagination.js
- src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
The purpose of this PR is to add `data-test-subj` to `Pagination`'s _next_ and _previous_ buttons. I have a number of functional tests expecting a table's pagination to have these values, and when I replaced the existing table with `eui` components I got stuck. Link to those changes: https://github.com/elastic/kibana/pull/22902
I chose these values based on the existing naming used for the numbered buttons, per https://github.com/elastic/eui/blob/master/src/components/pagination/pagination.js#L33
_Note: anything unchecked here I did not feel was applicable, please let me know if I need to revisit any items_
> Decorate pagination 'next' and 'previous' buttons with data-test-subj

- CHANGELOG.md
- src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.js.snap
- src/components/tabs/tabbed_content/tabbed_content.js
This addresses the issue in https://github.com/elastic/kibana/issues/22293.  aria-controls was not being used properly in EuiTabbedContent component.  The original implementation switched the content's div id to contain selected tab id, which meant that the unselected tab(s) had an aria-controls that pointed at a nonexistent id.  This change just uses the rootID for all aria-controls, which matches how aria-controls should be used (it's supposed to indicate the part of the page the button will affect when clicked).
> fixing issue with aria controls and unselected tabs

- CHANGELOG.md
- src/components/tool_tip/tool_tip.js
Kibana's polyfill wasn't picking up the `document.contains()` bit in EUI tooltips. Used `document.body.contains()` instead, which is supported.
https://github.com/elastic/kibana/issues/22956
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains
> IE11 doesn't support document.contains()

- CHANGELOG.md
- src-docs/src/views/form_layouts/described_form_group.js
- src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
- src/components/form/described_form_group/described_form_group.js
- src/components/form/described_form_group/described_form_group.test.js
Sometimes the title speaks for itself 😄
> Make description prop optional for EuiDescribedFormGroup.

- CHANGELOG.md
- src/components/search_bar/query/default_syntax.js
- src/components/search_bar/query/default_syntax.test.js
closes #1177 
Addresses two string-related issues
* if a string value began with a number (e.g. `15m`) it would be parsed only as the leading number
* if a non-string value (e.g. `15`, `true`) was passed to a string-type field, it would fail to pass schema validation instead of being coerced to a string
> Better support for string values in search queries

- CHANGELOG.md
- src/components/flex/flex_group.js
- src/components/flex/index.d.ts
Add support for the `direction` prop of the `EuiFlexGroup` component for TypeScript.
*Note: any checks not completed were deemed unnecessary by me. Please let me know if any further check work needs to be done before this is ready to merge.*
> Add direction prop for EuiFlexGroup typing

- CHANGELOG.md
- src/components/empty_prompt/__snapshots__/empty_prompt.test.js.snap
- src/components/empty_prompt/empty_prompt.js
- src/components/series_chart/__snapshots__/series_chart.test.js.snap
- src/components/series_chart/_index.scss
- src/components/series_chart/_series_chart.scss
- src/components/series_chart/series/__snapshots__/area_series.test.js.snap
- src/components/series_chart/series/__snapshots__/line_series.test.js.snap
- src/components/series_chart/series/_area_series.scss
- src/components/series_chart/series/area_series.js
- src/components/series_chart/series/line_series.js
- src/components/series_chart/series_chart.js
- src/components/series_chart/series_chart.test.js
- src/components/series_chart/status-text.js
- src/components/series_chart/utils/visualization_color_type.js
I commented out the console warning (and tests) that displayed if you passed a color that is not one of the EUI vis palette colors. Every chart render would spit out this warning and would really overload the console output. I only commented it for now to allow us to revisit if necessary.
I kept the defaults of `1` but this helps to be able to lessen the line series border and area series fill.
Ex:
Also, changed some spacing to be conditional EuiEmptyPrompt (only add space between content and actions if both `body` and `actions` exist).
**Before**
**After**
> Some quick `EuiSeriesChart` additions

- CHANGELOG.md
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/flex/_flex_item.scss
- src/components/table/_table.scss
- src/components/table/_variables.scss
- src/components/table/table_row.js
When a row has an `onClick` applied to it, the row becomes keyboard-accessible (you can tab to it) and has a visual focus state.
> Make EuiBasicTable rows keyboard-accessible when they are clickable.

- CHANGELOG.md
- src-docs/src/views/flex/flex_example.js
- src/components/flex/__snapshots__/flex_grid.test.js.snap
- src/components/flex/_flex_grid.scss
- src/components/flex/flex_grid.js
`EuiFlexGrid` now accepts `columns={1}`. This was at the request of @walterra.
Screen just shows that it's working, I didn't add this example to the docs.
> FlexGrid now accepts columns={1}

- CHANGELOG.md
- src-docs/src/components/guide_components.scss
- src-docs/src/routes.js
- src-docs/src/views/color_palette/color_palette.js
- src-docs/src/views/color_palette/color_palette_custom.js
- src-docs/src/views/color_palette/color_palette_example.js
- src-docs/src/views/color_palette/color_palette_histogram.js
- src/components/series_chart/series/area_series.js
- src/components/series_chart/series/bar_series.js
- src/components/series_chart/series/histogram_series.js
- src/components/series_chart/series/horizontal_bar_series.js
- src/components/series_chart/series/horizontal_rect_series.js
- src/components/series_chart/series/line_series.js
- src/components/series_chart/series/vertical_bar_series.js
- src/components/series_chart/series/vertical_rect_series.js
- src/services/color/color_palette.js
- src/services/color/eui_palettes.js
- src/services/color/index.js
- src/services/index.js
Adds a service that accepts a palette name and returns an array of hexidecimal color codes for use in other EUI components such as charts.
You can either...
a) pull a palette by name from the eui_palettes file,
b) provide your own palettes file, or 
c) use the "custom" palette name along with two hex color codes and a number of stops for a gradiated array of hex color codes.
> Adds colorPalette service

- src-docs/webpack.config.js
Tells the webpack dev server to accept connections to any host name. This allows remote machines (and VMs) to connect by IP address without ngrok or similar.
> Allow devserver to be served from any host

- CHANGELOG.md
- src/components/tool_tip/_tool_tip.scss
Fixes #1211 
Disabled pointer events on _any_ disabled element that is a child of EuiToolTip, not only direct child descendants.
Tested on all browsers, this has a side effect that the disabled mouse cursor state does not trigger when hovering over the disabled element - except ironically in IE11 where you still see the disabled cursor.
> Disable pointer-events on all disabled descendents of tooltips

- CHANGELOG.md
- src/components/avatar/__snapshots__/avatar.test.js.snap
- src/components/avatar/avatar.js
- src/components/avatar/avatar.test.js
Fixes case where EuiAvatar's name is composed entirely of whitespace. Fixes #1230
> Allow avatar name to be composed entirely of whitespace

- CHANGELOG.md
- src/components/index.d.ts
- src/components/key_pad_menu/index.d.ts
Adding typings for `EuiKeyPad` and its item components.
> Add typings for EuiKeyPad

- CHANGELOG.md
- src/components/key_pad_menu/index.d.ts
- wiki/component-development.md
Fixes TypeScript definitions for `EuiKeyPadMenuItem` and `EuiKeyPadMenuItemButton`. Adds documentation around proper typing when passing props down to DOM elements.
> Fix EuiKeyPadMenu component ts prop defs

- package.json
Closes #1242 - not 100% why this fixes the issue, but the `test` script was calling out to `npm` to run linting & unit tests. I changed to use `yarn` instead and now Ctrl+C stops all execution.
> Use yarn to run 'test' sub-commands to allow propagating ctrl+c signal

- README.md
Addresses an out-of-date doc section brought up in #1239. Support for `npm` was removed in #1217.
> Update Installation readme section to reference yarn instead of npm

- CHANGELOG.md
- src/components/form/select/select.js
When I passed an empty string, 0 or false to the `value` prop in the `EuiSelect` component, I would get this React warning: 
```Warning: Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled select element and remove one of these props. More info: https://fb.me/react-controlled-components```
By switching from a falsy check to a check for null equality, these warnings no longer pop up for the falsy values.
> Fixes select warning on falsy value in EuiSelect

- CHANGELOG.md
- src/components/form/index.d.ts
- src/components/form/radio/index.d.ts
- src/components/form/radio/radio_group.js
- src/components/form/range/index.d.ts
Add TypeScript definitions for `EuiRange` and `EuiRadio`, and correct the definitions for `EuiRadioGroup`.
> Add TypeScript definitions for EuiRange and EuiRadio

- CHANGELOG.md
- src/components/common.d.ts
- src/components/flex/index.d.ts
- src/components/form/field_password/index.d.ts
- src/components/icon/index.d.ts
- src/components/modal/index.d.ts
- src/components/table/index.d.ts
Add TypeScript definitions for `EuiConfirmModal`, plus other definition fixes.
Notes:
* I changed the `AnyProps` definition to map to `any` values, because I observed that the existing definition was too restrictive.
* However it then removed it entirely from `EuiTableRow` because `AnyProps` wasn't necessary to allow e.g. `key` or `data-foo` props, and other table rows attributes are deprecated in HTML5.
* The `color` prop for `EuiIcon` actually allows 6 or 3 digit hex color codes, so I allowed `string` as a possible type. I left the existing values as documentation.
> Add TypeScript definitions for `EuiConfirmModal`

- .github/pull_request_template.md
- CHANGELOG.md
- src-framer/code/_framer_helpers/frame_size.tsx
- src-framer/code/description_list/description_list.tsx
- src-framer/code/text/text.tsx
Adds a version of the `EuiDescriptionList` component to Framer. To make things easier to use in Framer, it creates a single row containing `EuiDescriptionListTitle` and `EuiDescriptionListDescription` so you don't need to pass a full list. I added Framer props for the text content of these two.
I've published this in the Framer Store. Simply install it and have fun.
Not required.
> Description list framer component

- CHANGELOG.md
- src/components/tool_tip/index.d.ts
Adds TypeScript definition for EuiToolTip's `delay` prop.
> Add EuiToolTip's delay prop to TS def

- src/components/badge/index.d.ts
'left' and 'right' are both valid values for the iconSide prop in EuiBadge: https://github.com/elastic/eui/blob/5e06ca13c3bd8212bd901294719ace57d6c3b55c/src/components/badge/badge.js#L26-L29
> IconSide can be 'left' or 'right'

- CHANGELOG.md
- src/components/tabs/index.d.ts
- src/components/text/index.d.ts
Adds type definitions for the EuiTab and similar components.
> Add TS types for EuiTab/EuiTabs/EuiTabbedContent

- CHANGELOG.md
- src/components/form/super_select/_super_select.scss
- src/components/form/super_select/_super_select_control.scss
- src/components/form/super_select/super_select.js
- Fixed size of context menu when there’s no initial selection
- Don’t use underlines for focus states, but background colors instead - It's possible to have blocks of text as options which looks odd to underline a whole paragraph
---
Change this state to null:
https://github.com/elastic/eui/blob/f7fbd94f8bfb6f7b6f809f6d7f015c08d3df0326/src-docs/src/views/super_select/super_select.js#L33
----
> Some `EuiSuperSelect` fixes

- CHANGELOG.md
- scripts/compile-eui.js
- src/components/badge/index.d.ts
- src/components/error_boundary/index.d.ts
- src/components/icon/index.d.ts
- src/components/index.d.ts
- src/components/popover/index.d.ts
Add TS defs for beta and notifications badges, and popover titles.
Fix the main TS index file so that tab definitions are included.
Fix the build to ensure all required directories are created.
> Add TS defs for badges, popover titles, and other fixes

- CHANGELOG.md
- src/components/token/__snapshots__/token.test.js.snap
- src/components/token/index.js
- src/components/token/token.js
`SHAPES` and `COLORS` are now enumerated constants and exported
> `EuiToken` enums

- src/components/toast/__snapshots__/global_toast_list.test.js.snap
- src/components/toast/__snapshots__/toast.test.js.snap
- src/components/toast/toast.js
This adds a `data-test-subj` to toast messages. This gives the ability to processes that check the DOM of the page (Reporting, Selenium) to check if there is a toast message on the page.
> add data-test-subj to toast item container

- CHANGELOG.md
- src/components/combo_box/_combo_box.scss
Ugh... good catch @cjcenizal 
Fixes #1313
*Full width & compressed*
*Full width & compressed*
~- [ ] This was checked for breaking changes and labeled appropriately`
> Fix combobox full width size

- CHANGELOG.md
- src/components/basic_table/basic_table.js
- src/components/table/_responsive.scss
- src/components/table/table_row_cell.js
This fixes a prop-type warning and poor UI when you provide a non-string node. This PR also changes the `name` prop-type of action columns to node, leftover from https://github.com/elastic/eui/pull/1234.
> Convert table cell header into an empty string if it's been provided to EuiBasicTable as a non-string node.

- CHANGELOG.md
- src-docs/src/theme_dark.scss
- src-docs/src/theme_k6_dark.scss
- src-docs/src/theme_k6_light.scss
- src-docs/src/theme_light.scss
- src-docs/src/views/date_picker/_global_date_picker.scss
- src-docs/src/views/date_picker/date_picker_example.js
- src-docs/src/views/date_picker/global_date_picker.js
- src/components/button/button.js
- src/components/button/button_empty/button_empty.js
- src/components/button/index.d.ts
- src/components/date_picker/_date_picker_range.scss
- src/components/date_picker/date_picker_range.js
- src/components/form/_mixins.scss
Altered global date/time picker to use buttons instead of date inputs and adds the update button. The component just needed a few adjustments, mostly on the pattern side.
Still needs:
---
Includes a fix for #1207 (don’t shrink date picker icon)
---
- ~[ ] This was checked against keyboard-only and screenreader scenarios~ (different PR for that)
> Update global date picker

- CHANGELOG.md
- src-docs/src/views/super_select/super_select_complex.js
- src/components/form/super_select/__snapshots__/super_select_control.test.js.snap
- src/components/form/super_select/super_select_control.js
- src/components/form/super_select/super_select_control.test.js
If you provide `EuiSuperSelect` with an empty value `''`, then a react warning is displayed
This PR verifies that value is not `''` before setting the defaultValue
> EuiSuperSelect - check for empty string before setting defaultValue

- CHANGELOG.md
- src/components/expression/_expression.scss
Fixes #1324 by copying the expression button's active style to `:focus`.
> 1324: copy ExpressionButton's active state to a focused state

- src/components/form/field_text/index.d.ts
AFAICT we have to use `any` here. From https://www.typescriptlang.org/docs/handbook/jsx.html#the-jsx-result-type: 
> By default the result of a JSX expression is typed as any.
> Add prepend prop to EuiFieldText's typescript definition

- package.json
- yarn.lock
Addresses two newly flagged vulnerabilities in modules used in the dev / test environments. I removed the `iedriver` library altogether as it's using old library versions and not configured to work in the visual regression setup.
> Update adm-zip and semver dependency versions

- CHANGELOG.md
- src/components/flex/index.d.ts
Fixes #1325  by adding `baseline` as a possible value to `EuiFlexGroup`'s `FlexGroupAlignItems` type for `alignItems` prop
~- [ ] This required updates to Framer X components`
> Add 'baseline' value to EuiFlexGroup's FlexGroupAlignItems type

- src-docs/src/views/card/card_beta.js
- src-docs/src/views/context_menu/context_menu_with_content.js
Fixes https://github.com/elastic/eui/issues/1339 and makes the context panel docs a little more pretty / helpful.
> Context panel docs cleanup

- CHANGELOG.md
- src-docs/src/views/tables/actions/actions.js
- src/components/basic_table/basic_table.js
- src/components/basic_table/default_item_action.js
I updated the example to demonstrate the use case.
> Add support for href and target props in EuiBasicTable actions.

- .npmignore
- CHANGELOG.md
- packages/index.js
- packages/react-datepicker.js
- packages/react-datepicker/package.json
- packages/react-datepicker/yarn.lock
Changes `react-datepicker` build setup to output as commonjs. Changed `packages/index.js` to be commonjs as well. This fixes EUI in environments that don't support ES Modules, such as in Jest tests.
> Publish react-datepicker sub-package in commonjs format

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes https://github.com/elastic/eui/issues/1307
When I test this out locally the UX feels pretty intuitive to me. What does everyone else think?
> `EuiComboBox` converts entered text into a custom option on blur

- CHANGELOG.md
- src/components/badge/index.d.ts
Fixes `eui.d.ts` by removing the EuiNotificationBadge definition from `badge/index.d.ts`, as EuiNotificationBadge is now a TS component. I'll dig into validating `eui.d.ts` at build time to prevent these issues in the future.
> Remove EuiNotificationBadge from badge/index.d.ts

- CHANGELOG.md
- packages/react-datepicker.js
- packages/react-datepicker/docs-site/bundle.js
- packages/react-datepicker/src/date_utils.js
- packages/react-datepicker/src/index.jsx
- packages/react-datepicker/src/time.jsx
- src-docs/src/views/date_picker/time_select.js
react-datepicker `Time` onChange callback does not zero out milliseconds when setting the time. This PR fixes that problem so when times are selected, milliseconds are set to zero.
> set milliseconds to zero when handling time change in react-datepicker

- CHANGELOG.md
- src/components/combo_box/combo_box.js
([#1353](https://github.com/elastic/eui/pull/1353)) introduced a bug where empty pills were being added to combo boxes on click. This reverts that change. We can do a follow up PR later to fix.
> Revert combobox onblur pill creation in #1353 

- CHANGELOG.md
- src-docs/src/views/super_select/super_select.js
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/form/super_select/_super_select.scss
- src/components/form/super_select/super_select.js
- src/components/form/super_select/super_select.test.js
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/index.d.ts
- src/components/popover/popover.js
- src/components/popover/popover.test.js
- src/global_styling/mixins/_helpers.scss
- src/global_styling/reset/_index.scss
- src/global_styling/reset/_scrollbar.scss
This was needed for the following:
Fixes #1352 cc @cjcenizal 
> Some fixes for EuiSuperSelect and Firefox Scrollbars

- scripts/compile-eui.js
- scripts/dtsgenerator.js
- tsconfig-builttypes.json
Adds a step to `yarn build` that validates the generated _eui.d.ts_ file. This is prevent future regressions similar to #1359 
> Validate eui.d.ts after generating during build

- CHANGELOG.md
- src/components/form/super_select/super_select.js
The kibana GIS app places an EuiSuperSelect in a FlexItem that is unmounted when the user clicks cancel (first screen shot). If the menu is open when the cancel button is clicked, the EuiSuperSelect will be unmounted but `focusSelected` gets called afterward, via `requestAnimationFrame`, and this causes a hard crash (second screen shot, third error message). This PR just adds a check to ensure the component is still mounted before proceeding with the contents of the `requestAnimationFrame` callback.
> fix EuiSuperSelect from accessing ref when unmounted

- CHANGELOG.md
- src-docs/src/views/icon/icon_example.js
- src/components/accordion/__snapshots__/accordion.test.js.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/icon/__snapshots__/icon.test.tsx.snap
- src/components/icon/icon.test.tsx
- src/components/icon/icon.tsx
Allows any color value to be passed to `EuiIcon`
> Allow any <color> value in EuiIcon

- CHANGELOG.md
- src-docs/src/views/call_out/warning.js
- src/components/text/_text.scss
Fixes https://github.com/elastic/eui/issues/1372
I think this will work the way we expect `EuiText` to operate. If it's a regular anchor, pass on styling, but if it has a class, then ignore and use whatever it has. The assumption is that if you have a class on an anchor, you know how you want it styled.
> if no selector on anchor, don't style in EuiText

- CHANGELOG.md
- scripts/dtsgenerator.js
Closes #1388. The `src/custom_typings` directory contains some TS definitions that allows TS files to import images without complaint. However, these definitions were being included in `eui.d.ts`, which meant downstream projects couldn't include their own mechanisms for importing images. The fix is to exclude `custom_typings` from `eui.d.ts`
> Exclude `custom_typings` from `eui.d.ts`

- CHANGELOG.md
- src/components/color_picker/_color_picker.scss
Fixes https://github.com/elastic/eui/issues/1394. Sets parent to `relative` so color picker popup stays with color selector element when scrolled
> [EuiColorPicker] align color picker popup with color selector when page is scrolled

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
- src/components/combo_box/matching_options.js
Fixes #1386 
In single selection mode, when the option list is rendered, it will have the current option highlighted.
I didn't create any new props but if you don't want this to be the default behavior, I could create a new property under singleSelection to control this.
> Keep the currently selected item selected in the dropdown in single selection mode

- CHANGELOG.md
- src/components/list_group/list_group.js
While building out the new nav drawer, the following warning was recognized coming from the List Group component:
This prop did accept a React node in an earlier iteration and this line was not cleaned up when we moved away from that solution.
> Change extraAction PropType

- CHANGELOG.md
- src/components/form/range/range.js
Currently, `EuiRange` inputs are assigned a dynamic width based upon the number of characters in the `max` attribute. This PR accounts for the `min` attribute as well, and chooses the longer of the two when determining input width.
Addresses https://github.com/elastic/eui/issues/1403
-~ [ ] This was checked in dark mode~
> Account for min attribute when determining EuiRange input width

- CHANGELOG.md
- src/components/modal/index.d.ts
- src/components/popover/index.d.ts
Adds type definitions for the `initialFocus` prop available on `EuiModal` and `EuiPopover`
(discovered via https://github.com/elastic/kibana/pull/28195)
> Adds initialFocus prop typedefs

- package.json
- yarn.lock
Clears a GitHub security alert around `webpack-dev-server` (https://nvd.nist.gov/vuln/detail/CVE-2018-14732). This vulnerability has/had no real effect on EUI unless you are running EUI locally with the port publicly available and are writing any code you don't want anyone to see.
~- [ ] This was checked against keyboard-only and …
> Upgrade webpack-dev-server devDependency

- package.json
- packages/react-datepicker/package.json
- packages/react-datepicker/yarn.lock
- yarn.lock
Updates the version of `webpack-dev-server` in our fork of `react-datepicker`, this addresses a GitHub vulnerability alert.
> Upgrade webpack dev server

- CHANGELOG.md
- src/components/search_bar/query/default_syntax.js
- src/components/search_bar/query/default_syntax.test.js
- yarn.lock
Fixes #1409 by adding support for non-western/latin/ASCII characters & punctuation within term & field values. This casts a wide net, allowing any and all UTF-16 characters in the range `U+00C0`-`U+FFFF` (begins in [Latin-1 Supplement](https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin-1_Supplement)). It's highly unlikely we would want to use any character in that range for another purpose in queries.
**Implementation**
I added the `U+00C0`-`U+FFFF` range as a supported value within the grammar's `wordChar` entry. [PEG.js doesn't understand regex character classes](https://github.com/pegjs/pegjs/issues/247) so this abuses the fact that character ranges only care about byte code values. The exact characters for `U+00C0` and `U+FFFF` are injected into the grammar's source …
> Support non-ASCII characters in EuiSearchBar & Query

- src-docs/src/views/badge/badge_example.js
- src-docs/src/views/button/button_example.js
- src-docs/src/views/form_controls/form_controls_example.js
- src-docs/src/views/guidelines/colors.js
- src-docs/src/views/guidelines/sass.js
- src-docs/src/views/home/home_view.js
- src-docs/src/views/list_group/list_group_links.js
- src-docs/src/views/toggle/toggle_example.js
- wiki/documentation-guidelines.md
Fixes #1387 and normalizes use of `<Link />` vs. `<EuiLink />` as they pertain to internal and external links in the docs.
> Fix broken docs links

- CHANGELOG.md
- src/components/code/_code_block.js
Propagate `className` in `EuiCodeBlock` in fullscreen mode, not just regular mode.
> Propagate className in EuiCodeBlock in fullscreen mode

- CHANGELOG.md
- src/components/accessibility/keyboard_accessible.ts
- src/components/common.ts
- yarn.lock
Aligns EUI's @types/react & @types/prop-types versions with Kibana
> rollback @types versions for react & prop-types to support Kibana

- CHANGELOG.md
- src/components/combo_box/combo_box.js
- src/components/combo_box/index.d.ts
Useful for focusing comboboxes from a parent component
> Add inputRef prop to combobox like other EUI form elements

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box.test.js
Fixes #1430 
IE11 doesn't include `relatedTarget` on `onBlur` events (it's a non-standard property on that event). `relatedTarget` _is_ included with `onFocusOut` but React doesn't support that event. This change manually manages the `focusout` event handler through ref updates, so IE11 provides the necessary data.
> 1430: fix combobox item selection in IE11

- src-docs/src/routes.js
- src-docs/src/views/nav_drawer/nav_drawer.js
- src-docs/src/views/nav_drawer/nav_drawer_example.js
- src/components/header/__snapshots__/header_logo.test.js.snap
- src/components/header/_index.scss
- src/components/header/_variables.scss
- src/components/header/header_logo.js
- src/components/header/header_section/_header_section_item.scss
- src/components/index.js
- src/components/index.scss
- src/components/list_group/_list_group_item.scss
- src/components/nav_drawer/_index.scss
- src/components/nav_drawer/_nav_drawer.scss
- src/components/nav_drawer/_nav_drawer_flyout.scss
- src/components/nav_drawer/_nav_drawer_menu.scss
- src/components/nav_drawer/_variables.scss
- src/components/nav_drawer/index.js
- src/components/nav_drawer/nav_drawer.js
- src/components/nav_drawer/nav_drawer_flyout.js
- src/components/nav_drawer/nav_drawer_menu.js
Adds a component named `EuiNavDrawer` that wraps one or more `EuiListGroup` components into an interactive side nav. It is designed to be used in conjunction with `EuiHeader` and, relatedly, resulted in a couple of minor changes to the `EuiHeader` design, most notably shortening its height from 64 to 48 pixels.
While keyboard accessibility is possible, it would be improved by using focus-trap for the sub menu that slides out. I attempted to get this working and while I could trap the focus in the flyout/sub menu, I could not get it to return focus to the triggering element upon pressing the `esc` key. 
Long story short, I could use some help sorting this out.
> Adds side nav component (EuiNavDrawer)

- CHANGELOG.md
- src-docs/src/views/button/button_example.js
- src-docs/src/views/button/button_group.js
- src/components/button/button_group/__snapshots__/button_group.test.js.snap
- src/components/button/button_group/button_group.js
- src/components/form/switch/_mixins.scss
- src/global_styling/reset/_reset.scss
This is what would happen in Kibana. So I just `!important`ed the `opacity: 0` of the hidden input.
But `legend` is only screen-reader accessible. Which works great with the Mac OS screen reader:
But Chrome Vox doesn't...
But it's the same functionality as https://www.w3.org/WAI/tutorials/forms/grouping/
Anyone have any thoughts? Acceptable? Or different approach?
> Button group fixes

- CHANGELOG.md
- src-docs/src/views/nav_drawer/nav_drawer.js
- src/components/header/_header_logo.scss
A few miscellaneous fixes are combined in this PR:
1. Forgot the CHANGELOG entry on my `EuiNavDrawer` PR https://github.com/elastic/eui/pull/1427
2. Discovered a misspell to a variable name
3. Added more time to OutsideClickDetector to prevent it from immediately closing on mobile toggle
4. Reduced padding on `EuiHeaderLogo` (used in Kibana) to align logo button with new nav width
> Misc small fixes related to nav drawer

- CHANGELOG.md
- src-docs/src/views/nav_drawer/nav_drawer.js
- src/components/header/_header_logo.scss
I got crossed up checking between EUI and Kibana for the precise `EuiHeaderLogo` width and was off by 1px. This PR adds that extra 1px width to account for the right border while also updating the `EuiNavDrawer` docs example to use `EuiHeaderLogo` (to match the Kibana setup and the Header docs example).
> Fixes header logo width and updates drawer example

- CHANGELOG.md
- src/global_styling/variables/_typography.scss
@weltenwort Caught a bug during the assets build process that spit out the monospace font as:
```
"euiCodeFontFamily": "Roboto Mono Consolas Menlo 'courier', 'new' monospace",
```
This just removes `new` and fixes spacing issues to it now spits out as:
```
"euiCodeFontFamily": "'Roboto Mono', 'Consolas', 'Menlo', 'Courier', monospace",
```
- ~[ ] This required updates to Framer X …
> Fix font stack for monospace font

- CHANGELOG.md
- package.json
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
- scripts/jest/setup/enzyme.js
- src-docs/src/routes.js
- src-docs/src/services/string/render_to_html.js
- src-docs/src/views/context/context.js
- src-docs/src/views/context/context_example.js
- src-docs/src/views/i18n/i18n_basic.js
- src-docs/src/views/i18n/i18n_example.js
- src-docs/src/views/i18n/i18n_multi.js
- src-docs/src/views/i18n/i18n_number.js
- src-docs/src/views/i18n/i18n_renderprop.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/context/context.tsx
- src/components/context/index.ts
- src/components/i18n/i18n.tsx
- src/components/i18n/i18n_number.tsx
- src/components/i18n/index.ts
- src/components/index.js
- src/components/search_bar/filters/__snapshots__/field_value_toggle_group_filter.test.js.snap
- src/components/table/table_pagination/table_pagination.js
- yarn.lock
These changes were previously merged in and then reverted as Kibana's unit testing did not support the new React context components. As of https://github.com/elastic/kibana/pull/24707 this is supported, so we are re-adding these changes.
> Re-add I18n components

- CHANGELOG.md
- src/components/accordion/__snapshots__/accordion.test.js.snap
- src/components/accordion/accordion.js
The `<button>` in `<EuiAccordion>` doesn’t set a type, so it triggers the submit action in forms.
> Set `type="button"` on accordion buttons

- CHANGELOG.md
- src-docs/src/views/progress/progress_example.js
- src-docs/src/views/progress/progress_fixed.js
- src/components/progress/_progress.scss
In cases where `EuiProgress` is nested within a parent whose `z-index` value is lower than `EuiHeader` (e.g. from a Kibana plugin), the header will overlay the progress bar preventing it from being seen.
To overcome this situation, a user will need to use an `EuiPortal` while the `EuiProgress` needs a `z-index` greater than the default for `EuiHeader`. This PR adds a `z-index` to `EuiProgress` and provides an example use case in the docs.
> Position EuiProgress over EuiHeader

- src/components/form/form_label/_form_label.scss
- src/global_styling/reset/_reset.scss
@w33ble noticed some inheritance problems with fonts in https://github.com/elastic/kibana/pull/29152. I also heard word from @gjones that there was some other weirdness going on in Cloud. @cchaos and I tracked it down to some over reliance on `inherit` with our reset file. We only use two fonts in EUI, the codey one and the not codey one. More explicitly declaring these in our reset fixes the issues we saw with Joe.
@cchaos I added pre on here because it fits the definition of the default. https://www.w3schools.com/tags/tag_pre.asp
Note to @zumwalt, since I like to alert everyone anytime I edit a reset file in EUI.
I also upped the weight of the form labels, which were a little weak with the new font.
> Font reset is more precise, fix form label weights

- CHANGELOG.md
- src/components/date_picker/super_date_picker/super_date_picker.js
Some more clean-up discovered from integrating EuiSuperDatePicker into Kibana QueryBar
1) `onTimeChange` is not getting called on each update when `showUpdateButton` is false
2) Need a way to know when `onTimeChange` is triggered from quick selection so the results can be applied immediately.
> EuiSuperDatePicker - always call onTimeChange when showUpdateButton is false

- CHANGELOG.md
- src/theme_light.scss
- src/themes/eui/eui_colors_light.scss
Because Kibana switches themes by doing some string magic on the sass files themselves we need to make an `eui_colors_light.scss` file to swap against `eui_colors_dark.scss`. This file changes nothing in the build of EUI itself, and although empty, does provide some symmetry to our theming system and load order.
Checklist not needed. This is an empty change for EUI, but a CL item will be added for documentation.
> Default light theme now comes with an empty light colors file

- CHANGELOG.md
- src/global_styling/mixins/_typography.scss
- src/global_styling/variables/_typography.scss
- src/themes/k6/k6_globals.scss
Fixes Safari only showing italics.
> Don’t add the variant font family

- CHANGELOG.md
- src/components/header/_header_logo.scss
- src/components/header/_variables.scss
- src/components/header/header_section/_header_section_item.scss
- src/components/nav_drawer/_nav_drawer.scss
- src/components/nav_drawer/_variables.scss
The header was being too squished in height on mobile screens. This PR just keeps the height from changing (but still allows the buttons to squish in width).
To @ryankeairns : I moved the `min-width: 49px` to just the header logo because it was causing the spaces avatar to look off-center. Though when I look at it without that the button seems to still render at 49px wide (probably because the 'border' is at `right: 0`. But anyhow, you can double-check that part and let me know if you'd rather me put it back the way it was.
- ~[ ] This was checked against …
> Don’t reduce header at at mobile size

- CHANGELOG.md
- src/components/date_picker/super_date_picker/super_date_picker.js
Invalid ranges are not colored as invalid because `isInvalid` was not getting calculated by `getDerivedStateFromProps`. Other than that, things are looking really good with embedding EuiSuperDatePicker in Kibana's QueryBar
> EuiSuperDatePicker determine state.isInvalid on props update

- CHANGELOG.md
- src/components/icon/__snapshots__/icon.test.tsx.snap
- src/components/icon/assets/logo_apm.svg
The logo wasn't properly aligned with the artboard.
**before**
**after**
> Fix APM logo

- CHANGELOG.md
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Fixes #1376. This extends our typescript->proptypes babel plugin to also remove any types or interfaces from ExportNamedDeclarations e.g. `export { Foo, Bar }` & `export { Foo, Bar } from './source';`. Added this functionality to the existing plugin for two reasons: 1. no build tooling in TS or Babel performs this transformation 2. our plugin already tracks variable type information across imports.
I tested this change in create-react-app by generating an npm module tarball with `npm pack` and adding the contents of that tarball as a dependency in a new CRA project.
~- [ ] This was checked against …
> Remove TS types & interfaces from ES exports

- CHANGELOG.md
- src/components/text/index.d.ts
This also adds the missing definition for `EuiTextAlign` and the missing `align` property from `EuiText` for TypeScript usage, and the missing `m` value for the text size of `EuiText`.
> [EuiText] Add 'align' property

- CHANGELOG.md
- src/services/popover/popover_positioning.test.ts
- src/services/popover/popover_positioning.ts
Addresses a bug @nreese found in https://github.com/elastic/kibana/pull/29235
The tooltip has a whitespace buffer of 16px, and its arrow must be 4px from its edge. Nathan's super update button is less than 16px from the right side of the screen; the calculations were shifting the popover to meet the buffer but didn't properly account for the 4px needed for the arrow, which forced the popover to an undesired position.
@nreese mind building the fix and confirming it works in your Kibana branch?
> Updated popover position to correctly address arrow buffer

- CHANGELOG.md
- src/components/date_picker/super_date_picker/date_popover/date_popover_button.js
- src/components/date_picker/super_date_picker/super_date_picker.js
There is a bug were updating props resets EuiSuperDatePicker `showPrettyDuration`. The bug occurs when either start or end `EuiSuperDatePicker` is open. Clicking on the tabs changes the respective time and calls `onChange` causing EuiSuperDatePicker.getDerivedStateFromProps to potentially set `showPrettyDuration` to true. This causes the  `EuiDatePopoverButton` to close unexpectedly because the component is unmounted. The bug is that displaying the pretty duration check only looks at `showPrettyDuration` and does not take into account if the date popovers are open. 
This PR moves the tracking of EuiDatePopoverButton isOpen state into EuiSuperDatePicker so that the pretty duration is only displayed when `showPrettyDuration` is true and the date popovers are not open.
> EuiSuperDatePicker move EuiDatePopoverButton isOpen state into EuiSuperDatePicker

- src-docs/src/views/search_bar/search_bar_example.js
Related to #1441. Adds documentation around `EuiSearchBar`'s date value parsing & usage.
@snide this is ugly and could probably use a designer's touch.
> Add docs around EuiSearchBar's date parsing

- CHANGELOG.md
- src/components/date_picker/super_date_picker/quick_select_popover/refresh_interval.js
Resolves #1502.
Adds 'seconds' option to the Refresh Interval selection
> EuiSuperDatePicker: add seconds unit option to refresh interval

- CHANGELOG.md
- src-docs/src/views/modal/confirm_modal.js
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/modal/confirm_modal.js
- src/components/modal/confirm_modal.test.js
Resolves #1382.
Prevents empty `EuiModalBody` from rendering in `EuiConfimModal`
> prevent modalBody render if no children provided

- CHANGELOG.md
- src/global_styling/mixins/_typography.scss
- src/global_styling/variables/_typography.scss
@bmcconaghy noticed some issues with console and tracked to down to a Kibana upgrade of EUI from 6.3.1 to 6.5.1. I picked up the trail and tracked it down to these lines
https://github.com/elastic/eui/blob/master/src/global_styling/mixins/_typography.scss#L12
https://github.com/elastic/eui/blob/master/src/global_styling/variables/_typography.scss#L30
I don't think this is a problem with the code in EUI but a weird bug in ACE and the way they [calculate cursor position based off character widths](https://github.com/ajaxorg/ace/issues/3037). Unfortunately we use ACE everywhere in Kibana and I'd rather cut this off here than add a lot of overwrites into our ACE implementation there. I'll be honest and say I don't know enough about this property to understand much of what it does other than …
> Fix ligature issue in ACE

- CHANGELOG.md
- src-docs/src/components/guide_components.scss
- src/components/page/_page.scss
When the background color was updated to be a bit lighter, the page background did not get updated as well, so it ended up like this:
Now it it's the same lighter color:
> Update page background to match body background

- CHANGELOG.md
- src/components/pagination/pagination.js
Refactor of `EuiPagination` for I18n didn't move the React keys to the new wrapping elements.
> Move pagination react keys onto wrapping elements

- CHANGELOG.md
- src/components/nav_drawer/_nav_drawer.scss
- src/components/nav_drawer/_variables.scss
Two minor animation speed adjustments to address feedback from internal K7 users.
These values are currently inlined on this Kibana PR to get in for FF - https://github.com/elastic/kibana/pull/29978
> Speed up collapsing animation for EuiNavDrawer

- CHANGELOG.md
- src/global_styling/variables/_colors.scss
Related to https://github.com/elastic/kibana/pull/30136#issuecomment-460841965
Makes the dark BG less dark so that it fits closer to the contrast patterns we have going in the light mode.
> Slight tweak with dark bg color

- CHANGELOG.md
- src/components/search_bar/query/__snapshots__/ast_to_es_query_string.test.js.snap
- src/components/search_bar/query/ast_to_es_query_string.js
- src/components/search_bar/query/ast_to_es_query_string.test.js
Summarize your PR. If it includes design elements include a screenshot or gif.
> Fix #1520 match_all query should be "*"

- CHANGELOG.md
- src/components/date_picker/super_date_picker/date_modes.js
- src/components/date_picker/super_date_picker/date_popover/absolute_tab.js
- src/components/date_picker/super_date_picker/date_popover/relative_tab.js
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
- src/components/date_picker/super_date_picker/super_date_picker.js
fixes https://github.com/elastic/eui/issues/1536
Negative relative dates caused `dateMath.parse` to return undefined. This PR protects against undefined results from `dateMath.parse`
The PR also updates relative panel to not call the callback for negative values and instead display a validation error in the panel
> EuiSuperDatePicker - safely handle negative relative times

- CHANGELOG.md
- src-docs/tslint.yaml
- src-docs/webpack.config.js
Now that we've merged #1529, all TypeScript files will trigger lint warnings if their formatting needs updating with Prettier (which can be done by fixing with the linter). So far, so good.
However, the Webpack config for `src-docs` pulls in the project's TypesScript and TSLint settings, meaning that Webpack won't compile any TS files that have lint problems. We don't need checking at this stage to be so strict, because the pre-commit hook and general lint task already check everything.
So, in order to stop docs development from being annoying, I've customised the TSLint settings when running `src-docs` so that lint problems are now warnings, instead of errors. They'll still have to get fixed before committing.
> Make TSLint issues be warnings, not errors, when running `src-docs`

- CHANGELOG.md
- src-docs/src/views/date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/date_popover/absolute_tab.js
- src/components/date_picker/super_date_picker/date_popover/relative_tab.js
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
- src/components/date_picker/super_date_picker/super_date_picker.js
EuiSuperDatePicker start and end props expect string values. This PR makes sure invalid values do not crash the component and allow users to recover by keeping the component working so they can set valid values. The PR updates the docs example so users can set anything for start and end and see how it behaves
dateMath.parse returns undefined for values like `now--15m` and an invalid moment for values like `badinput`. The logic had to be updated to ensure the moment returned from dateMath.parse exists and is also valid
> EuiSuperDatePicker handle invalid start and end property values

- src-docs/src/views/search_bar/props_info.js
- src-docs/src/views/search_bar/search_bar_example.js
Fixes #1547, updates the manual docgen values around `FieldValueToggleGroupFilter` & `FieldValueToggleGroupFilterItemType`
> Fix EuiSearchBar's proptype docs around FieldValueToggleGroupFilter

- CHANGELOG.md
- src-docs/src/views/date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.js
- src/components/date_picker/super_date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/types.js
Add `customQuickSelectPanels` prop to EuiSuperDatePicker.
This prop will allow users to extend EuiSuperDatePicker quick select menu. One such use case is for selecting the entire data set range in Kibana
> EuiSuperDatePicker - add customQuickSelectPanels prop

- CHANGELOG.md
- src-docs/src/components/guide_section/guide_section.js
- src-docs/src/components/guide_section/guide_section_types.js
- src-docs/src/views/code/code_block.js
- src-docs/src/views/code/code_example.js
- src-docs/src/views/progress/progress.js
- src-docs/src/views/progress/progress_example.js
- src/components/code/_code_block.js
- src/components/code/_code_block.scss
- src/components/code/index.d.ts
- src/components/progress/progress.js
This PR has two related objectives:
1. Add an optional 'copy' icon button to `EuiCodeBlock` via an `isCopyable` prop.
2. Add a `snippet` prop to `GuideSection` that optionally displays a new Snippet tab. This essentially allows an EUI docs user to copy code without having to wade through all the demo code in the Javascript tab. It won't be appropriate for all components, but likely for the majority. See it in action on the Code and Progress pages.
^ Something to consider is that what we provide in the snippet may be proliferated. In other words, we should likely put the preferred settings in there. The catch to that is we'd like to demonstrate some available props which, in the preferred state, commonly use the defaults. The moral of the story is to be thoughtful with what we put into the …
> Adds ability to copy EuiCodeBlock and adds snippet prop to docs

- src-docs/src/components/guide_components.scss
- src-docs/src/components/guide_locale_selector/guide_locale_selector.js
- src-docs/src/components/guide_page/guide_page_chrome.js
- src-docs/src/components/guide_theme_selector/guide_theme_selector.js
- src-docs/src/views/package/i18n_tokens.js
Moves the theming and translation options into their own "Docs options" popover. Figure we'll only have more of these kinds of things, and it will be a nice spot to drop docs versioning as well.
Links to the correct line on github and styles up this page a little better
> Move docs options into their own popover

- CHANGELOG.md
- src/components/form/field_text/index.d.ts
Fixes CI error I'm getting here https://kibana-ci.elastic.co/job/elastic+kibana+pull-request/772/JOB=kibana-ciGroup1,node=immutable/console
> Add append prop to EuiFieldText

- CHANGELOG.md
- src/components/button/index.d.ts
add iconSize to ButtonIcon type definition
- ~~[ ] This was checked in mobile~~
- ~~[ ] This was checked in IE11~~
- ~~[ ] This was checked in dark mode~~
- ~~[ ] Any props added have proper autodocs~~
- ~~[ ] Documentation examples were added~~
- ~~[ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked appropriately~~
- ~~[ ] This was checked for breaking changes and labeled appropriately~~
- ~~[ ] Jest tests were updated or added to match the most common scenarios~~
- ~~[ ] This was checked against keyboard-only and screenreader scenarios~~
- ~~[ ] This required updates to Framer X components~~
> add iconSize to ButtonIcon type definition

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #1451 by adding a bit more logic to determine whether to allow or disallow `tab` from exiting `EuiComboBox` focus.
Note that the bug only impacted the single select variation of the combo box.
Testing/reproduction can be done in the EUI docs site (Combo Box > Single Selection):
* Tab into the combo box
* Use arrow keys to select an option
* Hit enter
* Hit tab; caret should have focus
* Hit tab again; focus should move to the next relevant element
Previously, the last step would never move focus off the caret …
> EuiComboBox keyboard navigation: tab exit

- CHANGELOG.md
- package.json
Fixes #1578. Adds `"license": "Apache-2.0"` to `package.json`
> add license to package.json

- CHANGELOG.md
- src-docs/src/views/range/dual_range.js
- src-docs/src/views/range/input.js
- src-docs/src/views/range/levels.js
- src-docs/src/views/range/range.js
- src-docs/src/views/range/range_example.js
- src-docs/src/views/range/states.js
- src-docs/src/views/range/ticks.js
- src/components/form/range/__snapshots__/dual_range.test.js.snap
- src/components/form/range/__snapshots__/range.test.js.snap
- src/components/form/range/__snapshots__/range_levels.test.js.snap
- src/components/form/range/__snapshots__/range_track.test.js.snap
- src/components/form/range/_range_input.scss
- src/components/form/range/_range_slider.scss
- src/components/form/range/_range_tooltip.scss
- src/components/form/range/dual_range.js
- src/components/form/range/dual_range.test.js
- src/components/form/range/range.js
- src/components/form/range/range.test.js
- src/components/form/range/range_input.js
- src/components/form/range/range_levels.js
- src/components/form/range/range_levels.test.js
- src/components/form/range/range_slider.js
- src/components/form/range/range_ticks.js
- src/components/form/range/range_tooltip.js
- src/components/form/range/range_track.js
- src/components/form/range/range_track.test.js
- src/components/icon/__snapshots__/icon.test.tsx.snap
- src/components/loading/__snapshots__/loading_kibana.test.js.snap
- Gave the inputs a min-width in case of single digits. And remove shifting of inputs because they then don’t line up with other form rows
- Custom tick values now properly account for minimum value
- Fix styling of track color when not showing the range
- Top level `className` now applied to the top level wrapper
- Fixed prepend/append of value
- Moved dual range handles to min **and max** positions if the values are empty
- Dual range inputs account for both min and max for sizing
The [EuiRangeTrack](https://github.com/elastic/eui/compare/master...cchaos:dual-range-css-fixes?expand=1#diff-ba1a2287cccb3dc491b2faa5ad592ffe) and [EuiRangeLevels](https://github.com/elastic/eui/compare/master...cchaos:dual-range-css-fixes?expand=1#diff-c3982e95736ab0d1909eff527618ee6b) now handle some errors …
> EuiRange and EuiDualRange fixes

- CHANGELOG.md
- src-docs/src/views/date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.js.snap
- src/components/date_picker/super_date_picker/async_interval.js
- src/components/date_picker/super_date_picker/async_interval.test.js
- src/components/date_picker/super_date_picker/super_date_picker.js
When setting the refresh rate on `EuiSuperDatePicker` it should keep track of the interval, and call the `onRefresh` handler whenever the interval fires.
This will save consumers the hassle of implementing this logic themselves.
> [EuiSuperDatePicker] Add `onRefresh` handler

- package.json
- scripts/compile-scss.js
- scripts/sass-extract-js-plugin.js
- yarn.lock
Closes #1588
- Inline sass-extract-js plugin
- Remove camelCasing logic
- Preserve hex values where possible
Diff of the light theme with the new variables: https://www.diffchecker.com/XyqCx9Cs
> Inline sass-extract-js plugin

- CHANGELOG.md
Missing changelog comments from https://github.com/elastic/eui/pull/1590
Variables affected by camel casing change:
- euiSizeXs -> euiSizeXS
- euiSizeXl -> euiSizeXL
- euiSizeXxl -> euiSizeXXL
- euiFontSizeXs -> euiFontSizeXS
- euiFontSizeXl -> euiFontSizeXL   
- euiFontSizeXxl -> euiFontSizeXXL
Full list of variable changes: https://www.diffchecker.com/ocT4Z4lA
> Add "Inline sass-extract-js plugin" to changelog as Breaking Change

- CHANGELOG.md
- src-docs/src/views/facet/facet_example.js
- src-docs/src/views/filter_group/filter_group.js
- src-docs/src/views/filter_group/filter_group_example.js
- src/components/avatar/_avatar.scss
- src/components/badge/notification_badge/__snapshots__/badge_notification.test.tsx.snap
- src/components/badge/notification_badge/_notification_badge.scss
- src/components/badge/notification_badge/badge_notification.test.tsx
- src/components/badge/notification_badge/badge_notification.tsx
- src/components/facet/__snapshots__/facet_button.test.js.snap
- src/components/facet/_facet_button.scss
- src/components/facet/_index.scss
- src/components/facet/facet_button.js
- src/components/facet/facet_button.test.js
- src/components/facet/index.d.ts
- src/components/filter_group/__snapshots__/filter_button.test.js.snap
- src/components/filter_group/_filter_button.scss
- src/components/filter_group/filter_button.js
- src/components/filter_group/filter_button.test.js
- src/components/filter_group/index.d.ts
- src/components/icon/_icon.scss
- src/components/index.d.ts
- src/components/loading/_loading_spinner.scss
- src/global_styling/mixins/_typography.scss
Essentially, this PR aligns the EuiFilterButton styles too look similar to the EuiFacetButton. It also means allowing to pass the "total available filters" when none are selected:
As well as highlight when there are selected filters:
Which meant adding `numActiveFilters` to EuiFilterButton.
As a reference, this is what the facet buttons look like
---
I had originally attempted to convert them to TS, but because they each imported a non-TS'd component or the props of one, I couldn't do it. Maybe someone with better TS chops than me can. But I did make sure the TS def's were up to date so it will be easier to convert down the line.
---
Added some extra props to `EuiNotificationBadge`:
- `size`: s, m (default: s)
- `color`: accent, subdued (default: accent)
I also did some quick updates to …
> Align Filter and Facet button styles

- CHANGELOG.md
- src/components/button/button_group/button_group.js
- src/components/button/index.d.ts
- src/components/filter_group/index.d.ts
* EuiFilterButton was missing props in the shipped types (it was only using `EuiEmptyButtonProps` but it accepts about 5 extra props)
> A few fixes required to get eui@8.x working in Kibana

- src-docs/src/views/guidelines/sass.js
Edits to text for spelling, punctuation, and word usage.
Also, 404 errors for two links (lines 554-555):
` <EuiText grow={false} className="guideSection__text">
<p>
View the <Link to="https://github.com/elastic/eui/blob/master/src/global_styling/variables/_typography.scss">variable</Link>
{' '} and <Link to="https://github.com/elastic/eui/blob/master/src/global_styling/mixins/_typpography.scss">mixins</Link>
{' '}sass code for typography.
`
Would using the `<EuiLink>` tag instead fix the broken links?
` <EuiText grow={false} className="guideSection__text">
<p>
View the <EuiLink href="https://github.com/elastic/eui/blob/master/src/global_styling/variables/_typography.scss">variable</EuiLink>
{' '} and <EuiLink href="https://github.com/elastic/eui/blob/master/src/global_styling/mixins/_typog …
> Edits to text in guidelines/sass.js

- src-docs/src/routes.js
- src-docs/src/views/guidelines/toasts.js
- src-docs/src/views/modal/overflow_test.js
Fixes https://github.com/elastic/eui/issues/393 by providing guidelines for how to handle long messages in toasts. We discussed this in our design meeting and decided that it didn't make sense to build this INTO toasts, and should instead just be a guideline, since one size will never fit all in this case.
> Add guidelines for toasts that have long messages

- CHANGELOG.md
- src/components/toast/global_toast_list.js
Fixes #1595, in which attempts to do calculations on a element that had become `null` caused errors.
* Cancel `requestAnimationFrame` updates in `componentWillUnmount`
* Prevent accessing properties on a `null`ed DOM element
> Prevent unmounted EuiGlobalToastList from causing errors

- src/components/bottom_bar/bottom_bar.js
Fixed spelling in JSDoc comment.
I'm an editor rather than a developer, so I hope that this is the right place to make this change. If I understand correctly after some cursory Googling on /**, the JSDoc comments help to generate the HTML, in this case the table of properties shown in the Bottom Bar doc?
> Edit to JSDoc comment in bottom_bar.js

- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Component `propTypes` were not generated for `FunctionComponent`s. This fixes that.
> Process typedefs for FunctionComponent into propTypes

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/_combo_box.scss
- src/components/combo_box/combo_box.js
- src/components/combo_box/combo_box_input/_combo_box_pill.scss
- src/components/combo_box/combo_box_input/combo_box_input.js
Fixes #1615. Moves the highlighting-of-active-single-selection logic to the list open action instead of on any prop/state change. This allows controlling the active item via keyboard arrows.
`EuiComboBox` should get another pass in the future to get a better way of tracking & managing the current active item, there's a lot of interwoven logic in here.
> Allow keyboard navigation of single select combobox

- CHANGELOG.md
- src/components/flyout/flyout_body.tsx
- src/components/flyout/flyout_footer.tsx
- src/components/flyout/flyout_header.tsx
- src/components/flyout/index.d.ts
- src/components/modal/index.d.ts
- src/components/modal/modal_body.tsx
- src/components/modal/modal_footer.tsx
- src/components/modal/modal_header.tsx
- src/components/modal/modal_header_title.tsx
- src/components/portal/index.js
- src/components/portal/index.ts
Export type definitions in mixed js/ts component directories.
> [Typescript]: Fix 9.x exported members

- src-docs/src/views/icon/icon_example.js
Couple of spelling/wording changes & one formatting change with an `<EuiCode>` tag.
> Edits to text in icon/icon_example.js

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
Fixes #1693 (`activeOptionIndex` error with empty search results). See error reproduction steps in the issue.
* Change `activeOptionIndex` to always be a number (`-1` instead of `null` or `undefined`). This is just for logic simplification.
* Guard against attempting to match against `activeOptionIndex` of `-1`
> Fix EuiComboBox `activeOptionIndex` error

- src/components/title/title.js
Fixes #1692 - a component has props docs generated only if it returns JSX _or_ an explicit `React.*` function call.
> Make EuiTitle's docs list the components' props

- CHANGELOG.md
- src-docs/src/routes.js
- src-docs/src/views/app_view.js
- src-docs/src/views/guidelines/colors.js
- src-docs/src/views/guidelines/sass.js
- src/components/form/_mixins.scss
- src/components/form/_variables.scss
- src/global_styling/variables/_colors.scss
- src/themes/eui/eui_colors_dark.scss
Fixes https://github.com/elastic/eui/issues/605
Figured this was one of the few things we could try and get in before RC1.
Updates the dark mode color scheme to get blue hues. I brightened up the colors but have yet to do a full contrast audit other than to see that things generally work. I've tried to steal colors from the upcoming marketing designs as much as I could here so that we match against some of the things they are planning.
I also went ahead and fixed the docs pages to better account for the dark mode palettes. Because of the way they were imported, this required me to duplicate some vars in the `eui_theme_dark.scss` file (like the viz colors or ghost) that were unchanged between themes. I think it's ok to have them there, but would be nice to have a better solution.
@cchaos …
> Dark mode redux, fix dark mode docs

- CHANGELOG.md
- src/components/badge/_badge.scss
- src/components/badge/notification_badge/_notification_badge.scss
- src/components/bottom_bar/_bottom_bar.scss
- src/components/call_out/_mixins.scss
- src/components/loading/_loading_chart.scss
- src/components/side_nav/_side_nav_item.scss
- src/components/tool_tip/_mixins.scss
- src/components/tool_tip/_tool_tip.scss
- src/components/tool_tip/_variables.scss
- src/themes/eui/eui_colors_dark.scss
A follow-up to @snide's dark colors update.
The lightest three colors euiColorDarkShade, euiColorDarkestShade, euiColorFullShade were way too similar that they were indistinguishable from each other (especially on the dark background). I altered the dark and darkest shades to be a tad darker (still using the same hex values from the light theme).
I noticed the difference when looking at subdued text, which didn't look subdued at all. So now it does.
@snide Can you handle the update of these? You can push directly to this branch.
But I did fix the notification badge:
----
**Tooltips**
_before_
_after_
**Callout titles**
They were just a tad on the saturated side, so I tinted them ever so slightly.
_before_
_after_
**Bottom bar**
Added a shadow to try to distinguish it from the background …
> A few more dark mode fixes

- CHANGELOG.md
- src/components/popover/index.d.ts
Make EuiPopover's repositionOnScroll prop optional in TS
> Make EuiPopover's repositionOnScroll prop optional in TS

- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Fixes #1698 - defs->proptypes resolver didn't know how to look further into the TS defs for `SFC` or `FunctionComponent` on a variable declaration.
```
const Foo: FunctionComponent<FooType> = () => {}
```
vs
```
type FooType = FunctionComponent<{}>;
const Foo: FooType = () => {}
```
> Allow SFC and FunctionComponent definitions to be indirected

- CHANGELOG.md
- src/services/objects.ts
- src/services/predicate/lodash_predicates.ts
- src/services/utils.ts
Required for https://github.com/elastic/kibana/pull/32746
If `eui.d.ts` imports anything from lodash, TS opens lodash's `index.d.ts` and loads its declarations into the lodash namespace. These conflict with the lodash 3 definitions used by Kibana.
Tested this by building `eui.d.ts` and copying it into the Kibana above branch, then running `node scripts/type_check.js`
> Wrap lodash functions to avoid exporting lodash type defs

- CHANGELOG.md
- src/components/list_group/__snapshots__/list_group_item.test.js.snap
- src/components/list_group/_list_group_item.scss
- src/components/list_group/list_group_item.js
- src/components/list_group/list_group_item.test.js
This is required for the nav in Kibana where plugins can provide their own (non-EuiIcon icon type) icon/image.
Example using an avatar:
Also beefed up the test cases.
- ~[ ] Documentation examples were added~ I specifically didn't add an example as it's a very low use case
> Allow EuiListGroupItem to pass a custom element as the icon

- CHANGELOG.md
- src-docs/src/views/nav_drawer/nav_drawer.js
- src/components/avatar/avatar.tsx
- src/components/image/_image.scss
- src/components/list_group/_list_group_item.scss
- src/components/nav_drawer/_nav_drawer.scss
- src/components/nav_drawer/_nav_drawer_group.scss
- src/components/nav_drawer/nav_drawer_group.js
- src/services/index.ts
- src/services/string/index.ts
- src/services/string/to_initials.test.ts
- src/services/string/to_initials.ts
Instead of forcing a consumer to pass an icon, if they don't provide one, one will be created a la Avatar style and use the name to provide initials to display in collapsed view.
In order to do so, I also pulled the initials calculation out from EuiAvatar to a string service. This could probably be generalized further ( still kind of Avatar specific ) but in the interest of time, it all still works.
> EuiNavDrawerGroup default icon

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #1721 . Doesn't add a custom option if the user is clicking on an option.
> Don't create a custom combobox option if user clicked on an option

- CHANGELOG.md
- src/components/date_picker/index.d.ts
- src/components/date_picker/super_date_picker/super_date_picker.js
The SuperDatePicker was missing the `onRefresh` callback prop in the types file. I added it so that it can be used in a TS file without complaints.
Once I did that, I was able to test out the new `onRefresh` prop and it didn't _quite_ work. If you started refreshing and then changed the start/end values, each refresh would _reset_ them back where they were because of the closure where the refresh handler was created. 
This PR makes the handler grab start and end from props on each refresh so that the refresh callback is given the most up to date start and end values.
- ~[ ] This was checked for …
> Fix onRefresh for SuperDatePicker

- CHANGELOG.md
- src-docs/src/i18ntokens.json
- src/components/bottom_bar/__snapshots__/bottom_bar.test.js.snap
- src/components/bottom_bar/bottom_bar.js
FIxes https://github.com/elastic/eui/issues/1696. EuiBottomBar uses non-visual language.
> [Accessibility] EuiBottomBar refers to the end of document.

- package.json
Supports the effort to break apart `EuiIcon` by allowing webpack to tree shake unused EUI components from the build.
Stats from the building with a `sideEffects: false` EUI -
```
Empty React "Hello World" - 117Kb
Include anything in EUI with no tree shaking - 3.6Mb
Including only EuiPanel with tree shaking - 767Kb
Including only EuiCodeEditor with tree shaking - 545Kb
```
To ensure all JS/TS/TSX files in EUI src are compatible with this change, looking for any usage of outside variables in the module's initiation. There are two cases:
* A few components have `PropTypes.instanceOf(HTMLElement)`, a passive reliance on a browser-like environment
* `EuiCodeEditor` imports `brace`, which requires the `window` object be present. This is fine for tree shaking as `brace` isn't needed unless …
> Mark EUI package as sideEffect free to enable webpack treeshaking

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #1736. Makes `EuiComboBox`'s call its `onBlur` prop only when the entire combo box element loses focus i.e. text input, pills, dropdown, clear button no longer trigger it.
> Fix EuiComboBox's call to onBlur prop

- CHANGELOG.md
- src/components/badge/badge.js
- src/services/color/hex_to_rgb.ts
Makes `EuiBadge` resilient to an empty string passed into `color`
* adds a check in `hexToRgb` to prevent destructuring a `null`
* corrects the custom prop type in `EuiBadge` to properly warn when `color` is empty
> Prevent an empty badge color from blowing things up

- CHANGELOG.md
- src/components/date_picker/index.d.ts
The `EuiSuperDatePicker` component had an `onRefresh` prop added to its type files in 9.4.1, but it was accidentally made required. This makes it correctly optional.
> Makes SuperDatePicker onRefresh prop optional, as it should be

- CHANGELOG.md
- src/components/button/__snapshots__/button.test.js.snap
- src/components/button/button.js
- src/components/button/button_group/button_group.js
- src/components/button/index.d.ts
- src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.js.snap
This updates the prop type comment for `EuiButtonGroup` and the TypeScript definition for `EuiButtonGroup`, this is to normalise a bit of drift between what `EuiButtonGroup` and `EuiButton` were declaring as valid button sizes, beforehand:
- `EuiButtonGroup` used "s" and mentioned "m" in the docs
- `EuiButtonGroup` TypeScript definitions defined size as "s" | "m"
However, once these props were passed down to `EuiButton` this would cause a console warning using "m" due to `EuiButton` [supporting "s" and "l" only](https://github.com/elastic/eui/blob/master/src/components/button/button.js#L27).
Given "m" and "l" both produce buttons of the same size, I've just removed the notion of "m" from `EuiButtonGroup` (hopefully this is okay - I've checked it against the docs site and Kibana).
> Make "m" the default size of EuiButton

- CHANGELOG.md
- src/components/pagination/pagination.js
Included  documentation entry for activePage prop mentioning that the `activePage` is zero based. 
Ref: https://github.com/elastic/eui/issues/1667
> [Pagination] - Added props doc mentioning the activePage is zero based

- CHANGELOG.md
- src/components/tool_tip/tool_tip.js
Fixes #1734, in which content changes near the right edge of the window caused longer text to wrap lines and result in incorrect, uncorrected positioning calculations.
* Uses `EuiResizeObserver` instead of `EuiMutationObserver`. The latter did not account for side effect updates and missed possible resize changes. (This is a more forward-looking change, getting at what I think we _actually_ want to observe).
* Calculates `EuiToolTip` x-axis position from the right if nearing the right edge of the window. This prevents text wrap/reflow, negating positioning correction.
~~- [ ] Jest tests were updated or added to match the …
> Fix EuiToolTip text reflow on content changes

- CHANGELOG.md
- src/components/date_picker/super_date_picker/super_date_picker.js
Follow-up to https://github.com/elastic/eui/pull/1577
Since there is now an `onRefresh` callback, the update button should no longer call `onTimeChanged` when an actual refresh was performed (which doesn't change the time).
The ui of the button already distinguishes between the two states (update time range vs. manual refresh).
This is also the same callback that will be called, when the automatic refresh interval is fired.
This is important because the consumer might want to have separate logic for when the time range was changed vs. when a refresh was invoked. 
To make this backwards compatible this change only take effect for consumers who have implemented the `onRefresh` callback (searching through Kibana this will only affect APM)
> [EuiSuperDatePicker] Invoke `onRefresh` instead of `onTimeChanged` when clicking “Refresh” 

- CHANGELOG.md
- src/components/list_group/index.d.ts
- src/components/list_group/list_group.js
- Adds type definitions for `EuiListGroup` and `EuiListGroupItem`
- Changes the `propTypes` of `EuiListGroup` to reuse `EuiListGroupItem.propTypes` instead of redefining the shape.
~~- [] Jest tests were updated or added to match the most common scenarios~~
> add EuiListGroup and EuiListGroupItem type definitions.

- CHANGELOG.md
- package.json
- scripts/compile-scss.js
- scripts/derive-sass-variable-types.js
This enhances the `compile-scss.js` build script to also emit TypeScript type definitions for the JSON files generated from the theme variables. These type definitions are stored as `.json.d.ts` files in `dist/` alongside the JSON files so the imports are typed correctly.
When imported in downstream projects like Kibana, the imported symbols will be typed appropriately, which would reduce the risk involved in making breaking changes to these variables like #1590 did.
Letting the TypeScript compiler derive the types automatically was attempted twice in Kibana (elastic/kibana#24425 and elastic/kibana#25516). Both attempts failed due to limitations Kibana's build process and the TypeScript compiler.
- ~~This was checked in mobile~~
- ~~This was checked in IE11~~
- ~~This was checked in dark …
> Emit TypeScript type definitions for variables extracted from themes

- CHANGELOG.md
This fixes an incorrect merge conflict resolution in the changelog of #1750.
- ~~This was checked in mobile~~
- ~~This was checked in IE11~~
- ~~This was checked in dark mode~~
- ~~Any props added have proper autodocs~~
- ~~Documentation examples were added~~
- ~~This was checked for breaking changes and labeled appropriately~~
- ~~Jest tests were updated or added to match the most common scenarios~~
- ~~This was checked against keyboard-only and screenreader scenarios~~
- ~~This required updates to Framer X components~~
> Fix changelog mistake made in #1750

- CHANGELOG.md
- src/components/button/_mixins.scss
- src/global_styling/reset/_reset.scss
This now targets h1-h6 and p tags to reset the family, weight and size to be similar to the base. This fixes #1714 where plain headings outside of EuiText were getting the browser's default applied which doesn't match our EuiText or EuiTitle styles.
---
I also added a font-size declaration for EuiButton's since they were getting inherited from their container, even though the overall size of the button was staying the same.
For example in tables:
- ~[ ] This was checked against …
> Fix font reset for headings

- CHANGELOG.md
- src-docs/src/views/loading/loading_content.tsx
- src-docs/src/views/loading/loading_example.js
- src/components/index.js
- src/components/loading/__snapshots__/loading_content.test.tsx.snap
- src/components/loading/_index.scss
- src/components/loading/_loading_content.scss
- src/components/loading/_variables.scss
- src/components/loading/index.ts
- src/components/loading/loading_content.test.tsx
- src/components/loading/loading_content.tsx
Creating a simple loading animation for content blocks. I'm open to ideas on this. I wanted to start with something dead simple and get some eyes on it.
> Adding a content block loading animation.

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/form/file_picker/file_picker.js
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/form_control_layout_clear_button.js
- src/components/form/form_control_layout/form_control_layout_custom_icon.js
- src/components/list_group/__snapshots__/list_group_item.test.js.snap
- src/components/list_group/list_group_item.js
- src/components/side_nav/side_nav_item.js
Fixes #1763 
These `button`s have been updated to type of _button_ instead of their default _submit_:
* [file_picker.js](https://github.com/elastic/eui/pull/1764/files#diff-295d2dd996a5ad6de97e0140a8968742R109)
* [form_control_layout_clear_button.js](https://github.com/elastic/eui/pull/1764/files#diff-a4e30e244a6ffafdf3f7f7e095add8fdR19)
* [form_control_layout_custom_icon.js](https://github.com/elastic/eui/pull/1764/files#diff-8066e73816f64cd183d72d5ba360b0adR25)
* [list_group_item.js](https://github.com/elastic/eui/pull/1764/files#diff-ae7a27bc6cec53a4dc2132b43eb4d135R107)
* [side_nav_item.js](https://github.com/elastic/eui/pull/1764/files#diff-2d3833502cf827812482433b557676ebR29)
~- …
> Set some <button> elements to type="button"

- CHANGELOG.md
- src/components/nav_drawer/nav_drawer.js
This change will fix a Kibana issue https://github.com/elastic/kibana/issues/30331 where the expanded nav drawer will remain open if you navigate to the app that you are already viewing. In other words, there is no refresh so the menu doesn't get reloaded to the collapsed state. I noticed this can also happen with the flyout - if it's open and you click on an app icon in the main menu, the flyout stays open. This PR addresses both cases.
This solution was the outcome of some discussion an initial PR - https://github.com/elastic/eui/pull/1770
> Close nav drawer when a link is clicked

- wiki/react-router.md
`react-router` 5.0 came out recently and it's completely BWC version with `react-router` 4.x.
> [Wiki] react-router 4.x changes also apply to 5.x

- CHANGELOG.md
- src/global_styling/reset/_reset.scss
Fixing the previous fix of #1760 where setting the font size at the reset level was causing these tags not to inherit from their container. Even the text scales weren't working:
So now, all 3 properties are just set to inherit (which should be from the `html` tag which does set the size, family and weight.
**Now:**
_back to normal_
> Headings, and <p>, need to inherit

- wiki/react-router.md
This corrects the previous edit suggesting that `react-router` 5.0
was completely backward compatible with 4.x.
It turns out, while trying to use this trick to extract the `context`
within the constructor that `this.context.router` is `undefined`.
I _assume_ that we just need to use a context consumer, but I
do not see its name or type documented anywhere.
I also shortened the code examples a tiny bit.
> [Wiki] React Router 5.x does not provide React Context

- CHANGELOG.md
- src/components/button/index.d.ts
Fixes #1780 by updating `ButtonIconColor` type to match available options.
> Update ButtonIconColor type to match all available options

- CHANGELOG.md
- src/components/observer/observer.js
- src/components/observer/resize_observer/resize_observer.js
elastic/kibana#34271 raises the case where `EuiResizeObserver` using the fallback `MutationObserver` API results in errors when the observed element is removed.
Two possible scenarios where `this.childNode` ref becomes `null` but `onResize` can still occur:
1)  prior to the initialization `requestAnimationFrame`
2) prior to `observer.disconnect()` but `onResize` is already queued
Changes address the two above by calling `disconnect` before changing the `childNode` ref, and preventing calculations when `childNode` is `null`
~~- [ ] This was checked for breaking changes and labeled …
> Prevent calculation on null childNode during resize observation

- src/components/side_nav/side_nav.js
Resolves #1781 - added react-docgen documentation and a required PropType around an `item`'s _id_ value.
- [ x Documentation examples were added
> Added documentation for EuiSideNavItem's use of id prop as a key

- CHANGELOG.md
- src/components/combo_box/combo_box_input/combo_box_input.js
- src/components/toast/_toast.scss
- src/components/toast/global_toast_list.js
Easy one while I was cleaning out the backlog. As long as an item within a toast has focus, it will stick around. When you tab out, it will resume the countdown, similar to mouse actions.
Fixes https://github.com/elastic/eui/issues/717
Also added a fixes https://github.com/elastic/eui/issues/1343. Given how direct the combo box is with instruction it seemed like the best thing to do was announce the placeholder in the same way.
> Small accessibility fixes to toasts and combo box

- CHANGELOG.md
- src/components/search_bar/search_box.js
This one has been grinding our gears for as long as I can remember
Fixes https://github.com/elastic/cloud/issues/22906
> Fix search box query resetting on prop updates

- CHANGELOG.md
- src/components/search_bar/filters/__snapshots__/field_value_selection_filter.test.js.snap
- src/components/search_bar/filters/field_value_selection_filter.js
Fixes https://github.com/elastic/eui/issues/1815
> Fix EuiSearchBar filter highlighting

- src-docs/src/views/accordion/accordion.js
- src-docs/src/views/accordion/accordion_example.js
- src-docs/src/views/accordion/accordion_multiple.js
Tending garden 🥕, just adding some snippets to the `EuiAccordion` docs.
> Add snippets to accordion docs

- CHANGELOG.md
- src-docs/src/views/guidelines/index.scss
- src-docs/src/views/guidelines/sass.js
- src-docs/src/views/modal/overflow_test.js
- src/components/flyout/__snapshots__/flyout_body.test.tsx.snap
- src/components/flyout/_flyout_body.scss
- src/components/flyout/_flyout_footer.scss
- src/components/flyout/_flyout_header.scss
- src/components/flyout/flyout_body.tsx
- src/components/modal/__snapshots__/confirm_modal.test.js.snap
- src/components/modal/__snapshots__/modal_body.test.tsx.snap
- src/components/modal/_modal.scss
- src/components/modal/confirm_modal.js
- src/components/modal/confirm_modal.test.js
- src/components/modal/index.d.ts
- src/components/modal/modal_body.tsx
- src/global_styling/mixins/_shadow.scss
1. **Fixed `EuiConfirmationModal` responsive sizing** 
Since most confirmation modals are a simple title, short description and then the buttons, it meant that the buttons (footer) was very far from the intro. I made is so the confirmation style modal is just at the bottom of the screen but that it will still max out at 100vh.
This also fixes a layout issue for title-only confirmation modals:
Normal modals still display in full height:
2. **Using the new `euiOverflowShadow` mixin instead of separate shadows on header and footer**
This is a much simpler and more configurable way to add the overflow shadows, though it does require one extra wrapping div. However, it doesn't require a before element and after element. 
The new mixin is also more subtle (most noticeable in the flyout example …
> Better overflow shadows and some mobile modal fixes 

- CHANGELOG.md
- src/components/nav_drawer/_nav_drawer.scss
Fixes an issue that was opened in the Kibana repo: https://github.com/elastic/kibana/issues/35083
It seems this comes down to difference of interpretation for the overflow spec. The Mozilla team seems to have taken a slightly different approach (than other browsers) with regards to where they apply bottom padding when there is overflow: https://bugzilla.mozilla.org/show_bug.cgi?id=748518
There were several kludge solution, but simply changing this from `padding-bottom` to `margin-bottom` did the trick.
Tested EUI docs and Kibana on FF, Chrome, and IE.
> Fix EuiNavDrawer scroll overflow issue on Firefrox

- CHANGELOG.md
- src/components/button/__snapshots__/button.test.js.snap
- src/components/facet/__snapshots__/facet_button.test.js.snap
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/super_select/__snapshots__/super_select_control.test.js.snap
- src/components/loading/__snapshots__/loading_chart.test.tsx.snap
- src/components/loading/__snapshots__/loading_content.test.tsx.snap
- src/components/loading/__snapshots__/loading_kibana.test.tsx.snap
- src/components/loading/__snapshots__/loading_spinner.test.tsx.snap
- src/components/loading/_loading_chart.scss
- src/components/loading/_loading_content.scss
- src/components/loading/_loading_kibana.scss
- src/components/loading/loading_chart.tsx
- src/components/loading/loading_content.tsx
- src/components/loading/loading_kibana.tsx
- src/components/loading/loading_spinner.tsx
Replaces https://github.com/elastic/eui/pull/1840, fixes https://github.com/elastic/eui/issues/1834
Applies a width to the wrapping element for the Kibana loader. This also makes all of our loaders use spans instead of divs. I don't see any reason to also support divs, so this closes the PR mentioned above and removes the need for an extra prop.
> Use span for loaders and set width to kibana loader

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #1857, in which `focus()` was sometimes being called after an `EuiComboBox` `blur` event, causing the element's `input` to regain focus.
> Prevent refocusing EuiComboBox input after container blur event

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #1853  - bug in `EuiComboBox` which passed its `inputRef` prop to a DOM node
> Fix EuiComboBox's handling of inputRef

- CHANGELOG.md
- src/global_styling/mixins/_responsive.scss
Fixes https://github.com/elastic/eui/issues/1825. There was a feedback error with certain sass compilers.
> Bug/1825 Fix sass warn feedback on breakpoints

- scripts/update-token-changelog.js
The current setup for detecting changes to i18n tokens relies on changes to *i18n_tokens.json* not be manually committed, instead allowing the release script to generate & commit the new file. This process breaks if someone does a build, notices *i18n_tokens.json* was updated, and commits those changes.
This PR modifies the release process to check if the tokens have changed _since the last release_ instead of if there are unstaged changes.
~- [ ] This was checked for breaking …
> Improved logic for generating i18n changelog entries

- CHANGELOG.md
- src/components/table/table_pagination/table_pagination.js
Brought up in #1869 , `EuiTablePagination` was missing localization when selecting how many rows to display.
> Add localization to EuiTablePagination's options

- CHANGELOG.md
- src/components/date_picker/super_date_picker/date_popover/date_popover_button.js
- src/components/date_picker/super_date_picker/date_popover/date_popover_content.js
- src/components/date_picker/super_date_picker/date_popover/relative_tab.js
So when you set e.g. 70 years ago in the To field of the date
range with "Round to the year" active, the To field's value is rounded
up. So instead of:
Jan 1, 1949 @ 00:00:00.000
It's
Jan 1, 1949 @ 23:59:59.999
Since now this date is less then 70 years in the past, moment.js fromNow
displays 69 years
> [EuiSuperDatePicker] relative tab, timestamp: Use roundUp, switch pos with "Round To"  btn

- CHANGELOG.md
- src/components/modal/_modal.scss
Chrome 74 broke our implementation of overflow scrolling in modals. This adds an extra flex layer to ensure that scrolling works.
**Before**
**After**
---
I have checked in:
**Mac 10.14**
**Windows 7**
> Fix overflow of EuiModals in Chrome and Safari

- CHANGELOG.md
- src/components/overlay_mask/overlay_mask.tsx
Fixes `children` interface mismatches (below), which relates to the now-known #1890 about `children` element type restrictions/modifications. The type changes are not as well-defined as we'd like, but there is not good workaround yet.
```ts
Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string) | undefined'.
Type 'Element' is not assignable to type 'ReactPortal & string'.
Type 'Element' is not assignable to type 'ReactPortal'.
```
~~- [ ] This was checked in dark …
> EuiOverlayMask TS fix

- CHANGELOG.md
- src/components/form/file_picker/_file_picker.scss
- src/components/form/file_picker/file_picker.js
Fixes #1897 
`EuiFilePicker` would store `initialPromptText` in state, updating the value when the file selection changed. This introduced two bugs:
* If `initialPromptText` prop changed, the rendered text wouldn't update
* The component considered a selection to exist if the its prompt state did not match the initial prompt. This works when comparing primitive values like strings, but when provided a React element it would get confused on the next render as the element representation is an object resulting from `React.createElement`. This is reproducible by passing `initialPromptText={<span>Select or drag and drop multiple files</span>}`.
The fix is to avoid storing the initial prompt in state. Always pulling it from props keeps the rendered text up to date and allows it to know when the …
> Fix EuiFilePicker's prompt to properly reset

- src-docs/src/components/guide_components.scss
- src-docs/src/images/custom.svg
- src-docs/src/views/icon/apps.js
- src-docs/src/views/icon/icon_colors.js
- src-docs/src/views/icon/icon_example.js
- src-docs/src/views/icon/icon_sizes.js
- src-docs/src/views/icon/icon_types.js
- src-docs/src/views/icon/icons.js
- src-docs/src/views/icon/logos.js
- src-docs/src/views/icon/logos_third.js
- src-docs/src/views/icon/ml.js
- src-docs/src/views/icon/tokens.js
- src/components/icon/icon.tsx
WIP. Still needs:
* Make a guideline that describes good usage and authoring patterns
* Possibly break out `EuiToken` into its own page
@cchaos / @chandlerprall might want to check if we're ok with the lack of animation with non EUI icons. It's prolly OK? Also, @cchaos / @ryankeairns do you think we should copy the component or string for each icon? I couldn't decide which was more useful, which is why I've only applied it to one example in here.
> Docs for EuiIcon new abilities

- src-docs/src/components/guide_section/guide_section.js
- src-docs/src/views/icon/icon_example.js
You can now also pass an array of strings to break the snippets into multiples. This is helpful for copy and pasting single snippets. It renders like so:
> [Docs]: Allow multiple snippets

- src-docs/src/views/date_picker/date_picker_example.js
There has been several questions about how to parse the start/end strings returned from super date picker. This PR adds a section to the documentation about parsing the values
cc @justinkambic
> add section about parsing with datemath to SuperDatePicker docs

- src-docs/src/views/icon/icon_example.js
- src-docs/src/views/icon/icon_types.js
- src/components/badge/badge.js
- src/components/badge/beta_badge/beta_badge.js
- src/components/button/button.js
- src/components/button/button_empty/button_empty.js
- src/components/button/button_icon/button_icon.js
- src/components/call_out/call_out.js
- src/components/date_picker/date_picker_range.js
- src/components/empty_prompt/empty_prompt.js
- src/components/filter_group/filter_button.js
- src/components/header/header_logo.js
- src/components/icon/icon.tsx
- src/components/icon/index.ts
- src/components/key_pad_menu/key_pad_menu_item.js
- src/components/list_group/list_group_item.js
- src/components/table/table_header_button.js
- src/components/toast/global_toast_list.js
- src/components/toast/toast.js
- src/components/token/token.js
Fixes `IconType` to accept `ReactElement`s, `EuiIcon` provides a proptype for `IconType` for usage by other components.
> Update IconType and its proptype usage

- CHANGELOG.md
- src/components/form/_mixins.scss
For firefox only to fix the flash of unstyled dropdown.
> [Firefox] Remove `background-color` from transition property list of form control mixin

- CHANGELOG.md
- src/components/tool_tip/index.d.ts
The expansion of EuiIcon's _IconType_ made the EuiIconTip definition unhappy. I've tested this change in Kibana locally and verified that its type_check script completes successfully.
> Fix EuiIconTip TS types

- CHANGELOG.md
- src/components/icon/icon.tsx
`EuiIcon` currently only dynamically imports the icon file once during the `constructor` phase, even if the `type` prop changes at a later time. This PR adds the ability to dynamically import new icon files as the `type` prop changes over the component lifecycle.
> Handle EuiIcon `type` prop updates

- CHANGELOG.md
- src/components/button/__snapshots__/button.test.js.snap
- src/components/button/button.js
Summarize your PR. If it includes design elements include a screenshot or gif.
- ~[ ] This was checked in ### mobile~
> Remove unused prop enum of `l` in `EuiButton`

- CHANGELOG.md
- src/components/overlay_mask/overlay_mask.tsx
React portals require `ReactNode`, which accepts `null` and `undefined`. `children` can be optional in `EuiOverlayMask` for this reason as it does nothing except pass to a portal.
> Make EuiOverlayMask children optional

- CHANGELOG.md
- src/components/flex/__snapshots__/flex_grid.test.tsx.snap
- src/components/flex/_flex_grid.scss
- src/components/flex/flex_grid.tsx
Added width to `EUIFlexItem` when gutter in `EUIFlexGrid` is set to none. To fix #1493 
Before (2 columns)
After (2 columns)
> Added width to FlexItem when gutter in FlexGrid is set to none

- CHANGELOG.md
- src/components/drag_and_drop/draggable.tsx
- src/components/drag_and_drop/droppable.tsx
Fix: #1898
EuiDraggable, EuiDroppable should support the 'data-test-subj' property
> EuiDraggable, EuiDroppable should support the 'data-test-subj' property

- CHANGELOG.md
- src/components/form/form_control_layout/__snapshots__/form_control_layout_custom_icon.test.tsx.snap
- src/components/form/form_control_layout/form_control_layout_custom_icon.test.tsx
- src/components/form/form_control_layout/form_control_layout_custom_icon.tsx
- src/components/form/form_control_layout/index.d.ts
Converted EuiFormControlLayoutCustomIcon to TS
> `EuiFormControlLayoutCustomIcon` to TS

- CHANGELOG.md
- src/components/toast/index.d.ts
Fixes #1957, which points out that we had a type mismatch for the `title` prop in EuiToast (PropType: `node`; d.ts: `string`). We've generally allowed for more flexibility, so TypeScript will now accept `ReactNode` instead of `string`.
> EuiToast title prop should accept a node

- .babelrc.js
- CHANGELOG.md
- src/components/icon/icon.tsx
This PR adds a webpack directive (i.e. a comment) for naming icon chunks. The effect of this is obesrved in applications that use EUI and bundle through Webpack - instead of icon chunks such as e.g.
233.longhashgoeshereomgitssolong.js
you get:
icon.app-kibana-js.longhashgoeshereomgitssolong.js
It's a small thing, but if a dynamic download were to fail then it might make tracking down the problem fractionally easier.
I think it still works if you drop the file extension from the `import()`, which means you get a cleaner `[request]` value, but I thought I'd ask about that rather than just doing, since the `.js` assets live alongside the `.svg` assets.
> Add a webpack directive for naming icon chunks

- CHANGELOG.md
- src/components/form/field_text/index.d.ts
Add missing TypeScript definition for `EuiFieldText`'s `compressed` prop.
This changes are needed for the PR https://github.com/elastic/kibana/pull/37476
> Add missing TS definition for EuiFieldText

- CHANGELOG.md
- src/components/toast/global_toast_list.js
Summary
Updates fix for #1957 to fix mismatch with defined toast prop type in EuiGlobalToastList.
> EuiGlobalToastList toasts title prop should accept a node

- CHANGELOG.md
- src/components/button/index.d.ts
I found that this type definition was missing when trying to use `<EuiButton color="text">` in a typescript file.
> Fix missing typescript for EuiButton color="text"

- CHANGELOG.md
- src/components/toggle/_toggle.scss
Setting the z-index to 1 ensures the hidden input for the toggle is the top most element and is the one to receive the pointer events.
> Fix toggle pointer events

- CHANGELOG.md
- src/components/color_picker/index.d.ts
Fixes incorrect type definitions. Optional `onBlur` and `onFocus`
> EuiColorPicker `onBlur` & `onFocus` fns are optional

- CHANGELOG.md
- src/components/icon/icon.tsx
The work to remove TSLint in favour of ESLint has the side effect of "fixing" a lint failure in `EuiIcon`. It changed a plain string concatenation into a string template. Normally this would be fine, but this particular string concatenation is used to load icons dynamically, and Webpack can't build a dynamic require context from the compiled version of the template string.
Revert the change and add a lint directive to stop it recurring.
I built and linked the package, and tried it out in Cloud UI to ensure it was working as expected.
> Fix EuiIcon so webpack can build dynamic require contexts

- CHANGELOG.md
- src/components/form/form_control_layout/_form_control_layout.scss
#1849 Caused a regression with prepend/append items in EuiFormControlLayout when using a EuiFilterButton in either position because the PR added borders to the individual buttons that did not previously exist.
`EuiFormControlLayout` made the assumption that anything being put into prepend/append was not coming with borders and so it only added a dividing border but left any surrounding borders.
**Before**
This PR just resets/clears any borders for any prepend/append items that may be passed.
**After**
- ~[ ] Jest tests were …
> Reset borders of append/prepend items in EuiFormControlLayout

- src-docs/src/views/tables/sorting/sorting.js
Fixes #2003
*Docs-only fix so no CHANGELOG entry*
Remove duplicate `sortable: true` from sorting example in the tables docs.
> [Docs] Remove duplicate sortable prop

- CHANGELOG.md
- src/components/call_out/_call_out.scss
`.euiIcon` has a transform applied to it that is overriding  the transform placed on the `.euiCallOutHeader__icon` because the icon file is loaded after the callout file.
Causing:
This PR moves the `.euiCallOutHeader__icon` declaration inside of `.euiCallOutHeader` to increase specificity to override the `.euiIcon` property.
So now:
- ~[ ] This required updates to Framer X …
> Fix EuiCallOut icon alignment in header

- src-docs/src/views/guidelines/colors.js
We had a regression on the docs in https://github.com/elastic/eui/pull/1952 that made the color buttons not full width.
> [Docs] Fix buttons on colors guideline page

- src-docs/src/views/date_picker/date_picker_example.js
- src/components/date_picker/super_date_picker/super_date_picker.js
Fixes #2014, corrects docs typo in recommended moment/date formatting. No changelog as this is a docs-only change.
> Change date formatting docs from .sssZ to .SSSZ

- CHANGELOG.md
- src/components/basic_table/in_memory_table.js
Fixes a bug where `sorting` updates stop after `items` data is changed externally. This change persists the local values of sort properties through lifecycle changes.
> EuiInMemoryTable: maintain sort values through external item updates

- CHANGELOG.md
- src/components/flyout/_flyout.scss
- src/components/flyout/_flyout_body.scss
This issue was [originally picked up in the Logs UI](https://github.com/elastic/kibana/issues/37699). The changes here allow the body of the Flyout component to scroll in Safari, currently in `master` it won't scroll at all. My understanding is that, according to the Flebox spec, for `height` to take effect it needs to be present throughout the whole Flex hierarchy (so Safari was doing the right thing 😭).
However, these changes do seem to introduce the classic body scrolling issue, which on `master` currently only exists in IE11. By body scrolling issue I mean that when the scrollable area of the flyout is exhausted the body will start to scroll. In the past I've generally solved this with a `noscroll` class on the `body` when the component is open, or hovered (depending on the scenario). …
> Fix Flyout scrolling in Safari

- CHANGELOG.md
- src-docs/src/views/tables/basic/props_info.js
Found a small typo in the `props` documentation for `EuiBasicTable`. This patch is intended to fix it.
> Fix typo in EuiBasicTable documentation

- package.json
- src-docs/src/views/horizontal_rule/horizontal_rule_example.js
- src-docs/src/views/spacer/spacer_example.js
It's useful to allow warnings in dev environments, but they're enabled for a reason and should break builds (& commits). We had a few warnings committed in master, this resolves them and prevents future warnings from being committed.
~- [ ] This required updates …
> Make the commit hook (via yarn lint-es) fail on lint warnings

- CHANGELOG.md
- src/components/nav_drawer/nav_drawer_flyout.js
Fixes #2039 
Associated issue: elastic/kibana#34995
This PR replaces `<h5>` with `<div>` and that's it.
- ~~This was checked in mobile~~
- ~~This was checked in IE11~~
- ~~This was checked in dark mode~~
- ~~Any props added have proper autodocs~~
- ~~Documentation examples were added~~
- ~~This was checked for breaking changes and labeled appropriately~~
- ~~Jest tests were updated or added to match the most common scenarios~~
- ~~This required updates to Framer X components~~
> (Accessibility) Fix EuiNavDrawerFlyout using `<h5>` by replacing with `<div>`

- CHANGELOG.md
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Noticed that the docs showed proptype warnings for EuiCopy's `children`, even though everything was typed & passed correctly. Discovered that the `Function` identifier and method signatures were not being detected by the TS->proptype script. Added a test case to cover
```
{
foo(): ReactElement;
bar?(arg: number): string;
fizz: Function;
buzz?: (arg: boolean) => string;
}
```
(which should all result in either `PropTypes.func` or `PropTypes.func.isRequired`)
in both `interface` and `type` definitions, and confirmed EuiCopy's proptype is now correct.
~- [ ] This required …
> Properly handle Function and TSMethodSignature TS interfaces and type literals

- src-docs/src/views/guidelines/writing.js
Addendum to https://github.com/elastic/kibana/issues/38734
Updates the section on "Sentence case for all text" to say this:
> [DOCS] Update EUI writing guidelines to include title casing feature names

- CHANGELOG.md
- src/components/toast/index.ts
`Toast` interface from `EuiGlobalToastList` is used/extended in Kibana, so we need to export it as a member of `@elastic/eui`.
Open to naming suggestions other than `EuiGlobalToastListToast`; `Toast` just seemed too generic.
> Export `Toast` TS member

- CHANGELOG.md
- src-docs/src/views/guidelines/sass.js
- src/components/badge/_badge.scss
- src/components/button/_button.scss
- src/components/form/_mixins.scss
- src/components/series_chart/styles/react_vis/plot.scss
- src/components/tool_tip/_mixins.scss
- src/global_styling/functions/_colors.scss
- src/global_styling/variables/_colors.scss
- src/themes/eui/eui_colors_dark.scss
I'm tired of not having a black equivalent to `$euiColorGhost` so here its.
I also changed instances of `#000` to use the new variable.
> Added a fully black color variable `$euiColorInk`

- CHANGELOG.md
- src-docs/src/views/form_controls/form_control_layout.js
- src/components/color_picker/__snapshots__/color_picker.test.js.snap
- src/components/form/_mixins.scss
- src/components/form/_variables.scss
- src/components/form/field_number/__snapshots__/field_number.test.js.snap
- src/components/form/field_number/field_number.js
- src/components/form/field_number/field_number.test.js
- src/components/form/field_text/__snapshots__/field_text.test.js.snap
- src/components/form/field_text/field_text.js
- src/components/form/field_text/field_text.test.js
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.js.snap
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/form_control_layout.js
- src/components/form/form_control_layout/form_control_layout.test.js
- src/components/form/select/__snapshots__/select.test.js.snap
- src/components/form/select/select.js
- src/components/form/select/select.test.js
While working on #2049, I noticed that we don't currently account for the readonly state when using prepend/append.
This PR, passes the `readOnly` to the EuiFormControlLayout and applies the correct styling. This means also having to explicitly state and use it as a prop for EuiFieldNumber, EuiFieldText, and EuiSelect. These are also the only ones that currently support prepend/append.
**Before**
**After**
> Fix readonly input groups

- wiki/react-router.md
This PR adds the documentation on how we can forward the router with `v5`. 
I found the solution while testing with `react-router 5.0.0` installed and had to make my tests pass.
You can see here the change I had to make: https://github.com/elastic/kibana/pull/36871/files#diff-45ba9f8ef2d45b26681f545635cb504dR24
> Update README.md with example for react-router v5

- CHANGELOG.md
- src-docs/src/views/tabs/tabbed_content.js
- src/components/date_picker/super_date_picker/date_popover/date_popover_content.js
- src/components/tabs/index.d.ts
- src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.js.snap
- src/components/tabs/tabbed_content/tabbed_content.js
- src/components/tabs/tabbed_content/tabbed_content.test.js
The focus state of EuiTabs can confuse users since it's so prominent compared to the selected state. Some users thing the focus state **is** the selected state. This PR attempts to allow setting the initial focus of the tabbed items from `initial` (first tab) to `selected` (selected tab).
There are 2 issues with it at the moment:
- ~[ ] 1. If the selected tab is not the first, users have to <kbd>shift + tab</kbd> in order to get to the previous tabs.~ Got confirmation from most that this is not an issue.
--- 
Also fixes the second action item for the **EuiDatePicker** from GAH:
> Added `autoFocus` option to `EuiTabbedContent`

- CHANGELOG.md
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Cleans up renamed exports of TS types, such as [Toast as EuiGlobalToastListToast,](https://github.com/elastic/eui/commit/7de5b206163582e630145cf1c2d01f6b7a2c3ad3#diff-b5b09f81465c2c17912687397b176515R5) in _toast/index.ts_. There were two instances of the same bug, where the value being exported was observed instead of the local variable name.
After applying the fix & re-running babel on _toast/index.ts_ the new output is 
```
export { EuiToast } from './toast';
export { EuiGlobalToastList } from './global_toast_list';
export { EuiGlobalToastListItem } from './global_toast_list_item';
```
I also ran `icon/index.ts` to confirm this did not affect the existing type removal when the variable is not renamed.
~- [ ] This was …
> Strip TS type exports even when they are being renamed

- CHANGELOG.md
- src/components/icon/__snapshots__/icon.test.tsx.snap
- src/components/icon/assets/app_apm.js
- src/components/icon/assets/app_apm.svg
- src/components/icon/assets/logo_apm.js
- src/components/icon/assets/logo_apm.svg
- Updated the APM app icon because we have a new revised icon.
- Updated the APM solution logo
> [Icons] Updated APM app and solution logos

- CHANGELOG.md
- src/components/combo_box/index.d.ts
- src/components/combo_box/matching_options.test.ts
- src/components/combo_box/matching_options.ts
Fixes #2078 by updating the typescript definition for EuiComboBox's options' `value`.
I tested these changes in a new project to verify the generic was understood properly -
I also dropped the resulting _eui.d.ts_ file into Kibana and ran the typecheck script, there are two instances in _x-pack/legacy/plugins/siem/public/components/edit_data_provider/index.tsx_ where `EuiComboBox` is used through `styled-components` which interprets the generic as `{}` which is invalid. Both cases are solved by moving the css style onto `EuiComboBox` as a prop.
~- [ ] Jest tests were updated or added to match the …
> Update combobox option's value TS definition

- CHANGELOG.md
- src/components/color_picker/color_picker.test.js
- src/components/date_picker/super_date_picker/async_interval.test.js
- src/components/observer/mutation_observer/mutation_observer.test.tsx
- src/components/observer/resize_observer/resize_observer.test.tsx
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/popover.js
- src/components/popover/popover.test.js
- src/test/index.ts
- src/test/sleep.ts
Fixes #2042, in which a _closed_ `EuiPopover` inside of an _open_ `EuiPopover` will catch the `ESC` key press and prevent event propagation, preventing the open `EuiPopover` from closing.
More generally, this solution will allow propagation regardless of nesting/location if the `EuiPopover` is not open.
> Allow ESC to propagate if `EuiPopover` is not open

- src/components/basic_table/basic_table.js
So I was going through the eui docs and was trying to confirm whether a certain feature is available for my ancient version of eui by checking the source and came across this.
I'd say it's supposed to be a string. Could've been a react element but considering it gets pushed into attributes of html `input` tag, so it cannot be an element.
https://github.com/elastic/eui/blob/391dba27c7775bb5eafbb3c14386f84b5750b10d/src/components/form/checkbox/checkbox.js#L67
> minor code comment change

- CHANGELOG.md
- src/components/form/_mixins.scss
It looks like our prefixer doesn't prefix pseudo elements so I added more browser prefixes for the form control placholder text color. The biggest offender was IE:
> Fixed placeholder text color for more browsers

- CHANGELOG.md
- src-docs/src/views/popover/popover_block.js
- src-docs/src/views/popover/popover_example.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/color_picker/__snapshots__/color_picker.test.js.snap
- src/components/color_picker/_color_picker.scss
- src/components/color_picker/color_picker.js
- src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
- src/components/date_picker/super_date_picker/date_popover/date_popover_button.js
- src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.js.snap
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/form/super_select/_super_select.scss
- src/components/form/super_select/super_select.js
- src/components/popover/__snapshots__/popover.test.js.snap
- src/components/popover/_popover.scss
- src/components/popover/popover.js
- src/components/popover/popover.test.js
- src/components/search_bar/filters/__snapshots__/field_value_selection_filter.test.js.snap
I got really tired of having to give the popover and the anchor a className in order to override the `display: inline-block` property. So I created a prop on the component so now you can easily pass down `display: "block"` and it will apply to both elements.
1. [EuiSuperSelect](https://github.com/elastic/eui/pull/2112/files#diff-d8c4f706b866af7a0c272f4128faf18f)
2. [EuiSuperDatePicker](https://github.com/elastic/eui/pull/2112/files#diff-fa55a3db8835f939a4d433388a88db4d)
3. [EuiColorPicker](https://github.com/elastic/eui/pull/2112/files#diff-5e645efd120e1f5ba28918bc84f8b7c0) …
>  Added `display` prop to EuiPopover

- src/components/form/_mixins.scss
- src/components/form/_variables.scss
When playing around in sketch, I noticed that the border color is light transparency of one of our dark grays which when more transparent becomes less "blue". It's a very subtle difference, but now it looks like our horizontal rule and other border colors.
It needs to stay as a transparent inner shadow because it will overlap the background image which creates the thickened primary bottom border for the focus and invalid states.
You can see the difference if you compare the border color to the bottom border of the tabs above it.
- ~[ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked …
> [Feature branch] Updated form control border color

- .npmignore
- CHANGELOG.md
Fixes an issue with the published contents of EUI on npm. This restores all of the `.scss` files and `package/` directory in the build. Verified this passes Kibana's jest & type tests (with some known snapshots and TS changes, unrelated to the package contents).
> re-include all src scss files and packages/ dir in npm published build

- package.json
Fixes `docs` build by getting `postcss-loader` to use the correct config.
> remove postcss config from package.json

- package.json
- scripts/test-staged.js
Configures out existing `pre-commit` dependency to run a custom script on commit instead of `test`.
The custom hook gets the list of staged files from git and passes them to `jest --findRelatedTests` which only executes tests affected by the changes.
Note: this will only run tests affected by **staged** changes (those being included in the commit), it does **not** look at modified files outside the commit. I feel this best reflects the intention, but if people would prefer all uncommitted changes be used I can update.
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) …
> Run only tests affected by changes in commit hook

- src/components/common.ts
- src/components/form/form_control_layout/form_control_layout_icons.tsx
I've hit this a few times when typing complex prop interactions where `Omit` and `Pick` will transform optional props into required ones. In the past I've re-worked the types to get around the issue or (as was the case with EuiFormControlLayoutIcons) simply wrapped the result with a `Partial`. Stumbled upon a TypeScript github issue with distributed forms of those operations which solves the problem.
~- [ ] …
> Add DistributivePick and DistributiveOmit, update EuiFormControlLayoutIcons to use DistributiveOmit

- CHANGELOG.md
- src/components/combo_box/_combo_box.scss
The right-hand  padding for EuiComboBox was being overrided further down the selector. This fixes that.
**before** 
**after**
> Fixed EuiComboBox padding on the right

- CHANGELOG.md
- src/components/search_bar/query/ast.js
- src/components/search_bar/query/default_syntax.js
- src/components/search_bar/query/default_syntax.test.js
- src/components/search_bar/query/execute_ast.js
- src/components/search_bar/query/execute_ast.test.js
Closes #2107 by adding support for negated or clauses to `EuiSearchBar`.
> Allow EuiSearchBar group clauses to be negated

- wiki/component-development.md
`yarn link` no longer works. Updated the docs to give people options for something that does.
> Update docs on how to test local EUI in Kibana

- CHANGELOG.md
- src-docs/src/views/flyout/flyout_example.js
- src-docs/src/views/flyout/flyout_max_width.js
- src-docs/src/views/not_found/not_found_view.js
- src/components/flyout/__snapshots__/flyout.test.js.snap
- src/components/flyout/_flyout.scss
- src/components/flyout/flyout.js
Really all I did was change the docs example to a) not be wrong, b) showcase all the permutations to show what works and what doesn't.
But I also:
1. Rounded the SASS calculations so they don't come out as decimal points
2. Reduced the min width of the medium size so that it just fits our form width
3. Fixed the small flyout sizing on mobile
> Attempting to fix with EuiFlyout maxWidth

- src-docs/src/views/icon/icon_example.js
Fix an a11y typo in the icon docs that has been annoying me for ages.
> Fix typo in icon docs

- CHANGELOG.md
- src-docs/src/views/accordion/accordion_form.js
- src-docs/src/views/accordion/accordion_multiple.js
- src/components/accordion/__snapshots__/accordion.test.tsx.snap
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.tsx
Based on the issues stemming from negative margins and all the different options from EuiFlexGroup and wild nesting, I've removed this dependency for just applying `display: flex` in CSS.
Fixes the failed responsiveness when using the `extraAction` prop
I also added an example of how to truncate the text properly
cc @sulemanof @maryia-lapata 
> Remove EuiFlexGroup dependency from EuiAccordion

- src-docs/src/components/guide_components.scss
- src-docs/src/components/guide_page/guide_page_chrome.js
This has bugged me for a long time, also closes #2095. Enhances the docs' sidenav search to include subsections.
> Upgrade sidenav search to include sub-section titles

- src-docs/src/views/nav_drawer/nav_drawer.js
Closes #2094, although the outcome proposed in the issue isn't possible at this time. `EuiNavDrawer` can't take `onClick` events at every level without HTML validation warnings related to `button` as child of `button`. This simply changes the `href` target to be correctly relative, making nav item click events essentially do nothing (rather than 404).
~~- [ ] Jest tests were updated or added to …
> Relative `href` values in `EuiNavDrawer` example

- CHANGELOG.md
- src/components/tool_tip/__snapshots__/icon_tip.test.tsx.snap
- src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap
- src/components/tool_tip/tool_tip.test.tsx
- src/components/tool_tip/tool_tip.tsx
Tooltips have been adding their id to their anchor element as an `aria-describedby` attribute but that trips up a11y testing tools because the tooltips don't exist until after they're activated.
This change sets `aria-describedby` only when the tooltip is shown.
Closes #1533 
> Fix invalid aria-describedby values set by EuiToolTip (#1533)

- CHANGELOG.md
- src-docs/src/views/tables/basic/props_info.js
- src/components/basic_table/basic_table.js
Closes #2153 , small addition of `"center"` to the table's column align proptype. `"center"` is supported by the table header, footer, and cell components.
> Update EuiBasicTable's column proptype to support 'center' value for align

- packages/react-datepicker.js
- packages/react-datepicker/docs-site/bundle.js
- packages/react-datepicker/karma.conf.js
- packages/react-datepicker/package.json
- packages/react-datepicker/yarn.lock
Addresses some identified build/dev tooling vulnerabilities in the forked `react-datepicker` package.
This also updated enzyme packages & webpack configuration to get the `yarn test` command passing.
> Upgrade react datepicker deps

- CHANGELOG.md
- src-docs/src/views/guidelines/sass.js
- src-docs/src/views/utility_classes/utility_classes.js
- src/global_styling/utility/_utility.scss
@markov00 pointed out that our fallback for IE in `.eui-textOverflowWrap` wasn't quite right. We were close with all our text-wrapping properties but not quite right.
`word-break` is just to indicate **how** to break words, but `word-wrap` tells browser if they **should** break. With some browsers, you can't really use the former without first setting the latter to `break-word`.
This PR fixes the original `.eui-textBreakWord` utility class to be more browser compatible.
**It now works on IE:**
This also means that `.eui-textOverflowWrap` is now redundant to `.eui-textBreakWord` so I've set that for deprecation and removed it from the docs.
So now it's just back to the main 3 that work in **all** browsers similarly.
---
`. euiYScrollWithShadows` --> `.eui-yScrollWithShadows` since the …
> Fix text wrapping utilities

- CHANGELOG.md
- src-docs/src/views/form_controls/file_picker.js
- src/components/form/file_picker/__snapshots__/file_picker.test.js.snap
- src/components/form/file_picker/_file_picker.scss
- src/components/form/file_picker/_index.scss
- src/components/form/file_picker/_variables.scss
- src/components/form/file_picker/file_picker.js
This adds some more versions of the file picker since there were a few missing.
~I'm not thrilled with this name, I just was having trouble finding the appropriate name. In actuality we should allow the `compressed` prop to accept a boolean or some string that means "normal". Suggestions welcome.~ UPDATED
The main reason I created this one is because I've seen consumers use the "compressed" version when they just wanted the normal height/style input. But this is technically wrong, so this is more appropriate.
_This also fixed an issue where truncation wasn't working._
**And with multiple files**
There was a clash if popovers were anywhere near:
**Before**
The z-indexes weren't really necessary anyway since the input is first in DOM order.
**After**
For the large form, I just used the …
> More EuiFilePicker styles

- src-docs/src/views/super_select/super_select.js
- src-docs/src/views/super_select/super_select_complex.js
- src/components/context_menu/_context_menu_item.scss
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/form/super_select/_super_select.scss
- src/components/form/super_select/super_select.js
- src/components/form/super_select/super_select.test.js
The EuiSuperSelect's dropdown was way too big. It used the standard 16px font, but the input itself was still just 14px. This PR reduces the default font-size (and the padding) to create a more compact but still spacious dropdown.
^^ In the above "after" example, I also add a docs example for forcing truncation (this isn't the default).
**Complex example** looks better as well:
**Compressed especially looks better**
---
I also added a max-height of `300px` which is 100px taller than the EuiComboBox, since we want to try to display more of the complex style items.
---
Disabled items were grayed out but they were still getting the blue background on hover. This removes that hover state and adds the `not-allowed` cursor.
- ~[ ] Documentation …
> [Feature branch] Compressed EuiSuperSelect dropdown

- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/_data_grid.scss
- src/components/datagrid/_data_grid_column_resizer.scss
- src/components/datagrid/_data_grid_data_row.scss
- src/components/datagrid/_data_grid_header_row.scss
- src/components/datagrid/_index.scss
- src/components/datagrid/_variables.scss
- src/components/datagrid/data_grid.tsx
This is a really simple PR that just adds some basic Sass. It's just meant to make things mostly usable and isn't a deep dive into how we should necessarily do things.
I'm going to attempt to make these PRs frequent and small so that they are reviewable. All that said, early on a lot of this stuff is knowingly temporary as we build up the component. For example, I'm not concentrating too much on style yet since that will have it's own configuration layer.
This will likely change once node type content is passed in, but for now it works. We'll likely want to apply auto styling to certain data types so this is what too heavy handed.
* Made this stuff a lot easier to handle with a fat, invisible hitzone.
* Turned off `user-select` on the text in the header only (which it think should be ok …
> [EuiDataGrid] Base layer Sass

- CHANGELOG.md
- src/components/drag_and_drop/index.ts
Closes #2172, exports any interfaces EUI's drag&drop components imports from react-beautiful-dnd.
> Export used react-beautiful-dnd interfaces through EUI

- CHANGELOG.md
- src/components/nav_drawer/nav_drawer.js
Fixes #2175 
When minified, `EuiNavDrawerGroup`'s function name is shortened/mangled which caused the logic in `EuiNavDrawer` to break: `if (child.type.name === 'EuiNavDrawerGroup') {`
Instead of relying on the string name, this changes the logic to check for identity instead.
> Fix EuiNavDrawer to not rely on managleable function names

- CHANGELOG.md
- src/components/i18n/i18n.tsx
- src/components/stat/stat.tsx
Provides a better error message when an i18n mapping is defined as a formatting function but no values were provided.
> Update TS error-guard's text to be meaningful

- CHANGELOG.md
- src-docs/src/views/badge/badge_example.js
- src-docs/src/views/badge/badge_truncate.js
- src/components/badge/__snapshots__/badge.test.tsx.snap
- src/components/badge/_badge.scss
- src/components/badge/badge.tsx
Luckily it was mostly a matter of a missing class and missing truncation mixin. I also needed to add a `max-width: 100%` otherwise it wouldn't stop at the container's width.
It wouldn't even truncate at all
When it **did** truncate, it didn't do so correctly
Now it truncates no matter the contents. I also added the `innerText` to the `title` attribute of the surrounding content so that consumers don't have to worry about adding this or tooltips to show the full text.
> Fix EuiBadge truncation

- src-docs/src/views/datagrid/datagrid.js
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/_data_grid_data_row.scss
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_cell.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
Adds basic aria roles and focus controls.
- Write tests
> Adds basic aria roles and grid navigation

- CHANGELOG.md
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
Fixes #2185 by filtering out non-value exports from `node_modules` during build/babel. I tested by:
* diffing the `es` directory before-and-after this change, only components/drag_and_drop/index.js had changes
* created a new CRA repo and included and built with an `npm pack`ed version of EUI with these changes
> Remove TS types from exports when they come from node_modules

- src-docs/src/views/datagrid/datagrid.js
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/_data_grid.scss
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/data_grid_types.ts
- src/components/datagrid/grid_body.tsx
- src/components/table/table_pagination/__snapshots__/table_pagination.test.js.snap
- src/components/table/table_pagination/table_pagination.js
- src/themes/eui/eui_colors_dark.scss
**This is not the full implementation for pagination (can't disable individual pages, etc), but is a definition of the pattern and the change set is already getting big**
After the conversation on props vs. state for managing the grid's query, sorting, and pagination I went the route of pure props-driven, relying on the consuming component to hold and manage the state.
I also moved the row/body rendering into a separate component which cleaned out a _lot_ of code & logic from the top-level `EuiDataGrid`, using a `useMemo` hook to cache the processed rows instead of explicitly storing them on state.
In the future, user overrides may be held in the grid's internal state or may be expressed to the parent application in a way similar to this pagination.
@snide the overflow scrolling …
> Add pagination to EuiDataGrid

- CHANGELOG.md
- src-docs/src/views/header/_global_filter_group.scss
- src-docs/src/views/header/_global_filter_item.scss
- src-docs/src/views/header/global_filter_bar.js
- src-docs/src/views/header/global_filter_item.js
- src-docs/src/views/header/global_query.js
- src/components/badge/_badge.scss
... also finishes the fixes in  #2190 for IE by:
@snide If you can recall why that was in there I will try to find another solution. But that part of the styles was really conflicting with IE and forcing all those max-width calcs. Instead, I removed that to fallback to `border-box` and now just setting `max-width: 100%` accounts for all the extras.
**BEFORE**
**AFTER**
**Firefox**
**IE**
----
Most of these fixes will need to be repeated in Kibana 😓 but atleast this diff will tell us exactly what to do and we'll need the badge fix in there first.
- ~[ ] Checked for **accessibility** including keyboard-only and …
> Fix global filter truncation

- src-docs/src/components/guide_page/guide_page_chrome.js
Fixes #2183 
I couldn't find a root cause for IE11 to not update the URL, and thereby preventing routing. Apparently delaying the search state reset avoids the issue.
> Work around for IE11 sidenav navigation bug

- FAQ.md
The license link is broken. (removed .MD)
Fixed broken license link in FAQ page.
> Fix license link

- CHANGELOG.md
- src-docs/src/i18ntokens.json
- src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.js.snap
- src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.js.snap
- src/components/date_picker/super_date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/super_update_button.js
This adds i18m tokens to EuiSuperDatePicker and EuiSuperUpdateButton so they can be properly localized.
> adding i18n tokens to EuiSuperDatePicker and EuiSuperUpdateButton

- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
@daveyholler encountered this bug while working on a recursive tree component. The types->proptypes generator would infinite recurse if an interface or type referenced itself, e.g.
```
interface Foo {
children: Foo[];
}
```
This adds a check to verify we don't follow recursive references - for now this is done by resolving to a `PropTypes.any` as the object we would want to refer to doesn't exist (the JS code can't self-reference).
I verified this doesn't impact any existing components' proptypes by diffing the `es` and `lib` directories before and after the change.
~- [ ] Checked for **accessibility** …
> Allow self-referencing/recursive ts types

- src-docs/src/views/datagrid/datagrid.js
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/_data_grid.scss
- src/components/datagrid/_data_grid_column_resizer.scss
- src/components/datagrid/_data_grid_column_selector.scss
- src/components/datagrid/_data_grid_data_row.scss
- src/components/datagrid/_index.scss
- src/components/datagrid/column_selector.tsx
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_cell.tsx
- src/components/datagrid/data_grid_column_resizer.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/data_grid_types.ts
- src/components/form/switch/_switch.scss
- src/components/popover/_popover_footer.scss
- src/test/find_test_subject.ts
Adds column visibility and ordering options to EuiDataGrid.
I refactored `EuiDataGrid` from a class to a function component so it could use hooks. Implemented the column selector component as a hook, inspired by a conversation with @myasonik about child components reporting their data to parents in a tight feedback loop: `const [ColumnSelector, visibleColumns] = useColumnSelector(columns);`
> EuiDataGrid column visibility & ordering

- CHANGELOG.md
- src-docs/src/views/form_controls/switch.js
- src/components/form/_variables.scss
- src/components/form/switch/__snapshots__/switch.test.js.snap
- src/components/form/switch/_switch.scss
- src/components/form/switch/index.d.ts
- src/components/form/switch/switch.js
- src/global_styling/reset/_reset.scss
Kibana was [seeing issues with switches](https://github.com/elastic/kibana/issues/41522). Though we weren't able to figure out the root cause of the issue, switches have a unique aria role that they weren't taking advantage of. So, instead of continuing to dig, I thought I'd update the semantics skirting the issue a bit.
Following [Inclusive Component's recommendation](https://inclusive-components.design/toggle-button/) I've moved switches away from `<input type=checkbox />` to `<button role=switch aria-checked=true|false>`.
> Aligning switch semantics with aria role

- .npmignore
- package.json
- packages/eslint-plugin/.npmignore
- packages/eslint-plugin/README.md
- packages/eslint-plugin/index.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/rules/href_or_on_click.js
- packages/eslint-plugin/rules/href_or_on_click.test.js
- scripts/jest/config.json
- wiki/releasing-versions.md
- yarn.lock
In order to enforce rules like "only pass href, or onClick to `<EuiButton />`" outside of the library implementation, in a way that can be ignored on a case-by-case basis.
Failure:
> add `@elastic/eslint-plugin-eui` package

- CHANGELOG.md
- src-docs/src/views/date_picker/states.js
- src/components/date_picker/__snapshots__/date_picker.test.js.snap
- src/components/date_picker/date_picker.js
Adds an optional `onClose` prop to the the `EuiDatePicker` component. When present, it's passed to the `EuiFormControlLayout` that already wraps the date picker component, as its `onClick` method, so that the standard EUI close icon is applied.
> Adds onClear prop to EuiDatePicker to make it "clearable"

- scripts/compile-icons.js
First pass at a check for the `viewBox` attribute.  Happy to learn a more appropriate place for it or to adjust the behavior/output.
re: [this comment](https://github.com/elastic/eui/issues/2227#issuecomment-521294491) in #2227 Added [the command](https://github.com/elastic/eui/issues/276#issuecomment-356420133) supplied in #276 to `yarn compile-icons` but altered to only look in `src` files.
When run in `master @ 0594cc1` (which had 3 files missing the attribute) it correctly fails with:
```
Error processing /Users/jfsiii/work/eui/src/components/icon/assets/logo_docker.svg
Error: /Users/jfsiii/work/eui/src/components/icon/assets/logo_docker.svg is missing a 'viewBox' attribute
at iconFiles.forEach (/Users/jfsiii/work/eui/scripts/compile-icons.js:41:13)
at Array.forEach (<anonymous>)
at …
```
> compile-icons checks SVGs for viewBox attribute

- README.md
Removed .md extension from the link to LICENSE on the README file.
This was causing a redirect to 404 not found GitHub page when clicking the "Apache Licensed." link.
> Fixed license link on README

- CHANGELOG.md
- src/components/date_picker/super_date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/super_date_picker.test.js
Fixes a bug where a prop change of `isPaused` for SuperDatePicker is not reflected in the refresh interval.
- ~~Checked in **dark mode**~~ doesn't touch DOM
- ~~Checked in **mobile**~~ doesn't touch DOM
- ~~Checked in **IE11** and **Firefox**~~  doesn't touch DOM
- ~~Props have proper **autodocs**~~ doesn't touch props
- ~~Added **documentation** examples~~ doesn't change features
- ~~Checked for **accessibility** including keyboard-only and screenreader modes~~
> Fix SuperDatePicker isPaused prop update.

- src/components/toast/global_toast_list.test.tsx
Closes #1999 , converts the `EuiGlobalToastList` tests to use jest's fake timer API instead of hoping setTimeout executes exactly when it's expected.
> Use jest's fake timers to fix flaky test

- package.json
- src-docs/src/views/datagrid/datagrid.js
- src-docs/src/views/icon/icons.js
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/_data_grid.scss
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_body.tsx
- src/components/datagrid/data_grid_cell.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/utils.tsx
- src/services/key_codes.ts
- yarn.lock
Improved focus management for more complex cell contents. From the [a11y spec](https://docs.google.com/document/d/16Bje5R00cybqXeCvA0tLM4v8Dl3GwJG6o4etPCiChRM/edit?usp=sharing), this covers: 
- if a cell has one focusable element, default focus can go directly to the element
- if a cell has more than one focusable element or 1 focusable element with other content, the cell should receive focus but make it clear there is interactive content
- on [enter] if a cell contains one or more widgets, disables grid navigation and places focus on the first widget
- on [F2] same as enter; pressing [F2] again restores grid navigation
- [esc] restore grid navigation; if content was being edited, it may undo/cancel
- if grid navigation is disabled, [shift+tab/tab] can now navigate through widgets inside …
> Adds more complex focus control for DataGrid

- CHANGELOG.md
- src/components/button/button.tsx
- src/components/button/button_empty/button_empty.tsx
- src/components/button/button_icon/button_icon.tsx
- src/components/common.ts
- src/components/filter_group/index.d.ts
- src/components/pagination/pagination_button.tsx
TypeScript clean up related to a button component using `NoArgCallback<void>` for `onClick`. It instead needs to allow for an `event` param and discriminate between `a` and `button` element renders.
The component was used as the base for 2 other components, so they also needed to be updated.
> TS button `onClick` clean up

- CHANGELOG.md
- scripts/compile-eui.js
Extra `.ts` snuck in before the merge.
> `dist/eui_charts_theme` should be `.js`

- packages/react-datepicker/test/datepicker_test.js
- src/components/avatar/_avatar.scss
- src/components/badge/_badge.scss
- src/components/badge/notification_badge/_notification_badge.scss
- src/components/card/_card.scss
- src/components/filter_group/filter_button.js
- src/components/form/_mixins.scss
- src/components/form/file_picker/_file_picker.scss
- src/components/icon/_icon.scss
- src/components/image/_image.scss
- src/components/loading/_loading_spinner.scss
- src/components/modal/_modal.scss
- src/components/nav_drawer/_nav_drawer_group.scss
- src/components/table/_responsive.scss
- src/components/text/_text.scss
- src/components/tool_tip/_tool_tip.scss
- src/global_styling/functions/_colors.scss
I went to fix a typo in some documentation and discovered several instances of the same typo, so I went through and replaced them all. Also fixed a misspelling.
Super low priority, but hopefully useful.
> Fix some typoes in documentation/comments

- CHANGELOG.md
- src/components/date_picker/super_date_picker/super_date_picker.js
- src/components/date_picker/super_date_picker/super_date_picker.test.js
Follow up to #2250.
While the approach to add `componenDidUpdate()` in the PR linked above was the right one, the way the interval was updated didn't work out as intended. The code didn't properly stop any previous running interval. This updated PR changes the code to call `stopInterval()` in any case similar to how `onRefreshChange()` works. I also added some more tests to run against the interval updates.
- ~~Checked in **dark mode**~~ doesn't touch DOM
- ~~Checked in **mobile**~~ doesn't touch DOM
- ~~Checked in **IE11** and **Firefox**~~ doesn't touch DOM
- ~~Props have proper **autodocs**~~ doesn't change existing props
- ~~Added **documentation** examples~~ doesn't change features
- ~~Checked for **accessibility** including keyboard-only and screenreader modes~~
> Fix SuperDatePicker isPaused prop update (again).

- CHANGELOG.md
- src/components/context_menu/context_menu.tsx
Fixes a [bug introduced during TS conversion](https://github.com/elastic/eui/commit/1b7c29c4c0761ca50ee708d071dd820139993526#diff-43a73381f61128243de2427d64aba91dR181) where index of `0` isn't accounted for.
> `EuiContextMenu` `null` check for index

- package.json
- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
- src/components/flex/flex_group.tsx
- yarn.lock
Fixes #2302 
* updated our babel plugin to generate proptypes for `forwardRef` and `React.forwardRef` components
* upgraded to latest `babel-plugin-react-docgen` & `react-docgen`, which understands `React.forwardRef`
**caveat**: Although our babel plugin works on calls to `forwardRef`, the docgen plugin only works when the method is fully-qualified: `React.forwardRef`
I double checked our other `forwardRef` uses, but those couple components are never exposed to the docs' props layer and are fine as is.
For testing, I generated the `es` build directory for master + this branch and diffed them. The changes to `EuiFlexGroup` were the only meaningful changes, but it does also remove the now-known React component methods like `getDerivedStateFromProps` from the resulting docgen.
~- [ ] Checked …
> Generate & display React.forwardRef components' props in docs

- CHANGELOG.md
- src-docs/src/views/responsive/responsive_example.js
- src/components/code/_code_block.js
Fixes #2322 
EuiCodeBlock's `children` proptype has been `node` when the component internally treated it as `string`. This PR aligns the proptype to the component's intent while maintaining backwards compatibility for any existing implementations passing malformed `children`.
The bugs:
* "copy" button expects the value to be a single string
* dynamic content does not get reflected
The component needs to operate on a single string, but this constrains the developer experience to working in a non-React way when "interpolating" variables
`<EuiCodeBlock>Hello {name}</EuiCodeBlock>` creates a children of `['Hello', name]`, and forcing children to be a single string would require `<EuiCodeBlock>{'Hello ' + name}</EuiCodeBlock>` or some other way to pre-compute the string.
To support the React …
> Update EuiCodeBlock's children proptype

- src-docs/src/views/tool_tip/tool_tip_example.js
Removed reference to `clickOnly` prop from docs. Covers #2248 
> Updated tooltip docs

- CHANGELOG.md
- src/components/panel/panel.tsx
Closes #2329, which reports that the `onClick` def for `EuiPanel` isn't quite right. The `ExlusiveUnion` wasn't set up to be fully exclusive, so the def was ambiguous.
> Fix `EuiPanel` `onClick` def

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Closes #2303, which is an IE11 bug caused by a focus event and `setState` mistiming. IE11 needs a tick between calling `focus()` and `setState` so that the latter always happens second and prevents re-opening of the list.
> Use requestAnimationFrame on EuiComboBox singleSelection close

- src-docs/src/views/datagrid/styling.js
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_body.tsx
- src/components/datagrid/data_grid_cell.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/style_selector.tsx
Cleans up / refactors the hooks in data_grid.tsx. The goal was to make the overall structure more readable and make dependencies more explicit.
@snide I changed the logic around styles, overrides, etc. Please play with the docs to make sure it's acting the same way.
> EuiDataGrid hooks cleanup

- src-docs/src/theme_dark.scss
- src-docs/src/theme_light.scss
These got removed during a rebase or mege in #2270. Adding them back in fixes chart rendering in the docs. The EUI build assets in `14.1.0` are unaffected (charts theme is still usable).
> Put charts theme files back

- CHANGELOG.md
- src-docs/src/views/form_controls/file_picker.js
- src-docs/src/views/popover/popover_fixed.js
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/popover/__snapshots__/popover.test.tsx.snap
- src/components/popover/_popover.scss
- src/components/popover/popover.tsx
The z-index is based off of the parent and the triggering element. But if both are `0`, then so is the popover which causes anything with a z-index of `1` or more to show on top.
**Before**
I've added an example in the File Picker docs section that will show:
**Before**
**After**
I'll remove this before merge but allows for easy testing.
**And popovers in flyouts still work**
> Added additional/base amount of z-index to popovers

- CHANGELOG.md
- src-docs/src/views/button/button_group.js
- src-docs/src/views/form_compressed/complex_example.js
- src/components/button/button_group/__snapshots__/button_group.test.tsx.snap
- src/components/button/button_group/_button_group.scss
- src/components/button/button_group/button_group.test.tsx
- src/components/button/button_group/button_group.tsx
- src/components/button/button_toggle/index.ts
- src/components/button/index.ts
EuiButtonGroup's `buttonSize` prop now also accepts `compressed`. Which creates the following.
I also beefed up the tests for EuiButtonGroup that only had one in it.
> Created compressed EuiButtonGroup

- CHANGELOG.md
- src-docs/src/views/form_controls/form_controls_example.js
- src-docs/src/views/form_controls/prepend_append.js
- src/components/combo_box/index.d.ts
- src/components/date_picker/_date_picker_range.scss
- src/components/form/_mixins.scss
- src/components/form/_variables.scss
- src/components/form/checkbox/index.d.ts
- src/components/form/field_search/index.d.ts
- src/components/form/form_control_layout/_form_control_layout.scss
- src/components/form/form_control_layout/_form_control_layout_delimited.scss
- src/components/form/form_row/_form_row.scss
- src/components/form/form_row/index.d.ts
- src/components/form/radio/index.d.ts
- src/components/form/switch/index.d.ts
- src/components/suggest/__snapshots__/suggest_input.test.js.snap
- src/components/suggest/_suggest_input.scss
- src/components/suggest/suggest_input.js
There were some `compressed` props missing from the TS def files of some controls.
... and fixed up some styling especially if consumer was passing a popover or tooltip. These types of elements didn't get proper styling because the className wasn't being passed down to the right element it would have needed to be pass as the `anchorClassName`. The docs section is pretty robust showing lots of different types of elements being passed in.
> Compressed Fixes  Round 1

- CHANGELOG.md
- src/components/form/form_error_text/_form_error_text.scss
> Apply same top padding to EuiFormErrorText as EuiFormHelpText

- src-docs/src/views/datagrid/datagrid.js
- src-docs/src/views/datagrid/datagrid_example.js
- src-docs/src/views/datagrid/in_memory.js
- src-docs/src/views/datagrid/schema.js
- src/components/datagrid/_data_grid.scss
- src/components/datagrid/_data_grid_data_row.scss
- src/components/datagrid/_data_grid_header_row.scss
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_body.tsx
- src/components/datagrid/data_grid_cell.tsx
- src/components/datagrid/data_grid_data_row.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/data_grid_inmemory_renderer.tsx
- src/components/datagrid/data_grid_schema.ts
- src/components/datagrid/data_grid_types.ts
Adds a schema-detection pass to EuiDataGrid. The detection looks at the rendered content and scores each value against each type. A column's type scores are then aggregated by taking the `mean - standard_deviation`, and the best resulting type score wins.
Additional schema detectors can also be passed as a prop to EuiDataGrid.
@snide I threw the SCSS changes in to verify things were working, feel free to fix them up directly on this branch.
> [EuiDataGrid] Automatic column schema detection

- CHANGELOG.md
- src-docs/src/views/tables/actions/actions.js
- src-docs/src/views/tables/basic/props_info.js
- src/components/basic_table/__snapshots__/collapsed_item_actions.test.js.snap
- src/components/basic_table/basic_table.js
- src/components/basic_table/collapsed_item_actions.js
- src/components/basic_table/default_item_action.js
Closes #1807 
I added a `data-test-subj` to the collapsed actions button and allowed properties on default action types (non-custom actions can already specify the data-test-subj however they'd like). The `Adding actions to BasicTable` doc section was updated to include `data-test-subj`s and can be used to verify they are applied to the DOM in the three non-custom action locations:
* single action
* multiple actions, not in popover
* multiple actions, in popover 
/cc @lizozom @pheyos 
> Add data-test-subj support to non-custom table actions

- CHANGELOG.md
- src/components/popover/popover.tsx
Summarize your PR. If it includes design elements include a screenshot or gif.
> Fixed Issue #2362

- CHANGELOG.md
- src/components/basic_table/__snapshots__/basic_table.test.js.snap
- src/components/basic_table/basic_table.js
Closes #2370. Hard codes `textOnly={false} on `EuiBasicTable`'s expanded rows. This allows the content to properly grow to the full width of the expanded row.
/cc @justinkambic 
> Make EuiTableRowCell textOnly={false} when its an expanded row

- CHANGELOG.md
- src-docs/src/views/drag_and_drop/drag_and_drop.js
- src-docs/src/views/drag_and_drop/drag_and_drop_clone.js
- src-docs/src/views/drag_and_drop/drag_and_drop_complex.js
- src-docs/src/views/drag_and_drop/drag_and_drop_custom_handle.js
- src-docs/src/views/drag_and_drop/drag_and_drop_disable_blocking.js
- src-docs/src/views/drag_and_drop/drag_and_drop_move_lists.js
- src-docs/src/views/drag_and_drop/drag_and_drop_types.js
- src/components/drag_and_drop/index.ts
- src/components/drag_and_drop/services.ts
- src/components/index.js
Fixes #2372 by exporting the `copy`, `move`, and `reorder` drag-and-drop service methods. I tested by building EUI with this change and `require`ing the built package into node, verifying the three methods exist as expected.
> Export drag and drop service methods

- src/components/filter_group/index.d.ts
I am currently preparing the TS 3.7 upgrade in Kibana (https://github.com/elastic/kibana/pull/47188). There is currently one failure coming from EUI, that this PR fixes. It seems that newer TS versions make a difference between having a function (that `render` is in the base class) and an property assigned an arrow function, which we had in this typing. So TS 3.7 will [fail on this](https://kibana-ci.elastic.co/job/elastic+kibana+pipeline-pull-request/2162/console) on:
```
node_modules/@elastic/eui/eui.d.ts(2417,6): error TS2424: Class 'Component<CommonProps & ButtonHTMLAttributes<HTMLButtonElement> & EuiFilterSelectItemProps, {}, any>' defines instance member function 'render', but extended class 'EuiFilterSelectItem' defines it as instance member property.
```
Changing the typing here …
> Change `render` signature to function from property

- src-docs/src/views/tables/custom/custom.js
Removed extra footer cell from "Build a custom table from individual components" example. 
Covers #2407.
> Removed extra footer cell from docs

- CHANGELOG.md
- src-docs/src/views/list_group/list_group.js
- src-docs/src/views/list_group/list_group_extra.js
- src/components/list_group/_list_group_item.scss
Added focus state to `EuiListGroupItem` and updated some of the docs examples.
Covers #2266
> Added focus state to EuiListGroupItem

- src/components/index.js
- src/components/inner_text/index.ts
#2392 introduced a new `useRenderToText` hook but didn't export it outside of EUI. This PR corrects that.
> [EuiDataGrid] Export useRenderToText

- CHANGELOG.md
- src/components/page/page_body/__snapshots__/page_body.test.js.snap
- src/components/page/page_body/page_body.js
Added `component` prop to `EuiPageBody`. Default value is `main`, consumer can pass a different html tag if needed.
Covers #2359
-[X] Props have proper **autodocs**
-[X] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked appropriately
> Added component prop to EuiPageBody

- CHANGELOG.md
- src-docs/src/views/form_layouts/form_rows.js
- src/components/code_editor/__snapshots__/code_editor.test.js.snap
- src/components/code_editor/code_editor.js
- src/components/code_editor/code_editor.test.js
- src/components/date_picker/super_date_picker/date_popover/relative_tab.js
- src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.js.snap
- src/components/date_picker/super_date_picker/quick_select_popover/_commonly_used_time_ranges.scss
- src/components/date_picker/super_date_picker/quick_select_popover/_index.scss
- src/components/date_picker/super_date_picker/quick_select_popover/_quick_select.scss
- src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss
- src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.js
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select.test.js
- src/components/date_picker/super_date_picker/quick_select_popover/refresh_interval.js
- src/components/flex/__snapshots__/flex_item.test.tsx.snap
- src/components/flex/flex_grid.tsx
- src/components/flex/flex_item.test.tsx
- src/components/flex/flex_item.tsx
- src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap
- src/components/form/form_row/__snapshots__/form_row.test.js.snap
- src/components/form/form_row/form_row.js
Fixes several of misc a11y issues showing up in Kibana:
- Poor labeling in `EuiSuperDatePicker` ([Kibana issue 38794](https://github.com/elastic/kibana/issues/38794)) (this kind of snowballed into improving several things in the vicinity)
- Fixes #2416: `EuiFormRow`s that render fields that also render a label end up rendering multiple labels for an input which breaks many assistive tech (this issue was found during the in progress Kibana rollout of automated a11y testing ([Kibana issue 43584](https://github.com/elastic/kibana/pull/43584) )
- Fixes #2414: `EuiCodeEditor`s would render with the same ID which breaks many assistive tech (this issue was found during the in progress Kibana rollout of automated a11y testing)
~- [ ] …
> Fixes several a11y issues manifesting in Kibana

- CHANGELOG.md
- src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.js.snap
- src/components/date_picker/super_date_picker/quick_select_popover/quick_select.js
Just a small follow-up on #2411, tweaking a few attributes. 
> Cleanup around EuiSuperDatePicker quick select a11y

- CHANGELOG.md
- src/components/breadcrumbs/breadcrumbs.tsx
Fixes a React hooks [invariant violation](https://reactjs.org/warnings/invalid-hook-call-warning.html) in Kibana related to the use of `useInnerText` in `EuiBreadcrumbs`. The hook was improperly used inside of a `.map` callback, although caused no errors in the EUI docs.
The fix is to use the pass-through `EuiInnerText` component instead.
> Use `EuiInnerText` in `EuiBreadcrumbs`

- CHANGELOG.md
- scripts/dtsgenerator.js
- src/components/button/button_empty/button_empty.tsx
- src/components/button/button_empty/index.ts
- src/components/button/button_group/button_group.tsx
- src/components/button/button_icon/button_icon.tsx
- src/components/button/button_icon/index.ts
- src/components/button/index.ts
- src/components/link/index.ts
- src/components/link/link.tsx
Exports formerly exported types:
* `ButtonSize`
* `ButtonIconSide`
* `EmptyButtonColor` (now `EuiEmptyButtonColor`)
* `EmptyButtonSizes` (now `EuiEmptyButtonSizes`)
* `ButtonIconColor` (now `EuiButtonIconColor`)
* `EuiLinkColor`
* `EuiLinkType`
> Export missing type definitions

- CHANGELOG.md
- src/components/side_nav/__snapshots__/side_nav.test.js.snap
- src/components/side_nav/__snapshots__/side_nav_item.test.js.snap
- src/components/side_nav/side_nav.js
- src/components/side_nav/side_nav_item.js
`EuiSideNav` was making a promise that it couldn't keep. (Metaphor explainer: a custom `role` is a promise that developer is making to the assistive tech on how something will work.) Better to ship a simpler structure that's not broken but could be better rather than ship broken semantics.
`EuiSideNav` can still be improved but this is a small, quick PR to make it just a bit better.
> remove menubar role from EuiSideNav

- src-docs/src/views/tables/basic/props_info.js
Resolves #2432 
Corrected the props' docs for `selection.onSelectionChange` in tables. There are other instances of `onSelectionChanged` remaining in some test files but these are already addressed in #2428 
> Correct the tables' listing of onSelectionChanged -> onSelectionChange

- CHANGELOG.md
- src/components/basic_table/__snapshots__/in_memory_table.test.js.snap
- src/components/table/__snapshots__/table_footer_cell.test.tsx.snap
- src/components/table/__snapshots__/table_header_cell.test.tsx.snap
- src/components/table/__snapshots__/table_header_cell_checkbox.test.tsx.snap
- src/components/table/__snapshots__/table_row_cell.test.tsx.snap
- src/components/table/table_footer_cell.test.tsx
- src/components/table/table_footer_cell.tsx
- src/components/table/table_header_cell.test.tsx
- src/components/table/table_header_cell.tsx
- src/components/table/table_header_cell_checkbox.test.tsx
- src/components/table/table_header_cell_checkbox.tsx
- src/components/table/table_row_cell.test.tsx
- src/components/table/table_row_cell.tsx
- src/components/table/utils.test.ts
- src/components/table/utils.ts
After converting the `EuiTable` suite to TypeScript, obsolete `table` element DOM attributes like `width` stopped being accepted (`TdHTMLAttributes<HTMLTableCellElement>` does not extend obsolete attributes). `width` is still a desirable property, and one that EUI explicitly supported in some cases.
This explicitly adds `width` to table cell components and uses the recommended CSS transfer to apply the style. 
Note that other obsolete attributes are no longer supported, but would still be applied via `{...rest}` with `// @ts-ignore`. Closes #2436.
> `width` attribute for `EuiTable` cell components

- src-docs/src/views/datagrid/datagrid.js
- src/components/datagrid/__snapshots__/data_grid.test.tsx.snap
- src/components/datagrid/column_selector.tsx
- src/components/datagrid/column_sorting.tsx
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_types.ts
- src/components/datagrid/style_selector.tsx
Allows you to turn the toolbar on and off through a prop `toolbarDisplay`
`toolbarDiplay` can either take a boolean or object.
* If passed false, the entire toolbar does not show
* if passed an object, you can individually pass each toolbar control a false value to turn it off
I also changed some naming in here to be a little more clean. Tests added for turning the toolbar off and for turning one of the buttons off (which I think it good enough for the whole set)
Adjust `toolbarDisplay` options. I added some to `datagrid.js` for now, but I'll refactor this in my docs PR to be better.
> [DATA GRID] EuiGridToolBar toolbar is now configurable through props

- wiki/testing.md
A test contained a variable named "onCloseHandler", however the component below tried to use "onClickHandler". Renamed variable to "onClickHandler" to better match the purpose of the test and fix this error.
> Fix variable naming error in testing.md doc

- src-docs/src/views/form_controls/display_toggles.js
Removed canFullWidth propType duplicate
> Removed duplicate propType

- CHANGELOG.md
- src/components/nav_drawer/_nav_drawer.scss
- src/components/nav_drawer/nav_drawer.js
I reverted some changes introduced in #2417 and ended up with the original situation (i.e. a collapse/expand button with a weird focus behaviour). However, I think I've found a way to fix this using the `:focus-within` selector.
This is the behaviour now:
Fixes #2456 
Note: I moved `footerContent` back to its original position (above `modifiedChildren`) as I had missed a comment we have explaining why we need to have it before `modifiedChildren`.
> Fix EuiNavDrawer collapse/expand button height issue

- CHANGELOG.md
- src-docs/src/views/badge/badge.js
This removes a console warning that appears because we're passing "disabled" as a color in the docs for `EuiBadge` (introduced in #2440). I picked a random color to be the disabled badge. Let me know if you'd prefer to turn one of the existing colors into the disabled one. 
> Fixed console warning for disabled EuiBadge

- CHANGELOG.md
- src-docs/src/views/guidelines/index.scss
- src-docs/src/views/guidelines/sass.js
- src-docs/src/views/utility_classes/utility_classes.js
- src/global_styling/mixins/_helpers.scss
- src/global_styling/mixins/_shadow.scss
- src/global_styling/utility/_utility.scss
This new mixin `euiXScrollWithShadows` and utility class `.euiXScrollWithShadows` compliment the already existing mixin `euiYScrollWithShadows` and utility class `.euiYScrollWithShadows`.
> Added horizontal scroll mixin

- CHANGELOG.md
- src/components/form/super_select/__snapshots__/super_select.test.js.snap
- src/components/popover/__snapshots__/popover.test.tsx.snap
- src/components/popover/popover.tsx
An a11y addition to `EuiPopover` during datagrid work had a small typo 😄 
> Fix `aira-modal` typo

- CHANGELOG.md
- src/components/code/_code_block.js
Fixing issue where `EuiCodeBlock` always expands to given `overflowHeight` even when content does not require it. Fixes #2435
> Fix overflowHeight in EuiCodeBlock

- src-docs/src/views/color_picker/color_picker_example.js
`Free-range color stops` docs load the wrong source so `Demo JS` does not contain the correct code that is being used in the examples.
This PR just loads the correct source code for the docs
> use correct source to color stops range examples

- CHANGELOG.md
- src/components/color_picker/color_stops/color_stops.tsx
Notice when the input is an empty string and then the markers are all messed up. This is because `getRangeMin` and `getRangeMax` do not handle empty string values and can return `NaN`.
> [EuiColorStops] ignore empty values when getting range max and min

- CHANGELOG.md
- src/components/color_picker/color_stops/color_stop_thumb.test.tsx
- src/components/color_picker/color_stops/color_stop_thumb.tsx
- src/components/color_picker/color_stops/color_stops.test.tsx
- src/components/color_picker/color_stops/color_stops.tsx
- src/components/form/range/range_thumb.tsx
Closes #2497, which highlights a experience concern with which popover is open during serial drag events. This solves the problem by moving popover toggling from `onClick` to `onMouseDown`, and moving popover state management "up" to the parent component.
> `EuiColorStops` change popover open from onClick to onMouseDown

- CHANGELOG.md
- src/components/accordion/__snapshots__/accordion.test.tsx.snap
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.tsx
Uses er 90 degree transition instead of fade-in.
> Animate EuiAccordion arrow on open

- CHANGELOG.md
- package.json
- yarn.lock
Fixes https://github.com/elastic/eui/issues/2513
Only change in `2.2.1..2.2.2` is renaming deprecated lifecycle methods [per CHANGELOG](https://github.com/JedWatson/react-input-autosize/blob/0aa6225fb4ae4e30d51a23f75b36b15e709efdd0/HISTORY.md#v222--2019-01-10)
> Bump React Autosize

- src/components/steps/step_horizontal.tsx
The negation of `isComplete` always evaluate to true because of this [line](https://github.com/elastic/eui/blob/aaa1b5c6799e301514423f4722e7a46e270c6d68/src/components/steps/step_horizontal.tsx#L59).
> Removed unnecessary conditional

- CHANGELOG.md
- src/components/form/switch/__snapshots__/switch.test.tsx.snap
- src/components/form/switch/switch.tsx
Per https://dequeuniversity.com/rules/axe/3.3/button-name?application=axeAPI, `EuiSwitch` should be using `aria-labelledby` instead of `aria-describedby`.
> `EuiSwitch` use `aria-labelledby`

- CHANGELOG.md
- src/components/page/index.d.ts
- src/components/panel/panel.tsx
I added the `HTMLAttributes<HTMLDivElement>` type to EuiPageContent, because it seemed to be missing. 
I've noticed this because I tried to use the style prop, but it wasn't available and I had to //@ts-ignore the component.
> Added missing union type for EuiPageContent

- CHANGELOG.md
- package.json
- yarn.lock
Nothing fundamental changes. I took the liberty to upgrade to `7.0.5` which is the last non-breaking release of `react-ace`, as `react-ace@8` comes with some breaking changes that are more involved, but that we don't need to get into really
> Update `react-ace` because `UNSAFE_*` warnings

- src-docs/src/views/badge/badge.js
`EuiBadge` example was logging a warning due to an invalid hex value.
> Fix docs console warning

- CHANGELOG.md
- src/components/form/switch/switch.tsx
The name prop is being de-structured in the switch component but it unused. Because of this it's pulled out of `...rest` being passed into the element attributes which we need in cloud as we use it in conjunction with Formik in some cases. Currently blocking https://github.com/elastic/cloud/pull/43440
Not sure if I add this to the changelog or not as it's not part of the public API? Also unsure if …
> Passing name attribute into switch component

- CHANGELOG.md
- src/components/button/_button.scss
Fixes #2525 
I have add one line of code in scss, check and see is it what you want. If not, let me know, I can fix it.
> Fix issue#2525 Make disabled button styles uniform

- CHANGELOG.md
- src-docs/src/views/form_controls/checkbox_group.js
- src/components/form/checkbox/index.d.ts
Related to https://github.com/elastic/eui/issues/2538
Fixes bug in the `EuiCheckboxGroup` demo page in which both enabled and disabled groups were using the same ids for their checkbox input components, which caused the disabled ones to be checkable
> Fixes bug in the `EuiCheckboxGroup` demo page and add `disabled` to TS defs

- CHANGELOG.md
- src-docs/src/views/form_controls/checkbox_group.js
- src/components/form/checkbox/__snapshots__/checkbox_group.test.js.snap
- src/components/form/checkbox/checkbox_group.js
- src/components/form/checkbox/checkbox_group.test.js
- src/components/form/checkbox/index.d.ts
Related to https://github.com/elastic/eui/issues/2539
Added `disabled` option to the `option` attribute of the `options` object that is passed to the `EuiCheckboxGroup` so that checkboxes in a group can be individually disabled
> Adds possibility to disable checkboxes individually in an EuiCheckboxGroup component

- src-docs/src/views/inner_text/inner_text.js
- src/components/color_picker/color_picker.tsx
- src/components/color_picker/color_stops/color_stop_thumb.tsx
- src/components/color_picker/color_stops/color_stops.tsx
- src/components/color_picker/saturation.tsx
- src/components/color_picker/utils.ts
- src/components/form/range/range_ticks.tsx
- src/components/inner_text/inner_text.tsx
- src/components/inner_text/render_to_text.tsx
- src/components/popover/input_popover.tsx
First of two PRs. This fixes all the non-datagrid hooks warnings & errors as reported by `react-hooks/rules-of-hooks` & `react-hooks/exhaustive-deps`. I'm following up with a PR for the datagrid ones, along with enabling that eslint rule.
I reviewed the hooks' logic & interaction, and spot-checked each component after the changes. I didn't notice any difference in their operation.
~- [ ] A …
> Fix all non-datagrid hooks lint issues

- CHANGELOG.md
- src-docs/src/views/datagrid/datagrid_schema_example.js
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_schema.tsx
Fixes #2460 
Avoids running schema-detection on columns which already have a schema.
> [DATA GRID] Avoid schema detection on columns which already have a schema

- .eslintrc.js
- src-docs/src/views/datagrid/datagrid.js
- src-docs/src/views/datagrid/in_memory.js
- src-docs/src/views/datagrid/in_memory_enhancements.js
- src-docs/src/views/datagrid/in_memory_pagination.js
- src-docs/src/views/datagrid/in_memory_sorting.js
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid.tsx
- src/components/datagrid/data_grid_body.tsx
- src/components/datagrid/data_grid_header_row.tsx
- src/components/datagrid/data_grid_inmemory_renderer.tsx
- src/components/datagrid/data_grid_schema.tsx
Second hooks PR, this fixes a number of hooks warnings & errors in src & docs. No functionality changes, but it does fix a bug in the docs' in-memory demo. This also enables the react hooks eslint rule.
> Fix datagrid use of hooks

- package.json
- scripts/jest/polyfills/mutation_observer.js
- yarn.lock
* Removed `npm-run` dependency (has not been used for a while)
* Upgraded `caniuse-db` and `caniuse-lite` packages
* Increased the MutationObserver polyfill's max event listeners to prevent the max-listeners potential memory leak message. This comes from some test setups not executing a component's unmount.
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked …
> Some dependency management and unit test messaging cleanup

- CHANGELOG.md
- src/components/badge/beta_badge/_beta_badge.scss
- src/components/badge/beta_badge/beta_badge.tsx
- src/components/card/card.tsx
Since EuiBetaBadge's don't actually have any clickability to them, they were ignored from the tab order and therefore, the description which only shows on hover could never be read by a screenreader. This PR basically just adds `tab-index=0` to the element putting it into the focus order of the DOM. We handle this the same way for EuiIconTip.
This also then required moving the DOM order of the beta badge in EuiCard so that it didn't come before the title of the card.
> Fixed EuiBetaBadge a11y

- CHANGELOG.md
- src/components/context_menu/__snapshots__/context_menu.test.tsx.snap
- src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap
- src/components/datagrid/data_grid_inmemory_renderer.tsx
- src/components/icon/icon.test.tsx
- src/components/icon/icon.tsx
- src/services/react.ts
For performance reasons, EuiDataGrid utilizes `react-dom::unstable_batchedUpdates` to ensure setState calls are batched. EuiIcon suffers from not doing the same thing, which this PR resolves.
Shown in the screen shots below, the current performance is a 1.6s second UI-blocking back-to-back sequence of icon updates. The batched performance shows multiple frame renders and one consolidated React update operation.
I also added an `onIconLoad` prop to simplify the testing experience, as icon tests must now wait for the queued setState to finish in addition to the dynamic import resolving.
~- [ ] Checked for **accessibility** including …
> Extract setState queuing into a service, re-use it in EuiIcon

- CHANGELOG.md
- src/components/button/button_group/_button_group.scss
- src/components/form/_variables.scss
Fixes https://github.com/elastic/eui/issues/2564
Adds background color to compressed button groups to prevent underlying background from showing through. Also, reduced the tint on 'selected' button background color for a touch more contrast.
As you'll see below, these minor changes result in the button groups also aligning better to the styles of the other compressed inputs.
> adds background-color to compressed button group

- package.json
- scripts/release.js
* Adds a prompt for npm one-time password before `npm publish` step.
* Increases memory for `build-docs` script as it consistently hits the limit and hangs.
> Release script updates

- CHANGELOG.md
- src/components/form/switch/_switch.scss
- src/components/form/switch/switch.tsx
This fixes the regression of `EuiSwitch` component:
- The switch is clickable even in `disabled` state if click on label:
- Label displays under the switch button if there is not enough space:
Found in kibana:
Using flex box it looks better:
> Fixed `EuiSwitch` clicking on disabled label

- CHANGELOG.md
- src/components/combo_box/__snapshots__/combo_box.test.js.snap
- src/components/combo_box/combo_box.js
Closes https://github.com/elastic/eui/issues/2583
In `EuiComboBox` sets focus back to the input element after each scroll. In order to do that I took advantage of the `onScroll` hook of the `List` component.
> EuiComboBox: Sets focus back to the input element after each scroll

- src-docs/src/components/guide_locale_selector/guide_locale_selector.js
#2518 added a babelfish moment config that can be enabled via a 'Doc Options' toggle (intended for dev only). Defining a new locale via `moment.defineLocale`, though, also sets the app's _default_ locale. As the locale was never reset to 'en' after defining 'en-xa', all components that do no use `EuiI18nConsumer` to consume the togglable locale have formatted dates displayed in babelfish. This also happens in the production build, as the babelfish locale is still defined.
This PR sets moment's default locale back to 'en' after defining 'en-xa'. The babelfish toggle still works in dev (see datepicker examples).
~~- [ ] Added …
> Fix default docs moment locale

- CHANGELOG.md
- src/components/form/checkbox/index.ts
Completed exports:
* `EuiCheckboxType`
* `EuiCheckboxGroupOption`
* `EuiCheckboxGroupIdToSelectedMap`
> `EuiCheckbox` and `EuiCheckboxGroup` type exports

- CHANGELOG.md
- src/components/accordion/__snapshots__/accordion.test.tsx.snap
- src/components/accordion/_accordion.scss
- src/components/accordion/accordion.tsx
Closes https://github.com/elastic/eui/issues/2591
Fixes `EuiAccordion` icon rotation when it is a child of another `EuiAccordion` (avoids inheritance of the opened state).
> EuiAccordion: fixes rotation of icon when child of another EuiAccordion

- CHANGELOG.md
- src/components/datagrid/data_grid.tsx
Resolves the UX bug mentioned in https://github.com/elastic/eui/pull/2519#issuecomment-555223888
This introduces a new hook that is used to wait for two of React's DOM flushes before updating the focus. This allows the `cellsUpdateFocus` state to avoid direct manipulation and better orchestrates the focus management. It's likely this hook is abstracted further to replace other instances of `requestAnimationFrame` in the future.
> [DataGrid] Fix cell focus on keyboard pagination

- CHANGELOG.md
- src/components/drag_and_drop/__snapshots__/droppable.test.tsx.snap
- src/components/drag_and_drop/droppable.test.tsx
- src/components/drag_and_drop/droppable.tsx
The type definitions for EuiDroppable don't seem to allow multiple children. You can't use examples from the docs, without surrounding multiple children in their own `<></>` fragment node - this change attempts to remedy that issue.
I'll be honest, I'm not sure if `ReactElement[]` is the best type for this, I did try to use `ReactNode`, but that prevented other parts of the type definition from working, whereas `ReactElement[]` didn't stop anything else from working.
A test case has been added.
~~- [x] Checked in **dark mode**~~
~~- [x] Checked in **mobile**~~
~~- [x] Checked in **IE11** and **Firefox**~~
~~- [x] Props have proper **autodocs**~~
~~- [x] Added **documentation** examples~~
~~- [x] Checked for **breaking changes** and labeled appropriately~~
~~- [x] Checked for …
> EuiDroppable now accepts multiple children (TypeScript)

- CHANGELOG.md
- src/components/combo_box/combo_box.js
Fixes #2637, in which using <kbd>Enter</kbd> to select a list option could unintentionally trigger `form` submission.
> `EuiComboBox` prevent form submission

- CHANGELOG.md
- src/components/list_group/list_group_item.tsx
- src/components/nav_drawer/nav_drawer.js
Chipping away at #2252 
* > On clicking the expand/collapse button, focus management is lost and is returned to the body. (It should stay on the button.)
* > The dock/undock button should have aria-pressed=true|false defined to communicate state. This can replace the role=switch and aria-checked=true|false
* Some clean up to remove an unused method and an outdated comment
> `EuiNavDrawer` a11y, pt. 1

- src-docs/src/routes.js
- src-docs/src/views/date_picker/date_picker_example.js
- src-docs/src/views/super_date_picker/super_date_picker.js
- src-docs/src/views/super_date_picker/super_date_picker_config.js
- src-docs/src/views/super_date_picker/super_date_picker_custom_quick_select.js
- src-docs/src/views/super_date_picker/super_date_picker_example.js
This PR gives `EuiSuperDatePicker` its own section in EUI docs. 
Following the original ticket, I've added the main example and two other sections (1) configurations and 2) quick select custom panel.
I also added a brief description in which I highlight the quick select menu and its sections.
Screenshot - New description
Screenshot - Main example 
Fixes #2584 
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is …
> Revamp EuiSuperDatePicker docs

- CHANGELOG.md
- src/components/suggest/__snapshots__/suggest.test.js.snap
- src/components/suggest/__snapshots__/suggest_input.test.js.snap
- src/components/suggest/suggest_input.js
- src/components/table/mobile/__snapshots__/table_sort_mobile.test.tsx.snap
- src/components/table/mobile/table_sort_mobile.tsx
elastic/kibana#50992 highlights a case where duplicate `id` errors can occur with `EuiPopover`.
This removes the `id` attributes on cases where the value is not necessary and could produce such errors.
> Remove potentially duplicate `EuiPopover` `id` attributes

- CHANGELOG.md
- package.json
This PR does nothing but change the package.json version back to `17.2.0` so that the next release will be `17.2.1` (which I will kickoff on merge). For some reason during the revert hub-bub, it made a release against `17.1.3`. Talking with @chandlerprall and @thompsongl we decided just producing a new release back on cadence (and properly notied things in the CL) was the easiest course of action.
> Update package.josn to match last seq release number

- CHANGELOG.md
- scripts/dtsgenerator.js
Fixes #2671 
This excludes `*.test.tsx?` files when generating _eui.d.ts_. I verified this does not have unintended effects on Kibana by applying the change to eui@17.0.0 (Kibana's version of EUI in master), re-generating its _eui.d.ts_, and testing those type definitions in Kibana.
> exclude *.test.tsx? files from eui.d.ts

- CHANGELOG.md
- src/components/tree_view/__snapshots__/tree_view.test.tsx.snap
- src/components/tree_view/tree_view.tsx
Closes https://github.com/elastic/eui/issues/2699
Fixed `isExpanded` property of nodes of `EuiTreeView`.
> EuiTreeView: fixed isExpanded property of Nodes

- CHANGELOG.md
- src/components/link/_link.scss
Make `EuiLink` button text selectable using CSS. Fixes #1259
Screen recording in Firefox: 
~- [ ] Check against **all themes** for compatability in both light and dark modes~
> Make EuiLink button text selectable

- .github/pull_request_template.md
`compatability` -> `compatibility`
> Fixed typo in github PR template

- CHANGELOG.md
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid_column_resizer.tsx
Fixes #2693 
When the data grid's header row has interactive elements, clicking on a column resize handle would steal focus and put it on the header cell. This change adds a `preventDefault` to the event handler to prevent the focus moving. Tested in Chrome, FF, Safari, and Edge.
~- [ ] Check against **all themes** for compatability in both light and dark modes~
> Don't change cell focus when user resizes a column

- CHANGELOG.md
- src/components/code/_code_block.scss
**Before**
**After**
- ~[ ] Check against **all themes** for compatability in both light and dark modes~
> Fix EuiCodeBlock padding for scrollbar

- src-docs/src/services/string/render_to_html.js
Fixes #2713 and fixes #2711
Two issues I found:
* Any example source that returns a `<Fragment>` (e.g. [list_group.js](https://github.com/elastic/eui/blob/9985aadf7f316f5b7f81873fee5afe6a2f0bc100/src-docs/src/views/list_group/list_group.js#L38-L83) only rendered the first child's html
* The rendered content didn't include the root node's HTML, so **every** `Demo HTML` tab in our docs has been missing it's top-most wrapping element.
Both of these are fixed by wrapping the rendered source component in a `div`.
@thompsongl for code review
@snide / @cchaos to double check the Demo HTML output
~- [ ] Check against **all themes** for compatability in both light and dark modes~
~- [ ] …
> Properly render an example's html output in the  Demo HTML tab

- src-docs/src/views/tables/in_memory/in_memory_selection.js
Fixes the _In-Memory Table - Selection_ demo. `items` is a required field but the demo would set to `undefined` while generating a new list.
> Fix InMemory table selection demo by keeping 'users' defined

- CHANGELOG.md
- src/components/card/_card.scss
Fixes https://github.com/elastic/eui/issues/2740
While working in Canvas, I noticed that the title text for clickable cards was being centered. Seems like a regression, but regardless it's an easy fix.
`textAlign: left`
`textAlign: right`
> Match button text alignment to card textAlign prop

- CHANGELOG.md
- src/components/badge/_badge.scss
Fixes https://github.com/elastic/eui/issues/2744
After the recent badge color update, the hollow badge border became hard to see in dark mode. This PR adds some tint to lighten the border when in dark mode. Similar to the light version, the border remains more subtle than the text.
> Lighten hollow badge border in dark mode

- src-docs/src/views/popover/popover_anchor_position.js
Fixes #2747 
There was an extra word and the copy was a little hard to read, so I re-wrote some example text. I also put it into a variable since this piece of text was re-used four times within this file.
This is a docs-only change, so there is no CHANGELOG.
> Remove extra word in EuiPopover docs (re-write example copy)

- CHANGELOG.md
- src-docs/src/views/color_palette/color_palette.js
- src-docs/src/views/color_palette/color_palette_example.js
- src-docs/src/views/combo_box/colors.js
- src-docs/src/views/combo_box/render_option.js
- src-docs/src/views/guidelines/colors.js
- src/components/avatar/__snapshots__/avatar.test.tsx.snap
- src/components/avatar/avatar.tsx
- src/components/badge/badge.tsx
- src/components/loading/_loading_chart.scss
- src/global_styling/functions/_colors.scss
- src/global_styling/variables/_colors.scss
- src/services/color/eui_palettes.ts
- src/services/color/index.ts
- src/services/color/luminance_and_contrast.ts
- src/services/index.ts
- src/themes/eui-amsterdam/eui_amsterdam_colors_dark.scss
- src/themes/eui/eui_colors_dark.scss
As mentioned in #2455, we can increase the brightness of the color blind palette when using it with text. This creates an automatic palette for this use case.
It also updates the SASS by creating a new SASS map with both `graphic` and `behindText` variants.
In the color guidelines page, the example has been updated to import the palette from JS and allowing the user to toggle between variants.
This palette is now being used directly by EuiBadge, EuiAvatar, EuiLoadingChart, and EuiComboBox's examples.
> Created a `euiPaletteColorBlindBehindText` variant of the color blind palette

- CHANGELOG.md
- src-docs/src/views/form_controls/field_search.js
- src/components/form/field_search/field_search.js
Fixes #2763 
When adding a clear button to `EuiSearchField`, the call signature for `onChange` was modified. This changes the call to always provide the change event to the handler.
This should make it into the Kibana 7.6 branch as a bug fix.
> Fix EuiFieldSearch's onChange call so it is always called with the Event

- CHANGELOG.md
- src/components/table/table_pagination/table_pagination.tsx
Closes https://github.com/elastic/eui/issues/2762
Added `data-test-subj` to the `EuiContextMenuItem` in `EuiTablePagination`
> EuiTablePagination: Adds data-test-subj to the EuiContextMenuItem

- CHANGELOG.md
- src/components/form/form_control_layout/__snapshots__/form_control_layout.test.tsx.snap
- src/components/form/form_control_layout/form_control_layout.test.tsx
- src/components/form/form_control_layout/form_control_layout.tsx
Kibana maps application is using EuiFieldText to show the selected icon. This uses the `prepend` property like this. The problem is that the `className` property is not getting passed to the rendered prepend prop because `EuiFormControlLayout` over rights that prop to a static value. This PR just updates the logic to preserve the original className when provided.
```
<EuiFieldText
onClick={this._togglePopover}
onKeyDown={this._handleKeyboardActivity}
value={value}
compressed
readOnly
fullWidth
prepend={
<SymbolIcon
className="mapIconSelectSymbol__inputButton"
symbolId={value}
fill={isDarkMode ? 'rgb(223, 229, 239)' : 'rgb(52, 55, 65)'}
stroke={isDarkMode ? 'rgb(255, 255, 255)' : 'rgb(0, 0, 0)'}
strokeWidth={'1px'}
/>
}
/>
```
> Retain className for EuiFormControlLayout.prepend nodes

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+eui+deploy-docs.yml
- scripts/deploy/build_docs
- scripts/deploy/deploy_docs
- scripts/deploy/redirect_template.html
Adds scripts and a Jenkins job definition that build and deploy EUI docs to an internal, Bekitzur-managed GCS bucket, soon to replace the work of publishing docs to Github Pages.
See https://eui.elastic.co for an example of the docs published for the most current version of EUI.
N/A; I didn't change any EUI code to do this. 😎
> Publish docs to eui.elastic.co

- .ci/jobs/elastic+eui+deploy-docs.yml
Adds a missing Git branch parameter to the docs build/deploy Jenkins job definition. A small oversight. 😄
> Add branch parameter to docs publish job

- CHANGELOG.md
- src-docs/src/views/icon/icon_types.js
- src/global_styling/mixins/_beta_badge.scss
- src/global_styling/mixins/_button.scss
- src/global_styling/mixins/_form.scss
- src/global_styling/mixins/_panel.scss
- src/global_styling/mixins/_typography.scss
- src/global_styling/variables/_form.scss
There are two kinds of SASS comments.
1. `// This style doesn't get output in the compiled CSS file`
2. `/* This style does */`
When importing the invisibles files (variables, mixins, functions), if those files contain the second comment style, then the comments will be output in the consumer's CSS. This is unnecessary and can cause confusion.
**Kibana example:**
This PR, just changes the comments from the invisibles files to be the non-compiled style.
- ~[ ] Checked for **breaking changes** and labeled …
> [SASS] Change output style comments to non-rendered comments in invisibles files

- CHANGELOG.md
- src-docs/src/views/tables/basic/basic.js
- src-docs/src/views/tables/basic/props_info.js
- src-docs/src/views/tables/selection/selection.js
- src/components/basic_table/__snapshots__/basic_table.test.tsx.snap
- src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
- src/components/basic_table/basic_table.tsx
- src/components/table/_mixins.scss
- src/components/table/table_row_cell.tsx
This PR adds a new prop called `headerRow` to `BasicTable` that lets consumers specify what column is the row header (and thus should have `<th scope=“row”>`).
Doing something like
```
<EuiBasicTable
items={items}
rowHeader="firstName"
columns={columns}
rowProps={getRowProps}
cellProps={getCellProps}
/>
```
results in this markup
Limitations:
This only works with `FieldDataColumn` as it has `field` as a required prop which is what I’m using for doing
`(column as EuiTableFieldDataColumnType<T>).field === headerRow
`
Fixes #2335 #2337 …
> Add headerRow to EuiBasicTable

- CHANGELOG.md
- src/components/context_menu/__snapshots__/context_menu.test.tsx.snap
- src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap
- src/components/context_menu/context_menu.test.tsx
- src/components/context_menu/context_menu.tsx
This change will allow us to render more complex context menu items on Dashboard in Kibana, like `Edit` link below:
- ~~Check against **all themes** for compatibility in both light and dark modes~~
- ~~Checked in **mobile**~~
- ~~Checked in **IE11** and **Firefox**~~
- ~~Props have proper **autodocs**~~
- ~~Added **documentation** examples~~
- ~~Checked for **accessibility** including keyboard-only and screenreader modes~~
- ~~A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked appropriately~~
> Context menu allow jsx

- CHANGELOG.md
- src/components/code/__snapshots__/_code_block.test.js.snap
- src/components/code/__snapshots__/code.test.js.snap
- src/components/code/__snapshots__/code_block.test.js.snap
- src/components/code/_code_block.js
Fixes a bug introduced by #2792 which screws up the contents' vertical alignment in at least Firefox. PR removes a wrapping `div` from the rendering output. Tested changes in Chrome, FF, Safari, Edge, IE11, and Chrome for Android
> Remove extra div wrapping around EuiCode contents

- CONTRIBUTING.md
- wiki/component-design.md
- wiki/component-development.md
Based on our conversations around how to encourage PR handoffs I added a section in the CONTRIBUTING.md file. I also updated the component-design.md file to match the new TS format.
> Editing some markdown files around contributions

- CHANGELOG.md
- package.json
- src-docs/webpack.config.js
Fixes two issues with building EUI on Windows:
* two `scripts` in _package.json_ were setting environment keys without `cross-env` (side note: yarn2 polyfills this behaviour, if we go that route)
* regex for excluding `react-datepicker` package from babel processing was only configured for *nix environment
> Fix dev&docs build issues on Windows

- package.json
- src-docs/src/index.js
- src-docs/src/views/elastic_charts/shared.js
- yarn.lock
Fixes for the docs + IE11:
* `@elastic/charts` fixed their IE11 support in v17.0.3
* `Object.keys` requires a polyfill for `@elastic/charts`
* Made the docs' mention of the `@elastic/charts` version dynamically read from _package.json_
> Fix docs support for IE11

- scripts/babel/proptypes-from-ts-props/index.js
- scripts/babel/proptypes-from-ts-props/index.test.js
- src/components/button/button.tsx
Supersedes #2715 
Added support for `PropsForAnchor` and `PropsForButton` to the typescript->proptype generator. Previously, any component props defined with these utility types were dropped.
Testing this PR: you'll need to delete the `.cache-loader` directory before starting the dev server
> Fix Props tab & PropTypes for components with PropsForAnchor, PropsForButton

- .ci/jobs/elastic+eui+pull-request.yml
Temporarily disabling the new CI multijob that runs tests and builds a docs preview.
> Disable new Jenkins multijob

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+eui+deploy-docs.yml
- .ci/jobs/elastic+eui+pull-request-test.yml
- .ci/jobs/elastic+eui+pull-request.yml
- .ci/jobs/elastic-eui-pull-request.yml
Adds refspec rules to ensure PR jobs can pick up commits in unmerged PR branches. Also reenables the multijob that caused some issues earlier.
> Fix multijob

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+eui+deploy-docs.yml
- .ci/jobs/elastic+eui+pull-request.yml
- .ci/jobs/elastic-eui-pull-request.yml
Adjusts faulty `refspec` config, switches the docs build to use a new GCE service account's credentials.
> Fix pr multijob errors

- src-docs/src/components/guide_section/guide_section.js
- src-docs/src/services/string/render_to_html.js
Fixes #2859 
While we should still seek a build-time solution for the HTML tab, this PR modifies `renderToHtml` to return a render method which is called when switching the tabs. The modified flow means:
* the docs now load ~2 seconds faster (in dev)
* small delay when opening an _Demo HTML_ tab, not noticeable for small components
* more _Demo HTML_ tabs work (e.g. data grid)
My first pass used this new render workflow at docs startup, as the old approach did. However, that added 3-4 seconds to startup time so I opted for this complete refactor.
/cc @markov00 
~- [ ] Added or updated **jest …
> Refactor renderToHtml to use client-side React for rendering

- .ci/jobs/elastic+eui+pull-request.yml
Originally @nyurik [suggested that we run these jobs sequentially](https://github.com/elastic/eui/pull/2852#pullrequestreview-357929984), but in practice the test job is pretty slow (15+ minutes). Parallelizing the jobs will make sure the PR gets a passing or failing build report more quickly. There are many cases where tests could fail but the docs would still build, and it might actually be useful to have a copy of the docs built even if tests fail so the bad code can be tested in a PR-specific sandbox.
So, let's parallelize it.
> Run sub-jobs in parallel as they're mostly unrelated

- .ci/jobs/elastic-eui-pull-request.yml
Disables the old PR test job now that the new one is running.
> Disable legacy PR test job

- src-docs/src/views/datagrid/datagrid_example.js
Fixes 3 typos in URLs crosslinking between data grid docs
> Fix typos in urls in datagrid docs

- CHANGELOG.md
- src/components/title/__snapshots__/title.test.tsx.snap
- src/components/title/title.test.tsx
- src/components/title/title.tsx
Fixes : #2925 
Now euiTitle renders classNames of children too
> Fixes : #2925  Now euiTitle renders classes of children too

- src-docs/src/components/guide_section/guide_section.js
Fixes : #2927
fixed module imports in docs-view
> fixed module imports in docs-view

- CHANGELOG.md
- src/components/code_editor/code_editor.tsx
Allow `EuiCodeEditor` to accept additional props intended for the `react-ace` editor.
> Extend EuiCodeEditor's props with those from react-ace

- CHANGELOG.md
- src/components/flyout/__snapshots__/flyout.test.tsx.snap
- src/services/popover/popover_positioning.ts
Fixes a bug described in https://github.com/elastic/eui/pull/2874#issuecomment-592555721
The context menu's first render pass does not include any content, only the wrapping DOM. With a border, that DOM's height is 2*borderWidth and no border means no height. No height means the content isn't displayable, and the popover service errors out. This PR changes the service to be more lenient in these cases.
> Better guarantee that a popover position can be found

- CHANGELOG.md
- src-docs/src/views/datagrid/datagrid.js
- src/components/datagrid/column_sorting.tsx
- src/components/datagrid/data_grid.test.tsx
- src/components/datagrid/data_grid_schema.tsx
- src/components/datagrid/data_grid_types.ts
> Added isSortable to Datagrid columns

- CHANGELOG.md
- src/components/datagrid/column_sorting.tsx
- src/components/datagrid/column_sorting_draggable.tsx
Fixes #2949 
Fixed Data grid break on invalid schema
> Fixed data grid break on invalid schema

- CHANGELOG.md
- src/components/button/button.tsx
Fixes : #2831
eui button now has a single return statement to rerturn button or anchor tag
> eui button now has a single return statement

- CHANGELOG.md
- src/components/combo_box/combo_box.tsx
- src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
Another bugfix for `v20.0` types. The first was a regression in *combo_box_options_list.tsx*'s `onCreateOption`, which primarily returns `void`. The second is an interaction between TypeScript's management of class components' `defaultProps` and our pattern of exporting a component's props - the prop interface is not the end result.
I have verified that Kibana builds and passes type checks & jest tests, with these changes.
> EuiComboBox type fixes

- CHANGELOG.md
- src/components/code_editor/__snapshots__/code_editor.test.tsx.snap
- src/components/code_editor/code_editor.test.tsx
- src/components/code_editor/code_editor.tsx
Fixes: #2969
added theme prop to documentation, added test for theme
> EuiCodeEditor: added theme prop to documentation, added test for theme

- CHANGELOG.md
- src/components/datagrid/column_sorting.tsx
Fixes: #2975  fixed data grid sort popover
> fixed data grid sort popover

- package.json
Fixing a console warning from a package that recently moved from `devDependencies` to `dependencies`, but I think got accidentally reinserted in a later merge conflict resolution:
> warning package.json: "dependencies" has dependency "@types/react-input-autosize" with range "^2.0.2" that collides with a dependency in "devDependencies" of the same name with version "^2.0.1"
~~- [ ] Checked for **accessibility** including keyboard-only …
> Remove duplicate `@types/react-input-autosize` dep

- scripts/a11y-testing.js
- src-docs/src/views/accordion/accordion_arrow.js
- src-docs/src/views/accordion/accordion_callback.js
- src-docs/src/views/accordion/accordion_form.js
- src-docs/src/views/accordion/accordion_grow.js
- src-docs/src/views/accordion/accordion_multiple.js
- src-docs/src/views/accordion/accordion_open.js
Makes progress on #2679 
Adding an automated assessability test for layout pages.
Guidelines
Layout
> Adding automated accessibility tests for layout pages

- src-docs/src/routes.js
- src-docs/src/views/collapsible_nav/collapsible_nav.tsx
- src-docs/src/views/collapsible_nav/collapsible_nav_example.js
- src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap
- src/components/collapsible_nav/_collapsible_nav.scss
- src/components/collapsible_nav/_index.scss
- src/components/collapsible_nav/_variables.scss
- src/components/collapsible_nav/collapsible_nav.test.tsx
- src/components/collapsible_nav/collapsible_nav.tsx
- src/components/collapsible_nav/index.ts
- src/components/flyout/_flyout.scss
- src/components/index.js
- src/components/index.scss
This is the primary container for the new EuiCollapsibleNav component. It doesn't do much but 
- extend EuiFlyout, 
- push to the left side,
- add `docked` ability, and 
- setup some responsive behavior
- ~[ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked appropriately~ Will be added via the Feature Branch
> [Feature] Added `EuiCollapsibleNav` component

- src-docs/src/views/list_group/list_group_example.js
- src-docs/src/views/list_group/list_group_item_color.tsx
- src/components/accordion/_accordion.scss
- src/components/list_group/__snapshots__/list_group.test.tsx.snap
- src/components/list_group/__snapshots__/list_group_item.test.tsx.snap
- src/components/list_group/_list_group_item.scss
- src/components/list_group/_variables.scss
- src/components/list_group/list_group.test.tsx
- src/components/list_group/list_group.tsx
- src/components/list_group/list_group_item.tsx
- src/components/nav_drawer/__snapshots__/nav_drawer.test.js.snap
which is `ghost`, for use when the list is on a dark background as will be needed like in this screenshot:
Typically you'd only be able to color each list item, but now you color all of them if you're passing items via the `listItems` prop object.
- ~[ ] A [changelog](https://github.com/elastic/eui/blob/master/CHANGELOG.md) entry exists and is marked appropriately~ Will get added via feature branch
> [New Nav Feature] Added `ghost` colored EuiListGroupItem

- scripts/a11y-testing.js
- src-docs/src/views/accessibility/screen_reader.tsx
- src-docs/src/views/context/context.js
- src-docs/src/views/copy/copy.js
- src-docs/src/views/highlight/highlight.js
Makes progress on #2679
Automated Axe testing
**Utilities**
> Automated Axe testing

- src-docs/src/views/collapsible_nav/collapsible_nav_example.js
- src-docs/src/views/collapsible_nav/collapsible_nav_group.tsx
- src/components/collapsible_nav/_index.scss
- src/components/collapsible_nav/_variables.scss
- src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
- src/components/collapsible_nav/collapsible_nav_group/_collapsible_nav_group.scss
- src/components/collapsible_nav/collapsible_nav_group/_index.scss
- src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.test.tsx
- src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.tsx
- src/components/collapsible_nav/collapsible_nav_group/index.ts
- src/components/collapsible_nav/index.ts
- src/components/index.js
- src/components/nav_drawer/__snapshots__/nav_drawer.test.js.snap
- src/global_styling/utility/_animations.scss
- src/global_styling/variables/_states.scss
This is the **accordion** style grouping that will make up these three portions:
_The contents of the group doesn't matter, hence the scribbles_
Instead of trying to create 3 components, I made one that is child-agnostic and can be an accordion via `collapsible=true` or not. Consumers can also add a header with `title` and `iconType`. They can also choose the background color.
Since it does wrap the EuiAccordion when `collapsible=true`, if there's any a11y needs for that specifically, we should do it **in EuiAccordion** and make an issue for that.
The one thing I had to deal with is the focus states of the `dark` background accordion toggle arrow were hard to see. So I **forced** a different focus ring color with overrides.
In dark mode, they all just get different shades of dark that …
> [New Nav Feature] Created `EuiCollapsibleGroup`
