.travis.yml, README.md, package.json, scripts/release.sh, src/components/icon/__snapshots__/icon.test.js.snap, yarn.lock
=> Release automation and a proper CI job

src/components/side_nav/_side_nav.scss
Imperfect solution, becomes challenging with focus states. Chatting this up with @formgeist over slack and he gave the OK, but we'll continue to tweak the spacing on this.
=> Sidenav spacing

docs/index.html, src-docs/src/index.html, src/components/side_nav/_side_nav.scss
Side nav had a small caret alignment issue. Also removed font-awesome and roboto downloads now that both are no longer used.
=> Remove unneaded downloads on index, fix caret in side nav

CONTRIBUTING.md, README.md, wiki/component-development.md, wiki/creating-components-manually.md, wiki/creating-components-yeoman.md, wiki/releasing-versions.md, wiki/testing.md
Replaces https://github.com/elastic/eui/pull/110
=> Add Jest test documentation.

package.json, src/components/form/form_row/form_row.js
This adds a missing dep of `highlight.js` needed to run eui outside kibana such as when using react-storybook.
=> Add missing dep

src-docs/src/views/home/home_view.js
Ordered lists are for things you do in sequence.  Bulleted lists are for things that can be done in any order.
=> Change order lists to unordered lists

CHANGELOG.md, src-docs/src/views/icon/accessibility.js, src-docs/src/views/icon/icon_example.js
=> Update CHANGELOG and docs site after merging inline SVGs PR

CHANGELOG.md, src-docs/src/views/flex/flex_example.js, src-docs/src/views/flex/flex_group_wrap.js, src/components/flex/_flex_group.scss, src/components/flex/flex_group.js
* Loop through FlexGroup gutter size modifiers.
* Add wrap prop to FlexGroup.
Ports https://github.com/elastic/kibana/pull/15009
=> Add support for wrap prop to FlexGroup

src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/services/routes/routes.js, src-docs/src/views/app_view.js
=> Add Patterns section in nav.

src/components/form/form_row/__snapshots__/form_row.test.js.snap, src/components/form/form_row/form_row.test.js, src/components/form/radio/__snapshots__/radio.test.js.snap, src/components/form/radio/__snapshots__/radio_group.test.js.snap, src/components/form/radio/radio.test.js, src/components/form/radio/radio_group.behavior.test.js, src/components/form/radio/radio_group.test.js, src/components/form/range/__snapshots__/range.test.js.snap, src/components/form/range/range.test.js, src/components/form/select/__snapshots__/select.test.js.snap, src/components/form/select/select.test.js
Relates to #177
Adds tests for:
- FormRow
- Radio/RadioGroup
- Range
- Select
=> Form tests - Phase 3

CHANGELOG.md, README.md, package-lock.json, package.json
Also, add Wiki links to the README.
=> Fix typo in 0.0.7 changelog

CHANGELOG.md, src/components/button/_index.scss
Fixes https://github.com/elastic/eui/issues/231
=> Fix button vertical alignment

src/components/flyout/flyout.test.js
Add an empty onclose to the flyout test so it passes the isrequired check.
=> Fix flyout test

CHANGELOG.md, src/components/form/form_control_layout/_form_control_layout.scss
Fixes https://github.com/elastic/eui/issues/221
=> Remove pointer events on form select caret icon

CHANGELOG.md, src/components/button/__snapshots__/button.test.js.snap, src/components/button/button.js, src/components/button/button.test.js, src/components/button/button_empty/__snapshots__/button_empty.test.js.snap, src/components/button/button_empty/button_empty.js, src/components/button/button_empty/button_empty.test.js, src/components/button/button_icon/__snapshots__/button_icon.test.js.snap, src/components/button/button_icon/button_icon.js, src/components/button/button_icon/button_icon.test.js, src/components/link/__snapshots__/link.test.js.snap, src/components/link/link.js, src/services/index.js, src/services/prop_types/check_href_and_onclick.js, src/services/prop_types/index.js, src/services/security/get_secure_rel_for_target.js, src/services/security/get_secure_rel_for_target.test.js, src/services/security/index.js
Fixes https://github.com/elastic/eui/issues/318.
Compelled by https://github.com/elastic/kibana/pull/15949
CC @nyurik no need to review if you're busy.
=> Add rel='noopener noreferrer' to all links with target='_blank' for security

.travis.yml, package.json, scripts/test-travis.sh
Following advice from https://github.com/facebook/jest/issues/1524#issuecomment-260246008.
=> Configure Travis to run Jest tests with --runInBand flag, to avoid timeouts

CHANGELOG.md, package.json
=>  Move react-color from devDependencies to dependencies.

README.md, wiki/consuming.md
This can be seen in the browser at https://github.com/cjcenizal/eui/blob/plugin-usage/wiki/consuming.md
=> Add docs on consuming EUI.

CHANGELOG.md, src/components/context_menu/context_menu.js
=> Fix EuiContextMenu bug in which the menu items were continuously re-rendered

package.json
This script will primarily be used by Jenkins for testing the eui project. By adding it here it also gives humans an easy way to test in an identical way to how Jenkins is testing. Another advantage of having this in the repo is that upgrading node versions can also be tested as part of the pull request workflow!
=> Add script for testing project inside docker

package.json, yarn.lock
Fixes vulnerability https://nvd.nist.gov/vuln/detail/CVE-2017-18214
=> Upgrade moment to 2.19.3.

src/components/basic_table/__snapshots__/in_memory_table.test.js.snap, src/components/basic_table/in_memory_table.js
Analogue to https://github.com/elastic/eui/pull/449. Looks like some snapshots were affected but I think they may be fixes to errors that existed earlier.
=> Refactor EuiInMemoryTable for a more transparent data flow.

src-docs/src/views/guidelines/button.js, src-docs/src/views/guidelines/modals.js, src-docs/src/views/guidelines/toasts.js, src/components/flex/flex_item.js
* Uses react router for linking
* Fixes prop usage on buttons
* Adds figure to accepted flexItem components
=> Guideline link and error fixes

src-docs/src/views/guidelines/button.js, src-docs/src/views/guidelines/modals.js
Fixed wording for add and remove buttons
=> fixed text for Add and Remove

src-docs/src/routes.js, src-docs/src/views/guidelines/modals.js, src-docs/src/views/guidelines/writing.js, src-docs/src/views/home/home_view.js, src/components/modal/_modal.scss
=> Modals guidelines

src/components/portal/portal.js
=> Add warning in EuiPortal about inability to render immediately.

CHANGELOG.md, src/components/button/_button.scss, src/components/form/select/select.js
* Hollow focus state of disabled buttons, fixes #560 
* Allow select to pass any node as option, fixes #346
=> Misc. bugs and cleanup

src-docs/src/views/call_out/call_out_example.js
This PR addresses issue issue 570:  [[EuiCallout] [Docs]: Consistent spelling and more examples/guidelines](https://github.com/elastic/eui/issues/570)
=> Add guidelines and fix inconsistencies in Callout

CHANGELOG.md, src/components/side_nav/side_nav_item.js
Fixes https://github.com/elastic/eui/pull/655#issuecomment-380613718
=> Fix side nav in docs

CHANGELOG.md, src-docs/src/views/tables/in_memory/in_memory_search_callback.js, src-docs/src/views/tables/in_memory/in_memory_search_callback_section.js, src/components/basic_table/in_memory_table.js
Fixes https://github.com/elastic/eui/issues/467
=> Reset EuiInMemoryTable pagination state when a search has been executed.

src/components/form/described_form_group/__snapshots__/described_form_group.test.js.snap, src/components/form/described_form_group/described_form_group.js
Fixing title/description area width.
=> Fix EuiDescribedFormGroup width

CHANGELOG.md, src-docs/src/views/button/button_empty.js, src/components/button/button_empty/button_empty.js
=> add isLoading prop to EuiButtonEmpty

src-docs/src/views/combo_box/colors.js, src-docs/src/views/combo_box/containers.js, src-docs/src/views/combo_box/groups.js, src-docs/src/views/combo_box/render_option.js
fixes https://github.com/elastic/eui/issues/797, https://github.com/elastic/eui/issues/796, and https://github.com/elastic/eui/issues/795
Several of the EuiComboBox examples were broken with custom options. This PR fixes those
=> fix EuiComboBox examples with custom options

src/components/accordion/__snapshots__/accordion.test.js.snap
Forgot to apply a snapshot update to https://github.com/elastic/eui/pull/816
Sorry, my local linting is screwy.
=> Snapshot for accordion

CHANGELOG.md, src/components/form/form_label/_form_label.scss
Fixes https://github.com/elastic/eui/issues/823
cc @w33ble
=> Only show cursor pointer if for attribute is set on label

src-docs/src/views/tool_tip/tool_tip_example.js, src/components/tool_tip/tool_tip.js, yarn.lock
This will address pain points like https://github.com/elastic/eui/issues/839 in the future. This PR also updates `yarn.lock`.
=> Add guidance to EuiToolTip docs on how to use it with a custom component

wiki/component-design.md
=> add naming conventions for boolean and event handler props

src-docs/src/views/guidelines/button.js
=> Fixed column not showing up on large screens

src/components/basic_table/basic_table.js, src/components/search_bar/query/execute_ast.js
The goal of this PR is to reduce indirection, increase explicitness, and clarify intentions. I'll comment on the diff to explain some of the problems I encountered. These changes are a precursor to addressing https://github.com/elastic/eui/issues/902 and https://github.com/elastic/eui/issues/425.
=> Refactor EuiInMemoryTable's cell rendering methods and execute_ast

CHANGELOG.md, src/components/xy_chart/_legend.scss
#309 Altered the medium and large title sizing globally. This comments that out.
=> Quick fix to title sizing

CHANGELOG.md, src/components/page/_page.scss, src/components/page/page_content/_page_content.scss, src/components/page/page_header/_page_header.scss
Until I can get it right with the current Kibana sidebar
=> Temporarily removing page responsive styles

package-lock.json, package.json, yarn.lock
`serve` dependency was unused, removing. Updated yarn and package lock files.
=> removed 'serve' dependency

scripts/jest/setup/polyfills.js, src/components/mutation_observer/mutation_observer.test.js
Patches jsdom to automatically trigger the MutationObserver polyfill.
=> Enhance the test's polyfilled MutationObserver

src-docs/src/views/form_controls/form_controls_example.js
Fixes #1047 
- corrected docs props for `EuiNumberField`
- corrected docs props for `EuiRadioGroup`
=> Correct props documentation for EuiNumberField and EuiRadioGroup

CHANGELOG.md
This adds an entry for the 3.7.0 changelog for #1120
=> Changelog entry for #1120

wiki/react-router.md
I just implemented this in a feature and found out the guidance was slightly off.
=> Fix guidance on integration with react router.

.github/pull_request_template.md
@cchaos and I were talking through this the other week. I put up our most common gotchas. People can always remove a line if it isn't appropriate. I know this won't fit everything, but should fit most PRs.
=> Github PR template

.github/pull_request_template.md
Changed the wording of this to be more a checklist of what actions you took, rather than actions you need to take.
Checklist isn't applicable to this PR.
=> Clear up the PR template wording

src-docs/src/views/home/home_view.js
Add a new sketch kit zip for download that's up to date as of 4.0
=> Update sketch library links

CHANGELOG.md, package.json, src/components/avatar/avatar.js, yarn.lock
This PR has two purposes:
1. Updates some dependencies so that EUI works in Mojave.
2. Adds a few exports to components so that it works properly with framer.
=> Some fixes for framer and mojave

src-docs/src/views/guidelines/writing.js
This PR updates the writing guidelines. It includes new content for prioritizing pertinent information in messages.
Questions for @gchaps and @karenzone:
- There is already a section about using punctuation judiciously, but I'm wondering if we should include a bit about using parenthesis sparingly?
- We need to document somewhere how to create messages that are seen on the command line. They are currently squished together and somewhat unintuitive. TBD on this as I have yet to start my scrub on Cloud API messages.
=> [Guidelines] New content for prioritizing message information

src/components/context_menu/index.d.ts
https://github.com/elastic/eui/blob/6063ed3bc50dd5be01e9de50fae47ebfbd37fb2a/src/components/context_menu/context_menu.js#L69
=> title prop is optional

src/components/form/form_row/index.d.ts
Adds the remaining props to EuiFormRow's Props type.
=> Add props to EuiFormRowProps

src-docs/src/views/tables/in_memory/props_info.js, src/components/basic_table/__snapshots__/in_memory_table.test.js.snap, src/components/basic_table/in_memory_table.js, src/components/basic_table/in_memory_table.test.js
Resolves #1318
I'm not sure how to get the docs to auto-updated based on the props so any help there would be appreciated!
=> Add executeQueryOptions as a prop to EuiInMemoryTable

README.md, wiki/consuming.md
Fixes https://github.com/elastic/eui/issues/1506 from a docs sense
Just some quick docs so that people better understand how to install EUI if starting in a blank project.
=> Docs to illustrate dependencies for installation

CHANGELOG.md, src/components/form/switch/__snapshots__/switch.test.js.snap, src/components/form/switch/switch.js, src/components/form/switch/switch.test.js
Fixes https://github.com/elastic/eui/issues/1518
=> Fix bug which prevented EuiSwitch with generated ID from having its label read by VoiceOver

src/components/form/field_search/field_search.js
Closes #1548 by adding usage documentation on `EuiSearchField`'s `onSearch` prop.
=> Update documentation for EuiFieldSearch's onSearch prop

src-docs/src/views/guidelines/button.js
Edits to text for spelling and usage.
=> Edits to text in guidelines/button.js

src-docs/src/views/guidelines/colors.js
Edits to text for spelling (plus one comment re: proper word usage)
=> Edits to text in guidelines/colors.js

src-docs/src/views/home/home_view.js
Several minor edits for word usage and punctuation.
=> Minor edits to text in home/home_view.js

src-docs/src/views/guidelines/colors.js
Fixes https://github.com/elastic/eui/pull/1593/files#r260508354
Be more careful in review. Bad dave.
=> Fix errant comment in sass docs

src-docs/src/views/guidelines/modals.js
Couple of spelling corrections
=> Minor edits to text in guidelines/modals.js

src-docs/src/views/accordion/accordion_example.js
Handful of edits for spelling & wording.
=> Edits to text in accordion/accordion_example.js

src-docs/src/views/guidelines/writing.js
Handful of edits to text for spelling & usage
=> Edits to text in guidelines/writing.js

src-docs/src/views/flyout/flyout_example.js, src-docs/src/views/flyout/flyout_max_width.js
Minor edits to text in flyout docs for spelling, punctuation, capitalization, etc.
=> Edits to text in flyout docs

src-docs/src/views/flex/flex_grow_zero.js
=> Edits to text in flex/flex_grow_zero.js

src-docs/src/views/flex/flex_example.js
Minor edit to text for spelling
=> Edits to text in flex/flex_example.js

src-docs/src/views/header/header_example.js
=> Minor edit to text in header/header_example.js

src-docs/src/views/nav_drawer/nav_drawer_example.js
One spelling correction in text
=> Edit to text in nav_drawer/nav_drawer_example.js

src-docs/src/views/modal/modal_example.js
Deleted extraneous words from text
=> Edits to text in modal/modal_example.js

src-docs/src/views/page/page_example.js
Minor edits to text for spelling/punctuation.
=> Edits to text in page/page_example.js

src-docs/src/views/panel/panel_example.js
Minor edits to text for wording.
=> Edits to text in panel/panel_example.js

src-docs/src/views/popover/popover_example.js
Couple of minor edits to text for spelling/punctuation.
=> Edits to text in popover/popover_example.js

src-docs/src/views/button/button_example.js
Edits to text for spelling/punctuation.
=> Edits to text in button/button_example.js

src/components/button/button_group/button_group.js
Edits to text for spelling/punctuation.
=> Edits to button_group/button_group.js

src-docs/src/views/facet/facet_example.js
Deleted extraneous word in text.
=> Edit to text in facet/facet_example.js

src-docs/src/views/link/link_example.js
One spelling correction in text
=> Edit to text in link/link_example.js

src/components/side_nav/side_nav.js
=> Edits to side_nav/side_nav.js

src-docs/src/views/steps/steps_example.js
=> Edit to text in steps/steps_example.js

src/components/steps/steps.js
=> Edit to text in steps/steps.js

src-docs/src/views/steps/steps_complex.js
Inserted a missing space in text.
=> Edit to text in steps/steps_complex.js

src-docs/src/views/avatar/avatar.js
Corrected spellings of the Teenage Mutant Ninja Turtles. :smiley: 
However, if these are the correct names/spellings for the cats shown on the [Avatar page](https://elastic.github.io/eui/#/display/avatar), then we can ignore my edits.
=> Edited TMNT spellings in avatar/avatar.js =)

src-docs/src/views/avatar/avatar_initials.js
Edited for co
I assume we're referring to Leonardo, the Teenage Mutant Ninja Turtle here. If so, "Leonardo" is the correct spelling. :laughing: 
However, if we're just referring to one of the cat(s) in the icons on the [Avatar page](https://elastic.github.io/eui/#/display/avatar), then this spelling is fine. :smile_cat:
=> Edited "Leonardo" spelling in avatar_initials.js

src-docs/src/views/card/card_footer.js
=> Edits to text in card/card_footer.js

src-docs/src/views/card/card_example.js
Handful of spelling/punctuation/wording corrections.
=> Edits to text in card/card_example.js

src-docs/src/views/description_list/description_list_example.js
=> Edits to text in description_list_example

src-docs/src/views/image/image_example.js
=> Edit to text in image/image_example.js

src-docs/src/views/list_group/list_group_example.js
Couple of spelling/punctuation fixes.
=> Edits to text in list_group/list_group_example.js

src-docs/src/views/progress/progress_example.js
=> Edits to text in progress/progress_example.js

src-docs/src/views/tables/tables_example.js
=> Edit to tables/tables_example.js

src-docs/src/views/tables/basic/basic_section.js
Edits for spelling, wording, and punctuation
=> Edits to tables/basic/basic_section.js

src-docs/src/views/tables/actions/actions_section.js
=> Edit to text in tables/actions/actions_section.js

src-docs/src/views/tables/mobile/mobile_section.js
=> Edits to text in tables/mobile/mobile_section.js

src-docs/src/views/text/text_example.js
=> Edits to text in text/text_example.js

src-docs/src/views/toast/toast_example.js
Couple of spelling corrections
=> Edits to text in toast/toast_example.js

src-docs/src/views/tool_tip/tool_tip_example.js
Couple of edits for punctuation/spelling
=> Edits to text in tool_tip/tool_tip_example.js

src-docs/src/views/date_picker/date_picker_example.js
Couple of edits for punctuation/spelling
=> Edits to text in date_picker_example.js

src-docs/src/views/expression/expression_example.js
=> Edits to text in expression/expression_example.js

src-docs/src/views/search_bar/search_bar_example.js
Edits for spelling and word usage.
=> Edits to text in search_bar_example.js

src-docs/src/views/color_palette/color_palette_example.js
=> Edits to text in color_palette_example.js

src-docs/src/views/utility_classes/utility_classes.js
=> Edits to text in utility_classes.js

src-docs/src/views/color_palette/color_palette_custom.js
=> Edits to text in color_palette_custom.js

src-docs/src/views/resize_observer/resize_observer_example.js
=> Edits to text in resize_observer.js

src/components/avatar/avatar.tsx
One minor wording change in props table
=> Edits to text in avatar/avatar.tsx

src/components/copy/copy.js
Edits for spelling/capitalization.
=> Edits to text in copy/copy.js

src-docs/src/views/title/title_example.js
=> Edits to text in title/title_example.js

yarn.lock
Updates `diff` and `is-my-json-valid` deps to latest versions.
=> Update diff and is-my-json-valid version

CHANGELOG.md, src/components/badge/badge.tsx, src/components/badge/index.ts, src/components/copy/copy.tsx, src/components/tool_tip/index.ts
Definition updates and type exports necessary for Kibana upgrade.
=> EuiBadge and EuiCopy TS fixes

.npmignore
Cleans up unnecessary files from EUI's packed tarball distributed through npm.
npm notice === Tarball Details ===
npm notice name:          @elastic/eui
npm notice version:       12.2.0
npm notice filename:      elastic-eui-12.2.0.tgz
npm notice package size:  3.3 MB
npm notice unpacked size: 13.2 MB
npm notice shasum:        e5729cc91aac60108b3a18d71590b32741fe0ef4
npm notice integrity:     sha512-fCsAcBGkO3hBZ[...]81ow4EZAs3hhw==
npm notice total files:   3664
CHANGELOG.md			es				scripts
CONTRIBUTING.md			eui.d.ts			src
FAQ.md				lib				tsconfig-builttypes.json
LICENSE				package.json			tsconfig.json
README.md			packages			yarn-error.log
npm notice === Tarball Details ===
npm notice name:          @elastic/eui
npm notice version:       12.2.0
npm notice filename: …
=> Clean up packaged npm distributable

FAQ.md, README.md
Talking with the team over the last month, we wanted to tone down our scary language on usage. In practice, we _have_ welcomed PRs from outside Elastic, we _have_ maintained some manner of generic usage and we _do_ engage on community issues. I've left in language that makes it clear that we still maintain our roadmap based on internal priorities and concerns, but I think over the past six months we've seen that community contributions have been awesome and we should encourage them similar to how we do in our other repos.
I also took a moment to update the FAQ with some items as well.
=> Wiki and docs updates

CONTRIBUTING.md, wiki/creating-icons.md
Adds wiki page for creating icons.
Marking this as Draft for the moment, comments welcome, need to add some images.
It's a big brain dump and could benefit from some screenshots and tidying up.
=> Add 'Creating icons' section to the wiki

src/components/color_picker/_color_picker.scss, src/components/form/range/range.js, src/components/popover/_index.scss, src/components/popover/_input_popover.scss, src/components/popover/_popover.scss, src/components/popover/index.js, src/components/popover/input_popover.js, src/components/popover/popover.js
Beta/In-progress components for attaching popovers to inputs. Styling concerns are mostly resolved. Focus and key interaction are unsettled matters. Don't _use_ this in `master` just yet.
=> [BETA] `EuiInputPopover`

CHANGELOG.md, src/components/form/text_area/index.d.ts
This PR contains missing TS defs for EuiTextArea.
=> Add types for EuiTextArea

packages/react-datepicker.js, packages/react-datepicker/yarn.lock
=> Update react-datepicker deps

CHANGELOG.md, src-docs/src/views/accordion/accordion_example.js
Fix #2281 Incorrect code example for Multiple accordions
=> Fix incorrect code example for Multiple accordions

src-docs/src/views/image/image_example.js, src-docs/src/views/image/image_zoom.js
Summarize your PR. If it includes design elements include a screenshot or gif.
=> Adding snippets to EuiImage

src-docs/src/views/suggest/hashtag_popover.js
Use callback parameter to calculate state when update is about to be performed.
=> Fixed potentially inconsistent state update

src-docs/src/views/combo_box/colors.js
color property was duplicated.
=> Removed overwritten property

yarn.lock
=> Misc. package version updates

src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/_accordion.scss, src/components/accordion/accordion.tsx
Matches the timing and curve of the animation. Relies on the selectors already in place.
=> Clean up accordion styling

CHANGELOG.md, package.json, yarn.lock
React 16.11.x was complaining about `Grid`, inside `List`, inside `react-virtualized`, inside `@elastic/eui`.
=> Upgrade `react-virtualized` to 9.21.2

src-docs/src/views/home/home_view.js
fixes https://github.com/elastic/eui/issues/2562
This PR fixes the EUI tables broken link in the home page
Fix EUI tables broken link
=> Fix broken link

src-docs/src/views/icon/icon_example.js
Was reading docs and found duplicate, and I don't like duplicate stuff.
=> this wasn't that usable

src-docs/src/views/guidelines/forms.js
This PR provides edits to the Form guidelines documentation.
=> [DOCS] Edits to Form guidelines

.ci/jobs/elastic+eui+deploy-docs.yml
Forgot an important bit on PR #2801!
=> Add scm section to docs build

.ci/jobs/defaults.yml, .ci/jobs/elastic+eui+deploy-docs.yml, .ci/jobs/elastic+eui+pull-request-test.yml, .ci/jobs/elastic+eui+pull-request.yml, .ci/jobs/elastic-eui-pull-request.yml, scripts/deploy/deploy_docs
Updates jobs and the underlying `deploy_docs` script to post a preview link to docs changes on EUI pull requests.
I'll also be using this PR to test the script locally to verify it's working. 😉 
N/A
=> Add a preview URL to PRs with docs changes

.ci/jobs/elastic+eui+pull-request-deploy-docs.yml, .ci/jobs/elastic+eui+pull-request-test.yml, .ci/jobs/elastic+eui+pull-request.yml
Still fixing up the new Jenkins jobs so everything works correctly. 😭
=> Fix refspecs again, split deploy-docs into two jobs for PRs vs ad-hoc

.ci/jobs/defaults.yml, .ci/jobs/elastic+eui+deploy-docs.yml, .ci/jobs/elastic+eui+pull-request-deploy-docs.yml, .ci/jobs/elastic-eui-pull-request.yml
I have a good feeling about this one.
=> Fix PR multijob errors

.ci/jobs/elastic+eui+pull-request-deploy-docs.yml, .ci/jobs/elastic+eui+pull-request-test.yml
=> Assign pull refspecs to PR jobs

.ci/jobs/elastic+eui+pull-request-deploy-docs.yml, .ci/jobs/elastic+eui+pull-request.yml, scripts/deploy/deploy_docs
I moved some job parameters around and forgot to make sure the PR docs job has a pull request ID available to it.
=> Pass pull request ID on to docs build PR job

CONTRIBUTING.md
<h1>Description</h1>
1. It appears that the word <strong>icons</strong> should use the genetive case. Hence, noun has been changed.
2. <strong>different</strong>seems to be the wrong part of the speech for this context. Hence, it has been changed to <strong>differently</strong>.
3. <strong>short summary</strong> creates a tautology.
4. The phrase <strong>have an effect on</strong> may be unnecessarily wordy. I have replaced the corresponding noun with a verb.
=> Grammatical fixes in CONTRIBUTING.md file.

src-docs/src/components/guide_section/guide_section.js
I missed this one as part of @cchaos's removal of theme details from redux.
=> Removed old theme prop GuideSection used

CHANGELOG.md, src/components/highlight/__snapshots__/highlight.test.tsx.snap, src/components/highlight/highlight.test.tsx
added highlightAll test for highlight component
=> added highlightAll test for highlight component

scripts/a11y-testing.js, src-docs/src/views/form_layouts/described_form_group.js, src-docs/src/views/form_layouts/full_width.js, src-docs/src/views/range/dual_range.js, src-docs/src/views/range/input.js, src-docs/src/views/range/input_only.js, src-docs/src/views/range/levels.js, src-docs/src/views/range/range.js, src-docs/src/views/range/states.js, src-docs/src/views/range/ticks.js
Makes progress on #2679
<hr/>
Forms :
=> Performed axe-testing for form_layouts and range

src-docs/src/views/button/button_group.js
Fixes: #3050
now every group has distinct state
=> Fixed toggling in docs-section

scripts/a11y-testing.js, src-docs/src/views/facet/facet_layout.js
=> Fixed  a11y testing for EuiFacet

src-docs/src/views/home/home_view.js
=> added correct aria for Version

src-docs/src/views/datagrid/datagrid_schema_example.js
A minor typo fix in Datagrid docs
=> Typo fix in EuiDataGrid docs

wiki/creating-icons.md
=> Adding a line for updating the test in the Icon creation markdown file

src-docs/src/views/accordion/accordion_grow.js
#3150
Converted accordian_grow.js class component into function component
=> Convert accordian_grow example to function component

src-docs/src/views/flyout/flyout.js, src-docs/src/views/flyout/flyout_banner.js, src-docs/src/views/flyout/flyout_complicated.js, src-docs/src/views/flyout/flyout_example.js, src-docs/src/views/flyout/flyout_large.js, src-docs/src/views/flyout/flyout_max_width.js, src-docs/src/views/flyout/flyout_small.js
#3150
Converted flyout examples class component into function component
=> [Docs] Convert flyout example to function component

src-docs/src/views/nav_drawer/nav_drawer_example.js
Added a reference note to `EuiListGroupItem` for the details about the `listItems` object for `EuiNavDrawerGroup`.
Issue: #3139
=> [Docs] Updated the note about the listItems props for EuiNavDrawerGroup

src-docs/src/views/button/button_ghost.js, src-docs/src/views/button/button_toggle.js, src-docs/src/views/card/card_checkable.js, src-docs/src/views/card/card_selectable.js, src-docs/src/views/code_editor/code_editor.js, src-docs/src/views/code_editor/custom_mode.js, src-docs/src/views/code_editor/read_only.js
Makes progress on: #3150
~- [ ] Checked for **breaking changes** and labeled appropriately`
=> [Docs] Converted some examples to functional components

src-docs/src/views/header/header.js, src-docs/src/views/header/header_alert.js, src-docs/src/views/header/header_links.js
#3150
Converted bottom_bar.js class component into function component
=> [Docs]Convert Header examples into function component

src-docs/src/views/highlight_and_mark/highlight.js
Converted highlight.js 's class based component to functional component using hooks.
Continues the progress on #3150
=> [DOCS] Changed highlight / mark docs to use functional components

src-docs/src/views/modal/confirm_modal.js, src-docs/src/views/modal/modal.js, src-docs/src/views/modal/modal_example.js, src-docs/src/views/modal/overflow_test.js
#3150
Converted Modal examples class component into function component
=> [Docs] Converted Modal examples into function component

src-docs/src/views/stat/stat_combos.js, src-docs/src/views/stat/stat_loading.js, src-docs/src/views/steps/status.js
=> [DOCS] Changed `EuiStat` examples to functional components

src-docs/src/views/toggle/toggle.js
Converted toggle.js's class based component to functional Component.
Progress on #3150
=> [DOCS] Convert EuiToggle docs to Functional Component

src-docs/src/views/pagination/centered_pagination.js, src-docs/src/views/pagination/compressed.js, src-docs/src/views/pagination/few_pages.js, src-docs/src/views/pagination/many_pages.js
Makes progress on #3150.
Converted some pagination class based components to functional components.
=> [DOCS] Converted some pagination class based components into functional components

src-docs/src/views/call_out/call_out_example.js
This PR adds snippets to the callout docs.
=> [Docs] Add snippets to EuiCallOut

src-docs/src/views/side_nav/side_nav.js
Conversion of class based component to functional component.
Progress on #3150
=> [DOCS] Converted SideNav component from class based to functional based.

src-docs/src/views/elastic_charts/category_chart.js, src-docs/src/views/elastic_charts/shared.js, src-docs/src/views/elastic_charts/sparklines.js, src-docs/src/views/elastic_charts/theming_categorical.js, src-docs/src/views/elastic_charts/time_chart.js
Converted some EuiCharts docs to use Functional Components
=> [DOCS] Converted Charts examples to use Functional Components

src-docs/src/views/range/dual_range.js, src-docs/src/views/range/input.js, src-docs/src/views/range/input_only.js, src-docs/src/views/range/range.js, src-docs/src/views/range/states.js, src-docs/src/views/range/ticks.js, src-docs/src/views/resize_observer/resize_observer.js, src-docs/src/views/search_bar/controlled_search_bar.js, src-docs/src/views/search_bar/search_bar.js, src-docs/src/views/search_bar/search_bar_filters.js
Makes progress on #3150.
Turned Range family to functional components
=> [DOCS] Changed ranged component docs to functional components

src-docs/src/views/tree_view/tree_view_example.js
Added snippet to EuiTreeView
~- [ ] Added or updated **jest tests**`
~- [ ] Checked for **breaking changes** and labeled appropriately`
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~
=> Added snippet to EuiTreeView

src-docs/src/views/nav_drawer/nav_drawer.js
#3150
Converted nav drawer example class component into function component
=> [Docs] Converted nav drawer example into function component

src-docs/src/views/super_select/super_select.js, src-docs/src/views/super_select/super_select_basic.js, src-docs/src/views/super_select/super_select_complex.js
=> [Docs] Converted EuiSuperSelect examples to functional component

src-docs/src/views/suggest/global_filter_options.js, src-docs/src/views/suggest/hashtag_popover.js, src-docs/src/views/suggest/saved_queries.js, src-docs/src/views/suggest/suggest.js
=> [DOCS]  Convert EuiSuggest examples to functional component

src-docs/src/views/expression/expression.js, src-docs/src/views/filter_group/filter_group.js, src-docs/src/views/filter_group/filter_group_multi.js, src-docs/src/views/filter_group/filter_group_simple.js
Converted EuiFilter and EuiExpression examples to use Functional Components
=> [DOCS] Converted EuiFilter and EuiExpression examples to use Functional Components

src-docs/src/views/popover/popover.js, src-docs/src/views/popover/popover_anchor_position.js, src-docs/src/views/popover/popover_block.js, src-docs/src/views/popover/popover_container.js, src-docs/src/views/popover/popover_fixed.js, src-docs/src/views/popover/popover_htmlelement_anchor.js, src-docs/src/views/popover/popover_panel_class_name.js, src-docs/src/views/popover/popover_with_title.js, src-docs/src/views/popover/popover_with_title_padding.js, src-docs/src/views/popover/trap_focus.js
#3150
Converted popover example class component into function component
=> [DOCS] Converted EuiPopover examples to function component

src-docs/src/views/focus_trap/focus_trap.js
Issue #3150 
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~
=> [DOCS] Convert EuiFocusTrap example to functional component

src-docs/src/views/facet/facet_layout.js, src-docs/src/views/pagination/customizable_pagination.js
#3150
Converted facet and pagination(custom pagination) example class component into function component
=> [Docs] Converted facet and pagination examples into function component

src-docs/src/views/focus_trap/focus_trap.js, src-docs/src/views/form_compressed/complex_example.js, src-docs/src/views/form_compressed/form_compressed.js, src-docs/src/views/form_compressed/form_horizontal.js
Makes Progress on #3150 
Converted compressed forms to Functional Component
~~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~~
=> [Docs] Converted compressed forms examples to functional component 

src-docs/src/views/combo_box/async.js, src-docs/src/views/combo_box/colors.js, src-docs/src/views/combo_box/combo_box.js, src-docs/src/views/combo_box/combo_box_delimiter.js, src-docs/src/views/combo_box/containers.js, src-docs/src/views/combo_box/custom_options_only.js, src-docs/src/views/combo_box/disabled.js, src-docs/src/views/combo_box/disallow_custom_options.js, src-docs/src/views/combo_box/groups.js, src-docs/src/views/combo_box/render_option.js, src-docs/src/views/combo_box/single_selection.js, src-docs/src/views/combo_box/startingWith.js, src-docs/src/views/combo_box/virtualized.js
=> [DOCS] EuiComboBox to functional

src-docs/src/views/html_id_generator/bothPrefixSuffix.js, src-docs/src/views/html_id_generator/html_id_generator.js, src-docs/src/views/html_id_generator/html_id_generator_prefix.js, src-docs/src/views/html_id_generator/html_id_generator_suffix.js
#3150
Converted HTML id generator example class component into function component
=> [Docs]Converted html id generator examples class component into function component

src-docs/src/views/text/text_example.js
This PR adds snippets to the **EuiText** docs.
=> [Docs] Add snippets to EuiText

wiki/creating-components-manually.md
This PR improves the **Adding snippets** section of the Wiki
=> [Wiki] Improve "Adding snippets" section

src-docs/src/views/toast/info.js, src-docs/src/views/toast/toast_example.js, src-docs/src/views/toast/toast_list.js
Added snippets to EuiToast
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~
=> [DOCS] Added snippets to EuiToast

scripts/test-staged.js
Fixes: #2826
~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~
=> Added support for the`test-staged` script to search renamed files

src-docs/src/views/form_validation/validation.js
=> [DOCS] Converted Form Validation example from class component to functional component

src-docs/src/views/window_event/modal_example_container.js, src-docs/src/views/window_event/mouse_position.js, src-docs/src/views/window_event/window_event_conflict.js
=> [DOCS] Converted Window events to functional

CHANGELOG.md, src/services/popover/popover_positioning.ts, test/README.md, wiki/component-design.md, wiki/component-development.md, wiki/consuming.md, wiki/creating-components-yeoman.md, wiki/creating-icons.md, wiki/react-router.md
Fixed typos in the documentation.
=> fixed 30+ typos

src-docs/src/views/suggest/global_filter_add.js, src-docs/src/views/suggest/global_filter_form.js, src-docs/src/views/suggest/global_filter_item.js, src-docs/src/views/super_date_picker/super_date_picker.js, src-docs/src/views/super_date_picker/super_date_picker_config.js, src-docs/src/views/super_date_picker/super_date_picker_custom_quick_select.js
Converted EuiSuperSatePicker and EuiSuggest examples to functional components
~~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~~
=> [Docs] Converted EuiSuperDatePicker and EuiSuggest examples to functional components

src-docs/src/views/progress/progress_fixed.js, src-docs/src/views/progress/progress_value.js
Continuation of progress on #3150
=> [DOCS]Converted progress class group into functional group

src-docs/src/views/nav_drawer/nav_drawer_example.js
Updated Snippets as per new documentation guidelines.
=> [DOCS] Updated EuiNavDrawer Snippets.

src-docs/src/views/health/health_example.js
=> [DOCS] Added Snippets to EuiHealth.

src-docs/src/views/tables/actions/actions.js, src-docs/src/views/tables/auto/auto.js, src-docs/src/views/tables/expanding_rows/expanding_rows.js, src-docs/src/views/tables/footer/footer.js, src-docs/src/views/tables/in_memory/in_memory_search.js, src-docs/src/views/tables/in_memory/in_memory_search_callback.js, src-docs/src/views/tables/in_memory/in_memory_selection.js, src-docs/src/views/tables/mobile/mobile.js, src-docs/src/views/tables/paginated/paginated.js, src-docs/src/views/tables/selection/selection.js, src-docs/src/views/tables/sorting/sorting.js
Converted EuiTable examples to functional components
- custom table example is not converted
=> [Docs] Converted EuiBasicTable EuiInMemoryTable examples to functional components

src-docs/src/views/tabs/controlled.js, src-docs/src/views/tabs/tabbed_content.js, src-docs/src/views/tabs/tabs.js, src-docs/src/views/tabs/tabs_condensed.js, src-docs/src/views/toast/toast_list.js
Converted EuiTabs and EuiToastList examples to functional components
=> [Docs] Converted EuiTabs and EuiToastList examples to functional components

src-docs/src/views/pagination/pagination_example.js
Updated Pagination Snippets based on new guidelines.
<strike> [ ] Check against **all themes** for compatibility in both light and dark modes</strike>
<strike> [ ] Checked in **mobile**</strike>
<strike> [ ] Checked in **IE11** and **Firefox**</strike>
<strike> [ ] Props have proper **autodocs**</strike>
<strike> [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)** examples</strike>
<strike> [ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**</strike>
<strike> [ ] Checked for **breaking changes** and labeled appropriately</strike>
<strike> [ ] Checked for **accessibility** including keyboard-only and screenreader modes</strike>
<strike> [ ] A …
=> [DOCS] Updated EuiPagination Snippets.

src-docs/src/views/responsive/responsive_example.js
Added Snippets to EuiResponsive.
=> [DOCS] Added Snippets to EuiResponsive.

src-docs/src/views/badge/badge_example.js, src-docs/src/views/button/button_example.js, src-docs/src/views/card/card_example.js, src-docs/src/views/filter_group/filter_group_example.js, src-docs/src/views/flyout/flyout_example.js, src-docs/src/views/key_pad_menu/key_pad_menu_example.js, src-docs/src/views/panel/panel_example.js, src-docs/src/views/range/range_example.js, src-docs/src/views/selectable/selectable_example.js, src-docs/src/views/suggest/suggest_example.js, src-docs/src/views/tabs/tabs_example.js
Updated Older Snippets as per new guidelines.
=> [DOCS] Updated Older Snippets as per new guidelines.

src-docs/src/views/toggle/toggle_example.js
=> [DOCS]Added Snippets to EuiToggle

src-docs/src/views/form_controls/form_controls_example.js
Added Snippets to EuiFormControl.
=> [DOCS] Added Snippets to EuiFormControl

src-docs/src/views/button/button_group.js, src-docs/src/views/form_controls/file_picker.js
=> [DOCS] Converted Some class components to functional components.

src-docs/src/views/flyout/flyout_example.js
This PR updates the **EuiFlyout** snippets.
=> [Docs] Update EuiFlyout snippets 

wiki/component-development.md
Added mention of `yarn build` to the component testing section
=> Update the component development / testing documentation

src-docs/src/views/combo_box/combo_box_example.js
This PR adds snippets to the **EuiComboBox** docs.
=> [Docs] Add snippets to EuiComboBox

src-docs/src/views/copy/copy_example.js
This PR updates the **EuiCopy** snippet to match our Adding snippets documentation.
=> [Docs] Update EuiCopy snippets 

src-docs/src/views/beacon/beacon_example.js
This PR adds snippets to the **EuiBeacon** docs.
=> [Docs] Add snippet to EuiBeacon

src-docs/src/views/icon/icon_example.js
fixed EuiToken Snippet
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry …
=> [DOCS] fixed EuiToken Snippet

wiki/testing.md
I wasn't sure where to find this information, so thought it made sense to add here. I don't have much experience with writing or running tests, so I'm not 100% confident that my writing is accurate. Could use some :eyes:
=> Include info on how to update snapshots

.ci/jobs/elastic+eui+npm-publish.yml
I had to move some `nvm` bits around in order to get it to initialize the CI job correctly.
n/a
=> Fix broken nvm initialization

scripts/release.js
=> Ignore branch check in CI

src-docs/src/views/button/button_example.js, src-docs/src/views/form_layouts/form_layouts_example.js
Updated the Link because of some past changes in the repo
=> Updated link

CHANGELOG.md, src-docs/src/views/form_controls/file_picker.js, src-docs/src/views/form_controls/form_controls_example.js
Changed from `const FilePicker` to `default` 
Closes #3686 
@cchaos
=> [DOCS] Fixed export for `FilePicker`

src-docs/src/services/playground/_playground_knobs.scss, src-docs/src/services/playground/knobs.js, src-docs/src/services/playground/props.js, src-docs/src/views/call_out/call_out_example.js, src-docs/src/views/call_out/playground.js
=> [Playground] EuiCallout

src-docs/src/services/playground/props.js, src-docs/src/views/card/card_example.js, src-docs/src/views/card/playground.js
=> [Playground] EuiCard

generator-eui/app/documentation.js
=> fix spelling in generator-eui/app/documentation.js

src-docs/src/views/code/code_example.js, src-docs/src/views/code/playground.js
=> [Playground] EuiCode, EuiCodeBlock

src-docs/src/views/progress/playground.js, src-docs/src/views/progress/progress_example.js
=> [Playground] EuiProgress

src-docs/src/views/text/playground.js, src-docs/src/views/text/text_example.js
makes progress on #3057
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry …
=> [Playground] EuiText

src-docs/src/views/tool_tip/playground.js, src-docs/src/views/tool_tip/tool_tip_example.js
=> [Playground] EuiToolTip

src-docs/src/views/comment/comment_example.js, src-docs/src/views/comment/playground.js
=> [Playground] EuiComment

.github/pull_request_template.md
Updated the pull request template to include Chrome, Safari, Edge, and FF
=> Updated PR template to include all supported browsers

src-docs/src/views/link/link_example.js, src-docs/src/views/link/playground.js
=> [Playground] EuiLink

src-docs/src/views/key_pad_menu/key_pad_menu_example.js, src-docs/src/views/key_pad_menu/playground.js
=> [Playground] EuiKeyPad

src-docs/src/views/facet/facet_example.js, src-docs/src/views/facet/playground.js
=> [Playground] EuiFacet

yarn.lock
=> Bump `elliptic`

src-docs/src/views/markdown_editor/markdown_editor_errors.js, src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_footer.tsx
Fixes for the 2 issues in https://github.com/elastic/eui/pull/3522#issuecomment-672328839
=> Fixes some ARIA issues in EuiMarkdownEditor

src-docs/src/views/beacon/beacon_example.js, src-docs/src/views/beacon/playground.js
=> [Playground] EuiBeacon

src-docs/src/views/highlight_and_mark/highlight_and_mark_example.js, src-docs/src/views/highlight_and_mark/playground.js
=> [Playground] EuiHighlight , EuiMark

src-docs/src/views/toggle/playground.js, src-docs/src/views/toggle/toggle_example.js
=> [Playground] EuiToggle

src-docs/src/views/form_layouts/guidelines.js
Changed `charaters` to `characters` in the form guidelines.
=> [Docs] Updated form guidelines with friendly spellcheck

src-docs/src/views/tabs/playground.js, src-docs/src/views/tabs/tabs_example.js
=> [Playground] EuiTab

README.md
Closes #4017 by adding more direct language about `peerDependencies` requirements
=> Update readme with peerDependencies language

packages/react-datepicker.js, packages/react-datepicker/package.json, packages/react-datepicker/yarn.lock, yarn.lock
Affecting both `/yarn.lock` and `react-datepicker/yarn.lock`:
* `node-forge`
* `bl`
* `http-proxy`
* `node-sass`
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/docu …
=> Bump misc. deps

CONTRIBUTING.md
Spotted a broken link while reading [this doc](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md).
Not applicable.
=> Fix broken link CONTRIBUTING.md

packages/react-datepicker/yarn.lock, yarn.lock
=> [deps] Bump ini

src-docs/src/views/markdown_editor/mardown_format_example.js
=> [Docs] Type fix in markdown format documentation

CHANGELOG.md, src/components/form/form_control_layout/_form_control_layout.scss, src/components/health/health.tsx
This reverts commit 75ca1a927db9934351ebd67b97403bca9912f119 from #4410. See discussion in #4431. @miukimiu will follow up with a better resolutioon.
=> Revert "[EuiFormControlLayout] Fixed heights of append/prepend (#4410)"

package.json, src-docs/src/views/elastic_charts/time_chart.js, src/themes/charts/themes.ts, yarn.lock
This PR fixes #4308.
- Merged the new version of the Elastic Charts `24.5.1`
- Added the new theme object `crosshair.crossLine`. 
- Added a horizontal crosshair to `/elastic-charts/time-series` example.
I notice an issue with the crosshair. When grid lines are visible the crosshair hides behind those lines. I opened a PR in **Elastic Charts** repo to address this issue: https://github.com/elastic/elastic-charts/pull/1021. 
As we can see, the crosshair was too light and almost invisible.
https://user-images.githubusercontent.com/2750668/107390270-6fc76a80-6aef-11eb-986a-e203b97b5ccb.mov
Now, the crosshair looks better. You can also notice that there's an issue that I mentioned above (the crosshair hides behind the grid lines). This must be addressed in a future PR. …
=> [Elastic charts] Improve crosshair styles

src-docs/src/views/date_picker/custom_input.js, src-docs/src/views/date_picker/min_max.js, src-docs/src/views/date_picker/range.js, src-docs/src/views/date_picker/utc.js
Issue #3150 
Converted some date picker examples from class component to functional component
~~- [ ] A …
=> [DOCS] Converted Date Picker examples to functional component 

FAQ.md
This PR Fixes #4519 
Fixed a broken link in FAQ File
~~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is …
=> [Docs] Fixed invalid link

.github/workflows/changelog.yml
Small change to make the action trigger on label changes.
=> Add more rules for changelog action

.github/workflows/stale_issues.yml
Turns on the stale issue / PR action. We'll want to validate these and update them before turning it on. The action can be bypassed indefinitely by adding `skip-stale-check` as a label onto the issue or PR.
=> Turn on stale issue/pr action

yarn.lock
Manually bump `caniuse-lite` to rid us of console messages.
=> Bump `caniuse-lite`

package.json, yarn.lock
Minor dependency bumps: `lodash` & `url-parse`
=> Bump lodash, url-parse

CHANGELOG.md, src/components/form/file_picker/file_picker.tsx
=> [EuiFilePicker] Added i18n for Remove text

package.json, packages/react-datepicker.js, packages/react-datepicker/docs-site/bundle.js, packages/react-datepicker/yarn.lock, src/components/date_picker/__snapshots__/date_picker.test.tsx.snap, yarn.lock
Bump several package versions. See commit messages for details.
A test snapshot changed for date_picker (3c2ebb1). I ran the ES docs server locally and manually tested using the EuiDatePicker component, it seems to be working fine.
=> Bump dependencies

src/components/flyout/flyout.testenv.tsx
Respect `hideCloseButton` in the `testenv` mock.
=> [EuiFlyout] `testenv` `hideCloseButton`

package.json, yarn.lock
Upgrades `url-parse` to `v1.5.3`
=> [Deps] Bump `url-parse`

src-docs/src/services/routing/routing.ts
=> [Docs] Fixed exit full screen link back

wiki/automated-accessibility-testing.md, wiki/component-design.md, wiki/component-development.md, wiki/consuming.md, wiki/documentation-guidelines.md, wiki/react-router.md
A few super small nits I caught while perusing the wiki dev docs, aka me personifying programming humor memes:
N/A, internal/dev documentation only
=> Minor wiki docs fixes

wiki/component-development.md
Was doing a read through of the wiki docs as part of my ramp up today, and had the unique opportunity of QA testing one of Greg's branches in my local Kibana alongside an Enterprise Search feature branch. I had some suggestions based on that experience, as well as some generation organization suggestions for the unit testing section.
I recommend following along by commit as I left some context in the commit messages, but I'll also leave code comments highlighting any particularly spicy changes
N/A, internal/dev documentation only
=> Wiki documentation suggestions for Component development > Tests

wiki/releasing-versions.md
Updated _releasing-versions.md_ with more information on:
* configuring npm tokens
* potential github token interaction
* tagging the github release w/changelog
=> Updating releasing-versions.md

src-docs/src/views/selectable/data.ts, src-docs/src/views/selectable/selectable_popover.js
This reverts commit 2fbc966f66aefab9a33cb5ce13d06f6faf0930a9, which was supposed to be reverted before #5117 merged 🤦 
=> Revert temporary docs change

CONTRIBUTING.md, wiki/writing-styles-with-emotion.md
Just getting this doc started in `master` so we can add to it from whatever PR we need. Intentionally slim right now.
=> [Docs] Writing styles with Emotion

src/components/date_picker/super_date_picker/date_popover/relative_tab.tsx, src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.tsx, src/components/date_picker/super_date_picker/quick_select_popover/quick_select.tsx, src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx, src/components/date_picker/super_date_picker/quick_select_popover/refresh_interval.tsx
Parent PR:
- https://github.com/elastic/eui/pull/5195
QA screencaps below in code comments.
Changelog will be added in a single entry in #5195.
=> [EuiSuperDatePicker] Fix multiple IDs regenerating on rerender

wiki/releasing-versions.md
I just ran through backporting/releasing a 38.0.1 patch and ran into 1 or 2 local CLI errors while following the steps in our wiki. As such I'm opening a PR with some suggested fixes!
N/A, internal documentation only
=> [Docs] Backporting documentation improvements

src-docs/src/views/code/virtualized.js
This reverts commit 2b9eee0bf2dacfac7a3c5ba240ba1daad98fb6af.
Should have been done in #5207
=> [Docs] Revert temporary change

yarn.lock
=> [Deps] `ansi-regex` to v5.0.1

src/components/context_menu/context_menu_panel.spec.tsx
I've been seeing a decent amount of failing CI due to `EuiContextMenuPanel` failures, I'm going to run Jenkins on this PR 3x to see if we still get failures with the increased wait time.
=> [Cypress] Attempt to harden flaking EuiContextMenuPanel specs

generator-eui/changelog/templates/changelog.md, scripts/update-changelog.js
I forgot the part where I need to delete upcoming changelogs in https://github.com/elastic/eui/pull/5727 🤦‍♀️ 
1. Open `package.json`, change version to `52.0.1` (or anything above current version)
1. In the `upcoming_changelogs/` folder, create a new `5555.md` (or any other name) file (can be empty)
1. In your CLI, run `node -e "require('./scripts/update-changelog').updateChangelog('test')"`
=> [Tech debt] Delete upcoming changelogs on release

wiki/documentation-guidelines.md, wiki/releasing-versions.md
@chandlerprall noticed last week that I missed a few wiki docs during #5727 🙈 
N/A, wiki doc changes only
=> [Wiki] Update old references to manual CHANGELOG.md updates

.ci/jobs/elastic+eui+pull-request-test.yml
Add artifact archiving publisher for PR test job so the cypress screenshots show up.
Related: https://github.com/elastic/eui/pull/5805
=> [ci] add an artifact archiving publisher for pr job

wiki/writing-styles-with-emotion.md
Specifically adding guidance around passing props even to child style objects or, when necessary, using the `[class*=""]` selector.
=> [Emotion Wiki] Adding sections about child element styles

wiki/writing-styles-with-emotion.md
When we have child elements I think it's too much for each of them to have its own theme function. So I'm proposing all of the elements to live in the same function to simplify.
=> [Emotion Wiki] Proposing new child element styles

wiki/writing-styles-with-emotion.md
Adds some wiki documentation for mixin/util best practices based on our discussion at our sync today.
N/A, wiki only
=> [Emotion] Add wiki documentation for mixin best practices

src/components/context_menu/context_menu_panel.spec.tsx
Recent CI failures:
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/7151/
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/7153/
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/7155/
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/7174/
This isn't failing for me whatsoever locally so I can't really repro reliably 😞
=> Attempt to squash flaky Cypress tests

scripts/babel/react-docgen-typescript.js
Previously, importing types & interfaces and re-exporting them would cause webpack to throw warnings when building our docs because the transpiled JS code wouldn't have those values, e.g.
**place/example.ts**
```typescript
export interface Example {};
```
**place/index.ts**
```typescript
export { Example } from './example';
```
Babel only knows the content of the file it's currently working on, so the above transpiles to:
**place/example.js**
```javascript
```
**place/index.js**
```javascript
export { Example } from './example';
```
triggering webpack's warning when trying to import the now non-existent Example. To fix this, we modified the doc site's typescript->docgen loader to remove type & interface exports. This logic asked TS for the names of all such values and if it found a …
=> [Docs] fix documentation build

wiki/upgrading-kibana.md
Thanks to @dominiqueclarke for getting me pointed in the right direction for how to debug synthetics failures!
N/A, internal wiki only
=> Update Kibana upgrade wiki with more tips + section for synthetics E2E tests

src-docs/src/index.js
=> [Docs] Remove `console.log`

src-docs/src/views/provider/provider_example.js
=> [Docs] fixed EuiThemeProvider links in EuiProvider documentation

wiki/upgrading-kibana.md
Adds a few more tips around debugging FTR tests, a tip on updating failing baseline screenshot FTRT tests, and a link to OSQuery's Cypress tests
N/A, wiki only
=> Add more helpful tips to the Upgrading Kibana wiki

.github/workflows/add_issues_to_project.yml, .github/workflows/moves_assigned_card.yml
This PR adds some automation to the EUI Team project.
- Auto add issues to the EUI Team Project
- Moves cards to 'In Progress' when an issue is assigned
=> Adds actions for EUI Team project.

.github/workflows/add_pr_to_project.yml
Fixes the release_version for actions 🤦🏼‍♂️
=> Fixes some broken actions

renovate.json
=> Update RenovateBot owners of elastic/charts

cypress/support/index.d.ts, src/components/breadcrumbs/breadcrumbs.a11y.tsx, src/components/card/card.a11y.tsx, src/components/control_bar/control_bar.a11y.tsx, src/components/drag_and_drop/drag_and_drop.a11y.tsx
* Adding a11y spec for Control Bar.
* Updating checkAxe TS definition.
* Adding a11y and keyboard spec to Drag and Drop.
* Adding a11y and keyboard spec for Card.
Tracking these a11y test specs in https://github.com/elastic/eui/issues/6300.
=> Adding a11y tests for Control Bar, Drag and Drop, Card.

.github/workflows/add_issues_to_project.yml
I’m removing PRs from the actions workflow while I get the errors sorted out.
=> Removes PRs from the actions workflow

src/components/error_boundary/error_boundary.a11y.tsx, src/components/expression/expression.a11y.tsx, src/components/filter_group/filter_group.a11y.tsx
* Added a11y and keyboard specs for EuiErrorBoundary.
* Added a11y and keyboard specs to EuiExpression.
* Added a11y and keyboard specs for EuiFilterGroup.
=> Added Cypress a11y tests for EuiErrorBoundary, EuiExpression, and EuiFilterGroup.

wiki/releasing-versions.md
I've missed a key step in the release instructions a couple of times, so added it to the documentation. Also added some clarifying information for creating a release from a tagged commit.
=> Added NPM login and release steps to releasing-versions.md.

src-docs/src/views/side_nav/side_nav.js, src-docs/src/views/side_nav/side_nav_heading.js
This pull request fixes two broken links within the documentation.
=> fix: broken link within EuiSideNav documentation

catalog-info.yaml
Fixing a bug introduced by some improper formatting in the `catalog-info.yml` and a team name change.
* Updated team name in catalog file
* Ran the updated catalog structure through a validation tool
=> Fixing a config bug in catalog-info.

.buildkite/pipeline.yml
Boosting the agent memory for our first Buildkite job. This should help the job run successfully.
=> Bumping memory for Buildkite agent.

.ci/jobs/defaults.yml
Node 18 requires a newer OS. This PR ensures we set that OS level explicitly once it's merged into `main`.
=> Adjusting CI for Node 18.

scripts/deploy/deploy_docs
🤞 This _should_ fix https://github.com/elastic/eui/issues/6924
- In CI deploy-docs step, check to confirm that the `echo`'d current release output is as expected:
N/A, dev only
=> [CI] Remove non-working bash script / `npx semver`

scripts/deploy/deploy_docs
This Buildkite PR will test that our Buildkite pipeline is deploying docs on pull requests correctly.
All QA will be done in the Buildkite CI environment and manual click-through.
=> [INFRA] Adding Docker image name to deploy docs comment.

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_body_virtualized.test.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/footer/data_grid_footer_row.test.tsx, src/components/datagrid/body/header/data_grid_header_cell.test.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/utils/scrolling.test.tsx
This PR converts `EuiDataGrid` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert EuiDataGrid unit tests using enzyme render to RTL

src/components/color_picker/__snapshots__/color_picker.test.tsx.snap, src/components/color_picker/__snapshots__/color_picker_swatch.test.tsx.snap, src/components/color_picker/__snapshots__/hue.test.tsx.snap, src/components/color_picker/__snapshots__/saturation.test.tsx.snap, src/components/color_picker/color_palette_display/__snapshots__/color_palette_display.test.tsx.snap, src/components/color_picker/color_palette_display/color_palette_display.test.tsx, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/color_picker/color_palette_picker/color_palette_picker.test.tsx, src/components/color_picker/color_picker.test.tsx, src/components/color_picker/color_picker_swatch.test.tsx, src/components/color_picker/color_stops/__snapshots__/color_stop_thumb.test.tsx.snap, src/components/color_picker/color_stops/__snapshots__/color_stops.test.tsx.snap, src/components/color_picker/color_stops/color_stop_thumb.test.tsx, src/components/color_picker/color_stops/color_stops.test.tsx, src/components/color_picker/hue.test.tsx, src/components/color_picker/saturation.test.tsx, src/components/color_picker/saturation.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/range_highlight.tsx
This PR converts `EuiColorPicker` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert EuiColorPicker unit tests using enzyme render to RTL

.buildkite/scripts/pipeline_test.sh, scripts/deploy/deploy_docs
This PR simplifies the Docker `run` command in our Buildkite test and docs deploy scripts.
QA will be done using Buildkite test logs to make sure everything passes as expected.
=> [CHORE] Improve Docker run scripts for Buildkite

wiki/contributing-to-eui/running-eui-locally.md
We had a few devs run into this issue last week in the EUI channel, and figured we should document fixes/workarounds more easily for folks since arm64 machines are starting to become more common.  
N/A, internal/documentation only
=> [Wiki] Document puppeteer error on M1/M2 machines

scripts/deploy/deploy_docs
closes https://github.com/elastic/eui/issues/7088
I got annoyed enough at various developer friction points in my day-to-day to _bash_ this one out during my support week :trollface: 
- https://docs.github.com/en/rest/issues/comments
- https://jqlang.github.io/jq/manual/
N/A, infra only
=> [CI] Delete previous staging link comment(s) when posting a staging link

wiki/eui-team-processes/releasing-versions.md
This PR updates the [Release process](https://github.com/elastic/eui/blob/main/wiki/eui-team-processes/releasing-versions.md) wiki doc to remove references to GitHub pages and accurately describe the release docs build process.
- Browser QA
- Docs site QA
=> Updating docs link and description in release process doc.

wiki/eui-team-processes/upgrading-kibana.md
[Preview](https://github.com/elastic/eui/blob/e3fde5d4a85ef9dff4ff26dd6d6917c477cf4c32/wiki/eui-team-processes/upgrading-kibana.md)
N/A, docs only
=> [wiki] Update upgrading Kibana doc with a FAQ for Kibana teams

wiki/contributing-to-eui/README.md
Reworded our contributing readme with a "Who can contribute?" section.
=> Update contributing README

src/components/expression/expression.stories.tsx, src/components/facet/facet_button.stories.tsx, src/components/facet/facet_group.stories.tsx, src/components/filter_group/filter_button.stories.tsx, src/components/filter_group/filter_group.stories.tsx, src/components/flex/flex_grid.stories.tsx, src/components/flex/flex_group.stories.tsx, src/components/flex/flex_item.stories.tsx, src/components/flyout/flyout.stories.tsx, src/components/flyout/flyout_body.stories.tsx, src/components/flyout/flyout_footer.stories.tsx, src/components/flyout/flyout_header.stories.tsx, src/components/flyout/flyout_resizable.stories.tsx, src/components/focus_trap/focus_trap.stories.tsx
Skips form components, which likely need to be their own PR 😨
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euiexpression--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euifacetbutton--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euifacetgroup--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euifilterbutton--regular
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euifiltergroup--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euiflexgrid--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euiflexgroup--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euiflexitem--playground
- https://eui.elastic.co/pr_7476/storybook/?path=/story/euiflyout--playground
- …
=> [Storybook] Add remaining stories for components starting with E-F

src-docs/src/views/expression/expression.js
Closes #7308
This PR updates the primary EUIExpression example to use encourage better practices in Kibana. The linked issue above includes useful illustrations that show the before and after.
Primarily, it encourages a pattern of using EUISelectable directly in a popover to alleviate required clicks to make a change to an expression.
By using the prior solution as our primary example, we inadvertently propagated the pattern throughout Kibana.
- Browser QA
- Docs site QA
=> [Docs] Update EUIExpression example

.buildkite/scripts/pipelines/pipeline_prune_staging_docs.sh
For the working build run, see https://buildkite.com/elastic/eui-prune-staging-docs/builds/14
Feedback on my very hacky/noob-y bash is welcome!
N/A - infra only
=> [buildkite] Delete all but most recent 50 PR staging subdirs

.github/pull_request_template.md
See below. Now that we have Loki working locally, let's go ahead and add a step to check/update VRT screenshots to our PR template
- Browser QA
- Docs site QA
=> Add VRT step to PR template checklist

wiki/eui-team-processes/releasing-versions.md, wiki/eui-team-processes/upgrading-kibana.md
This PR adds small updates to the release docs `releasing-versions.md` and `upgrading-kibana.md`.
- updates old links
- adds information about how to run Kibana CI
=> [Docs] Update release docs

catalog-info.yaml
I believe I missed some key metadata in [my last PR](https://github.com/elastic/eui/pull/7914).
=> Added missing details to new analytics pipeline

wiki/contributing-to-eui/testing/testing-in-kibana.md
This PR updates the `testing-in-kibana.md` wiki docs to add information on how to deploy a local EUI package in Kibana.
=> [Wiki] Add docs on how to deploy a local EUI package in Kibana

catalog-info.yaml
=> chore: remove EUI from `ci-systems` system

packages/website/docs/components/utilities/beacon.mdx
Added the Beacon page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Beacon page

packages/website/docs/components/utilities/i18n.mdx
Added the i18n page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > i18n page

packages/website/docs/components/utilities/copy.mdx
Added the Copy page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Copy page

packages/website/docs/components/layout/header.mdx, packages/website/docs/components/utilities/portal.mdx
Added the Portal page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Portal page

.github/ISSUE_TEMPLATE/beta.md
I created some issues to track the beta functionalities (see: #1469).
On this PR I'm adding a simple beta template to help with creating such issues.
=> chore: add beta issue template

packages/eslint-plugin/changelogs/upcoming/8524.md
Forgot to add the changelog on https://github.com/elastic/eui/pull/8524
=> chore(eslint-plugin): add changelog

wiki/eui-team-processes/betas.md
Added a doc for "Betas" to our wiki
=> chore(wiki): add a doc for "Betas" to our wiki

packages/docusaurus-theme/src/components/navbar_item/index.tsx, packages/docusaurus-theme/src/theme/DocSidebarItem/Category/index.tsx, packages/docusaurus-theme/src/theme/Navbar/MobileSidebar/Layout/index.tsx, packages/docusaurus-theme/src/theme/Root.styles.ts
Follow-up to #8547 
Resolves #8575 
This fixes an issue in the sidebar where font sizes were inconsistent.
| --- | --- |
| ![Capture-2025-04-10-192810-before](https://github.com/user-attachments/assets/b10c08d7-6db9-4502-94ec-96e8aca4423c) | ![Capture-2025-04-10-192748-after](https://github.com/user-attachments/assets/f98a6d92-1f99-4182-b37c-9c9bf3efce35) |
=> fix(website): sidebar font sizes

packages/eui/changelogs/upcoming/8648.md, packages/website/src/components/homepage/header/index.tsx
I added an animation that was planned some time ago [when the home page was designed](https://www.figma.com/design/g5Vk0k2DgeQPCPBoWmun2U/EUI--docs?node-id=986-32373&t=phWUlSZhBOXfNugH-4), but a little simplified. The animation looks like this:
- Browser QA
- Docs site QA
=> Animation on a new site homepage

wiki/contributing-to-eui/documenting/writing-documentation.md
I had to figure out the right way to do this in MDX/Docusaurus, so I thought it would be worth noting it here for other folks.
=> Added Images to writing-documentation.md

packages/website/docs/components/display/icons/index.mdx
Closes https://github.com/elastic/eui/issues/8711
=> docs: fix typo in eui token docs

wiki/contributing-to-eui/testing/testing-in-kibana.md
This PR updates the wiki on how to test eui packages locally in Kibana to align it with the current process.
=> [Wiki] Update local testing documentation

packages/website/docs/components/display/health.mdx
Matching values with the ones displayed in the https://eui.elastic.co/docs/patterns/severity/
- Browser QA
- Docs site QA
=> Updating severity palette examples

.github/ISSUE_TEMPLATE/02-feature_request.md
Just a small change to an issue template to fix a typo.
Not applicable.
No impact to users.
- Browser QA
- Docs site QA
=> docs: fix small typo
