elastic/eui

CHANGELOG.md, src/components/datagrid/column_sorting.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid_schema.tsx
The new `isSortable` prop added to data grid schemas was made required, an accidental breaking change. This PR makes it optional.
I'm planning on backporting this fix to eui@21 after merge
=> Make isSortable optional on datagrid schemas

src-docs/src/views/tables/in_memory/in_memory_selection.js
Fixes  #3026
So, it all started from [this commit](https://github.com/elastic/eui/commit/22c983bb5ce868e944a78fa21eb66764162bbcdd#diff-032471f91c9a03ca48b34d7f1a79dae1R98). Later, the TypeError got patched in [this commit](https://github.com/elastic/eui/commit/63739a6f4562b2a5a57ef8a112dcaddc67681326#diff-032471f91c9a03ca48b34d7f1a79dae1R100) but despite an error no longer being thrown, this was not the desired behaviour. @pugnascotia could you please have a look?
The control columns were added to `EuiDataGrid`, this doc page demos `EuiInMemoryTable`.
=> #3026 [Docs] TypeError in In-Memory Table - Selection

wiki/consuming.md
Simply that. And a link to the NPM.
=> Adding a links to Next and Gatsby starters in CONSUMING.md

CONTRIBUTING.md
This is a docs only change that covers how we plan to handle the assignment of issues in the repo. Given the EUI's popularity in the community over the last six months we wanted to make sure we had clear guidelines over how to handle community contributions and how we define our roadmap and perform review.
=> Contributing guidelines around PR assignment

CHANGELOG.md, src/components/flyout/_flyout_body.scss
This PR aligns the content of a callout with the content of EuiFlyoutHeader 
Before
After
=> Fix padding in EuiCallout when used as banner for EuiFlyout

CONTRIBUTING.md
Changed the contributing.md file to suggest only having three active PRs up at any one time. It's become difficult for the team to review so many early stage PRs in tandem. 
cc @anishagg17 who this policy is lovingly directed towards 😸. We appreciate the enthusiasm, but a narrower focus will help get your current PRs in quicker.
This can be a go-forward event. No need to close PRs for ones that are currently active.
=> Proccess - Limit active PRs per contributor to three when possible

CHANGELOG.md, src-docs/src/views/tabs/controlled.js, src-docs/src/views/tabs/tabbed_content.js, src-docs/src/views/tabs/tabs.js, src-docs/src/views/tabs/tabs_condensed.js, src-docs/src/views/tabs/tabs_example.js, src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, src/components/tabs/tabbed_content/tabbed_content.test.tsx, src/components/tabs/tabbed_content/tabbed_content.tsx
`EuiTab` already supports this, so now users of `EuiTabbedContent` will also be able to provide a node for the `name` prop.
=> Add support for node name prop to EuiTabbedContent, to bring it up to par with EuiTab

src-docs/src/components/guide_page/guide_page.js
Fixes: #696
"ghost" Show Component Code button is removed, on first tab "Show component code" but is active
=> removed ghost "Show component code" button

CHANGELOG.md, src/components/icon/icon.tsx
Fixes #3113 
Reproduced the issue in the Kibana branch as described. Copied code to EUI's docs to boil it down to a basic use case, and found:
* start with `empty` , which triggers a dynamic fetch for the empty icon
* get the url for the correct icon & set the icon's type
* `img` element created, network request made
* dynamic fetch returns, setting empty back to the icon's internal state
* icon re-renders with empty icon 😱
After making this change in EUI & confirming it fixed my simplified test case, I built EUI with the change and dropped it into the above Kibana branch, confirming it resolves the issue there too.
~- [ ] Props have …
=> Fix race condition in EuiIcon's internal setState

src-docs/src/components/guide_page/guide_page.js, src-docs/src/services/index.js, src-docs/src/services/routing/routing.js, src-docs/src/views/app_view.js, wiki/react-router.md
Follow up to #3078, where it was discovered that we have some good ideas in our wiki that we weren't taking advantage of.
Following the thread from https://github.com/elastic/eui/blob/master/wiki/react-router.md#1-conversion-function-recommended and shamelessly copy-pasting from the 3.x section, we can use react-router `Link` behavior without the a11y concerns of nested `a` and `button`.
~- [ ] Checked for **accessibility** including keyboard-only …
=> Docs routing service for react-router `Link` behavior

CHANGELOG.md, src/components/button/button_empty/_button_empty.scss
This PR adds a darker background on **focus state** for `EuiButtonEmpty` when the `color` type is `text`. 
The same background color is used in other components like:
-  `EuiButtonIcon`
- `EuiButtonToggle`
I think it makes sense that all the buttons that allow the color type text to have the same background color on focus state.
As we can see, the previous focus state background color wouldn't work in situations like this:
With this new color the contrast decreases a little bit but it still ok.
- ~~[ ] Checked in **mobile**~~
- ~~[ ] Props have proper **autodocs**~~
- ~~[ ] Added **documentation** examples~~
- ~~[ ] Added or updated **jest tests**~~
- ~~[ ] Checked for **breaking changes** and labeled appropriately~~
=> Improving EuiButtonEmpty focus state for color type text

CHANGELOG.md, src/components/pagination/_pagination.scss, src/components/pagination/pagination.tsx
Closes #3148
This PR fixes the vertical alignment of the `of` word when the `EuiPagination` is `compressed`.  
- ~~[ ] Checked in **mobile**~~
- ~~[ ] Props have proper **autodocs**~~
- ~~[ ] Added **documentation** examples~~
- ~~[ ] Added or updated **jest tests**~~
- ~~[ ] Checked for **breaking changes** and labeled appropriately~~
- ~~[ ] Checked for **accessibility** including keyboard-only and screenreader modes~~
=> Fixed EuiPagination vertical alignment of text when is compressed

CHANGELOG.md, src/components/date_picker/super_date_picker/date_popover/date_popover_content.js
Possible Fix for: #3131 
The "End date" popover shows the same relative time as the "Start date" popover. This can be solved by converting the value on relative tab to absolute string using toAbsoluteString function
Before:
After:
=> Fixed EuiSuperDatePicker "End date" popover shows wrong relative time

src-docs/src/views/tables/basic/props_info.js
<h1>Description</h1>
Fixes #62
=> Added textOnly prop info in the table-docs.

package.json, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap, src/components/selectable/selectable_list/_selectable_list.scss, src/components/selectable/selectable_list/_selectable_list_item.scss, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_list/selectable_list_item.tsx, src/components/selectable/selectable_search/selectable_search.tsx, yarn.lock
Sorry for conflating two things in this PR - I thought all the changes were going to be smaller but as they started to pile on, I thought it'd be better to cut this PR and open a feature branch for future work.
This PR accomplishes two things:
1. Swaps [`react-virtualized`](https://github.com/bvaughn/react-virtualized) for [`react-window`](https://github.com/bvaughn/react-window)+[`react-virtualized-auto-sizer`](https://github.com/bvaughn/react-virtualized-auto-sizer)
- `virtualized` makes some bad a11y assumptions that `react-window` doesn't make. They're both made by the same person actually and `react-window` is his slimmer replacement for `virtualized`.
- I used `react-virtualized-auto-sizer` because after this effort, only one other component uses `react-virtualized` which would …
=> [Feature / Selectable A11y] Improve basic use case a11y

CHANGELOG.md, src/components/nav_drawer/__snapshots__/nav_drawer.test.js.snap, src/components/nav_drawer/_nav_drawer.scss, src/components/nav_drawer/nav_drawer.js
#3143
NavDrawer didn't scroll in mobile view. Problem solved using respective css selectors to modify flex-wrap property.
=> [EuiNavDrawer] Fix scrolling in mobile view

CHANGELOG.md, src/components/form/select/_select.scss
<h1>Description</h1>
Old - #3178
Fixes #3171 
GIF
=> Removed moz border on focus from EuiSelect.

CHANGELOG.md, src/components/token/__snapshots__/token.test.tsx.snap, src/components/token/token.tsx
#3182
aria-label, aria-labelledby, aria-describedby, title is now added to EuiToken
~~Check against **all themes** for compatibility in both light and dark modes
~~Checked in **mobile**
=> Pass title and aria attributes to `EuiToken`'s icon element

CHANGELOG.md, src/components/popover/_popover.scss
This is a one-pixel offset change.
So I noticed that some of the chevrons (i.e. arrows) on the popovers on the [BasicTables](https://elastic.github.io/eui/#/tabular-content/tables) component had a dark line between the arrow and the box:
without dark line:
with dark line:
I noticed that this happens repeatably for the same components on the same page (at the same zoom level), as well as that which popovers on the page do it changes if I adjust my browser zoom.  This suggests it's just a subpixel thingy, as I like to call them.
To help illustrate: we can move the arrow down to exaggerate the effect:
Or we can move it up _too far_:
It seemed like, in this case, all that was needed was _one more pixel_.  And it's in better shape now.
I checked all of the positions in 3 different zoom levels …
=> Fix EuiPopover arrow position in Android and Linux

src/components/search_bar/query/date_format.test.ts, src/components/search_bar/query/date_format.ts
Fixes: #634
Fixed week check, earlier for `week 0, 10, etc`  it was failing
=> Undo skipped date_format tests

src-docs/src/views/context_menu/content_panel.js, src-docs/src/views/context_menu/context_menu.js, src-docs/src/views/context_menu/context_menu_with_content.js, src-docs/src/views/context_menu/single_panel.js, src-docs/src/views/control_bar/control_bar.js, src-docs/src/views/control_bar/control_bar_example.js, src-docs/src/views/control_bar/controls.js, src-docs/src/views/control_bar/mobile.js, src-docs/src/views/control_bar/tabs.js, src-docs/src/views/copy/copy.js, src-docs/src/views/datagrid/additional_controls.js, src-docs/src/views/datagrid/column_widths.js, src-docs/src/views/datagrid/container.js, src-docs/src/views/date_picker/classes.js, src-docs/src/views/date_picker/date_picker.js, src-docs/src/views/date_picker/inline.js, src-docs/src/views/date_picker/locale.js, src-docs/src/views/date_picker/open_to_date.js, src-docs/src/views/date_picker/states.js, src-docs/src/views/date_picker/time_select.js, src-docs/src/views/delay_render/delay_hide.js, src-docs/src/views/delay_render/delay_render.js
Makes progress on #3150
Converted multiple docs examples from class to functional components:
- EuiContextMenu
- EuiControlBar
- EuiCopy
- EuiDataGrid 
- EuiDatePicker
- EuiDelayRender
- EuiDelayHide 
=> [DOCS] Converts multiple examples from class to functional components

src-docs/src/views/avatar/avatar_example.js
This PR adds some snippets to the **EuiAvatar** docs.
=> Add snippets to avatar docs

src-docs/src/views/form_controls/checkbox.js, src-docs/src/views/form_controls/field_password.js, src-docs/src/views/form_controls/field_search.js, src-docs/src/views/form_controls/field_text.js, src-docs/src/views/form_controls/radio.js, src-docs/src/views/form_controls/select.js, src-docs/src/views/form_controls/switch.js, src-docs/src/views/form_controls/text_area.js
=> [Docs] Converted form control component examples to functional component 

CHANGELOG.md, src-docs/src/views/tables/actions/actions.js, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx
Fixes #3029 UI/UX: Accounting for action availability while computing row actions
As stated in the docs ([Adding actions to BasicTable](https://elastic.github.io/eui/#/tabular-content/tables)): 
> There can only be up to 2 actions visible per row. When more than two actions are defined, the first 2 isPrimary actions will stay visible, an ellipses icon button will hold all actions in a single popover.
Currently, the availability of an action is not being taken into account while computing for popover and primary actions.
Let's say you have:
- Total Actions: 4.
- Active Action on a particular row: 1.
Similarly, if the first 2 primary actions in  your action list happen to be unavailable, none of your available primary action will not even be shown on hover as primary actions are being …
=> #3029 EuiBasicTable: Accounting for action availability while computing row actions

CHANGELOG.md, src/components/icon/icon.tsx
This PR fixes the `img` element in `EuiIcon` components using custom SVGs to have an `alt` attribute with an empty string, rather than no `alt` attribute at all. This ensures validation while also indicating to screen readers to not read icons that are for decoration purposes only.
=> Ensure alt attribute in custom icon img elements

CHANGELOG.md, src/components/datagrid/_data_grid.scss, src/components/datagrid/_data_grid_column_selector.scss, src/components/datagrid/_variables.scss, src/components/datagrid/column_selector.tsx, src/components/datagrid/column_sorting.tsx
Fixes https://github.com/elastic/eui/issues/3209
Adds an overflow to a couple of the popovers in Data Grid to fix instances where there are lots of columns.
=> Add overflow to datagrid toolbar dropdowns

src-docs/src/routes.js, src-docs/src/views/datagrid/datagrid_focus_example.js, src-docs/src/views/datagrid/focus.js, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_cell.tsx, src/components/datagrid/data_grid_header_cell.tsx, src/components/focus_trap/focus_trap.tsx
Fixes #2626 
This is ready to review **functionality**, not yet the code side.
Added a new docs page for data grid, **Data grid focus**, to track requirements and provide a datagrid for testing these states. This also touched `EuiFocusTrap`'s outside-click-disabling, so we'll want to double check that (added ability to re-enable a trap which was previously-disabled-by-click).
I also want to diagram/record the focus logic and refactor it, but that has to wait until the logic is solidified and should be in another PR.
=> Overhaul EuiDataGrid's cell focus states

CHANGELOG.md, scripts/babel/proptypes-from-ts-props/index.js, scripts/babel/proptypes-from-ts-props/index.test.js, src/components/icon/__snapshots__/icon.test.tsx.snap, src/components/icon/icon.test.tsx, src/components/icon/icon.tsx
Fixes #3175 
**EuiIcon** incorrectly specified `ReactElement` instead of `ComponentType`, this passed through TS because the svg imports are typed as `any`, mixing in that type at `const icon = this.state.icon || empty;` and losing any subsequent type checking.
* fixed the type
* added proper type casting on `empty` to avoid mixing in `any`
* added unit test
=> Fix incorrect TypeScript type for custom components passed to EuiIcon

src-docs/src/views/i18n/context.js, src-docs/src/views/link/link_disable.js, src-docs/src/views/list_group/list_group.js, src-docs/src/views/list_group/list_group_link_actions.js, src-docs/src/views/mutation_observer/mutation_observer.js, src-docs/src/views/outside_click_detector/outside_click_detector.js
Converted i18n, links, list group, mutation observer, outside click detector examples to functional components
~~- [] Checked for **accessibility** including keyboard-only and screenreader modes~~
~~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~~
=> [Docs] Converted i18n, link, list group and some other examples to functional components

src-docs/src/views/side_nav/side_nav_example.js
This PR adds snippets to the **EuiSideNav** docs.
=> [Docs] Add snippets to EuiSideNav

packages/eslint-plugin/yarn.lock, packages/react-datepicker/yarn.lock, yarn.lock
I confirmed these are used in build and dev-server only flows and took the path of least resistance, only upgrading the already-latest major deps to point at the most recent of these packages.
=> Upgrade minimist and kind-of dependencies

scripts/jest/config.json, scripts/jest/polyfills/mutation_observer.js, scripts/jest/setup/unmount_enzyme.js, src/components/drag_and_drop/__snapshots__/droppable.test.tsx.snap, src/components/drag_and_drop/droppable.test.tsx
Turns out enzyme [does not attempt to unmount or cleanup components](https://github.com/enzymejs/enzyme/issues/911) after executing. It makes sense, but is unfortunate. The impact to us has mostly been through the MutationObserver polyfill singleton yelling about too many listeners and possible memory leak. Turns out there was a memory leak.
* intercepts calls to `mount` and stores a reference to the returned component
* added a global `afterEach` to unmount any still-mounted components
* ~bumped~ ~un-bumped?~ **cratered** the MutationObserver polyfill's setMaxListeners back to a reasonable number
* modified **EuiDroppable**'s test to reset the react-beautiful-dnd context counter
* the snapshots were already affected by the global unmounting
* its individual snapshots are no longer …
=> Unmount enzyme components after test execution

src/components/form/form_row/make_id.test.ts, src/components/table/table_footer_cell.test.tsx, src/components/table/table_header_cell.test.tsx, src/components/table/table_header_cell_checkbox.test.tsx, src/components/table/table_row_cell.test.tsx, src/components/table/utils.ts
This has bothered me for a while. There are four unit tests which purposefully trigger the warning
> Two `width` properties were provided. Provide only one of `style.width` or `width` to avoid conflicts.
which normalizes the idea of logs/warnings/errors in unit test output. This PR captures & verifies the messages, while continuing to emit any non-expected warnings. I also fixed a similar thing in the makeId test.
~- [ ] A …
=> Silence expected console.warn messages

src-docs/src/views/description_list/description_list_example.js
This PR adds snippets to the **EuiDescriptionList** docs.
=> [Docs] Add snippets to EuiDescriptionList

CHANGELOG.md, src/components/date_picker/super_date_picker/date_popover/date_popover_content.js
Fixes #3250 
This error due to `name` and `content` not passed to EuiTabbedContent.
~~- [ ] A [changelog](https://github.com/elastic/eui/blob/master/CONTRIBUTING.md#changelog) entry exists and is marked appropriately~~
=> Fixed console error in EuiDatePopoverContent

src-docs/src/views/title/title_example.js
=> [DOCS] Added Snippets to EuiTitle.

src-docs/src/views/health/health.js, src-docs/src/views/health/health_example.js, src/components/health/health.tsx
Closes #3163 
<strong>Added custom Hex String Example</strong>
<strong>Added Description for color prop</strong>
=> [Docs] Improved EuiHealth example and added description for `color` prop

CHANGELOG.md, src-docs/src/components/guide_components.scss, src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/routes.js, src-docs/src/views/collapsible_nav/collapsible_nav_example.js, src-docs/src/views/comment/comment_example.js, src-docs/src/views/html_id_generator/html_id_generator_example.js, src/components/side_nav/side_nav_item.tsx
When there is a new component added to the docs, you can now add the key `isNew: true` to the sections object (just below the `title` in the `_example.js` files). This will add the pink **NEW** badge in the side nav.
Here are examples of the different states including truncation.
---
I had to fix EuiSideNavItem's to pass down `className` on both itself and the icon otherwise custom classNames were getting overridden/ignored. Fixes part of #2380
=> [Docs] Adds a *NEW* badge to side nav items that are new

CHANGELOG.md, src/components/tabs/tabbed_content/tabbed_content.tsx
Fixes #3261 
Fixed EuiTabbedContent doesn't focus on the correct tab when using the mouse and `initialFocus` is `selected`
This issue was fixed by calling focus after `setState` so the correct tab is focused.
Before:
After :
=> Fixed focus on EuiTabbedContent when initialFocus is selected

src-docs/src/views/tool_tip/tool_tip_example.js
This PR adds snippets to the **EuiToolTip** docs.
=> [Docs] Add snippets to EuiToolTip

.github/pull_request_template.md, CONTRIBUTING.md, FAQ.md, README.md, src-docs/src/views/button/button_icon.js, wiki/component-design.md, wiki/component-development.md, wiki/consuming.md, wiki/creating-components-manually.md, wiki/creating-components-yeoman.md, wiki/creating-icons.md, wiki/documentation-guidelines.md, wiki/theming.md
Simply moving any documentation specific guidelines to the actual documentation-guidelines.md.
=> [Wiki] Re-organizing documentation guidelines

CHANGELOG.md, src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.test.tsx, src/components/badge/badge.tsx
Closes #3282 where the inline styles for EuiBadge are being wiped by consumer passed inline styles.
- ~~[ ] Checked in **mobile**~~
- ~~[ ] Props have proper **autodocs**~~
- ~~[ ] Added **documentation** examples~~
- ~~[ ] Checked for **breaking changes** and labeled appropriately~~
- ~~[ ] Checked for **accessibility** including keyboard-only and screenreader modes~~
=> [EuiBadge] Fix the inline styles being wiped by consumer passed styles

CHANGELOG.md, src/components/i18n/__snapshots__/i18n.test.tsx.snap, src/components/i18n/i18n.test.tsx, src/components/i18n/i18n_util.tsx
Fixes #3301 
- Added test to render component if the value is null
- Fixed issue by checking if the child is null then return false
=> Fixed EuiI8n hasPropName utility errors on null values 

src-docs/src/views/popover/popover_example.js
This PR updates the **EuiPopover** snippets so they can match our **Adding snippets** documentation.
Also, the **Demo JS** tabs were recently updated and are now written like a **Function Component** so it makes sense to have the snippets with the same format.
=> [Docs] Update EuiPopover snippets

src/test/find_test_subject.test.tsx
Converts the last remaining `src` JS file to TS (excluding open PRs and index files).
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked …
=> Convert `find_test_subject.test` to TypeScript

scripts/jest/config.json, scripts/jest/setup/polyfills.js
Memory leaks, grr.
Quick google search led to an excellent article https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html wherein I learned about combining node's `--expose-gc` and jest's `--logHeapUsage` (in addition to `--runInBand)`:
```
node --expose-gc node_modules/.bin/jest --logHeapUsage --runInBand --config ./scripts/jest/config.json
```
Running that showed every test suite slowly but surely increased the heap size, leaking memory. Threw in an `--inspect-brk` and looked around the heap snapshots, and it appeared that nothing was being cleaned up. No smoking guns, just **everything** stuck around. Yay.
Commented out the contents of our setup files:
```
"<rootDir>/scripts/jest/setup/polyfills.js",
"<rootDir>/scripts/jest/setup/enzyme.js", …
```
=> Fix jest memory leak

src-docs/src/views/home/home_view.js
I adjusted some of the wording, but the main change is the addition of this:
EUI's original role was to support engineers building UI in Kibana. Especially those who didn't have designer to help with layouts, UX, etc. And so EUI was/is very opinionated in terms of the UI it renders and the configurable options.
However, I now see EUI's role evolving as we grow and Elastic gains more designers to work alongside the engineers. I think the system needs to start being much more flexible and customizable so it can **support the designer’s needs while also supporting the engineers with minimal overrides.**
We should still be able to "maintain brand" through our judicious use of tokens for color, spacing, and typography. And since these are the building blocks of any component, they may also be …
=> [Docs] Update design goals on home page

CHANGELOG.md, src/components/form/field_search/field_search.tsx
=> Fixed `EuiInMemoryTable` `isClearable` property to initiate reset

src-docs/src/views/form_layouts/described_form_group.js, src-docs/src/views/form_layouts/form_rows.js, src-docs/src/views/form_layouts/inline_popover.js, src-docs/src/views/guidelines/toasts.js, src-docs/src/views/header/header_spaces_menu.js, src-docs/src/views/portal/portal.js, src-docs/src/views/portal/portal_insert.js, src-docs/src/views/selectable/selectable_custom_render.js, src-docs/src/views/selectable/selectable_popover.js, src-docs/src/views/side_nav/side_nav.js, src-docs/src/views/side_nav/side_nav_complex.js, src-docs/src/views/side_nav/side_nav_force_open.js
Converted 
- EuiSideNav 
- EuiSelectable
- EuiPortal
- EuiHeaderSpacesMenu
- Toast Guidelines
- EuiFormGroup
examples to functional components
=> [Docs] Converted EuiSideNav EuiSelectable and some other examples to functional components 

CHANGELOG.md, src/components/popover/popover.tsx, src/components/tour/__snapshots__/tour_step.test.tsx.snap, src/components/tour/tour_step.tsx
Fixes a bug where passing `left` or `top` as part of the <b>EuiPopover</b> `style` prop would override its internally calculated position.
The passing-through of `style` to the _panel_ of <b>EuiPopover</b> has only been possible since <b>EuiTourStep</b> was introduced. It should have been a new style object prop, as `style` was already used on the base `div` element of <b>EuiPopover</b>.
Adding and using the `panelStyle` prop solves two problems:
1) <b>EuiPopover</b> will not have its position overridden
2) <b>EuiTourStep</b> will more correctly set `minWidth` on the panel element _only_ (instead of _also_ setting `minWidth` on a wrapper element)
~- [ ] Checked in **IE11** and …
=> Add `panelStyle` prop to EuiPopover; Fix EuiTourStep `minWidth` prop placement

wiki/react-router.md
I chatted about this with @chandlerprall and @thompsongl yesterday when asking for assistance in merging React Router's `<Link>` component behavior with `<EuiButton>`, and was super helpfully pointed towards the [React Router wiki](https://github.com/elastic/eui/blob/constance/react-router-links-update/wiki/react-router.md#react-router-51) doc.
After wrangling the 5.1 snippet/code example to work in Kibana, I realized it was missing a few details to get it working 100% the same as `<Link>` does:
- 6b35491 was the major functionality I noticed missing. In Kibana plugins, URL routes look something like `localhost:5063/xyz/app/your_plugin_name` and get added to the `<Router basename="...">` prop.
The snippet wasn't accounting for basename, and as such clicking would work, but `href` …
=> Update wiki doc - React Router 5.1 code snippet

CHANGELOG.md, src/components/date_picker/react-datepicker.d.ts
Closes #3319 by allowing **ReactDatePicker**'s `startDate` and `endDate` values to be null. I tested passing `null` into these props to verify it works as expected, and also followed their usage in the code to check for possible breakages.
=> Extended types for ReactDatePicker's startDate and endDate to allow null

CHANGELOG.md, src/components/search_bar/search_bar.tsx
Closes: #3327
made a copy of `box` , then deleted `shema` attribute and finally passed the copy to `<input/> `
`- [ ] Checked in **IE11** and **Firefox**~
-~ [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)** examples~
=> Removed schema="[object Object]"  form EuiInMemoryTable

CHANGELOG.md, src/components/page/page_body/_page_body.scss
Fixes https://github.com/elastic/eui/issues/3373
See https://github.com/elastic/eui/issues/3373#issuecomment-617959532 for more discussion
By setting a max width of `EuiPageBody` we can likely force inner items to not break down in various smaller screen configs.
=> Set a max width to EuiPageBody

src-docs/src/views/pretty_duration/pretty_duration.js, src-docs/src/views/pretty_duration/pretty_duration_example.js
This PR started by adding Snippets to EuiPrettyDuration. But after some discussion, it was decided to:
-  Enable the copy button for the demos **EuiCodeBlock**s
- Not adding snippets
=> [DOCS] Improved Demos for EuiPrettyDuration.

CHANGELOG.md, src-docs/src/views/card/card_example.js, src-docs/src/views/card/card_image.js, src/components/card/_card.scss, src/components/card/card.tsx
Issue: #3341
Added `ReactElement` to the `EuiCard` `image` prop to allow passing custom component.
=> [EuiCard] Allow custom component for image prop

yarn.lock
Upgrades `escodegen` to avoid an unrecognized (but permissive) license downstream. `escodegen` is only used by `jsdom`.
=> Upgrade escodegen dependency

src-docs/src/views/empty_prompt/empty_prompt_example.js
This PR adds snippets to the **EuiEmptyPrompt** docs.
=> [Docs] Add snippets to EuiEmptyPrompt

CHANGELOG.md, src/components/form/radio/radio.tsx, src/components/form/radio/radio_group.tsx
Fixes #3248  id is required if a label is passed to EuiRadio
Created new interface for checking if a label is passed or not and perform as required
=> [EuiRadio] Make `id` required if `label` is present

src-docs/src/views/comment/comment_example.js
Continuing the snippets work! 🎉 
This PR updates one of the EuiComment snippets. A very small fix.
=> [Docs] Update EuiComment snippet

CHANGELOG.md, src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.tsx
Fixes #3390
Use `span` instead of `button` | `a` if `onClick` is not provided.
=> Fixed EuiBadge iconOnClick makes badge text clickable

CHANGELOG.md, src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap, src/components/date_picker/_date_picker_range.scss, src/components/date_picker/date_picker.tsx, src/components/date_picker/date_picker_range.tsx
Fixes #3374 
Icon has been changed to be a part of the start date, so the picker aligns with the front,
<s> - [ ] Checked for **accessibility** including keyboard-only and screenreader modes </s>
=> Start date popover for date picker range starts at the calendar icon

CHANGELOG.md, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/collapsible_nav/_collapsible_nav.scss, src/components/collapsible_nav/collapsible_nav.test.tsx, src/components/collapsible_nav/collapsible_nav.tsx, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/flyout/flyout.test.tsx, src/components/flyout/flyout.tsx, src/components/header/_header.scss, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.test.tsx, src/components/popover/popover.tsx
It was found that the fixed EuiHeader's z-index was too high, causing popovers to slip underneath. While the primary fix would be to contain the popover's within Kibana's main app area, this isn't possible at the moment.
The quick fix is to lower the header's z-index from `7000` to `1000` (keeping the same z-index for static and fixed position). This allows the popovers to overlap the header (for now).
**However**, this caused issues when flyouts or the nav (with EuiOverlayMask) were open, where the nav would then be hidden underneath (including the collapsible nav).
**The fix** was to add to the body's class list a class indicating when a flyout is open `.euiBody--hasFlyout` or when the nav is open `.euiBody--collapsibleNavIsOpen` and use that to increase the header's z-index up to …
=> Fixes for EuiHeader z-index, EuiPopover buffer, and EuiCollapsibleNav close button props

src-docs/src/views/tables/in_memory/in_memory_custom_sorting_section.js, src-docs/src/views/tables/in_memory/in_memory_section.js
Fixes #3362 
Add documentation around EuiInMemoryTable's usage of column names in sorting
~~- [ ] Added or updated **[jest tests]~~(https://github.com/elastic/eui/blob/master/wiki/testing.md)**~~
=> Add documentation around EuiInMemoryTable's usage of column names in sorting

CHANGELOG.md, src/components/icon/__snapshots__/icon.test.tsx.snap, src/components/icon/icon.test.tsx, src/components/icon/icon.tsx
Fixes #3393 
Added a caching layer and some other logic to avoid fading in icons when they are immediately renderable.
* Added a caching layer to EuiIcon and an exported function to clear one-or-all of the cache entries
* Removed the `euiIcon-isLoaded` class when an icon is immediately renderable, removing the fade-in animation on cached icons or when a custom component is provided
* Single snapshot touched, proving the non-fade-in for custom components
The various update paths for the icon's state is definitely a mess. Everything's working, rendering, and snapshotting as expected but the next time the maze is touched it should be documented & refactored.
~- [ ] Checked in …
=> Add caching layer to EuiIcon

CHANGELOG.md, src/components/basic_table/basic_table.tsx
Fixes #3416 
When `id` of the data is `0` EuiBasicTable selection doesn't work as expected because `0` is falsy. This issue is solved by checking if the `id` is `null` or `undefined`.
=> Fixed EuiBasicTable selection doesn't work as expected when id is 0

CHANGELOG.md, src/components/nav_drawer/nav_drawer.tsx
Fixes #3414
If locked, the old behaviour disabled the outside click detector, even if it was then unlocked again. Even when locked, it seems like the outside click detector doesn't need to be disabled, because it calls closeBoth which also checks if the nav drawer is locked itself, and only closes the outer menu if locked.
This PR adjusts that behaviour so that when the lock button is pressed, the outside click detector is always kept enabled. 
Going to be honest, I'm not really sure how to approach testing this one - happy of course for you guys to just take this change and add tests how you see fit if that's okay?
=> Fixed EuiNavDrawer not closing on outside click after being unlocked

src-docs/src/views/context_menu/context_menu.js
I recently experienced some difficulty comprehending the docs' example code explaining how to create a nested context menu. There was some clever code demonstrating the configuration, but it obscured for me the basic requirements the component needs to function.
There are other examples using the same type of code further down the page, so I wanted to create a "barebones" example with POJOs to show how to use this feature.
To check the changes, compare the docs outputted by this patch against https://elastic.github.io/eui/#/navigation/context-menu and ensure that the interaction you see looks the same as the example below:
=> Simplify docs instructions for basic `EuiContextMenu` example

CHANGELOG.md, src/components/basic_table/in_memory_table.tsx
PR #3371 introduces a new issue when a filter is set and when we try to select a row the data is reset as shown in the screenshot. This issue can be found at [https://eui.elastic.co/pr_3371/](https://eui.elastic.co/pr_3371/).
Before
After
=> [EuiInMemoryTable] Fixed data reset on selection change.

CHANGELOG.md, src/components/date_picker/date_picker.tsx, src/components/date_picker/date_picker_range.tsx
Resolves a type mismatch problem between the exported component interface (`EuiDatePickerProps`) and `defaultProps` interface in <b>EuiDatePicker</b>.
The component makes use of `ApplyClassComponentDefaults`, which in this case applies the inferred default type of `popoverPlacement` (`string | undefined`) over the explicit type defined in `_EuiDatePickerProps` (union type).
Resolved by using `as const` with the `popoverPlacement` default value.
(Kibana extends this component and the `...rest` interface errors as a mistype)
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/ …
=> [EuiDatePicker] `defaultProps` types

CHANGELOG.md, src/global_styling/mixins/_form.scss
This PR fixed the `euiFormControlIsLoading` SASS mixin to prevent the loading icon from overlapping with the text when the form control is `compressed` and has an icon on the right side.
I noticed this issue when I was working on the **EuiColorPalettePicker**.
=> Fix euiFormControlIsLoading mixin to prevent the loading icon overlapping when compressed

CHANGELOG.md, src/components/form/field_search/field_search.tsx
Fixes: #3420
I noticed that `onSearch` was called twice because of its binding with the input element during `componentDidMount` function as well as `onKeyUp` function. 
=> Fixed double search issue with [EuiFieldSearch]

CHANGELOG.md, src/components/common.ts, src/components/date_picker/date_picker.tsx
`ApplyClassComponentDefaults` errantly applied TS's interpretation of `defaultProps` to the extracted definition, instead of using `defaultProps`'s keys to index/lookup the types already defined by the component's props.
I tested this change by mimicking a wrapping of the datepicker Kibana does, and using both that wrapper and EuiDatePicker directly in various configurations of required, defaulted, and omitted values.
~- [ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)** …
=> Fix ApplyClassComponentDefaults's typing of a defaultProps

CHANGELOG.md, src/components/date_picker/super_date_picker/pretty_duration.ts
The `prettyDuration` util function has an implicit `string | undefined` return type because of `matchingQuickRange.label`.
`matchingQuickRange.label` should allow `undefined`, but `prettyDuration` has a fallback value (`cantLookup(...)`) that should be used in place of an empty label.
Kibana indirectly uses `prettyDuration` and correctly expects a `string` for output.
~- [ ] …
=> Ensure `string` return from `prettyDuration` util

CHANGELOG.md, src/components/badge/badge_group/badge_group.tsx, src/components/header/header_section/header_section_item_button.tsx, src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, src/components/tabs/tabs.tsx
Set `displayName` value for top-level components using `React.forwardRef`. Otherwise, each component renders as `<ForwardRef>` in shapshots and React dev tools.
Eliminates snapshot churn Kibana.
=> Ensure correct display name for `forwardRef` components

src-docs/src/components/guide_section/guide_section.js
Fixes a race condition where _sometimes_ the content of the Demo JS is not available when the `scrollTop` check is done on an internal element.
This fix does a few things:
1) Moves the check closer to where the tab switch happens and calls it fewer times
2) Adds some wait time via `requestAnimationFrame`
3) Checks for existence of the element, just in case. …
=> [Docs] 'Demo JS' tab error fix

src-docs/src/views/expression/expression_example.js
This PR adds  snippets to`EuiExpression` following our "Adding snippets" documentation.
=> [Docs] Add EuiExpression snippets

src-docs/src/views/markdown_editor/markdown_editor.js, src/components/markdown_editor/index.ts, src/components/markdown_editor/markdown_editor.test.tsx, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_format.tsx, src/components/markdown_editor/markdown_modes.ts
Creates initial code structure for
* Refactored `EuiMarkdownEditor` into a function component
* Split the `unified` plugins structure into two passes (parse, process/render) and use them as defaults
* split apart to make it easier to naively append additional markdown plugins
* exported for re-use and allow consuming apps to selectively modify
* Snapshots the markdown AST so the information can be re-used by the UI/plugins (future work)
=> Markdown editor plugins

src-docs/src/views/resizable_container/resizable_container_basic.js, src-docs/src/views/resizable_container/resizable_container_reset_values.js, src-docs/src/views/resizable_container/resizable_container_three_panels.js, src-docs/src/views/resizable_container/resizable_container_vertical.js, src-docs/src/views/resizable_container/resizable_resizer_size.js
Fixes: #3444
used `'../../../../src/components';` instead of `'../../../../src';` as per the function requirements to classify services , utils , components
~- [ ] Props have proper **autodocs*~
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/do …
=> [DOCS] Fixed import statements for EuiResizableContainer

CHANGELOG.md, src/components/code_editor/__snapshots__/code_editor.test.tsx.snap, src/components/code_editor/code_editor.tsx
In #2970 the default value for the theme was set to `github`. As a result, now we have many places in `Kibana` where we need to import this theme even if we don't want to specify theme (remind you it's optional property). 
Related issue in Kibana repo: 
https://github.com/elastic/kibana/issues/56424
I think if we decided to set `github` as a default theme, it should be loaded here
=> [EuiCodeEditor] Console error when using the editor without import the default theme

CHANGELOG.md, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/collapsible_nav/_collapsible_nav.scss, src/components/collapsible_nav/collapsible_nav.tsx
This PR closes #3402 
With this PR I'm improving the contrast for the **EuiCollapsibleNav** close link.
A few decisions:
- During the implementation, I decided to keep the **EuiButtonEmpty** because it was the most similar button to what I wanted to achieve.
- Since this button was only implemented to keyboard users I used the `<EuiScreenReaderOnly showOnFocus>` component and added a visible focus ring as suggested by @chaos. 
=> Improve contrast for EuiCollapsibleNav close link

src-docs/src/views/date_picker/date_picker_example.js, src-docs/src/views/date_picker/utc.js
This PR adds `EuiDatePicker` snippets following our "Adding snippets" documentation.
Also added the description of `popperClassName` and added `showTimeSelect` to the UTC example so consumers can see the UTC change in action.
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry …
=> [Docs] Add EuiDatePicker snippets

CHANGELOG.md, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.test.tsx, src/components/card/card.tsx
Fixes : #3459
Added `null` as acceptable type to `icon` for `EuiCardProps`
=> Added null as acceptable `icon` for EuiCard

package.json, src-docs/.eslintrc.js, src-framer/.eslintrc.js
* Change lint-es task in package.json to use escaped double-quotes.
When running `yarn lint-es` on Windows, the following error is thrown in the console:
No files matching the pattern "'{src,src-docs,src-framer}/**/*.{ts,tsx,js}'" were found.
Please check for typing mistakes in the pattern.
This is due to https://eslint.org/docs/user-guide/command-line-interface:
"If you want to use node glob syntax, you have to quote your parameter (using double quotes if you need it to run in Windows)"
With this fix, it works as expected on all platforms.
Fixes #3484
--------------------
* Reformat .eslintrc.js files matching the guidance output from `yarn lint-es` (prettier/prettier rules).
All files in the project lint pattern now pass linting.
=> Change lint-es task in package.json to use escaped double-quotes (to fix Windows console issue)

package.json, src-docs/src/views/markdown_editor/markdown_editor.js, src-docs/src/views/markdown_editor/plugins/markdown_chart.js, src-docs/src/views/markdown_editor/plugins/markdown_tooltip.js, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_types.ts, yarn.lock
`!{chart}`
Experimenting with syntax we'll need for more complex embeddings. Can be configured with a json string
```
!{chart {"palette": 2, "height": 400}}
```
`!{tooltip[tooltip text][anchor]}`
Demonstrates re-parsing content consumed by a plugin - in this case, the anchor text can contain further markdown. I played with also re-parsing the tooltip text, and while it can be parsed without difficulty there is a limitation during the AST->rehype->React conversion where only content in the `children` nodes are processed. There are potential ways around this, but I'm leaving it as-is for now, and it's likely fine for the foreseeable future anyway.
```
!{tooltip[This is the tooltip][_Emphasized trigger text_]}
```
Right now, a consuming app has to jump through a few hoops to add a custom …
=> [markdown] chart & tooltip plugins

CHANGELOG.md, src/components/form/super_select/super_select.tsx
Fixes #3491
Used `componentDidMount` to render Open animation if Panel is open by default
=> [EuiSuperSelect] Dropdown renders full width when isOpen is true

src-docs/src/views/form_controls/display_toggles.js
While working on a different issue I found the size of the **EuiSpacer** inside of the **DisplayToggles** component too large.  
To solve this, I'm allowing consumers to pass a prop called `spacerSize` to control this size.
- ~ ] Checked in **IE11** and **Firefox**~
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guide …
=> [Docs] Add spacerSize prop to DisplayToggles

CHANGELOG.md, src/components/date_picker/date_picker.tsx, src/components/date_picker/react-datepicker.d.ts
According to https://github.com/elastic/eui/blob/master/packages/react-datepicker/src/popper_component.jsx, `left-start` popover placement is forgotten in current library.
<s>- [ ] Check against **all themes** for compatibility in both light and dark modes</s>
<s>- [ ] Checked in **mobile**</s>
<s>- [ ] Checked in **IE11** and **Firefox**</s>
<s>- [ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**</s>
<s>- [ ] Checked for **breaking changes** and labeled appropriately</s>
<s>- [ ] Checked for **accessibility** including keyboard-only and screenreader modes</s>
=> Adding left-start placement of the popover to EuiDatePicker

src-docs/src/views/tour/fullscreen.js, src-docs/src/views/tour/managed.js, src-docs/src/views/tour/managed_hook.js
see: https://github.com/elastic/eui/pull/2766#discussion_r430417591
I noticed over the weekend whilst exploring EuiTour that there are `console.log` statements that are firing when you step through.  I checked with @thompsongl and it appears that these were added during development with the intention of removal prior to merge.  This PR removes them.
Check against all themes for compatibility in both light and dark modes
- ~[ ] Checked in mobile~
- ~[ ] Checked in IE11 and Firefox~
- ~[ ] Props have proper autodocs~
- ~[ ] Added documentation examples~
~Added or updated jest tests~
~Checked for breaking changes and labeled appropriately~
- ~[ ] Checked for accessibility including keyboard-only and screenreader modes~
~A changelog entry exists and is marked appropriately~ (it seemed to me …
=> removes errant `console.log`s from EuiTour

CHANGELOG.md, src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
Fixes #3458 
- Pass `getSelectedOptionForSearchValue` to `EuiComboBoxOptionsList` options list as prop.
Before:
After:
I think this was missed during the typescript conversion #2838
=> Fixes EuiComboBox Label not calculated correctly

src-docs/src/views/markdown_editor/plugins/markdown_chart.js, src-docs/src/views/markdown_editor/plugins/markdown_checkbox.js, src-docs/src/views/markdown_editor/plugins/markdown_tooltip.js, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_context.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_text_area.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_types.ts
Adds the ability for UI buttons to trigger modals when creating or editing their markdown tags.
* Plugins are allowed to pass either a `formatting` object **or** an `editor` React component
* Plugin recommended practice no longer to include a `configuration` object, instead applying those values directly on the markdown node
* Method to directly set the markdown text no longer provided to the markdown renderers, instead they are given a `replaceNode`
* Editor now tracks which markdown node the text cursor is in
* currently it walks until it finds a `text` node, but this likely needs to be smarter in the future, for example if I'm in a `bold` section within a `tooltip`'s anchor text, what should happen?
* the implementation to update this knowledge is intentionally buggy (for now), e.g. …
=> [Markdown] Allow toolbar buttons to present modals to create/edit tags

src/components/markdown_editor/_index.scss, src/components/markdown_editor/_markdown_editor.scss, src/components/markdown_editor/_markdown_editor_preview.scss, src/components/markdown_editor/_markdown_editor_text_area.scss, src/components/markdown_editor/_markdown_format.scss, src/components/markdown_editor/_variables.scss, src/components/markdown_editor/markdown_editor.tsx
This PR improves the fonts for the `EuiMarkdownEditor` text and preview areas:
- I'm removing the code font family from the text area that created some visual issues
- The text and preview areas are now both using the `Inter UI` font.
- I'm also making sure the text color and background changes according to the theme.
- ~[ ] A …
=> [EuiMarkdownEditor] Improve markdown editor font

package.json, src-docs/src/views/markdown_editor/plugins/markdown_chart.js, src-docs/src/views/markdown_editor/plugins/markdown_checkbox.js, src-docs/src/views/markdown_editor/plugins/markdown_tooltip.js, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_context.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_text_area.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_types.ts, yarn.lock
Fixes #3526 
Un-disables remark's default list parsing/processing, and injects EUI's checkbox plugin above that default `list` parser so we can execute first.
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is …
=> Re-enable default markdown list parsing

CHANGELOG.md, src-docs/src/views/header/header_alert.js, src-docs/src/views/header/header_dark.tsx, src-docs/src/views/header/header_example.js, src-docs/src/views/header/header_links.js, src-docs/src/views/header/header_position.js, src-docs/src/views/header/header_updates.js, src/components/header/__snapshots__/header.test.tsx.snap, src/components/header/_header.scss, src/components/header/_header_logo.scss, src/components/header/_index.scss, src/components/header/_mixins.scss, src/components/header/_variables.scss, src/components/header/header.test.tsx, src/components/header/header.tsx, src/components/header/header_links/__snapshots__/header_link.test.tsx.snap, src/components/header/header_links/__snapshots__/header_links.test.tsx.snap, src/components/header/header_links/_header_link.scss, src/components/header/header_links/_header_links.scss, src/components/header/header_links/header_link.test.tsx, src/components/header/header_links/header_link.tsx, src/components/header/header_links/header_links.tsx, src/components/header/header_section/header_section_item.tsx, src/components/nav_drawer/_variables.scss, src/themes/eui-amsterdam/global_styling/variables/_header.scss, src/themes/eui-amsterdam/global_styling/variables/_index.scss, src/themes/eui-amsterdam/overrides/_header.scss, src/themes/eui-amsterdam/overrides/_index.scss
This PR tackles 3 main things:
This adds support for providing `theme="dark"` and the header will display as if it's dark mode no matter the theme. For now it only supports a few child components.
Mainly fixes some usages of `$euiHeaderSize` vs `$euiHeaderChildSize` variables, and removes the borders. This does not yet tackle the breadcrumb updates.
Like alignments and responsive displays.
=> Dark EuiHeader

CHANGELOG.md, src-docs/src/views/datagrid/datagrid_styling_example.js, src/components/datagrid/data_grid.tsx
Fixes #3505
Added `minSizeForControls` to `euiDataGrid` as prop to control the min size for grid controls.
~~[ ] Checked in **IE11** and **Firefox**~~
~~[ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**~~
~~[ ] Checked for **accessibility** including keyboard-only and screenreader modes~~
=> Add minSizeForControls to euiDataGrid

CHANGELOG.md, src/components/combo_box/combo_box.test.tsx, src/components/combo_box/combo_box.tsx
Fixes #3528 , a regression from #2838 , where **EuiComboBox**'s `inputRef` callback was not fired.
=> Fix bug in EuiComboBox's inputRef callback

CHANGELOG.md, src-docs/src/views/color_picker/color_picker_example.js, src-docs/src/views/color_picker/props.tsx, src/components/color_picker/color_palette_picker/color_palette_picker.tsx, src/components/color_picker/color_palette_picker/index.ts
I noticed that after some TS changes for the **EuiColorPalettePicker** that the docs props tab wasn't showing properly all the props. 
This PR adds exports for the missing types so that they can be visible in our docs.
=> Add exports for EuiColorPalettePicker types

CHANGELOG.md, src/components/call_out/__snapshots__/call_out.test.tsx.snap, src/components/call_out/call_out.tsx
I added conditional rendering to the title in the callout function. As extra space was being taken up, when there was a missing title.
Relating to Issue : fixes #3473
@cchaos
=> Adding conditional rendering in EuiCallOut component based on title

CHANGELOG.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/basic_table.tsx
This forces all keys to be unique regardless of field name collisions (rare) and computed columns (less rare).
Closes #3558 
=> [EuiBasicTable] Always use Column Index for Footer key

CHANGELOG.md, src/components/card/_card.scss
Fixes an issue that allowed card images to peek out of their containers at the top left/right corners.
~- [ ] Added or updated **[jest tests]~(https://github.com/elastic/eui/blob/master/wiki/testing.md)**
=> Adding an overflow to round card images.

src-docs/src/services/string/clean_imports.js
Replaced the `.matchAll` call with `.match` and updated how those matched values are extracted. Tested that the docs load in those two browsers, and that the code sandbox links still function as expected
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked …
=> Fix EUI docs in IE11 & Safari < 13

packages/react-datepicker/yarn.lock
Bump `websocket-extensions` in `react-datepicker` to `v1.4` (ref: #3571)
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/do …
=> websocket-extensions to 1.4

CHANGELOG.md, src/components/datagrid/column_sorting.tsx, src/components/datagrid/column_sorting_draggable.tsx
From: https://github.com/elastic/eui/pull/3520#issuecomment-640285036
Added display prop to `EuiDataGridColumnSortingDraggable` to set the value to the column sorting popover popover
=> Added display prop to EuiDataGridColumnSortingDraggable

src-docs/src/views/code_editor/custom_mode.js
made use of useState in custom code editor example to preserve the text when user switches the tabs
=> made use of useState in custom code editor example

CHANGELOG.md, src-docs/src/views/header/header_example.js, src/components/control_bar/_index.scss, src/components/flyout/_mixins.scss, src/components/header/_index.scss, src/components/nav_drawer/_index.scss, src/global_styling/mixins/_header.scss, src/global_styling/variables/_header.scss, src/global_styling/variables/_index.scss
It was pointed out that the mixin provided for fixed headers wasn't properly importing the necessary variables so consumers got hit with a missing variable error when trying to use it. This was because the header variable that was being used in the mixin wasn't in the global_styles but in the component styles. 
I've moved all the header variables to `global_variables` since these seem to be affecting more than itself anyway.
I have tested that this fixes the missing variable issue by linking locally in the K8 POC. Errors are gone 👍 !
This also fixes the docs that accidentally said to use `@mixin ...` instead of `@include ...`.
- ~[ ] Checked **[Code …
=> [EuiHeader] Fix SASS globals & docs

CHANGELOG.md, src/themes/eui-amsterdam/overrides/_filter_group.scss, src/themes/eui-amsterdam/overrides/_index.scss
before:
after:
fixes #3590 
~~- [ ] Added or updated **[jest tests]~~(https://github.com/elastic/eui/blob/master/wiki/testing.md)**
=> [EuiFilterButton] Fix Amsterdam style

CHANGELOG.md, src/components/empty_prompt/empty_prompt.tsx
Used default titleSize _(m)_ for EuiEmptyPrompt , 
this is specifically docs side as it doesn't affect working of the component
when no `titleSize` is passed , `EuiTitle` applies a default size `'m'` to the title but no such identification is given inside the `docs`
This is just to shown that `titleSize` is implicitly set to  `'m'`  by default
~- [ ] Checked for **breaking changes** and labeled …
=> Used default titleSize for EuiEmptyPrompt

src-docs/src/views/badge/badge_example.js
`EuiBadgeGroup` props section was displayed underneath the `EuiBetaBadge` prop's section.
<hr/>
=> [DOCS] EuiBadgeGroup props are passed to correct example

.eslintrc.js, src-docs/src/views/expression/stringing.tsx, src/components/accessibility/keyboard_accessible.test.tsx, src/components/avatar/avatar.tsx, src/components/expression/expression.test.tsx, src/components/i18n/i18n_util.tsx, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/tool_tip/tool_tip_popover.test.tsx, src/services/copy_to_clipboard.ts, src/services/predicate/lodash_predicates.ts, src/services/time/timer.test.ts, src/test/react_warnings.ts
This PR enables a [new eslint rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-tslint-comment.md) that prevents accidental `tslint` directives (this project no longer uses tslint).
Since we just updated to @typescript-eslint:v3.2.0 anyway, this seemed fun enough to be worth doing.  I suspect it will be a default rule in the next major version anyway.
(didn't seem worthy of a changelog entry to me, but I'm happy to make one if not)
=> enables new ban-tslint-comment eslint rule

CHANGELOG.md, src/themes/eui-amsterdam/global_styling/variables/_borders.scss, src/themes/eui-amsterdam/overrides/_code.scss, src/themes/eui-amsterdam/overrides/_index.scss
Small PR for EUI Amsterdam theme that adds rounded corners to inline versions of EuiCodeBlock. It is a very subtle change, but gives it a little more personality. I opted not to use `$euiBorderRadius` (6px) and instead used `$euiSizeXS` (4px) because the larger radius made the shape look too much like a pill. 
- ~[ ] Checked for **accessibility** including keyboard-only and …
=> [Amsterdam] Added rounded corners to inline EuiCode

CHANGELOG.md, src/components/toast/__snapshots__/global_toast_list.test.tsx.snap, src/components/toast/_global_toast_list.scss, src/components/toast/global_toast_list.test.tsx, src/components/toast/global_toast_list.tsx
Added the `side` property to `EuiGlobalToastList` to allow the user to place the toasts left or right instead of just the default right
fixes #3435 
@cchaos @chandlerprall
=> Added side property to 'EuiGlobalToastList' 

src-docs/src/views/popover/popover_container.js
Fixes #3608
The constrained popover example broke during its class->function component conversion. The container's ref was not tracked properly, leading to an `undefined` value passed as the container.
=> Fix popover's container constraint example

src-docs/src/views/datagrid/datagrid_example.js
Fixes #3607
- Updated link to `data_grid_types`
- Added info about `onColumnResize`
~~- [ ] Checked for **breaking changes** and …
=> [DOCS] Added info onColumnResize props and updated link to types in EuiDataGrid

src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_editor.tsx
* toggles the editor's CSS `display` between `none` and `block`, instead of unmounting, to preserve undo/redo history
* now prefers `execCommand` to apply tag formatting over setting the field's `value`, as this preserves undo/redo (with a fallback for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1220696 which does not preserve history)
~- [ ] A …
=> Enable undo/redo for markdown editor, apart from firefox

src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx
1. Adds `aria-setsize` and `aria-posinset` attributes to the options (gives accurate sizes and positions to screen readers in virtualized lists)
2. Adds the messages (e.g., "no results found") as an `aria-describedby` to the search field
3. When clicking on an option, it would set focus on the first focusable option. Now, instead, it sets it on the option you clicked which prevents a weird jump and seems to just work better. (**Breaking change:** needed to pass around another function for this)
Reviewer note: Each of these is a single commit if you want to review that way.
~- [ ] Added …
=> More aria attributes for Selectable

src-docs/src/views/markdown_editor/markdown_editor.js, src-docs/src/views/markdown_editor/plugins/markdown_chart.js, src-docs/src/views/markdown_editor/plugins/markdown_tooltip.js, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_format.tsx
Added `onParse` callback to provide stop-the-world error, info messages, and parse results to the consuming application. I've updated the sole markdown example to display this information until we split it up into multiple examples.
Unified immediately stops all parsing and halts, no parsing result is generated. I've added this to the chart plugin, if you have a malformed JSON configuration object e.g. `!{chart{"palette": ,"height":300}}`. As another example, I encountered a parsing failure from one of the 3rd party modules, if you use the malformed tag `!{tooltip[])}`.
If it does fail to parse, the markdown formatter component now renders the markdown string with no processing.
Plugins can also generate info messages which do not prevent further parsing. I've given the checkbox plugin 2, …
=> Pass markdown parse results to application

CHANGELOG.md, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/color_picker/color_palette_picker/color_palette_picker.test.tsx, src/components/color_picker/color_palette_picker/color_palette_picker.tsx
Closes #3615.
This PR extendeds `CommonProps` in `EuiColorPalettePickerPaletteTextProps`, `EuiColorPalettePickerPaletteFixedProps` and `EuiColorPalettePickerPaletteGradientProps` types.
=> Extended CommonProps in EuiColorPalettePicker palettes types

CHANGELOG.md, src/components/basic_table/collapsed_item_actions.tsx
**EuiBasicTable** actions:
Custom actions (i.e., those with their own `render` function) in a collapsed actions menu (i.e., a per-row context menu) should close the context menu popover on click. This was already the default behavior of default actions.
~- [ ] Checked for **accessibility** …
=> [EuiBasicTable] Custom actions in a collapsed actions menu should close popover on click

CHANGELOG.md, src-docs/src/views/accordion/accordion_example.js, src-docs/src/views/accordion/accordion_forceState.js, src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx
Resolves #3594 by allowing `forceState` and `onToggle` to work together as an external state value and update function pair.
When `forceState` is in use `onToggle` will be called with a boolean reflecting the _current_ open/closed state. This might be slightly confusing as standard `onToggle` is called with a boolean reflecting the _new_ open/closed state after click.
=> [EuiAccordion] Allow external control

src/components/markdown_editor/markdown_editor.tsx
Allows the consuming application to pass a `ref` to **EuiMarkdownEditor**, the ref receives an object with the shape `{ textarea, replaceNode }` allowing the app to interact directly with the editor's textarea and also programmatically alter the markdown AST.
I tested both items on the ref by manually altering the existing example, but did not leave any of that test code in place.
=> Add an imperative ref to EuiMarkdownEditor

CHANGELOG.md, src/components/code/_code_block.tsx, src/components/code/code_block.test.tsx
Fixes #3627 
The fullscreen code container's ref wasn't being set in time the `useEffect` fired to set its content. This PR moves that ref into a state variable and creates a separate `useEffect` to fill it. I added a test and verified it fails without the accompanying changes to **EuiCodeBlockImpl**.
Not sure when/how this bug was introduced, I checked the published docs for the previous 2 PRs touching this file, and fullscreen mode works in both. Perhaps there's a difference in React's dev & production builds affecting this? …
=> Fixed EuiCode's fullscreen mode

src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list_item.test.tsx.snap, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_list/selectable_list_item.tsx
1. Adds a couple more keyboard shortcuts 
- <kbd>Home</kbd> to go to top of the list
- <kbd>End</kbd> to go to the end of the list
- <kbd>Space</kbd> as an alias for Enter
2. Adds some instructions to the exclusion states
- Follow up issue #3625
- To do this, now passing in `allowExclusions` into `selectable_list_item`
=> [EuiSelectable] Adding more keyboard shortcuts and screen reader instructions

src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_inmemory_renderer.tsx
* Mutation observer previously wrapped each individual in-memory cell, this has been moved to a single observer wrapping the entire in-memory table
* Less components are rendered in the Virtual DOM hierarchy 
* `onCellRender` callback updated to mutate the values object instead of cloning every time a cell reports a new value
I modified the *in_memory_sorting.js* example and took the timings from the first 3 togglings-on
<details>
<summary>see modified example file</summary>
```
import React, { Fragment, useCallback, useMemo, useState } from 'react';
import { fake } from 'faker';
import { EuiDataGrid, EuiLink, EuiButton } from '../../../../src/components/';
const columns = [
{
id: 'name',
},
{
id: 'email',
},
{
id: 'location',
},
{
id: 'account',
},
{
id: 'date',
},
{
id: 'amount',
},
{ …
```
=> Optimized in-memory datagrid mount performance

CHANGELOG.md, src/components/card/card.tsx, src/components/card/index.ts
The `EuiCardProps` weren't being returned in the `EuiCard` component
Closes #3634 
@chandlerprall @thompsongl
=> Exported `EuiCard` TypeScript types

src-docs/src/views/elastic_charts/theming.js
This PR adds the **EuiColorPalettePicker** to the charts theming docs.
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
=> [Docs] Add EuiColorPalettePicker to charts theming docs

CHANGELOG.md, src-docs/src/views/facet/facet_example.js, src-docs/src/views/facet/facet_layout.js, src/components/facet/__snapshots__/facet_button.test.tsx.snap, src/components/facet/__snapshots__/facet_group.test.tsx.snap, src/components/facet/_facet_button.scss, src/components/facet/_facet_group.scss, src/components/facet/_index.scss, src/components/facet/_variables.scss, src/components/facet/facet_button.tsx, src/components/facet/facet_group.test.tsx, src/components/facet/facet_group.tsx
Allowing user to choose the size of gutter in EuiFacetGroup, by adding gutterSize 
Closes #3621 
@snide We can put different margin for horizontal and vertical, although that might not be of much use and make the sass code redundant, if you like these changes, I'll add the tests :)
=> Allowed variable gutterSize in EuiFacetGroup

CHANGELOG.md, src-docs/src/views/context_menu/context_menu.js, src/components/context_menu/context_menu_panel.tsx
Fixes #3547, in which menu items in an **EuiContextMenuPanel** would become unclickable after animating in. The problem was caused by the applied animation class (e.g., `.euiContextMenuPanel-txOutRight`) that sets `pointer-events: none;` not being removed after the animation end.
This appeared only in Chromium browsers and was likely spurred on by a recent (unknown) change that resulted in a `setState` race condition.
The solution here is to bypass the offending state update by removing it entirely. The `isTransitioning` state flag was nothing more than an analog for the existence of the `transitionType` prop provided by the parent component and updated on the same events. Replacing `isTransitioning` and its `setState` methods with a truthy prop check simplifies logic without changing …
=> [EuiContextMenu] Fix post-transition unclickable menu items

src-docs/src/views/flyout/flyout_complicated.js, src-docs/src/views/modal/modal.js
There are some typos in src-docs. I think ```setSuperSeelctValue``` should be changed to ```setSuperSelectValue```.
~~- [ ] A …
=> [Docs] Fix typo with EuiSuperSelect examples

scripts/release.js
Updates release.js script to check for `VERSION_TYPE` and `NPM_OTP` environment variables before prompting for manual input. This will help support automating future EUI releases.
n/a
=> Add optional support for environment variables to override prompts in release.js

CHANGELOG.md, src-docs/src/views/accessibility/skip_link.js, src/components/accessibility/__snapshots__/skip_link.test.tsx.snap, src/components/accessibility/_screen_reader.scss, src/components/accessibility/index.ts, src/components/accessibility/skip_link.test.tsx, src/components/accessibility/skip_link.tsx
A couple issues arose when trying to use this component in Kibana. 
There was a simple code error where the component's props was not **all** the props. It was referencing just the `EuiSkipLinkProps` instead of the `Prop` one which includes the `PropsForAnchor` and `PropsForButton` props to allow for `onClick` and such. So TS threw an error when trying to add `onClick`
~This prop was required but is too specific to only one possible use case/consuming ability. For instance, Discover's "Skip to bottom of table" button still has an Angular wrapper and so it needed to do the functionality via an `onClick` and not an `href`. I just made this one optional.~
**Update**: Is still required
The browser had a weird state when you couldn't click the button with a mouse when in the focus state. As …
=> [EuiSkipLink] Fix TS types and Safari click issue

CHANGELOG.md, package.json, src/themes/charts/themes.ts, yarn.lock
- upgrade elastic charts to `19.6.3`
- add background.color to eui chart theme
=> Upgrade elastic charts 19.6.3

.ci/jobs/elastic+eui+npm-publish.yml
Adds an ⚠️EXPERIMENTAL⚠️ job to publish a new release to npm using release.js.
For a number of reasons, I am not able to fully test this locally. Not least of which is the fact that actually publishing to npm during my testing is not something I wanted to do.
All that said, I would love to merge this so that it can be run by a member of the EUI team for their next release and see how it goes! If it doesn't fully succeed, we'd just have to do some manual cleanup, like remove tags from the repo and, hopefully this is unlikely, unpublish the package from npm.
n/a
=> CI job to publish a new version of EUI to npm

CHANGELOG.md, src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap, src/components/search_bar/query/ast_to_es_query_dsl.test.ts, src/components/search_bar/query/ast_to_es_query_string.test.ts, src/components/search_bar/query/ast_to_es_query_string.ts, src/components/search_bar/query/default_syntax.test.ts, src/components/search_bar/query/default_syntax.ts
Closes #2325 and closes #3426
* Updated query syntax to allow any character inside double-quoted phrases; `"` and `\` characters must be escaped with a backslash
* Added unit test covering AST->ES DSL generation when a `"` or `\` is present
* Updated AST -> ES querystring conversion and added a unit test to escape `"` and `\` characters
=> Allow any character to be used in Query

src-docs/src/components/with_theme/theme_context.tsx
Fixes #3674 where the docs site fails to load if the theme key in local storage does not exist in the application.
Tested with:
* valid theme key
* invalid theme key
* no value in local storage
=> Fix docs site when local storage theme does not exist

src-docs/src/components/guide_page/guide_page.js, src-docs/src/index.js, src-docs/src/routes.js, src-docs/src/views/button/button_example.js, src-docs/src/views/button/guidelines.js, src-docs/src/views/form_layouts/form_layouts_example.js, src-docs/src/views/form_layouts/guidelines.js, src-docs/src/views/modal/guidelines.js, src-docs/src/views/modal/modal_example.js, src-docs/src/views/text/text_example.js, src-docs/src/views/text_scaling/text_scaling_sandbox.js, src-docs/src/views/toast/guidelines.js, src-docs/src/views/toast/toast_example.js
=> [Docs] Consolidated tabs for Examples-Guidelines-Playground

CHANGELOG.md, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.tsx
Sent `buffer` as 0 in the `EuiSuperSelect` component to avoid extra spacing.
@miukimiu Some ts related error is occurring, maybe y'all can take a …
=> Passed buffer as 0 to fix extra gap in `EuiSuperSelect`

src-docs/src/views/code_editor/code_editor.js
Fixed 'react-ace' problem. When `sandbox` renders `ace` not defined.
=> Fixed 'react-ace' problem

CHANGELOG.md, src-docs/src/views/tables/actions/actions.js, src-docs/src/views/tables/basic/props_info.js, src/components/basic_table/__snapshots__/default_item_action.test.tsx.snap, src/components/basic_table/action_types.ts, src/components/basic_table/default_item_action.test.tsx, src/components/basic_table/default_item_action.tsx
Creates a work-around path for #3679  by expanding **EuiBasicTable**'s default action's `name` to allow any React node.
* updated actions example to include react nodes in action names
* tested aria-label -> aria-labelledby change in Mac VoiceOver + Chrome
* added unit test
This does _not_ fix the bug reported in #3679 where 3+ custom actions will trigger a React warning about nested button elements.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs …
=> Expand table's default action type to allow reactnode names

.ci/jobs/elastic+eui+npm-publish.yml
Can't use Node dependencies if they're not installed! :thinkaboutit:
=> Jenkins needs to install Node dependencies :facepalm:

CHANGELOG.md, src/global_styling/mixins/_form.scss, src/themes/eui-amsterdam/eui_amsterdam_globals.scss, src/themes/eui-amsterdam/global_styling/functions/_index.scss, src/themes/eui-amsterdam/global_styling/index.scss, src/themes/eui-amsterdam/global_styling/mixins/_index.scss, src/themes/eui-amsterdam/global_styling/variables/_index.scss, src/themes/eui/eui_globals.scss, wiki/consuming.md
Consuming apps that want to use our invisibles have to import the functions, mixins, and variable index files separately because importing the `global_styles/index.scss` file comes with the reset and animations (non-invisibles) that would be repeated for each import.
This is too much for the apps to remember, so I made a helper file for the default and Amsterdam themes.
- ~[ ] …
=> SASS globals helper file

src-docs/src/views/selectable/selectable_custom_render.js, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_list/selectable_list_item.tsx, src/components/selectable/selectable_search/selectable_search.test.tsx, src/components/selectable/selectable_search/selectable_search.tsx
Fixes [bug report](https://github.com/elastic/eui/pull/3169#pullrequestreview-438550377) from @cchaos:
> The only thing I felt odd in the functionality was when the list was filtered down from the search box, and an option is selected it loses focus where as it would normally stay focused.
Also fixes [follow-up bug](https://github.com/elastic/eui/pull/3670#issuecomment-651872086) also found by @cchaos of selecting an option after searching would lose focus.
- `options` passed into **EuiSelectable** cannot have an `id` (an `id` is generated internally)
- This feels kind of risky but this wasn't documented as a possibility before so it shouldn't be too bad (out of 23 uses in Kibana, none passed in an `id`)
- Requires an `onChange` to be passed into **EuiSelectableSearch**
- Not meant to be …
=> [EuiSelectable] Focus option after search value change

CHANGELOG.md, src/components/resizable_container/context.tsx, src/components/resizable_container/helpers.ts, src/components/resizable_container/resizable_button.tsx, src/components/resizable_container/resizable_container.tsx
Fixes #3698 
* Fixed the bug reported in #3698 where a nested panel would not resize. The issue came from looking at all resizable buttons in a container instead of only the ones directly used by a container
* Fixed a bug where resizing by arrow keys did nothing in an un-controlled usage
* Fixed a bug which impacted the last docs' example where resizable buttons of different sizes were improperly assumed to be of the same size
Replaced _resizable_container_basic_ with the following for testing:
```
import React from 'react';
import { EuiText, EuiResizableContainer } from '../../../../src/components';
import { fake } from 'faker';
const text = (
<>
<p>{fake('{{lorem.paragraphs}}')}</p>
<p>{fake('{{lorem.paragraphs}}')}</p>
<p>{fake('{{lorem.paragraphs}}')}</p>
</>
);
export default () => ( …
```
=> Multiple bug fixes for resizable container

src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap, src/components/markdown_editor/_markdown_editor.scss, src/components/markdown_editor/_markdown_editor_drop_zone.scss, src/components/markdown_editor/_markdown_editor_footer.scss, src/components/markdown_editor/_markdown_editor_preview.scss, src/components/markdown_editor/_markdown_editor_text_area.scss, src/components/markdown_editor/_markdown_editor_toolbar.scss, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_drop_zone.tsx, src/components/markdown_editor/markdown_editor_footer.tsx, src/components/markdown_editor/markdown_editor_text_area.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx
This PR adds better styles and class names for the **EuiMarkdownEditor**. 
* Now the markdown styles look better in all screen sizes, including mobile. Not perfect but better.
* The `classNames` are now aligned with other EUI components.
* Replaced the toolbar that was using the `EuiFlexGroup` and `EuiFlexItem` with custom CSS.  …
=> [EuiMarkdownEditor] Better styles and class names

CHANGELOG.md, src/components/steps/_steps_horizontal.scss
This PR closes #3704. 
The **EuiHorizontalSteps** numbers were rendering over a fixed **EuiHeader**: https://codesandbox.io/s/brave-lake-s4r7f?file=/index.js
To ensure the connecting lines stay behind the number a z-index of `$euiZLevel0` was given to the lines and the numbers received a z-index of `$euiZLevel1`. But `$euiZLevel1` is too high `1000`. 
Because we only want to make the lines saying behind the number it makes sense to give a z-index to numbers just a little bit higher than the lines. So `$euiZLevel0 + 1` seems a good solution to me.
- ~[ ] Added …
=> Fix EuiHorizontalSteps rendering over EuiHeader

package.json, scripts/babel/fetch-i18n-strings.js, src/components/markdown_editor/index.ts, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_drop_zone.tsx, src/components/markdown_editor/markdown_editor_footer.tsx, src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_types.ts, src/components/markdown_editor/plugins/markdown_checkbox.tsx, src/components/markdown_editor/plugins/markdown_tooltip.tsx, src/components/markdown_editor/unified-plugins.d.ts, yarn.lock
Adds and corrects types within the markdown editor and its dependencies.
* Upgraded a couple packages to versions with types
* Added a .d.ts file for missing dependency types
* Resolved all of markdown's `@ts-ignore` directives except for two places where a JS svg component is imported
* Resolved the parse error types
=> Add types to markdown editor

.ci/jobs/elastic+eui+npm-publish.yml, package.json, scripts/release.js, yarn.lock
Adds argument parsing to release.js so we can set a `--type` arg (major, minor or patch) instead of using a `VERSION_TYPE` env var, and adds a `--steps` arg (comma-separated list of release steps) so that we can run the first half of the release, then fetch MFA creds at the very last second before publishing to npm and finishing other post-release steps.
(I kept `NPM_OTP` an env var instead of converting it to an argument to make it easy to not leak the token into the public CI job logs.)
Also added a `--dry-run` flag so that you can test `npm run release` without actually making any public changes.
=> Break up release.js

CHANGELOG.md, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.tsx
Fixes #3727 by re-focusing the super select's button after a value change. Tested selection by both mouse and keyboard. I'm not really happy with using `querySelector` to get at the underlying button, but adding `forwardRef` to the super select control gets messy because of its props' generic, and I couldn't get a satisfactory version working. Please push on that if you feel it shouldn't go in as-is.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs …
=> Re-focus EuiSuperSelect input after making a value change

CHANGELOG.md, src-docs/src/views/tables/actions/actions.js, src-docs/src/views/tables/basic/props_info.js, src/components/basic_table/__snapshots__/default_item_action.test.tsx.snap, src/components/basic_table/action_types.ts, src/components/basic_table/collapsed_item_actions.test.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/default_item_action.test.tsx, src/components/basic_table/default_item_action.tsx
Per #3679, `item.name` needed to be expanded to allow for a function returning a `ReactNode` in addition to a `ReactNode. The callback function accepts the row `item` as a parameter.
=> [EuiTable] Expand item action name to allow a function

.ci/jobs/elastic+eui+npm-publish.yml
Just what it says on the tin: we need some valid ssh keys before we can push new tags back to Github.
This work required some changes to workers in kibana-ci to ensure `/usr/local/bin/ssh-add-from-vault` exists. That config change should be applied sometime in the next few hours if it hasn't already.
Once this is merged, we should be clear to attempt another automated release!
=> Add ssh keys so new tags can be pushed to Github from Jenkins

src-docs/src/views/flyout/flyout.js, src-docs/src/views/flyout/flyout_banner.js, src-docs/src/views/flyout/flyout_complicated.js, src-docs/src/views/flyout/flyout_example.js, src-docs/src/views/flyout/flyout_large.js, src-docs/src/views/flyout/flyout_max_width.js, src-docs/src/views/flyout/flyout_small.js, src-docs/src/views/modal/modal_example.js, src-docs/src/views/popover/popover.js, src-docs/src/views/popover/popover_block.js, src-docs/src/views/popover/popover_container.js, src-docs/src/views/popover/popover_example.js, src-docs/src/views/popover/popover_fixed.js, src-docs/src/views/popover/popover_htmlelement_anchor.js, src-docs/src/views/popover/trap_focus.js, src-docs/src/views/tool_tip/tool_tip_example.js
1. Fixes a link in modal docs to the guidelines
2. Moves all flyout and popover examples and snippets to use `ownFocus` with a section about not using it (instead of the reverse)
3. Adds a11y notes to when and how to best use tooltips
I am not a wordsmith. Would welcome any all improvements on this.
=> [Docs] Adding more acccessibility-focused notes and examples

src-docs/src/views/datagrid/styling.js
Clicking both buttons on https://eui.elastic.co/#/tabular-content/data-grid-styling-and-toolbar demo brings up partially hidden popups because their z-index is too low. Increasing by one seems to do the trick.
=> Fix zIndex for two popup ups

CHANGELOG.md, src/test/find_test_subject.ts, src/test/take_mounted_snapshot.ts
Noticed during Kibana upgrade prep that certain uses of `findTestSubject` require more explicit prop typing (`ReactWrapper<MyComponentProps>` vs `ReactWrapper<{}>`). This expands two functions in EUI's test utils to be accept `any` props.
~- [ ] Checked for **accessibility** including …
=> Expand `findTestSubject` utility type

CHANGELOG.md, src/components/form/form_row/form_row.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list_item.tsx
Fixes two regressions caused by the recent [selectable-a11y branch](https://github.com/elastic/eui/pull/3169).
1. Adding <kbd>space</kbd> as a option for how to selection items removes the ability to have items with <space> in them so reverting this change.
2. With the new `react-window` library replacing `react-virtualized`, this in conjunction with **EuiFormRow** was causing an extra rerender on click of virtualized elements which broke clicking... Adding a check in **EuiFormRow** for if the thing needs to rerender fixes it.
~- [ ] Added …
=> [EuiSelectable+EuiComboBox] recent regresion fixes

CHANGELOG.md, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx
The `ListProps` interface applies to the `FixedSizeList` component, which both come from`react-window`. EUI uses `FixedSizeList` and applies all required props. EUI's layered-on `windowProps` prop allows consumers to pass any additional props directly to `FixedSizeList`, but intended to do so on an optional basis.
The solution is to add `Partial<>`
This change is required for type_check passing in Kibana. …
=> [EuiSelectable] Partial ListProps type

CHANGELOG.md, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
Fixes #3791 
Turns out a very long search/custom value in the combobox triggers a `scroll` event on the input itself. This is not captured by the options list, and causes the list box to close. When the input has focus but the list box is closed, the input is considered invalid.
~- [ ] Checked for **accessibility** including keyboard-only …
=> Prevent combobox from complaining about long search values

package.json
Closes #3397
Marks EUI's *.css and *.scss files as having sideEffects when they are imported by webpack. Setup I tested with:
<details>
<summary>package.json</summary>
```
{
"name": "test",
"version": "1.0.0",
"main": "index.js",
"license": "MIT",
"dependencies": {
"@babel/core": "^7.10.5",
"@babel/preset-env": "^7.10.4",
"@babel/preset-react": "^7.10.4",
"@elastic/datemath": "^5.0.3",
"@elastic/eui": "^27.2.0",
"babel-loader": "^8.1.0",
"css-loader": "^4.0.0",
"lodash": "^4.17.19",
"moment": "^2.27.0",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"style-loader": "^1.2.1",
"webpack": "^4.44.0",
"webpack-cli": "^3.3.12",
"webpack-dev-server": "^3.11.0"
}
}
```
</details>
<details>
<summary>webpack.config.js</summary>
```
const path = require('path');
module.exports = {
mode: 'production', …
```
=> enable webpack sideEffects for css and scss files

src/components/markdown_editor/_markdown_editor_text_area.scss
Just a small Firefox fix. There was this weird margins on top and bottom of the `<textarea />`.  
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guideli …
=> [EuiMarkdownEditor] Fixed firefox textarea margin

src-docs/src/views/code_editor/custom_mode.js, src-docs/src/views/code_editor/read_only.js
Fixes #3810
* Fixed the Read Only link by moving the EUI import above brace
* Fixed the Custom Mode link by moving the EUI import above brace and importing the github theme
=> Fixed EuiCodeEditor Read Only and Custom Mode code sandbox links

CHANGELOG.md, src/components/button/_button.scss, src/components/button/button_empty/_button_empty.scss
Removed the `pointer-events: none` in both `EuiButton` and `EuiButtonEmpty` to not override the `pointer-events` in the button mixin `euiButtonContentDisabled`.
Issues: #3818
=> Remove 'pointer-events:none' for EuiButton&EuiButtonEmpty

CHANGELOG.md, src/components/pagination/pagination.tsx
Fix for #3826.
```js
if (compressed) {
const firstPageButtonCompressed = (
<PaginationButton pageIndex={activePage} inList={false} />
);
const lastPageButtonCompressed = (
<PaginationButton pageIndex={pageCount} inList={false} />
);
}
```
EuiPagination was passing one based `pageCount` prop to PaginationButton's `pageIndex` prop directly, which is zero based, which caused wrong page count when used with `compressed`.
=> [EuiPagination] Fixed wrong page count with `compressed`

src-docs/src/services/playground/iconValidator.js, src-docs/src/services/playground/index.js, src-docs/src/views/badge/playground.js, src-docs/src/views/button/playground.js, src-docs/src/views/call_out/playground.js
https://github.com/elastic/eui/pull/3722#discussion_r456082936
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentatio …
=> [Playground] Created iconValidator util

src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src/components/index.js, src/components/markdown_editor/index.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_format.tsx, src/components/markdown_editor/plugins/markdown_default_plugins.tsx
Moves the default parsing&processing plugin arrays behind a constructor function, which prevents consumers from mutating the defaults & cross-polluting/leaking between apps.
=> Prevent markdown plugin extensions from interacting with each other

CHANGELOG.md, src/components/datagrid/_data_grid.scss
Significant improvement of performance issues encountered in #3705. Screens taken using Chrome 83, MacBook Pro 15'' 2019 on a retina screen, rendering 100 rows. 
Before:
After:
Important: pls test on a retina/high resolution monitor, there the lag is significant, and also the improvement
~- [ ] Checked for **breaking changes** and labeled …
=> [DataGrid] Add will-change to CSS to improve performance in chrome full screen mode

CHANGELOG.md, scripts/dtsgenerator.js
Fixes #3849 by configuring our _eui.d.ts_ generation to exclude `src-docs/**/*`
Tested by running `node scripts/dtsgenerator.js` and inspecting the generated file.
I also verified all there are no other entires outside of the _src_ path with regex search `module '@elastic/eui/(?!src)` - with the sole exception of `@elastic/eui/dist/eui_theme_*.json` which is expected to be present.
=> Remove src-docs files from eui.d.ts modules

src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src-docs/src/views/markdown_editor/markdown_plugin_example.js, src/components/markdown_editor/plugins/markdown_checkbox.tsx, src/components/markdown_editor/plugins/markdown_default_plugins.tsx, src/components/markdown_editor/plugins/markdown_tooltip.tsx
Implements the recently-added `unknownHandler` option in the remark->rehype plugin, removing the need for custom (but the same) handlers which were confusing and easy to misconfigure. The opportunity to provide a custom remark->rehype node handler is maintained.
=> Simplify the markdown editor's plugin API

src-docs/src/views/form_layouts/form_rows.js
See issue https://github.com/elastic/eui/issues/3863 for more context & discussion
This PR uses `useRef` to wrap the call to htmlIdGenerator instead of wrapping the checkbox definitions inside of `useState`. 
Heads up--I checked the calls to htmlIdGenerator and it looks like there are more situations that could use this swap but due to the amount and that we only discussed this instance, I kept my scope to this form. No priority, just wanted to let you know!
~- [ ] Props have proper **autodocs**~ props didn't change
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)**~ This was a documentation example fix, no functional changes
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelo …
=> Wrap htmlIdGenerator in useRef

wiki/consuming.md
I ran into that issue and found out that the docs here are regarding the location of eui_globals outdated.
Looks like it was named `global` and now it's named `globals`.
=> Fix reference to eui_globals in consuming.md

src-docs/src/views/markdown_editor/markdown_editor.js, src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src-docs/src/views/markdown_editor/markdown_plugin_example.js, src/components/markdown_editor/markdown_actions.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_editor_drop_zone.tsx, src/components/markdown_editor/markdown_types.ts
Settled on keeping a distinction between a Formatting object & string to represent changes. The formatting objects, used by a plugin's UI button to directly modify the text, are used when the change is _presentational_ e.g. bold, italic. Our extended markdown formats, like the chart plugin's JSON insertion, do not interact with the text/presentation but are brand new values, so no custom formatting rules make sense. I think that's a fair (and good) distinction.
* Added license information for markdown tag formatting code
* Added support for markdown insertion to be block-level (testable via the chart plugin example and drag&drop)
* Corrected a documentation bug
=> [Markdown] Support for markdown block text insertion

src-docs/src/services/playground/dummyFunction.js, src-docs/src/services/playground/index.js, src-docs/src/views/accordion/accordion_example.js, src-docs/src/views/accordion/playground.js, src-docs/src/views/badge/playground.js, src-docs/src/views/card/playground.js, src-docs/src/views/toast/playground.js, src-docs/src/views/tool_tip/playground.js
=> [Playground] EuiAccordion

CHANGELOG.md, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_data_grid.scss, src/components/datagrid/data_grid.tsx
Fixes https://github.com/elastic/eui/issues/3878
Related to https://github.com/theKashey/react-focus-on/pull/47 , our focus trap solution didn't accept `style` props. Regardless, it accepts `className` and we should use that instead.
=> Fix datagrid not fitting into containers

src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src/components/markdown_editor/index.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/markdown_types.ts, src/components/markdown_editor/plugins/markdown_default_plugins.tsx
Built EUI with the markdown editor & attempted the reproduce the chart plugin example, found some missing/incomplete types. Made these changes, rebuilt & confirmed in a create-react-app that they make the plugin example usable.
=> Fix externally-needed markdown editor types

src-docs/src/views/empty_prompt/empty_prompt_example.js, src-docs/src/views/empty_prompt/playground.js
=> [Playgorund] EuiEmptyPrompt

CHANGELOG.md, package.json, src/components/focus_trap/__snapshots__/focus_trap.test.tsx.snap, src/components/focus_trap/focus_trap.test.tsx, yarn.lock
Fixes #3795 by updating to the latest `react-focus-on`, which [now has support for passing through `style` prop](https://github.com/theKashey/react-focus-on/releases/tag/v3.5.0). Behavior is now the same as when `react-focus-lock` was used directly.
=> [EuiFocusTrap] accept `style` prop

src/components/toggle/toggle.tsx
The `div.onChange` prop needs to be properly removed before the override `onChange` can get picked up by the docgen script.
=> [EuiToggle] Fix `onChange` prop type override

CHANGELOG.md, src/components/datagrid/data_grid.tsx
Fixes #3880 
`DataGridContext` has been dependent on the `pagination` prop, so any re-renders of an EuiDataGrid+pagination (or its parent) has been triggering all cells to re-render. There's no need for that context to be pagination-dependent, so that has been removed.
I also verified a datagrid with no pagination continues to work as expected …
=> Don't re-generate DataGridContext from pagination

src/components/expression/expression.tsx
Props are not displayed for EuiExpression. It was missed in #3554 
~~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/docum …
=> Fixed prop not displaying for EuiExpression

CHANGELOG.md, src/components/focus_trap/focus_trap.testenv.tsx
The [most recent EUI upgrade](https://github.com/elastic/kibana/pull/74004) in Kibana [increased Jest test flakiness](https://github.com/elastic/kibana/issues/74814) and ultimately exposed [recently changed EuiFocusTrap dependencies](https://github.com/elastic/eui/pull/3631) to significantly lengthen unit test run times (leading to timeout-based failures).
This PR introduces a testenv mock for EuiFocusTrap which will prevent library internals from unnecessarily interfering with downstream unit tests.
The effective result in Kibana is up to 85% faster runs in affected unit tests, 0 behavioral changes, and surprisingly few snapshot updates. 
~- [ ] Checked in **Chrome**, …
=> Add test-env mock for EuiFocusTrap

CHANGELOG.md, src/components/table/_table.scss
In some cases the max-height of a table row needs to be more than 1000px when expanded - for example when the table contains a large sub-table. I tried setting `100% { max-height: max-content}`, but the expansion animation was not smooth, so instead added a two step animation -- to 1000px at 90%, and to `max-content` at 100%.   I do not know if `max-content` is the right choice here, not an expert TBH.
Fixes #3854 …
=> [EuiBasicTable] Fix limited expandable row height

src/components/form/select/select.tsx
Fixes #3933 
- Add `value` props to `EuiSelectProps`
- Verified generation of prop in props page
~~- [ ] A …
=> Add value props to EuiSelect props

CHANGELOG.md, src/components/side_nav/_side_nav_item.scss
Replaces https://github.com/elastic/eui/pull/3926 which was already approved by @cchaos  
Minor change to the sidenav coloring to make it more consistant for navs in their various open / close states. The current setup over-assumes that you'll be using open states as a location reference. This might be something we want to change based on a prop, but in general I think this way is a more consistent default.
When working with trees where you force them open to show heigharchy, you'd wonder why the coloring was highlighted differently.
=> Make sidenav coloring more consistant for open nodes

scripts/babel/react-docgen-typescript.js
Fixes a bug in the docs' props generation, where TypeScript notices a prop with the union `boolean | number | string` overlaps the named `Primitive` type from https://github.com/elastic/eui/blob/f937facb3f7647c5c9cacb146436d472082f651f/src/services/sort/comparators.ts#L23 and uses that name instead of the expanded union.
One example is **EuiFlyout**'s `maxWidth` prop:
/cc @cchaos who brought this up
~- [ ] …
=> Force rename/expansion of Primitive type -> boolean | number | string in docs

CHANGELOG.md, src-docs/src/views/search_bar/controlled_search_bar.js, src/components/form/field_search/field_search.tsx, src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
Fixes #3950 
**EuiFieldSearch** did not include its `defaultValue` prop (inherited from `InputHTMLAttributes`) when generating its value state. **EuiSearchBox** provides the initial query value to the search field via`defaultValue`.
* updated **EuiFieldSearch** to respect `defaultValue`
* updated **EuiSearchBar**'s _Controlled search bar_ example to set an initial query for better usage demonstration
=> Update EuiFieldSearch to show a clear button when defaultValue is present

src-docs/src/views/guidelines/writing.js
Notes that field help text should always end with a period, even if it's only a sentence fragment.
=> [Guidelines] Clarify punctuation rules for help text

package.json, scripts/babel/react-docgen-typescript.js, src/components/markdown_editor/markdown_editor.tsx, yarn.lock
Makes progress on #3056 
- Updated react-docgen-typescript
- Show ref as  a prop in props tab if component is a forward ref component
=> Ref in props tab for froward ref components

CHANGELOG.md, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/matching_options.ts, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_option.tsx, src/components/selectable/selectable_search/selectable_search.tsx, src/components/selectable/selectable_templates/selectable_template_sitewide.tsx
Fixes #3966, where the addition of a generic extension of `EuiSelectableOption` needed to be further propagated to all aspects of `EuiSelectable` and related components. More types and components accept a generic (defaulted to `{}`).
To aid TypeScript parsing, the `id` prop was more explicitly restricted (`never` instead of `Omit`, which could have been reinstated with the new generic).
Tested in Kibana with expected updates flagged
=> Update and expand use of EuiSelectable option type generic

CHANGELOG.md, src/global_styling/mixins/_button.scss
When showing a button in RTL, margin-left/right shows up incorrectly. The needed CSS seems to be `margin-inline-start/end`.  Partially relates to #3960 
Those values do not exist in IE, so not sure if we can introduce these or not just yet.  I tested these changes with a search bar's filters and `EuiHeaderLink` with icons.
english | current RTL | desired RTL 
---|---|---
The above changes can be achieved with this CSS override.
```css
.euiButtonContent > * + * {
margin-left: unset;
-webkit-margin-start: 8px;
margin-inline-start: 8px; }
.euiButtonContent--iconRight > * + * {
margin-left: unset;
margin-right: unset;
-webkit-margin-start: 0;
margin-inline-start: 0;
-webkit-margin-end: 8px;
margin-inline-end: 8px; }
.euiFacetButton__content > * + * {
margin-left: unset;
-webkit-margin-start: …
```
=> [WIP][rtl][css] Fix button margins for RTL langs

src-docs/src/views/toast/toast_example.js
No major changes, just found a typo and fixed it 😄
=> [Docs] Fix link to toast usage guidelines

src/components/side_nav/_side_nav.scss
=> Fixes docs page navbar showing only in homepage in mobile

CHANGELOG.md, src/components/expression/__snapshots__/expression.test.tsx.snap, src/components/expression/expression.test.tsx, src/components/expression/expression.tsx
Fixes #4007 
- Made value prop field not required
=> [EuiExpression] Allow the use of descriptions only

CHANGELOG.md, src/components/combo_box/_combo_box.scss, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_input/combo_box_input.tsx
Fixes: #3852
- Add loading icon to EuiComboBox input when isLoading is true.
~~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs examples`~~
=> [EuiComboBox] Added loading icon to combobox input

scripts/release.js
Delays import of `nodegit` during release, as it isn't used in CI, and causes environmental issues there.
=> Delay import of nodegit

src-docs/src/components/guide_section/guide_section.js
`raw-loader` was upgraded in #4022 which changed the result of `require`ing to an ESModule format instead of returning the default export. This PR accesses updates the guide component to add `.default` when accessing the string value.
A more correct change would be to update every instance of `require('!!raw-loader!` to `import from '!!raw-loader!` but that
1. introduces an eslint warning
2. requires an automated change to every single example file
These should be solvable, but I'm opting for a quick fix to get the DemoJS tabs working again before going down the more complex path.
~- [ ] Props have proper …
=> Update DemoJS docs tab processing to match new raw-loader import format

CHANGELOG.md, src/components/date_picker/super_date_picker/super_date_picker.tsx
Fixes #4025 
- EuiSuperDatePicker update button only shows if the value is changed.
Before:
After:
=> [EUISuperDatePicker] Show update button only if the value is changed

CHANGELOG.md, src/components/image/__snapshots__/image.test.tsx.snap, src/components/image/image.test.tsx, src/components/image/image.tsx
Fixed #4032: Moved nested button out to prevent event propagation that trigger the activation of full screen mode
=> Fixed EuiImage deactivate fullscreen event propagation

CHANGELOG.md, src/components/badge/badge.tsx
Fixed #4031: Allowed `onClick` prop when `href` prop is provided in `EuiBadge`
=> Allowed onClick prop in conjunction with href prop in EuiBadge

CHANGELOG.md, src-docs/src/views/context_menu/context_menu_example.js, src-docs/src/views/context_menu/context_menu_with_content.js, src/components/context_menu/__snapshots__/context_menu.test.tsx.snap, src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap, src/components/context_menu/context_menu.test.tsx, src/components/context_menu/context_menu.tsx, src/components/context_menu/context_menu_item.tsx, src/components/context_menu/context_menu_panel.tsx, src/components/horizontal_rule/horizontal_rule.tsx, src/components/horizontal_rule/index.ts
This is a Proof-of-Concept for line separator that we need for https://github.com/elastic/kibana/issues/66051
=> [EuiContextMenu] Add line separator as menu item

src-docs/src/components/codesandbox/link.js, src-docs/src/views/code/code_block.js, src-docs/src/views/code/playground.js, src-docs/src/views/package/changelog.js
More places affected by the `raw-loader` upgrade. This time I searched for !!raw-loader and inspected every use outside of an *_example.js* file - where the import's `default` is handled in another way.
Fixes:
* https://elastic.github.io/eui/#/forms/form-controls Demo JS tab
* https://elastic.github.io/eui/#/editors-syntax/code **Code block** section
* https://elastic.github.io/eui/#/editors-syntax/code/playground - Playground tab, first example reads "[object Module]"
* https://elastic.github.io/eui/#/package/changelog 🤦
=> clean up raw-loader imports in a few places

src-docs/src/views/toast/toast_list.js
Fixes #2790 
- Fixed documentation issue of using number as toast id.
~~- [ ] A …
=> [DOCS] EuiGlobalToastList Use string instead of number for toast id

CHANGELOG.md, src/components/text/text_color.tsx
Fixes #4057: Override the `color` prop inherit from the `HTMLDivElement` and `HTMLSpanElement`
=> Fixed EuiTextColor props

CHANGELOG.md, src/themes/eui-amsterdam/overrides/_call_out.scss
We decided to remove border radius on EuiCallout because there were some situations where the callout looked very similar to the new hollow button style.
=> [EuiCallout] Remove border radius from Amsterdam

src-docs/src/views/tree_view/tree_view_example.js
Added aria-label to EuiTreeView snippet for easier copy-paste from snippet experience. As aria-label parameter is required, so copy-paste from EuiTreeView snippet before this change gives a TypeScript error.
=> Add aria-label to EuiTreeView snippet

package.json, src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/components/scroll_to_hash.tsx, src-docs/src/index.js, yarn.lock
I've been thinking about what I was trying to solve with moving our docs to static. One of the things was the **deep linking to EUI doc sections**.
Because moving the docs to static (does it even make sense?) or using the elastic docs might take some time I'm just checking if this PR could be an option to solve this issue.
This PR introduces:
* A fragment URL like `/navigation/button#flush-empty-button`. By clicking to any nav subsection an hash with the subsection ID is added to the end of the URL. But it's also possible to pass directly the URL to the address bar.
* When the URL changes we check if it contains a `fragment URL`. If yes,  the page scroll to that ID element. If not it scrolls to the top. 
- …
=> [Docs] Add fragment URL

src-docs/src/index.js
After a few attempts here's my solution to prevent encoded URLs with a section ID like [https://eui.elastic.co/pr_4069/#/navigation/button%23ghost](https://eui.elastic.co/pr_4069/#/navigation/button%23ghost ) to fail in Chrome and other browsers.
I'm checking if the pathname contains a `%23` which is the encoded #. If it contains I'll decode it and redirect the URL to it. 
Feel free to find better solutions! 🎉  …
=> [Docs] Prevent encoded urls with a section ID to fail

src-docs/src/views/package/changelog.js
Remove the `master` section from the docs' changelog rendering. It's pretty meaningless in local development and misleading in the published version.
=> Remove 'master' section of changelog in docs

CHANGELOG.md, src/themes/eui-amsterdam/global_styling/variables/_typography.scss
This PR fixes an unintended (i think?) consequence of reducing `$euiFontSize` to `14px` which caused `EuiTitle` to use line-heights that increment in units of `7px` (42, 35, 28, 21). I think we should keep `EuiTitle` line-heights as they are in the base theme so that they increment in units of `8px` (48, 40, 32, 24).
Since our `lineHeightFromBaseline` function references `$euiFontSize` and divides it by 2, changing the font size variable caused our baseline to increment in units of `7px` (14 / 2 = 7) for `EuiTitle`. 
`EuiTitle` is the only component that uses the `lineHeightFromBaseline` function. Because EuiTitle is used in so many places, this `7px` increment throws a lot of components off of our imaginary grid. This can cause elements to align in weird ways, for example:
It also feels …
=> Fix EuiTitle lineheight

CHANGELOG.md, src-docs/src/views/button/button_empty_flush.js, src-docs/src/views/button/button_example.js, src-docs/src/views/card/card_checkable.js, src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap, src/components/button/button_empty/_button_empty.scss, src/components/button/button_empty/button_empty.tsx, src/components/card/checkable_card/_checkable_card.scss, src/components/form/field_search/_field_search.scss, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/dual_range.tsx, src/components/form/range/range.tsx
**Mostly stylistic fixes...**
Closes #4012. Made this a priority to help the Core UI (@MichaelMarcialis).
This spacer was only supposed to show when the input is being displayed inline. The logic wasn't correct though, which made it always show unless it was the input with dropdown style.
The current padding affording for the clearable icon wasn't also affording for being mixed with `isLoading` and `compressed` states. This adds more mixin usages for these states.
I saw this usage in Kibana where a checked card was also disabled but the blue border was too prominant.
So this PR simply moves the addition of the blue border to only occur if the item is checked but not disabled.
- ~[ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs …
=> A couple fixes for 7.10

src-docs/src/views/tables/in_memory/in_memory_search_section.js
Linked the In-memory table example with search bar to the search bar syntax docs.
[Link of issue](https://github.com/elastic/eui/issues/4061)
This is my first PR. Let me know if you have any feedback!
=> In-memory table docs linked to search bar (#4061)

CHANGELOG.md, src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
There're 2 issues that I discovered in EuiComboBox. 
The first issue is the miscalculation of `height` when the `rowHeight` prop is used.
This is because the list container uses the class `euiComboBoxOptionsList__rowWrap`, which has a `max-height` of `200px`. I added a condition to limit the height of `react-window` to `200px` and updated the snapshot as well. 
This also fixes a small visual issue: With the default rowHeight set to `29px`, the list height was `203px` (7 visible options * 29) which was actually pushing the bottom arrow of the scrollbar down by 3px.
---
The second issue is only relevant when `singleSelection` is used. The selected option isn't focused or scrolled to if we didn't use the `options` variable to reference the selected value. 
This is because the …
=> [EuiComboBox] Fix rowHeight and singleSelection focus issues

CHANGELOG.md, src-docs/src/views/tables/in_memory/in_memory_search.js, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/in_memory_table.test.tsx, src/components/basic_table/in_memory_table.tsx
Fixes #4095 
- Added a prop `childrenBetween` to add components between search bar and table
- Added tests
=> [EuiInMemoryTable] Added ability to insert component between the searchbar and the table

src-docs/src/views/i18n/i18n_example.js, src-docs/src/views/i18n/i18n_interpolation.js
Added minimal documentation for value interpolation via `Eui18n` and `useEuiI18n`. An additional example of component interpolation could also be added here if required (as requested in #4044). I was unsure if it would be preferred to add a new section + examples, or combine that example into my existing one. This additional example would highlight that passing components as values (to interpolate a `EuiButton`, or `strong` tag, for example) works. Please let me know what's preferred.
Closes #3835
Related to #4044
=> docs: i18n interpolation

wiki/component-development.md
Update wiki to reflect changes to the Kibana testing docs. elastic/kibana#79878 introduced a `bootstrap` flag that will again allow for using the `npm pack` method
=> [wiki] Update Kibana testing docs

src/components/markdown_editor/markdown_editor.test.tsx
Makes progress on #3908 
- Add more tests for EuiMarkdownEditor
=> [EuiMarkdownEditor] Add more tests

src-docs/src/views/collapsible_nav/collapsible_nav_all.tsx, src-docs/src/views/elastic_charts/category_chart.js, src-docs/src/views/elastic_charts/pie_alts.js, src-docs/src/views/elastic_charts/sparklines.js, src/components/token/token.tsx
While I'm also bought into the larger goal of removing lodash completely, these changes are a halfway house towards that goal. With these changes, only used lodash modules should (I'm unsure how to verify this) end up in the `eui` bundle.
> const throttle = require('lodash/throttle'), only the subset of lodash code your package uses will be bundled in projects that use your package.
> [Reference](https://lodash.com/per-method-packages)
Part of https://github.com/elastic/eui/issues/360
=> Import minimal lodash packages

package.json, scripts/babel/react-docgen-typescript.js, src-docs/webpack.config.js, yarn.lock
Fixes the out-of-memory error on recompile in dev, this was caused by the `react-docgen-typescript` script building a new TS program before the previous one had been GCed. I also added the `cacheDirectory` configuration to `cache-loader` so we get cache locally in the _.cache-loader_ directory once again.
=> Fix out-of-memory in dev server; re-configure cache-loader

CHANGELOG.md, src/components/button/button_group/_button_group.scss
In the recent Kibana upgrade it was found that some nested congregation of different display positions of elements can cause a weird overflow issue when used in conjunction with EuiButtonGroup and the EuiScreenReaderOnly component.
This is a quick fix by adding `position: relative` to the EuiButtonGroup to ensure the `absolute` positioned EuiScreenReaderOnly elements are positioned against **it** and not some other relative parent.
- ~[ ] …
=> [EuiButtonGroup] Fix position for EuiScreenReaderOnly

wiki/consuming.md
To piggy back off of the conversation from #3896. I've updated the consuming doc to better explain between importing just the global vars to iterate on top of the EUI theme, vs overriding the default theme colors.
=> Updated Consuming doc for SASS

src-docs/webpack.config.js
Based on @myasonik's [stack trace](https://github.com/microsoft/vscode-eslint/issues/1055#issuecomment-718051933) the vscode+eslint hangup comes from the synchronous port assignment for the dev server. How? eslint -> eslint-import-resolver-webpack -> webpack.config.js -> getPortSync. Presumably, vscode is calling eslint rapidly which is exhausting the defined port range (8030-8130) and causing subsequent runs to hang. This PR modifies the webpack config to only choose a port when the `WEBPACK_DEV_SERVER` envvar is set to `true`.
=> Fix vscode + eslint hanging

CHANGELOG.md, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/column_actions.tsx, src/components/datagrid/column_sorting_draggable.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_header_cell.tsx, src/components/datagrid/data_grid_header_row.tsx
Came up again in #4197 but also reported in slack last week, the recently added column actions used placeholder copy for sort text instead of using the column schema's labels.
I opted to nest the existing i18n'd labels (`A-Z`, `High-Low`) into a new i18n token which prepends `Sort `. I think this combines the best of re-usability while retaining flexibility for downstream consuming applications. I confirmed these overrides work as expected (see below).
```
i18n={{
mapping: {
'euiColumnSortingDraggable.defaultSortAsc': 'Going down',
'euiColumnSortingDraggable.defaultSortDesc': 'Going up',
'euiDataGridSchema.currencySortTextAsc': 'Increasing',
'euiDataGridSchema.currencySortTextDesc': 'Decreasing',
},
}}
```
```
i18n={{
mapping: {
'euiColumnSortingDraggable.defaultSortAsc': 'Going down', …
```
=> [EuiDataGrid] use schema sorting labels instead of placeholder value

CHANGELOG.md, src-docs/src/views/image/float.js, src-docs/src/views/image/image_example.js, src/components/image/__snapshots__/image.test.tsx.snap, src/components/image/_image.scss, src/components/image/image.test.tsx, src/components/image/image.tsx, src/components/text/_text.scss
Adds props for `float` and `margin` to `EuiImage`. This is needed for long-form text content, like documentation where an image compliments the text in an article format.
TODO:
- Drop floats on mobile
=> Add floats to EuiImage

CHANGELOG.md, src/components/form/__snapshots__/form.test.tsx.snap, src/components/form/form.test.tsx, src/components/form/form.tsx
This PR adds the accessibility labels to the `EuiCallOut` used in `EuiForm` to show the validation errors. More details in https://github.com/elastic/kibana/issues/43000.
=> [EuiForm] Add a11y labels to the EuiCallOut for validation errors

CHANGELOG.md, src/components/selectable/selectable.tsx
Resolves `onChange` issue in searchProps as mentioned in https://github.com/elastic/eui/issues/4132
=> [EuiSelectable] call searchProps functions on search/change

CHANGELOG.md, src/components/combo_box/_combo_box.scss, src/components/combo_box/combo_box_input/_combo_box_placeholder.scss
Addresses the following issue in the `security_solution` plugin's UI: https://github.com/elastic/kibana/issues/81284
Basically there's a bunch of comboboxes which have long placeholders, and here's how it looks like:
I added a quick fix: truncation with CSS.
http://localhost:8030/#/forms/combo-box
Before:
After:
- ~[ ] Checked for **accessibility** …
=> [EuiComboBox] Truncate long placeholder text with ellipsis

CHANGELOG.md, src-docs/src/views/tables/in_memory/in_memory_search.js, src-docs/src/views/tables/in_memory/in_memory_search_external.js, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/in_memory_table.tsx
When `childrenBetween` was added, it also added a conditional spacer between it and the search bar (keeping the spacer that existed before the table). The main consumer for needing teh `childrenBetween` doesn't want this spacer/wants to manually handle this spacing that exists between the children and the table.
This PR, moves the pre-existing spacer to only display if the search bar exists and after the search bar (before the children). So if consumers addd any `childrenBetween` they will need to add their own spacer between it and the table.
The only possible implications with this change is that it does now make the pre-existing spacer conditional upon the presence of the search bar. So if consumers were using the EuiInMemoryTable **without search**, it did have a large spacer between …
=> [EuiInMemoryTable] Remove spacer after `childrenBetween`

CHANGELOG.md, src/components/popover/popover.tsx
Fixes #4247 
**EuiPopover** uses a mutation observer to detect when its content's dimensions may have changed. One watched mutation occurs when the **EuiFormRow**'s label loses its `isFocused` class name. For some reason, when this resize handling occurs in response to the user tabbing the call stack looks like:
```
[React handling tab event]
MutationObserver
EuiPopover::positionPopoverFixed
EuiPopover::positionPopover
EuiPopover::setState
ReactClientsideEffect::componentDidUpdate
ReactClientsideEffect::emitChange
ReactFocusLock::handleStateChangeOnClient
ReactFocusLock::activateTrap
```
Introducing a `setTimeout` before `positionPopover` calls `setState` avoids the setState from triggering the ReactClientsideEffect lifecycles.
This is not a long-term fix, but should hold the component …
=> Prevent EuiPopover's focus lock from resetting during element tabbing

CHANGELOG.md, src/components/datagrid/column_selector.tsx, src/components/datagrid/column_sorting.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/index.ts, src/components/datagrid/style_selector.tsx
Exports the `useDataGridColumnSelector`, `useDataGridColumnSorting`, and `useDataGridStyleSelector` hooks from datagrid. This was asked for by @XavierM to help unify the UX in the security timeline, as the full **EuiDataGrid** does not support their row renderer need.
There was not a great way to export these on the **EuiDataGrid** object, mostly because of TypeScript, so I renamed the hooks for clarity.
I did not write documentation. I'm unsure how we want to document hooks and will bring this up with the team in our weekly discussion.
/cc @kertal this might be interesting for Discover's re-implementation of some of the popover experiences.
~- [ ] Checked in **Chrome**, …
=> Export some datagrid hooks

CHANGELOG.md, src/components/datagrid/_data_grid_column_resizer.scss
The rightmost cell header resize element was overlapping the header menu, so it was difficult to click this element. This PR resizes the width of this element to prevent this overlapping.
Before:
After:
Fixes #4233
~- [ ] Checked for **accessibility** including …
=> [EuiDataGrid] Fix size of rightmost cell resizer

CHANGELOG.md, src/components/index.js
Previous PR (#4271) didn't export the hooks from _src/components/index.js_ - turns out that's a necessary step. I'll make a follow-up release after this merges.
=> Actually export the datagrid hooks 🤦‍♂️

CHANGELOG.md, src-docs/src/views/form_compressed/form_compressed_example.js, src-docs/src/views/form_compressed/form_compressed_popover.js, src/components/button/button_group/_button_group.scss
By removing the `transition: all` on the `.euiButtonGroup__buttons` selector. This was safe to remove because no interaction states were directly applied to this selector. It was probably leftover from before the a11y fix.
Also added an example to the compressed forms page.
**Before**
**After**
=> [EuiButtonGroup] Fix initial focus when in a popover

CHANGELOG.md, src/components/selectable/selectable.tsx
Fixes the issue described in https://github.com/elastic/eui/issues/4262. In short, passes the latest component state to the `searchProps.onChange` callback.
=> fix(selectable): use latest state in onChange

CHANGELOG.md, src-docs/src/views/color_picker/color_palette_display.js, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/_combo_box.scss, src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx, src/components/date_picker/_date_picker.scss, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/_super_select.scss, src/components/form/super_select/super_select.tsx, src/components/popover/_popover.scss, src/global_styling/mixins/_popover.scss, src/themes/eui-amsterdam/global_styling/reset/_reset.scss, src/themes/eui-amsterdam/overrides/_date_picker.scss, src/themes/eui-amsterdam/overrides/_index.scss, src/themes/eui-amsterdam/overrides/_popover.scss
This allowed me to remove a lot of placement logic that was already present in EuiInputPopover.
Instead of duplicating styles and the increase in maintenance, I've copied the `euiPopover__panel` classes onto the EuiPanel within EuiComboBox to help maintain consistency of styles. I've added a comment in the code indicating that in a future re-factor of this component, it should just straight up use the EuiPopover component.
Also fixed the scrollbar and extra height issues.
This animation was just too much when it would end up connected to the input. So I only added the transition if the `attached` class doesn't exist.
**Before**
**After**
This one was overlooked during the form updates. There's still more work to do on the datepicker itself, but this just fixes the immediate.
The picker …
=> Fix dropdown styles in Amsterdam

CHANGELOG.md, src/components/index.js, src/components/selectable/index.ts, src/components/selectable/selectable.tsx, src/components/selectable/selectable_search/selectable_search.test.tsx, src/components/selectable/selectable_search/selectable_search.tsx
Fixes #4277
This PR does two things:
1. Export `euiSelectableTemplateSitewideRenderOptions` so that consumers can customize the `renderOption` around it while still using the same option component
- This enables Kibana to customize the `searchValue` that gets passed in to control highlighting
2. Allow `isPreFiltered` to be passed into the component and pass it along to the sorting function. (The sorting function already supported this flag but there was no way to use it.)
- This avoids some sorting work in EUI, which allows Kibana to roll in advanced searching using some basic queries.
Also tested changes in Kibana confirming everything works.
- ~[ ] Checked in **Chrome**, …
=> [EuiSelectable] export SiteWideRenderOptions and wire-up `isPreFiltered`

wiki/component-development.md
Update the wiki to provide information on testing changes in Kibana. When running `yarn build` & `npm pack` more than once, the name of the resulting `.tgz` needs to be change each time. Otherwise `yarn` does not see the package as updated and uses the cached version.
=> [Docs] npm pack update recognition

src-docs/src/views/tables/in_memory/in_memory_section.js
The first sentence of the description for `In-memory tables` located [here](https://elastic.github.io/eui/#/tabular-content/in-memory-tables) is either missing a word or has an extra word. 
Currently, the sentence reads:
"The `EuiInMemoryTable` is a higher level component wrapper around `EuiBasicTable` that aimed at displaying tables data when all the data is in memory."
This PR enacts the smallest possible adjustment to the sentence for it to make sense by removing the word "that" from the sentence.
It would now read:
"The `EuiInMemoryTable` is a higher level component wrapper around `EuiBasicTable` aimed at displaying tables data when all the data is in memory."
=> [Docs] Update in_memory table with friendly spellcheck

CHANGELOG.md, src/components/collapsible_nav/_variables.scss
Allow for overriding collapsible nav SASS vars. Fixes #4334 
=> Add !default to all EuiCollapsibleNav SASS variables

CHANGELOG.md, src/themes/eui-amsterdam/overrides/_index.scss, src/themes/eui-amsterdam/overrides/_list_group_item.scss
- [Amsterdam] Adjust font size for size M of `EuiListGroupItem`
=> [EuiListGroupItem] Increase font size of size M in Amsterdam

src-docs/src/views/tables/mobile/mobile_section.js
The code example used in the responsive tables section on this [page](https://elastic.github.io/eui/#/tabular-content/tables) has a missing comma after the width: '100%' attribute.
This pr adds that comma in to make the code valid.
=> [Docs] Fix typo in table mobile options code example

CHANGELOG.md, src-docs/src/views/datagrid/datagrid.js, src/components/datagrid/column_selector.tsx, src/components/datagrid/data_grid_header_cell.tsx
- Datagrids now use `displayAsText` column prop as a heading (#4114). Will use `display` over `displayAsText`, and `displayAsText` over `id`.
- Column search now compares input against the `displayAsText` column prop (#4204). Will still use `id` if `displayAsText` was not provided.  
Other than changelog, I don't think any of these apply; I thought I'd wait for a review before editting the changelog. Should I add a test or two?
=> [EuiDataGrid] Use `displayAsText` for column sort search and columns headers

CHANGELOG.md, src/components/combo_box/combo_box.tsx, src/components/popover/popover.tsx
Fixes #4306, in which an EuiComboBox inside an EuiPopover would close both the options list _and_ the popover when hitting <kbd>escape</kbd>. Adds additional logic to the key press handler.
The reason for the change is the move to having `react-focus-on` (via EuiFocusTrap) handle <kbd>escape</kbd> (previously EuiFocusTrap had its own logic). `react-focus-on` attaches the `onKeyDown` event to the `document` and uses `!event.defaultPrevented` as its  prevention logic.
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md) …
=> [EuiComboBox, EuiPopover] Update `esc` logic

CHANGELOG.md, src/themes/eui-amsterdam/overrides/_index.scss, src/themes/eui-amsterdam/overrides/_range.scss, src/themes/eui-amsterdam/overrides/_tooltip.scss
- Reduce padding in `EuiToolTip` and therefore overall size to better align with smaller font size.
- Reduce `EuiRange`'s tooltip border-radius
=> [Amsterdam] Small styling adjustments in tooltips

CHANGELOG.md, src-docs/src/services/playground/simulateFunction.js, src-docs/src/views/steps/playground.js, src-docs/src/views/steps/steps.js, src-docs/src/views/steps/steps_complex.js, src-docs/src/views/steps/steps_example.js, src/components/steps/__snapshots__/step.test.tsx.snap, src/components/steps/__snapshots__/step_horizontal.test.tsx.snap, src/components/steps/__snapshots__/step_number.test.tsx.snap, src/components/steps/__snapshots__/steps.test.tsx.snap, src/components/steps/__snapshots__/steps_horizontal.test.tsx.snap, src/components/steps/_step_number.scss, src/components/steps/_steps.scss, src/components/steps/_steps_horizontal.scss, src/components/steps/_variables.scss, src/components/steps/index.ts, src/components/steps/step.tsx, src/components/steps/step_horizontal.tsx, src/components/steps/step_number.tsx, src/components/steps/step_strings.tsx, src/global_styling/mixins/_button.scss, src/global_styling/mixins/_helpers.scss, src/themes/eui-amsterdam/global_styling/variables/_index.scss, src/themes/eui-amsterdam/global_styling/variables/_steps.scss, src/themes/eui-amsterdam/overrides/_index.scss, src/themes/eui-amsterdam/overrides/_steps.scss
Also updated the docs a bit too.
Closes #3339
Closes #4322 
We aligned the styles between Vertical and Horizontal steps and removed center line indicators.
---
1. A few of the props are then obsolete in Amsterdam as they're overridden by the overall style of the `status`. I've marked these as `**DEPRECATED IN AMSTERDAM**`.
2. The previous design would not render the number if the step is `incomplete`, while the new one does. I ended up changing this to always render the number but hide visually in the default theme.
=> [EuiSteps] Updates for Amsterdam and added `disabled` and `loading` states

CHANGELOG.md, src/components/datagrid/_data_grid_header_row.scss, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid_header_cell.tsx
It adds a sorting indicator on the EuiDataGridColumn which renders only when the column is sorted and indicates the sorting direction.
=> [EuiDataGrid] Add sorting icon if the column is sorted

CHANGELOG.md, src-docs/src/views/datagrid/column_cell_actions.js, src-docs/src/views/datagrid/datagrid_styling_example.js, src/components/datagrid/data_grid_cell.tsx, src/components/datagrid/data_grid_cell_buttons.tsx, src/components/datagrid/data_grid_cell_popover.tsx, src/components/datagrid/data_grid_types.ts
Allow a custom cell action to close the popover manually.
The original request in Data table vis replacement -> https://github.com/elastic/kibana/pull/70801#issuecomment-737082772
The desired result:
=> [Data Grid] Added closePopover action to EuiDataGridColumnCellActionProps

CHANGELOG.md, src/components/list_group/__snapshots__/list_group_item.test.tsx.snap, src/components/list_group/list_group_item.test.tsx, src/components/list_group/list_group_item.tsx
Fixes #4355, where it was discovered that `isDisabled` on the item `extraAction` config was not used/was overwritten by the item-level `isDisabled` prop.
=> [EuiListGroupItem] Respect `isDisabled` on `extraAction` config

CHANGELOG.md, package.json, src-docs/src/views/link/link_example.js, src-docs/src/views/link/link_validation.js, src/components/badge/badge.tsx, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/button/button.tsx, src/components/button/button_empty/button_empty.tsx, src/components/button/button_icon/button_icon.tsx, src/components/card/card.tsx, src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap, src/components/context_menu/context_menu_item.tsx, src/components/control_bar/__snapshots__/control_bar.test.tsx.snap, src/components/header/header_logo.tsx, src/components/key_pad_menu/key_pad_menu_item.tsx, src/components/link/link.tsx, src/components/list_group/list_group_item.tsx, src/components/markdown_editor/plugins/markdown_default_plugins.tsx, src/components/markdown_editor/plugins/markdown_link_validator.test.tsx, src/components/markdown_editor/plugins/markdown_link_validator.tsx, src/components/side_nav/side_nav_item.tsx, src/components/tabs/tab.tsx, src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, src/services/security/href_validator.test.tsx, src/services/security/href_validator.tsx, yarn.lock
Closes #4331 
https://eui.elastic.co/pr_4362/#/editors-syntax/markdown-editor
Look how only the valid urls get rendered as links, and the rest render their text. Ooooh. Ahhhh. Valid markdown links start with http:/https: or a forward slash.
https://eui.elastic.co/pr_4362/#/navigation/link#link-validation
**EuiLink** docs updated with a section on the validation. I [Chandler] initially planned on creating a new prop to disable the validation, but with React planning on similarly removing this functionality I'm going to be optimistic that no one will miss having this option available. In contrast to markdown's validation which only allows a small approved list of url patterns, the href validation only prevents `javascript:`.
Components affected:
~- [ ] Check against **all themes** for …
=> [EuiMarkdownEditor] Add a markdown link validator

src-docs/src/views/link_wrapper.js, src/components/table/table_pagination/table_pagination.tsx
Updates the docs' link interception routing to only match against urls starting with `#/`, instead of `#`. This was caught in the data grid examples where the previous implementation broke their pagination.
~- [ ] A …
=> Fix doc to not intercept hash links

CHANGELOG.md, src/components/date_picker/super_date_picker/quick_select_popover/_commonly_used_time_ranges.scss, src/components/date_picker/super_date_picker/quick_select_popover/_index.scss, src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss, src/components/date_picker/super_date_picker/quick_select_popover/commonly_used_time_ranges.tsx, src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx
Fixes #4226 
Changed to `EuiFlexGrid` view in `Recently used date ranges` under `EuiRecentlyUsed` component.
- ~[x] Props have proper **autodocs**~ 
- ~[x] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)**~
- ~[x] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs examples~
- ~[x] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**~
- ~[x] Checked for **breaking changes** and labeled appropriately~
=> [EuiSuperDatePicker]Changed to `EuiFlexGrid` view in `Recently used date ranges`

CHANGELOG.md, src/components/context/context.tsx, src/components/i18n/i18n_util.test.tsx, src/components/i18n/i18n_util.tsx, src/components/tree_view/tree_view.test.tsx, src/components/tree_view/tree_view.tsx
Fixes #4323 
Changed `label` PropType in tree_view to `ReactNode`
=> [EuiTreeView] [EuiTreeViewNode] changed label PropType in tree_view to ReactNode

CHANGELOG.md, src-docs/src/views/super_date_picker/super_date_picker.js, src/components/date_picker/super_date_picker/_super_date_picker.scss
I have removed "max-width:100%" from this className
This is because we are giving "margin:-4px" and it is creating some margin in right when we put "max-width:100%" but after removing, it is working fine.
Here is the screenshot of before and after the change.
Before:
After:
=> Spacing issue resolved #4263

CHANGELOG.md, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.test.tsx, src/components/popover/popover.tsx, src/services/popover/popover_positioning.ts
Fixes #4414 
Added support for adjusting `buffer` for individual window sides.
=> [EuiPopover] Allow adjusting `buffer` for individual window sides.

src-docs/src/views/markdown_editor/markdown_editor_errors.js
Hey, this is my first pull request. It fixes issue #4275 and required a very small change. All I had to do was replace the Link Component with an anchor tag.
The Link component from **react-router-dom** was breaking the code.
I also deleted the line that imported the Link component from **react-router-dom** because it wasn't being used anywhere else in that file.
Since it was such a small change, I didn't have to check all the checkboxes, checked all the ones I thought would be relevant to my change.
If my request does not meet your standards, or it breaks the app in any way, I would really like some advice or suggestions on how I could improve it so that I could continue contributing to this project in the future.
To be more clear, the anchor tag here is added by me.
=> Fixed an issue caused by using Link component instead of anchor (a)  tag

CHANGELOG.md, src/components/form/form_control_layout/_form_control_layout.scss
Fixes #4407
Fixed icons' and buttons' sizes in append/prepend in `EuiComboBox`
=> [EuiComboBox] Fixed icons' and buttons' sizes in append/prepend

CHANGELOG.md, src-docs/src/views/form_controls/select.js, src/components/form/select/select.test.tsx, src/components/form/select/select.tsx
Closes #4427 by adding logic for **EuiSelect[hasNoInitialSelection]** to reset to its hidden empty **option** if it receives a `value={undefined}`.
=> [EuiSelect] allow select's value to be reset with an undefined value

CHANGELOG.md, src/components/combo_box/_combo_box.scss
The initial fix for #4407 was reverted in #4432. This new PR fixes #4407.
=> [EuiComboBox] Fixed prepend and append heights

CHANGELOG.md, src/components/focus_trap/focus_trap.test.tsx, src/components/outside_click_detector/outside_click_detector.test.tsx, src/components/outside_click_detector/outside_click_detector.ts
Closes #4422 by hiding the implementation details of **EuiOutsideClickDetector** event manipulation and allowing standard event types in prop parameters.
`onOutsideClick` now accepts `Event` rather than requiring `EuiEvent`
=> [EuiOutsideClickDetector] Accept standard event types

wiki/documentation-guidelines.md
_Note that is is merging to `cchaos-patch-1`_
Minimal documentation for steering contributors towards playground examples and understanding potential cases. Not intended to focus on starting from scratch (i.e., a new component), but instead when adding or modifying props on existing components that have a playground tab present.
=> [Docs] Playground wiki

CHANGELOG.md, src-docs/src/views/resizable_container/resizable_container_basic.js, src/components/resizable_container/resizable_container.tsx
Fixes a problem discovered in https://github.com/elastic/kibana/pull/86934.
EuiResizableContainer is initially hidden (`display: none;`) and overlaid with a loading screen while data is loaded. When the data is loaded, the visualization is rendered onto a target DOM element via `ref` reference inside the EuiResizablePanel. EuiResizableContainer is mounted at this point but rerenders when it becomes visible and gains calculable size dimensions. That rerender changes/remounts the target `div` and alters the `ref`, effectively disconnecting the visualization from the DOM.
The solution is to not initialize EuiResizableContainer until it is visible/has calculable dimensions. There are likely other ways to solve this problem in the implementation (e.g., not using`display: none;`; watching for …
=> [EuiResizableContainer] Initialize after DOM is ready

.github/pull_request_template.md, wiki/documentation-guidelines.md
=> Added playground to the PR checklist

CHANGELOG.md, src-docs/src/views/combo_box/combo_box.js, src/components/badge/badge.tsx
Fixes #4273 by adding `type=button` to the "remove" button on the EuiBadge items rendered by EuiComboBox.
The problem comes from the default button `type=submit` being triggered when <kbd>Enter</kbd> was hit on an input element in a form with `onSubmit`/`action`.
> What should happen? The onSubmit handler of the form should be triggered, the combo box should not react at all
This is half true. The combobox should indeed not react, but the form should not submit without a `type=submit` element in the form. [The spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission) says that in a form with no submit buttons, implicit submission will be done if only one input is present.
So you can see in the to-be-reverted docs change that the combobox no longer …
=> [EuiBadge] Add button type to prevent form submission

CHANGELOG.md, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_body.tsx
Solves the worst offender in https://github.com/elastic/eui/issues/4458
Fixes the horizontal scrolling issues that the grid has when it full-screen. It has some performance issues at present that @chandlerprall is gonna check into (see comment below, it might be fine).
=> [DATA GRID] Fix fullscreen scrolling issues

CHANGELOG.md, src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.tsx
Signed-off-by: Akash Gupta <akashgp9@gmail.com>
This PR Fixes #3765 
Handling invalid color entry passed to EuiBadge color prop
=> [EuiBadge] : Handle invalid color entry

src-docs/src/views/datagrid/virtualization.js, src-docs/src/views/datagrid/virtualization_constrained.js
Resolves an item in #4495
Two datagrid virtualization examples generated a combined 20000 rows of fake data when any doc page loaded, taking about 6 seconds to do so. I've updated these 2 problematic examples to instead generate the rows on-demand.
=> Don't generate 20000 rows of fake data when loading the docs

src-docs/src/views/datagrid/column_actions.js, src-docs/src/views/datagrid/column_cell_actions.js, src-docs/src/views/datagrid/column_widths.js, src-docs/src/views/datagrid/control_columns.js, src-docs/src/views/datagrid/styling.js
Faker has trouble with images. Remove it to fix a visual bug and drop to initials in the avatar column
=> [Docs] Remove avatar image from dg example

CHANGELOG.md, src/components/code/__snapshots__/_code_block.test.tsx.snap, src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/code/_code_block.tsx
A fix for https://github.com/elastic/kibana/issues/89490
Related to https://github.com/elastic/eui/issues/3385 but doesn't address some of the bigger/broader questions and fixes one specific instance.
=> Make tabbable codeblocks if content overflows

CHANGELOG.md, package.json, scripts/a11y-testing.js, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.tsx, src/components/table/mobile/__snapshots__/table_sort_mobile.test.tsx.snap, src/components/tour/__snapshots__/tour_step.test.tsx.snap, src/components/tour/tour_step.tsx, yarn.lock
This PR Fixes: #4436 
Migrated deprecated dependency `axe-puppeteer v1.1.1` to `@axe-core/puppeteer v4.1.1`
**Note:**
Fixed one accessibility error that occured after migrating to `@axe-core/puppeteer v4.1.1`
Now all a11y tests are passing :
~~-[ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs examples~~
=> [Chore] : Migrated axe-puppeteer to @axe-core/puppeteer

CHANGELOG.md, src/components/flyout/flyout.tsx
This PR Fixes #2894 
Fixed `onClose` invoking with unexpected parameter in `EuiFlyout`
=> [EuiFlyout] - Fixed `onClose` invoked with unexpected parameter

CHANGELOG.md, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_body.tsx
Fixes https://github.com/elastic/eui/issues/4457
I'm surprised it was that easy, but it works fine for the cases I tested (maybe I missed some?). This PR makes sure the vertical scroll bar is taken into account on auto-sizing data grid columns.
To do so, it's simply looking up the `clientWidth` property of the virtualization container instead of the width of the wrapper container as a reference width. To guard against unforeseen race conditions, it's falling back to the container width if that doesn't work for some reason.
~- [ ] Added …
=> Data grid: Take scrollbar into account

CHANGELOG.md
Follow up to #4448.
By mistake, I didn't open the PR #4448 against the `feature/notification` branch but in `master`. So this PR includes the missing CL.
- ~[ ] Props have proper **autodocs** and **[playground toggles]~(https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-playground-toggles)** …
=> Update changelog to include EuiFlyout paddingSize PR

src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/_accordion.scss, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap
Closes #4224 by adding a `tabIndex={-1}` to the accordion's children wrapper and calling `.focus()` when it expands.
This is a draft because I added `outline: 1px solid blue;` to the focus state on `.euiAccordion__childWrapper` and would like help finding the right style to apply.
=> Shift focus to accordion content when expanded

CHANGELOG.md, src-docs/src/components/guide_page/guide_page.js, src-docs/src/views/tabs/playground.js, src-docs/src/views/tabs/tabs.js, src-docs/src/views/tabs/tabs_example.js, src/components/tabs/__snapshots__/tabs.test.tsx.snap, src/components/tabs/_tabs.scss, src/components/tabs/_variables.scss, src/components/tabs/tabs.test.tsx, src/components/tabs/tabs.tsx, src/themes/eui-amsterdam/overrides/_index.scss, src/themes/eui-amsterdam/overrides/_tabs.scss
This PR is to align the styles of EuiTabs with the latest from the Amsterdam design assets. The main problem we had was that the smaller (`14px`) font size affected both the medium and small sizes of tabs. This is actually good for maintaining font size consistency, but we had needs for a larger set as well. One that bumped the font size back up to `16px`.
What the results are is that:
Tab size | Default theme | Amsterdam theme
------------ | ------------- | ------------
`s` | `14px` | `14px`
`m` | `16px` | `14px`
`l` | `16px` | `16px`
This might seem weird on the surface that only `medium` (default) tab font sizes are different across themes, but this is intentional. And this affects both the default and `condensed` displays.
**Default theme**
**Amsterdam theme**
- ~[ ] Checked for …
=> [EuiTabs] Add large size

package.json
Avoids including a [yellow list licensed dependency in Kibana](https://github.com/elastic/open-source/blob/master/elastic-product-policy.md#yellow-list) by correctly moving @axe-core/puppeteer out of dependencies into devDependencies.
=> Move @axe-core/puppeteer to devDeps

CHANGELOG.md, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.tsx
According to these two links:
- https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance
- https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
The best way to enhance animations in the browser is with `will-change` but adding this statically to class in CSS is costly so it's best to add it via JS only on instantiation. Luckily, we already were applying a `style` prop to the EuiPopover panel only when mounted so it was an obvious place to add this property.
**before**
https://user-images.githubusercontent.com/549577/108101213-eb2b9d80-7054-11eb-8e91-2ab9e052ca40.mp4
**after**
https://user-images.githubusercontent.com/549577/108101230-ef57bb00-7054-11eb-92ca-73fe94d78320.mp4
- ~[ ] Props have proper **autodocs** and **[playground …
=> [EuiPopover] Added `will-change` via JS to help with fuzzy animation

CHANGELOG.md, src/components/datagrid/_data_grid.scss
This reverts the background color of the data grid content. Although the light gray works well for loading states, it isn't a good experience for fixed height grids with a low amount of items. We'll solve the loading issue in a better way in 7.13. I'm leaving the scrollbar mixin as is because I think it will be useful in other spots. 
=> Revert grid background color

CHANGELOG.md, src/global_styling/mixins/_form.scss, src/global_styling/reset/_reset.scss, src/themes/eui-amsterdam/global_styling/reset/_reset.scss
@gjones Brought to our attention that the text of filled, disabled inputs on Safari did not have proper contrast. Apparently, in Safari, there is a special `-webkit-` prefix for applying `color` to disabled text of inputs. ☹️ 
So based on [this SO](https://stackoverflow.com/questions/262158/disabled-input-text-color), I've forced `opacity` (for iOS) in the reset files, then applied the disabled text `color` in the Sass mixin to the `-webkit-` prefix.
**Before**
**After**
- ~[ ] Checked **[Code …
=> Fixed disabled text styles in Safari (and iOS)

CHANGELOG.md, src/components/form/checkbox/__snapshots__/checkbox.test.tsx.snap, src/components/form/checkbox/checkbox.test.tsx, src/components/form/checkbox/checkbox.tsx, src/components/form/radio/__snapshots__/radio.test.tsx.snap, src/components/form/radio/radio.test.tsx, src/components/form/radio/radio.tsx, src/components/form/switch/__snapshots__/switch.test.tsx.snap, src/components/form/switch/switch.test.tsx, src/components/form/switch/switch.tsx
This PR Fixes #3660 
Added `labelProps` prop to EuiSwitch, EuiRadio and EuiCheckbox.
- data test subject can be added now.
- x ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-playground-toggles)**
=> Added `labelProps` prop to [EuiSwitch, EuiRadio, EuiCheckbox] 

src/components/color_picker/color_stops/index.ts, src/components/color_picker/index.ts, src/components/index.js
Rolling back `index.js` to just before #4517 merged.
A build should not have any output in the form of:
```
WARNING in ./components/color_picker/index.ts 23:0-66
"export 'EuiColorStopsProps' was not found in './color_stops'
@ ./components/index.js
@ ./index.js
```
=> Remove type exports from index.js

CHANGELOG.md, src/components/selectable/selectable.tsx
This PR Fixes:  #4553 
Removed Home and End Key configured behavior of moving focus to first and last option of the list.
Pressing `HOME` key moves focus to first Element of the list and pressing `END` key moves focus to the last ELement of the list.
Pressing `HOME` key places the cursor on the first character and pressing `END` key places the cursor after the last character.
~~- [ ] Added or updated **[jest …
=> [EuiSelectable] Removed Home and End Key configured behavior

wiki/component-development.md
Small update to the docs on how to link EUI to Kibana:
- removes a reference to the days when we had two different ways to do it
- adds a new step that (maybe?) isn't necessary all the time but is simple enough and has blocked several people now
=> Add more docs on how to run a local version of EUI in Kibana

scripts/babel/react-docgen-typescript.js
Should dramatically help protect against the too-many-file-watchers we see on some CI runs. Also helps reduce memory usage & speed up dev server start time. Logging the array of folders/files chokidar is watching, the line count of `JSON.stringify(chokidarWatcher.getWatched(), null, 2)` went from 4472 lines to 1013
=> Limit dev-server watched files to only TS/TSX

scripts/babel/fetch-i18n-strings.js
due to the script did not support i18n multi-value lookup feature, some i18n token missing in the docs, 
e.g. `euiColorPicker.openLabel`
=> some i18n tokens missing in the docs

.github/workflows/changelog.yml
This adds a Github Action based on a [published Github action](https://github.com/marketplace/actions/changelog-enforcer) that will check for an edit to `CHANGELOG.md`. It checks every time you push, similar to our other CI items. It can be skipped by using the `skip-changelog` label.
I've tested this scenario a couple times on a private repo. Yell if you want to see a demo. I thought about removing the CL checklist item, but I think it's still a good way to surface the link to the changelog.
=> Add Github action to check for changelog edits

CHANGELOG.md
This is just something that bugged me for a while. I've removed all the ending periods before the () parenthetical PR references.
=> Fixing inconsistency of period usage in Changelog

package.json
Increases `start-server-and-test`'s timeout from 5 minutes (default) to 10 minutes. This is a bandaid to help CI executions, I'm sure we can find ways to decrease build times rather than accepting the current times.
How I got here:
First thought the timeout was coming from puppeteer, and tried recreating the error by decreasing pupeeter's timeout but got a different error. Looking at the CI stacktrace closer, it appeared to be from `start-server-and-test` itself. Pulled up that docs, saw the default timeout of 5 minutes matches the time passed in CI between command & error, and successfully triggered that error locally with a timeout of 10ms.
=> Increase start-server-and-test timeout to address CI timeouts

src-docs/src/views/emotion/canopy.tsx, src/components/common.ts, src/services/index.ts, src/services/theme/README.md, src/services/theme/context.ts, src/services/theme/hooks.tsx, src/services/theme/index.ts, src/services/theme/provider.tsx, src/services/theme/types.ts, src/services/theme/utils.test.ts, src/services/theme/utils.ts
Allows for extending a theme object with custom properties (including top-level sections).
Custom properties will be computed 1) after all "standard" theme values have been computed and 2) in the order they are defined. This means that they will have access to all computed values and can have computational dependencies just like standard theme properties.
=> [CSS-in-JS] Support extensions via overrides prop

src-docs/src/views/collapsible_nav/collapsible_nav_example.js, src-docs/src/views/comment/comment_example.js, src-docs/src/views/elastic_charts/pie_example.js, src-docs/src/views/markdown_editor/mardown_editor_example.js, src-docs/src/views/markdown_editor/mardown_format_example.js, src-docs/src/views/markdown_editor/markdown_plugin_example.js, src-docs/src/views/resizable_container/resizable_container_example.js, src-docs/src/views/text_diff/text_diff_example.js, src-docs/src/views/tour/tour_example.js
We've kept some of these **NEW** badges on a little too long so I've cleaned up the usages to remove them from any that were applied more than 6 months ago. This pretty much wiped out **all** the badges since the youngest one was 7 months old. 
**Are there any components we **missed** putting the `isNew` badge **on**?**
There's been talk about creating some automatic timer for these, but I didn't feel like going down that rabbit hole at the moment. I just wanted to clean up the usages before the next release that will contain the docs layout redesign.
=> [Docs] Removed all `isNew` declarations on components over 6 months old

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid_body.tsx
Closes #4514. Instead of falling back to 500x500 height/width when rendering the datagrid within Jest, now using `Number.MAX_SAFE_INTEGER`. Tried first with `Infinity` but the values are passed in a `style` object which doesn't support `Infinity`.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs …
=> [EuiDataGrid] Update jest environment rendering to include all cells

.github/workflows/changelog.yml
I believe this will prevent the warning emails when merging PRs into `master`
=> Prevent the changelog check from running on commits to master

CHANGELOG.md, src/components/index.js
Fixes #4595 by removing `EuiPageSideBarProps` and `EuiPageTemplateProps` exports from _src/components/index.js_ as they are TypeScript definitions and removed from the transpiled code.
I confirmed with `BABEL_MODULES=false yarn webpack --config=src/webpack.config.js` that these are the only two such exports.
=> Don't export TS types from JS files

CHANGELOG.md, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.tsx
Draft mode as I've only tested this in Chrome on Mac, but otherwise ready for review.
Fixes #4574. Caroline noticed that the `will-change` style on the popover panel broke the `display: fixed` usage by drag&drop. This update dynamically adds `will-change` only during the popover's initial open animation, removing it after any transitions/animations have finished.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works …
=> [EuiPopover] Don't apply willChange to popover after it is done opening & animating

CHANGELOG.md, src/components/index.js
Removes an additional exported type identified in https://github.com/elastic/eui/pull/4597#issuecomment-789284284. This one wasn't reported during a webpack build presumably because its source file does `export * from` compared to the explicit `export { ComponentProps}` pattern which exported the others. This is the last occurrence of `props` in _src/components/index.js_.
Looked into making CI fail if webpack issued the warning about an unknown import but decided against for a few reasons:
* looks like it requires adding a plugin e.g. https://www.npmjs.com/package/fail-on-errors-webpack-plugin
* we'd have to shoe-horn it into the CI environment for `dist` build or devserver+axe configurations, which is brittle
* final conversion of index.js->TypeScript will need to handle this in an …
=> Remove EuiPageSideProps from src/components/index.js export

CHANGELOG.md, src-docs/src/routes.js, src-docs/src/views/app_view.js
This PR Fixes: #4585 
Added the ability to navigate through the docs pages using the left/right keyboard arrows.
[Discussion](https://github.com/elastic/eui/commit/8d29c3115db72529a9a5d206328a6c027556b4d2#diff-a3e37e779466cbffa21938778433d0ce534a612da61784a6596511b7fb4a44fe)
~~- [ ] Checked for **breaking …
=> [Docs] Added the ability to navigate through the docs pages using keyboard arrows

src/components/inner_text/inner_text.test.tsx, src/components/tool_tip/tool_tip.test.tsx
Replace `sleep` with ` jest.useFakeTimers` and `jest.advanceTimersByTime`.
Hoping to fix the often-seen flaky test failure related to [EuiToolTip focus timeout](https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/3440/console):
>12:45:48 FAIL src/components/tool_tip/tool_tip.test.tsx
12:45:48   ● EuiToolTip › shows tooltip on focus
12:45:48 
12:45:48     expect(received).toMatchSnapshot()
12:45:48 
12:45:48     Snapshot name: `EuiToolTip shows tooltip on focus 1`
12:45:48 
12:45:48     - Snapshot
12:45:48     + Received
12:45:48 
12:45:48       <span
12:45:48         class="euiToolTipAnchor"
12:45:48       >
12:45:48         <button
12:45:48     -     aria-describedby="id"
12:45:48           data-test-subj="trigger"
12:45:48         >
12:45:48           Trigger
12:45:48 …
=> [EuiToolTip, useInnerText] Use jest.useFakeTimers for flaky tests

CHANGELOG.md, src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss
Fixes #4472.
@chandlerprall explained how to reproduce the problem and why it is happening 
https://github.com/elastic/eui/issues/4472#issuecomment-790043390
To test it on the docs page, use devtools to manually remove enough elements so that only 1 `EuiComboBox` is left, then mimic the clip shared in the issue. …
=> [EuiComboBox] Fixed options list misalignment

src-docs/src/views/color_picker/color_stops.js
Fixed: Standard, Random & Fixed Examples are using same state.
Issue Link:-  Closes https://github.com/elastic/eui/issues/4609
=> [EuiColorStops] Fixed: Standard, Random & Fixed Examples are using same state

CHANGELOG.md, src-docs/src/views/image/float.js, src-docs/src/views/image/image.js, src-docs/src/views/image/image_example.js, src-docs/src/views/image/image_size.js, src-docs/src/views/image/image_zoom.js, src-docs/src/views/image/playground.js, src/components/image/__snapshots__/image.test.tsx.snap, src/components/image/image.test.tsx, src/components/image/image.tsx
This `url` prop for EuiImage has tripped me up many times. I constantly try to use the typical HTML `src` attribute and it takes me several minutes and docs lookup to find my mistake. 
This PR just creates an exclusive union that requires **either** `url` or `src` but since they can also conflict if not using TS, it defaults to `src` since this feels more standard and aligns to the final `<img>` tag.
=> [EuiImage] Allow `src` as well

src-docs/src/views/context_menu/context_menu_example.js
"Demo JS" of "Sizes" shows example of "With single panel" and vice versa. See:
https://elastic.github.io/eui/#/navigation/context-menu
=> [DOCS] Fix demo for "Sizes" and "With single panel" for Context menu

.github/workflows/stale_issues.yml, CONTRIBUTING.md
Adds a Github action that checks for stale issues and PRs using https://github.com/actions/stale, which is Github's officially supported action for stale checks. To run this in a dry run mode, I've turned on Github logging for the repo, and set `debug-only: true` for the action. The docs on https://github.com/actions/stale#debugging suggest this means the action will not be run, and only be logged. This should allow us to watch how this would effect our repo.
=> Stale issue/pr action

CHANGELOG.md, src/components/button/button_empty/button_empty.tsx, src/components/header/header_section/header_section_item_button.tsx
Re-adding the forwardRef to **EuiHeaderSectionItemButton**, now as `button | a`.
=> Re-add a forwardRef to EuiHeaderSectionItemButton

scripts/babel/react-docgen-typescript.js, src-docs/webpack.config.js
Fixes #4576
`chokidar` by way of `webpack-dev-server` by way of `yarn start-test-server-and-a11y-test` was watching all files and hitting memory limits. This prevents watching the entire docker environment using [devServer.watchOptions.ignored](https://webpack.js.org/configuration/watch/#watchoptionsignored).
=> Disable file watching in CI build

src/components/index.js, src/webpack.config.js
Use `strictExportPresence` on production builds to prevent missing exports, namely type exports from `.js` files.
=> [webpack] Fail on missing export

.github/workflows/stale_issues.yml
`* */8 * * *` -> `0 */8 * * *`
The former runs the action every minute of every 8th hour, the new value only runs the action once on that hour.
[https://crontab.guru/#0_*/8_*_*_*](https://crontab.guru/#0_*/8_*_*_*)
=> Tweak the stale issue action's cron setup

src-docs/src/views/datagrid/schema.js, src-docs/src/views/datagrid/styling.js, src-docs/src/views/form_controls/display_toggles.js
Making progress: #3150 
**Converted some  examples from class component to functional component**
- [example1](https://elastic.github.io/eui/#/tabular-content/data-grid-styling-and-control)
- [example2](https://elastic.github.io/eui/#/tabular-content/data-grid-schemas-and-popovers)
- [example3](http://localhost:8030/#/forms/form-controls)
~~- [ ] Added or updated **[jest …
=> [DOCS] Coverted some examples to functional component

src-docs/src/views/tables/in_memory/in_memory_selection_section.js
This PR Fixes: #3381 
Improved props table and added documentation for `itemId` prop.
=> [EuiInMemoryTable] Added documentation for `itemId` prop and improved props table

README.md, wiki/consuming.md
It seems that when I tried to create the new getting started page for #4449 and then we decided to not move forward:
- the `Using EUI with react-router` link was changed and stopped working 
- The `consuming.md` file was deleted
This PR reverts those changes and closes #4651.
- ~[ ] Checked **[Code …
=> [Docs] Add missing wiki file and fix links

src-docs/src/components/guide_section/guide_section_parts/guide_section_props_description.tsx
Show all `HTMLAttributes` type extensions unless there is more appropriate custom type extension
=> [Docs] Show all `HTMLAttributes` types

src/components/button/button.tsx, src/components/context/context.tsx, src/components/form/described_form_group/described_form_group.tsx, src/components/i18n/i18n_number.tsx, src/components/portal/portal.tsx, src/components/selectable/selectable_message/selectable_message.tsx
Fixes #4666 and other similar (though unrecorded) issues.
A [known bug in `react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript/issues/323) causes React component types (`Component` and `FunctionComponent`) prefixed with `React.` to be excluded from parsing. This results in missing docgen info and errors in the props table.
Fix is to remove `React.` prefixes in the few, old cases where they still exist.
=> [Props] Explicit import of `Component` and `FunctionComponent`

src/components/header/header_section/header_section_item_button.test.tsx, wiki/component-development.md
* Added documentation for using `forwardRef` in EUI
* Added two unit tests for **EuiHeaderSectionItemButton**'s ref
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked …
=> forwardRef documentation, forwardRef tests for EuiHeaderSectionItemButton

src/components/header/header_section/header_section_item_button.tsx
Fixes a failing unit test on master caused by **EuiHeaderSectionItemButton** re-rendering during the mount lifecycle as it tracks its internal buttonRef value.
Turns out the function component mount lifecycle is `mount -> update refs -> useImperativeHandle`, and I falsely believed it was `mount -> useImperativeHandle -> update refs`, which caused some null values to sneak in plus 2 additional renders.
~- [ ] Props have proper **autodocs** and **[playground toggles]~(https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-playground-toggles)**
~- [ ] Added …
=> Update EuiHeaderSectionItemButton to avoid re-renders

CHANGELOG.md, src/global_styling/mixins/_panel.scss, src/themes/eui-amsterdam/global_styling/mixins/_panel.scss
In https://github.com/elastic/eui/pull/4662, I introduced a bug trying to scope specific `<button>` styles in the `euiPanel()` mixin. I mistakenly thought, but didn't check that my Sass nested selector would work. It didn't.
This PR fixes the block display of `EuiPanel.onClick` by using the `:enabled` selector instead.
**Before**
**After** …
=> [EuiPanel] Fix selector for `button` element styling

src-docs/src/views/code_editor/code_editor_example.js
I completely remove all docs examples and props tables as we **really** don't want users to use it.
=> [Docs] EuiCodeEditor - Removed examples and added deprecation notice

CHANGELOG.md, src/components/button/button_group/button_group_button.tsx
Fixed htmlIdGenerator import
Fixed bad imported htmlIdGenerator that throwing an error on build my(and any other) project
=> Fixed htmlIdGenerator import

CHANGELOG.md, src/components/color_picker/color_stops/color_stop_thumb.tsx, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.test.tsx, src/components/popover/popover.tsx
Fixes #4679. Changes to `ownFocus` in `EuiPopover` affected the underlying focus trap on outside clicks. Clicking a color stop thumb while the popover was open would disable the underlying focus trap, causing the focus trap to no longer watch for outside clicks. We don't want the EuiColorStopThumb popover trap to be disabled on outside click; instead, we the trap should remain active while the popover is open.
I decided to expand the prop options beyond what we currently need. Can be expanded further in the future if necessary.
=> [EuiColorStops] Ensure popover close on outside click

CHANGELOG.md, src/components/avatar/index.ts, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.test.tsx, src/components/card/card.tsx
Two bug fixes to aid in upgrading Kibana:
* Export `EuiAvatarProps`
* Omit `title` and `onClick` props that are overridden with different types in **EuiCard**
~- [ ] Checked for **accessibility** including keyboard-only and screenreader …
=> Misc. TypeScript fixes

CHANGELOG.md, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.test.tsx, src/components/card/card.tsx
Allows for `selectable` EuiCard with `layout="horizontal"`
=> [EuiCard] Allow `selectable` with `layout="horizontal"`

src-docs/src/components/guide_components.scss, src-docs/src/components/with_theme/theme_context.tsx, src-docs/src/services/playground/iconValidator.js, src-docs/src/views/icon/accessibility.js, src-docs/src/views/icon/apps.js, src-docs/src/views/icon/custom_tokens.js, src-docs/src/views/icon/editor.js, src-docs/src/views/icon/icon_colors.js, src-docs/src/views/icon/icon_colors_apps.js, src-docs/src/views/icon/icon_example.js, src-docs/src/views/icon/icon_sizes.js, src-docs/src/views/icon/icon_types.js, src-docs/src/views/icon/icons.js, src-docs/src/views/icon/logos.js, src-docs/src/views/icon/logos_third.js, src-docs/src/views/icon/ml.js, src-docs/src/views/icon/playground.js, src-docs/src/views/icon/tokens.js
This PR fixes up the Icons documentation page mainly to reduce the panels. It also removes the third-party logos example without breaking actual usages by keeping the logos in the repo.
It also defaults first time users to the Amsterdam (light) theme now 😜 
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
=> [Docs] Fixing up Icons page

scripts/a11y-testing.js, src-docs/src/views/drag_and_drop/drag_and_drop_custom_handle.js, src-docs/src/views/form_compressed/complex_example.js, src-docs/src/views/suggest/hashtag_popover.js, src-docs/src/views/suggest/saved_queries.js
Makes progress on: #2679 
Adding  automated a11y test for docs pages.
**Forms**
**Display** 
~- [ ] Checked for **breaking changes** and …
=> Added a11y tests for some pages

tsconfig.json
Enabled TypeScript's `incremental` option to increase performance. Locally this decreases the `yarn tsc --noEmit` time from ~30s to ~5s when there are no changes present; changes to more core components approach 30s again, while modifying a TS file in _src-docs_ makes it take ~10s.
eslint & sass-lint, also part of the `test-staged` command, already take only a couple seconds each to run so I did not focus any effort there.
=> Enable incremental typescript runs

CHANGELOG.md, src-docs/src/views/datagrid/column_actions.js, src-docs/src/views/datagrid/column_widths.js, src-docs/src/views/datagrid/styling.js, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_data_grid_header_row.scss, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_body.tsx, src/components/datagrid/data_grid_header_cell.tsx, src/components/popover/popover.tsx
Fixes #4641 by only responding to key events when they are triggered on an element in the grid's DOM, ignoring events React bubbles through portals.
Fixes #4588 by moving all datagrid header cell contents into the popover's anchor button
Fixes #4532 (and another bug) by resetting the grid's height to its container size instead of unsetting+rerender+recalculate the container size. The second bug was in that recalculate step, or more correctly that it wasn't triggered at all.
~- …
=> [EuiDataGrid] bug fixes

src-docs/src/views/guidelines/index.scss, src-docs/src/views/guidelines/sass.js
Fixed issue #4715 by adding `euiBorderRadiusSmall` to Sass section.
=> [Docs] Add `euiBorderRadius` to sass guidelines

CHANGELOG.md, src/components/datagrid/data_grid_schema.tsx
Closes #4712, in which it was discovered that the sort labels for `datetime` schema were inverted.
For dates, ascending means that earlier values precede later ones (e.g., 1/1/2020 will sort ahead of 1/1/2021) …
=> [EuiDataGrid] Reverse asc and desc labels for `datetime` schema

src-docs/src/views/accordion/accordion_form.js, src-docs/src/views/flyout/flyout_complicated.js, src-docs/src/views/flyout/flyout_max_width.js, src-docs/src/views/form_layouts/described_form_group.js, src-docs/src/views/form_layouts/inline_popover.js, src-docs/src/views/form_validation/validation.js, src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src-docs/src/views/modal/modal_example.js, src-docs/src/views/modal/modal_form.js, src-docs/src/views/tour/managed.js, src-docs/src/views/tour/managed_hook.js, src-docs/src/views/tour/tour.js
Fixed #4711:  Updated examples to used EuiForms to use component="form" as a prop
=> Updated EuiForm examples 

src/components/markdown_editor/plugins/markdown_default_plugins.tsx
Fixes #4688 by exporting `Rehype2ReactOptions`
This is needed because of the same underlying problem noted in https://github.com/elastic/eui/pull/4672
=> [EuiMarkdowEditor] export intermediary type

CHANGELOG.md, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/button/button_content.tsx, src/components/button/button_empty/button_empty.tsx
Reduce size of the icon in `EuiButtonEmpty` so that when the size is `xs` the icon's size is `s`.
This is one of the issues we're tracking on the Amsterdam Airtable.
~- [ ] Props have proper **autodocs** and **[playground toggles]~(https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-playground-toggles)**
=> [EuiButtonEmpty] Reduce icon in xs size

CHANGELOG.md, src-docs/src/views/form_layouts/inline_popover.js, src-docs/src/views/modal/modal_form.js, src/components/popover/popover.tsx
Fixes #4767, where it was discovered that `EuiPopover` would exit early from its method to set initial focus, causing the `initialFocus` prop to be disregarded.
The fix here is to ensure that focus has been intentionally set, not just that any element has focus.
`false` is now an option for `intialFocus` to allow consumers to opt-out of initial auto-focus while maintaining focus trapping.
Wasn't able to write a test that actually worked.
=> [EuiPopover] Handle `initialFocus`

CHANGELOG.md, src-docs/src/views/combo_box/combo_box.js, src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box.test.tsx, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_input/combo_box_input.tsx
Adds a top-level `autoFocus` prop that gets passed through to the input, enabling native [HTML `autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autofocus) behavior.
=> [EuiComboBox] `autoFocus` behavior

CHANGELOG.md, i18ntokens.json, src/components/tour/tour_step_indicator.tsx
This PR fixes the usage of the `EuiI18n` label `euiTourStepIndicator.ariaLabel` in `EuiTourStepIndicator`.
=> [i18n] EuiTourStepIndicator to use EuiI18n following the standard way

CHANGELOG.md, src/components/call_out/__snapshots__/call_out.test.tsx.snap, src/components/call_out/call_out.tsx, src/components/form/__snapshots__/form.test.tsx.snap
Fixed #4811 by changing EuiText color of EuiCallout to default.
=> Changed EuiText color of EuiCallout

package.json
`mdast-util-to-hast` is imported directly in EUI but it is not included in `dependencies`. This was never _functionally_ a problem because it is brought in with `remark-rehype`.
https://github.com/elastic/eui/blob/7aeb30f542186c01b94baa3ab7237ab38b4df15f/src/components/markdown_editor/plugins/markdown_default_plugins.tsx#L38
Including in `dependecies` to unblock @mistic and Bazel
~### Checklis~
=> [Deps] Add `mdast-util-to-hast`

CHANGELOG.md, src/components/tour/_tour.scss
Removing the `text-transform: capitalize` from the `EuiTourStep` header title as per [Elastic writing guidelines](https://eui.elastic.co/#/guidelines/writing).
=> Removing text transform from EuiTour.

CHANGELOG.md, src/components/tour/tour_step.tsx
Fixes #4840.
Updated `EuiTourStep`'s `title` and `subtitle` prop type from `string` to `ReactNode`
- ~[ ] Checked for **accessibility** including keyboard-only and screenreader modes (#4814 has ideas to address a11y, should be a follow-up)~
=> [EuiTourStep] title and subtitle should accept ReactNode

CHANGELOG.md, src/components/flyout/flyout.testenv.tsx
EuiFlyout is [now wrapped in a React portal by default](https://github.com/elastic/eui/pull/4713), which makes selector querying in Jest environments difficult or impossible.
This adds a `testenv` mock to hide the internal complexities of EuiFlyout in Jest environments.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** …
=> [EuiFlyout] Add `testenv` mock

src-docs/src/index.js, src-docs/src/routes.js
Fixes #4870, the broken **playground** and **guidelines** links&tabs.
**Bug source:** the changes to enable stand-alone routes for **EuiPage** included marking component routes as `exact`, but these component routes are the only way playground/guideline routes are provided, and when navigating off those exact-matches the target routes were unmounted.
**Fix:** avoided specifying `exact` by re-ordered the main component & its full-screen section routes so sections can be matched first, allowing the component route to exist with its playground/guidelines.
**Tested:**
In Chrome, FF, Safari, Edge, and Mobile Chrome:
* full-screen, linked examples for **EuiPage**
* **EuiButton**'s guidelines
* _Key pad menu_'s playground
~- [ ] Check against **all themes** for compatibility in both light and …
=> Fix links to playgrounds and guidelines

CHANGELOG.md, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx
EuiComboBox auto scrolls to the selected item in componentDidUpdate. This makes the combo box unusable, as it auto-scrolls away from where users are looking any time there is an update. This issue is occurring in maps https://github.com/elastic/kibana/issues/78420.
This PR resolves the problem by moving the call to this.listRef.scrollToItem from componentDidUpdate to within setListRef.
=> fix combo box auto scrolling on componentDidUpdate

src-docs/src/views/page/page_example.js
There was a bad merge somewhere that didn't update the full height page demo to the new full screen ability so it was erroring out like this:
=> [Docs] Fix full height page demo for new `fullScreen` capability

CHANGELOG.md, src/components/page/page_body/_page_body.scss
This had broke full screen data grids by scoping the grid to that component, so no matter how high the z-index was on full screen data grids, that since it wasn't in a portal, it would always be constrained to the position of the page body.
**Before**
**After**
=> [EuiPageBody] Revert `z-index: 1`

CHANGELOG.md, src/components/date_picker/super_date_picker/super_date_picker.test.tsx, src/components/date_picker/super_date_picker/super_date_picker.tsx, src/components/date_picker/super_date_picker/super_update_button.test.tsx, src/components/date_picker/super_date_picker/super_update_button.tsx
* Closes #4871 by adding an optional `updateButtonProps` to **EuiSuperDatePicker**
* Extended `EuiSuperUpdateButtonProps` with `CommonProps` and a partialized subset of `EuiButtonProps`
* Added two tests around this setup
=> [EuiSuperDatePicker] Added prop to control the update button

package.json, yarn.lock
Closes #4894, which highlighted that EUI has an undeclared dependency: `unist-util-visit`. It is available via some remark plugins, but it is imported directly.
=> [Deps] Add `unist-util-visit`

CHANGELOG.md, src/components/drag_and_drop/index.ts
This PR adds an interface to the list of exports from 'react-beautiful-dnd' for use by consumers, without the need to export them from 'react-beautiful-dnd’.
See https://github.com/elastic/kibana/issues/102689
=> Add interface from react-beautiful-dnd

CHANGELOG.md, src-docs/src/views/page/page_custom_content.js, src-docs/src/views/page/page_simple.js, src-docs/src/views/page/page_simple_template.js, src/components/page/__snapshots__/page_template.test.tsx.snap, src/components/page/_mixins.scss, src/components/page/_page.scss, src/components/page/page_header/_page_header.scss, src/components/page/page_template.tsx
...and fix [EuiPageTemplate] props of EuiPageHeader in `empty` template type
Before, if you just added `bottomBorder = true` to EuiPageHeader, but there was no padding, there would also be no space between the header content and the border.
**Before**
**After**
Now it will always add a large padding. So it's not currently configurable, but it matches the default `paddingSize` of the typical page layout.
**Unless there's tabs**
Which still removes the bottom padding.
**Before **
**After**
**Before**
**After**
- ~[ ] Checked for …
=> [EuiPageHeader] Fix margin/padding when `bottomBorder` exists

CHANGELOG.md, src/components/observer/resize_observer/resize_observer.tsx
Fixes #4907, in which it was discovered that height and width from [`clientRect` do not include padding or border](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) (DOM box model).
This removes reliance on`clientRect` data and uses `getBoundingClientRect` instead. …
=> [EuiResizeObserver, EuiBottomBar] Account for padding and border

CHANGELOG.md, src-docs/src/views/combo_box/colors.js, src-docs/src/views/combo_box/combo_box.js, src-docs/src/views/combo_box/single_selection.js, src/components/combo_box/_combo_box.scss, src/global_styling/mixins/_form.scss
This PR fixes the **EuiComboBox** disabled pills and text color contrast.
This issue was originated by:
https://github.com/elastic/eui/blob/fb286cbe1b67f451cf33a984d2a1ead1832149df/src/global_styling/mixins/_form.scss#L201
The text and pills were inheriting this `-webkit-text-fill-color` in webkit browsers. And in no webkit browsers, there were no disabled styles for the pills and texts. They were getting their default colors.
So I added some styles and also added more `DisplayToggles` with `isDisabled` states in a few **EuiComboBox** examples.
- ~[ ] Checked **[Code …
=> [EuiComboBox] Fixed disabled pills and text contrast

package.json, yarn.lock
This PR updates the @elastic/charts dependency in the package.json from `24.5.1` - `30.2.0`. 
I'll be updating the `elastic-charts` section in the EUI doc system and the texture fill changes don't take effect until version 30.x. (Issue for reference: #4875)
I went through the existing elastic-charts documentation section, and it looks like all the sample charts are rendering correctly still. 
The existing checks here didn't seem relevant, but let me know if I misunderstood. Thank you!
=> build: update elastic-charts version

CHANGELOG.md, src/components/side_nav/__snapshots__/side_nav.test.tsx.snap, src/components/side_nav/side_nav.test.tsx, src/components/side_nav/side_nav.tsx
Also quickly allows for a non-responsive version by setting to `undefined`.
=> [EuiSideNav] Made `mobileBreakpoints` optional

CHANGELOG.md, src/themes/eui-amsterdam/global_styling/mixins/_range.scss, src/themes/eui-amsterdam/overrides/_color_stops.scss
This PR **almost** fixes the **EuiColorStops** outline flashing in Safari when clicking or adding a stop.
The focus state is now more consistent with the stop focus state.
It seems that the issue is fixed but if we press the mouse until we're **dragging** the outline appears. This behavior doesn't happen in other browsers.
https://user-images.githubusercontent.com/2750668/123241815-60165480-d4d9-11eb-9b03-204b69abaefa.mov
- ~[ ] Checked **[Code Sandbox](https://codesandbox.io/)** …
=> [EuiColorStops] Fixed outline flashing when clicking or adding a stop

CHANGELOG.md, src-docs/src/views/code/code_block.js, src/components/code/_code_block.tsx
Typically prism.js sets an empty `children` node as `undefined`, but in certain edge cases, like a childless `script` tag in a `language=html` block, `children` is set to `[]`.
This updates the logic to bypass parsing line data for `children: []`
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the any docs …
=> [EuiCodeBlock] Account for empty children in edge cases

package.json, yarn.lock
Moves `refractor` to `v3.4.0` (and `prismjs` to `v1.24.0`)
=> [Deps] Bump `refractor`

src-docs/src/views/text/text_example.js
Minor change in EuiText docs #4922
=> Replaced HTML with XHTML in EuiText

CHANGELOG.md, src/components/context_menu/context_menu.tsx
Updated EuiContextMenuPanelDescriptor's title prop type from string to ReactNode
=> [EuiContextMenuPanelDescriptor] title should accept ReactNode rather than string

src-docs/src/views/markdown_editor/mardown_format_example.js
In the documentation of `EuiMarkdownFormat`, the link to the Remark library was broken. It contained a typo and was using a routing component instead of a link. This small PR fixes it. :slightly_smiling_face:  …
=> docs: fix a broken link in the EuiMarkdownFormat section

CHANGELOG.md, scripts/dtsgenerator.js
To allow applications to confirm they define the whole set of our i18n tokens - and are updated when tokens are added or removed - this creates an `EuiTokensObject` definition in _eui.d.ts_ that can be used to type the context mapping object.
Relevant change in Kibana to opt-in to this typing: https://github.com/elastic/kibana/blob/master/src/core/public/i18n/i18n_eui_mapping.tsx#L18
`const euiContextMapping = {`
becomes
`const euiContextMapping: EuiTokensObject = {`
Tested this by dropping the generated eui.d.ts into Kibana & making the above change. TypeScript then identified 9 tokens that are no longer in use and 15 that are missing from that mapping.
=> Define set of i18n tokens via TypeScript

CHANGELOG.md, src-docs/src/views/datagrid/datagrid_height_options_example.js, src-docs/src/views/datagrid/row_height_options.js, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/data_grid_cell.tsx, src/components/datagrid/row_height_utils.ts
Adds a missing wrapping div to match the other cell instances in when the expand buttons are not showing yet. Basically it needed the same DOM structure as the other permutations, but it was just missing the  `.euiDataGridRowCell__expandContent` element.
**AFTER:**
https://user-images.githubusercontent.com/549577/125856032-06611905-029f-4bdb-b445-b86434dfce8c.mp4
By absolute positioning the buttons instead, they overlap instead of shift content. This behavior only affects multi-line cells. I also changed `break-all` to simply `break-word` for better line break positions. Eventually, this should become a customizable prop.
**Before**
**After**
- ~[ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-p …
=> [EuiDataGrid] Fix initial alignment of cells and expand button on multi-line cells

CHANGELOG.md, src/components/overlay_mask/overlay_mask.tsx
PR fixes an issue with the "click" event for EuiOverlayMask. Otherwise, it keeps adding listeners to the "click" event without removing them.
=> [EuiOverlayMask] Fixed click event subscription bug

src-docs/src/views/datagrid/container.js, src-docs/src/views/datagrid/datagrid_styling_example.js, src-docs/src/views/datagrid/flex.js
https://user-images.githubusercontent.com/549577/126009112-b445c3df-0dc0-45a5-8056-e2686039807b.mp4
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
=> [EuiDataGrid] Adding a docs section about nesting in a flex item

CHANGELOG.md, src/components/markdown_editor/plugins/markdown_checkbox/index.ts, src/components/markdown_editor/plugins/markdown_checkbox/parser.ts, src/components/markdown_editor/plugins/markdown_checkbox/renderer.tsx, src/components/markdown_editor/plugins/markdown_checkbox/types.ts, src/components/markdown_editor/plugins/markdown_default_plugins/index.ts, src/components/markdown_editor/plugins/markdown_default_plugins/parsing_plugins.ts, src/components/markdown_editor/plugins/markdown_default_plugins/processing_plugins.tsx, src/components/markdown_editor/plugins/markdown_default_plugins/ui_plugins.ts, src/components/markdown_editor/plugins/markdown_tooltip/index.ts, src/components/markdown_editor/plugins/markdown_tooltip/parser.ts, src/components/markdown_editor/plugins/markdown_tooltip/plugin.tsx, src/components/markdown_editor/plugins/markdown_tooltip/renderer.tsx, src/components/markdown_editor/plugins/markdown_tooltip/types.ts
We would like to use markdown plugin parsers on the server side, but because the logic is in `.tsx` we cannot import it, so I did split markdown plugin files to allow import just parser from `.ts` file
https://github.com/elastic/kibana/pull/96703/files#diff-4cc334d57c5ffcd80634cb613dd7f949499dd74f8990705cc3dca71d9a2efc87R456
=> [Markdown editor] Split plugin files

CHANGELOG.md, src/components/search_bar/filters/__snapshots__/field_value_selection_filter.test.tsx.snap, src/components/search_bar/filters/field_value_selection_filter.tsx
Closes #4976 by marking a filter as inactive when the number of active filters drops to 0.
See repro steps in the[ issue](https://github.com/elastic/eui/issues/4976).
~- [ ] Added or updated **[jest …
=> [EuiSearchBar] Handle 0 count after manual query manipulation

CHANGELOG.md, src/components/datagrid/data_grid_cell.tsx
Fixes #4975 
A few things came together to create this bug:
* **EuiDataGrid** owns which cell is focused
* **EuiDataGridCell** subscribes to notifications about its focus state and responds accordingly by accepting focus
* **EuiDataGridCell** also reacts to it receiving focus by e.g. a user clicking on it, it tells the parent grid about the updated focus state in a setTimeout which is meant to allow any focus traps to deactivate before the cell re-claims focus
* If multiple cells receive focus within that same setTimeout delay, they each queued up the focus claim
* As the focus queue was processed, each cell noticed it was no longer focused and would re-queue its claim
This fix avoids any queuing by merging the timeouts into one.
~- [ ] Check against **all themes** for compatibility in …
=> Prevent datagrid cells from queuing up focus ownership

CHANGELOG.md, src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
Fixes #4995 by formatting the date value passed to `title` and adds i18n tokens.
~- [ ] Checked for **breaking changes** and labeled …
=> [EuiSuperDatePicker] Button `title` formatting and i18n

CHANGELOG.md, src/components/form/form_label/__snapshots__/form_label.test.tsx.snap, src/components/form/form_label/_form_label.scss, src/components/form/form_label/form_label.test.tsx, src/components/form/form_label/form_label.tsx, src/components/form/form_row/form_row.tsx
Fixes #4987 
This PR passes the `isDisabled` prop from `EuiFormRow` to `EuiFormLabel`. When `isDisabled = true` the `EuiFormLabel` applies a class that changes its appearance to be `cursor: default`, which overrides the default behavior of `cursor: pointer` when there is a `for` attribute on the label.
https://user-images.githubusercontent.com/63428137/128564497-ab7882e2-cc29-44d0-94da-8b748d728a1e.mov
https://user-images.githubusercontent.com/63428137/128563993-f458c293-a7e5-4009-b555-dd0e5699a489.mov
=> [EuiFormRow] Allow isDisabled to remove interaction from label

CHANGELOG.md, src/components/form/form_row/form_row.tsx
Related to #4908, EuiFormRow also needs to respect the `isDisabled` prop on a child element.
~- [ ] Checked for **accessibility** including …
=> [EuiFormRow] Respect child `isDisabled`

CHANGELOG.md, src-docs/src/views/flyout/flyout_small.js, src/components/flyout/flyout.tsx
#4986 unintentionally changed the default value of `outsideClickCloses` to `true` when `ownFocus={false}`. This resets the default behavior while respecting `outsideClickCloses={true}` when `ownFocus={false}`.
See to-be-reverted docs change "Without ownFocus"
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for the …
=> [EuiFlyout] Fix `outsideClickCloses` logic

CHANGELOG.md, src/components/markdown_editor/plugins/markdown_default_plugins/processing_plugins.tsx
This PR enables the `EuiCodeBlock` copy button in `EuiMarkdownFormat`. 
- ~[ ] Checked for **accessibility** including keyboard-only and …
=> Enabled `EuiCodeBlock` copy button  in `EuiMarkdownFormat`

CHANGELOG.md, src/components/button/button_group/button_group_button.tsx
Fixes #4961, in which an EuiButtonGroup with `type=single` would fire the `onChange` callback twice for click events.
The fix is to remove the `onClick` handler for `type=single` groups because a `label` click will automatically call the `input` element's `onChange` handler.
~- [ ] Added or updated **[jest …
=> [EuiButtonGroup] Ensure `onChange` is called only once

wiki/documentation-guidelines.md
I hadn't realized I needed to add a specific label to skip the changelog CI/GH action and get my previous PRs to pass. While you do actually get that info by viewing the CI job error itself, it would also be nice to document the `skip-changelog` label in the Changelog wiki section for extra discovery purposes!
N/A, documentation changes only
=> Wiki changelog skip suggestion

wiki/creating-icons.md
The current Creating Icons wiki docs have a lot of references to Sketch (and says a Sketch library can be downloaded from EUI's docs, which no longer appears to be true). I translated them all as closely as I could to Figma equivalents (which we now appear to be using), although I'm far from a Figma expert and would totally appreciate a pair of eyes from someone with more knowledge than me.
N/A, documentation changes only
=> Remove Sketch references from Creating icons wiki

src-docs/src/views/datagrid/datagrid_example.js
This PR should fix the type errors in the DataGrid props tab/table.
Before:
After:
The issue was that all types were moved to `data_grid_types.ts` in https://github.com/elastic/eui/pull/5008, and the 2 imports in the diff needed to be updated accordingly.
~- [ ] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md) …
=> [Docs only] Fix type error in EuiDataGrid props table

.eslintignore, .stylelintrc, src-docs/src/views/icon/icon_example.js
This PR updates various linter ignore files to more accurately reflect what our CI/precommit checks require.
I recommend following along by commit for granular diffs/commit messages, but I'll additionally add code comments below with screenshots of the errors I was seeing.
I opened this PR primarily from the perspective of VSCode, which does a lot more live-checking of issues than other IDEs do OOTB (I could be totally wrong about this, but in-IDE catches of Typescript issues it's definitely one of the reasons why I switched over from Sublime when I started working in Kibana).
For repro: the 3 VSCode extensions I have installed are [ESLint](https://github.com/Microsoft/vscode-eslint), [Prettier](https://github.com/prettier/prettier-vscode), and …
=> [Tech debt] Update various linter ignore files

src-docs/src/views/icon/icon_example.js
The [ignore tech debt PR](https://github.com/elastic/eui/pull/5045/files#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275L11) caused `icon_examples.js` to stopped being lint-ignored and to start being correctly linted by Prettier. Turns out there were some Prettier issues to fix in it that I missed that are now causing issues in master - apologies!
Soapbox aside: Also a good case study in why not to add specific files to ignore files, but instead prefer either fixing the issue or to use single line `// *-ignore` type comments 😅 
N/A, linting fix only
=> [Linting] Fix Prettier linting issue in master

src-docs/src/views/form_controls/file_picker.js
I noticed this while QA testing https://github.com/elastic/eui/pull/5063 locally - my file list in the file picker doc example wasn't updating when I added/updated existing files, only on new file add:
(note how `trial` does not update to match `gold`, and 3 files are listed in the picker but not on the right)
After some digging, this appears to be because I'm a Firefox user, and Firefox for some reason is mutating the existing FileList in place, which fails to trigger a React state change 🤦‍♀️ (https://github.com/facebook/react/issues/18104)
There's a relatively simple `Array.from(FileList)` workaround you can use to correctly trigger state changes, which I thought was worth implementing both to fix this behavior and as an example to other dev users who may run into the same issue at …
=> [Docs only] Fix EuiFilePicker example file list on Firefox

CHANGELOG.md, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/data_grid.test.tsx
closes #4599, and I _believe_ should also close #4665
The before/after screenshots depict the issue quite clearly, so I'll let a picture speak a thousand words for me 😄 
=> [EuiDataGrid] Fix cell props not clearing state on column reorder

scripts/jest/config.json, wiki/component-development.md, wiki/testing.md
I'm writing unit tests for datagrid child components, and I like to run with the `--coverage` flag when writing tests to help me catch any branches or uncovered lines I may have forgotten. I noticed my coverage reports weren't what I expected, and updated our `jest/config.json` accordingly to account for most/all of our files now being `.ts`/`.tsx`.
I also noticed from our wiki docs that the commands we run have some outdated syntax that no longer apply - the `run` command isn't necessary with yarn, nor is the `--` delineator. I've been running `yarn test-unit data_grid -u --coverage --watch` locally with no issues.
N/A, dev/documentation only changes
=> [Tech debt/docs] Unit test updates

CHANGELOG.md, src/components/form/form_row/_form_row.scss, src/components/table/_table.scss, src/components/toast/_toast.scss, src/global_styling/mixins/_form.scss, src/global_styling/mixins/_typography.scss
Ensures that anywhere we use the title mixin to create titles, it will break on really long words if need be. This doesn’t affect those that use it with truncation.
I've also pushed a `REVERT ME` commit that adds a really long string to the end of content that uses the mixin to test all the usages.
<details>
<summary> EuiTable header cell wasn't using the full `euiTextTruncate` mixin </summary>
---
This was a really old style, before we had the mixin, where there title mixin was used at more parent element than the truncation mixin. But there was a style that was applying `nowrap` at the same level, which I just changed to the whole `euiTextTruncate` mixin.
**Before**
**After**
---
</details>
<details>
<summary> Added `euiTextTruncate` mixin to EuiFormLabel</summary>
---
It doesn't …
=> Added `euiTextBreakWord` mixin to the `euiTitle` mixin

src-docs/src/components/guide_section/_utils.js, src-docs/src/services/string/clean_imports.js, wiki/consuming.md
Updates the _consuming_ wiki & _Demo JS_ code rendering to not import from locations other than `@elastic/eui`. Noticed this while looking at some accordion examples with @breehall.
=> Update documentation for service imports

src/components/common.ts, src/components/flyout/flyout.tsx
Fixes #4980. Changes include exporting `EuiFlyout` from the definition location, and some clean up work to standardize React type imports.
=> [EuiFlyout] Fix prop table; refactor

CHANGELOG.md, src-docs/src/views/selectable/data.ts, src-docs/src/views/selectable/selectable_popover.js, src/components/selectable/selectable.tsx
Fixes #4147, in which a click event on an unfocused EuiSelectable would prevent the intended option click and instead scroll to the currently selected option (i.e., two clicks were required because the first was captured by `onFocus`).
The fix is to look for click events on the element that watches for `onFocus` and prevent the handler from running. The subsequent events triggered by the option selection will correctly place focus inside the list and allow for keyboard navigation. Keyboard navigation is otherwise unaffected.
**Repro:**
1) Go the Single Selection example.
2) Check the last item.
3) Click away from the list (outside the component)
4) Click the first item in the list.
5) The first item should be selected.
6) Repeat with the Popover example.
~- [ ] Check against **all …
=> [EuiSelectable] Prevent `onFocus` from negating selection

src-docs/src/views/form_controls/form_controls_example.js, src-docs/src/views/form_controls/switch.js, src-docs/src/views/form_controls/switch_label.tsx
In the Security design meeting there was a discussion around how to label switches. The age old question of if it should be detailing the current state or not. We came to a consensus that if it is the **sole** label for the switch, it should be static and describe the feature or state the question.
But if there is a label elsewhere in the UI that gives meaning to the switch, then the label can either be completely eliminated or used to describe the state like "on/off".
This PR, updates our Switch section to detail these ideas as well as cleans up the original example to display a single switch and use the `DisplayToggles` to see the different states (which is 🤷 up for debate since we have the playground now, but at least its consistent).
~- [ ] Props have proper **autodocs** and …
=> [EuiSwitch] Add guidelines around labelling

CHANGELOG.md, src/global_styling/mixins/_helpers.scss
@qn895 reported an issue with their usage of `EuiInMemoryTable` within a scrolling container causing strange scrolling on the rest of their page/body. I was able to reproduce this behavior in our own docs page as well as in a [CodeSandbox](https://codesandbox.io/s/busy-liskov-rlorg?file=/index.js):
Notice the page scrollbar jumping/increasing every time the table rows (and consequently table height) increases.
[CSS-tricks](https://css-tricks.com/findingfixing-unintended-body-overflow/) put me on the right track of thinking it was a hidden absolutely positioned element that was causing the overflow issue. I also noticed when I had a table with plain text and no external link, I didn't have the same scroll issues. Well, I put 2 and 2 together, and it turns out it's the …
=> [euiScreenReaderOnly] Use `clip` to fix scrolling issues caused by absolute positioning

src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_buttons.test.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_footer_row.test.tsx, src/components/datagrid/body/data_grid_footer_row.tsx, src/components/datagrid/body/popover_utils.test.tsx, src/components/datagrid/body/popover_utils.tsx, src/components/datagrid/data_grid_schema.tsx, src/components/datagrid/data_grid_types.ts, src/components/observer/resize_observer/resize_observer.tsx
I originally started writing unit tests on the top-level files and realized those were some of the most complex 😅 I ended up going from small files to large for my own sanity.
Code coverage of new tests:
I **strongly** recommend following along by-commit. Here's a tl;dr breakdown of changes:
- Straightforward tests
- b46fcf4: EuiDataGridFooterRow
- 5cc3274: EuiDataGridCellButtons
- c092407: EuiDataGridCellPopover
- Non-straightforward tests:
- 56c8215: EuiDataGridCell contains a high amount of native DOM behaviors (resize observer, mouse/keyboard events, focus/tab state, etc.) that are difficult to mimic in JSDom. I left general TODO blocks in here for sections of code I thought would be better served by writing in Cypress than Jest
- cc8777c: EuiDataGridBody has the same difficulties …
=> [EuiDataGrid] Add unit tests for body/ components + minor refactors

CHANGELOG.md, src/global_styling/mixins/_helpers.scss
closes #5145
Per @cchaos, we should consider the addition of the `clip` property to be a breaking change since it may impact other devs who were targeting or overriding `.euiScreenReaderOnly` (which is what we were doing in #5149).
This PR thus reverts #5130, and after it lands, I'll open a new PR that includes both #5130 and #5149 that will be labeled as a breaking change and target `38.0`.
Mostly skipped as this is a straightforward git revert
=> [euiScreenReaderOnly] Revert #5130 - clip property addition

.github/pull_request_template.md
Removed an extra `the` from `the any`. Copy should now be:
> Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs examples
=> [Misc] Fix typo in PR template

i18ntokens.json, yarn.lock
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
I find this warning very annoying; be gone
=> [Deps] Bump `caniuse-lite`

CHANGELOG.md, src/components/resizable_container/_resizable_button.scss, src/components/resizable_container/_resizable_collapse_button.scss
Fixes #5003
This PR changes: 
- `.euiResizableButton` to use `z-index: 1` instead of `z-index: $euiZLevel1`
- `.euiResizableToggleButton` to `z-index: 2`  instead of  `z-index: $euiZLevel1 + 1`
Both of these changes fix the UI bug which caused the button's separating line and the button itself to overlap the header when the page is scrolled.
Here is a before and after:
=> [EuiResizableContainer] Fix z-index ui bugs

CHANGELOG.md, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/data_grid.test.tsx
Fixes #5162
Um, so. I omitted a `!` in an if statement in #5136 which interacted with itself in an extreme way when a column resize causes a column to drop off into the virtualization void.
This PR:
* adds an optimization to only process a cell once even if there were multiple mutations (not the crux of the issue, but one flame graph implicated this)
* actually finds the cell's div to pass to tabbable, instead of flagging the entire grid
Testing:
Set the main grid demo's page size to 100, then resize a column to drop one or more off the end.
/cc @kqualters-elastic if you'd like to test this within your grid
~- [ ] Props have proper **autodocs** and **[playground …
=> [EuiDataGrid] Actually fix calls to tabbable instead of moving the issue to a different part of the code

CHANGELOG.md, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx
closes #4705
Apologies if the striping is hard to see on my recorded gif settings! 🙈 
This is a fairly straightforward JS fix, so I opted not to thoroughly frontend test it. I'm also 50/50 on adding unit tests for this fix; if we didn't have unit tests already written for striping I'm not a massive fan of adding ones now for a primarily visual bugfix, but I can do so if folks feel strongly about it!
~- [ ] Added …
=> [EuiDataGrid] Fix stripes incorrectly alternating on sort/pagination 

CHANGELOG.md, package.json, src/components/icon/icon.test.tsx, src/components/selectable/selectable_templates/selectable_template_sitewide.tsx, yarn.lock
Closes #5146 by upgrading our typescript dependency to match Kibana's pinned version.
* updated TS version in `dependencies` & `peerDependencies`
* gave a Promise in _icon.test.txt_ an explicit return type
* convinced TS spreading `searchProps` in **EuiSelectableSitewideTemplate* is okay
* tested resulting _eui.d.ts_ in Kibana
~- [ …
=> Bump typescript version to ~4.1.3

CHANGELOG.md, src-docs/src/views/datagrid/datagrid_focus_example.js, src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/_mixins.scss
This PR fixes the **EuiDataGrid** focus ring to be contained in the cell. It also fixes cells when focused getting a higher `z-index` which was causing long content to overlap surrounding cells.
The issue with the focus states was found on #4958. 
As we can see having the focus rings outside of the cells was making them getting cut by other surrounding cells. IMO it was not looking good. 
- ~[ ] …
=> [EuiDataGrid] Fixed focus ring to be contained in cell

src/components/datagrid/body/header/column_actions.test.tsx, src/components/datagrid/body/header/column_actions.tsx, src/components/datagrid/body/header/data_grid_header_cell.tsx
By-commit walkthrough:
1. ccae0fa - These new unit tests are technically all that's required in terms of test-writing goals. It gets close, but not quite, to 100% coverage:
The reason why I didn't stop here and ended up refactoring the file further was:
2. 1501bfd - Writing unit tests revealed several code pain points (e.g.: a long series of args vs. an object of options, the object almost always should be used) that I wanted to fix to make reading & writing the unit tests less painful 
3. d67d387 - Parsing the file and writing unit tests was relatively painful in terms of grokking the intended functionality was vs. where the code lived. I wanted the source code to better reflect the end unit test experience (i.e. separating concerns).
4. Separate functions and utilities not only makes …
=> [EuiDataGrid] Refactor + write unit tests for body/header/column_actions

src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap, src/components/form/super_select/super_select_control.tsx
- Fixes an accessibility ID that regenerates on component rerender
- Fixes an unnecessary aria-labelledby that renders as `undefined`
Related parent PR:
- https://github.com/elastic/eui/pull/5195
N/A, internal/tech debt only - changelog will be in parent #5195 PR
=> [EuiSuperSelect] Fix regenerating and missing IDs

src/components/accordion/accordion.tsx, src/components/combo_box/combo_box_input/combo_box_input.tsx, src/components/form/file_picker/__snapshots__/file_picker.test.tsx.snap, src/components/form/file_picker/file_picker.tsx, src/components/popover/popover.tsx, src/components/side_nav/__snapshots__/side_nav.test.tsx.snap, src/components/side_nav/side_nav.tsx
Parent PR: #5195
- Class components fixed (before/after screencaps in individual code comments below)
- EuiAccordion
- EuiComboBox
- EuiFilePicker
- EuiPopover
- EuiSideNav
- Class components that did not need to be fixed (static IDs saved to state or class var)
- EuiCodeEditor
- EuiFormRow
- EuiDualRange
- EuiRange
- EuiOutsideClickDetector
- EuiSelectable
- EuiTabbedContent
- EuiToolTip
- EuiTreeView
- Class components left alone:
- EuiIcon - I wasn't sure how to interpret how the `titleId` was being used and I couldn't find an example of it in our docs
QA screencaps in comments below
Single changelog entry will be made in #5195
=> Fix multiple class components to not regenerate IDs on rerender

CHANGELOG.md, src/components/button/button_group/button_group.tsx, src/components/button/button_group/button_group_button.tsx, src/components/card/card.tsx, src/components/form/switch/switch.tsx, src/components/header/header_alert/header_alert.tsx, src/components/key_pad_menu/key_pad_menu_item.tsx, src/components/markdown_editor/markdown_editor.tsx, src/components/markdown_editor/plugins/markdown_checkbox/renderer.tsx, src/components/notification/notification_event.tsx, src/components/notification/notification_event_messages.tsx, src/components/notification/notification_event_meta.tsx, src/components/resizable_container/resizable_button.tsx, src/components/resizable_container/resizable_panel.tsx, src/components/tour/tour_step.tsx
Follow up to #5133: This PR updates our functional components to not regenerate our randomized HTML IDs on every component update/rerender.
- Components addressed in separate PRs:
- Class components (#5201)
- EuiBasicTable (#5196)
- EuiSuperSelect (#5197)
- EuiSuperDatePicker (#5200)
- Components addressed in this PR:
- I'll go through each commit below (separated by component) and add before/after screencaps!
N/A - Individual component QA steps listed above.
=> Update multiple functional components to useGeneratedHtmlId hook

CHANGELOG.md, src/components/button/button_group/__snapshots__/button_group.test.tsx.snap, src/components/button/button_group/button_group_button.tsx
Fixes (#5180)
- ~~[ ] Check against **all themes** for compatibility in both light and dark modes~~
- ~~[ ] Checked in **mobile**~~
- ~~[ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md#adding-playground-toggles)**~~
- ~~[ ] Added **[documentation](https://github.com/elastic/eui/blob/master/wiki/documentation-guidelines.md)**~~
- ~~[ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs examples~~
- ~~[] Added or updated **[jest tests](https://github.com/elastic/eui/blob/master/wiki/testing.md)**~~
- ~~[ ] Checked for **breaking changes** and labeled appropriately~~
- ~~[ ] Checked for **accessibility** including keyboard-only and screenreader modes~~
=> [EuiButtonGroup] Add `title` when in `iconOnly` mode

CHANGELOG.md, src/components/link/_link.scss, src/global_styling/mixins/_helpers.scss
We changed `.euiScreenReaderOnly` to `left: 0` in #5152, specifically [here](https://github.com/elastic/eui/commit/5833109a7129f65185ecb7cc238e4320da51d9d5#diff-21df3b63568ade74e435fc702dc637d3e7cb68431f01f24456d496fdc48fa201L114-R116).
Unfortunately, this change caused Kibana's FTR Selenium `.getVisibleText()` to include screen reader text when it previously did not:
These functional test failures can be viewed in our Kibana upgrade PR: https://github.com/elastic/kibana/pull/112462
1. I strongly think it will be significantly faster and less dev time/effort to backport this reversion to a new `38.0.1` release and update our Kibana upgrade to point at that release.
2. It's extremely confusing from a Kibana dev POV to assert on/expect visually hidden text.
3. I don't think the change to …
=> [EuiScreenReaderOnly] Revert left positioning change

CHANGELOG.md, src-docs/src/views/super_select/super_select_complex.js, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.test.tsx, src/components/form/super_select/super_select.tsx
While discussing EuiSuperSelect with @scottybollinger, we realized that there isn't a className prop that developers can pass to the actual portalled EuiPopover panel generated by EuiSuperSelect. `popoverClassName` feels like it should, but actually passes it to the un-portalled wrapping class (instead of to `.euiPopover__panel`).
This PR solves that by adding a new `popoverProps` config object to EuiSuperSelect, which passes down almost every prop that EuiPopover would normally take (except for `isOpen`, which we still want to remain as a top-level API). Users can now simply pass `popoverProps={{ className: 'wrapper', panelClassName: 'foo' }}` (plus any other popover styling props desired).
~- [ ] Checked …
=> [EuiSuperSelect] Add popoverProps prop 

src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.test.tsx
For some reason `Emotion` didn't like the latest update to with the `popoverProps` as it errored like:
```bash
19:59:02 FAIL src/components/form/super_select/super_select.test.tsx
19:59:02   ● EuiSuperSelect › props › renders popoverProps on the underlying EuiPopover
19:59:02 
19:59:02     PrettyFormatPluginError: Cannot delete property 'className' of #<Object>TypeError: Cannot delete property 'className' of #<Object>
19:59:02 
19:59:02       177 |       );
19:59:02       178 | 
19:59:02     > 179 |       expect(component).toMatchSnapshot();
19:59:02           |                         ^
19:59:02       180 |     });
19:59:02       181 |   });
19:59:02       182 | });
```
My guess is because the popover panel didn't actually exist so those props couldn't be passed down 🤷‍♀️ . But anyhow, …
=> [EuiSuperSelect] Update jest test for `popoverProps` to simulate click first

CHANGELOG.md, src-docs/src/views/tour/step.js, src/components/tour/__snapshots__/tour_step.test.tsx.snap, src/components/tour/_tour.scss, src/components/tour/tour_step.test.tsx, src/components/tour/tour_step.tsx
I ran into this where I wanted to use the EuiTour component more to indicate to users changes in the UI, so it wasn't more than a single step. Requiring **two** titles and body content was quite excessive. So I just made `subtitle` optional.
**Before**
**After**
Before, it was accepting a boolean, number or string and doing some className workarounds for the default of `true`. I noticed that this wasn't actually working (the default minWidth class was never getting applied) and so I just changed the type to `CSSProperties['minWidth']` set the default to `300` and passed it along to `panelStyle`.
I also then added a similar thing for `maxWidth`.
They started at `<h1>`, but as per the guidance in #4843 , they should start at `h2`.
=> [EuiTour] Style and a11y fixes

CHANGELOG.md, src-docs/src/views/color/color_example.js, src-docs/src/views/color/contrast_body.js, src/services/color/contrast.ts, src/services/color/manipulation.ts
I noticed in our Global Values page any time we were doing color calculations on hex values, the `rgb()` value was output which in turn confused the color picker. So I've updated these functions to attempt to maintain the same format that was passed in except for `makeHighContrast()` since we don't support alpha values anyway.
**Before**
**After**
**Color utility page showing input vs output**
- ~[ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs examples~ Emotion is not working …
=> Changed color utility functions to maintain color format supplied

CHANGELOG.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.tsx
Bug fix/follow up to https://github.com/elastic/eui/pull/5196#discussion_r710527022
- I hadn't realized during my initial testing that two `select all` checkboxes are rendered - one in the mobile table header, and one in the regular/desktop table header 🤦‍♀️ 
- In our latest Kibana upgrade (https://github.com/elastic/kibana/pull/113633), its functional accessibility tests are correctly flagging/raising an error due to both checkboxes sharing the same/duplicate ID
- The fix here is to generate a separate suffixed ID depending on whether it's a mobile or desktop checkbox
- Go to https://eui.elastic.co/pr_5237/#/tabular-content/tables#adding-selection-to-a-table
- Make your screen smaller until the table collapses to become mobile
https://user-images.githubusercontent.com/549407/135918086-59e …
=> [EuiBasicTable] Fix duplicate ID in EuiBasicTable's Select All checkbox(es)

CHANGELOG.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.tsx
I was messing around EuiBasicTable fixing accessibility issues and noticed this small missing i18n token 👀 
~- [ ] Checked for **breaking …
=> [EuiBasicTable & EuiInMemoryTable] Fix missing i18n token for default noItemsMessage

CHANGELOG.md, src/components/markdown_editor/markdown_editor_drop_zone.tsx
@brittanyjoiner15 and @i-a-n noticed that `EuiFilePicker`s on the same page as `EuiMarkdownEditor`s did not have functioning drag & drop. This is because [react-dropzone](https://github.com/react-dropzone/react-dropzone) (used by `EuiMarkdownEditor`) intercepts all document drop events, which we have to toggle off via a `preventDropOnDocument` config. …
=> [EuiMarkdownEditor] Fix react-dropzone taking over all drop events on the page

CHANGELOG.md, src/components/button/button_empty/_button_empty.scss, src/components/call_out/_variables.scss, src/components/drag_and_drop/_droppable.scss, src/components/toast/_toast.scss, src/global_styling/react_date_picker/_date_picker.scss, src/global_styling/variables/_colors.scss, src/themes/eui-amsterdam/eui_amsterdam_colors_dark.scss, src/themes/eui-amsterdam/eui_amsterdam_colors_light.scss, src/themes/eui/eui_colors_dark.scss
As a follow up to https://github.com/elastic/eui/pull/5323#pullrequestreview-791097097 and #4874, this PR removes the Sass vars with `secondary` in the name.
https://gist.github.com/thompsongl/506f6f86201c83d61cc850170fd49467#remove-secondary-color-prop-options
=> [Breaking] Remove Sass vars `$euiColorSecondary` and `$euiColorSecondaryText`

wiki/creating-components-manually.md, wiki/creating-components-yeoman.md, wiki/react-router.md, wiki/testing.md
Fix filenames and paths for components and routes on the wiki.
Fix files that still have `.js` extension
Fix references to `src-docs/src/routes.js`
Closes https://github.com/elastic/eui/issues/5347
=> Fix filenames and paths for components and routes

CHANGELOG.md, src/components/error_boundary/_error_boundary.scss, src/components/error_boundary/error_boundary.tsx
Before the component was just rendering a bare `<pre>` element, but now the error gets wrapped in our EuiCodeBlock which handles the overflow scrolling and gets rid of some unnecessary custom styles and selectors.
**Before**
**After**
- ~[ ] Checked for …
=> [EuiErrorBoundary] Use EuiCodeBlock to render error

src/services/theme/hooks.tsx, src/services/theme/index.ts, src/services/theme/types.ts, src/themes/index.ts
https://github.com/elastic/kibana/pull/117368 highlights some missing exports from the original `EuiThemeProvider`/`useEuiTheme` PR:
* The actual themes (`EuiThemeDefault`, `EuiThemeAmsterdam`)
* 🙈 
* Required for switching to Amsterdam
* `COLOR_MODES_STANDARD` constant, for convenience
* Newly defined, comprehensive `UseEuiTheme` interface
* Simple wrapper around its 3 component parts 
* Reused in `WithEuiTheme`
=> [CSS-in-JS] Theme exports

CHANGELOG.md, src/components/empty_prompt/empty_prompt.tsx, src/components/icon/icon.tsx, src/components/icon/named_colors.tsx
**EuiEmptyPrompt** uses the `isNamedColor` function from icon.tsx, but wasn't included in the icon.testenv.tsx mock. I don't think there's a good way to mock the function, so instead I moved it & its dependencies into a new file that isn't bypassed in test environments.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works …
=> [EuiIcon] Moved isNamedColor out of a testenv-targeted file

CHANGELOG.md, src-docs/src/views/datagrid/datagrid.js, src/components/datagrid/body/data_grid_body.tsx
- closes #5391
- Bug introduced in https://github.com/elastic/eui/pull/5313
https://github.com/elastic/eui/blob/a648149ac0ecb5cb94b655f39187a494344bc9eb/src/components/datagrid/body/data_grid_body.tsx#L601
`height` being set to undefined means that `finalHeight` falls back to `unconstrainedHeight` here on line 641:
https://github.com/elastic/eui/blob/cb9f462a4fc63913019f921bf3fbe5d4c2ba7846/src/components/datagrid/body/data_grid_body.tsx#L639-L641
Which leads to `.euiDataGrid__virtualized` and the inner content being the same `unconstrainedHeight`, resulting in inner content that never scrolls:
https://user-images.githubusercontent.com/549407/142914297-31dce55a-58b8-46fe-83a5-04d73679a973.mp4
Having the main `setHeight()` logic (lines 604-608) respond dynamically to `rowCount` fixes the …
=> [EuiDataGrid] Fix paginated & height-limited datagrids becoming unscrollable on `rowCount` change

generator-eui/documentation/index.js, generator-eui/documentation/templates/documentation_page.js, generator-eui/documentation/templates/documentation_page_demo.tsx
- Removes `HTML` source tab
- Aligns both sets to spit out the same content
- Wraps text in fragment (we do this manually a lot)
- Changes the `existing` doc output to be the **object** method not component
- Reduces import path to just `/src` since further folders are no longer necessary
- Moved order of `text` to just after `title` since `source` it's more related to the `demo`
- Added `intro` section to the new page with required `<EuiText>`
---
Running the following commands: 
1. `yarn run yo-doc` option 1 for component called `test`
```bash
? What do you want to do? Create a new component documentation page
? What's the name of the component you're documenting? Use snake_case, please. test
```
2. `yarn run yo-doc` option 2 for the same named component `test`
```bash
? What do you …
```
=> Update yeoman docs generator

cypress/plugins/webpack.config.js, cypress/support/index.js, package.json, scripts/cypress.js, wiki/cypress-testing.md
Adds a `--theme` flag to allow switching to light mode when running cypress. Usage is `--theme=light` or [default] `--theme=dark`. This specifies which css file to build (if `--skip-css` is not present) and uses webpack to define a magic variable so the right css file can be `require`d.
=> [Cypress] Allow theme selection in tests

src/components/page/page_header/page_header_content.tsx
This PR fixes a small typo in the autodocs of `EuiPageHeader`.
=> Fixes typo in EuiPageHeader docs

CHANGELOG.md, scripts/dtsgenerator.js
Per @1Copenut's upgrade Kibana PR (https://github.com/elastic/kibana/pull/119205), the checks step is failing with this error:
```
ERROR Type check failed in test/tsconfig.json:
ERROR node_modules/@elastic/eui/eui.d.ts:17870:31 - error TS2503: Cannot find namespace 'jest'.
```
> It looks like there's a TypeScript export issue that I traced back to row_height_utils.ts (datagrid mock) and line 17,864 of the eui.d.ts definitions file.
Mocks should **not** be exported in our `eui.d.ts` file, nor should any other test files. I've updated our `dtsgenerator.js` config to exclude all possible mocks, as well as Cypress spec files just in case.
=> Exclude mocks and Cypress specs from eui.d.ts

src/components/code/code.tsx, src/components/code/code_block.tsx, src/components/code/utils.tsx
In #5379, I refactored `code_block.tsx` to essentially be `_code_block.tsx` but forgot to check/update the types accordingly:
https://github.com/elastic/eui/blob/c85913bef931f2eb7df754c48eca7fdf6481ebc4/src/components/code/code_block.tsx#L14-L16
(specifically the last line is what I missed)
CommonProps was DRY'd out to `EuiSharedProps`. (Theoretically `& HTMLAttributes<HTMLElement>` could go there as well since EuiCode uses it as well - would be open to making that change, let me know)
Without this fix, a bunch of Kibana type checks end up failing because folks are using (e.g.) `style` and other props on EuiCodeBlock:
```
x-pack/plugins/enterprise_search/public/applications/workplace_search/components/shared/status_item/status_item.tsx:47:9 - error TS2322: Type '{ children: string; …
```
=> [EuiCodeBlock] Fix HTML attributes not being accepted as props

src/components/basic_table/table_types.ts
https://github.com/elastic/eui/blob/4a67fdc66ea7f9139824c7d000ec4f5d4402b7f1/src/components/basic_table/table_types.ts#L37
currently there's no suggestions from `keyof T` on `field` when the type is `EuiTableFieldDataColumnType` 
turns out this happens because `keyof T | string` ends up being just `string` 
[workaround](https://github.com/microsoft/TypeScript/issues/29729#issuecomment-460346421) is applied in this PR
and suggestions now include the keys from `T` :
also -
- we could get support for all nested keys with [Paths<T>](https://stackoverflow.com/a/58436959) but that's probably too much
- we could enforce root keys or dotted keys with root key as prefix, not sure it's worth it though
i think it's not relevant here. types didn't really change, just how TS displays them.
=> [EuiTableFieldDataColumnType] improve autocomplete suggestions for `field` property

CHANGELOG.md, src-docs/src/views/code/code_block_copy.tsx, src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/code/code_block.test.tsx, src/components/code/code_block.tsx
Fixes a copy bug and incidentally closes #5416 while I'm here
When using empty HTML nodes/React components inside an `EuiCodeBlock`, e.g.:
```
<EuiCodeBlock>
<div />
</EuiCodeBlock>
```
It was possible for the copy button to incorrectly output `[Object object]` due to the ``` innerText || `${children}` ``` fallback.
This PR amends the `${children}` fallback to _only_ be used for its intended edge case (virtualized code blocks), and correctly hides the copy buttons for EuiCodeBlocks with empty text and child nodes.
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#adding-playground-toggles)* …
=> [EuiCodeBlock] Fix empty code blocks with children returning `[Object object]`, use `fullScreenExit` icon

src-docs/src/views/theme/borders/_border_sass.tsx
This PR fixes the Sass `border-radius` snippet in theming borders that was incorrect.
- ~[ ] A …
=> [Docs] Fix Sass `border-radius` snippet in theming borders

CHANGELOG.md, src/components/avatar/__snapshots__/avatar.test.tsx.snap, src/components/avatar/avatar.tsx, src/components/comment_list/__snapshots__/comment.test.tsx.snap, src/components/comment_list/__snapshots__/comment_timeline.test.tsx.snap
The EuiAvatar has an `aria-label` attribute that is throwing an error in the latest axe-core plugin and CLI rulesets. This PR adds a conditional `role` attribute that resolves to "img" or "presentation" if the `isDisabled` prop is passed. PR closes #5289.
=> [EuiAvatar] Adding conditional`role` attribute to EuiAvatar container DIV

CHANGELOG.md, src/components/form/range/_range_ticks.scss
Fixes #5425 by adding `overflow-y: hidden;` to the tick label elements.
Note that this bug only affects Safari, and is really only noticeable when system scrollbars are configured to show "Always" (System Preferences > General > Show scrollbars)
`overflow: hidden;` was not used because we override `overflow-x` in the case of custom labels.
Pink: Desired label truncation
Orange: Desired label overflow
~- [ ] Added or updated …
=> [EuiRange] Remove tick label scrollbars in Safari

CHANGELOG.md, src-docs/src/views/datagrid/datagrid_height_options_example.js, src-docs/src/views/datagrid/datagrid_styling_example.js, src-docs/src/views/datagrid/display_callbacks.js, src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/controls/display_selector.tsx, src/components/datagrid/data_grid_types.ts, src/services/hooks/index.ts, src/services/hooks/useDependentState.ts, src/services/hooks/useUpdateEffect.test.tsx, src/services/hooks/useUpdateEffect.ts, src/services/index.ts
Per feedback from Caroline and Vlad, we should expose internal `gridStyle` and `rowHeightsOptions` state in an `onChange` callback:
> In the future, we should provide a grid example that manually adjusts its content based on the selected display size. Does that display selector have a callback function that consumers can use?
(From Caroline)
> I had some thought about height switcher, what we can do if devs will need current state of rowHeightsOptions to store it in something like saved object.
(From Vlad)
After discussion with @chandlerprall, the API we settled on was adding these callbacks in `gridStyle.onChange` and `rowHeightsOptions.onChange`.
https://user-images.githubusercontent.com/549407/144127724-c0dba6d8-6329-4a9a-b36b-15e67b931e4e.mp4
~- [ ] Check against **all themes** for …
=> [EuiDataGrid] Add `onChange` callbacks for display selector changes

src-docs/src/components/codesandbox/link.js
Closes #5433 
Correctly handles the `@emotion/react` `peerDependencies` setup for codesandbox links
=> [Docs] Add `@emotion/react` to codesandbox `dependecies`

CHANGELOG.md, src/components/popover/popover.tsx
[Per MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener): 'Removal of a capturing listener does not affect a non-capturing version of the same listener, and vice versa.'
closes #5435
This is causing a memory leak for Kibana (https://github.com/elastic/kibana/issues/120251), so we'll likely need to backport this to 7.16 and 8.0
=> [EuiPopover] Fix removeEventListener with mismatched capture flag

src-docs/src/components/guide_section/guide_section_parts/guide_section_code.tsx
Broken in https://github.com/elastic/eui/pull/5378 - the code there was only checking for `.JS` types and needed `.TSX` as well
~- [ ] Checked for **breaking …
=> [Docs] Fix broken TSX demos/CodeSandbox links

src-docs/src/index.html, src-docs/src/views/app_context.js
Seeing a difference between [eui.elastic.co](https://eui.elastic.co/#/) and all other documentation site deployments (including the [preview](https://eui.elastic.co/pr_5121/) and [versioned](https://eui.elastic.co/v42.0.0) deployments of the exact same site 🤔) with regards to global styles.
I can't really test this until it gets released, as even the preview deployment will appear fine, but my theory is that the empty `<style>` tag is being removed before bundle can reference it. Also, the `<meta>` tag is just better, as I've learned that `@emotion` will not insert styles above `<meta>` tags unless instructed.
=> [Docs] Use `<meta>` tag for global style insertion point

cypress/support/commands.js, cypress/support/index.d.ts, cypress/support/index.js, src/components/context_menu/context_menu_panel.spec.tsx, src/components/datagrid/data_grid.spec.tsx, src/components/focus_trap/focus_trap.spec.tsx
Replaces `@cypress/react`'s `mount()` API with our own custom `cy.mount()` which automatically wraps children in `<EuiProvider>`. This DRY's out each component/file having to remember to wrap a provider in order to correctly get EUI's reset styles.
Reference links:
- https://github.com/cypress-io/cypress/issues/14672#issuecomment-900825353
- https://github.com/cypress-io/cypress/blob/develop/npm/react/docs/providers-and-composition.md
N/A, dev/test-only change
=> [Cypress] Fix missing reset styles

CHANGELOG.md, src/global_styling/reset/global_styles.tsx, src/global_styling/reset/reset.ts
I noticed that the font-size of the links in our Props docs table were way too big and found that I was originally too heavy-handed with the new global styles for Emotion. Previously, it just set everything to `inherit`, while in the new file I applied our actual font styles. This broke the EuiLink font-size inheritance if the link was actually a `<button>` and rendered inside of a sized EuiText block.
**Before**
**After**
This PR pulls that `button` selector out of the input-specific font global styles and just applies the necessary `font-family`. It also ensure font-size inheritance by adding it to the `reset` file.
- ~[ …
=> [Global reset] Fix reset of `button` styles

CHANGELOG.md, src/components/code/code.testenv.tsx, src/components/code/code_block.testenv.tsx
`testenv` mocking was mistakenly removed when moving away from the shared `EuiCodeBlockImpl` component.
Previous mock file for reference: [_code_block.testenv.tsx](https://github.com/elastic/eui/pull/5379/files#diff-d54be217b09ff7e4968e0f8fb637b97ba29f16d31dfe5755d78908f24297149f)
Adds a new file for each component and adds a `data-code-language` attribute for debugging.
=> [EuiCode][EuiCodeBlock] Reinstate `testenv` mocks

src/components/date_picker/super_date_picker/async_interval.test.ts
Noticed the jest output for the _async_interval.test.ts_ complained about the `async` describe blocks. Verified that the tests themselves have been running (& passing), this is just maintenance cleaning up noise.
=> [EuiSuperDatePicker] Small unit test clean up

cypress/support/index.js, package.json, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/data_grid.spec.tsx, yarn.lock
Added some cypress tests around **EuiDataGrid**'s focus management, mostly covering the manual testing we've been doing against https://elastic.github.io/eui/#/tabular-content/data-grid-focus to catch regressions.
=> [EuiDataGrid] Added focus management cypress tests for data grid

CHANGELOG.md, src/components/provider/__snapshots__/provider.test.tsx.snap, src/components/provider/provider.tsx, src/global_styling/reset/global_styles.tsx
Makes `EuiGlobalStyles` theme-aware so that global and reset styles are not added when using the legacy theme.
Decided to do this in the component rather than in the docs because as we move forward, we'll need to account for future and custom themes potentially having different global styles. For now, we can simply use `isLegacyTheme` as the flag.
=> [EuiGlobalStyles] Omit global and reset styles when using legacy theme

CHANGELOG.md, src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/date_picker/super_date_picker/super_date_picker.test.tsx, src/components/date_picker/super_date_picker/super_date_picker.tsx
Fixes a bug where `EuiAutoRefresh` is not disabled when `EuiSuperDatePicker` is configured with `isDisabled`.
Also passes through `data-test-subj` and adds minimal tests for `isAutoRefreshOnly`.
=> [EuiSuperDatePicker] Pass `isDisabled` to `EuiAutoRefresh`

package.json, src-docs/webpack.config.js, yarn.lock
Enables react-refresh, which builds on top of hot module replacement, to reload components during development instead of requiring a whole page refresh for some changes.
From testing, this prevents a full page reload when modifying components in `src`. Utility files, service functions, etc, and documentation in _src-docs_ still trigger a reload. But when it applies, the state retention is very nice:
* switch to page 3
* shift Location column to the left
* update component
* page & column order is retained
This also enables webpack's error overlay when there are compilation issues:
=> [Docs][Proposal] Enable react-refresh in docs development

CHANGELOG.md, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/data_grid.spec.tsx
When computing the unconstrained height, now determine if a horizontal scroll is present & find its height, adding that to the datagrid contents' height. This helps address (and may close) some open issues like #4848 , but there's been a lot of movement and re-validating these issues will be necessary before closing them.
To test: in the primary data grid example, resize any of the columns so you get a horizontal scrollbar. Previously, the vertical scrollbar would be present to scroll the extra 13 pixels. Now, all the cells + horizontal scroll are rendered and no vertical scrolling is needed.
~- [ ] Props have proper **autodocs** and **[playground …
=> [EuiDataGrid] Account for horizontal scrollbar when determining height

CHANGELOG.md, package.json, src-docs/src/views/elastic_charts/accessibility_sunburst.js, src-docs/src/views/elastic_charts/pie.js, src-docs/src/views/elastic_charts/pie_example.js, src-docs/src/views/elastic_charts/pie_slices.js, src-docs/src/views/elastic_charts/treemap.js, src/themes/charts/themes.ts, yarn.lock
This PR upgrades `@elastic/charts` to `v41.0.1` which included some breaking changes. Namely, the removal of `config` from `PartitionSpec`. EUI uses this config to set default properties on the shared eui charts theme, thus throws and errors with `PartitionConfig` being removed.
The changes move all the old config overrides into the `theme.partition` sections which is a 1:1 match for all defined properties.
> Note: I'm not sure if y'all are able to backport or plan to use your latest version in `7.17` but this would be ideal for us as we plan to upgrade charts to the breaking version in `7.17`.
=> Update elastic-charts to v41.0.1

CHANGELOG.md, src/components/modal/__snapshots__/confirm_modal.test.tsx.snap, src/components/modal/__snapshots__/modal_header_title.test.tsx.snap, src/components/modal/modal_header_title.tsx
Add a check in the `modal_header_title.tsx` file to wrap `props.children` in an H1 if a string is passed into the component. Anything else (not a string) is ignored by this check. Closes #5276.
=> [EuiModal] Wrapping header in H1 if a string is returned

CHANGELOG.md, src/components/date_picker/__snapshots__/date_picker.test.tsx.snap, src/components/date_picker/react-datepicker/src/day.js, src/components/date_picker/react-datepicker/src/month.js, src/components/date_picker/react-datepicker/src/time.js
The calendar datepicker needed `role="option"` added to the individual date choices and the time picker needed an accessible label. Also revised the accessible label for the calendar to closer match the time picker. Closes #5303.
=> [EuiDatePicker] Update ARIA and role attributes for better screen reader accessibility

CHANGELOG.md, src-docs/src/views/datagrid/datagrid_example.js, src-docs/src/views/datagrid/datagrid_focus_example.js, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_context.tsx, src/components/datagrid/data_grid_types.ts
=> [EuiDataGrid] Fix cells losing focus state when scrolled out of view

CHANGELOG.md, src/components/date_picker/react-datepicker/src/time.js
Axe-core was reporting a violation for the `Time` component `ul[role="listbox"]` being contained in a DIV with a tab index. I moved the tab index to the UL and retested for keyboard navigation and screen reader usability. Closes #5296.
=> [EuiDatePicker] Moved `Time` component tabindex to UL

CHANGELOG.md, src-docs/src/views/flyout/flyout_complicated.js, src/components/form/super_select/super_select.tsx
Follow up to our [January 2022 deprecations](https://github.com/elastic/eui/issues/1469) and https://github.com/elastic/eui/pull/5214
=> [EuiSuperSelect] Remove popoverClassName and repositionOnScroll props 

src/components/context_menu/__snapshots__/context_menu_panel.test.tsx.snap, yarn.lock
This reverts commit caa769f48de1468f562c8c90a5a4fda99d1ba0de. For reasons we're still investigating, this set of changes resulted in our `dist/eui.js` increasing from 11.6 MB to 13.1 MB.
Repro steps for confirmation:
- Check out the the first commit in https://github.com/elastic/eui/pull/5459/commits
- `rm -rf node_modules && yarn && yarn build-pack`
- Inspect `dist/eui.js`'s size (should be 11.6 MB)
- Check out caa769f48de1468f562c8c90a5a4fda99d1ba0de
- `rm -rf node_modules && yarn && yarn build-pack`
- Inspect `dist/eui.js`'s size (should be 13.1 MB)
A couple extra notes from our Slack convo/investigation:
> it might be worth mentioning that I'm now seeing a warning on compilation:
> `Compiling src/ to es/, lib/, and test-env/`
> ```WARNING (@babel/preset-env): The `corejs` option only …
```
=> Revert yarn.lock changes which resulted in 1.5MB bundle increase

CHANGELOG.md, src-docs/src/views/search_bar/search_bar.js, src/components/search_bar/query/default_syntax.test.ts, src/components/search_bar/query/default_syntax.ts
See https://github.com/elastic/kibana/issues/122237 - filter values with leading or trailing spaces were resulting in buggy behavior within EuiSearchBar. The search bar should now correctly preserve leading and trailing spaces within phrases.
⚠️ I'm not sure if this is considered a breaking change, since based on the previous unit test, it's an intentional change in functionality from how it was before. Any thoughts?
Notice in particular that `owner:" dewey"` is not removing the correct filter
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documen …
=> [EuiSearchBar] Allow phrases with leading and trailing spaces

CHANGELOG.md, src-docs/src/views/selectable/selectable_custom_render.js, src-docs/src/views/selectable/selectable_example.js, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, src/components/selectable/selectable_list/_selectable_list_item.scss, src/components/selectable/selectable_list/index.ts, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_option.tsx
Convenience PR to pull out shared features in #5157 and #5387:
* Adds `isVirtualized` option to **EuiSelectableList**
* Defaults to true
* `EuiSuggest` will use `false` when implemented
* Adds `data` to **EuiSelectableList** items for passing through data
* Prevents major breaking changes to the shape of options in various components (`FieldValueSelectionFilter` and `EuiSuggest`)
* Eventually we may look to merge the shape of options to align with `EuiSelectable`
=> [EuiSelectable] `isVirtualized` and `data`

CHANGELOG.md, src-docs/src/routes.js, src-docs/src/views/datagrid/datagrid_example.js, src-docs/src/views/datagrid/datagrid_ref_example.js, src-docs/src/views/datagrid/ref.js, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_buttons.test.tsx, src/components/datagrid/body/data_grid_cell_buttons.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts
https://user-images.githubusercontent.com/549407/146981252-3c208b9b-1c8b-4c5c-bade-8176ecc3756e.mp4
https://eui.elastic.co/pr_5499/#/tabular-content/data-grid-ref-methods
What this PR does:
- Adds a `forwardRef` and `useImperativeHandle` to EuiDataGrid
- Exposes the `setFocusedCell` API **only**
What this PR does not do:
- Add a `closeCellPopover` or `openCellPopover` API (that will be the next PR, since it requires a new context for EuiDataGridCells to communicate with EuiDataGrid and a decent amount of refactoring)
- Re-focusing to the cell from the **cell popover actions** does not currently work. This is because the popover is trapping focus within the popover. This will begin working once we add the `closeCellPopover` API.
- Attempting to `setFocusedCell` to a location that is …
=> [EuiDataGrid] Set up `ref` that exposes focus/popover internal APIs

src-docs/src/views/datagrid/datagrid_ref_example.js, src-docs/src/views/datagrid/ref.js, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts
See https://github.com/elastic/eui/issues/5126 (NB: will not close this until the feature branch is merged into main)
This PR exposes our `setIsFullScreen` state to our new forwarded imperative ref API.
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
NB: Skipping the …
=> [EuiDataGrid] Add `setIsFullScreen` to ref API

CHANGELOG.md, src-docs/src/views/datagrid/focus.js, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/header/column_actions.test.tsx, src/components/datagrid/body/header/column_actions.tsx, src/components/datagrid/body/header/data_grid_header_cell.tsx, src/components/datagrid/body/header/data_grid_header_cell_wrapper.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/__mocks__/focus_context.ts, src/components/datagrid/utils/focus.ts
This PR fixes 3 bugs with EuiDataGrid around restoring correct focus/keyboard navigation to the grid:
If the user scrolls the currently focused cell out of view (via mouse) and then attempts to tab back into the grid (via keyboard), the grid should intelligently focus into the first visible and interactive cell (instead of the entire grid becoming unfocusable).
https://user-images.githubusercontent.com/549407/149015670-fce2ae61-d8e6-42fe-87e1-1bc72a71cf38.mp4
Problem: If the user hides the current column via the column header's actions popover, the popover cannot focus back into the now-removed cell, and sets the current focus back to the top of the document 
Fix: Focus should be manually set to the grid by targeting its first visible and interactive cell (which is not perfect, but at …
=> [EuiDataGrid] Fix multiple grid focus restoration issues

CHANGELOG.md, src-docs/src/views/datagrid/styling.js, src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/controls/display_selector.tsx, src/components/datagrid/data_grid.tsx
- closes #5524 (⚠️ see below `Caveat` heading)
- I recommend following along by commit, as there is some tangential cleanup in this PR.
https://user-images.githubusercontent.com/549407/148836777-79b70e9b-ec9a-46dc-b3ae-b0777a3795f6.mp4
https://user-images.githubusercontent.com/549407/148836555-9c7af405-faaa-4433-a18e-6fd203ab26b1.mp4
Note that this fix only applies to prop changes that occur **before** the user interacts with the display selector. Once the user has chosen their own settings, those user settings will always override any passed props, regardless of whether the props update later. See the below example:
- Go to https://eui.elastic.co/pr_5526/#/tabular-content/data-grid-styling-and-control (first demo)
- Open the display selector, confirm it's set to Compact and Single
- …
=> [EuiDataGrid] Update display selector UI when `gridStyle` and `rowHeightsOptions` props change

CHANGELOG.md, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/header/header_is_interactive.ts, src/components/datagrid/controls/data_grid_toolbar.test.tsx, src/components/datagrid/controls/data_grid_toolbar.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/grid_height_width.ts
closes https://github.com/elastic/eui/issues/5139
closes https://github.com/elastic/eui/issues/5131
You gotta love it when a fix just involves removing logic! 🔥 
Quick summary of changes - the previous `finalHeight = window.innerHeight - toolbarHeight - headerRowHeight - footerRowHeight` calculation likely came from pre-virtualization and is no longer necessary. There's no need for a separate `isFullScreen` logic - EuiDataGridBody's wrapper dimensions update on full screen toggle and resize correctly due to flexbox. `react-window` should simply use that wrapper's height & width, the same way it does in non-full-screen mode.
Note how bottom row is cut off and how the horizontal scrollbar does not appear after increasing the width of a column
Note how bottom row is not cut off and how the …
=> [EuiDataGrid] Fix incorrect full screen height

src-docs/src/views/datagrid/additional_controls.tsx, src-docs/src/views/datagrid/column_actions.js, src-docs/src/views/datagrid/column_cell_actions.js, src-docs/src/views/datagrid/column_widths.js, src-docs/src/views/datagrid/container.js, src-docs/src/views/datagrid/control_columns.js, src-docs/src/views/datagrid/datagrid.js, src-docs/src/views/datagrid/display_callbacks.js, src-docs/src/views/datagrid/flex.js, src-docs/src/views/datagrid/footer_row.js, src-docs/src/views/datagrid/in_memory.js, src-docs/src/views/datagrid/in_memory_enhancements.js, src-docs/src/views/datagrid/in_memory_pagination.js, src-docs/src/views/datagrid/in_memory_sorting.js, src-docs/src/views/datagrid/row_height_auto.tsx, src-docs/src/views/datagrid/row_height_fixed.tsx, src-docs/src/views/datagrid/row_line_height.tsx, src-docs/src/views/datagrid/virtualization.js, src-docs/src/views/datagrid/virtualization_constrained.js
closes https://github.com/elastic/eui/issues/5235
As the linked issue points out, we have invalid React hook usage in 2 of our datagrid demos - the main one and our footer row example - where we're nesting `useContext` and `useEffect` within a `useMemo`, which is invalid (hooks cannot be nested within a hook).
The solution I used for this is copied from one we're using in a few other places, notably our [virtualization](https://github.com/elastic/eui/blob/f67acef220f569bef1ee6e33f73f01ae1b785ef4/src-docs/src/views/datagrid/virtualization.js#L60) and row height examples where we declare `renderCellValue` outside the main component as its own React component, essentially. All other usages of `renderCellValue` in other examples do not use React hooks within their fn's and do not need to be …
=> [EuiDataGrid] Fix documentation examples with invalid React hook usage

src-docs/src/views/datagrid/datagrid_ref_example.js, src-docs/src/views/datagrid/ref.js, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_buttons.test.tsx, src/components/datagrid/body/data_grid_cell_buttons.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/body/data_grid_footer_row.test.tsx, src/components/datagrid/body/data_grid_footer_row.tsx, src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/scrolling.spec.tsx, src/components/datagrid/utils/scrolling.test.ts, src/components/datagrid/utils/scrolling.ts, src/test/test_custom_hook.tsx
The main goal of this PR is to expose APIs that allow consumers to manually control cell popovers (#5310)
However, because each cell contained its own individual popover and popover state, this required a refactor of how our cell popover architecture works:
-  Each data grid now only creates a single popover for the entire grid (instead of a popover per cell) which changes location/anchor depending on the cell that triggered it
- A top-level cell popover context now exists and which manages open/closed popover state and the popover cell location
- Each cell responds to changes in open/closed and location state to determine whether its popover should be open, and if so, it updates the top level context with its anchor (wrapping div element) and popover content (rendered cell values).
I …
=> [EuiDataGrid] Add `openCellPopover` and `closeCellPopover` to ref APIs

CHANGELOG.md, src/components/combo_box/combo_box_input/combo_box_pill.tsx, src/components/provider/__snapshots__/provider.test.tsx.snap
Our `EuiComboBox` component had a nested SVG with a tabindex -1 passed into `...closeButtonProps` that was causing axe to throw a violation. We removed the negative tabindex because the SVG is nested inside a standard button.
Closes #5545
=> [EuiComboBox][KEYBOARD]: Removing `tabindex -1` from `EuiComboboxPill` SVG

CHANGELOG.md, src/components/form/described_form_group/__snapshots__/described_form_group.test.tsx.snap, src/components/form/form_row/__snapshots__/form_row.test.tsx.snap, src/components/form/form_row/form_row.tsx, src/components/popover/input_popover.tsx, src/components/popover/popover.tsx, src/services/index.ts
Miscellaneous updates in support of #3733 and other `EuiSelectable` conversions
* **EuiFormRow**: Add referenceable `id` for the generated `label`
* `${id}-label` pattern
* Useful for `aria-labelledby`
* **EuiPopover**: Optional attribute configurations to aid screen reader announcements
* `aria-modal` + `role="dialog"` combination will steal SR focus and block announcements
* To be used in conjunction with #5567 in combobox-like implementations
* **EuiIputPopover**: Allow consumers to attach `ref`s 
* **src/services**: Convenience wildcard export
=> [a11y] Miscellaneous updates

CHANGELOG.md, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/data_grid_pagination.test.tsx, src/components/datagrid/utils/data_grid_pagination.tsx
closes https://github.com/elastic/eui/issues/5577 - please see the linked issue for a description of why the bug is happening.
Notice the black outline (in Safari) that indicates the grid wrapper is getting focused instead of into a grid cell.
Notice that the first grid data cell is now focused on every new page.
~- [ …
=> [EuiDataGrid] Fix focus on pagination

CHANGELOG.md, src-docs/src/views/drag_and_drop/drag_and_drop_complex.js, src-docs/src/views/drag_and_drop/drag_and_drop_custom_handle.js, src-docs/src/views/drag_and_drop/drag_and_drop_disable_blocking.js, src-docs/src/views/drag_and_drop/drag_and_drop_example.js, src/components/drag_and_drop/__snapshots__/draggable.test.tsx.snap, src/components/drag_and_drop/_draggable.scss, src/components/drag_and_drop/draggable.test.tsx, src/components/drag_and_drop/draggable.tsx
Our interactive elements drag and drop pattern had focusable buttons that could not be reached by keyboard, and wouldn't announce to screen readers. We also had a draggable group that was a `div[role="button"]` which was preventing keyboard navigation. I refactored both patterns to retain the existing visual design as much as possible, and add the needed updates to pass an axe check and improve keyboard and screen reader experience.
Closes #5294 
I made a visual change to the [interactive elements pattern](https://eui.elastic.co/#/display/drag-and-drop#interactive-elements) by leveraging the custom drag handle. I went this direction to fix a nested focusable element error. If the container will receive keyboard focus, the interactive element(s) will not be usable by keyboard events, and …
=> Revising drag and drop for accessible interactive and complex patterns.

CHANGELOG.md, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap, src/components/table/table_pagination/table_pagination.tsx
This attempts to address item 5 in #4458:
> 5. It looks like we also need a smarter pagination display on skinny screens/containers.
1. Go to https://elastic.github.io/eui/#/tabular-content/data-grid-virtualization
2. Click on page 200 in the first example
3. Click on page 196
4. Note how the rightmost arrow is now cut off due to the small width of the grid and the high amount of pages/content
The overflowing pagination UI can now be scrolled to.
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/documentation-guide …
=> [EuiDataGrid][EuiTables] Fix pagination potentially rendering out view on narrow tables with many pages

CHANGELOG.md, src/components/datagrid/_data_grid.scss, src/components/datagrid/controls/_data_grid_toolbar.scss
This attempts to address item 4 in #4458:
> 4. It would be great if while scrolling with virtualization which shows a white background while the cells load, we could have either add in some light gray like `$euiPageBackgroundColor`, or even some sort of pattern indication "loading".
I tried to take some screencaps but the GIFs didn't end up capturing the very subtle color change sufficiently in terms of either FPS or color swatching. It's probably easier just to compare staging vs. prod directly:
- Prod: https://elastic.github.io/eui/#/tabular-content/data-grid-virtualization
- Staging: https://eui.elastic.co/pr_5562/#/tabular-content/data-grid-virtualization
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guideli …
=> [EuiDataGrid] Change data grid body background to light gray

src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/grid_height_width.ts
Super huge kudos to @miukimiu for catching this bug before it shipped! I introduced it in https://github.com/elastic/eui/pull/5557 🙈
- Open the data grid's full screen mode
- Exit full screen mode
- Notice the grid still has the full-screen mode height
- No unit tests written, mostly due to lack of existing tests + the `IS_JEST_ENVIRONMENT` conditional
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
- No changelog needed as this bug isn't yet in main/production
=> [EuiDataGrid] Fix grid height when exiting full screen mode

src-docs/src/views/datagrid/datagrid_ref_example.js, src-docs/src/views/datagrid/ref.js, src-docs/src/views/datagrid/ref.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/header/data_grid_header_cell.test.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/ref.spec.tsx, src/components/datagrid/utils/ref.test.ts, src/components/datagrid/utils/ref.ts, src/components/datagrid/utils/scrolling.ts, src/components/datagrid/utils/sorting.ts
Follow up to https://github.com/elastic/eui/pull/5550#pullrequestreview-863950503
This should resolve the issue of `setFocusedCell` and  `openCellPopover` being called on sorted or paginated grids. It should also:
- Convert the documentation ref demo to Typescript to better catch potential type issues that our consumers may run into
- Create a full E2E suite of Cypress tests for our ref APIs
I **strongly** recommend following along [by commit](https://github.com/elastic/eui/pull/5572/commits).
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documen …
=> [EuiDataGrid] Handle exposed ref APIs potentially pointing to invalid, off-page, or out of view cells

CHANGELOG.md, src/components/form/file_picker/file_picker.tsx
~~I simply passed down the disabled prop in EuiFilePicker into it's child button components to disallow removing the files when disabled. This doesn't fix the use case of programmatically removing the file but that shouldn't matter at all since that's the expected behavior where users should be implementing that themselves.~~
Above approach introduced some inconsistent UI behavior so instead the clearButton is actually removed from the UI entirely when `EuiFilePicker` is disabled.
=> [EuiFilePicker] Fix can still be cleared when disabled

CHANGELOG.md, src/components/table/utils.ts
Adds an explicit return type of `CSSProperties` to `resolveWidthAsStyle` (table util) to avoid a verbose inferred type resulting in hundreds of `cssType` imports in the shape of:
```
WebkitTransform?: import("csstype").Property.Transform | undefined;
```
Previously, the verbosity was present, but did not use an import:
```
WebkitTransform?: string | undefined;
```
This change will eliminate ~700s line from `eui.d.ts`
=> [TypeScript] Return type for `resolveWidthAsStyle`

CHANGELOG.md, src/components/selectable/selectable_templates/selectable_template_sitewide_option.tsx
Closes #5616
Adds an explicit return type of `EuiSelectableTemplateSitewideOption[]` to `euiSelectableTemplateSitewideFormatOptions` to avoid a verbose inferred type resulting in hundreds of `<div>` and `<li>` DOM attributes and event handlers being added to the definition.
This change will eliminate ~600 lines from `eui.d.ts`
=> [TypeScript] Return type for `euiSelectableTemplateSitewideFormatOptions`

src-docs/src/views/panel/panel_example.js, src-docs/src/views/panel/panel_shadow.js
The original logic showcasing the right combination of `hasShadow` and `hasBorder` props no longer worked with the addition of EuiProvider. So I've updated this example to use `useEuiTheme` instead.
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/d …
=> [Docs] Fixing the logic for shadow and border combinations of EuiPanel

wiki/releasing-versions.md, wiki/upgrading-kibana.md
Let's start using the `ci:deploy-cloud` tag in upgrade PRs (https://github.com/elastic/kibana/pull/125023#issuecomment-1042910190)
=> [Wiki] Kibana upgrade tags

CHANGELOG.md, src-docs/src/views/range/input_only.js, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/dual_range.test.tsx, src/components/form/range/dual_range.tsx, src/components/form/range/range.test.tsx, src/components/form/range/range.tsx, src/components/form/range/range_slider.tsx
This PR adds an `isLoading` prop to **EuiDualRange**. Similar to **EuiRange** the  loading only shows if `showInput = inputWithPopover`.
Closes #5645.
=> [EuiDualRange] Add `isLoading` prop

package.json, yarn.lock
Bumps `url-parse` to `1.5.10` and `prismjs` to `1.27.0`. Also updates their `@types/` packages to latest as well.
=> [Deps] Bump url-parse and prismjs

package.json, src/components/date_picker/super_date_picker/date_popover/_absolute_tab.scss, src/themes/amsterdam/global_styling/react_date_picker/_date_picker_times.scss, yarn.lock
Brings the `known-css-properties` package used by `sass-lint` and `style-lint` (via `prettier-stylelint`) from 0.3.0 and 0.5.0 respectively to the latest 0.24.0.
Compatibility check:
* entry file between the two versions retain the same API [0.3.0](https://github.com/known-css/known-css-properties/blob/v0.3.0/index.js) / [0.24.0](https://github.com/known-css/known-css-properties/blob/v0.24.0/index.js)
* the shape of exported data is the same [0.3.0](https://github.com/known-css/known-css-properties/blob/v0.3.0/data/all.json) / [0.24.0](https://github.com/known-css/known-css-properties/blob/v0.24.0/data/all.json)
* added a `gap: 1em;` to one of the SCSS files
* 0.3.0 flags as an unknown prop
* 0.24.0 has no problems
* typo'd `gap` -> `gbp` and 0.24.0 flags as incorrect
=> Force bump known-css-properties package to 0.24.0

CHANGELOG.md, src-docs/src/views/datagrid/datagrid.js, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx
closes https://github.com/elastic/eui/issues/5583
I previously solved cell props not resetting for columns moving/re-ordering (https://github.com/elastic/eui/pull/5068), but not for columns being sorted.
~- [ ] Checked for **breaking changes** and …
=> [EuiDataGrid] Fix cell props not resetting on column sort

CHANGELOG.md, src-docs/src/views/datagrid/cell_popover_is_expandable.tsx, src-docs/src/views/datagrid/datagrid.js, src-docs/src/views/datagrid/datagrid_cell_popover_example.js, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/data_grid_types.ts
closes https://github.com/elastic/eui/issues/2793
This PR allows `isExpandable` to be set at the `cellProps` level, which lets consumers override/more granularly set `column.isExpandable`. Consumers can key off of any of the props passed to `renderCellValue`, such as rowIndex, colIndex, columnId, schema, etc.
http://localhost:8030/#/tabular-content/data-grid - note how none of the cells in the 3rd row have an expansion button, but all other cells do
~- [ ] Props have proper **autodocs** and **[playground …
=> [EuiDataGrid] Allow `isExpandable` to be set via `setCellProps`

src-docs/src/views/pagination/guidelines.js
The context menu style examples in the new Pagination Guidelines page was causing the page to auto-scroll to these examples on load because of EuiContextMenuPanel's auto-focusing behavior which is more required for when in real-use.
https://user-images.githubusercontent.com/549577/155583991-fdabff80-2fc6-424d-bdb4-bf7ab6e45501.mp4
I was able to just render the items themselves instead of passing through this component.
Go to the pagination guidelines page: https://eui.elastic.co/pr_5661/#/navigation/pagination/guidelines and ensure the page stays at the top.
=> [Pagination Guidelines] Fixed auto-focus on context menu panel by removing the panel

src-docs/src/views/copy/copy_example.js, src-docs/src/views/copy/copy_to_clipboard.js
Closes ##5573. 
This PR adds a new section in `/#/utilities/copy` called **Copy to clipboard function**.
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentati …
=> [Docs] Add `copyToClipboard` utility function docs

CHANGELOG.md, src/components/flyout/flyout.testenv.tsx
This PR only changes `testenv` file of EuiFlyout that produces a mocked version of EuiFlyout. The current mock doesn't have an `aria-label` on the close flyout button and causes "critical" a11y violations when an jest-axe test is run against any consuming components in Kibana (see https://github.com/elastic/kibana/pull/127185).
I don't think any of the items in the checklist are applicable because this PR only touches the mock file.
=> [A11y] Added `aria-label` to the flyout testenv file

CHANGELOG.md, src/components/datagrid/data_grid_types.ts, src/test/index.ts
Type fixes related to https://github.com/elastic/kibana/pull/126926
* Ensure `SharedRenderCellElementProps.schema` is optional
* `: undefined | null | string` is not the same as `?: null | string`
* https://buildkite.com/elastic/kibana-pull-request/builds/28576#62eba969-0a7f-4793-9a93-574d7641c42f
* Remove `IS_JEST_ENVIRONMENT` from `test/index.d.ts`
* It now exists in `eui.d.ts` because it's now in `utils/`
* The path was incorrect in `test/index.d.ts` (https://buildkite.com/elastic/kibana-pull-request/builds/28847#b58e4b0c-372f-4630-aba1-96c5cd67d313)
=> [Misc] Type fixes

.github/pull_request_template.md
The UX org leads have been brainstorming ideas to try to keep the Figma library from falling out of relevance. We know that the EUI members can't be **everywhere** (and honestly we hardly use the Figma library ourselves), but one thing we can be more proactive on is ensuring that we consider the Figma side when we make visual updates to the components.
As per usual checklist tasks, you can just cross this one off if it doesn't apply to your PR.
We also know that this will more than likely fall on our designer team members so please be mindful of the extra workload/communication of design changes. 
If it's not likely something to be tackled within the timeframe of the PR, there is now a Figma specific repo where we can add issues: https://github.com/elastic/eui-figma/issues
=> Added a Figma specific PR checklist item

CHANGELOG.md, src/components/selectable/selectable_templates/_selectable_template_sitewide.scss
We received feedback that the global navigational search in Kibana is hard to find. So we're opting to increase the contrast of the text as it is in the dark header and then in Kibana we'll change the placeholder text to be more specific.
- ~[ ] Checked …
=> [EuiSelectableTemplateSitewide] Increase contrast of text when in dark header

src-docs/src/views/selection_controls/guidelines.js, src-docs/src/views/selection_controls/selection_controls_example.js
This PR adds guidelines and Do/Don't examples for writing checkbox and radio button labels as well as some generic guidelines. 
- ~[ ] Checked for **breaking changes** and labeled …
=> [Docs] Add writing guidelines to selection controls

src-docs/src/views/i18n/i18n_interpolation.js, src/components/i18n/__snapshots__/i18n.test.tsx.snap, src/components/i18n/i18n.test.tsx, src/components/i18n/i18n.tsx, upcoming_changelogs/5748.md
I noticed this while attempting to QA #5743 with Babelfish checked in local dev.
=> [EuiI18n] Fixed `EuiContext.i18n`'s `mappingFunc` not being called for `EuiI18n` with multiple tokens and function callbacks

src-docs/src/views/datagrid/cells_popovers/datagrid_cells_example.js, src-docs/src/views/datagrid/cells_popovers/visible_cell_actions.tsx, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_cell_actions.test.tsx, src/components/datagrid/body/data_grid_cell_actions.tsx, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/5675.md
closes https://github.com/elastic/eui/issues/5132
Cell action buttons on the cell will only show a maximum number of actions on the cell (default limit is 2, but this is configurable via `columns.visibleCellActions`). The remaining items in the `columns.cellActions` array will only be displayed on the cell expansion popover, in a second column-style footer.
https://eui.elastic.co/pr_5675/#/tabular-content/data-grid-cell-popovers#cell-actions-and-cell-popovers
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#adding-playgro …
=> [EuiDataGrid] Enforce `visibleCellActions` shown (overflowing extra actions to the cell popover)

renovate.json
This updates the renovate configuration to re-enable updates to `@elastic/charts`. I initially tried some negative lookaheads but the `re2` package used by renovate [doesn't support lookaheads](https://github.com/renovatebot/config-help/issues/540) and then came across a [discussion](https://github.com/renovatebot/renovate/discussions/14713#discussioncomment-2380555) with an approach that worked.
I tested this by creating a [new repo](https://github.com/chandlerprall/renovate-testing) and configured renovate there by copying EUI's _renovate.json_ configuration into the [PR to enable renovate](https://github.com/chandlerprall/renovate-testing/pull/1), which provides a **What to Expect** section now listing only the `@elastic/charts` package. Prior to the proposed configuration, all 3 …
=> Update renovate configuration to include @elastic/charts

src-docs/src/views/datagrid/_datagrid.scss, src-docs/src/views/datagrid/styling/datagrid_styling_example.js, src-docs/src/views/datagrid/styling/row_classes.js, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_row_manager.test.ts, src/components/datagrid/body/data_grid_row_manager.ts, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/5732.md
closes #4401
This PR adds the ability to add specific classes/styling to certain rows, primarily for the purpose of highlighting (e.g. selections, or important row data, etc.), via a new `gridStyle.rowClasses` prop. The API of this is intentionally meant to be similar to `rowHeightsOptions.rowHeights`.
Added a gradient/striped example to show how styling differs from styling each individual cell:
=> [EuiDataGrid] Add new `gridStyle.rowClasses` API

src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, upcoming_changelogs/5761.md
This PR closes https://github.com/elastic/eui/issues/5646 by manually returning `.focus()` to the originating cell when a popover is closed by keyboard users (the escape key or the F2 key). This applies to two separate buggy use cases:
1. When VoiceOver is open (see detailed convo in #5646, this appears to be a very strange Mac/VO quirk)
2. When the user uses a **mouse** button on the expand icon to open the popover, but uses the **Escape key** to close the popover
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/docum …
=> [EuiDataGrid] When a cell expansion popover is closed, ensure focus is always returned to the originating cell for keyboard users

scripts/jest/setup/emotion.js, src/components/mark/__snapshots__/mark.test.tsx.snap, src/components/mark/mark.test.tsx
The PR #5739 called `renderWithStyles()` twice in a unit test, and it started causing an error. We decided to call `renderWithStyles()` once, and use the [Emotion/jest style checkers](https://emotion.sh/docs/@emotion/jest#tohavestylerule) to assert CSS was not present when `hasScreenReaderText` was set to false.
=> Reducing the snapshot output of EuiMark unit tests.

src/components/datagrid/body/data_grid_footer_row.spec.tsx
We have 2 tests failing intermittently in main currently affecting other branches.
=> Attempt to squash flaky EuiDataGridFooterRow tests

src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, upcoming_changelogs/5797.md
This PR essentially reverts the approach used in https://github.com/elastic/eui/pull/5681 as it is causing the Security team unintentional headaches/bugs, detailed in https://github.com/elastic/kibana/issues/128626#issuecomment-1099554165.
This PR will need to be backported to v53.0.2 and then further backported to Kibana's 8.2 branch before the next BC.
~- [ ] Checked in **mobile**~ `onFocus` should work for tap events as well …
=> [EuiDataGrid] Fix cell popover close on cell click unintentionally affecting complex cell popovers

package.json, scripts/release.js, scripts/tests/update-changelog.test.js, scripts/update-changelog.js, wiki/releasing-versions.md
I noticed some improvements to be made while doing the latest manual cherry-pick v53.0.2 backport!
1. Our changelog commits are happening **after** `npm version`, which means they're not getting included correctly in the appropriate release tag 🤦‍♀️ (fixed by 66358de31a08910b92aaa21bbcf222ffa269f0ea)
2. There's no way to manually run the changelog script outside of the release.js script, which we can't do for backport releases (fixed by 659de548e1b64092c34dbd141f2b9c5af5014e1c)
Also since I was here I added the git command to prune tags that may have been created locally as part of testing this script, since it's bitten 3 separate devs in the past, and is fairly risk-free to add (05425d5e6fc7bbd68f419dbfb9a32b3a8b887655).
yarn command
- Run `yarn update-changelog-manual`
- Run `git reset …
=> [Dev-only] Release script improvements

scripts/jest/setup/polyfills.js, src/utils/is_jest.ts
_Taking a page from Caroline's book and using an "on" Friday to go through the backlog_
Closes #3713 
Uses the check against the global `jest` namespace [mentioned therein](https://github.com/elastic/eui/issues/3713#issuecomment-771785574) rather than adding to `global`. Note that we should remove polyfill from Kibana, also, after this is released: https://github.com/elastic/kibana/blob/cf844371e4ceeae5471b8d26d073f27776545433/packages/kbn-test/src/jest/setup/polyfills.jsdom.js#L18-L20
=> [Jest] Remove `_isJest` polyfill

src/components/combo_box/combo_box.spec.tsx, src/components/combo_box/combo_box.tsx, upcoming_changelogs/5795.md
Fixes #5179 , addressing https://github.com/elastic/kibana/issues/111335
**EuiComboBox** has a custom `blur` handler to know when it should close the options popover and assumes various callbacks or other method invocations will restore focus to the input box. This change removes that assumption and explicitly restores focus.
~- [ ] Added or updated …
=> [EuiComboBox] keep focus on the combobox input when clicking disabled options

src/components/mark/__snapshots__/mark.test.tsx.snap, src/components/mark/mark.test.tsx
@constancecchen [recommended](https://github.com/elastic/eui/pull/5772#discussion_r845569689) keeping a `describe` block for two new tests that omitted CSS :before and :after helper text as part of PR #5772. This PR adds that block back for readability.
=> Adding `describe` block to EuiMark unit test that omits screen reader helper text

src/themes/amsterdam/_globals.scss, upcoming_changelogs/5820.md
The [file was removed in #5754](https://github.com/elastic/eui/pull/5754/files#diff-3f78e1899db035e3ec701f288f86d85d2b877ec1ede9f977df824f657b21c3f8) but the import statement was not. Unsure why EUI was able to compile but Kibana fails.
=> Remove missing Sass file import

scripts/release.js
Caught in the latest release, I still had a local version of the _v52.0.0_ tag from prior testing which the newly added tag fetch & prune tripped on because it was being very nice and cautious. This PR throws that caution to the wind, screams YOLO, and force prunes.
=> [Platform] Force prune local tags on release

src/services/theme/clone_element.test.tsx, src/services/theme/clone_element.tsx, src/services/theme/index.ts
`React.cloneElement` does not work when setting `css` if the cloned element does not already have the `css` prop. To support cloning `css`, we need to create an internal helper that uses `jsx()` when cloning elements in the above scenario.
See:
- https://github.com/emotion-js/emotion/issues/1404
- https://github.com/emotion-js/emotion/issues/1102
- https://emotion.sh/docs/css-prop#gotchas
Per note from @thompsongl, we're holding off on exporting this as a public API until we've tested it more thoroughly internally.
~- [ ] Checked for **accessibility** including keyboard-only …
=> [Emotion] Add internal service for cloning elements with the `css` property

wiki/writing-styles-with-emotion.md
I noticed a `const` name that needed updated to match an import statement while reviewing a separate PR. This is a one-line change for consistency.
=> Updating a const name in the Emotion wiki entry.

src-docs/src/views/accessibility/accessibility_example.js, src-docs/src/views/scroll/scroll.tsx, src-docs/src/views/scroll/scroll_x.tsx, src-docs/src/views/scroll/scroll_y.tsx, src-docs/src/views/theme/_components/_theme_example.tsx, src-docs/src/views/theme/borders/_border_js.tsx, src-docs/src/views/theme/color/_color_js.tsx, src-docs/src/views/theme/other/_animation_js.tsx, src-docs/src/views/theme/other/_shadow_js.tsx, src-docs/src/views/theme/sizing/_sizing_js.tsx, src-docs/src/views/theme/typography/_typography_js.tsx, src-docs/src/views/theme/typography/typography.tsx, src-docs/src/views/utility_classes/utility_classes_section.tsx
We've started to use the `ThemeExample` component for more than just Sass and Emotion and for actual JSX snippets.  As such I'm tweaking the logic that adds a `css` wrapper/ternary around the passed snippet to specify emotion snippets.
- NB: except in one `snippetLanguage="ts"` case which now renders the correct syntax highlighting, and a few hook snippets which I corrected to use expected Emotion syntax
=> [Docs] ThemeExample component - tweak `snippetLanguage` logic

.github/workflows/stale_issues.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src-docs/src/views/accessibility/accessibility_example.js, src-docs/src/views/accessibility/styles_helpers.tsx, src-docs/src/views/theme/_components/_theme_example.tsx, src-docs/src/views/theme/customizing/_focus.js, src-docs/src/views/theme/customizing/_values.tsx, src-docs/src/views/theme/customizing/values.tsx, src/components/panel/split_panel/_split_panel.scss, src/components/provider/__snapshots__/provider.test.tsx.snap, src/global_styling/mixins/__snapshots__/_states.test.ts.snap, src/global_styling/mixins/_states.test.ts, src/global_styling/mixins/_states.ts, src/global_styling/mixins/index.ts, src/global_styling/reset/global_styles.tsx, src/global_styling/variables/states.ts, src/services/theme/types.ts, src/themes/amsterdam/global_styling/variables/_states.ts, src/themes/amsterdam/theme.ts, upcoming_changelogs/5855.md
My general thought process here is that we want to limit the variances in focus states across components, but we know that there are some places where we at least need to adjust the position (inset/outset) of the outline or better control the `color`. This is mainly a component driven and therefore, will can be adjusted through the new function.
At the global level, however, I can see a consumer (and eventually user) wanting to adjust some of the settings more broadly like making the outline thicker or making them all a specific color. These are the only tokens that can be adjusted.
Since we "pride" ourselves in accessibility, this pattern enforces consumers to use the standard `outline` property for focus rings and standardizes them across all components for consistency.
I've re-instated …
=> [Emotion] Convert `euiFocusRing()` mixin

src/components/basic_table/basic_table.tsx
Address the following issues.
https://github.com/elastic/eui/issues/5874
=> [Docs] typo correction of basic tables

src/components/form/form.tsx, upcoming_changelogs/5866.md
Fixes #5465 
This PR has updated `EuiForm` to use the `ref` prop. No visual changes in this PR.
- ~[ ] …
=> [EuiForm] Enable `ref` Prop for EuiForm

src-docs/src/components/codesandbox/link.js, src-docs/src/theme_dark.scss, src-docs/src/theme_light.scss, src-docs/src/views/app_context.js, src-docs/src/views/guidelines/getting_started/getting_started.js
Fixes Chrome hanging on loading. I also updated the Getting Started docs to mention this `<link />` method instead of through Sass imports as well as added the link to the codesandbox setup.
=> [Docs] Moved google fonts import to `<head>`

src/components/combo_box/combo_box_options_list/_combo_box_option.scss, src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss, upcoming_changelogs/5890.md
This PR centers the enter badge in the Combo Box option, by setting `align-self` to `center`, instead of `flex-start`. Because centering the badge would actually cause the badge to not be centered with smaller `rowHeight`s, I also increased the default `rowHeight` to be `34`.
This is the badge with a default `rowHeight` of `29`, after setting `align-self` to `center`:
I believe this can be caused by the margin being set to `-4` for the EuiFlexGroup: 
This is the badge after changing the default `rowHeight` to `34`:
Closes https://github.com/elastic/eui/issues/5873
=> [EuiComboBox] Center enter badge in option

src/components/empty_prompt/__snapshots__/empty_prompt.test.tsx.snap, src/components/empty_prompt/empty_prompt.tsx, upcoming_changelogs/5907.md
In Kibana, we're using the shared No Data View empty prompt in a lot more locations. Because EuiPanel comes with `grow=true` by default **and** the prop has been excluded from EuiEmptyPrompt, it's been difficult to override this behavior when the prompt is placed in `flex-direction: column` containers (which is a lot in Kibana). 
I couldn't think of a scenario where we'd **want** the prompt to grow to fill it's container's height especially since the prompt's contents are centered in itself. So I just set `grow=false` directly in the component.
To test, you'll need to set `flex-direction: column` on a parent container.
**Before**
**After**
- …
=> [EuiEmptyPrompt] Remove `grow` from EuiPanel

src/components/search_bar/query/date_format.test.ts
In my EuiText Emotion PR, my machine ended up running a lot of tests due to downstream affected components and I saw the following flakey Jest failure more than 5 times while working on the conversion:
```
FAIL src/components/search_bar/query/date_format.test.ts
● date format › parse - day granularity
expect(received).toBe(expected) // Object.is equality
Expected: 8
Received: 7
133 |       expect(parsed.utcOffset()).toBe(0);
134 |       expect(parsed.year()).toBe(sunday.year());
> 135 |       expect(parsed.month()).toBe(sunday.month());
```
I'm honestly not clear why this is happening (greebles?) but I think it's because the previous code was looking to last Sunday whereas the new code finds this week's Sunday (https://momentjscom.readthedocs.io/en/latest/moment/02-get-set/06-day/) 🤷 TBH …
=> Attempt to squash flaky date Jest test

src/components/table/_table.scss, upcoming_changelogs/5914.md
Removes the bottom border of table headers so that it doesn't compete with the top border of cells. Everything should render exactly as it did, but now the loading state is properly aligned.
https://user-images.githubusercontent.com/549577/169591982-b6c72a72-359a-4ac8-8a0a-369f250a6984.mp4
- ~[ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/testing.md) …
=> [EuiBasicTable] Remove bottom border of table header cell

src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap, src/components/datagrid/controls/column_sorting_draggable.tsx, upcoming_changelogs/5916.md
closes https://github.com/elastic/eui/issues/5900
closes https://github.com/elastic/eui/issues/5912
- Fixes the drag handle props being repeated/nested unecessarily (probably a mistake)
- Fixes the drag handle missing an `aria-label` and triggering an axe error
=> [EuiDataGrid] Fix sorting drag handle axe errors

src-docs/src/views/drag_and_drop/drag_and_drop_example.js, upcoming_changelogs/5919.md
Adding a callout to the `EuiDraggable` custom drag handles section that outlines adding an `aria-label` for accessibility.
Closes #5911 
---
=> Adding a callout for aria-label on EuiDraggable custom drag handles.

src-docs/src/components/scroll_to_hash.tsx
From @miukimiu 
> I noticed on our site when the page load (the first time) the scroll-to functionality doesn't work as expected: https://elastic.github.io/eui/#/tabular-content/data-grid-cells-popovers#focus. It should scroll to the Focus section.
This PR adds a document readystate check to ensure DOM is done loading/shifting before scrolling to a hash section.
It also tweaks the header offset slightly account for new section spacing added in #5887
Other items are probably N/A as an internal only change
=> [Docs] Fix scroll to hash behavior

src-docs/src/views/accessibility/screen_reader_styles.tsx, src-docs/src/views/accessibility/styles_helpers.tsx, src/components/accessibility/index.ts, src/components/accessibility/screen_reader_only/index.ts, src/components/accessibility/screen_reader_only/screen_reader_only.styles.ts, src/components/highlight/__snapshots__/highlight.test.tsx.snap, src/components/mark/__snapshots__/mark.test.tsx.snap, src/components/mark/mark.styles.ts, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, upcoming_changelogs/5921.md
EuiMark's pseudo `::before/::after` elements had some custom screen reader only CSS that wasn't the actual CSS in our `.euiScreenReaderOnly` utility. The CSS we're using in our existing mixin has been battle-tested and accounts for many cross-browser shenanigans (see #5130, #5152), and we shouldn't be deviating from it.
This PR fixes the Emotion `euiScreenReaderOnly` mixin to match our Sass mixin w/ comments and then updates EuiMark to use said mixin.
Before / After:
=> [EuiMark] Fix screen-reader only CSS causing scroll issues in Chrome

scripts/jest/setup/throw_on_console_error.js, src-docs/src/components/codesandbox/link.js, src-docs/src/views/app_context.js, src-docs/src/views/provider/provider_styles.tsx
Emotion throws a bunch of errors for the `:first-child` and `:nth-child` selectors for SSR reasons: https://github.com/emotion-js/emotion/issues/1105
This PR silences those errors on Jest (db0b25a80f87a8443cbe12743253b38c336c2b9d, see https://github.com/emotion-js/emotion/issues/1105#issuecomment-1029920343) which absolutely do not need them, and also silences them in the browser (1378d1ae2ba91e7bd56d1f6d75e88454f122308c, https://github.com/emotion-js/emotion/issues/1105#issuecomment-557726922 - dev-recommended option)
No changelog as _technically_ this does not affect any source code
=> [Emotion] Squash :first-child/:nth-child errors

src-docs/src/views/selectable/search.tsx, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list.tsx, upcoming_changelogs/5926.md
This PR attempts to partially address https://github.com/elastic/eui/issues/5408 - or at least unblock Kibana so they can get a basic 'open this link if the user was holding down the shift/cmd key' behavior.
This is **not** intended to be a best/perfect solution, which would involve changing the API & markup of `EuiSelectable` significantly to allow `<a>` links and native a link behavior. This is also not a perfect screen reader solution as Kibana will likely need to provide some hidden or visible text hint to users that `shift+click` is even an option.
- Go to https://eui.elastic.co/pr_5926/#/templates/sitewide-search
- Click into input to open selectable popover
- Use the up/arrow keys to start keyboard navigating
~- [ ] Checked in …
=> [EuiSelectableTemplateSitewide] Pass keyboard/mouse event to onChange handler

.babelrc.js
Encountered a scenario where Emotion source mapping was adding 65kb to a 8kb file. Furthermore, we don't get the real benefit of source mapping because of out TypeScript compilation step (same problem we see with devtool sourcing). 
=> Turn off Emotion source mapping

cypress/plugins/webpack.config.js, src-docs/webpack.config.js
Per @cchaos's request:
<details>
<summary>Click to expand</summary>
```
Constances-MBP:eui constance$ yarn start
yarn run v1.22.18
$ cross-env BABEL_MODULES=false webpack-dev-server --config=src-docs/webpack.config.js
ℹ ｢wds｣: Project is running at http://0.0.0.0:8030/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from src-docs/build
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: Hash: dd9f82cc8b17fe7139f5
Version: webpack 4.46.0
Time: 90541ms
Built at: 05/20/2022 2:04:36 PM
Asset      Size                              Chunks                         Chunk Names
bundle.js  48.8 MiB                              bundle  [emitted]              bundle
bundle.js.map  28.4 MiB                              bundle  [emitted] [dev]        bundle …
```
=> Reduce webpack dev server output

src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.tsx, upcoming_changelogs/5935.md
This PR fixes a TypeScript error in  `EuiCollapsibleNavGroup` where `title` definition was being overridden by an extended `div` element.
- ~[ ] Checked for **accessibility** including keyboard-only and …
=> [EuiCollapsibleNavGroup] Fix TypeScript error with `title` definition

.babelrc.js, upcoming_changelogs/5947.md, yarn.lock
Used https://github.com/scinos/yarn-deduplicate to limit the number of instances of the same packages
=> Cleanup yarn.lock

src-docs/src/views/utility_classes/utility_classes_example.js
This PR fixes a link on **CSS utility classes** page. The link `Text documentation page` was pointing to an old page resulting in a 404 error.
=> [Docs] Fix link in CSS utility classes page

src/services/time/timer.test.ts, src/services/time/timer.ts, upcoming_changelogs/5954.md
closes https://github.com/elastic/eui/issues/5945
Fixes the toast disappear immediately issue.
=> [EuiGlobalToastList] Persistent toasts disappear immediately #5945

src-docs/src/views/popover/popover_panel_class_name.js, src/components/text/__snapshots__/text.test.tsx.snap, src/components/text/__snapshots__/text_align.test.tsx.snap, src/components/text/__snapshots__/text_color.test.tsx.snap, src/components/text/text.test.tsx, src/components/text/text.tsx, src/components/text/text_align.test.tsx, src/components/text/text_align.tsx, src/components/text/text_color.test.tsx, src/components/text/text_color.tsx, upcoming_changelogs/5960.md
The new cloning mechanism doesn't respect the custom `style` attribute.
**Fixed for EuiText**
=> [EuiText] Fixes custom `styles` 

src/components/call_out/__snapshots__/call_out.test.tsx.snap, src/components/call_out/call_out.tsx, src/components/form/__snapshots__/form.test.tsx.snap, upcoming_changelogs/5963.md
#5870 updated `EuiCallout` to use `EuiPanel` instead of a `div`. The `EuiPanel` configuration left `grow` to use the default value of `true` which adds `flex-grow: 1;` and consumes vertical height when possible.
This PR sets `grow={false}` on the `EuiCallout` configuration.
=> [EuiCallout] Set `grow={false}`

src-docs/src/views/app_view.js, src/components/accessibility/skip_link/__snapshots__/skip_link.test.tsx.snap, src/components/accessibility/skip_link/skip_link.styles.ts, src/components/accessibility/skip_link/skip_link.test.tsx, src/components/accessibility/skip_link/skip_link.tsx, upcoming_changelogs/5957.md
See Ryan's comment here: https://github.com/elastic/kibana/issues/38980#issuecomment-606114655
Default skip anchor links mess up hash routers, which both EUI's docs and Kibana uses. We need the ability to set a prop to override manual anchor link behavior by replicating it manually (scrolling to and focusing the destination node).
As a proof of concept, this PR also sets up skip links for our own EUI docs.
~- [ ] Updated the …
=> [EuiSkipLink] Add `overrideLinkBehavior` prop for SPA/hash routers

src-docs/src/views/theme/other/_shadow_js.tsx, src/themes/amsterdam/index.ts, upcoming_changelogs/5970.md
Somewhat a quick fix since only Sass files can be imported from `src` in the package, this PR also exports the shadows from the theme folder (but only the shadows). We may want to continue thinking about how we store these long-term.
=> Export theme-based shadows at global level

src/components/combo_box/combo_box.test.tsx, src/components/combo_box/matching_options.ts, upcoming_changelogs/5976.md
Fixes an issue that has come up twice in Kibana support. The issue is that the spread operation,
```
matchingOptions.push(...matchingOptionsForGroup);
````
was transpiled to
```
matchingOptions.push.apply(matchingOptions, matchingOptionsForGroup);
```
which overflowed the call stack size when matchingOptionsForGroup array was too large (see https://mathiasbynens.be/demo/javascript-argument-count). The fix is to use the `concat` method to merge the two arrays. Also had to update a second instance in _matching_options.ts_ with the same change.
~- [ ] Added …
=> Fix maximum call stack error for large combobox option groups

src-docs/src/views/page_template/page_template.tsx, src-docs/src/views/page_template/page_template_bottom_bar.tsx, src-docs/src/views/page_template/page_template_example.js, src-docs/src/views/page_template/page_template_sidebar.tsx, src/components/bottom_bar/bottom_bar.tsx, src/components/page_template/__snapshots__/page_template.test.tsx.snap, src/components/page_template/bottom_bar/page_bottom_bar.tsx, src/components/page_template/page_template.tsx
Since most of Kibana's usages wildly separate the content from the template, the cloning method was not going to work as it required the children to be direct descendents without any file obfuscation.
So instead, I'm creating a template context in order to pass through the top-level props like padding and restricted width. 
The exception of which is the sidebar. This needs to be a direct child because the presence of this exact element determines the configuration. I've noted this in the docs.
The bottom bar now uses `createPortal` to insert itself at the right place.
- ~[ ] Checked for **breaking changes** and labeled …
=> [Feature] Converting EuiPageTemplate to use ReactContext instead of cloneChildren

src-docs/src/views/progress/progress_example.js, src-docs/src/views/theme/color/_color_js.tsx, src-docs/src/views/theme/color/_color_sass.tsx, src-docs/src/views/theme/color/tokens.tsx
=> [EuiProgress docs] Removing callout and other fixes

src/components/accessibility/skip_link/skip_link.spec.tsx, src/components/accessibility/skip_link/skip_link.test.tsx, src/components/accessibility/skip_link/skip_link.tsx, upcoming_changelogs/5996.md
Note: Scroll jump + how black focus outline remains after clicking on the container
=> [EuiSkipLink] Improve `overrideLinkBehavior` UX

scripts/loaders/prop-loader.js
This started by looking at why `EuiPopoverPanelProps` were not showing in the props table in #5977. Turns out the code for TS->docgen was limited to a very specific type def. This PR adds support for basic `type`s and a fallback to use whatever TS gives us in other cases.
It doesn't solve `EuiPopoverPanelProps` in a great way,
but at least it shows up now and aligns with how other complex types are displayed. The basic `type` handling does include meaningful details,
```typescript
type FooProps = {
foo: string;
bar?: number;
}
```
~- [ …
=> [docs] Increased support for TS types -> props table/docgen

src-docs/src/views/datagrid/_snippets.tsx, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap, src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap, src/components/datagrid/body/header/data_grid_header_cell.tsx, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/6013.md
closes https://github.com/elastic/eui/issues/6012
This uses `displayAsText` by default, falling back to `id` (which means `title` should always be present).
=> [EuiDataGrid] Add `title` attribute to column header cell content

src/components/selectable/selectable_list/selectable_list.tsx, upcoming_changelogs/6026.md
@jeramysoucy alerted us that the 2nd `event` arg on EuiSelectable's `onChange` callback (added in https://github.com/elastic/eui/pull/5926) is not working in Kibana. This is due to Kibana being on React v16 and EUI being on React v17 (see https://reactjs.org/docs/legacy-event-pooling.html).
I tested a built version of this branch against local Kibana and can confirm event types, shiftKey, nativeEvent data etc. are now correctly coming through:
=> [EuiSelectable] EuiSelectable's onChange prop not passing a full event back on React v16

src/components/datagrid/data_grid.spec.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/utils/focus.test.tsx, src/components/datagrid/utils/focus.ts, upcoming_changelogs/6018.md
closes https://github.com/elastic/eui/issues/6008
=> [EuiDataGrid] Fix focus/scroll jump when initial data grid focus is not a keyboard tab

src-docs/src/views/datagrid/_snippets.tsx, src-docs/src/views/datagrid/basics/datagrid.js, src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/6019.md
closes https://github.com/elastic/eui/issues/6002
This PR adds support for `virtualizationOptions.onItemsRendered` as well as `virtualizationOptions.className` (figured why not, since I was here). It also adds better documentation and type-checking for the `virtualizationOptions` prop.
~- [ ] Checked for **accessibility** …
=> [EuiDataGrid] Update `virtualizationOptions` to respect `onItemsRendered` and `className`

src/components/text/__snapshots__/text.test.tsx.snap, src/components/text/text.test.tsx, src/components/text/text.tsx, upcoming_changelogs/6027.md
closes https://github.com/elastic/eui/issues/6023
Even our own `euiText` className wasn't being correctly inherited. Apologies for missing this 😬 
Before:
After:
=> [EuiText] Fix `className` not correctly inheriting when both `color` and `textAlign` are passed

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/6033.md
Please see inline code comments below that highlight changes & include screen reader before/after screencaps.
=> [EuiDataGrid] Improve `aria` row counts and indices for screen reader users

src-docs/src/views/context_menu/context_menu_example.js, src/components/context_menu/context_menu.tsx, upcoming_changelogs/6043.md
closes https://github.com/elastic/eui/issues/5980
This resolves two issues in the linked thread:
- A consumer who wants to set `width: 100%;` CSS on a non-popover'ed `EuiContextMenu` (which can be accomplished by passing `width: '100%',` on each `panels[]` object) - our typing needed to be updated to allow for all CSS values of `width`, not just numbers
- Lack of prop documentation of the `panels` prop on `EuiContextMenu`
~- [ ] Added or updated …
=> [EuiContextMenu] Fix `panels.width` prop typing to accept all CSS width values

src/components/selectable/selectable.tsx, upcoming_changelogs/6045.md
🤦 I completely missed this in #6026. Just throw my body in the trash
=> [EuiSelectable] Fix keyboard events not persisting to onChange callbacks

.github/workflows/stale_issues.yml
Adds another job to our [GitHub Stale Action](https://github.com/actions/stale) that auto-closes all issues (not PRs) marked as `answered` within 7 days. Should hopefully close certain issues faster than the stale bot normally does.
N/A, internal GitHub only change
Issue to test on: https://github.com/elastic/eui/issues/6020
=> Add new auto-close cron job for `answered` label

src-docs/src/views/text/text.js, src/components/text/__snapshots__/text.styles.test.ts.snap, src/components/text/text.styles.ts, upcoming_changelogs/6049.md
Closes #5016.
This PR adds styles for `kbd`'s within `EuiText`.
- This can be tested locally by replacing the file `src-docs/src/views/text/text.js` with the content from: https://gist.github.com/miukimiu/ed2274e98af630f46013fd767b4a9799. 
- Or just use the playground in https://eui.elastic.co/pr_6049/#/display/text.
The implementation differs a little bit from Figma because of the way the font is rendered.
=> [EuiText] Add `kbd` styles

src/components/health/__snapshots__/health.test.tsx.snap, src/components/loading/__snapshots__/loading_chart.test.tsx.snap, src/components/stat/__snapshots__/stat.test.tsx.snap, src/test/emotion-prefix.ts
I only just noticed in a current Emotion PR that Emotion sometimes output 5 character hashes 🙈 
N/A, tests only. May affect Kibana/create snapshot churn for them down the road
=> Fix some Emotion snapshots not being correctly converted to static classNames

src/components/text/__snapshots__/text.styles.test.ts.snap, src/components/text/text.styles.ts, upcoming_changelogs/6059.md
I missed converting a few of these properties in #5895 and #6049 🙈
=> [EuiText] Fix multiple missing CSS logical properties

src/components/datagrid/body/data_grid_body.test.tsx, src/components/datagrid/body/data_grid_body.tsx, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/__mocks__/row_heights.ts, src/components/datagrid/utils/row_heights.test.ts, src/components/datagrid/utils/row_heights.ts, src/services/hooks/useLatest.test.tsx, src/services/hooks/useLatest.ts
This refactors the `RowHeightUtils` tests to fix problems stemming from spies and fake timers. This has been split out of #6028.
- I refactored the way the `RowHeightUtils` receive references to various dependencies. It now receives them as `MutableRefObject`s in its constructor without the need for several imperative `set*` methods. This will make it easier to extend and mock in the future.
- The tests for the `RowHeightUtils` were not working as intended, because they used some jest features incorrectly. I tried to correct for the following problems before adding additional test cases for the new `compensateForLayoutShift` method:
- `jest.useFakeTimers` was called in several places directly in `describe` blocks, which means they're not bound to the lifecycle of the test cases. As a …
=> [EuiDataGrid] Fix row height tests and mocks

src-docs/src/views/portal/portal.js, src-docs/src/views/portal/portal_example.js, src-docs/src/views/portal/portal_insert.js
This PR fixes the CodeSandbox demos in `/utilities/portal`.
=> [Docs EuiPortal] Fix CodeSandbox demos

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body.test.tsx.snap, src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap, src/components/datagrid/body/header/data_grid_header_cell.test.tsx, src/components/datagrid/body/header/data_grid_header_cell.tsx, src/components/datagrid/data_grid.spec.tsx, src/components/datagrid/data_grid.test.tsx, upcoming_changelogs/6034.md
closes https://github.com/elastic/eui/issues/5333
**Fixes:**
- Column headers with actions were not correctly announcing their sorting status to screen readers
- Multi-sort SR announcements were not being correctly i18n'd
**Improvements:**
- Column headers without actions now report multi-sort announcements _after_ the column title, not before
- Multi-sorts now have better punctuation and general verbal flow
- The SR text for column headers with actions is more explicit/provides more guidance (`Click to view header actions`) and additionally also comes after a pause instead of being mashed together with the column title
- When using screen reader navigation/browsing to navigate grid cells, SRs would previously announce the column title as `{Title} Header Actions`. Thanks to switching to …
=> [EuiDataGrid] Fix/improve screen reader accessibility for column headers

src/components/context_menu/context_menu_panel.spec.tsx, src/components/context_menu/context_menu_panel.tsx, src/components/focus_trap/focus_trap.tsx, src/components/popover/popover.spec.tsx, src/components/popover/popover.test.tsx, src/components/popover/popover.tsx, upcoming_changelogs/6044.md
See: https://github.com/elastic/eui/pull/5977#issuecomment-1180907603
> I think what's happening is actually due to [react-focus-on's autoFocus](https://github.com/theKashey/react-focus-on#focuson) behavior. If I set EuiFocusTrap's `autoFocus={false}` when `initialFocus={false}` - focus is removed completely from the document. This is actually technically 'correct' behavior if a focus trap is enabled on the popover - because the toggling button is outside the popover, focus actually **shouldn't** have remained on it.
>
> I think the best way forward frankly (after #5784) is to remove `initialFocus={false}` as an option at all. It no longer really makes sense after its first implementation in #4768, since `false`/focusing the panel is basically the default at this point.
⚠️ **The main fix …
=> [EuiPopover] Removed `false` as an option for `initialFocus`, removed unnecessary focus logic

scripts/jest/config.json, src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx, src/global_styling/mixins/__snapshots__/_responsive.test.ts.snap, src/global_styling/mixins/_responsive.test.ts, src/global_styling/mixins/_responsive.ts, upcoming_changelogs/6057.md
It turns out I completely misunderstood how the Sass `euiBreakpoint` mixin worked!
1. Sass was capable of generating `min-width: {size} to infinity` without a max width media queries all along :upside_down_face: it just wasn't obvious because it was generating separate media queries (and accompanying CSS) for each screen size passed instead of a single media query, and `xl` was apparently the size that had no max-width set.
So, no need for new `0` or `Infinity` inputs, xs/xl essentially serve as those ranges.
2. The old JS mixin was treating input breakpoints as single one-dimensional points, while the Sass mixin treated input breakpoints as two-dimensional widths/screen sizes, i.e.
JS: `euiBreakpoint(['xs', 's'])` -> outputs `min-width of xs` and `max-width of s - 1px`
Sass: …
=> [Emotion] Fix `euiBreakpoint` behavior to match Sass mixin

src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_search/selectable_search.test.tsx, src/components/selectable/selectable_search/selectable_search.tsx, upcoming_changelogs/6072.md
This PR also contains 2 other small fixes / cleanups (see commit history).
`EuiSelectable.onSearchChange` was being called on mount by `EuiSelectableSearch`, which was setting `activeOptionIndex` to undefined:
https://github.com/elastic/eui/blob/eb493ffc41feb968602ebf5087694475e6a2d082/src/components/selectable/selectable.tsx#L423-L432
Moving the `searchProps.onChange` callback to the `EuiSelectable`'s constructor (which calls `getMatchingOptions`/sets search state on mount anyway, so no need for `EuiSelectableSearch` to repeat it) fixes the issue and leaves the found `activeOptionIndex` from the constructor intact.
~- [ ] Props have proper …
=> [EuiSelectable] Fix searchable single selection selectables not correctly highlighting the checked option on initial render

src-docs/src/views/comment/comment.tsx, src-docs/src/views/comment/comment_actions.tsx, src-docs/src/views/comment/comment_avatar.tsx, src-docs/src/views/comment/comment_example.js, src-docs/src/views/comment/comment_flexible.tsx, src-docs/src/views/comment/comment_list.tsx, src-docs/src/views/comment/comment_props.tsx, src-docs/src/views/comment/comment_system.tsx, src-docs/src/views/copy/copy_to_clipboard.js, src/components/avatar/__snapshots__/avatar.test.tsx.snap, src/components/avatar/avatar.tsx, src/components/comment_list/__snapshots__/comment.test.tsx.snap, src/components/comment_list/__snapshots__/comment_event.test.tsx.snap, src/components/comment_list/__snapshots__/comment_list.test.tsx.snap, src/components/comment_list/__snapshots__/comment_timeline.test.tsx.snap, src/components/comment_list/comment.test.tsx, src/components/comment_list/comment.tsx, src/components/comment_list/comment_event.tsx, src/components/comment_list/comment_timeline.test.tsx, src/components/comment_list/comment_timeline.tsx, src/components/timeline/__snapshots__/timeline.test.tsx.snap, src/components/timeline/__snapshots__/timeline_item.test.tsx.snap, upcoming_changelogs/6071.md
This PR reverts the **EuiComment**'s `username` prop to accept a `ReactNode` instead of a `string`. 
Not having the `username` as a string makes it impossible to have a `timelineIcon` defaulting to the `username`'s initials. So the `timelineAvatar` now defaults to an avatar with a `userAvatar` icon.
This example reflects more on the current implementation for **Cases**:
Consumers can now pass a `ReactNode` to show the username with a tooltip and or avatar. As they doing in **Cases**
One of the reasons I was trying to have the `username` as a `string` is that I could pass the username as a name to the `timelineAvatar` Having the username reverted to a `ReactNode` turns this impossible.
For this reason, I created a new prop called `timelineAvatarAriaLabel`  that should be passed for each …
=> [EuiComment] Revert `username` prop to accept a `ReactNode`

src/components/filter_group/__snapshots__/filter_button.test.tsx.snap, src/components/filter_group/filter_button.tsx, upcoming_changelogs/6076.md
@Heenawter reported an axe violation in EUI issue #6011 for the `EuiFilterButton` component. I solved this issue by adding a role of "marquee" to the badge inside the button. This felt like the correct role [based on MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/marquee_role) and will be non-breaking change.
Closes #6011
=> [BUG]: Adding `role=marquee` to `EuiFilterButton`

scripts/release.js
The build's `compile-scss` step includes generating _eui_theme_light.json_ and _eui_theme_dark.json_ token/value maps. This dirties the git workspace and interrupts following actions during a release.
Testing:
* copy the new `commitThemeTokens` function into _scripts/test.js_ and call it in the script
* update [`$euiBreadcrumbSpacing`](https://github.com/elastic/eui/blob/main/src/components/breadcrumbs/_variables.scss#L1)'s definition
* run `yarn compile-scss`
* verify the json token files are dirty
* run `node scripts/test.js`
* verify the json files are no longer dirty, and that a new _update theme json tokens_ commit exists
=> Track changes to json theme files during release

src/components/empty_prompt/_empty_prompt.scss, src/components/image/__snapshots__/image.test.tsx.snap, src/components/image/image_caption.tsx, src/components/image/image_wrapper.styles.ts, upcoming_changelogs/6081.md
closes https://github.com/elastic/eui/issues/6080
~- …
=> [EuiImage] Fix empty `figcaption`s and non-centered EuiEmptyPrompt images

wiki/upgrading-kibana.md
I noticed Kibana no longer seems to type check on `kbn bootstrap` - it's a little faster to run type checks locally than it is to wait for the full Kibana CI, so I thought adding this script reference would be helpful.
N/A, internal docs only
=> [Wiki] Add script for running Kibana type checks

scripts/release.js
I noticed while doing a patch release today that the prompt copy is off:
The version in pink should be 62.0.1, not 62.0.0. Not a huge deal, but reduces some confusion / a tiny moment of 'oh no did choose the wrong release type'.
N/A, internal only
=> Tweak release script prompt

src/components/badge/beta_badge/beta_badge.tsx
Fixes #6085, which highlights that sometimes `ExclusiveUnion` does weird things. When using `type` the interface will be accessible as part of the eventual export, but not when using `interface`.
**Local testing:**
* In Kibana, add `export const BetaBadgeTest = EuiBetaBadge;` to `x-pack/plugins/infra/public/components/beta_badge.tsx`
* Confirm a type error about `LabelAsString`
* In EUI, run `node scripts/dtsgenerator.js`
* Copy the resuting `eui.d.ts` and paste into Kibana's `eui.d.ts`
* Confirm the type error is resolved
=> [EuiBetaBadge] Change `LabelAsString` from  interface to type

src/components/comment_list/__snapshots__/comment.test.tsx.snap, src/components/comment_list/__snapshots__/comment_event.test.tsx.snap, src/components/comment_list/__snapshots__/comment_list.test.tsx.snap, src/components/comment_list/comment_event.styles.ts, src/components/comment_list/comment_event.tsx, upcoming_changelogs/6089.md
Several Kibana tests and CSS overrides were targeting these classNames: https://github.com/elastic/kibana/pull/136865/commits/1bdae6b56507a78de66f7250d5e99ddaaec9e514
After some team discussion on Slack, we've decided that for the Emotion conversion, we're generally opting to **not** remove `__child` classNames (especially on DOM elements that aren't customizable via consumers/props). They serve as useful hooks/markers for consumers to use.
Modifier `--` classNames, especially maps, are fair game to be removed especially if replaced by a `data-` attribute (I've added one here for event types), but should be checked in Kibana first for usage.
While I was here I did some minor code cleanup. The first 2 commits (+ snapshots) are the only required changes
=> [EuiCommentEvent] Restore child classNames removed in Emotion conversion

scripts/jest/setup/mocks.js, src/components/observer/resize_observer/resize_observer.testenv.tsx, src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap, src/components/tool_tip/tool_tip.test.tsx, src/components/tool_tip/tool_tip_popover.tsx, src/test/rtl/component_helpers.ts, upcoming_changelogs/6106.md
This PR:
- Improves our EuiToolTip tests to actually snapshot the rendered tooltip content
- Converts our tooltip tests to RTL while still maintaining a single Enzyme test for legacy/portal regression testing
- Exports new RTL `waitForEuiToolTipVisible` and `waitForEuiToolTipHidden` test helpers
- Closes https://github.com/elastic/eui/issues/6065
=> [EuiToolTip] Convert tests to RTL and export tooltip RTL helpers

src-docs/src/views/theme/_props.tsx, src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx, src-docs/src/views/theme/breakpoints/breakpoints.tsx, src-docs/src/views/theme/customizing/_breakpoints.js, src/global_styling/mixins/_responsive.test.ts, src/global_styling/mixins/_responsive.ts, src/global_styling/variables/breakpoint.ts, src/services/breakpoint/_sorting.test.ts, src/services/breakpoint/_sorting.ts, src/services/breakpoint/breakpoint.ts, src/services/breakpoint/currentEuiBreakpoint.spec.tsx, upcoming_changelogs/6111.md
Despite our CSS-in-JS documentation noting it as such, our current EuiProvider does not actually support extra keys being added to our `breakpoint` map, e.g. `xxl`, `xxxl`, `xxs`, etc.
This is primarily because our `getBreakpoint` logic (which depended on the map being statically ordered from largest to smallest) was no longer in order when dynamic values were added. If our `breakpoint` maps can be anything, we need to dynamically order them as we get them to obtain the behavior we want.
http://localhost:8030/#/theming/breakpoints/values#custom-values (TODO: replace w/ staging link)
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#adding-playground-togg …
=> [Emotion][Theming] Add support for added custom theme breakpoints

src-docs/src/components/guide_section/guide_section.tsx, src-docs/src/components/guide_section/guide_section_parts/guide_section_text.tsx, src-docs/src/index.js, src-docs/src/services/index.js, src-docs/src/services/routing/scroll_to_hash.ts, src-docs/src/views/accessibility/screen_reader_live.tsx, src-docs/src/views/app_view.js, src/components/accessibility/screen_reader_live/__snapshots__/screen_reader_live.test.tsx.snap, src/components/accessibility/screen_reader_live/screen_reader_live.tsx, src/components/selectable/__snapshots__/selectable.test.tsx.snap, upcoming_changelogs/6133.md
closes https://github.com/elastic/eui/issues/6115
I recommend [following along by commit](https://github.com/elastic/eui/pull/6133/commits), as this PR has several tweaks and an incidental `EuiScreenReaderLive` fix (required to get this PR working).
This was the broken experience in #6115. Repro steps:
1. Search for, e.g. "humor" in the sidebar
2. Click the **third level** hash subsection in the sidebar
3. On production, this was not correctly scrolling to the hash section due to the `EuiScreenReaderLive` stealing focus
Fixed behavior: (**Note**: GitHub starts video auto-muted, unmute to hear VoiceOver narration)
https://user-images.githubusercontent.com/549407/184252511-0a6e7251-30a3-47ad-af03-2bd585e3760d.mov
NOTE: Safari + VO treats the polite non-focused live region correctly (waiting …
=> [Docs] Fix scrollToHash focus fighting

wiki/screen-reader-testing-matrix.md
Creating a wiki page for screen reader testing by priority tiers. This matrix was created based on my cloud analytics gathered in July 2022.
=> Create screen reader testing matrix MD.

package.json, src-docs/src/views/app_context.js, src-docs/src/views/guidelines/getting_started/getting_started.js, src/components/provider/cache/__snapshots__/cache_provider.test.tsx.snap, src/components/provider/cache/cache_provider.test.tsx, src/components/provider/cache/cache_provider.tsx, upcoming_changelogs/6126.md, wiki/consuming.md
closes https://github.com/elastic/eui/issues/6113
#5920 did not account for consumers who do not pass a cache tag to `<EuiProvider>`. This PR fixes the first-child/nth-child console warnings for that scenario, ~using the "Option 3" method recommended by https://github.com/emotion-js/emotion/issues/1105#issuecomment-557726922~ by creating our own default cache.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs …
=> [Emotion] Use default cache for consumers who do not pass a cache to EuiProvider

src/components/date_picker/date_picker_range.test.tsx, src/components/date_picker/date_picker_range.tsx, upcoming_changelogs/6136.md
Fixes #6128 which has a detailed description of the error and how to replicate it.
- Destructures `onBlur` and `onFocus` to ensure they're not scooped up by the rest parameter and fed to containing `div` element.
- Uses lodash's [over](https://lodash.com/docs/4.17.15#over) method to create handlers that will trigger callbacks for both `EuiDatePicker` and `EuiDatePickerRange`. It's worth noting that `over` gracefully handles array elements that aren't functions, and ignores them. This means we don't need to worry about any of the handlers not being defined.
_Note: I contemplated writing these tests in Cypress as I think ultimately it's a better, more user-centric test but the entirety of the date picker suite runs using Enzyme so I've opted for consistency here._
=> [EuiDatePickerRange] Applying onFocus/OnBlur handlers to inner EuiDatePicker components

src/components/header/header.tsx, src/components/page/page_sidebar/page_sidebar.tsx, src/components/page_template/page_template.tsx, upcoming_changelogs/6140.md
Related to #5768
Closes #6138
`EuiPageTemplate` expects the `data-fixed-headers` attribute is to exist, but the attribute is only managed by `EuiHeader`. The fix is to have a fallback value for when `EuiHeader` is not in use. Also updated the method by which the attribute is managed (`setAttribute` to `dataset`).
For verification, you'll need something other than the docs site. I used CRA with the `build-pack` output and the simple [`App.tsx` from the issue](https://github.com/elastic/eui/issues/6138#issue-1338189645).
=> [EuiPageTemplate] Fix `data-fixed-headers` usage

src-docs/src/views/guidelines/accessibility.js
I added a section to our `Accessibility` documentation for disabled elements. It mentions specifically adding the `disabled` attribute or passing `isDisabled` to EuiAccordion and users' responsibility to not include focus interactions.
=> [DOCS] Adding a11y documentation for disabled elements

src/components/aspect_ratio/__snapshots__/aspect_ratio.test.tsx.snap, src/components/aspect_ratio/aspect_ratio.test.tsx, src/components/aspect_ratio/aspect_ratio.tsx, upcoming_changelogs/6141.md
The video on https://elastic.github.io/eui/#/guidelines/accessibility was not working correctly due to the `height: 100%` set (which was attempting to inherit height from the parent div which had a `flex-direction: column;` set).
If we're using the `aspect-ratio` css (see #5818), we shouldn't be using `height: 100%` - we should be using `height: auto` due to setting `width: 100%`, the same way an img tag gets treated essentially.
I also noticed 2 more things while adding this fix:
1. Any custom `style`s getting set by the consumer were not correctly being spread, and
2. The `div` wrapper for `max-width` is also unnecessary if we're using the `aspect-ratio` CSS property: because it now behaves the same way as an img tag, the max-width can be set directly on the iframe.
~- [ ] Checked in …
=> [EuiAspectRatio] Fix incorrectly inherited height and ignored `style` prop

scripts/dtsgenerator.js, upcoming_changelogs/6142.md
Required for https://github.com/elastic/kibana/pull/138837
The exclude glob pattern for the `d.ts` generator script was not accounting for nested directories with TS files. The result was that `src/test/rtl/` and `src/test/internal/` files and types were included in `eui.d.ts` (like, specifically the ones we _don't_ want to include 🙈) and in turn included problematic types from RTL that interfere with other testing lib type definitions.
Verification:
* Checkout the `v62.2.1` tag
* `yarn`
* Generate a new `eui.d.ts` 
* Drop that `eui.d.ts` in the [Kibana upgrade branch](https://github.com/elastic/kibana/pull/138837)
* Type errors related to `this` in, say `test/functional/apps/console/_autocomplete.ts` should be resolved
=> [eui.d.ts] Exclude all of `src/test`

src/components/description_list/description_list_description.tsx, src/components/description_list/description_list_title.tsx
Required for https://github.com/elastic/kibana/pull/138837
Instances of `EuiDescriptionListDescription` and `EuiDescriptionListTitle` are styled with `styled-components` and the prop type cannot be correctly accessed because the interface is not exported.
> Exported variable 'MonListTitle' has or is using name 'EuiDescriptionListTitleProps' from external module "@elastic/eui/src/components/description_list/description_list_title" but cannot be named.
Local export resolves the problem
=> [EuiDescriptionList] Export subcomponent prop interfaces

src-docs/src/views/scroll/full_height.tsx, src-docs/src/views/scroll/scroll_example.js, src-docs/src/views/scroll/scroll_x.tsx, src-docs/src/views/scroll/scroll_y.tsx, src/components/breadcrumbs/breadcrumb.styles.ts, src/components/image/image_button.styles.ts, src/components/link/link.styles.ts, src/components/text/text.styles.ts, src/components/toast/global_toast_list.styles.ts, src/global_styling/functions/__snapshots__/logicals.test.ts.snap, src/global_styling/functions/logicals.test.ts, src/global_styling/functions/logicals.ts, src/global_styling/mixins/__snapshots__/_typography.test.ts.snap, src/global_styling/mixins/_helpers.scss, src/global_styling/mixins/_helpers.ts, src/global_styling/mixins/_states.ts, src/global_styling/mixins/_typography.ts, src/global_styling/reset/global_styles.tsx, src/global_styling/utility/__snapshots__/utility.test.tsx.snap, src/global_styling/utility/_utility.scss, src/global_styling/utility/utility.test.tsx, src/global_styling/utility/utility.tsx, upcoming_changelogs/6124.md
I strongly recommend [following along by commit](https://github.com/elastic/eui/pull/6124/commits), as I did a few extra side cleanup items (missing logical properties, mixin API updates, documentation) alongside the global conversions.
=> [Emotion] Convert global `className` utilities

src-docs/src/views/tables/actions/actions.js, src/components/basic_table/collapsed_item_actions.tsx, upcoming_changelogs/6145.md
The `registerPopoverDiv` callback was not accounting for `null` as a possible return value.
In the scenerio where `popoverDiv` is `null` and `this.popoverDiv` is not defined, we would attempt to add an event listener to `null`, which results in a type error.
Solution is to update the type and logic to account for `null`
=> [CollapsedItemActions] Account for `null` ref object

src/components/description_list/__snapshots__/description_list_title.test.tsx.snap, src/components/description_list/description_list_title.tsx, upcoming_changelogs/6160.md
Resolved a bug that caused `compressed` styles not to be applied to text in the original Emotion conversion of `EuiDescriptionList`. The text within the `DescriptionListTitle` and `DescriptionListDescription` should be 14px when the DescriptionList is compressed.
**Resolved: Text = 14px**
**Previous: Text = 16px**
=> [EuiDescriptionListTitle] Fix compressed styles not being correctly applied

src/components/datagrid/_data_grid_data_row.scss, upcoming_changelogs/6163.md
closes https://github.com/elastic/eui/issues/6151 - see issue for more discussion/context
=> [EuiDataGrid] Fix missing cell popover shadows in Safari

src-docs/src/views/theme/color_mode/color_mode_example.js, src-docs/src/views/theme/color_mode/inverse.tsx, src-docs/src/views/theme/color_mode/inverse_complex.tsx
Closes #6123.
This PR adds better docs in  https://eui.elastic.co/pr_6155/#/theming/color-mode to show how to use components like **EuiText** and **EuiIcon** in a specific color mode. 
The last example shows how to use color variables.
=> [Docs] Better docs for color mode

src/components/icon/icon.tsx, upcoming_changelogs/6166.md
Fixes #6099 
React.StrictMode, used by Create React App & others, does interesting things around component creation, mounting, and re-use in development mode to enforce lifecycle best practices. **EuiIcon** was setting its `isMounted` property in the wrong place which led to no icons loading in some development environments (I was never able to reproduce the issue in EUI docs), as StrictMode would mount->unmount->mount components, causing **EuiIcon** to throw away the async icon when it loaded.
I tested this by manually changing _node_modules/@elastic/eui_ in a create-react-app, and confirmed the change (also applied manually) resolved this issue in an internal Elastic project.
~- [ ] Checked in **Chrome**, …
=> [EuiIcon] Correct isMounted logic

src/components/basic_table/basic_table.tsx, src/components/basic_table/table_types.ts, src/components/card/card.styles.ts, src/components/datagrid/body/header/_data_grid_header_row.scss, src/components/description_list/description_list_description.styles.ts, src/components/description_list/description_list_title.styles.ts, src/components/filter_group/_filter_group.scss, src/components/flex/_flex_group.scss, src/components/flex/_flex_item.scss, src/components/form/field_search/_field_search.scss, src/components/list_group/_list_group_item.scss, src/components/table/_table.scss, src/components/table/table_row_cell.tsx, src/global_styling/mixins/__snapshots__/_typography.test.ts.snap, src/global_styling/mixins/_form.scss, src/global_styling/mixins/_helpers.scss, src/global_styling/mixins/_typography.scss, src/global_styling/mixins/_typography.ts, src/global_styling/utility/__snapshots__/utility.test.tsx.snap, src/global_styling/utility/_index.scss, src/global_styling/utility/_utility.scss, upcoming_changelogs/6154.md
This PR is a follow-up to #6124, by removing the `_utility.scss` file completely (removing `.euiIEFlexWrapFix`) and removing the `internetExplorerOnly()` mixin.
This PR also removes several fairly innocuous IE fallbacks/workarounds. There are more in the codebase, but I decided to open multiple PRs rather than just one. The next PR will handle IE flex fallbacks/workarounds specifically, and a 3rd PR will handle IE fallbacks/workarounds in our JS code.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works …
=> Remove IE CSS utilities, mixins, and non-flex/sizing fallbacks

src/components/icon/icon.tsx, src/services/theme/hooks.test.ts, src/services/theme/hooks.tsx, upcoming_changelogs/6165.md
Fixes #6159 
Threw a console.log in **EuiIcon**'s render and verified any time its owner component rendered, the icon would unexpectedly re-render as well. Narrowed it down to a different `theme` prop coming in from `withEuiTheme` on every render, and traced object creation to both `useEuiTheme` and `withEuiTheme`.
* `withEuiTheme` updated to forward `useEuiTheme`'s return value into the wrapped component
* `useEuiTheme` updated with a `useMemo` to keep the resulting object stable
* added a unit test for regression
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidel …
=> [useEuiTheme] return a memoized object for performance

src/components/flex/_flex_group.scss
💀 Turns out this affects modern browsers, not just IE: 
No changelog as #6161 has not yet been released
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
=> [EuiFlexItem] Revert flex-basis unitless 0 CSS change

src/components/header/header_section/__snapshots__/header_section_item.test.tsx.snap, src/components/header/header_section/_header_section_item.scss, src/components/header/header_section/header_section_item.test.tsx, src/components/header/header_section/header_section_item.tsx, upcoming_changelogs/6158.md
While working on the guided onboarding [project](https://github.com/elastic/kibana/issues/138557), I noticed that when a header section item is empty, it's still rendered with a `min-width` setting. Instead we only render this component, if it's not empty.
=> Set min-width on header section items only when they are not empty

src-docs/src/components/guide_page/_guide_page.scss, src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/services/routing/scroll_to_hash.ts
I recommend [following along by commit](https://github.com/elastic/eui/pull/6177/commits)!
Note how the tooltip and utility links do not actually stay in view
Side nav now always resets to the top of the scroll container
~- [ ] Checked for **breaking …
=> [Docs] Fix sidenav scroll position resetting on every page change + fix nav on mobile

src-docs/src/components/guide_page/guide_page_header.tsx
In the spirit of fixing small screen bugs...
On larger small screens:
**Before:**
**After:**
=> [Docs] Fix small screen layout in "other" nav popover

src/components/page/page_sidebar/page_sidebar.test.tsx, src/components/page/page_sidebar/page_sidebar.tsx, upcoming_changelogs/6191.md
This PR fixes an issue that Caroline was running into in her EuiPageTemplate Kibana upgrade PR (https://github.com/elastic/kibana/pull/138546):
The reason why `minWidth` isn't updating downstream in Kibana is because `sticky` is not set in Kibana, and `EuiPageSidebar` has buggy logic causing inline styles not to be correctly updated if `sticky` is not set.
=> [EuiPageSidebar] Fix inline styles not updating if `sticky` is not set

src-docs/src/views/form_controls/guidelines.js
This PR expands the guidelines for hint text. Provides a recommendation for text length.
=> Expands the guideline for hint text

src/components/page/page_section/__snapshots__/page_section.test.tsx.snap, src/components/page/page_section/page_section.test.tsx, src/components/page/page_section/page_section.tsx, src/components/page_template/bottom_bar/__snapshots__/page_bottom_bar.test.tsx.snap, src/components/page_template/empty_prompt/__snapshots__/page_empty_prompt.test.tsx.snap, upcoming_changelogs/6192.md
It seems incredibly bizarre to have a component named `EuiPageSection` that doesn't actually use the `<section>` tag for semantic meaning.
If for some reason `<section>` is not applicable, we should support overriding the tag via the `component` prop (already used as a paradigm in `EuiPageTemplate` to override `<main>`).
~- [ ] Checked for **accessibility** including keyboard-only and …
=> [EuiPageSection] Add `component` prop, default to `section` tag

src/components/page/page_content/page_content.tsx, src/components/page/page_content/page_content_body.tsx, src/components/page/page_content/page_content_header.tsx, src/components/page/page_content/page_content_header_section.tsx, src/components/page/page_side_bar/page_side_bar.tsx, src/components/page/page_template.tsx, upcoming_changelogs/6194.md
Using the `@deprecated` jsdoc flag will be picked up by supporting IDEs (VSCode, possibly webstorm as well) and add a strikethrough in both import and component usage:
This will be relatively useful in encouraging Kibana consumers to switch over from deprecated components sooner rather than later.
N/A - technically this is not an actual source-code-affecting change and only affects development 🤔
=> [EuiPage*_Deprecated] Use `@deprecated` flag

src/components/provider/__snapshots__/provider.test.tsx.snap, src/components/provider/cache/__snapshots__/cache_provider.test.tsx.snap, src/components/provider/cache/cache_provider.test.tsx, src/components/provider/cache/cache_provider.tsx, src/components/provider/provider.test.tsx, src/components/provider/provider.tsx, upcoming_changelogs/6202.md
Having the fallback cache configured for each `EuiCacheProvider` broke the context "bubbling" fallback assumed by `EuiProvider`, resulting in the `defaultCache` in `EuiProvider` not being the catch-all location for Emotion styles. The net effect is that global styles were being inserted after component styles when not configured with `EuiProvider.cache.global` (such is the case in the docs).
The fix is to move the fallback to be the default prop value in `EuiProvider` rather than `EuiCacheProvider`.
Also, the `defaultCache` will always get `compat=true`, even if consumers forget to add it.
**Before**
**After**
=> [EuiProvider] Change location of fallback Emotion cache

src-docs/src/views/notification_event/notification_event_example.js, src/components/notification/__snapshots__/notification_event.test.tsx.snap, src/components/notification/notification_event.test.tsx, src/components/notification/notification_event.tsx, upcoming_changelogs/6208.md
Closes #6206. This PR spreads the `className` and `rest` props on `EuiNotificationEvent`
=> [EuiNotificationEvent] Spread `className` and `rest` props

wiki/upgrading-kibana.md
Writes down the process for handling flaky Cypress team tests that aren't caused by us/EUI. Also updates approval process to reflect that the EUI team can no longer admin merge in Kibana
N/A, docs only
=> Update upgrading kibana wiki

src-docs/src/views/_index.scss, src-docs/src/views/selectable/selectable_templates/_sitewide.scss, src-docs/src/views/selectable/selectable_templates/sitewide_search.tsx, src/components/button/button_display/_button_display.tsx, src/components/button/button_empty/button_empty.tsx, src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx, src/components/expression/expression.tsx, src/components/image/image_types.ts, src/components/page/page_section/page_section.tsx, src/components/progress/progress.tsx, src/components/resizable_container/resizable_panel.tsx, src/components/side_nav/side_nav.tsx, upcoming_changelogs/6211.md
#6118 extended `CommonProps` to allow the `css` Emotion prop for Emotion-based styling, but not all nested `*Props` were correctly extending CommonProps. I did a quick grep for `Props?:` and checked for types that were not extending CommonProps.
The second commit of this PR addresses https://github.com/elastic/eui/pull/6074#discussion_r929187329 (figured I'd grab that while I was here).
As this is not a change that affects end-users, I'm not 100% sure if we need a changelog for this, but including in any case
=> Fix various nested `componentProps` to accept the `css` prop type

src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap, src/components/search_bar/query/ast_to_es_query_dsl.ts, upcoming_changelogs/6220.md
This replaces a single match query with bool `should` or `must` logic in Query.toESQuery().    As a match query, fields with non-text mappings were failing search due to reliance on a text analyzer which doesn't exist in that case.
closes https://github.com/elastic/eui/issues/6217
=> [SearchBar] Use bool query instead of match bool logic

src/components/button/button.tsx, src/components/button/button_display/_button_display.styles.ts, src/components/button/button_display/_button_display.tsx, src/components/card/card.styles.ts, src/components/card/card.tsx, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select.test.tsx.snap, src/components/popover/__snapshots__/popover_title.test.tsx.snap, src/components/popover/popover_title.styles.ts, src/components/popover/popover_title.tsx, src/components/tour/__snapshots__/tour_step.test.tsx.snap
See https://github.com/elastic/eui/pull/6213#discussion_r965200619 for more context
- **EuiButton**: custom `minWidth`s should be a `style` tag and not an Emotion class, for the same reason we inline custom `color`s on components (we're otherwise generating a potentially infinite number of classes)
- **EuiPopoverTitle**: the `paddingSize` on this can be easily be converted into a static list of keys without sacrificing readability
- **EuiCard**: the `display` arg can be easily removed in favor of an array conditional instead, but the `paddingSize` cannot (this instance is a good example of when dev readability trumps Emotion performance, especially since paddingSize can only be one of 7 options and is not as wildcard as, e.g. minWidth or color)
- Skipping changelog on this one as this is …
=> [Emotion] Remove misc unnecessary args from Emotion style functions

src-docs/src/views/search_bar/props_info.js, src-docs/src/views/search_bar/search_bar_filters.js, src/components/search_bar/filters/__snapshots__/custom_component_filter.test.tsx.snap, src/components/search_bar/filters/custom_component_filter.test.tsx, src/components/search_bar/filters/custom_component_filter.tsx, src/components/search_bar/filters/filters.tsx, src/components/search_bar/query/ast.ts, src/components/search_bar/query/query.ts, upcoming_changelogs/6226.md
This PR adds a new filter type to the Search bar: `custom_component`. This filter gives full control to the consumer to render the filter button + the panel.
Fixes https://github.com/elastic/eui/issues/6003
```js
const CustomComponent = ({ query, onChange }) => {
// Access to the Query instance and the onChange handler to update the search bar
const [isOpen, setIsOpen] = useState(false);
const closePopover = () => {
setIsOpen(false);
};
const button = (
<EuiFilterButton
iconType="arrowDown"
iconSide="right"
onClick={() => setIsOpen((prev) => !prev)}
hasActiveFilters={<some-internal-state>}
numActiveFilters={<some-internal-state>}
grow
>
Filter label
</EuiFilterButton>
);
return (
<EuiPopover
button={button}
isOpen={isOpen}
closePopover={closePopover}
panelPaddingSize="none" …
```
=> [SearchBar] Add custom_component filter

src-docs/src/views/tables/data_store.js, src/components/basic_table/in_memory_table.test.tsx, src/components/basic_table/in_memory_table.tsx, upcoming_changelogs/6228.md
Fixes #6032 by updating **EuiInMemoryTable**'s `getDerivedStateFromProps` to update the sort details in prevProps as necessary.
~To be honest, I'm not sure how to write a meaningful test for this. @sebelga can you extract your use case to a simple test scenario? (just describing it should be fine, I can put the test together)~ …
=> [EuiInMemoryTable] Update state.prevProps.sortName & sortDirection

src-docs/src/views/date_picker/date_picker_example.js, src-docs/src/views/date_picker/locale.js
- see https://github.com/elastic/eui/issues/6233
- see https://github.com/elastic/eui/issues/2383
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~ N/A, docs only
=> [EuiDatePicker] Fix CodeSandbox locale examples and add dev note for explicit imports

src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/button/button_icon/__snapshots__/button_icon.test.tsx.snap, src/components/button/button_icon/button_icon.tsx, src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/form/field_password/__snapshots__/field_password.test.tsx.snap, src/components/list_group/__snapshots__/list_group.test.tsx.snap, src/components/list_group/__snapshots__/list_group_item.test.tsx.snap, src/components/list_group/pinnable_list_group/__snapshots__/pinnable_list_group.test.tsx.snap, src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap, src/components/modal/__snapshots__/confirm_modal.test.tsx.snap, src/components/modal/__snapshots__/modal.test.tsx.snap, src/components/notification/__snapshots__/notification_event.test.tsx.snap, src/components/notification/__snapshots__/notification_event_read_button.test.tsx.snap, src/components/pagination/__snapshots__/pagination.test.tsx.snap, src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap, src/components/toast/__snapshots__/global_toast_list.test.tsx.snap
EuiButtonIcon's changes were merged in with randomized `css-` IDs in their snapshots, generating an annoying amount of snapshot churn. Adding an initial `euiButtonIcon: css` fixes this and makes working with downstream changes less of a headache
=> Fix EuiButtonIcon snapshots

scripts/jest/setup/mocks.js, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/page/__snapshots__/page_template.test.tsx.snap, src/components/panel/split_panel/__snapshots__/split_panel.test.tsx.snap
Tests calling `useIsWithinBreakpoints`, `useIsWithinMinBreakpoint`, and `useIsWithinMaxBreakpoint` within EUI were not getting the correct [current_breakpoint_hook.testenv.tsx](https://github.com/elastic/eui/blob/3efa3ee616f3913b7d50197287d09ebb5c71e1a2/src/services/breakpoint/current_breakpoint_hook.testenv.tsx) mock - this is because the mock was pointing at `src/services/breakpoint/index.ts` and not at `src/services/breakpoint/current_breakpoint_hook.ts`, which the `is_within_hooks` file was importing.
- nb: in theory this _shouldn't_ have affected Kibana, since the exported testenv logic is different and replaces the file entirely
N/A, dev-only
=> Fix internal test mocks of `useIsWithin*Breakpoint` hooks

src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/description_list/description_list.test.tsx, src/components/expression/expression.test.tsx, src/components/image/image.test.tsx, src/components/image/image_wrapper.tsx, src/components/page/page_body/page_body.test.tsx, src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, src/components/page/page_header/page_header_content.test.tsx, src/components/page/page_header/page_header_content.tsx, src/components/page/page_section/page_section.test.tsx, src/components/page/page_section/page_section.tsx, src/components/page_template/page_template.test.tsx, src/components/progress/progress.test.tsx, src/components/progress/progress.tsx, src/test/internal/render_custom_styles.tsx, upcoming_changelogs/6239.md
See https://github.com/elastic/kibana/pull/140706#issuecomment-1247373983
This PR fixes the `css` prop being passed to various child `componentProps` not correctly merging `css`. Apparently Emotion generally requires our `css={}` definition to come before the `{...props}` spread for it to be combined correctly.
Or in the case of `EuiPageSection`, it requires the concatenation to occur in our Emotion styles array declaration (I think because `contentProps` has no classNames on it).
NOTE:
- ⚠️ This PR **does not include components that were converted to Emotion after 64.x** ⚠️ 
- because this PR needs to be backported to the latest Kibana upgrade, I kept it limited to components converted in 64.0.0 and below
- ⚠️ This PR **does not include components that have not yet been converted to …
=> [Emotion] Fix multiple css props not being properly cascaded/merged to child props

src-docs/src/views/search_bar/controlled_search_bar.js, src-docs/src/views/search_bar/search_bar.js, src-docs/src/views/search_bar/search_bar_filters.js
One of the examples in https://eui.elastic.co/#/forms/search-bar#search-bar-filters doesn't align with the form controls guidelines: https://eui.elastic.co/#/forms/form-controls/guidelines.
So this PR fixes that.
=> [EuiSearchBar docs] Updated placeholder example to align with forms guidelines

src-docs/src/views/datagrid/basics/datagrid.js, src/components/accordion/accordion.styles.ts, upcoming_changelogs/6235.md
EuiAccordion's `will-change` CSS creates a [stacking context](https://www.joshwcomeau.com/css/stacking-contexts/) which causes nested positioned components to behave unexpectedly, e.g. fullscreen mode in EuiDataGrid:
We're opting removing this CSS for several reasons:
- https://github.com/elastic/eui/pull/5806:
- "It's also very possible that we don't need to engage the GPU at all and even `transform: translatez(0);` was a preoptimization. In that case, we can remove `will-change`, too"
- It looks like `translateZ` was first added by [5 years ago in a relatively unrelated component PR](https://github.com/elastic/kibana/pull/14003), so we're guessing the addition this was an unnecessary pre-optimization that was popular in the frontend world at the time
- Mozilla/MDN has since [recommended …
=> [EuiAccordion] Remove `will-change` CSS

src/components/avatar/avatar.tsx, upcoming_changelogs/6251.md
Closes #6249 by cloning the incoming `style` prop, if any, instead of keeping a direct reference to the object.
~- [ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/cypress-testing.md) …
=> [EuAvatar] Avoid mutating the style prop

src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/date_picker/super_date_picker/super_date_picker.test.tsx, src/components/date_picker/super_date_picker/super_date_picker.tsx, src/components/date_picker/super_date_picker/super_update_button.test.tsx, src/components/key_pad_menu/key_pad_menu.test.tsx, src/components/key_pad_menu/key_pad_menu_item.test.tsx, src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap, src/components/tool_tip/icon_tip.test.tsx, src/components/tool_tip/tool_tip.test.tsx, src/test/internal/render_custom_styles.tsx, src/test/rtl/component_helpers.d.ts, src/test/rtl/component_helpers.ts, upcoming_changelogs/6253.md
Related PRs: #6239, #6248, #6254, #6255
This PR:
- Updates `shouldRenderCustomStyles` to support a `renderCallback` function, which `EuiToolTip` requires because the styles/classes/css that it passes are not rendered until the tooltip is visible / the trigger button is interacted with.
- Adds regression tests for all tooltip components and components with child `tooltipProps`
- [RTL helpers] Update timeout to support tooltips with long delays, and update type definitions to include tooltip helpers
=> [Emotion] Fix/regression test tooltip-related `css` props

src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/form/checkbox/__snapshots__/checkbox.test.tsx.snap, src/components/form/checkbox/checkbox.test.tsx, src/components/form/checkbox/checkbox.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/dual_range.test.tsx, src/components/form/range/dual_range.tsx, src/components/form/switch/__snapshots__/switch.test.tsx.snap, src/components/form/switch/switch.test.tsx, src/components/form/switch/switch.tsx, src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap
Related PRs: #6239, #6248, #6253, #6255
Several of our form components (_note_: with nested childProps, I didn't look for any others) have somewhat tricky DOM structure in that the wrapper their `className`s go on is not the same  as the location that `...rest` is spread to. This means that to accurately `shouldRenderCustomStyles` test these components, I had to create a fake Emotion CSS className to merge with a custom/passed `css` prop.
I thought this worth doing now rather than later (i.e. during the actual Emotion conversion of the components) to ensure that:
1. The `css` array merge approach is in place and not forgotten when converted to Emotion
2. The regression test is in place and not forgotten when it's converted to Emotion
also CC @miukimiu and @thompsongl since IIRC y'all are …
=> [Emotion] Pre-emptively fix/regression test form components with tricky `className`/`css` locations

wiki/writing-styles-with-emotion.md
Adds a lil VS Code "pro tip" snippet to the Emotion conversion wiki.
=> VS Code snippet for component styles.

src-docs/src/views/portal/complex/custom_flyout.tsx, src-docs/src/views/portal/portal_complex.tsx, src-docs/src/views/portal/portal_example.js, src-docs/src/views/portal/portal_flyout.tsx, src/components/flyout/flyout.styles.ts, src/components/flyout/index.ts
Closes #6241.
We normally recommend in our slack to override a `EuiFlyout` or to create one from scratch using a `EuiPortal`. We always point to what should be the right a11y features but we don't have an example in our docs.
So this PR, hopefully, adds an example of what a custom flyout can be with a recommend a11y.    
The example can be found here: https://eui.elastic.co/pr_6247/#/utilities/portal#a-custom-flyout
=> [EuiPortal docs] Add custom flyout example

src-docs/src/views/popover/initial_focus.tsx, src-docs/src/views/popover/popover.tsx, src-docs/src/views/popover/popover_anchor_position.tsx, src-docs/src/views/popover/popover_container.js, src-docs/src/views/popover/popover_example.js, src-docs/src/views/popover/popover_fixed.tsx, src-docs/src/views/popover/popover_htmlelement_anchor.js, src-docs/src/views/popover/popover_panel_class_name.tsx, src-docs/src/views/popover/popover_with_title.tsx, src-docs/src/views/popover/popover_with_title_padding.tsx, src-docs/src/views/popover/trap_focus.tsx
This PR updates a few examples for the EuiPopover to better align with product assistance guidelines (https://github.com/elastic/tech-writing-guidelines/pull/54/):
- Most of the **EuiButtons** were updated to use **EuiButtonEmptys**. In our products, the trigger to open popovers typically comes from a **EuiButtonEmpty** and this align with the guidelines.
- I replaced all icons. All examples were using an `arrowDown`, and it should be avoided. It seems that indicates that the popover will open down. And this is not always true. Like in the following example:
- The `arrowDown` icons were replaced with `help`, `questionInCircle` and `documentation` icons. To better align with the guidelines.
=> [EuiPopover docs] Update examples to align with product assistance guidelines

scripts/test-docker.js
We're seeing multiple hanging CI issues on the a11y testing step:
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request-test/8235/console
- https://kibana-ci.elastic.co/job/elastic+eui+pull-request/8510/
It's not totally clear why, but this only started happening recently (Sept 21st/22nd). This PR skips said step in order to unblock multiple PRs from being merged. Long term, we should potentially consider moving our a11y tests to using Cypress/cypress-axe instead of building our docs and running axe against docs.
Note: I accidentally pushed this commit directly up to main and had to reverted it on main 💀 please disregard that oopsie
=> [CI] Skip a11y testing to stop CI from hanging

src-docs/src/views/resizable_container/resizable_container_callbacks.js, src-docs/src/views/resizable_container/resizable_container_callbacks.tsx, src-docs/src/views/resizable_container/resizable_container_example.js, src/components/resizable_container/resizable_button.tsx, src/components/resizable_container/resizable_container.test.tsx, src/components/resizable_container/resizable_container.tsx, src/components/resizable_container/types.ts, upcoming_changelogs/6236.md
This PR adds support for `onResizeStart` and `onResizeEnd` callback props to `EuiResizableContainer`. The callbacks support resizing with a pointer or a keyboard, and a `trigger: 'pointer' | 'key'` parameter is passed to `onResizeStart` indicating which action triggered the resize.
Notes:
- For pointers, `onResizeStart` is called on `mousedown`, and `onResizeEnd` is called on `mouseup` or `mouseleave`.
- For keyboards, `onResizeStart` is called only on the first `keydown` event while the key remains pressed, and `onResizeEnd` is called on `keyup`. Tapping an arrow key repeatedly will called `onResizeStart` and `onResizeEnd` once for each tap.
- If an arrow key is pressed while a pointer resize is in progress, `onResizeEnd` is called to signal the end of the pointer resize before …
=> [EuiResizableContainer] Add resizable container callbacks

src-docs/src/views/breadcrumbs/truncate_single.js, src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap, src/components/breadcrumbs/breadcrumb.tsx, src/components/breadcrumbs/breadcrumbs.test.tsx, src/components/breadcrumbs/breadcrumbs.tsx, upcoming_changelogs/6280.md
closes https://github.com/elastic/eui/issues/6277
Problem: When the parent `EuiBreadcrumbs` has `truncate` set, this sets a custom truncation style on the last breadcrumb. However, if that last breadcrumb sets its own `truncate: true/false` bool override, that should take precedence over that style (which it currently is not doing).
This was unintentionally broken in the Emotion conversion of EuiBreadcrumbs (#5934). I've added several unit tests for this for future potential regressions.
=> [EuiBreadcrumbs] Fix the last breadcrumb in the array not respecting `truncate` overrides

src-docs/src/views/flex/playground.js, src/components/flex/__snapshots__/flex_grid.test.tsx.snap, src/components/flex/flex_grid.styles.ts, src/components/flex/flex_grid.test.tsx, src/components/flex/flex_grid.tsx, upcoming_changelogs/6281.md
- Closes https://github.com/elastic/eui/issues/4878
- Follow up to https://github.com/elastic/eui/pull/6270#issuecomment-1261320287
This PR adds the `alignItems` prop to `EuiFlexGrid`, but **does not** add the `justifyContent` prop, because said prop does not really makes sense or do anything given that grid items are a percentage width and should always occupy fixed amounts of the container totaling up to 100%.
I also took a look at https://css-tricks.com/snippets/css/complete-guide-grid/ and tested `align-content` and `justify-items`, but they also did nothing that I could tell / did not really make sense again given the percentage-width grid layout.
- Go to http://localhost:8030/#/layout/flex#flex-grids-are-for-repeatable-items and click the playground button, and then use the …
=> [EuiFlexGrid] Add `alignItems` prop

src/components/overlay_mask/overlay_mask.tsx, upcoming_changelogs/6289.md
Several Kibana CSS stylesheets were hooking into the now-removed `euiOverlayMask--aboveHeader` and `euiOverlayMask--belowHeader` classes.
Because of the way EuiOverlayMask's Emotion CSS styles were written, there isn't even a randomly generated Emotion className for those styles to update to. So we need to provide a data attribute instead, and backport this fix.
=> [EuiOverlayMask] Restore missing above/below header information

src/components/basic_table/in_memory_table.test.tsx, src/components/basic_table/in_memory_table.tsx, src/components/search_bar/query/ast.ts, src/components/search_bar/query/default_syntax.test.ts, upcoming_changelogs/6284.md
In this PR I've added a new option to `executeQueryOptions` that allows the consumer to disable the execution of the query when it is controlled.
We have the case in Kibana where the `items` are filtered outside of the table and we don't want the query to be executed on the already filtered items.
**Note**
I've also included in this PR a change to the `AST` parser to allow adding and removing items to a specific "must" or "must not" clause. Let me know if this needs to be in a separate PR or if I can leave it here.
The changes was required to make https://github.com/elastic/kibana/pull/142108/files#diff-5de71eb8bb8fd1e9fc5440e218f972239fdb0ff4933f26a180cc45d5950d7143R69 work.
Fixes https://github.com/elastic/eui/issues/6240
=> [InMemoryTable] Add `enabled` option to executeQueryOptions

src/global_styling/mixins/_header.scss, upcoming_changelogs/6293.md
Missed in https://github.com/elastic/eui/pull/6289 and https://github.com/elastic/eui/pull/6090. Required to not bork Kibana to high heaven
=> [EuiOverlayMask] Fix broken selector reference in EuiHeader mixin

src-docs/src/views/overlay_mask/props.tsx, src/components/overlay_mask/overlay_mask.tsx
Since the overlay mask is essentially a portalled raw DOM node/element, it can't accept an `@emotion/react` `css` prop.
TODO was added in https://github.com/elastic/eui/pull/6118/
~- [ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#changelog)** entry exists and is marked appropriately~
Going to skip the changelog on this as this doesn't really affect user functionality, just developer typing and props table documentation.
=> [EuiOverlayMask] Do not allow the `css` prop

src/components/tool_tip/__snapshots__/tool_tip.test.tsx.snap, src/components/tool_tip/__snapshots__/tool_tip_popover.test.tsx.snap, src/components/tool_tip/tool_tip.styles.ts, src/components/tool_tip/tool_tip.tsx, src/components/tool_tip/tool_tip_arrow.tsx, src/components/tool_tip/tool_tip_popover.tsx, upcoming_changelogs/6295.md
I noticed a missing `euiCanAnimate` while examining EuiToolTip's styles for the Kibana upgrade, and then noticed several other things for improvement. I recommend [following along by commit](https://github.com/elastic/eui/pull/6295/commits)
=> [EuiToolTip] Improve Emotion CSS

src-docs/src/views/tour/step.js, src/components/tour/__snapshots__/tour_step.test.tsx.snap, src/components/tour/tour.styles.ts, src/components/tour/tour_step.test.tsx, src/components/tour/tour_step.tsx, upcoming_changelogs/6298.md
closes https://github.com/elastic/eui/issues/6297
I recommend [following along by commit](https://github.com/elastic/eui/pull/6298/commits), since I did some incidental cleanup while here.
=> [EuiTour] Fix `panelProps` overriding Emotion css + misc cleanup

.github/pull_request_template.md, generator-eui/changelog/index.js, generator-eui/changelog/templates/changelog.md, upcoming_changelogs/_template.md
- Adds the entire Emotion conversion checklist to our default PR template (with extra details + categorization) to encourage devs to fill it out fully
- Adds an Emotion conversion prompt/template to our changelog `yo` generator for better consistency
Feedback would be appreciated on the PR template md file (tagging multiple reviewers for that purpose). Are items well categorized? Would you know how to know if a step should or shouldn't be done with just the information provided, or is more context needed?
- **Does it work?**
&nbsp;
- **Unit tests**
&nbsp;
- **Sass/Emotion conversion process**
&nbsp;
- **CSS tech debt**
&nbsp;
- **DOM cleanup**
&nbsp;
- **Kibana due diligence**
- Pre-emptively check how your conversion will impact …
=> [Emotion] Improve checklist/QA process

src/components/button/button_display/_button_display.styles.ts, upcoming_changelogs/6323.md
We added `pointer-events: none` to disabled buttons as part of their conversion to Emotion. The internet is full of opinions (e.g. a [material-ui issue](https://github.com/mui/material-ui/issues/14455) and a [ux stack exchange](https://ux.stackexchange.com/questions/77163/should-disabled-elements-ever-have-pointer-events)) on this, but we've found it created some jest and functional test errors in Kibana, and it also prevents the `cursor: not-allowed` style from taking effect. This unsets the pointer-events property.
~- [ ] Props have proper **autodocs** and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md …
=> [EuiButton] Remove pointer-events:none on disabled buttons

src/components/page_template/__snapshots__/page_template.test.tsx.snap, src/components/page_template/page_template.test.tsx, src/components/page_template/page_template.tsx, upcoming_changelogs/6324.md
See https://github.com/elastic/kibana/issues/143114#issuecomment-1286856764 for more context. This PR will likely need to be backported to the latest Kibana upgrade to resolve the linked issue.
When the `css` prop is set on a component, Emotion wraps it, changing `.type` EuiPageTemplate is using to detect sidebars. By expanding the conditions for checking for EuiPageSidebar, we can work around this behavior to fix the bug.
~- [ ] Added …
=> Fix EuiSideBar with `css` props not being detected by EuiPageTemplate

src-docs/src/views/card/card_beta.tsx, src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap, src/components/badge/beta_badge/beta_badge.tsx, src/components/card/__snapshots__/card.test.tsx.snap, src/components/key_pad_menu/__snapshots__/key_pad_menu_item.test.tsx.snap, upcoming_changelogs/6326.md
Fixes #6325
The `anchorProps` value with the positioning css, built by **EuiCard**, was not being used when tooltip content wasn't specified. I've added a wrapping span to the two non-tooltip cases and spread these anchor props onto it.
For testing, I've modified the card + beta badge example, removing their tooltip contents.
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs …
=> [EuiBetaBadge] fix beta badge placement when no tooltip content is specified

src-docs/src/views/form_controls/display_toggles.tsx, src-docs/src/views/range/dual_range.tsx, src-docs/src/views/range/input.tsx, src-docs/src/views/range/input_only.tsx, src-docs/src/views/range/levels.tsx, src-docs/src/views/range/range.tsx, src-docs/src/views/range/range_example.js, src-docs/src/views/range/states.tsx, src-docs/src/views/range/ticks.tsx
This PR is open against [[Feature Branch] Convert EuiRange sliders to Emotion and more enhancements](https://github.com/elastic/eui/pull/6092/)  and it fixes https://github.com/elastic/eui/issues/6307.:
- It adds a new coding example called "No linear intervals"  in the tick marks section.
- It also converts all the range slider demos to **typescript**.
- It also converts the `DisplayToggles` component to TS.
=> [Range sliders docs] Add non linear intervals example

src-docs/src/views/search_bar/props_info.js, src-docs/src/views/search_bar/search_bar.js, src/components/popover/popover.tsx, src/components/search_bar/__snapshots__/search_box.test.tsx.snap, src/components/search_bar/search_bar.test.tsx, src/components/search_bar/search_bar.tsx, src/components/search_bar/search_box.tsx, upcoming_changelogs/6319.md
In this PR I've added an option to the `<EuiSearchBar />` component to render a hint below. By default it displays underneath the bar on focus but its visibility can also be controlled using the `isOpen` prop of the `<EuiInputPopover />` component.
Fixes https://github.com/elastic/eui/issues/6005
=> [Euisearchbar] Add option to render hint

src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/_data_grid_toolbar.scss, src/components/datagrid/controls/column_selector.tsx, src/components/datagrid/controls/column_sorting.tsx, src/components/popover/__snapshots__/popover.rtl.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.tsx, src/components/popover/popover_arrow/_popover_arrow.tsx, src/components/popover/popover_panel/__snapshots__/_popover_panel.test.tsx.snap, src/components/popover/popover_panel/_popover_panel.styles.ts, src/components/popover/popover_panel/_popover_panel.test.tsx, src/components/popover/popover_panel/_popover_panel.tsx, src/components/tour/__snapshots__/tour_step.test.tsx.snap, upcoming_changelogs/6329.md
I recommend following along by commit.
closes https://github.com/elastic/eui/issues/6314
Paraphrasing my comment from the above issue as to why this prop/fix is needed:
> you always need to set `transform: none !important;` on any popover panels that contain drag & drop. This is because drag & drop does not work inside transformed elements. There is an example of our own EuiDataGrid using this workaround here:
https://github.com/elastic/eui/blob/7412e4f74d2b56bc151889f6784c6e0d3ffab4af/src/components/datagrid/controls/_data_grid_toolbar.scss#L55-L61
> When `EuiPopover` was converted to Emotion, it started to use `filter` to create a drop shadow effect instead of `box-shadow`, causing our EuiDataGrid popover drag & drop to stop working. Unfortunately `filter` appears to create a [stacking …
=> [EuiPopover] Add `hasDragDrop` prop for popovers with draggable contexts

src/components/modal/__snapshots__/modal.test.tsx.snap, src/components/modal/modal.test.tsx, src/components/modal/modal.tsx, upcoming_changelogs/6327.md
This temporarily addresses https://github.com/elastic/eui/issues/6304 but is not the intended long-term solution. Ideally once https://github.com/theKashey/react-focus-on/pull/63 is merged and released, we would upgrade `react-focus-on` and switch to using `focusOptions={{ preventScroll: true }}` instead.
I recommend following along by commit, the first commit has the primary workaround (intended to be easily removable/deletable in the future).
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.m …
=> [EuiModal] Temporary workaround for scroll-jumping behavior

src-docs/src/views/card/card_image.tsx, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.test.tsx, src/components/card/card.tsx, src/components/card/checkable_card/checkable_card.test.tsx, src/components/card/checkable_card/checkable_card.tsx, upcoming_changelogs/6341.md
- Fixes components passed to `icon` not correctly merging `css` props
- Fixes `css` prop on EuiCheckableCard not landing on the same DOM element as the `className` prop
- Cleanup:
- Removes all `.euiCard-` modifier classes - none of them were being used in Kibana + types cleanup
- Add a few missing unit tests
~- [ ] Checked for **accessibility** including keyboard-only and …
=> [EuiCard] Various fixes & cleanup from Emotion conversion

src/components/avatar/__snapshots__/avatar.test.tsx.snap, src/services/string/to_initials.ts, upcoming_changelogs/6346.md
This PR fixes the `toInitials` bug mentioned in issue  #6276.
=> Fixing toInitials bug that truncates custom initials (Issue #6276)

src-docs/src/views/accessibility/screen_reader_focus.tsx, src-docs/src/views/datagrid/_snippets.tsx, src-docs/src/views/datagrid/toolbar/_grid.js, src-docs/src/views/datagrid/toolbar/visibility.js, src/components/accessibility/screen_reader_only/screen_reader_only.styles.ts, src/components/accessibility/screen_reader_only/screen_reader_only.tsx, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_index.scss, src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap, src/components/datagrid/controls/_data_grid_keyboard_shortcuts.scss, src/components/datagrid/controls/data_grid_toolbar.test.tsx, src/components/datagrid/controls/data_grid_toolbar.tsx, src/components/datagrid/controls/index.ts, src/components/datagrid/controls/keyboard_shortcuts.test.tsx, src/components/datagrid/controls/keyboard_shortcuts.tsx, src/components/datagrid/data_grid.spec.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/scrolling.spec.tsx, upcoming_changelogs/6036.md
closes https://github.com/elastic/eui/issues/2482, see also https://github.com/elastic/kibana/issues/90515 for reference
This PR adds a keyboard shortcuts popover to the EuiDataGrid toolbar. The primary target audience of this functionality is non-sighted screen reader users who otherwise have no indication of how to interact with the data grid.
=> [EuiDataGrid] Add keyboard shortcuts reference

src-docs/src/views/card/card_example.js, src-docs/src/views/card/card_selectable.tsx, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.styles.ts, src/components/card/card.tsx, src/components/card/card_select/card_select.styles.ts, upcoming_changelogs/6348.md
This PR fixes a bug in **EuiCard** where the layout breaks when `horizontal` and `selectable` props are passed. It closes #6345.
I decided to wrap the content, beta badge, and footer in a div called `euiCard__main`. Leaving the select button out of this div. 
I first tried just playing with flex without adding a new div, but when the cards were inside a `EuiFlexGrid` the layout wouldn't work as expected. So this led me to create the `euiCard__main`.
Go to the following example: https://eui.elastic.co/pr_6348/#/display/card#selectable. I've put some of the cards inside a `EuiFlexGroup` and others inside a `EuiFlexGrid`. Just for testing purposes. This example then will be **reverted**.
You can compare it with the version that has the bug: https://codesandbox.io/s/leg8ch?file=/demo.js. …
=> [EuiCard] Fix bug where layout breaks when `horizontal` and `selectable`

src/components/page_template/__snapshots__/page_template.test.tsx.snap, src/components/page_template/inner/__snapshots__/page_inner.test.tsx.snap, src/components/page_template/inner/page_inner.test.tsx, src/components/page_template/inner/page_inner.tsx, src/components/page_template/outer/page_outer.tsx, src/components/page_template/page_template.test.tsx, src/components/page_template/page_template.tsx, upcoming_changelogs/6352.md
closes https://github.com/elastic/eui/issues/6351
`EuiPageTemplate` claims to respect the `component` prop for the inner `main` content wrapper, but does not actually do so.
I recommend following along by commit.
~- [ ] Updated the **[Figma](https://www.figma.com/community/file/964536385682658129)** …
=> [EuiPageTemplate] Fix ignored `component` prop

package.json, src/components/date_picker/super_date_picker/super_date_picker.a11y.tsx, src/components/modal/modal.a11y.tsx, src/components/modal/modal.spec.tsx, src/components/popover/popover.a11y.tsx, src/components/tabs/tabs.a11y.tsx, src/components/tabs/tabs.spec.tsx, src/components/tree_view/tree_view.a11y.tsx, src/components/tree_view/tree_view.spec.tsx, yarn.lock
This PR continues work from #6340. Adding a11y tests for five components, bumping `cypress-axe` to v1.0.0, and adding keyboard navigation tests to three components.
* Adding spec and a11y tests for Modal.
* Adding spec and a11y tests for Tabs.
* Adding spec and a11y tests for TreeView.
* Adding a11y spec for Super Date Picker.
* Adding a11y spec for Popover.
=> Adding Cypress a11y tests for five components.

package.json, scripts/test-a11y-docker.js
After [splitting the Cypress a11y tests](https://github.com/elastic/eui/pull/6331) from functional tests, we need a new job to run them in CI. This PR re-uses much of our `test-docker.js` script, but changes up the command to test `NAME.a11y.tsx` files only. It also adds a command to our package.json file that will be used to scrip the Jenkins job.
* Ran the existing Docker container locally using the new test command
=> Adding a Docker script and prompt for Cypress a11y tests in CI.

src/components/accessibility/skip_link/skip_link.test.tsx, src/components/accessibility/skip_link/skip_link.tsx, upcoming_changelogs/6355.md
I came across this bug in Kibana where Discover had a completely custom EuiSkipLink `onClick` for their legacy data table. They were using the skip link to programmatically scroll the table past hundreds of rows, so the traditional EuiSkipLink behavior did not apply.
This PR allows EuiSkipLink to call totally custom `onClick` behavior (was previously returning early if no target or fallback destination existed) by passing `destinationId="" fallbackDestination=""`.
=> [EuiSkipLink] Allow consumer `onClick`s to be called even if no valid destination or fallback destination exists

src/components/page/page_section/page_section.test.tsx, src/components/page/page_section/page_section.tsx, upcoming_changelogs/6365.md
- This was originally fixed in https://github.com/elastic/eui/pull/6239 
- (although my guess as to why it needed to be that way was not quite correct)
- This was broken in https://github.com/elastic/eui/pull/6257 (released in v69.x)
- I assumed it was working because tests were passing, but tests were only checking that passed CSS existed and not for our CSS being overriden
- This PR re-fixes the bug **(will need to be backported for Kibana)** and adds clearer comments and a regression unit test.
=> [EuiPageSection] Fix `contentProps` not correctly concatenating `css`

src/components/flyout/flyout.a11y.tsx
@constancecchen suggested adding an a11y spec for EuiFlyout to [PR 6344](https://github.com/elastic/eui/pull/6344#discussion_r1015858034) and I forgot to **add it** to the PR files. This PR just adds that missing test.
=> Adding an a11y spec for EuiFlyout.

src/components/tabs/__snapshots__/tab.test.tsx.snap, src/components/tabs/tab.tsx, upcoming_changelogs/6366.md
When we converted `EuiTabs` to Emotion in https://github.com/elastic/eui/pull/6311, we started passing down `size` to child `EuiTab`, but we didn't set a default `size = 'm'` for `<EuiTab>`s used outside of parent `<EuiTabs>` **or** when consumers add, e.g. a wrapper of some kind around `EuiTab`.
This is affecting a Kibana plugin and will need to be backported:
⚠️ **Note**: Technically this fix does not address scenarios where consumers do something like this:
```
<EuiTabs size="l">
<SomeIntermediateWrapper>
<EuiTab> // will be size "m" / will not inherit size "l"
```
For the above scenarios, we need to use React Context instead to share `size`, similar to how EuiDescriptionList behaves, instead of cloning children with props. However, as that's a significantly more involved fix and …
=> [EuiTab] Fix standalone tabs not defaulting to a size

package.json, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/focus_trap/__snapshots__/focus_trap.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/modal/__snapshots__/confirm_modal.test.tsx.snap, src/components/modal/__snapshots__/modal.test.tsx.snap, src/components/modal/modal.test.tsx, src/components/modal/modal.tsx, src/components/popover/__snapshots__/popover.rtl.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/tour/__snapshots__/tour_step.test.tsx.snap, upcoming_changelogs/6360.md, yarn.lock
- closes https://github.com/elastic/eui/issues/6304 (this time for real!)
- Removes https://github.com/elastic/eui/pull/6327 (temporary workaround)
Now that https://github.com/theKashey/react-focus-on/pull/63 has been merged in, we can use `react-focus-on`'s new `preventScrollOnFocus` prop to... prevent scrolling on focus.
=> [EuiModal] Permanently fix `EuiModal` to scroll-jumping issues, remove temporary workaround

src/components/flyout/__snapshots__/flyout_body.test.tsx.snap, src/global_styling/mixins/_helpers.ts, src/global_styling/utility/__snapshots__/utility.test.tsx.snap, upcoming_changelogs/6374.md
Elizabet noticed this first in https://github.com/elastic/eui/pull/6321#discussion_r1006780946, I'm copying her fix here so we can get it into Kibana 8.6FF.
> I noticed that the previous value `calc(${size.base} * 0.75 * 1.25)` was not corresponding to the Sass mixin (before converted to Emotion). So I fixed to use a similar value:
>
> <img width="721" alt="" src="https://user-images.githubusercontent.com/2750668/198277233-cdc7d172-5cf2-46ab-93b5-bfc6f240d24d.png">
>
> The problem of using the ``calc(${size.base} * 0.75 * 1.25)`` could be noticed here:
>
> <img width="846" alt="" src="https://user-images.githubusercontent.com/2750668/198278858-e1c31a02-eb6a-4786-9bec-ec21832958b6.png">
In production, this primarily affects `EuiFlyout` and consumers directly using `.eui-yScrollWithShadows` …
=> [Emotion] Fix overly large scroll shadow gradients

src/components/card/card.styles.ts, upcoming_changelogs/6377.md
This PR fixes a bug where the inner content in vertical cards was not growing 100% in width. This issue was introduced in #6348. **The bug is only visible if the card has inner background**. 
The best way to test is by comparing the cards in the button page EUI version 70.2.0 (where the bug exists) with the fix:
- **Bug:** https://eui.elastic.co/v70.2.0/#/navigation/button
- **Fix:** https://eui.elastic.co/pr_6377/#/navigation/button
=> [EuiCard] Fix bug with vertical cards not growing 100% in width

src/components/date_picker/super_date_picker/_super_date_picker.scss, src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss, src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx, src/components/date_picker/super_date_picker/quick_select_popover/recently_used.tsx, upcoming_changelogs/6380.md
This PR fixes incorrect button margins in **EuiSuperDatePicker** quick select popover. This bug was introduced when the **EuiFlexGrid** was converted to Emotion.
Compare the example with the bug with the fix:
- Bug: https://eui.elastic.co/v70.2.0/#/templates/super-date-picker
- Fix:  https://eui.elastic.co/pr_6380/#/templates/super-date-picker
=> [EuiSuperDatePicker] Fix incorrect button margins in quick select popover

src/components/flex/flex_group.styles.ts, upcoming_changelogs/6381.md
Prior Sass had a `>` selector that I missed in my conversion:
https://github.com/elastic/eui/blob/c85913bef931f2eb7df754c48eca7fdf6481ebc4/src/components/flex/_flex_item.scss#L30-L36
This primarily affects nested nested EuiFlexGroups where the parent is responsive but a child EuiFlexGroup within is not responsive. This is affecting Kibana and will need to be backported to the latest upgrade.
=> [EuiFlex] Fix responsive selector missed in Emotion conversion

src-docs/src/components/codesandbox/link.js, src-docs/src/services/string/clean_imports.js, src-docs/src/views/date_picker/range.tsx, src-docs/src/views/form_controls/display_toggles.tsx
This PR converts the `DisplayToggles` component to Typescript. 
I first converted this component in #6092, then I needed it in #6370. So I converted again. 
So I guess it is better to have its own PR. Both PRs where I converted the component are part of feature branches and they will take a while to be merged. 
=> [Docs] Convert `DisplayToggles` to `*.TS`

wiki/upgrading-kibana.md
Step 10 of [Upgrading EUI in Kibana](https://github.com/elastic/eui/blob/main/wiki/upgrading-kibana.md) **Overview** lists a required tag as `ci:deploy-cloud` but the tag has been renamed to `ci:cloud-deploy` on Kibana. Updating to match.
=> Changing label in `upgrading-kibana.md`
