elastic/eui

src/components/flyout/flyout.styles.ts, upcoming_changelogs/6422.md
closes https://github.com/elastic/eui/issues/6419 
Broken animation missing transform in from left: https://eui.elastic.co/v70.0.0/#/navigation/collapsible-nav
Original Sass animation: https://eui.elastic.co/v60.0.0/#/navigation/collapsible-nav
Fixed staging link: https://eui.elastic.co/pr_6422/#/navigation/collapsible-nav
=> [EuiFlyout][EuiCollapsibleNav] Fix broken slide in animation for left flyouts

src/components/card/card.styles.ts, upcoming_changelogs/6424.md
This PR fixes a bug where the **EuiCard** footer was not getting aligned to the bottom. This bug was introduced in #6348, where I added a new container and this new container was not vertically stretching. 
The issue was reported at https://github.com/elastic/kibana/issues/145962.
The following example should have the footer aligned to the bottom:
- https://eui.elastic.co/pr_6424/#/display/card#footer
=> [EuiCard] Fix bug where footer were not getting aligned to the bottom

src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap, src/components/search_bar/query/ast_to_es_query_dsl.ts, upcoming_changelogs/6409.md
This restores previous functionality when querying for multi-term values in analysed fields
Fixes https://github.com/elastic/eui/issues/6399
Restores the previous match operator behaviour when the query value is split into multiple terms after analysis.
=> Specify the operator option when generating term queries.

src-docs/src/views/app_context.js, src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx, src/components/description_list/description_list.styles.ts, src/components/description_list/description_list_description.styles.ts, src/components/description_list/description_list_description.tsx, src/components/description_list/description_list_title.styles.ts, src/components/flex/flex_grid.styles.ts, src/components/flex/flex_group.styles.ts, src/components/flyout/flyout.styles.ts, src/components/image/image_wrapper.styles.ts, src/components/modal/modal.styles.ts, src/components/modal/modal_body.styles.ts, src/components/modal/modal_footer.styles.ts, src/components/page/page.styles.ts, src/components/toast/global_toast_list.styles.ts, src/global_styling/mixins/__snapshots__/_responsive.test.ts.snap, src/global_styling/mixins/_responsive.test.ts, src/global_styling/mixins/_responsive.ts, upcoming_changelogs/6431.md
Consumers who have custom breakpoints above and below our `xs` and `xl` breakpoints currently will have buggy responsive behavior due to the way our breakpoint mixins are written. When we wrote `euiBreakpoint(['m', 'xl'])` in our previous CSS, we _actually_ wanted `m and above` and not just `screens m, l, and xl` (which breaks when screen on `xxl`).
To future-proof our current CSS against custom consumer breakpoints, I've added new `euiMinBreakpoint()` and `euiMaxBreakpoint()` utils to help us actually capture the "x and below" or "x and above" logic we usually want. These two new utilities treat breakpoint sizes as one-dimensional points rather than two-dimensional screen ranges, which should hopefully be easier to reason about.
This fix **must** be backported to 8.6 in order for …
=> [CSS-in-JS] Fix EUI media queries to more flexibly account for custom breakpoints

src/components/breadcrumbs/breadcrumbs.a11y.tsx, src/components/pagination/pagination.a11y.tsx, src/components/side_nav/side_nav.a11y.tsx
Adding specs to put three navigation patterns through the axe scanner. Experimented further with `beforeEach()` and using the Cypress viewport widths to toggle mobile and desktop layouts.
* Adding EuiBreadcrumb a11y spec.
* Adding EuiSideNav a11y spec.
* Adding EuiPagination a11y spec.
* Ran Cypress a11y specs on localhost in headless environment
=> Adding a11y specs for three navigation patterns.

wiki/releasing-versions.md
Updates our wiki documentation to remove the step where we add backports/patch releases made only for Kibana from the `main` CHANGELOG. Since we're not doing GH releases for the backport/patches, it doesn't make sense to list them in the main CHANGELOG.
=> [Wiki] Remove `main` changelog update step from Kibana patch/backports docs

scripts/eslint-plugin/css_logical_properties.js, scripts/eslint-plugin/css_logical_properties.test.js, src-docs/src/views/comment/comment_props.tsx, src-docs/src/views/theme/borders/_border_sass.tsx, src-docs/src/views/theme/sizing/_sizing_js.tsx, src/components/badge/badge.styles.ts, src/components/breadcrumbs/breadcrumb.styles.ts, src/components/button/button_display/_button_display.styles.ts, src/components/code/code.styles.ts, src/components/expression/expression.styles.ts, src/components/list_group/list_group_item.styles.ts, src/components/loading/loading_spinner.styles.ts, src/components/markdown_editor/__snapshots__/markdown_format.styles.test.ts.snap, src/components/markdown_editor/markdown_format.styles.ts, src/components/modal/modal_header.styles.ts, src/components/popover/popover_footer.styles.ts, src/components/popover/popover_title.styles.ts, src/components/text/text.styles.ts, src/components/token/token.styles.ts, src/components/tool_tip/tool_tip.styles.ts, src/global_styling/functions/index.ts, src/global_styling/functions/logical_shorthands.test.ts, src/global_styling/functions/logical_shorthands.ts, src/global_styling/functions/logicals.json, src/global_styling/functions/logicals.ts, upcoming_changelogs/6429.md
Unfortunately, [shorthand properties that describe boxes](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties#edges_of_a_box) such as `margin` and `padding` do not currently automatically respond to logical changes in display direction (see https://github.com/w3c/csswg-drafts/issues/1282).
Until an official spec is created by W3C, this utility is a stopgap measure to convert (e.g.) `margin` shorthands to `margin-inline` and `margin-block` respectively.
Example usage within Emotion (intentionally similar in usage to `logicalCSS()`):
```js
margin: 0 ${euiTheme.size.s};
```
becomes
```js
${logicalShorthandCSS('margin', `0 ${euiTheme.size.s}`)}
```
I've also added a lint rule for this, which flags shorthand usage with multiple values. Single values (same value applied to all …
=> [CSS-in-JS] Add `logicalShorthandCSS` util + lint rule

src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/code/code_block_virtualized.tsx, src/global_styling/functions/__snapshots__/logicals.test.ts.snap, src/global_styling/functions/logicals.test.ts, src/global_styling/functions/logicals.ts, upcoming_changelogs/6426.md
This utility allows us to convert any `style` object to use corresponding logical properties instead of, e.g. `width`, `height`, etc. It checks the entire style obj for keys that have corresponding logical properties and converts them if so. It's particular desired for anywhere we use a virtualization library.
The example/snapshot change for `EuiCodeBlock` most clearly illustrates what this utility accomplishes.
This is very much a "nice to have" util and doesn't necessarily exactly work 100% as expected in `react-window` in actual `direction: rtl` or `writing-mode: vertical-rl` prod behavior (although it's hard to tell if this is because EUI as a whole is not fully converted to logical properties yet).
It also contains an incidental test cleanup commit.
=> [CSS-in-JS] Add utility for converting `style` to logical properties

.ci/jobs/elastic+eui+pull-request.yml
This PR adds `renovate` bot user to the permitted users for building pull requests. See JJB [options](https://jenkins-job-builder.readthedocs.io/en/latest/triggers.html?highlight=white-list#triggers.github-pull-request).
This will prevent messages like [this](https://github.com/elastic/eui/pull/6350#issuecomment-1307505603), shown below and automatically run the CI build treating `renovate` as a trusted user.
=> Add renovate bot to jenkins white-list

src/components/basic_table/in_memory_table.tsx
closes https://github.com/elastic/eui/issues/5928
The above issue auto-stale-closed, but I thought updating the docs would be a super quick fix and I wanted to address it really quickly [with Greg's comments](https://github.com/elastic/eui/issues/5928#issuecomment-1138633747) since a docs change is much simpler than a props change.
=> [EuiBasicTable] Fix incorrect props documentation

src/components/breadcrumbs/breadcrumbs.a11y.tsx, src/components/color_picker/color_picker.a11y.tsx, src/components/combo_box/combo_box.a11y.tsx, src/components/control_bar/control_bar.a11y.tsx, src/components/copy/copy.a11y.tsx, src/components/modal/modal.a11y.tsx, src/components/side_nav/side_nav.a11y.tsx
* Added color picker Cypress a11y spec. Updating some specs to use `cy.realClick()`
* Added EuiComboBox a11y and keyboard specs.
* Adding EuiCopy a11y and keyboard specs.
=> Adding a11y tests for EuiColorPicker, EuiComboBox, and EuiCopy

src/components/form/range/dual_range.test.tsx
Whether we like it or not, there are currently 2 instances of Kibana using the `ref` prop on `EuiDualRange` to call the class `onResize` method: https://github.com/elastic/kibana/pull/147142/commits/5c575f9d97b81275c81db5583e16a85332df3cdb. I discovered this because the typing for `EuiDualRange`'s ref prop became extremely annoying once we started wrapping in `withEuiTheme`.
The ideal solution, converting `EuiDualRange` from a class component to a function component, unfortunately also takes away Kibana's ability to call `onResize`. This means if/when we do convert `EuiDualRange` to a function component, we'll need to deliberately expose `onResize` via React's `useImperativeHandle` API.
To ensure we don't forget this, I've added a unit test for calling `rangeRef.current.onResize()` that …
=> [EuiDualRange] Add regression test for Kibana use of `ref` prop

src/components/page/index.ts, src/components/page/page_side_bar/index.ts, src/components/page/page_side_bar/page_side_bar.tsx, src/components/page/page_template.tsx, upcoming_changelogs/6468.md
@spalger pointed out that we are exporting both `EuiPageSideBarProps` (deprecated) and `EuiPageSidebarProps` (the new one), which is super confusing for consumers and Kibana.
It looks like Caroline missed renaming `EuiPageSideBarProps` to deprecated to match `EuiPageSideBar` (she marked other similar/confusing props as `_Deprecated`), so this PR amends that.
https://github.com/elastic/eui/blob/d549ff0d95969c977f299fbe63a732a0330f83d6/src/components/page/index.ts#L42-L43
https://github.com/elastic/eui/blob/c48afd76b31a6fa645f11626abcce07d653dba86/src/components/page/index.ts#L48-L49
=> More clearly mark `EuiPageSideBarProps` as deprecated

src-docs/src/services/playground/playground.js, src/components/error_boundary/error_boundary.tsx
Previously when components threw errors in playgrounds, there would just be an empty blank and a console message:
I initially attempted wrapping the playground in an `EuiErrorBoundary`, but nothing was happening. After looking at [react-view's documentation](https://github.com/uber/react-view#error), I realized they were swallowing/capturing errors and passing them via an `errorProps`.
I didn't want to use react-view's default `Error` component as they styling was super different than anything else we had in EUI, and we already had error styling via `EuiErrorBoundary`. My solution to this was to extract react-view's `errorProps.message`, and pass that manually to a styled internal component (a view-only internal version of `EuiErrorBoundary` pulled out separately). The end result:
Repro …
=> [Docs] Add EUI error messaging to playground errors

src/components/datagrid/data_grid.a11y.tsx, src/components/date_picker/date_picker.a11y.tsx, src/components/delay_hide/delay_hide.a11y.tsx, src/components/delay_render/delay_render.a11y.tsx, src/components/empty_prompt/empty_prompt.a11y.tsx
* Added EuiDataGrid a11y spec.
* Added a11y and keyboard spec for EuiDatePicker.
* Added a11y and keyboard spec for EuiDelayRender.
* Added a11y and keyboard spec for EuiEmptyPrompt.
Mocked two tests using `cy.spy()` to confirm no a11y side effects on `EuiEmptyPrompt`. Probably over-engineered, but it's a pattern I want to establish for future Cypress component tests where we do need to capture and evaluate side effects.
=> A11y specs for EuiDataGrid, EuiDatePicker, EuiDelayRender, EuiEmptyPrompt

package.json, scripts/postinstall.js, scripts/release.js, scripts/update-token-changelog.js, wiki/releasing-versions.md, yarn.lock
This PR is part of our higher-level goal of removing dependencies causing issues for M1/arm64 developers (see https://github.com/elastic/eui/issues/6442).
Our `nodegit` dependency is only used during our release script. While there are alpha versions of `nodegit` that purport to support M1, I spiked out removing/replacing the dependency totally with `exec` versions of git CLI commands, and was able to successful find their corresponding CLI APIs which I found easy enough to replace.
While these changes may not be totally bullet or bug proof, these changes are dev-only and I feel confident enough to move forward with them as-is and fix any issues that arise during the next release.
Release script
Tokens script
- Open `i18ntokens.json` and change the first `defString` to (e.g.) `TEST`. Save …
=> Remove `nodegit` dependency

src/components/form/file_picker/__snapshots__/file_picker.test.tsx.snap, src/components/form/file_picker/_file_picker.scss, src/components/form/file_picker/file_picker.tsx, upcoming_changelogs/6479.md
This PR updates `EuiFilePicker` dropzone styles to look more like an interactive element. Text contrast is boosted in the compact variant of the component and it no longer looks like a disabled button or inactive input.
=> EuiFilePicker dropzone style updates

package.json, yarn.lock
I missed this in #6470 - with `sass-lint` gone, `stylelint` already uses a more modern resolution of `known-css-properties`, so there's no need for us to manually resolve this dependency this any longer.
N/A, this only affects a single dev dependency, so if sass linting passes on CI everything should be fine
=> Remove unnecessary `known-css-properties` resolution

src/components/tabs/__snapshots__/tabs.test.tsx.snap, src/components/tabs/tab.tsx, src/components/tabs/tabs.test.tsx, src/components/tabs/tabs.tsx, src/components/tabs/tabs_context.tsx, upcoming_changelogs/6478.md
- `EuiTabs` component passes `size` and `expand` props only to children (`EuiTab` components) that are direct descendants. The props will not be passed if the children, or one of the children, is wrapped in another element. This PR fixes the issue by using context instead of props to pass `size` and `expand` values to all `EuiTab` children at any level.
- Closes #6367 
~- [ ] Updated the …
=> [EuiTabs] Pass `size` and `expand` to all children using a React context provider

package.json, src-docs/src/services/props/markdown_format/plugin_list.js, src/components/markdown_editor/markdown_types.ts, src/components/markdown_editor/plugins/markdown_default_plugins/parsing_plugins.ts, upcoming_changelogs/6482.md, yarn.lock
This PR does **not** fully address https://github.com/elastic/eui/issues/5543, but resolves the underlying issue being described (security issues caused by `remark-parse`'s use of `trim@0.0.1`).
Simply upgrading `remark-parse` is non-trivial due to all the reasons outlined in https://github.com/elastic/eui/issues/5543#issuecomment-1352060546, but it looks like GitHub's docs team at some point released a fork of `remark-parse@8.0.3` without the trim dependency/security warnings, which is exactly what we need for an interim solution.
=> Replace `remark-parse` with `remark-parse-no-trim`

src-docs/src/views/selectable/selectable_exclusion.tsx, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, src/components/selectable/selectable_list/selectable_list.tsx, upcoming_changelogs/6487.md
closes https://github.com/elastic/eui/issues/6485
@Heenawter's team has a fairly custom include/exclude usage of `EuiSelectable` where they want to be able to quickly grab the triggering `option` without having to scrub through the event or the entire `options` array to figure out what changed.
This is an extremely reasonable request, just IMO, and is also a very quick add onto the existing `onChange` callback.
- Go to https://eui.elastic.co/pr_6487/#/forms/selectable#options-can-be-excluded
- Open your browser devtools
~- [ ] Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs …
=> [EuiSelectable] Add the single triggering option as a parameter to `onChange`

src-docs/src/views/popover/outside_click.tsx, src-docs/src/views/popover/popover_example.js, src/components/popover/popover.spec.tsx, src/components/popover/popover.tsx, upcoming_changelogs/6500.md
closes https://github.com/elastic/eui/issues/6498
It appears the Lens team wants the ability to add a confirmation modal on EuiPopover outside click, in order for consumers to not lose progress or input if they accidentally click away/outside of the popover before finishing their action within the popover.
This is currently not supported by EuiPopover via `closePopover` (and cannot be). Instead, we need to modify `focusTrapProps` to support overriding our internal popover `onOutsideClick` method, which then will allow a consumer to toggle a confirmation modal manually:
- Go to https://eui.elastic.co/pr_6500/#/layout/popover#custom-outside-click-behavior
- Click to open the popover, and then click outside the popover …
=> [EuiPopover] Support custom `onClickOutside` overrides

src/components/basic_table/table.a11y.tsx, src/components/image/image.a11y.tsx, src/components/key_pad_menu/key_pad_menu.a11y.tsx
* Added a11y and keyboard specs for EuiImage.
* Added a11y and keyboard specs for EuiInMemoryTable.
* Added a11y and keyboard specs for EuiKeyPadMenu.
=> A11y specs for EuiImage, EuiTable, EuiKeyPadMenu.

src/components/image/image.tsx, src/components/image/image_fullscreen_wrapper.tsx, src/components/image/image_types.ts, src/components/image/image_wrapper.tsx, upcoming_changelogs/6504.md
We are using EuiImage full screen state and in some case we needed to show caption only when image is in full screen mode. So we need full screen state to determine that. This PR expose the full screen state of the component via callback.
=> [EuiImage] Expose full screen state

src/components/tour/tour.styles.ts, upcoming_changelogs/6512.md
This PR adds an extra spacing of 4px (`euiTheme.size.xs`) between the `title` and `subtitle` in **EuiTour** and closes #5848.
=> [EuiTour] Add extra spacing between the `title` and `subtitle`

src/components/accordion/accordion.tsx
Condition 'isLoadingMessage' is always true at this point because it has been already checked at line 348. This patch removes the unnecessary condition statement.
[Cee note] N/A, this is a relatively minor change that doesn't need extensive QA - I would consider current tests passing to be sufficient
=> [EuiAccordion] Remove a unnecessary condition statement

src/components/markdown_editor/__snapshots__/markdown_format.styles.test.ts.snap, src/components/markdown_editor/_markdown_format.scss, src/components/markdown_editor/markdown_format.styles.ts, src/components/text/__snapshots__/text.styles.test.ts.snap, src/components/text/text.styles.ts, upcoming_changelogs/6511.md, upcoming_changelogs/6514.md
This PR updates the `EuiText.blockquote` styles to match the `EuiMarkdownFormat.blockquote` styles. Blockquotes are normally used in docs sites so we should have styles that users are more familiar with. 
Closes #6511. 
=> [EuiText] Add new `blockquotes` styles

src-docs/src/views/tool_tip/tool_tip_example.js, src-docs/src/views/tool_tip/tool_tip_fixed.tsx, src/components/tool_tip/tool_tip.test.tsx, src/components/tool_tip/tool_tip.tsx, upcoming_changelogs/6515.md
closes https://github.com/elastic/eui/issues/5604
This PR adds the `repositionOnScroll` prop, which fixes tooltip positioning on anchors that are `position: fixed`, and behaves exactly the same way `repositionOnScroll` behaves for `EuiPopover`.
=> [EuiToolTip] Add `repositionOnScroll` prop

src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap, src/components/datagrid/controls/_data_grid_column_sorting.scss, src/components/datagrid/controls/column_selector.tsx, src/components/datagrid/controls/column_sorting_draggable.tsx, src/components/datagrid/data_grid.a11y.tsx, upcoming_changelogs/6517.md
closes https://github.com/elastic/eui/issues/6516
This was actually a more trivial than I thought, since our [EuiDraggable component already has affordance built in](https://elastic.github.io/eui/#/display/drag-and-drop#interactive-elements) for interactive children via `hasInteractiveChildren` and `customDragHandle` :)
axe should no longer be complaining about nested interactive controls when any EuiDataGrid popover with draggable columns is open. Said draggable columns should remain draggable by drag handles and column names, but not by any interactive elements.
- Go to http://localhost:8030/#/tabular-content/data-grid
- Open the "Columns" visibliity popover in the data grid toolbar
- Open the "Sort fields" visibliity popover in the data grid toolbar
- In the bottom left hand corner of …
=> [EuiDataGrid] Fix nested interactive controls axe error

wiki/upgrading-kibana.md
I noticed while walking through a Kibana upgrade with @JasonStoltz that our wiki doc on the subject could use a little improvement. Here are the short list of changes made:
- Ordered entire documents in a more generally chronological order to make it easier to follow (vs jumping around the page)
- Removed overview in favor of table of contents
- Split up more areas into sections with step-by-steps
- Updated recommendations, scripts, and general context to be more current
- More documentation around the ready for review/merging process
Would definitely appreciate any feedback or suggestions to continue improving this doc!
[Preview the markdown-rendered doc here](https://github.com/cee-chen/eui/blob/wiki/kibana/wiki/upgrading-kibana.md).
N/A, docs only
=> [Wiki] Improve Kibana upgrade docs

src-docs/src/views/button/guidelines.js, src-docs/src/views/modal/confirm_modal.tsx
This PR updates the confirm modal examples to reflect better writing practices and closes #6506.
It also removes the word "discard" from "Avoid these words in buttons" in: https://eui.elastic.co/#/navigation/button/guidelines.
All the discussions that led to these changes can be found in #6506.
The confirm modals for QA can be found here: https://eui.elastic.co/pr_6519/#/layout/modal#confirm-modal
=> [Docs] Update `EuiConfirmModal` examples

src/components/tool_tip/tool_tip.spec.tsx, src/components/tool_tip/tool_tip.tsx, src/components/tool_tip/tool_tip_manager.test.ts, src/components/tool_tip/tool_tip_manager.ts, upcoming_changelogs/6520.md
closes https://github.com/elastic/eui/issues/6423
This PR attempts to address multiple filed issues (https://github.com/elastic/kibana/issues/144482, https://github.com/elastic/eui/issues/5883, etc.) complaining about **focused** tooltip toggles not going away when another tooltip toggle is **hovered**. This behavior primarily affects mouse users (keyboard-only users will not have this issue, as focus is lost when tabbing away).
The solution to this problem should address this point of friction **without impacting the accessibility of keyboard and screenreader users**.
The solution that we think should satisfy the above problem and parameters was to add an internal tooltip manager that only allows **one** tooltip (the most recently triggered tooltip) at a time to be visible. This is …
=> [EuiToolTip] Enforce only one visible tooltip at a time

src/components/tool_tip/tool_tip.test.tsx
closes https://github.com/elastic/eui/issues/6430
As it turns out, controlling internal EuiToolTip visibility state is already currently achievable (due to it being a class component) via `ref`.
This PR adds tests for this functionality but after speaking to @1Copenut, we've actively decided **against** publicly documenting this functionality - this is an extremely edge case scenario with a **lot** of accessibility implications (see code comments), and as a team, EUI **only** wants to recommend it to consumers for very very specific use cases.
The below use case example (a button that toggles a flyout/modal/focus trap and consumers not wanting the tooltip to be re-shown on when the focus trap closes) is one such use case, primarily for when the tooltip occludes another UI element: …
=> [EuiToolTip] Unit tests for control of internal tooltip visibility state via `ref`

src-docs/src/views/guidelines/getting_started/getting_started.js
I was looking at the getting started page to help a consumer and realized that a code snippet I added earlier when adding React Testing Library helpers was broken-looking 😭 
N/A, docs only
=> [Docs] Fix code snippet

src/components/notification/notification_event.a11y.tsx, src/components/page/page_header/page_header.a11y.tsx, src/components/portal/portal.a11y.tsx
* Added a11y and keyboard specs for EuiNotificationEvent.
* Added page header a11y tests.
* Added a11y and keyboard specs for EuiPortal.
=> Added a11y specs for EuiNotificationEvent, EuiPageHeader, EuiPortal

scripts/release.js
@breehall discovered that our various upstream fetches will cause a lot of failures if `upstream` is pointed at the wrong repo. Rather than assuming devs have `upstream` already set up and pointed correctly, we should catch `upstream` remote issues in our release script automatically.
- Run `git remote remove upstream` locally
- Run `git remote add upstream git@github.com:cee-chen/eui.git`
- Run `git remote remove upstream && git remote add upstream git@github.com:elastic/eui.git`
N/A, internal dev-only changes
=> Harden release script to check for correct `upstream` remote

src/components/modal/__snapshots__/modal_header_title.test.tsx.snap, src/components/modal/confirm_modal.test.tsx, src/components/modal/confirm_modal.tsx, src/components/modal/modal_header_title.test.tsx, src/components/modal/modal_header_title.tsx, upcoming_changelogs/6530.md
closes https://github.com/elastic/eui/issues/6531
The [EuiModal conversion](https://github.com/elastic/eui/pull/6321/files#diff-65352da4495c877124ff12f370d4469672232423b8e8b6b78d9a85ed418f53f9) removed the `div` wrapper for `EuiModalHeaderTitle` in favor of `EuiTitle`. In combination with the conditional React child detection check, this broke several instances in Kibana where styles were no longer applying as expected. This is due to devs passing in `<FormattedMessage />` components (which look and smell like a React Element, but in actuality just outputs a raw string that has no valid element to set title styles on).
This PR opinionatedly changes the behavior of `EuiModalTitle` to **always** wrap its contents in a `h1` tag by default, no matter what type of children is passed (string, …
=> [EuiModalHeaderTitle] Remove automatic detection of title contents in favor of always wrapping a `h1`, configurable via new `component` prop

src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/basic_table.styles.ts, src/components/basic_table/basic_table.tsx, upcoming_changelogs/6538.md
For whatever arcane CSS reason, the `EuiToolTip` and `EuiPopover` anchor wrappers around tables' action buttons were causing a slight 1-2px increase in height.
Resetting the entire action cell's `line-height` appears to fix the issue and ensures that all actions remain at 24px high regardless of whether they're enabled or disabled.
I also started a `basic_table.styles.ts` file while here, we'll end up using it at some point.
=> [EuiBasicTable] Fix row heights jumping when actions are disabled

src-docs/src/views/resizable_container/resizable_container_basic.tsx, src-docs/src/views/resizable_container/resizable_container_callbacks.tsx, src-docs/src/views/resizable_container/resizable_container_example.js, src-docs/src/views/resizable_container/resizable_container_reset_values.tsx, src-docs/src/views/resizable_container/resizable_container_vertical.tsx, src-docs/src/views/resizable_container/resizable_panel_collapsible.tsx, src-docs/src/views/resizable_container/resizable_panel_collapsible_options.tsx, src-docs/src/views/resizable_container/resizable_panels.tsx, src/components/resizable_container/__snapshots__/resizable_panel.test.tsx.snap, src/components/resizable_container/resizable_panel.test.tsx, src/components/resizable_container/resizable_panel.tsx, upcoming_changelogs/6534.md
Added tabindex prop to EuiResizablePanel for keyboard accessibility. Removing a number of axe-core violations for unreachable content and added documentation to help teams know when they need to add `tabindex` prop. Closes #5295.
---
=> [EuiResizablePanel] Added tabindex prop to EuiResizablePanel for keyboard accessibility.

src-docs/src/views/tables/basic/basic.tsx, src/components/basic_table/basic_table.tsx, upcoming_changelogs/6543.md
closes https://github.com/elastic/eui/issues/5014
While converting EuiBasicTable to Emotion, I happened upon this tbody logic/ref added when EuiInMemoryTable was first introduced (https://github.com/elastic/eui/pull/390), although unfortunately, I could not find any context as to why it was introduced/approved.
Unfortunately, I strongly feel that this behavior is problematic at worst (accessibility - keyboard users who tab into a loading table will never be able to tab off) and totally unnecessary at best (we're adding and removing 11 event listeners on loading change, for very little UX benefit).
I'm proposing we remove this, with designer approval and approval of our resident a11y expert.
=> [EuiBasicTable] Remove preventing all mouse/keyboard interactions when `loading`

src/components/modal/__snapshots__/modal_header_title.test.tsx.snap, src/components/modal/modal_header_title.test.tsx, src/components/modal/modal_header_title.tsx, upcoming_changelogs/6547.md
There are several Kibana instances of devs doing things like `<EuiModalHeaderTitle><EuiTitle size="s"><h3>`, which we can boil down to `<EuiModalHeaderTitle size="s" component="h3">`, but Typescript is complaining about it.
These props are currently already being passed via `...rest`, so this is primarily just a type change with a changelog so we can do a patch release for the Kibana upgrade.
=> [EuiModalHeaderTitle] Fix type errors when passed EuiTitle props

src-docs/src/views/i18n/context.js
Added a `lang="en | fr"` attribute to the container in our [i18n Context demo](https://eui.elastic.co/#/utilities/i18n#context). This ensures screen readers will load the correct dictionary for pronunciation and inflection. No axe-core errors detected after the change.
Closes #5368
=> Added a lang attribute to EUI i18n context EN | FR demo.

i18ntokens.json, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.tsx, upcoming_changelogs/6549.md
Updated the `EuiSuperSelect` screen reader instructions to more explicitly say "Up and Down arrow keys" and capitalize "Escape". Tested with VoiceOver on Safari + Firefox. Screenshot below.
Closes #5363.
=> [EuiSuperSelect] Updated i18n default instructions string

src/components/card/card.test.tsx, src/components/card/card.tsx, upcoming_changelogs/6551.md
Fixes #6545 
Resolved a bug that causes the `onClick` method to be triggered twice when clicking on a card title by creating a condition inside of `outerOnClick` to ensure the link does not contain a duplicate click event. Updated tests accordingly
**Testing:**
1. Pull branch and open `src-docs/src/views/card/card_beta.tsx`. Update the first `EuiCard` instance (line 13) to: 
```
<EuiCard
icon={<EuiIcon size="xxl" type="dashboardApp" />}
title={<span>Dashboards</span>}
description="Example of a card's description. Stick to one or two sentences."
onClick={() => {
console.log('Dashboards Clicked');
}}
betaBadgeProps={{
label: 'Beta',
tooltipContent:
'This module is not GA. Please help us by reporting any bugs.',
}}
/>
```
2. Spin up EUI and navigate the the EuiCard Beta Badge example. When …
=> [EuiCard] Harden Click Event Criteria to Prevent Duplicate `onClick` Events

src-docs/src/views/skeleton/skeleton_example.js, src/components/skeleton/skeleton_text.styles.ts, src/components/skeleton/skeleton_title.styles.ts
This PR makes the **EuiSkeletonText** and **EuiSkeletonTitle** have a more rectangular `border-radius`.
=> [EuiSkeleton] Design review

src-docs/src/views/skeleton/skeleton_circle.tsx, src-docs/src/views/skeleton/skeleton_example.js, src-docs/src/views/skeleton/skeleton_loading.tsx, src-docs/src/views/skeleton/skeleton_rectangle.tsx, src-docs/src/views/skeleton/skeleton_text.tsx, src-docs/src/views/skeleton/skeleton_title.tsx, src/components/loading/__snapshots__/loading_content.test.tsx.snap, src/components/skeleton/__snapshots__/skeleton_circle.test.tsx.snap, src/components/skeleton/__snapshots__/skeleton_loading.test.tsx.snap, src/components/skeleton/__snapshots__/skeleton_rectangle.test.tsx.snap, src/components/skeleton/__snapshots__/skeleton_text.test.tsx.snap, src/components/skeleton/__snapshots__/skeleton_title.test.tsx.snap, src/components/skeleton/index.ts, src/components/skeleton/skeleton_circle.test.tsx, src/components/skeleton/skeleton_circle.tsx, src/components/skeleton/skeleton_loading.test.tsx, src/components/skeleton/skeleton_loading.tsx, src/components/skeleton/skeleton_rectangle.test.tsx, src/components/skeleton/skeleton_rectangle.tsx, src/components/skeleton/skeleton_text.test.tsx, src/components/skeleton/skeleton_text.tsx, src/components/skeleton/skeleton_title.test.tsx, src/components/skeleton/skeleton_title.tsx, src/components/skeleton/utils.ts, upcoming_changelogs/6562.md
closes https://github.com/elastic/eui/issues/4814
This adds the loading accessibility detailed in #4814. I recommend following along by commit if possible.
- All `EuiSkeleton` components now accept `isLoading` and `children` props, which automatically handles conditionally rendering the skeleton components vs. the loaded content (`children`) for consumers.
- A `Loaded {contentAriaLabel}` announcement is now made whenever `isLoading` flips to false.
=> [EuiSkeletonLoading] Improve loading accessibility and bake in `isLoading` API handling

i18ntokens.json, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap, src/components/popover/__snapshots__/popover.rtl.test.tsx.snap, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.tsx, upcoming_changelogs/6567.md
* Updating screen reader help text in EuiPopver and i18nJSON.
* Updating EuiPopover snapshots.
This PR closes #5282 
---
=> Updating EuiPopover screen reader text to include mobile cues.

src-docs/src/views/selectable/selectable.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx, upcoming_changelogs/6571.md
closes https://github.com/elastic/eui/issues/6565
This bug was occurring whenever group labels existed in the `options` array that were not located at the start of the array.
- Go to https://eui.elastic.co/pr_6571/#/forms/selectable and inspect the `<li>` items in the first example.
=> [EuiSelectable] Fix incorrect `aria-posinset` indices

generator-eui/component/index.js, generator-eui/component/templates/_component.scss, generator-eui/component/templates/_index.scss, generator-eui/component/templates/component.styles.ts, generator-eui/component/templates/stateless_function.tsx, generator-eui/component/templates/test.tsx, package.json, yarn.lock
Updated the `yo-component` script to create Emotion files for CSS-in-JS when new components are created instead of Sass files. This change only applies to the `stateless function` option, not the component class template. 
Upgraded `Yo` to version `4.3.1`!
Fixes #6536 
Side note: Prettier did a number on `generator-eui/component/index.js` so it looks like a lot more changed.
**Create a new component with `yo-component`**
1. Run `yo-component` in the terminal. 
~_(If you're using an M1 Mac, you may need to update a file within `node_modules` to get this to work. See below.)_~
Choose: 
- `Stateless function`
- Enter `testComponent`
- [Enter]
- Enter 'Y'
2. The script should have completed and a new directory should be available
- `index.ts`
- `testComponent.styles.ts`
- …
=> [Yeoman] Remove Sass Template Files for New Component Script

src/components/search_bar/filters/field_value_selection_filter.spec.tsx, src/components/search_bar/filters/field_value_selection_filter.tsx, upcoming_changelogs/6577.md
closes #6540
closes #6569
Huge shout out to @robert-seymour-numerated for extremely accurately narrowing down the location in our code in which this bug was occurring, saving me a whole bunch of time 🙌 
And another bonus shout out to @Heenawter for requesting the new `changedOption` parameter/API that we added in #6487, which made this fix extremely easy and require 0 array iteration/comparison 🎉 
I recommend checking the git commit messages for more context & detail as to how the fix works.
The buggy behavior can be reproduced/compared against [production docs](https://elastic.github.io/eui/#/tabular-content/in-memory-tables#in-memory-table-selection).
- Go to https://eui.elastic.co/pr_6577/#/tabular-content/in-memory-tables#in-memory-table-selection, click "Load users"
- Click the …
=> [EuiSearchBar] Fix `multiSelect: false` filter behavior

src-docs/src/views/code/code_example.js, src-docs/src/views/code/line_numbers_highlight.tsx, src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/code/__snapshots__/code_block_annotations.test.tsx.snap, src/components/code/__snapshots__/utils.test.tsx.snap, src/components/code/code_block.test.tsx, src/components/code/code_block.tsx, src/components/code/code_block_annotations.spec.tsx, src/components/code/code_block_annotations.style.ts, src/components/code/code_block_annotations.test.tsx, src/components/code/code_block_annotations.tsx, src/components/code/code_block_full_screen.tsx, src/components/code/code_block_line.styles.ts, src/components/code/utils.test.tsx, src/components/code/utils.tsx, upcoming_changelogs/6580.md
closes https://github.com/elastic/eui/issues/6564
This PR implements a new `annotations` API for EuiCodeBlock, with the primary purpose of aiding the @elastic/docs-engineering team and new Elastic docs efforts.
Example usage:
```jsx
<EuiCodeBlock
lineNumbers={{
annotations: {
1: <>A <b>special</b> note about this line</>,
9: 'Also accepts quick plaintext notes',
}
}}
>
{}
</EuiCodeBlock>
```
QA link: https://eui.elastic.co/pr_6580/#/editors-syntax/code#line-numbers
=> [EuiCodeBlock] Add new `lineNumbers.annotations` API

src/components/form/range/range_track.tsx, upcoming_changelogs/6588.md
This PR fixes a bug in `EuiRange` where styles were applied incorrectly when custom ticks were passed but `showTicks` were `false`.
Per logic, I think that consumers shouldn't be passing custom ticks if they're not going to show them. But... Just in case they pass, we can improve the design.
So the styles for the ticks **should only** be applied when consumers specifically set the `showTicks` to `true`.
Closes #6578.
You can test by looking into https://eui.elastic.co/pr_6588/#/elastic-charts/metric-chart#single-value.
=> [EuiRange] Fix bug when `showTicks` is `false`

src-docs/src/views/image/image_example.js, src-docs/src/views/image/image_svg.tsx
(Second stab at https://github.com/elastic/eui/pull/6591)
I got confused when using auto-generated SVG files with EUI Image because the files were "disappearing". The svgs didn't have defined sizes. I talked with Cee and they proposed a workaround. We're documenting that here so the answer can be there when someone else gets confused!
This just adds docs--let me know if there's a check that you actually want me to go through for this PR that I crossed off.
~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground …
=> Add docs for using EuiImage with SVGs

src/components/code/__snapshots__/code_block_annotations.test.tsx.snap, src/components/code/code_block_annotations.tsx, upcoming_changelogs/6600.md
Follow up to https://github.com/elastic/eui/pull/6580#discussion_r1105150992
~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#adding-playground-toggles)**~ …
=> [EuiCodeBlock] Anchor annotation down left

src-docs/src/components/guide_section/_utils.js, src-docs/src/components/guide_section/_utils.test.js, upcoming_changelogs/6603.md
Yesterday I merged #6595 to update `EuiCodeBlock` regex to ignore template literal comments. This change caused a bug in Safari because it used the currently unsupported [negative lookbehind](https://caniuse.com/js-regexp-lookbehind). I've updated the regex to use negative lookahead and keyed off the end of the template literal string instead of the beginning.
Retested with Chrome, Safari, Edge, and Firefox locally as well as opened CodeSandbox from playground links in each browser. Expanded unit test for this case.
* Updated EuiCodeBlock regex to support Safari using negative lookahead.
* Changed regex comment to explain negative lookahead.
=> Fixing EuiCodeBlock regex for Safari regex support.

src-docs/src/views/call_out/call_out_example.js, src-docs/src/views/call_out/danger.tsx, src-docs/src/views/call_out/warning.tsx, src-docs/src/views/toast/danger.js, src-docs/src/views/toast/guidelines.js, src-docs/src/views/toast/toast_example.js, src-docs/src/views/toast/warning.js
Recently we worked on a new error icon, which should be used when different error patterns are displayed in the UI. For example when using `EuiToast` or `EuiCallOut`. We know that the difference between an error and a warning might be slight, but it's also essential when we want to have a recognized and easy-to-understand patter and product. In this PR, I'm updating some small pieces of documentation here and there to communicate this difference clearly. 
Toast Guidelines
Toast examples
Callout examples
Related to: 
https://github.com/elastic/eui/issues/6554
https://github.com/elastic/kibana/pull/151413
=> Error & warning guides

src/components/accessibility/skip_link/skip_link.tsx, upcoming_changelogs/6613.md
I spiked out adding an `EuiSkipLink` to Kibana in https://github.com/elastic/kibana/pull/150461/commits/5267bc405b60fd7ddc126804f382f637d6f7a10a, but unfortunately ran into multiple issues with the skip link not working as expected.
The problem arises with how Kibana progressively and dynamically renders its layout, and EuiSkipLink storing "valid" IDs/selectors in state. What happens is that the skip link renders on initial load when the header is rendered but the app/content isn't yet loaded. The `destinationalEl` is stored as null and clicks end up doing nothing even after the main content actually loads in.
The fix is to not store valid destination checks in state but instead run them on every click. This is potentially a very minor microperf hit, but not significant by any means (the …
=> [EuiSkipLink] Better handling of dynamically rendered content

src-docs/src/views/text/text.js, src/components/text/__snapshots__/text.styles.test.ts.snap, src/components/text/text.styles.ts, upcoming_changelogs/6615.md
Updated the styling of nested ordered lists (`ol`) to align with GitHub's list style, which is a popular format used in Markdown or MDX formatting. These changes will enhance the readability and consistency of our content, and ensure that our lists are easily understood by readers.
Added a margin-bottom property exclusively to the direct child `ul` and `ol` elements of the **EuiText** component. This change will ensure that the spacing between nested lists within the **EuiText** component is consistent and visually pleasing. Other child elements of **EuiText** will not be affected by this change.
Closes #6611.
=> [EuiText] Update nested ordered lists styles

src/components/badge/badge_group/badge_group.styles.ts, upcoming_changelogs/6618.md
This PR closes #6617.
Fix the issue with badges appearing within an `EuiBadgeGroup`, where the CSS rule to override the `margin-inline-start` was not being applied correctly due to the order of appearance in the CSS rules. 
With the fix, the correct order of appearance is now enforced, allowing the margin to be properly overridden and ensuring that badges are displayed in the desired position within the `EuiBadgeGroup`.
=> Fix rule to override `margin-inline-start` for badges inside a `EuiBadgeGroup`

src-docs/src/routes.js, src-docs/src/views/app_view.js
closes #4762
EUI as a team has decided to remove the left/right arrow key press behavior that would cause the user to go to the "next" or "previous" page in the side nav list. We made this decision for several reasons:
1. It's an accessibility issue - the fact that SR/keyboard users have no idea that it's there and that it behaves unpredictably is problematic
2. It's a dev point of friction - particularly with data grid etc., it's easy (when live-coding) to end up with stranded focus while using arrow keys to navigate the grid and end up on a totally different page than you wanted to be
3. It's no longer used by anyone on the team. If we're getting to the point of far-reaching changes where _every page_ in our docs need to be tested/QA'd, we should be writing automated testing or visual …
=> [Docs] Remove arrow key page/route navigation

src-docs/src/views/selectable/selectable_custom_render.tsx, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/selectable.spec.tsx, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable.tsx, upcoming_changelogs/6631.md
closes https://github.com/elastic/eui/issues/6627
In #5613 and [#5693](https://github.com/elastic/eui/pull/5693/commits/6bccb75a37b8132f0b6395471d06bc4c4eaa4f77#diff-2bc165a0bf23c9a90824394f5072dc0b25e65056dcac4c148cb465d149fcd6ac), an early return was added to the space/enter keydown listeners to ensure the search clear button still worked without accidentally selecting an option.
It turns out we should have been more aggressive about this early return and put it in front of the entire listener so that the up/down arrow keys also did not function when on the clear button (or any other wildcard interactive content passed by consumers). The arrow keys and enter/space keys should only function when consumers are focused either on the searchbox, or on the listbox.
Custom interactive child …
=> [EuiSelectable] Disable arrow key navigation on non-search/listbox children

src-docs/src/views/super_select/super_select_complex.js, src-docs/src/views/super_select/super_select_example.js, src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select_control.test.tsx.snap, src/components/form/super_select/_super_select_control.scss, src/components/form/super_select/super_select.tsx, src/components/form/super_select/super_select_control.test.tsx, src/components/form/super_select/super_select_control.tsx, upcoming_changelogs/6630.md
closes https://github.com/elastic/eui/issues/6189
This PR adds a working `placeholder` prop that accepts either a string or ReactNode (to potentially match `inputDisplay`, which can also be a ReactNode).
This PR also incidentally cleans up and removes some unnecessary screen reader accessibility that was not quite working as intended. Rationales are in commit messages/code comments.
- Go to http://localhost:8030/#/forms/super-select#more-complex
=> [EuiSuperSelect] Add new `placeholder` API; clean up screen reader accessibility

src-docs/src/views/datagrid/cells_popovers/cell_popover_rendercellpopover.tsx, src-docs/src/views/datagrid/cells_popovers/datagrid_cell_popover_example.js, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/body/footer/data_grid_footer_row.test.tsx, src/components/datagrid/data_grid_types.ts, upcoming_changelogs/6632.md
The Discover team requested an API in https://github.com/elastic/kibana/pull/152480 to allow setting props on the cell popover. This prop will enable them to, e.g. set custom `resize` CSS on the cell popover panel, making their cell popovers resizable, and additionally set custom min/max height/widths.
The new `setCellPopoverProps` API behaves exactly the same as `setCellProps` does for the cell, and allows customizing (almost) any prop that `EuiPopover` takes, except for the `button` and `closePopover` props.
Example usage:
```jsx
<EuiDataGrid
renderCellPopover={({ setCellPopoverProps, DefaultCellPopover, ...props }) => {
// Set a custom className on each cell popover panel
useEffect(() => {
setCellPopoverProps({ panelClassName: 'customCellPopover' });
}, [setCellPopoverProps]);
// …
```
=> [EuiDataGrid] Add new `setCellPopoverProps` API to `renderCellPopover`

src/components/selectable/selectable_list/_selectable_list.scss, src/themes/amsterdam/global_styling/mixins/_states.scss, upcoming_changelogs/6637.md
closes https://github.com/elastic/eui/issues/6633
This PR attempts to fix the odd focus ring behavior for `EuiSelectable`s that are listboxes only (i.e., do not have the `searchable` prop).
Unfortunately, due to limitations of `:focus-within` and `:focus-visible` (https://github.com/WICG/focus-visible/issues/151), we can only support clear focus rings for for browsers that support the `:has` selector (i.e. all browsers except FF, which is working on `:has` support).
- Go to https://eui.elastic.co/pr_6637/#/forms/selectable#the-basics
=> [EuiSelectable] Fix focus ring on non-searchable listboxes

src-docs/src/services/playground/iconValidator.js, src/components/icon/__snapshots__/icon.test.tsx.snap, src/components/icon/icon_map.ts, upcoming_changelogs/6640.md
After a conversation with the Elastic Charts team (@dej611 and @stratoula - thank you!) about our rename of the `alert` icon to `warning` (https://github.com/elastic/eui/pull/6608), we've determined that this change unfortunately puts an undue onus on their team due to how their constants, saved objects, and rendering functions are tied together. A quick snippet from our conversations:
> I've run thru the various editors and checked what's the impact of this new alias, and things are a bit more complicated than planned.
> It's not just about rendering, but also configuration in the Lens editor. The ad hoc code has to be deployed into several places for both Annotations and Reference Lines. Also the expression requires both old and new alias to be available for validation.
> An alias on …
=> [EuiIcon] Add legacy/undocumented `alert`->`warning` alias

src/components/page/page_content/page_content.tsx, upcoming_changelogs/6643.md
closes https://github.com/elastic/eui/issues/6642
The `HTMLAttributes` type should be coming from `react`, not `enzyme`.
=> Fix HTMLAttributes type incorrectly coming from `enzyme`

src/components/accessibility/skip_link/skip_link.test.tsx, src/components/accessibility/skip_link/skip_link.tsx, upcoming_changelogs/6646.md
Kibana needs nuanced fallback support for skip link behavior. Because it has such a huge variety of individual plugins/apps, we have no guarantee over whether:
1. Apps are using `Eui/KibanaPageTemplate` (which uses the `main` tag)
2. Apps are using the old, deperecated page template components (which does not use the `main` tag but outputs an `.euiPageContent` class we can hook into)
3. Apps are not using any of EUI's page templates whatsoever and we need to target `.kbnAppWrapper` as a last-ditch fallback
Unfortunately, passing `main,.euiPageContent,.kbnAppWrapper` does not work as expected because today I learned I [don't actually know how `document.querySelector` works](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) - I assumed it was targeting the first …
=> [EuiSkipLink] Add array support for `fallbackDestination` prop

src/components/code/code_block_full_screen.tsx, src/components/flyout/flyout.tsx, src/components/image/image_fullscreen_wrapper.tsx, upcoming_changelogs/6645.md
The `scrollLock` property on `EuiFocusTrap` (actually an underlying 3rd party library, `react-focus-on`) allows preventing scrolling on the background and additionally "freezes" the width of the of the body so that the removal/addition of the scrollbar doesn't cause the page width to change slightly whenever the focus trap opens:
This property was added for `EuiModal` in https://github.com/elastic/eui/pull/6327/commits/daf6a73fd34696630e234a44da06b84949595d89. This PR adds this functionality & behavior as well to all other components with focus traps with full-screen behavior, i.e. `EuiFlyout`, `EuiImage`, and `EuiCodeBlock`.
Note that `EuiDataGrid`'s fullscreen mode is not handled here, as page jumping is going to happen no matter what in EuiDataGrid (the entire grid is taken out of its …
=> [EuiFlyout] Preserve scrollbar width on `body` when EuiFlyout is open

src-docs/src/views/icon/icon_example.js
Closes #3961. 
This PR adds a callout with considerations for when importing SVGs as Components. As it can be seen on the following screenshot:
=> [EuiIcon Docs] Add callout with considerations for when importing SVGs as Components

package.json, yarn.lock
This PR is part of an ongoing effort to upgrade our various babel dependencies to the latest (https://github.com/elastic/eui/issues/6652) in order for Storybook to work as expected.
I'm opening PRs in very very atomic increments in order to 1. get frequent help from other devs testing, so I don't run into a "it works on my machine" issue, and 2. catch any issues that may arise in CI.
The following scripts work as expected locally:
=> Upgrade `@babel/core` and `@babel/cli` to latest

src/components/inline_edit/__snapshots__/inline_edit_text.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_title.test.tsx.snap, src/components/inline_edit/inline_edit_text.styles.ts, src/components/inline_edit/inline_edit_text.tsx, src/components/inline_edit/inline_edit_title.styles.ts, src/components/inline_edit/inline_edit_title.tsx
Spec Doc: [EuiInlineEdit Spec Doc](https://docs.google.com/document/d/19Ba2I3iF8W5-XYIdzHH4pBDuXbQ5hyKyv0m2o6Tw70s/edit?usp=sharing)
This PR adds styling to both `EuiInlineEdiText` and `EuiInlineEditTitle` components. 
When in `editMode` the font size of the text inside of the form control should match the the size of the text in `readMode`. 
When long text is saved, the `EuiEmptyButton` used in `readMode` will truncate the text.
1. Head to the [PR Preview](https://eui.elastic.co/pr_6660/#/display/inline-edit) for `EuiInlineEdit` and click on the `readMode` button to open `editMode`
2. Toggle through the `size` prop button group options and confirm that the font size used in the form control changes as the size is updated. (Note: Forms are compressed in sizes `small` and lower, so you …
=> [EuiInlineEdit] Add Dynamic Font Sizing & Truncation Styling

src/themes/amsterdam/global_styling/variables/_typography.scss, upcoming_changelogs/6665.md
At the moment, it's not possible to override `font-family` within the Amsterdam theme via a SCSS variable. This PR adds `!default` to the variables set to hardcoded values in that theme.
Tested locally with the [Typerighter](https://github.com/guardian/typerighter/) project. This allows us to keep our custom typeface consistent across SCSS- and Emotion-themed components.
Aware that eventually these will be deprecated! In the mean time, this will save us vendoring the theme in our codebase.
~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground …
=> Allow typography variables in Amsterdam theme to be overridden

src/components/code/code_syntax.styles.ts, upcoming_changelogs/6666.md
This was previously a Sass variable that was likely missed in EuiCode's Emotion conversion. It should be pointing at an `euiTheme` JS var instead.
To be honest, I have no idea where we even print bold code tokens so I'm not sure where to produce a before/after - this change is fairly straightforward however so I don't know if it needs thorough testing.
=> [EuiCode] Fix bold tokens

src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.tsx, src/components/notification/__snapshots__/notification_event.test.tsx.snap, src/components/notification/__snapshots__/notification_event_meta.test.tsx.snap, src/themes/amsterdam/global_styling/mixins/button.ts, upcoming_changelogs/6659.md
Issue #6656 identified a case where our `EuiBadge` component was using a helper to generate background colors that wasn't being overridden correctly when users opted for custom themes. This PR removes the helper method and codes badge background colors to match their corresponding filled button.
PR closes #6656
---
---
As part of this PR, we also tweaked the `success` and `accent` fill buttons to be more readable. Left is before, right is after.
=> [EuiBadge] Update named colors to use `EuiTheme` values

src/components/date_picker/__snapshots__/date_picker.test.tsx.snap, src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap, src/components/date_picker/_date_picker_range.scss, src/components/date_picker/date_picker.test.tsx, src/components/date_picker/date_picker.tsx, src/components/date_picker/date_picker_range.tsx, src/components/form/field_text/_field_text.scss, src/components/form/validatable_control/index.ts, src/components/form/validatable_control/validatable_control.test.tsx, src/components/form/validatable_control/validatable_control.tsx, upcoming_changelogs/6677.md
As part of my on-call work this week, I'm finishing up some older backlog work, in this case https://github.com/elastic/eui/issues/2017.
This PR:
- Adds the alert icon (and icon offset/padding affordance) to `EuiDatePicker`
- Converts `EuiDatePicker` from a class component to a function component
- Removes the need for `.euiFieldText-isInvalid` by adding a new `useEuiValidatableControl` hook that allows passing in control/input elements instead of relying on direct children
- Updates `EuiDatePickerRange` to account for the underlying date picker component using `:invalid` styling
**I strongly recommend following along [by commit](https://github.com/elastic/eui/pull/6677/commits) with whitespace changes turned off**, as there are a lot of "lines" changed that are just indentation changes. …
=> [EuiDatePicker] Add alert icon when `isInvalid`

src-docs/src/views/form_controls/text_area.js, src/components/form/text_area/__snapshots__/text_area.test.tsx.snap, src/components/form/text_area/_text_area.scss, src/components/form/text_area/text_area.tsx, upcoming_changelogs/6679.md
As part of my on-call work this week, I'm finishing up some older backlog work, in this case https://github.com/elastic/eui/issues/2017.
Quick note about this implementation - I'm aware that the text and icons may overlap and be difficult to see or read, but I consider that to be an edge case (most text won't go all the way to the bottom and all the way to the right), and to be a lesser evil than not showing enough information. I'd prefer to wait to see if it becomes an issue, and iterate on it in the future if it does.
~- [ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/cypress-testing.md) tests**~ Existing tests are nonexistent …
=> [EuiTextArea] Add alert icon when `isInvalid` and `isLoading` support

src-docs/src/views/form_controls/form_controls_example.js, src/components/form/file_picker/_file_picker.scss, src/components/form/file_picker/file_picker.tsx, upcoming_changelogs/6678.md
As part of my on-call work this week, I'm finishing up some older backlog work, in this case https://github.com/elastic/eui/issues/2017.
~- [ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/cypress-testing.md) tests**~ There aren't really any for EuiFilePicker. We should remedy this when we switch to Storybook
=> [EuiFilePicker] Use alert icon when `isInvalid`

src-docs/src/views/popover/popover.tsx, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/popover/__snapshots__/popover_footer.test.tsx.snap, src/components/popover/popover_footer.styles.ts, src/components/popover/popover_footer.tsx, src/components/popover/popover_panel/_popover_panel.tsx, src/components/tour/__snapshots__/tour_step.test.tsx.snap, upcoming_changelogs/6698.md
closes https://github.com/elastic/eui/issues/6695
The main (fairly simple) context fix is in https://github.com/elastic/eui/pull/6698/commits/7619bfc084916abb2af33da03f5f4a064765fb0e.
The [other commits](https://github.com/elastic/eui/pull/6698/commits) are an Emotion cleanup that I noticed while here and should have caught when cleaning up `EuiPopoverTitle` in #6221
- Go to https://codesandbox.io/s/exciting-water-vq07t2?file=/demo.js
- Open the popover, and then click the date range picker in the popover
- Click any time or date in the nested popover (causing a state rerender)
- Close the date popover and notice that the original popover's footer has now changed/bugged out
- Go to http://localhost:8030/#/layout/popover
- Click the popover button in the first example
- Open the nested …
=> [EuiPopoverFooter] Fix buggy panel padding size context

src/components/combo_box/combo_box.spec.tsx, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_input/combo_box_input.tsx, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx, upcoming_changelogs/6699.md
closes https://github.com/elastic/eui/issues/590
What this PR does:
- Prevents `backspace` keypresses on the `clear` button from triggering the last pill deletion
- Prevents `backspace` keypresses on when other pills are focused from triggering the last pill deletion
What this PR **does not do**:
- Allow `backspace` keypresses on pills to delete the pill that's currently focused (I agree with @1Copenut who mentioned in a meeting that that behavior felt unintuitive, and would require extra SR instructions to tell people it's even an option. We can potentially revisit this in the future if it becomes a feature request, but I don't see it as necessary for now)
- Go to https://eui.elastic.co/pr_6699/#/forms/combo-box (first demo)
- Using your keyboard, tab to the X button of the already …
=> [EuiComboBox] Only delete the last selected pill when pressing the backspace key when the input caret is present

src-docs/src/views/inline_edit/inline_edit_confirm.tsx, src-docs/src/views/inline_edit/inline_edit_example.js, src-docs/src/views/inline_edit/inline_edit_mode_props.tsx, src-docs/src/views/inline_edit/inline_edit_text.tsx, src/components/inline_edit/index.ts
Creation of the `EuiInlineEdit` component docs. These docs cover:
*Note: the `startWithEditOpen` prop doesn't have its own example (I thought it was self-explanatory) 
Please [visit the PR preview](https://eui.elastic.co/pr_6697/#/display/inline-edit) for `EuiInlineEdit` and read through the docs and examples
=> [EuiInlineEdit] Create `EuiInlineEdit` Docs

src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, src/components/form/field_number/__snapshots__/field_number.test.tsx.snap, src/components/form/field_number/field_number.spec.tsx, src/components/form/field_number/field_number.test.tsx, src/components/form/field_number/field_number.tsx, src/components/form/field_text/field_text.tsx, src/components/form/form_control_layout/__snapshots__/form_control_layout_delimited.test.tsx.snap, src/components/form/form_control_layout/_form_control_layout_delimited.scss, src/components/form/form_control_layout/form_control_layout_delimited.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/__snapshots__/range_input.test.tsx.snap, src/components/form/range/dual_range.tsx, src/components/form/range/range.tsx, src/components/form/range/range_input.test.tsx, src/components/form/range/range_input.tsx, src/components/form/validatable_control/validatable_control.test.tsx, src/components/form/validatable_control/validatable_control.tsx, upcoming_changelogs/6704.md
- This PR directly addresses both https://github.com/elastic/eui/issues/4082 and https://github.com/elastic/eui/issues/4097
- by adding an alert icon to `EuiFieldNumber` and `EuiRange/EuiDualRange` number fields when invalid numbers are typed by users)
- This PR is one of the last components needed for https://github.com/elastic/eui/issues/2017
I strongly recommend [following along by commit](https://github.com/elastic/eui/pull/6704/commits) as this PR touches and cleans up various sub-components that `EuiRange/EuiDualRange` rely on.
=> [EuiRange/EuiDualRange] Add alert icon when `isInvalid` and `showInput`

src-docs/src/views/search_bar/search_bar_example.js, src/components/search_bar/query/__snapshots__/ast_to_es_query_dsl.test.ts.snap, src/components/search_bar/query/__snapshots__/ast_to_es_query_string.test.ts.snap, src/components/search_bar/query/ast_to_es_query_dsl.test.ts, src/components/search_bar/query/ast_to_es_query_dsl.ts, src/components/search_bar/query/ast_to_es_query_string.test.ts, src/components/search_bar/query/ast_to_es_query_string.ts, upcoming_changelogs/6714.md
This PR fixes an issue where multi-word terms (without a field) aren't quoted properly when converted to an Elasticsearch query.
~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/documentation-guidelines.md#adding-playground-toggles)**~
=> [EuiSearchBar] Fix quoted phrases (without a field) removing quotes

.github/workflows/stale_issues.yml
What this PR does:
- Removes the `skip-stale-check` label: we no longer want to give ourselves the free "out" of infinitely ignoring stale closures. Instead, we should be either doing the work of addressing the issue, or determining that we as a team simply don't have the bandwidth and closing it for that reason.
- Removes skipping the stale check if the issue is assigned to someone. Just because an issue is assigned does not mean it's being actively worked on, and we need to hold assignees accountable.
- Extends the stale issue length from 6 months to ~1 year (i.e., giving us a bit more grace period before definitively closing issues the EUI team will not be working on).
- Updates the messaging around stale issues to clarify what will happen (auto closing), and what issue-openers can do …
=> Update stale bot skips, messages, and durations

.github/workflows/label_commenter.yml, .github/workflows/label_commenter_config.yml
This PR sets up the [Label Commenter](https://github.com/marketplace/actions/label-commenter) GitHub action, which has the `github-actions` bot auto-reply with a response of our configuration based on any label applied.
I've set currently set up just one auto response based on the `help wanted` label (indicating EUI will not be actively working on the issue and that the opener or the community at large will be expected to).
You can see it in action here in my fork: https://github.com/cee-chen/eui/issues/6
N/A - dev/GitHub only
=> [GitHub Actions] Add auto-responses based on applied labels

src-docs/src/views/datagrid/basics/container.js, src-docs/src/views/datagrid/basics/flex.js, src-docs/src/views/datagrid/cells_popovers/column_cell_actions.js, src-docs/src/views/datagrid/schema_columns/column_actions.js, src-docs/src/views/datagrid/schema_columns/column_widths.js, src-docs/src/views/datagrid/schema_columns/control_columns.js, src-docs/src/views/datagrid/styling/styling_grid.js, src-docs/src/views/datagrid/toolbar/_grid.js, src-docs/src/views/datagrid/toolbar/additional_controls.tsx
This is my first time attempting to contribute to Eui. I read through the contribution guidelines, but it's very likely I'm still missing something.
When using `EuiDataGrid` code snippets from the docs, I noticed `setPagination` updates pagination state by accessing the previous state value directly, rather than by using the previous state value provided by the `setState` callback. The preferred method of accessing previous state when constructing and setting new state is via `setState` callback. In addition accessing the state directly results in an unnecessary `useCallback` dependency.
No changelog - documentation changes only
=> [EuiDataGrid Docs] Minor update to EuiDataGrid docs code examples

.prettierrc, src/components/form/form.styles.test.tsx, src/components/form/form.styles.ts, src/components/form/switch/_switch.scss, src/global_styling/variables/_form.scss, upcoming_changelogs/6729.md
Fixes #6690
Fixes #6692
The current contrast ratio for checkbox outlines in both light and dark modes does not meet WCAG AA guidelines for UI components. This PR increases the threshold for the shade and tint that are used the generate the outline color. 
<br />
⭐ **What else does this affect?**
In order to increase the contrast ratios, I used the `euiFormCustomControlBorderColor` used with both SASS and Emotion. 
There should be no large visual differences with this change. This key affects the following components:
- [EuiSwitch](https://eui.elastic.co/pr_6729/#/forms/selection-controls#switch) - Thumb/Slider
- `euiCustomControl` mixin
- [EuiColorPicker](https://eui.elastic.co/pr_6729/#/forms/color-selection#color-picker) - Hue range, color stops
- …
=> [EuiForm] Increase Contrast on `EuiForm` Section Controls to Pass WCAG AA Standards

wiki/eui-team-processes/upgrading-kibana.md
Trevor and I were tweaking a shared plugin component for while debugging a Kibana upgrade today and realized we both can never remember what the dang command for hot reloading plugin changes is. We're memorializing this our docs so we can quickly reference it in the future.
=> [wiki] Document `yarn kbn watch` command for Kibana plugins

.github/ISSUE_TEMPLATE/accessibility.md, .github/ISSUE_TEMPLATE/ask-a-question.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
closes #6706
The following are a basic set of templates that mainly apply the correct labels and prompt the issue reporter for additional information.
The "Ask a question" template also takes the opportunity to preemptively ask the user to check for existing answers first, and points them to the correct location.
The Bug report and Feature request templates are primarily based on Github's default template. I modified the Bug report a bit to ask users to provide a code sandbox if possible.
Let me know what you think. Is there anything else we'd like to include?
=> Created issue templates

.buildkite/pipeline.yml
The `pipeline.yml` file agent entry for memory needed to be a string "4G". This PR should fix the error being thrown.
=> Agent memory value needed to be a string.

src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, src/components/form/field_number/__snapshots__/field_number.test.tsx.snap, src/components/form/field_number/field_number.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/__snapshots__/range_input.test.tsx.snap, upcoming_changelogs/6741.md
For some arcane React reason, our `EuiFieldNumber` change in https://github.com/elastic/eui/pull/6704/commits/37c35ea5ebfea0a069396207767dba65403e809b (that added detection of native browser `:invalid` state) is causing extra rerender cycles and redux sync issues with the Lens team, which is reproducibly causing a failure/bug in the latest Kibana upgrade: https://github.com/elastic/kibana/pull/155208
After a bit of debugging with Drew and determination of what can and can't be fixed on their end, I spiked out reverting the `isNativeInvalid` functionality and confirmed that seemed to fix the issue on my local Kibana. I then experimented with rewriting the native detection logic to try and reduce vectors that could be causing the extra rerender, and... I think it worked??
Honestly, I'm not …
=> [EuiFieldNumber] Clean up native `:invalid` detection

package.json, src/components/focus_trap/focus_trap.spec.tsx, src/components/focus_trap/focus_trap.tsx, upcoming_changelogs/6744.md, yarn.lock
This PR fixes an issue discovered by @Heenawter and reported by many other Elastic engineers - all the credit to them for narrowing down this problematic bug. This fix/workaround will need to be backported to Kibana v8.8.
The `scrollLock` functionality added to EuiFlyout in https://github.com/elastic/eui/pull/6645 unfortunately appears to prevent scrolling on anything that's not the flyout itself (in Kibana specifically, but not in CodeSandbox, strangely enough). This includes popovers, dropdowns, and comboboxes within flyouts, and by extrapolation, modals.
Screenshot in https://github.com/elastic/kibana/issues/156161
The solution came from the author of our 3rd party focus trap dependency: https://github.com/theKashey/react-focus-on/issues/49:
> You might not need the actual logic behind …
=> [EuiFocusTrap] Workaround for `scrollLock` prop causing nested portals/popovers to be unscrollable

src-docs/src/views/inline_edit/inline_edit_text.tsx, src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap, src/components/inline_edit/inline_edit_form.test.tsx, src/components/inline_edit/inline_edit_form.tsx
Relates to #3928 
Allows users to select `Enter` to save and `Escape` to cancel inline edits. When a custom `onKeyDown` function is passed in through `editModeProps.inputProps` , it will take priority and override the default functionality.
=> [EuiInlineEdit] Add `onKeyDown` Mapping for Saving and Canceling Edits

src-docs/src/views/skeleton/skeleton_example.js, src-docs/src/views/skeleton/skeleton_live_props.tsx, src/components/skeleton/__snapshots__/skeleton_loading.test.tsx.snap, src/components/skeleton/skeleton_circle.tsx, src/components/skeleton/skeleton_loading.test.tsx, src/components/skeleton/skeleton_loading.tsx, src/components/skeleton/skeleton_rectangle.tsx, src/components/skeleton/skeleton_text.tsx, src/components/skeleton/skeleton_title.tsx, upcoming_changelogs/6752.md
When using `EuiSkeletonRectangle` in the new EuiInlineEdit component, I realized we need more customization around when loading/loaded announcements were made. These new props (hopefully) solve that issue:
- `announceLoadingStatus` (defaults to false)
- `announceLoadedStatus` (defaults to true)
- `ariaLiveProps` (escape hatch props passthrough to the underlying `aria-live` region - allows setting role, or conditionally turning off the `aria-live`, etc)
I'm aiming to ship these new props alongside the deprecation/removal of `EuiLoadingContent` to smooth over the transition.
- Go to https://eui.elastic.co/pr_6752/#/display/skeleton#customizing-screen-reader-announcements and test with a screen reader
~- [ ] …
=> [EuiSkeleton] Add new props that allow for more screen reader control

src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_text.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_title.test.tsx.snap, src/components/inline_edit/inline_edit_form.test.tsx, src/components/inline_edit/inline_edit_form.tsx
This PR originally started as just screen reader improvements to the `isLoading` state and then I ended up doing a bunch of other misc cleanup and fixes 😅 I recommend checking individual commit messages for details and reasonings behind changes:
- DOM cleanup: 894da9a0a65065913f2ef8027cdab8f615e92915
- `isLoading` screen reader UX improvement:
- d1b75f98f345af03389e787ff39368b89883517d
- 76e04a49d4e416439bf37d2ff3839c7a484cb81c
- Read mode screen reader UX improvement: ac19b54e97354398ccbcc849e6cad54ea9f6c54d
- `onChange` bugfix: a5001a7a371a67591fb0cb975c47140ddf1004ca
- `autoFocus` fix: a236a56177674bbffdcf44678987bb8ff9f59d1f
- Go to http://localhost:8030/#/display/inline-edit#validating-edited-text
- Start VoiceOver
- Tab to the inline edit read mode button (for the Validation example …
=> [EuiInlineEdit] DOM cleanup, a11y improvements, and fix breaking `onChange` bug

src-docs/src/views/page_header/page_header.tsx, src/components/page/page_header/__snapshots__/page_header.test.tsx.snap, src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, src/components/page/page_header/page_header_content.tsx, upcoming_changelogs/6753.md
Fixes #6693
EuiPageHeader [intentionally sets the content of the header](https://github.com/elastic/eui/blob/f7a86007ac173e113af8a3797ebbdaa0cf09443f/src/components/page/page_header/page_header_content.tsx#L362) to have a flex-direction of row-reverse. This is causing the last element of the within the array of items to catch focus first (via screenreader and keyboard).
This PR takes the responsibility of display order away from `flex`. Instead, the array is cloned and reversed so that the DOM matches the display order. Now, when accessed by keyboard, the first element in the list catches focus first. 
<details>
<summary> Before & After </summary>
<br/>
https://user-images.githubusercontent.com/40739624/236049754-9871a1d8-bc89-4950-868f-f9800b4a2b5f.mov …
=> [EuiPageHeader] `rightSideItems` Update DOM to Match Display Order

src/components/flyout/flyout.spec.tsx, src/components/flyout/flyout.tsx, src/components/focus_trap/focus_trap.spec.tsx, src/components/focus_trap/focus_trap.tsx, upcoming_changelogs/6764.md
https://github.com/elastic/eui/pull/6645 and https://github.com/elastic/eui/pull/6744 made EuiFlyouts use `padding-right` to preserve scrollbar width, which `react-remove-scrollbar` unfortunately sets `!important` for, which overrides [the inline padding styles](https://github.com/elastic/eui/blob/329eb41a8c36ba76be780fc6a45d375cf7184033/src/components/flyout/flyout.tsx#L217-L228) push flyouts use to push the page content.
The fix to this issue that push flyouts should not have `scrollLock` enabled - I've taken several measures at both the `EuiFlyout` and `EuiFocusTrap` levels to ensure this is the case.
- Go to https://elastic.github.io/eui/#/layout/flyout#push-versus-overlay
- Go to http://localhost:8030/#/layout/flyout#push-versus-overlay
=> [EuiFlyout] Fix broken push flyout behavior

src-docs/src/views/selectable/selectable_templates/sitewide_search.tsx, src/components/selectable/selectable_templates/_variables.scss, upcoming_changelogs/6761.md
Fixes #6623 
✅ Increased the color contrast on `EuiSitewideSearch` item meta labels to meet WCAG 4.5 contrast ratio requirement in both light mode and dark mode. 
These colors are calculated using the `makeHighContrastColor` color function, but they did not take a background color into account. This means the color was being calculated with the assumption that the background was white. On hover, these items have a light blue background. These colors will now be calculated with the hover background color in mind. 
<details>
<summary>🎨  Color Details & Changes</summary>
<br/>
**Light Mode Difference**
<br/>
**Dark Mode Difference**
| Sitewide Type | Color Before | Contrast Before | Color After (Light) | Contrast After (Light) | Color After (Dark) | Contrast After (Dark)
| -------------- | …
=> [EuiSitewideSearch] Increase Color Contrast on Meta Labels to Meet WCAG 4.5 Contrast Ratio

.stylelintrc.js, src/components/combo_box/_combo_box.scss, upcoming_changelogs/6766.md
Prepended and appended icon buttons were not centering the icon vertically in `EuiComboBox`. This PR fixes the CSS by updating a `height: auto` rule to be more specific.
Will QA for browsers, light/dark mode, and mobile in staging URL.
---
=> [EuiComboBox] Bug fix for `append` and `prepend` icons

src/components/context_menu/context_menu.test.tsx, src/components/context_menu/context_menu.tsx, upcoming_changelogs/6767.md
@tonyghiani requested a callback to know when navigating into and out of nested panels in `EuiContextMenu`. He specced out the feature for the EUI team in a Slack discussion. Cee and I discussed it and pair coded the solution presented here.
=> [EuiContextMenu] Added optional `onPanelChange` callback hook.

src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, src/components/form/field_number/__snapshots__/field_number.test.tsx.snap, src/components/form/field_number/field_number.spec.tsx, src/components/form/field_number/field_number.tsx, src/components/form/range/__snapshots__/range_input.test.tsx.snap, upcoming_changelogs/6760.md
This PR is a follow-up to our existing EuiFieldNumber enhancement that added detection of native browser invalidity (https://github.com/elastic/eui/pull/6741, https://github.com/elastic/eui/commit/37c35ea5ebfea0a069396207767dba65403e809b).
Specifically, this PR is meant to address a comment left in a Kibana upgrade: https://github.com/elastic/kibana/pull/155208#issuecomment-1531455336.
Initially I thought the `:invalid` issue on `EuiFieldNumbers` intended for decimal usage was already a problem beforehand. As it turns out, it had **not** been a visual problem because
1. On blur, `<input type="number">`s with an undefined step **update their validity status** to accept the decimal as valid (default browser behavior). Screencap of said behavior:
3. Our `:focus` styles (blue underline) were …
=> [EuiFieldNumber] Default to `step="any"` and check native validity on blur

.babelrc-test-env.js, .babelrc.js, package.json, scripts/babel/proptypes-from-ts-props/index.js, scripts/jest/.babelrc.js, yarn.lock
This PR is part of our ongoing `babel` upgrade work (https://github.com/elastic/eui/issues/6652). It removes the following unused babel packages:
- `@babel/plugin-syntax-dynamic-import`
- Per Babel's docs (https://babeljs.io/docs/babel-plugin-syntax-dynamic-import.html), `@babel/plugin-syntax-dynamic-import` is now included automatically in `@babel/core` above v7.8.0 (which we're above) as well as in `@babel/preset-env` which we already have. As such, we shouldn't need to define it manually in our package.json or as a babel plugin.
- `babel-plugin-dynamic-import-node`
- same reasoning as above - `EuiIcon` Jest tests do not fail with this removed, which would be the primary usage
- `babel-core@7.0.0-bridge.0`
- doesn't seem to be affecting anything either. will wait and see if CI throws
- …
=> [babel] Remove unused babel plugins/dependencies

.buildkite/pipelines/pipeline_pull_request_test.yml, catalog-info.yaml
This PR is infrastructure as code (IAC) to scaffold a new Buildkite agent. Merging this into `main` is the first step, then I can work from a long-tail feature branch for defining the actual job.
QA will be done after the job merges to verify the new agent was built correctly. I'll rebase my feature branch onto `main` and start building against it for the remainder of work on this agent.
=> [BUILDKITE] Adding IAC scaffold for new EUI agent.

src-docs/src/views/inline_edit/inline_edit_example.js, src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_text.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_title.test.tsx.snap, upcoming_changelogs/6757.md
This PR only formats copy that was updated in Github UI and wasn't linted, and a change log for the feature branch.
=> [EuiInlineEdit] `CHANGELOG` & Copy Linting

src-docs/src/views/inline_edit/inline_edit_example.js, src-docs/src/views/inline_edit/inline_edit_read_only.tsx, src-docs/src/views/inline_edit/inline_edit_text.tsx, src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_text.test.tsx.snap, src/components/inline_edit/__snapshots__/inline_edit_title.test.tsx.snap, src/components/inline_edit/inline_edit_form.styles.ts, src/components/inline_edit/inline_edit_form.test.tsx, src/components/inline_edit/inline_edit_form.tsx, src/components/inline_edit/inline_edit_text.test.tsx, src/components/inline_edit/inline_edit_text.tsx, src/components/inline_edit/inline_edit_title.test.tsx, src/components/inline_edit/inline_edit_title.tsx
Included in #3928 
✅ Create the `isReadOnly` prop for `EuiInlineEdit`. When the prop is true, a disabled `EuiEmptyButton` is displayed which locks the user in read mode and displays the text value. This does not affect edit mode. 
https://github.com/elastic/eui/assets/40739624/5a10ec7c-d7c0-4652-a935-4f3f2a2c9f9f
=> [EuiInlineEdit] Create `isReadOnly` Prop for Read Mode

catalog-info.yaml
After talking with our Ops team, I found out the `catalog-info.yaml` file needed a few more declarations to ensure the Buildkite job(s) run only on my feature branch. At least for now. This PR updates the catalog-info file with the needed Terraform declarations to limit builds to `feature/buildkite-migration`.
Will verify builds are only happening on my feature branch after the change is merged.
=> Revising Buildkite config file to run `pull_request_test` on one branch only

catalog-info.yaml
This PR fixes some logic from my earlier PR https://github.com/elastic/eui/pull/6789. I realized later in the day that I needed to focus on **branches** instead of **pull requests** and filter to my long-tail `feature/buildkite-migration` branch. This PR updates the `catalog-info.yaml` file to accomplish that task.
I've read through the docs recommended by our Ops team a second time and will confirm this updates the BK pipeline settings correctly.
=> [BUILDKITE] Update Terraform config to only build (run jobs) on one branch

catalog-info.yaml
This job will run the two previous jobs I've created, namely [pull request test](https://github.com/elastic/eui/blob/17647029fd47be52a027b24dc41e4908ae435326/catalog-info.yaml#L61) and [pull request deploy docs](https://github.com/elastic/eui/blob/17647029fd47be52a027b24dc41e4908ae435326/catalog-info.yaml#L102). Those jobs with now **only** run when this third job is triggered on a pull request.
This PR adds the third job configuration, disables the two existing jobs from running on their own, and changes the job run parameters to PR instead of code push.
@1Copenut will verify this job is created by Buildkite correctly and only runs when PRs are pointed at the `feature/buildkite-migration` branch.
=> [BUILDKITE] Scaffolding job to run test and deploy jobs on PR.

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_cell.tsx, upcoming_changelogs/6817.md
This PR attempts to provide an interim workaround to https://github.com/elastic/eui/issues/6804 while https://github.com/elastic/eui/pull/6806 is blocked due to a Chromium bug.
It adds the `hidden` attribute to SR text of cells that aren't currently being focused, which prevents the text from being selected/copied in all browsers. The currently focused cell should not be `hidden` and should still read out its cell position to screen readers.
It's not 100% perfect as the cell position of the currently focused cell will still be end up in a copy/paste selection, but that's infinitely easier to edit once vs having to modify **every** single cell.
- Go to http://localhost:8030/#/tabular-content/data-grid-advanced#ref-methods with a screen reader open
=> [EuiDataGrid] Reduce hidden SR text when copying text from multiple cells

wiki/eui-team-processes/upgrading-kibana.md
Our Kibana upgrade document doesn't include instructions for running Jest integration tests. This PR adds those instructions and a screenshot illustrating the test path.
Will QA mobile, dark mode, browsers in the PR docs link. I asked Tomasz to review the PR as he wasn't involved in our pair code session and is seeing these new docs cold. Kind of a DX hallway test.
=> [DOCS] Added Jest integration test help to Kibana upgrade.

src/components/code/code_block_copy.spec.tsx, src/components/code/code_block_copy.tsx, src/components/code/utils.tsx, upcoming_changelogs/6794.md
This PR fixes #6585 that was caused by an incorrect regex being used in `src/components/code/code_block_copy.tsx`. Rest of the replace logic stays the same.
- ~Checked in both **light and dark** modes~
- ~Checked in **mobile**~
- ~Props have proper **autodocs** (using `@default` if default values are missing) and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/playgrounds.md)**~
- ~Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting)**~
- ~Checked **[Code Sandbox](https://codesandbox.io/)** works for any docs examples~
- ~Checked for **breaking changes** and labeled appropriately~
- ~Checked for **accessibility** including keyboard-only and screenreader modes~
- ~Updated the …
=> fix(EuiCode): fix code block copy button not including the last character

src-docs/src/views/tables/expanding_rows/expanding_rows.tsx, src/components/table/_table.scss, upcoming_changelogs/6826.md
closes https://github.com/elastic/eui/issues/6770
Counter to our guesses/musings in the above linked thread, the issue with Safari was not the mutation observer (never fired) nor stale refs/rerenders. After adding timeouts of increasing lengths, I realized it was the animation itself that was causing Safari to return empty `innerText`.
The `overflow: hidden` on the container, in combination with the `max-height`, makes Safari calculate that the container's children are not visible. For not-visible children, `innerText` becomes `''` (you can test this right now in your browser by setting any DOM node to `visibility: hidden` and then pasting its `.innerText` value in the console).
I initially played around with a couple different options to try to keep the "expanding animation". I tried the …
=> [EuiTable] Remove overflow/height animation causing Safari cross-browser issues

src-docs/src/views/range/range_example.js, src-docs/src/views/range/ticks.tsx, src/components/form/range/__snapshots__/range_track.test.tsx.snap, src/components/form/range/range_track.test.tsx, src/components/form/range/range_track.tsx, upcoming_changelogs/6829.md
closes https://github.com/elastic/eui/issues/6807
This PR removes the hard-coded limit (thrown error) of 20 ticks visible, and instead uses the width of the track (on mount) to detect if each tick has a minimum width.
- If each tick has 5px or less of width, the component throws/errors and will not render (same behavior as before when more than 20 ticks were visible).
- If the component has between 5 to 20px of width available, the component will warn to the console, but not throw, and will still render
- If each tick has more than 20px of width, no warning or error will be thrown.
=> [EuiRange] Remove 20 tick hard limit, detect minimum tick width instead

scripts/deploy/build_docs, scripts/docker-ci/Dockerfile, scripts/test-a11y-docker.js, scripts/test-docker.js
I created a new Docker image that uses Debian 11 (Bullseye) with our same workflow commands and added a general update command to the script.
Checks will be in the CI log files only. This update is to an upstream Docker image used to run our regular test and deploy scripts.
=> Update Docker image to use Debian Bullseye

src/global_styling/variables/animations.ts, src/global_styling/variables/borders.ts, src/global_styling/variables/breakpoint.ts, src/global_styling/variables/levels.ts, src/global_styling/variables/size.ts, src/global_styling/variables/states.ts, src/global_styling/variables/typography.ts, src/services/breakpoint/_sorting.test.ts, src/services/breakpoint/_sorting.ts, src/services/theme/types.ts
This PR leverage JSDocs to provide the value for font weight and sizing tokens, to be a nice time-saver when using autocomplete suggestions from the IDE to provide the values of a token as the example:
Also, added direct links referring to the Eui Docs:
When developing some feature from a Figma file, we often have to deal with translating fixed values of the properties (i.e sizing, font weight, ...etc) into the corresponding EUI Token, so we need to look for the matching value for a EUI token, and for that, we need to visit the [EUI Website](https://elastic.github.io/eui), since Typescript autocomplete only tells us about its type:
Currently, Typescript suggestions only tell us about its type (i.e string, FontWeight):
Also, it's useful for debugging, when we are looking at a code already …
=> [DX] Leveraging JSDoc for font-weight and size tokens

src/components/markdown_editor/markdown_editor_toolbar.tsx, src/components/markdown_editor/markdown_types.ts, upcoming_changelogs/6840.md
Exposes an additional prop to markdown ui plugin button configurations, isDisabled, to be passed through to the underlying button in the toolbar. Use case being an instance where a markdown plugin is disabled for some reason, in the screenshot below this is due to a license level restriction. 
=> [EuiMarkdownEditor] Allow markdown plugins to disable toolbar button

catalog-info.yaml
Updating `catalog-info.yml` to point at the consolidated Buildkite PR job that will test and build docs.
QA will happen in CI logs and feature branch(es). There should be no errors here, but I'll add an empty BK job file if needed.
=> Updating `catalog-info.yml` to run combined PR job on Buildkite

wiki/contributing-to-eui/running-eui-locally.md
- Updates a link to the `nvm` GH repo
- Updates documentation around `yarn` and specifies the version of yarn (classic / v1) that must be used in the EUI repo
N/A, documentation only
=> [Wiki] Update yarn dependencies documentation

.buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml
PR fixes a mis-labeled Buildkite env variable, and an incorrect output string value.
This fix should allow the PR https://github.com/elastic/eui/pull/6871 to run correctly. That PR is failing because of the missing `GIT_BRANCH` variable. QA will happen on the other PR after this one is merged. I will re-run the existing PR jobs, and verify they both pass as expected.
=> [BUILDKITE] Fix mis-labeled `GIT_BRANCH` variable in combined test and deploy PR job

.buildkite/scripts/pipeline_pull_request_test.sh, .ci/jobs/elastic+eui+pull-request.yml, scripts/deploy/build_docs
PR removes the `npm run build` from the Buildkite test PR job. The command runs in the Buildkite deploy PR docs job. Running the build command twice seems unnecessary.
QA will consist of checking that all tests ran successfully, and that docs were deployed correctly. The `npm run build` command will run twice on this PR, because the change needs to be merged into the `feature/buildkite-migration` branch before Buildkite will pick it up. The next PR I issue should run the build step only once.
=> [BUILDKITE] Streamline PR job by removing second `npm run build` from combined PR job

src-docs/src/views/badge/notification_badge.tsx, src-docs/src/views/filter_group/filter_group_multi.js, src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.styles.ts, src/components/badge/badge.tsx, src/components/badge/badge_group/__snapshots__/badge_group.test.tsx.snap, src/components/badge/beta_badge/beta_badge.styles.ts, src/components/badge/color_utils.ts, src/components/badge/notification_badge/__snapshots__/badge_notification.test.tsx.snap, src/components/badge/notification_badge/badge_notification.styles.ts, src/components/badge/notification_badge/badge_notification.tsx, src/components/filter_group/__snapshots__/filter_button.test.tsx.snap, src/components/filter_group/filter_button.test.tsx, src/components/filter_group/filter_button.tsx, src/components/notification/__snapshots__/notification_event.test.tsx.snap, src/components/notification/__snapshots__/notification_event_meta.test.tsx.snap, upcoming_changelogs/6864.md
- Add `success` as a new `color` in **EuiNotificationBadge**
- Add a new prop to **EuiFilterButton** called `badgeColor` to support `success` in addition to `accent`.
- This request originated from feedback from the Security Solution. They are using **controls** on their Alerts page and mentioned the dark pink color could be interpreted as something negative or alarming, which is not the intended case when displaying the number of selections in a control. They expressed a desire for a more neutral color. One suggestion that came up was to use `subdued`. However, we're already using that `color` when `isDisabled` is set to `true`. As an alternative, I suggested the `success` color, which they agreed with. 
- I am using the background color from the `success` **EuiBadge** as it seems to be …
=> [EuiNotificationBadge] Add success color

src-docs/src/views/guidelines/getting_started/_app_setup.tsx, wiki/consuming-eui/README.md
I changed the snippet to be a stand-alone snippet that can be copied and replaced over an App.tsx file from create-react-app. I felt like it wasn't obvious or helpful to have `Page` included as part of the setup guide.
=> Updated get started guide

package.json, upcoming_changelogs/6884.md
Update supported Node versions in `package.json` to allow:
- Node 16 LTS (EOL 2023-09-11)
- Node 18 LTS (EOL 2025-04-30)
- Node 20 and up (EOL 2026-04-30 for Node 20)
Node 19 reached end of life this month.
1. Pull the branch
2. Use nvm to switch between node versions
3. Make sure `yarn` runs successfully on any Node 16, 18 and 20
=> build(node): update node engines

src/components/collapsible_nav/collapsible_nav.spec.tsx
We added Cypress testing to our release script semi-recently, and @breehall has been running into local failures/flakes with `EuiCollapsibleNav` that doesn't appear to be present in CI. This PR attempts to fix that flakiness 🤞
=> [EuiCollapsibleNav] Harden flaky Cypress test

src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/pagination/__snapshots__/pagination.test.tsx.snap, src/components/pagination/pagination.styles.ts, src/components/pagination/pagination.tsx, src/components/pagination/pagination_button.styles.ts, src/components/pagination/pagination_button.tsx, src/components/pagination/pagination_button_arrow.tsx, src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap, upcoming_changelogs/6893.md
Fixes #6890
When `EuiPagination` was converted to Emotion, a style hack was set and put in place in anticipation of the `EuiButtonEmpty` conversion. Now that the conversion is complete we no longer need the specificity hack. 
With both styles in place, the numbers within `EuiPagination` aren't spaced properly.
1. Find the incorrect styling [in production](https://elastic.github.io/eui/#/navigation/pagination) and confirm that the numbers are too close together within `EuiPagination`
2. Compare [staging](https://eui.elastic.co/pr_6893/#/navigation/pagination) and the [PR preview before the `EuiButtonEmpty` conversion](https://eui.elastic.co/pr_6861/#/navigation/pagination). Visually, they should be the same.
=> [EuiPagination] Remove Unneeded Styling Post `EuiButtonEmpty` Emotion Conversion

src/components/accessibility/skip_link/__snapshots__/skip_link.test.tsx.snap, src/components/button/__snapshots__/button.test.tsx.snap, src/components/button/button.tsx, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card_select/__snapshots__/card_select.test.tsx.snap, src/components/control_bar/__snapshots__/control_bar.test.tsx.snap, src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, upcoming_changelogs/6887.md
This bug was introduced during Caroline's Emotion conversion of EuiButton (which was merged in without thorough QA after she left). At least I presume it's a bug and not intentional, no other component's `className` behaves this way.
_(Bug discovered during `shouldRenderCustomStyles` work, pulling it out to its own PR for easy review and a separate changelog)_
=> [EuiButton] Fix overridden (instead of merged) `className`

src/components/icon/icon.test.tsx, src/components/icon/icon.tsx, upcoming_changelogs/6888.md
We were pulling out `style` from `props` but only passing it to svg `EuiIcon`s and not img `EuiIcon`s.
This would result in consumers passing in both a custom image and a `style` prop to `EuiIcon` not having that `style` render whatsoever.
_(Bug discovered during `shouldRenderCustomStyles` work, pulling it out to its own PR for easy review and a separate changelog)_
=> [EuiIcon] Fix missing `style` prop on custom icons

src/components/datagrid/_data_grid_data_row.scss, upcoming_changelogs/6881.md
closes https://github.com/elastic/eui/issues/6851
For some incredibly bizarre reason, Safari doesn't correctly update the flex width of the cell content (when rows are an undefined height/single flex row), which causes the action icons to overlap the content and makes the content less readable even when there is room for both the cell content and cell actions.
This workaround "animation" forces a rerender of the flex content width after the cell actions are done animating in. If the duration time is reduced, the fix becomes flaky/intermittent, occasionally working and occasionally not. No, I do not understand why 💀 
I've filed a bug for Safari for this behavior here: https://bugs.webkit.org/show_bug.cgi?id=258539
- **In Safari**, go to …
=> [EuiDataGrid] Safari workaround for cell actions hover animation

src-docs/src/views/inline_edit/inline_edit_example.js, src-docs/src/views/inline_edit/inline_edit_placeholder.tsx, src/components/inline_edit/__snapshots__/inline_edit_form.test.tsx.snap, src/components/inline_edit/inline_edit_form.styles.ts, src/components/inline_edit/inline_edit_form.test.tsx, src/components/inline_edit/inline_edit_form.tsx, src/components/inline_edit/inline_edit_text.tsx, src/components/inline_edit/inline_edit_title.tsx, upcoming_changelogs/6883.md
Fixes #6857 || Original PR: #6872
Creation of the `placeholder` prop for `EuiInlineEdit`.
Read Mode:
The `placeholder` value is displayed in `readMode` when the placeholder is present and no `defaultValue` is passed in or if `readModeValue` is empty. The `placeholder` text will also appear in a light color in `readMode`.
Edit Mode:
`placeholder` is passed to the `editMode` input form control.
Head over to EuiInlineEdit in staging and ensure you can do the following:
=> [EuiInlineEdit] Create `placeholder` prop for Inline Edit & Friends

.buildkite/.pull-requests.json
Adding the required config file to accept PRs from forked `EUI` repos securely. This config is very basic and locked down to just the EUI team for the moment.
QA will be a manual process, and will be tested against the `feature/buildkite-migration` branch for now. Will include the following:
=> [BUILDKITE]: JSON config to trigger PRs from forked repos

src/components/card/checkable_card/checkable_card.test.tsx, src/components/date_picker/super_date_picker/super_date_picker.test.tsx, src/components/date_picker/super_date_picker/super_update_button.test.tsx, src/components/form/checkbox/checkbox.test.tsx, src/components/form/range/dual_range.test.tsx, src/components/form/range/range.test.tsx, src/components/form/switch/switch.test.tsx, src/components/header/header.test.tsx, src/components/image/image.test.tsx, src/components/key_pad_menu/key_pad_menu.test.tsx, src/components/key_pad_menu/key_pad_menu_item.test.tsx, src/components/list_group/list_group_item.test.tsx, src/components/popover/popover.test.tsx, src/components/progress/progress.test.tsx, src/components/resizable_container/resizable_panel.test.tsx, src/components/tour/tour_step.test.tsx, src/test/internal/render_custom_styles.tsx
This is some final extra/optional work on top of #6896 - I didn't want to include it in the above PR as that was was big enough as it was. I recommend [reviewing by commit](https://github.com/elastic/eui/pull/6907/commits) and [turning off whitespace diffs](https://github.com/elastic/eui/pull/6907/files?w=1).
- Removes `skipStyles` API - now uses `skip: { style: true }`
- Removes `skipParentTest` API, now uses `skip: { parentTest: true }`
- Adds a new `skip` API which allows for granular skipping, e.g. `skip: { css: true }`
- Updates all tests using the old APIs (particularly ones that were skipping styles due to `...rest` spread - add tests that actually checks that consumer styles are correctly applied)
N/A, internal dev/tech debt only
=> [Emotion] Further enhance `shouldRenderCustomStyles`

src-docs/src/views/accordion/accordion_example.js, src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/accordion.tsx, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/notification/__snapshots__/notification_event.test.tsx.snap
Removes EuiAccordion's padding class map/modifiers (`.euiAccordion__padding--[size]`) in favor of a static `.euiAccordion__children` className.
- ⚠️ Note that there are two instances of CSS references to the removed padding modifiers in Kibana that we'll have to manually convert over to referencing `.euiAccordion__children` in the next upgrade:
- https://github.com/search?q=repo%3Aelastic%2Fkibana%20euiAccordion__padding--&type=code
This PR also incidentally renames the `EuiAccordionSize` type to a more specific `EuiAccordionPaddingSize` just for clarity, but this isn't a noteworthy change as this type is not exported at the top-most level for consumer usage.
This PR also removes a callout from the EuiAccordion docs that I noticed while QAing. The callout is no longer correct as …
=> [EuiAccordion] Children class cleanup 

src/components/link/link.styles.ts
I noticed this minor annoyance while trying to override some default link styling for the new EuiCollapsibleNav work and wanted to fix it separately (so I wouldn't have to introduce yet more `!important`s to the codebase).
- the `!important` appeared to be set because the `text-decoration: underline` in `_colorCSS` was overriding it
- `_colorCSS` should only be in charge of colors in any case and not hover/focus states, so removing that unnecessary CSS means we can remove the `!important`
- Go to https://eui.elastic.co/pr_6905/#/navigation/link#coloring-links
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/changelogs.md)** entry exists and is marked appropriately~ - I'm skipping a changelog on this as this is a technical detail unlikely …
=> [EuiLink] Remove unnecessary `!important` from styles

src/components/combo_box/combo_box_input/_combo_box_pill.scss, upcoming_changelogs/6910.md
@andreadelrio identified a bug where the compressed `EuiCombox` plain text pills were not aligned vertically. I added a rule to target these pills specifically and adjust the vertical margin.
PR closes #6899. 
---
=> [EuiCombobox]: Added a rule to reset margin on compressed plain text pills.

package.json, src-docs/src/views/focus_trap/focus_trap_example.js, src/components/focus_trap/focus_trap.stories.tsx, src/components/focus_trap/focus_trap.tsx, upcoming_changelogs/6908.md, yarn.lock
Upgrades to latest `react-focus-on` which allows setting `crossFrame=false` (https://github.com/theKashey/react-focus-on/issues/72).
Example of previous cross frame behavior:
- Go to https://codesandbox.io/s/qzf8zp?file=/demo.js
- Click the "Show flyout" button
- Click into the code panel/frame and try to type. Notice that it won't let you (at first at least, it may intermittently work if you click enough but the first click+type never does)
I wasn't able to test this working behavior locally for whatever bizarre reason, so I did a pre-release RC and created a demo CodeSandbox with the RC:
- Go to https://codesandbox.io/s/red-grass-zqrgvj?file=/demo.js
- Click the blank EuiFieldText and tab back and forth, confirm tabbing is trapped and does not go down to the console
- ⚠️  This doesn't …
=> [EuiFocusTrap] Default to not trapping focus across iframes

src/components/resizable_container/_resizable_collapse_button.scss, src/components/resizable_container/resizable_collapse_button.tsx, upcoming_changelogs/6926.md
I randomly noticed this while answering a support question today - the icon colors on `EuiResizablePanel`'s collapse button are incorrect after `EuiButtonIcon`'s Emotion conversion. 😬 
Assigning this PR to either Andrea (showing as last person who touched the component), or anyone on the EUI team, whoever gets to this first.
=> [EuiResizableCollapseButton] Fix icon colors

scripts/deploy/deploy_docs
Our Jenkins deployment job seems to be working differently than before and we can't figure out the exact reason why. This PR prints CURRENT_RELEASE and GIT_BRANCH environment variables that'll allow us understand where the issue is coming from.
Note: **do not run the `deploy_docs` script locally**, especially if you're authenticated with Google Cloud.
1. Check the updated code and make sure there are no syntax errors
=> build: log CURRENT_RELEASE and GIT_BRANCH in deploy_docs script

src-docs/src/components/guide_page/_guide_page.scss, src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/components/guide_section/guide_section.tsx, src-docs/src/components/guide_section/guide_section_parts/guide_section_text.tsx, src-docs/src/views/guidelines/getting_started/getting_started.js, src-docs/src/views/provider/provider_component_defaults.tsx, src-docs/src/views/provider/provider_example.js, src/components/portal/portal.tsx, src/components/provider/component_defaults/component_defaults.test.tsx, src/components/provider/component_defaults/component_defaults.tsx, src/components/provider/component_defaults/index.ts, upcoming_changelogs/6923.md
⚠️ Please be aware this work is merging into a **feature branch** (in order to avoid non-valid documentation in main). This initial PR sets up some basic infrastructure and initial documentation, but the actual behavior is not yet wired up (i.e., will not work as promised in the docs example). I'm planning on opening individual PRs for each component that we plan to support defaults for initially (at least portals, pagination, and focus trap as a bonus).
This PR sets up the prop, context, and documentation for an `<EuiProvider componentDefaults={}>` API that be used so that certain components (to be discussed) can have various settings configured at a global level instead of needing to be set on every instance.
I recommend following along [by …
=> [EuiProvider] Set up `componentDefaults` prop, context, & documentation

src/components/page/page_header/__snapshots__/page_header.test.tsx.snap, src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, src/components/tabs/__snapshots__/tab.test.tsx.snap, src/components/tabs/tab.styles.ts, src/components/tabs/tab.tsx, src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, upcoming_changelogs/6938.md
fixes https://github.com/elastic/eui/issues/6935
Pre-Emotion conversion (#6311), icons used within the `prepend`/`append` props of `EuiTab` correctly inherited the selected primary color (go to https://eui.elastic.co/v60.0.0/#/navigation/tabs#tabbed-content and click the hydrogen tab).
This PR correctly sets the selected text color of all children of `EuiTab`, and incidentally cleans up CSS, reducing unnecessary overrides and removing some CSS that isn't doing anything (I recommend [following along by commit](https://github.com/elastic/eui/pull/6938/commits)).
- Go to https://eui.elastic.co/pr_6938/#/navigation/tabs#tabbed-content
- Click the `Hydrogen` tab
- Regression testing
=> [EuiTab] Fix prepend/append elements not inheriting selected colors + misc CSS cleanup

wiki/eui-team-processes/releasing-versions.md
Adds a wiki section for EUI prerelease versions - something we've recently done for testing (e.g.) iframe behavior in CodeSandbox, and will very likely need to do again for the React 18 feature branch.
You can preview the documentation markdown file here: https://github.com/cee-chen/eui/blob/wiki/prerelease/wiki/eui-team-processes/releasing-versions.md#prerelease-process
N/A, documentation only
=> [Wiki] Document prerelease RC process

src-docs/src/views/theme/consuming_emotion_theme.tsx, src-docs/src/views/theme/theme_example.js, src/custom_typings/emotion.d.ts, src/services/theme/emotion.test.tsx, src/services/theme/emotion.tsx, src/services/theme/hooks.test.tsx, src/services/theme/hooks.tsx, src/services/theme/index.ts, src/services/theme/provider.tsx, src/services/theme/warning.ts, upcoming_changelogs/6913.md, wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
See https://emotion.sh/docs/theming
This work will support:
- Consumers who are used to `styled.` CSS-in-JS syntax, particularly the ability to use `(props) => props.theme.var` (which Kibana has multiple uses of across their codebase)
- Consumers who want to use the `css={}` prop without needing to import or call `useEuiTheme()` separately, e.g. `css={theme => ({ color: theme.euiTheme.colors.primary })`
<details><summary>Resolved questions</summary>
**Questions resolved in comment below: https://github.com/elastic/eui/pull/6913#issuecomment-1626384082**
Questions to answer:
- It's not clear to me why Greg/Caroline never mentioned Emotion theming or made use of Emotion's `ThemeProvider` before this. Was it intentional to avoid conflicts with other Emotion themes? Did they simply just not …
=> [Emotion] Add Emotion theming support

.ci/jobs/elastic+eui+deploy-docs.yml, .ci/jobs/elastic+eui+pull-request-deploy-docs.yml
I need a reliable way to differentiate the Jenkins and Buildkite CI environments during the migration. There's not a good Jenkins CI environment variable I can key off, so I'm adding one for the very short term.
https://github.com/elastic/eui/pull/6947 is blocked by this PR.
All QA will be done on the Jenkins CI environment to ensure this variable was added.
=> [CHORE] Adding a temp Jenkins env variable for the migration.

src/components/popover/input_popover.tsx, src/components/popover/popover.tsx, upcoming_changelogs/6955.md
@Heenawter is working on a custom `EuiSelectable` component that has a filter dropdown/popover selection menu in between the search box and the listbox. This filter popover has special custom focus behavior that returns focus to the searchbox after filter select, and not to the toggling popover button.
The solution their usage needs is something like this:
```tsx
<EuiPopover
closePopover={}
focusTrapProps={{
returnFocus: false,
onEscapeKey: // custom callback closing the popover and focusing the searchbox
onDeactivation: // custom callback focusing the searchbox
}}
/>
```
Unfortunately EuiPopover's default focus return behavior is getting in the way of their custom focus behavior. We should loosen the spread behavior of `focusTrapProps` to allow consumers to control focus UX as needed. …
=> [EuiPopover][EuiInputPopover] Allow more control via `focusTrapProps`

src/components/page/__snapshots__/page.test.tsx.snap, src/components/page/__snapshots__/page_template.test.tsx.snap, src/components/page/page.test.tsx, src/components/page/page_body/__snapshots__/page_body.test.tsx.snap, src/components/page/page_body/page_body.test.tsx, src/components/page/page_content/__snapshots__/page_content_body.test.tsx.snap, src/components/page/page_content/page_content.test.tsx, src/components/page/page_content/page_content_body.test.tsx, src/components/page/page_content/page_content_header.test.tsx, src/components/page/page_content/page_content_header_section.test.tsx, src/components/page/page_header/__snapshots__/page_header.test.tsx.snap, src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, src/components/page/page_header/page_header.test.tsx, src/components/page/page_header/page_header_content.test.tsx, src/components/page/page_header/page_header_section.test.tsx, src/components/page/page_section/__snapshots__/page_section.test.tsx.snap, src/components/page/page_section/page_section.test.tsx, src/components/page/page_side_bar/page_side_bar.test.tsx, src/components/page/page_sidebar/__snapshots__/page_sidebar.test.tsx.snap, src/components/page/page_sidebar/page_sidebar.test.tsx, src/components/page/page_template.test.tsx, src/components/page_template/__snapshots__/page_template.test.tsx.snap, src/components/page_template/bottom_bar/__snapshots__/page_bottom_bar.test.tsx.snap, src/components/page_template/bottom_bar/page_bottom_bar.test.tsx, src/components/page_template/empty_prompt/__snapshots__/page_empty_prompt.test.tsx.snap, src/components/page_template/empty_prompt/page_empty_prompt.test.tsx, src/components/page_template/inner/__snapshots__/page_inner.test.tsx.snap, src/components/page_template/inner/page_inner.test.tsx, src/components/page_template/outer/page_outer.test.tsx, src/components/page_template/page_template.test.tsx
This PR converts `EuiPage` and `EuiPageTemplate` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert EuiPage and EuiPageTemplate unit tests using enzyme render to RTL

src/components/accessibility/screen_reader_live/__snapshots__/screen_reader_live.test.tsx.snap, src/components/accessibility/screen_reader_live/screen_reader_live.test.tsx, src/components/accessibility/screen_reader_only/screen_reader_only.test.tsx, src/components/accordion/accordion.test.tsx, src/components/avatar/__snapshots__/avatar.test.tsx.snap, src/components/avatar/avatar.test.tsx, src/components/badge/__snapshots__/badge.test.tsx.snap, src/components/badge/badge.test.tsx, src/components/badge/badge_group/__snapshots__/badge_group.test.tsx.snap, src/components/badge/badge_group/badge_group.test.tsx, src/components/badge/beta_badge/beta_badge.test.tsx, src/components/badge/notification_badge/badge_notification.test.tsx, src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap, src/components/breadcrumbs/breadcrumbs.test.tsx, src/components/card/__snapshots__/card.test.tsx.snap, src/components/card/card.test.tsx, src/components/card/card_select/card_select.test.tsx, src/components/card/checkable_card/__snapshots__/checkable_card.test.tsx.snap, src/components/card/checkable_card/checkable_card.test.tsx, src/services/emotion/clone_element.test.tsx
This PR converts `EuiCard`, `EuiBreadcrumbs`, `EuiBadge`, `EuiAvatar`, `EuiAccordion`, `EuiScreenReaderLive`, `EuiScreenReaderOnly` and `cloneElementWithCss` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert remaining component unit tests using enzyme render to RTL

src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/__snapshots__/table_footer.test.tsx.snap, src/components/table/__snapshots__/table_footer_cell.test.tsx.snap, src/components/table/__snapshots__/table_header_cell.test.tsx.snap, src/components/table/__snapshots__/table_header_cell_checkbox.test.tsx.snap, src/components/table/__snapshots__/table_row_cell.test.tsx.snap, src/components/table/mobile/table_header_mobile.test.tsx, src/components/table/mobile/table_sort_mobile.test.tsx, src/components/table/mobile/table_sort_mobile_item.test.tsx, src/components/table/table.test.tsx, src/components/table/table_footer.test.tsx, src/components/table/table_footer_cell.test.tsx, src/components/table/table_header.test.tsx, src/components/table/table_header_button.test.tsx, src/components/table/table_header_cell.test.tsx, src/components/table/table_header_cell_checkbox.test.tsx, src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap, src/components/table/table_pagination/table_pagination.test.tsx, src/components/table/table_row.test.tsx, src/components/table/table_row_cell.test.tsx, src/components/table/table_row_cell_checkbox.test.tsx
This PR converts `EuiTable` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert EuiTable unit tests using enzyme render to RTL

src/components/progress/__snapshots__/progress.test.tsx.snap, src/components/progress/progress.test.tsx, src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap, src/components/resizable_container/resizable_container.test.tsx, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/selectable.test.tsx, src/components/selectable/selectable_message/selectable_message.test.tsx, src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap, src/components/selectable/selectable_templates/selectable_template_sitewide.test.tsx, src/components/side_nav/__snapshots__/side_nav.test.tsx.snap, src/components/side_nav/__snapshots__/side_nav_item.test.tsx.snap, src/components/side_nav/side_nav.test.tsx, src/components/side_nav/side_nav_item.test.tsx, src/components/stat/__snapshots__/stat.test.tsx.snap, src/components/stat/stat.test.tsx, src/components/steps/step.test.tsx, src/components/steps/step_horizontal.test.tsx, src/components/steps/step_number.test.tsx, src/components/steps/steps.test.tsx, src/components/steps/steps_horizontal.test.tsx, src/components/steps/sub_steps.test.tsx, src/components/suggest/__snapshots__/suggest.test.tsx.snap, src/components/suggest/suggest.test.tsx, src/components/suggest/suggest_item.test.tsx, src/components/tabs/tab.test.tsx, src/components/tabs/tabbed_content/tabbed_content.test.tsx, src/components/tabs/tabs.test.tsx, src/components/token/__snapshots__/token.test.tsx.snap, src/components/token/token.test.tsx
This PR converts `EuiToken`, `EuiTabs`, `EuiSuggest`, `EuiSteps`, `EuiStat`, `EuiSideNav`, `EuiSelectable`, `EuiResizeableContainer` and `EuiProgress` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert more component unit tests using enzyme render to RTL

src-docs/webpack.config.js, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_link.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/index.ts, src/components/collapsible_nav_beta/index.ts, src/components/index.ts
This PR sets up a new `EuiCollapsibleNavItem` component that follows the new nav redesign and UX outlined in https://github.com/elastic/eui/issues/6759.
This PR, as noted by the [Beta] label in the title, is not a complete feature in and of itself. However, I'm choosing to ship it to main for the following reasonns reasons:
- Creating new components/folders does not interfere or cause interruptions to consumers using the old components, and is relatively risk free
- Releasing it (unannounced/undocumented) allows @tsullivan to incrementally use redesign progress in his Kibana feature work and battle-test our component using production data, leading to issues (hopefully) getting caught faster
- `gh pr checkout 6904`
- `yarn storybook` (may need to `yarn` beforehand if you haven't run EUI …
=> [Beta] Add `EuiCollapsibleNavItem` component

src/global_styling/variables/states.ts, src/themes/amsterdam/global_styling/variables/_states.ts, upcoming_changelogs/6984.md
- Adds `focus.transparency` (mostly just needed for `focus.backgroundColor`) and `focus.backgroundColor`
- ⚠️  Note: an `euiFocusBackground` Sass mixin exists ([link](https://github.com/elastic/eui/blob/329eb41a8c36ba76be780fc6a45d375cf7184033/src/themes/amsterdam/global_styling/mixins/_states.scss#L39-L41)). This mixin allows customizing the background color used (defaulting to `primary`). I **did not** convert this mixin to a CSS-in-JS util, and opted to go this route (theme tokens) instead. I did this for several reasons:
- Kibana has multiple usages of basic `$euiFocusBackgroundColor` usages (which uses the default `primary` color) and has 0 usages of custom focus background colors. Based on this, consumers will want an easier-to-grab theme token vs. a util they have to specifically …
=> [Emotion] Add new `focus.transparency` and `focus.backgroundColor` theme tokens

src/components/filter_group/filter_group.styles.ts, upcoming_changelogs/6983.md
🤦 I messed up the syntax for this during https://github.com/elastic/eui/pull/6982, and now `EuiFilterGroup` is full width at all breakpoints when it should only be full-width at the xs->s breakpoint.
**Broken on prod:**
**After fix:**
**Broken on prod:**
**After fix:**
=> [EuiFilterGroup] Fix responsive styles

src/components/button/__snapshots__/button.test.tsx.snap, src/components/button/button.test.tsx, src/components/code/__snapshots__/code_block.test.tsx.snap, src/components/code/code.test.tsx, src/components/code/code_block.test.tsx, src/components/context_menu/__snapshots__/context_menu.test.tsx.snap, src/components/context_menu/context_menu.test.tsx, src/components/context_menu/context_menu_item.test.tsx, src/components/context_menu/context_menu_panel.test.tsx, src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap, src/components/date_picker/auto_refresh/auto_refresh.test.tsx, src/components/date_picker/date_picker_range.test.tsx, src/components/description_list/description_list.test.tsx, src/components/description_list/description_list_description.test.tsx, src/components/description_list/description_list_title.test.tsx, src/components/empty_prompt/__snapshots__/empty_prompt.test.tsx.snap, src/components/empty_prompt/empty_prompt.test.tsx, src/components/expression/__snapshots__/expression.test.tsx.snap, src/components/expression/expression.test.tsx, src/components/flex/flex_grid.test.tsx, src/components/flex/flex_group.test.tsx, src/components/flex/flex_item.test.tsx
This PR converts `EuiFlex`, `EuiExpression`, `EuiEmptyPrompt`, `EuiDescriptionList`, `EuiDatePicker`, `EuiContextMenu`, `EuiCode`, `EuiButton` and `EuiAspectRation` unit tests using Enzyme's render() function to RTL render() counterpart to reduce our tech debt.
=> test: convert further component unit tests using enzyme render to RTL

scripts/babel/proptypes-from-ts-props/index.js, src-docs/src/views/datagrid/advanced/custom_renderer.tsx, src-docs/src/views/datagrid/advanced/ref.tsx, src-docs/src/views/datagrid/styling/row_height_auto.tsx, src-docs/src/views/datagrid/styling/row_height_fixed.tsx, src-docs/src/views/datagrid/styling/row_line_height.tsx, src-docs/src/views/datagrid/toolbar/additional_controls.tsx, src/components/datagrid/body/data_grid_body_custom.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/body/data_grid_row_manager.ts, src/components/datagrid/body/header/data_grid_header_cell.tsx, src/components/datagrid/controls/data_grid_toolbar.tsx, src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/controls/display_selector.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/data_grid_pagination.tsx, src/components/datagrid/utils/in_memory.tsx, src/components/datagrid/utils/ref.ts
`@types/react` for React 18 introduced a few breaking changes, primarily in the automatic type inference area. Specifically, type inference for `useCallback` when passing to typed props is broken in TS version we're using (it should be fixed in v5.2 by [this PR](https://github.com/microsoft/TypeScript/pull/49707) and possibly more), but we're not there yet and the upgrade isn't straightforward.
React 17 apps using EUI won't be affected by these changes and React 18 apps will work as before depending on the TypeScript version they're running on.
There are also a few small fixes to ensure safe typing in other EuiDataGrid places.
Please pay attention to the `JSXElementConstructor` changes as it's the one that may cause the most trouble. I made sure the old and new types resolve to almost the …
=> feature: EuiDataGrid type improvements to support React 18

cypress/support/component.tsx
Bafflingly enough, this doesn't appear to occur on Jenkins CI but does occur/fail when running `yarn test-cypress` on some local machines.
There are now apparently two ResizeObserver-related error messages that can crop up in Cypress:
- (old) `> ResizeObserver loop limit exceeded`
- (new) `> ResizeObserver loop completed with undelivered notifications.`
Honestly we should just ignore all resize observer shenanigans as they don't appear to affect actual production behavior.
N/A, internal/dev only
=> [Cypress] Ignore even more `ResizeObserver loop` shenanigans

src-docs/src/views/filter_group/filter_group.js, src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box.test.tsx, src/components/combo_box/combo_box.tsx, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx, src/components/filter_group/__snapshots__/filter_select_item.test.tsx.snap, src/components/filter_group/_filter_select_item.scss, src/components/filter_group/_index.scss, src/components/filter_group/filter_select_item.styles.ts, src/components/filter_group/filter_select_item.test.tsx, src/components/filter_group/filter_select_item.tsx, src/components/index.scss, upcoming_changelogs/6982.md
closes https://github.com/elastic/eui/issues/6398
This PR:
1. Converts `EuiFilterSelectItem` to Emotion
- This involves removing several CSS classNames that not being used directly within the EUI component, but instead as separate CSS hooks: `.euiFilterSelect__items`, `.euiFilterSelect__note`, and `.euiFilterSelect__noteContent`
2.  Improves the keyboard "focus" state of disabled items - now uses a clearly disabled background color instead of the previous primary background color
3. Marks `EuiFilterSelectItem` for deprecation - once `EuiComboBox` switches to dogfooding `EuiSelectable`, we should move away from it entirely and request that Kibana usages do so as well
Note that I opted not to create stories for this component since we'll eventually be removing it. The easiest way to QA it …
=> [EuiFilterSelectItem] Convert to Emotion + mark as deprecated

src-docs/src/views/color_palette/color_palette_quantitative.js, src-docs/src/views/color_picker/color_palette_display.js, src-docs/src/views/elastic_charts/theming.js, src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js, src/services/color/eui_palettes.ts, src/services/color/index.ts, src/services/index.ts, upcoming_changelogs/6992.md
closes #6901 
It looks like we made a whoopsie a while ago and misspelled `complementary` when naming our color palettes. This PR:
I've added `euiPaletteComplimentary` to the Deprecations schedule. Kibana is [only showing two usages](https://github.com/search?q=repo%3Aelastic%2Fkibana%20euiPaletteComplimentary&type=code) at this moment, so this shouldn't be difficult to update during an upgrade.
References to the old color palette name have been updated in the docs. Each example should have no visual changes between staging and prod. The new name should also be displayed (`euiPaletteComplementary`).
=> [Color Palette] Deprecate `euiPaletteComplimentary`; Add `euiPaletteComplementary`

catalog-info.yaml
This job adds a `cancel_intermediate_jobs: true` boolean to `catalog-info.yml` to stop old jobs on PR update. I added the command to the combined PR test and deploy docs, as well as individual jobs so we get good coverage. 
I discussed this with @markjhoy as he's working on a same PR for Enterprise Search: https://github.com/elastic/ent-search/pull/7653
I added the `cancel_intermediate_jobs` boolean to all three jobs. Catalog changes have to be in main to get picked up by the Terraform task.
I'll rapidly test this by updating the PR, **after the fix is merged into main** by changing things rapidly and changing them back to see if it cancels jobs correctly. Will make the PR history a little dirtier, but eh, squash and merge.
=> [INFRA] Add command to stop running Buildkite jobs

.buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml
Buildkite needs more information to ensure we are polling the correct branch and correct commit hash to run PR jobs.
I went back to the trigger step docs in Buildkite and came up with the **build > branch** variable:
```
branch
The branch for the build.
Default: The triggered pipeline's default branch.
Example: "production"
```
I added this branch env variable to the commit hash we're already asking for. In a previous experiment I added the branch without the commit hash and buildkite failed the job because it didn't have the ref to the forked repo. It takes both variables to accurately check out the branch and commit to be run against, I'm now learning.
QA will be done manually using Buildkite logs to review env variables and build output.
**Findings**
* This PR has the correct branch as …
=> [INFRA] Configuring Buildkite `branch` plus commit hash to run jobs accurately.

src/components/context_menu/context_menu_panel.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/flyout/flyout.spec.tsx, src/components/popover/wrapping_popover.tsx, src/components/portal/portal.tsx, src/components/tour/tour_step.tsx
Fix StrictMode and async rendering issues in `EuiPortal`, `EuiWrappingPopover` and `EuiTourStep`, and fix more flaky cypress tests found running on 6x CPU slowdown multiplier.
Ensure unit tests and cypress tests are passing.
=> [React 18] Add full <StrictMode> support

.buildkite/pipelines/pipeline_pull_request_deploy_docs.yml, .buildkite/pipelines/pipeline_pull_request_test.yml
We don't want to run our pull request jobs on merge to `main` as they've just run on the PR during the review cycle. This PR adds a negation `if` statement to the jobs' YML files.
Testing will be confimed in the Buildkite UI. I'll be checking the `main` branch for two jobs, to ensure there's not new runs before or after the PR is merged.
* eui-pull-request-test
* eui-pull-request-deploy-docs
**UPDATE Monday 31 July**
Started a fresh run of this job. Looked through the Buildkite UI `main` branch runner for both jobs. Neither job started on `main` branch, only the feature branch. This change appears to be working as I wanted.
=> [INFRA] Adding logic to prevent Buildkite triggered jobs on merge to `main`.

package.json, src/components/code/code_block_copy.spec.tsx, yarn.lock
Bumping Cypress to version `12.17.0` (current release)
* Bumping Cypress to version 12.17.0.
* Changing invoke to then to resolve promise and not throw an error.
* Closes #6917 
Changed one test's `invoke()` method to resolve a promise using `then()` per the Cypress changelog:
> The [.invoke()](https://docs.cypress.io/api/commands/invoke) command now throws an error if the invoked function returns a promise. If you wish to call a method that returns a promise and wait for it to resolve, use [.then()](https://docs.cypress.io/api/commands/then) instead of .invoke(). Addressed in [#24417](https://github.com/cypress-io/cypress/pull/24417)
**Ran Cypress tests locally:**
* `yarn test-cypress`
* `yarn test-cypress-a11y`
* Tested a handful of previous failing tests in the Cypress browser runner
* …
=> [CHORE] Upgrading Cypress to version 12.

src/components/date_picker/super_date_picker/super_date_picker.a11y.tsx, src/components/filter_group/filter_group.a11y.tsx
Two tests were failing because of changes to an `aria-label` and a containing CSS class. I updated these and re-ran the tests locally.
This PR closes #7024.
Ran tests locally several times in CI (headless) mode and using the Cypress UI. All tests passing again.
---
=> [A11y] Fixed two failing Cypress accessibility tests

src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/collapsible_nav_beta/collapsible_nav_button/__snapshots__/collapsible_nav_button.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx, src/components/collapsible_nav_beta/collapsible_nav_button/index.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, src/components/collapsible_nav_beta/index.ts, src/components/flyout/flyout.tsx, src/components/header/header.styles.ts
- ⚠️ This PR is part **1 of 2** of completing EuiCollapsibleNavBeta's responsive/docked behavior.
- The part that is missing is the part where `EuiCollapsibleNavItem` needs to conditionally render a icon that toggles a popover, but only for larger desktop screens when in the "collapsed" state.
- I opted to split out this work into separate PRs, as this one was already getting pretty long in the tooth in terms of LOC/review time.
- Parent issue: https://github.com/elastic/eui/issues/6759
- Previous PRs: https://github.com/elastic/eui/pull/6904
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7027/commits).
As noted above, this is **expected to be broken** and will be implemented in the next PR. However, the flyout width should be correct.
Smallest …
=> [EuiCollapsibleNavBeta] Build out component state and responsive behavior

src-docs/src/views/breadcrumbs/breadcrumbs_example.js, src-docs/src/views/breadcrumbs/popover_content.tsx, src/components/breadcrumbs/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap, src/components/breadcrumbs/breadcrumb.test.tsx, src/components/breadcrumbs/breadcrumb.tsx, upcoming_changelogs/7031.md
closes https://github.com/elastic/eui/issues/7015
Per the above issue, Kibana's new serverless design needs the ability to allow breadcrumbs to toggle popovers that can act as more complex navigation patterns:
This PR also updates the collapsed `...` breadcrumb to dogfood the new popover API and (hopefully) increases a11y UX for it as well. As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7031/commits) as there's a few incidental cleanups.
- Go to https://eui.elastic.co/pr_7031/#/navigation/breadcrumbs#popover-content
- Regression testing
- Mobile collapsed behavior isn't _super_ great because you end up in a popover-within-a-popover situation, but I'm not super sure there's any way around this, and at least it works?
~- [ ] Checked for **breaking …
=> [EuiBreadcrumbs] Add `popoverContent` and `popoverProps`

src-docs/src/views/steps/status.tsx, src/components/steps/step.styles.ts, src/components/steps/step_horizontal.styles.ts, src/components/steps/step_number.styles.ts, upcoming_changelogs/7032.md
Included in #6932
Updated the `disabled` title color for `EuiSteps` and `EuiStepsHorizontal` to meet the 4:5.1 contrast ratio.
**Vertical Steps**
Please note: There's no background color change!
---
**Horizontal Steps**
1. Check the disabled state for `EuiSteps` and `EuiStepsHorizontal`. When using your browsers developer tools, you should find that the title and step number meet the and exceed the 4:5.1 contrast level
=> [EuiSteps] Create High Contrast Color for Disabled Step Titles

scripts/deploy/deploy_docs
Based on [EUI's release wiki docs](https://github.com/elastic/eui/blob/main/wiki/eui-team-processes/releasing-versions.md#backport-process), backports and prerelease tags should, _theoretically_, only exist on branches that aren't main. Tweaking our git command to only grab the latest tag from the main branch should prevent us from accidentally deploying tags we don't want to `eui.elastic.co`.
Caveat: this isn't completely bulletproof and we probably still want some sort of way to trigger a manual deploy to `eui.elastic.co` in the event someone accidentally tags something they shouldn't, but that's pretty unlikely for EUI's current workflow, so this gets us most of the way there for now.
N/A, CI only
=> [Buildkite] Avoid deploying backport and prerelease tags

package.json, yarn.lock
This PR resolves Snyk dependency upgrade recommendation from #6811 by upgrading `mdast-util-to-hast` to version 10.2.0.
- https://github.com/syntax-tree/mdast-util-to-hast/commit/c3397021866c90bfbefb3dc3c5668dded1613f13 Add mdast code.meta to hast as code.data.meta
- https://github.com/syntax-tree/mdast-util-to-hast/commit/703a652d75f57c3ab292c0df9685dcd56338cfe8 Fix exception on node.data set to undefined
- https://github.com/syntax-tree/mdast-util-to-hast/commit/a4979905ac423b2581d4d2aa0b8fb410f18fa573 Add passThrough option to keep custom nodes
- https://github.com/syntax-tree/mdast-util-to-hast/commit/197247c95c98cf864733f110b7995dbf9c11cfa9 Fix support for hName on non-element
=> build: upgrade mdast-util-to-hast to 10.2.0

.ci/jobs/elastic+eui+pull-request.yml, catalog-info.yaml
This PR removes the automatic trigger for Jenkins' combined pull request test and deploy PR docs job. The job will still be able to be triggered from the Jenkins UI for now, but will be phased out in favor of the automatic Buildkite run.
This PR also updates the `catalog-info.yml` file to enable `build` permissions for Elasticians.
QA will be done manually:
=> [INFRA] Updating Jenkins and BK permissions for PR jobs.

src-docs/src/views/skeleton/skeleton_example.js
closes https://github.com/elastic/eui/issues/7021
Our `EuiSkeleton` components have been publicly available for ~6 months now, and should no longer be considered "new".
N/A, docs only
=> [Docs] Remove `isNew` flag from `EuiSkeleton` components

src-docs/src/views/steps/status.tsx, src/components/steps/step_number.styles.ts, upcoming_changelogs/7048.md
Included in #6932 
This PR adds a `2px` outer halo to steps within `EuiSteps` and `EuiStepsHorizontal` that have the `current` status. This will create a better user experience by providing users with a more clear indication of the step they are currently on. 
=> [EuiSteps] Add outer halo to `current` step

src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx
Per Marcialis's comment in https://github.com/elastic/kibana/issues/161889#issuecomment-1644172690, the new collapsible nav should sit below any flyout/modal/general overlay masks. This Storybook adds a quick way to visually QA that Kibana behavior and confirm it's working as expected.
- `gh pr checkout 7051`
- `yarn storybook`
- Go to http://localhost:6006/?path=/story/euicollapsiblenavbeta--flyout-in-fixed-headers
N/A, internal dev-only
=> [EuiCollapsibleNavBeta] Add storybook QA test for ensuring flyouts sit above the nav

src-docs/src/views/date_picker/range.tsx, src/components/date_picker/__snapshots__/date_picker_range.test.tsx.snap, src/components/date_picker/date_picker_range.test.tsx, src/components/date_picker/date_picker_range.tsx, upcoming_changelogs/7058.md
This PR fixes `EuiSuperDatePicker`'s compressed display not working correctly, by adding `EuiDatePickerRange` support for `compressed` display.
This behavior was regressed in #6705 (when we updated `EuiSuperDatePicker` to dogfood `EuiDatePickerRange`).
> ⚠️  This fix will need to be backported to Kibana 8.10 post-FF.
- Go to https://eui.elastic.co/pr_7058/#/templates/super-date-picker#sizing
- Toggle the `compressed` switch
- Go to https://eui.elastic.co/pr_7058/#/forms/date-picker#date-picker-range
- Click `Display toggles` and then toggle the `compressed` switch
- ~[ ] Updated the **[Figma](https://www.figma.com/community/file/964536385682658129)** library counterpart~
-  Neither the super date picker nor date picker files have a `compressed` example, although one should probably be …
=> [EuiDatePickerRange] Add support for `compressed` display

src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/flyout/flyout_body.test.tsx, src/components/flyout/flyout_body.tsx, upcoming_changelogs/7061.md
This PR is part of #7041 (several a11y improvements/enhancements for the new `EuiCollapsibleNavBeta` work).
This PR _only_ addresses the extra tab stop caused by `EuiFlyoutBody` - it does not address any issues inherent to push flyouts (https://github.com/elastic/eui/issues/6576). I'll be looking into that as a separate PR.
- `gh pr checkout 7061`
- `yarn storybook`
- Go to http://localhost:6006/?path=/story/euicollapsiblenavbeta--kibana-example
- Click the collapse nav button and press tab - there should only be 1 tab stop (instead of 2) between the toggle button and the flyout content
- Run axe devtools, there should be 0 issues caught
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting)**~ - Opting for just props documentation, I …
=> [EuiFlyoutBody] Add `scrollableTabIndex` prop

src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, upcoming_changelogs/7064.md
closes https://github.com/elastic/eui/issues/6980, part of https://github.com/elastic/eui/issues/7041
`EuiAccordion`s children cannot be hidden due to accordions needing to detect their height. This means that interactive/tabbable children still remain the keyboard tab order when accordions are closed when they should not be. Example production behavior: https://codesandbox.io/s/withered-moon-hc3ft6?file=/demo.js (notice several tabs are required to reach the 2nd visible button).
The solution to this is that on close, `EuiAccordion` needs to evaluate its tabbable children and manually set them to `tabIndex={-1}` to remove them from tab order. On open, their original tabindex behavior should be restored.
There's some misc syntax cleanup in this PR, so as always, follow along by commit!
An …
=> [EuiAccordion] Improve keyboard accessibility of tabbable children

wiki/eui-team-processes/upgrading-kibana.md
Updates our wiki docs with more explicit instructions around EUI's role in managing breaking changes and deprecations for Kibana.
N/A, wiki docs only
=> [wiki] Update Kibana upgrade docs

src-docs/src/views/flyout/flyout_example.js, src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/flyout/flyout.test.tsx, src/components/flyout/flyout.tsx, upcoming_changelogs/7065.md
This is my last PR for https://github.com/elastic/eui/issues/7041.
This relates to the discussion brought up in https://github.com/elastic/eui/issues/6576, but **does not resolve it** per the issue. It instead takes a completely different direction of specifically marking push flyouts **not** as dialogs, and removing all dialog-related props (primarily `role` and `tabIndex`).
I've opted to go with this approach because of the direction that the new beta collapsible nav has gone in, which will eventually be present on every page of Kibana.
- `gh pr checkout 7065`
- `yarn storybook`
- Go to http://localhost:6006/?path=/story/euicollapsiblenavbeta--kibana-example (ensure the nav is on a wide enough screen that it's pushing the page as opposed to being an overlay)
- Click the toggle button
- …
=> [EuiFlyout] Resolve disparity between push flyouts and overlay flyouts

src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_button.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_popover.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx, src/components/tool_tip/tool_tip.test.tsx, src/components/tool_tip/tool_tip.tsx, src/components/tool_tip/tool_tip_anchor.tsx, upcoming_changelogs/7055.md
- Part of https://github.com/elastic/eui/issues/7041.
- ⚠️ This PR does not resolve **all** a11y issues with EuiCollapsibleNavBeta, just _one_ of them (see linked issue for full list).
This PR:
1. Makes the typing of nav item `title`s stricter - they now **must** be strings and not ReactNodes (in order to support `aria-label`/`title` type attributes)
2. Sets an `aria-label` on all collapsed/docked button icon nav items (example below)
which resolves the many warnings in tests as well as devtools:
3. ~However, adding an `aria-label` to button icons with a tooltip wrapped around them leads to duplicated content, because the `aria-label` and `aria-describedby` contain the same exact content. The solution is to modify `EuiToolTip` to allow configuring disabling the `aria-describedby` logic if …
=> [EuiCollapsibleNavBeta] Improve collapsed button icon screen reader UX

src/components/page/page_sidebar/page_sidebar.tsx, src/components/page_template/page_template.tsx
closes https://github.com/elastic/eui/issues/7016
This PR fixes side navigation scroll and page content top offset updating after the page is already rendered.
Due to the implementation details of checking if there are `EuiHeader` components with fixed position rendered based on data attributes, there's still a single top offset update when the docs page is first loaded. However, the content doesn't jump whenever users navigate through pages anymore. I need to think of a clean fix for that, possibly moving away from using data attributes to store information like that. I'll fix it in a separate PR.
=> fix: docs layout jumping

src-docs/src/views/popover/input_popover.tsx, src-docs/src/views/popover/popover_example.js, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.tsx, src/components/popover/input_popover.spec.tsx, src/components/popover/input_popover.tsx, src/components/popover/popover.tsx, upcoming_changelogs/7071.md
See this conversation https://github.com/elastic/kibana/pull/162651#discussion_r1283757785 with @Heenawter and @andreadelrio about some of the new Discover work being done to standardize the visual behavior of input popovers.
Prior to this prop, `EuiInputPopover` widths were entirely tied to the width of the input element. Now, consumers can specify a minimum width, allowing wider content to display at desired widths if necessary, e.g.:
This PR also fixes `EuiPopver` to allow `EuiInputPopover` to respect different side anchors and to update the popover position if the input resizes.
- https://eui.elastic.co/pr_7071_buildkite/#/layout/popover#popover-attached-to-input-element …
=> [EuiInputPopover] Add `panelMinWidth` prop

src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/range/dual_range.test.tsx, src/components/form/range/dual_range.tsx, src/components/form/range/range.test.tsx, src/components/form/range/range.tsx, src/components/form/range/types.ts, upcoming_changelogs/7082.md
Follow-up to https://github.com/elastic/eui/pull/7071#pullrequestreview-1577180668
> [...] would it be possible to make this prop available for the `EuiDualRange` component for when `showInput="inputWithPopover"`? We use this for our range slider control and, while **less** important than with the options list control, it would still be valuable to make the popover extend past the input on our smaller sizes:
> 
> ![image](https://github.com/elastic/eui/assets/8698078/0247b8d5-de28-4fad-85f5-3b84a038a883)
N/A, I didn't add any QA-able documentation for this, since it's a (relatively) straightforward props spread. The added tests should give us sufficient confidence that the spread behavior is working as expected.
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/c …
=> [EuiRange][EuiDualRange] Add new `inputPopoverProps` prop

src/components/resizable_container/__snapshots__/resizable_button.test.tsx.snap, src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap, src/components/resizable_container/_index.scss, src/components/resizable_container/_resizable_button.scss, src/components/resizable_container/_variables.scss, src/components/resizable_container/resizable_button.styles.ts, src/components/resizable_container/resizable_button.test.tsx, src/components/resizable_container/resizable_button.tsx, upcoming_changelogs/7081.md
https://github.com/elastic/eui/issues/6408
- This PR converts `EuiResizableButton` to Emotion
- This PR **does not** convert `EuiResizableCollapseButton`. That conversion + this one was getting fairly gnarly, so I opted to leave it separate to make review easier.
- This PR performs several incidental cleanup items on `EuiResizableButton`, including adding unit tests that were previously missing, and gets component code coverage up to 100%
- This PR performs a large CSS refactor (https://github.com/elastic/eui/pull/7081/commits/78e57b8164847170c9cc78e4a6b2d97a6f8afdee) that converts from absolute positioning & transform CSS to using flex CSS instead. This has the major benefit of: 
1. fixing an existing Safari visual bug on production (go to …
=> [Emotion] Convert `EuiResizableButton`

src-docs/src/views/resizable_container/_props.tsx, src-docs/src/views/resizable_container/resizable_button.tsx, src-docs/src/views/resizable_container/resizable_container_example.js, src-docs/src/views/resizable_container/resizable_panel_collapsible_options.tsx, src/components/resizable_container/__snapshots__/resizable_button.test.tsx.snap, src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap, src/components/resizable_container/index.ts, src/components/resizable_container/resizable_button.stories.tsx, src/components/resizable_container/resizable_button.styles.ts, src/components/resizable_container/resizable_button.test.tsx, src/components/resizable_container/resizable_button.tsx, upcoming_changelogs/7087.md
- closes #6100
Exports a generic `EuiResizableButton` with no context or references to the registry/resizers from `EuiResizableContainer`, and sets up a new internal `EuiResizableButtonControlled` component for the container parent to use
- closes #5787
Creates a new `alignIndicator` prop that determines the position/alignment of the resize indicator
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7087/commits).
- Go to https://eui.elastic.co/pr_7087/#/layout/resizable-container#custom-resizable-button
- `gh pr checkout 7087`
- `yarn compile-scss && yarn storybook`
- Note that the `yarn compile-scss` step is important/required ever since we changed Storybook to import our distributed CSS, the old Sass will linger/override Emotion otherwise
- Go to …
=> [EuiResizableButton] Export as generic component; Add `alignIndicator` prop

src/components/steps/step.styles.ts, wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
This PR is a follow-up to https://github.com/elastic/eui/pull/7091#discussion_r1296573174 which was the first PR/component to use getters in Emotion. I've decided to document the approach and update our `EuiStep`s styles to adopt it as well.
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/changelogs.md)** entry exists and is marked appropriately~ - Skipping as this should not affect consumers or end-users
=> [Emotion] Document usage of getters in Emotion style objects

src/components/page_template/page_template.tsx, src/services/accessibility/html_id_generator.test.tsx, src/services/accessibility/html_id_generator.ts, upcoming_changelogs/7095.md
This PR resolves #7078 by updating `useGeneratedHtmlId` utility function to use [`React.useId`](https://react.dev/reference/react/useId) when it's available (which means when running React 18).
It's the first step in making `useGeneratedHtmlId` and its usages SSR-compatible. We must do #7094 to make `useGeneratedHtmlId` SSR-safe across all supported React versions.
* Make sure all tests are passing
* Verify that `<EuiSwitch>` and `<EuiDataGrid>` generated DOM `id` attributes reference the same objects as before. The id values will be different (instead of UUIDs there's gonna be strings like `:r1:` generated by `React.useId`)
=> feat: update useGeneratedHtmlId to use React.useId when available

.github/workflows/_fragment.yml, catalog-info.yaml
This PR fixes the issue where Buildkite runs the combined test and deploy docs job twice. The root cause was determined to be the job kicking off with an API and webhook call. 
This PR is modeled after a Fleet Server PR the Buildkite CI team sent me to [avoid duplicate builds](https://github.com/elastic/fleet-server/pull/2573/files?w=1).
This PR closes #7069.
QA will be done manually after the PR is merged into `main`. I will open a feature branch on the EUI repo (not my fork) to ensure it doesn't run duplicate jobs, and a community PR to ensure it also runs correctly.
=> [BUG] Update `catalog-info.yml` to avoid double job starts in Buildkite

wiki/eui-team-processes/releasing-versions.md
PR removes the Jenkins release docs step and adds new information for Buildkite. PR closes #7110.
=> [DOCS] Updating wiki doc for Buildkite release docs job

src/services/theme/__snapshots__/provider.test.tsx.snap, src/services/theme/context.ts, src/services/theme/hooks.test.tsx, src/services/theme/hooks.tsx, src/services/theme/index.ts, src/services/theme/provider.stories.tsx, src/services/theme/provider.test.tsx, src/services/theme/provider.tsx, src/services/theme/types.ts
> ⚠️ NOTE: This PR is merging into a feature branch, as it doesn't make much sense on its own without another component utilizing its behavior.
This PR adds the architecture for CSS variables to be set by EUI components. This is part of the work needed for #7025, in particular:
> Some components have style-related **variables** that may need to be reused by consumers, or even by other components within EUI. Examples of these are [`euiFormVariables`](https://github.com/elastic/eui/blob/d39c0e988409f90f62af57174590044664b2bfce/src/components/form/form.styles.ts#L19) and [`euiHeaderVariables`](https://github.com/elastic/eui/blob/3e950bf7605c6fea31f75cd7f2aedfe233d5607e/src/components/header/header.styles.ts#L20).
> Instead of moving these style variables outside our `.styles.ts` files and …
=> [EuiThemeProvider] Add context & state required for theme CSS variables architecture

src-docs/src/views/theme/typography/_typography_js.tsx, src/components/markdown_editor/markdown_format.styles.ts, src/components/text/text.styles.ts, src/global_styling/functions/__snapshots__/typography.test.tsx.snap, src/global_styling/functions/typography.test.tsx, src/global_styling/functions/typography.ts, src/global_styling/mixins/_typography.test.ts, src/global_styling/variables/typography.ts, src/themes/amsterdam/global_styling/variables/_typography.ts, upcoming_changelogs/7133.md
closes https://github.com/elastic/eui/issues/7124
Currently, all Emotion component font sizes use `rem` sizing and this isn't something that we allow configuration for (e.g. to `px` or `em`) values. Adding a new `font.defaultUnits` token to our EUI theme will enable consumers to easily and quickly customize our component font size CSS output in one place.
> ⚠️ Note that there are a few components that do need to set a custom measurement override that does not use this new token - primarily `<EuiText size="relative">` is the (current) one instance of this in EUI where `em` is enforced.
- Go to http://localhost:8030/#/theming/typography/values
=> [Emotion][Theming] Add new consumer-configurable `font.defaultUnits` token

src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx
Consumers will need this callback to store current collapsed state (e.g. in local storage, for feeding back to `initialIsCollapsed`).
- `gh pr checkout 7134 && yarn storybook`
- Go to http://localhost:6006/?path=/story/euicollapsiblenavbeta--collapsed-state-in-local-storage
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/changelogs.md)** entry exists and is marked appropriately~ - N/A, beta component
=> [EuiCollapsibleNavBeta] Add `onCollapseToggle` callback

src-docs/src/views/icon/apps.js, src-docs/src/views/icon/icons.js, src-docs/src/views/icon/logos.js, src-docs/src/views/icon/ml.js, src-docs/src/views/icon/tokens.tsx
Reorders the icons grid view to go left to right (rows) rather than vertically down (columns).  It can be difficult to find icons currently.
https://github.com/elastic/eui/assets/3756330/15c411b6-0611-4b82-bf6b-f47dd2ad3088
=> Reorders icon grid to go left to right instead of vertically.

src-docs/src/views/drag_and_drop/drag_and_drop_example.js, src-docs/src/views/drag_and_drop/in_popover.tsx
Adds a section to the EuiDraggable docs page to mention the special use case in popovers and the necessary additional prop.
=> [docs] Document requirement for using drag & drop components in popovers

src-docs/src/views/datagrid/_snippets.tsx, src-docs/src/views/description_list/column_widths.tsx, src-docs/src/views/description_list/description_list_example.js, src/components/datagrid/controls/__snapshots__/keyboard_shortcuts.test.tsx.snap, src/components/datagrid/controls/_data_grid_keyboard_shortcuts.scss, src/components/datagrid/controls/keyboard_shortcuts.tsx, src/components/description_list/__snapshots__/description_list.test.tsx.snap, src/components/description_list/description_list.test.tsx, src/components/description_list/description_list.tsx, src/components/description_list/description_list_types.ts, upcoming_changelogs/7146.md
This PR adds a new prop to `EuiDescriptionList` to smooth over changes made in #7062 (primarily the change that converted column data grids to using `display: grid`).
Unfortunately, many Kibana teams and EUI itself were setting custom column widths via CSS `flex-basis` or `width` overrides, e.g.:
https://github.com/elastic/eui/blob/a4493d9037eae9110c6ab4fbf672abb15c2709d9/src/components/datagrid/controls/_data_grid_keyboard_shortcuts.scss#L8-L16
The new `display: grid` CSS completely ignores both properties, resulting in broken looking UIs:
This new prop adds a quick and easy way for consumers to customize column widths (clearly a frequently desired ability, considering there are 10+ CSS overrides in Kibana alone) without needing to know CSS grid to do so.
> ⚠️ NOTE: This PR should be …
=> [EuiDescriptionList] Add new `columnWidths` prop

src-docs/src/components/guide_page/_guide_page.scss, src-docs/src/components/guide_page/guide_page_chrome.js, src-docs/src/views/header/header_elastic_pattern.tsx, src-docs/src/views/header/header_example.js, src-docs/src/views/header/header_stacked.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/datagrid/_data_grid.scss, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/flyout/flyout.styles.ts, src/components/header/__snapshots__/header.test.tsx.snap, src/components/header/header.stories.tsx, src/components/header/header.styles.ts, src/components/header/header.test.tsx, src/components/header/header.tsx, src/components/overlay_mask/overlay_mask.styles.ts, src/components/overlay_mask/overlay_mask.test.tsx, src/components/page/page_sidebar/page_sidebar.test.tsx, src/components/page/page_sidebar/page_sidebar.tsx, src/components/page_template/__snapshots__/page_template.test.tsx.snap, src/components/page_template/page_template.tsx, src/global_styling/mixins/_header.scss, src/global_styling/mixins/_helpers.ts, upcoming_changelogs/7144.md
This logic allows `EuiHeader` to afford for any number of fixed headers (although it's likely that consumers will not use more than two). The most important aspect of this refactor that other EUI components can access this CSS variable globally with no extra JS logic or rerendering on their end, which removes a significant amount of duplicated `useEffects` from components affected by fixed headers (`EuiPageTemplate`, `EuiSideBar`, and `EuiCollapsibleNavBeta`), and for other components (`EuiFlyout` and `EuiOverlayMask`), it allows them to correctly and dynamically set their top position and height instead of relying on a static Sass mixin to work as expected.
I strongly recommend [reviewing by commit](https://github.com/elastic/eui/pull/7144/commits) as multiple downstream …
=> [EuiHeader] Update to set a new global `--euiFixedHeadersOffset` CSS variable

wiki/contributing-to-eui/developing/writing-styles-with-emotion.md
Adds an example of how components can set CSS variables. Ideally should also clearly explain _when_ to use CSS variables, but I'm not sure this is totally clear and my brain is a little fried right now, so would appreciate feedback.
BTW, I definitely anticipate us tweaking these docs more as we move on to converting form components to and actually have to set up CSS variables for them.
N/A, wiki/docs only
=> [wiki] Add CSS variables docs to our Emotion wiki

src-docs/src/routes.js, src-docs/src/views/text_truncate/ellipsis.tsx, src-docs/src/views/text_truncate/performance.tsx, src-docs/src/views/text_truncate/render_prop.tsx, src-docs/src/views/text_truncate/text_truncate_example.js, src-docs/src/views/text_truncate/truncation.tsx, src-docs/src/views/text_truncate/truncation_offset.tsx, src-docs/src/views/text_truncate/truncation_position.tsx, src/components/index.ts, src/components/text_truncate/__snapshots__/text_truncate.test.tsx.snap, src/components/text_truncate/index.ts, src/components/text_truncate/text_truncate.spec.tsx, src/components/text_truncate/text_truncate.stories.tsx, src/components/text_truncate/text_truncate.styles.ts, src/components/text_truncate/text_truncate.test.tsx, src/components/text_truncate/text_truncate.tsx, src/components/text_truncate/utils.spec.tsx, src/components/text_truncate/utils.test.ts, src/components/text_truncate/utils.ts, upcoming_changelogs/7116.md
This standalone component was created from @dej611's proposal for customizable truncation for `EuiComboBox`. Once this PR merges, we'll update #7028 to dogfood the new component.
⚠️ Unlike most PRs, I **don't** recommend following along by commit, as I went through a ton of back and forth and refactoring with Marco 😅 (see https://github.com/elastic/eui/pull/7028#discussion_r1301242633). I preserved the commit history just in case anyone was interested in seeing it, but since it's a brand new component, it's way easier to just look at the final diff. I promise most 50-60% of it is just tests and documentations 🤞 
Note that highlighting truncated text will see a significant UX improvement with this utility compared to previously (highlighted text that was out of view would not be visible to …
=> Add `EuiTextTruncate` component

src-docs/src/views/datagrid/advanced/custom_toolbar.tsx, src-docs/src/views/datagrid/advanced/datagrid_advanced_example.js, src/components/datagrid/controls/display_selector.tsx, src/components/datagrid/data_grid.tsx, src/components/datagrid/data_grid_types.ts
This PR is introducing a renderCustomToolbar render prop allowing the customize EuiDataGrid
=> [EuiDataGrid] Introduce a renderCustomToolbar render prop

.storybook/main.ts
The upgrade to latest Storybook (#7092) broke Emotion styling and required a webpack override for Emotion to work again. It turns out I didn't check "working" closely enough, because the new setup is actually applying styles twice 💀 
- On main, run `yarn storybook`
- Inspect any story's components and look at the output class styles - each one is repeated twice:
- `gh checkout pr 7155`
- Stop the any running storybook instances and re-start `yarn storybook`
- Re-inspect any story's component and confirm the output class styles are no longer repeated:
N/A, internal dev only
=> [Storybook] Fix emotion styles being applied twice

src-docs/src/views/accordion/accordion_example.js, src-docs/src/views/accordion/accordion_form.js, src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/_accordion_form.scss, src/components/accordion/_index.scss, src/components/accordion/accordion.styles.ts, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/index.scss, src/components/notification/__snapshots__/notification_event.test.tsx.snap, upcoming_changelogs/7154.md
closes #6386
This was a tricky PR to "convert" because none of these Sass-generated classes are actually used in EUI itself; they're classes we generated and told consumers to use directly on EuiAccordion (an architecture we're trying to move away from with Emotion).
Thankfully, there's just 4 or so internal Elastic usages of these classes - 3 in Kibana and 1 in support portal. I based my decisions on what to turn into a generic prop on those usages. Please follow along by commit if possible.
- Go to https://eui.elastic.co/pr_7154/#/layout/accordion#styled-for-forms
- ~[ ] Updated the **[Figma](https://www.figma.com/community/file/964536385682658129)** library counterpart~ - thankfully it looks like this pattern isn't in our Figma library
Skipping the Emotion checklist for this since it's …
=> [Emotion] Remove `.euiAccordionForm` styles

src-docs/src/views/toast/toast_list.js, src/components/toast/global_toast_list.styles.ts, src/components/toast/global_toast_list.test.tsx, src/components/toast/global_toast_list.tsx, upcoming_changelogs/7111.md
Takes a shot at resolving the "Clear All Button" requirement of https://github.com/elastic/eui/issues/6945, referenced by https://github.com/elastic/kibana/issues/162646
- Leverages the pre-existing `EuiGlobalToastListItem` component to keep the clear all button fixed at the bottom of all toasts, having the clear all button on the top pushes the button out of the screen once the list of visible toast exceeds the current screen size. 
- Introduces a new prop `showClearAllButtonAt` with a default of 3, that denotes when the threshold for displaying the dismiss all toasts button, passing a value of `0` would opt one out of displaying the dismiss all toasts button. An accompanying prop `onClearAllToasts` is introduced to register a method that will be invoked if provided when the clear all …
=> Add dismiss all toast button for EuiGlobalToastList component

generator-eui/changelog/index.js, generator-eui/changelog/templates/changelog.md, upcoming_changelogs/_template.md, wiki/contributing-to-eui/documenting/changelogs.md
This process change is a direct result of https://github.com/elastic/kibana/pull/163961#discussion_r1297420672, where confusion arose from a downstream snapshot change that resulted due to a dependency upgrade not listed in our changelog.
I've added a new section to our changelog template and yeoman generator for dependency upgrades specifically.
If we do want to list _developer_ dependency updates in our changelog, it might be worth taking a leaf from, e.g.: https://github.com/hello-pangea/dnd/blob/main/CHANGELOG.md#1630-2023-06-30
N/A, internal/dev-only
=> [wiki] Include dependency upgrades in changelog

.github/config/label_commenter_config.yml, .github/pull_request_template.md, wiki/contributing-to-eui/README.md
See below for an example of the newly-organized PR checklist template
- Browser QA
- Docs site QA
=> [GitHub] Add breaking change specific checklist, organize general PR checklist template 

src-docs/src/views/inline_edit/inline_edit_example.js
This PR removes the `isBeta` flag from `EuiInlineEdit` to signify the end of the 'beta' period for the component. 
- Check the [PR Preview](https://eui.elastic.co/pr_7181/#/forms/inline-edit) and confirm that the `isBeta` flag no longer exists in the side nav and on the component page header.
=> [EuiInlineEdit] End Beta Phase

.github/workflows/label_commenter.yml
🤦 The _other_ reason why https://github.com/elastic/eui/pull/7178#issuecomment-1714564168 wasn't working was because I hadn't actually configured the GH action to run on PRs
N/A, infra/dev only
=> [GitHub] Fix `breaking change` PR bot auto-responder

src-docs/src/components/guide_page/guide_page_header.tsx
closes https://github.com/elastic/eui/issues/7171
- Go to https://eui.elastic.co/pr_7184/#/
- Click on the codesandbox logo in the top right hand corner of the nav
=> [Docs] Update CodeSandbox link in nav to use Typescript

.github/workflows/community_contribution.yml
My Buildkite community contribution bot threw a `403 Forbidden` error when I tested it with a non-org member contribution. I traced the root cause to my action having `read` permission for pull requests instead of `write`. This was a mis-understanding of how the REST API and Actions differ in their handling of issues vs. pull requests.
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
>
> `pull requests`
>
> Work with pull requests. For example, pull-requests: write permits an action to add a label to a pull request.
QA will be done manually. I'll open a new PR from my test account (not an Elastic org member) and verify the community bot adds a comment and a label without erroring.
=> [BUG] Add write permission to Buildkite community bot.

src/components/description_list/__snapshots__/description_list_title.test.tsx.snap, src/components/description_list/description_list_title.styles.ts, src/components/description_list/description_list_title.tsx, src/themes/amsterdam/overrides/_description_list.scss, src/themes/amsterdam/overrides/_index.scss, upcoming_changelogs/7185.md
- e44a951d345e2fbeda3101364a613be780f2bd8e - Fixes a Sass Amsterdam override for `inline compressed` titles that was missed in #5971 
- b1b7a098a71b6b176ae3264790040894b803c299 - Fixes an unnecessary margin-top style applied to all inline titles when it does nothing (missed in #7062)
- Go to https://eui.elastic.co/pr_7185/#/display/description-list#customizing-appearance
- Browser QA
- Docs site QA - Skipped
- Code quality checklist - Skipped except for snapshot updates
- Designer checklist~
~- [ ] …
=> [EuiDescriptionListTitle] Misc compressed style fixes

package.json, scripts/test-staged.js, scripts/tests/test-staged.test.js, src-docs/src/components/guide_section/_utils.test.js, src/components/card/card.styles.ts, src/components/card/card.test.tsx, src/components/card/card.tsx, src/components/popover/popover.test.tsx, src/global_styling/functions/typography.test.tsx, src/services/theme/hooks.test.tsx, src/test/internal/render_custom_styles.tsx, src/test/rtl/custom_render.ts, yarn.lock
After a recent meeting, the EUI team discussed the friction point of the current `pre-commit` hook and that we feel it currently hinders developers more than it helps. We agreed to move it to a `pre-push` hook instead, ~and additionally switch it to only linting and not running unit tests.~ (see below git thread)
Note - if absolutely necessary, this hook can be skipped via `git push --no-verify`.
NOTE: Once this PR merges, devs will need to manually run `rm -rf .git/hooks/pre-commit` from the EUI project root
N/A, tech debt/dev-only
=> Switch `pre-commit` hook to `pre-push`; fix Jest `--findRelatedTests` behavior

src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap, src/components/datagrid/controls/column_selector.tsx, src/components/datagrid/controls/column_sorting_draggable.tsx, src/components/datagrid/data_grid.test.tsx, src/components/drag_and_drop/__snapshots__/drag_drop_context.test.tsx.snap, src/components/drag_and_drop/__snapshots__/draggable.test.tsx.snap, src/components/drag_and_drop/__snapshots__/droppable.test.tsx.snap, src/components/drag_and_drop/_draggable.scss, src/components/drag_and_drop/_droppable.scss, src/components/drag_and_drop/_index.scss, src/components/drag_and_drop/_variables.scss, src/components/drag_and_drop/drag_drop_context.test.tsx, src/components/drag_and_drop/draggable.styles.ts, src/components/drag_and_drop/draggable.test.tsx, src/components/drag_and_drop/draggable.tsx, src/components/drag_and_drop/droppable.styles.ts, src/components/drag_and_drop/droppable.test.tsx, src/components/drag_and_drop/droppable.tsx, src/components/index.scss, upcoming_changelogs/7187.md
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7187/commits) as this PR contains some cleanup/tech debt tasks around tests etc.
This PR additionally contains a very small focus outline placement fix in https://github.com/elastic/eui/pull/7187/commits/6e1823e6661f7c05995f386d2bfc8b653a56f98a:
**Before:**
**After:**
- Go to https://eui.elastic.co/pr_7187/#/display/drag-and-drop
- Go to https://eui.elastic.co/pr_7187/#/tabular-content/data-grid
- Browser QA
- Docs site QA - skipped
- Designer checklist~
- ~[ ] Updated …
=> [Emotion] Convert `EuiDroppable` & `EuiDraggable`

src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box_input/_combo_box_pill.scss, src/components/combo_box/combo_box_input/combo_box_pill.tsx, upcoming_changelogs/7193.md
Closes #7173 
This PR fixes the truncation for selected `EuiComboBox` items in two parts:
1. Truncation added for combo boxes that have `singleSelection: {{ asPlainText: true }}`
2. Truncation restored for all combo box pills when the length of the text exceeds with width of the pill
1. View the basic combo box demo (https://eui.elastic.co/pr_7193/#/forms/combo-box) and add the option beginning with `Pandora` to your selected options. This pill should truncate.
2. View the single selection demo (https://eui.elastic.co/pr_7193/#/forms/combo-box#single-selection) and add the option beginning with `Pandora`. This plain text should truncate.
- Browser QA
- Docs site QA
=> [EuiComboBox] Allow `ComboBoxPill` components to truncate when displaying long text

wiki/contributing-to-eui/testing/unit-testing.md
Follow up to https://github.com/elastic/eui/pull/7111#discussion_r1318479009
We discussed as a team using `screen` from RTL vs destructuring queries from `render`, and in general decided to clearly document that we prefer `render` for the EUI codebase.
N/A, wiki only
=> [wiki] RTL docs update

.buildkite/pipelines/pipeline_pull_request_test.yml, .buildkite/scripts/pipeline_test.sh
Reverts elastic/eui#7197
This PR broke out individual test commands and used `yarn` to call them in Buildkite where we'd previously used `npm`. This created an issue for the Cypress tests, so I'll rework the original PR.
=> Revert parallelize the Buildkite `test` job

src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, src/components/combo_box/combo_box.spec.tsx, src/components/combo_box/combo_box.test.tsx, src/components/combo_box/combo_box_options_list/_combo_box_options_list.scss, src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx, src/components/text_truncate/__snapshots__/text_truncate.test.tsx.snap, src/components/text_truncate/text_truncate.styles.ts, src/components/text_truncate/text_truncate.tsx, upcoming_changelogs/7212.md
It turns out Kibana's FTR test service is _incredibly_ [dependent on the title attribute](https://github.com/elastic/kibana/blob/main/test/functional/services/combo_box.ts#L95-L98) to select combobox options by so me removing that in #7028 was A Huge Mistake 😭 
While here, I've decided to address https://github.com/elastic/eui/pull/7028#pullrequestreview-1607433096 after all by not instantiating the truncation component (and letting CSS `text-overflow: ellipsis` do its thing) if no custom `truncationProps` configuration(s) are passed.
Also EuiTextTruncate was missing `className`s (yay, betas 💀) so I added those while here.
- Go to https://eui.elastic.co/pr_7212/#/forms/combo-box#truncation
- Browser QA
=> [EuiComboBox] Fixes/reversions for Kibana FTR

src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss, src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx, upcoming_changelogs/7217.md
closes https://github.com/elastic/eui/issues/7196
| <img width="224" alt="" src="https://github.com/elastic/eui/assets/549407/0a43eb58-3b9f-487f-98e1-0769076b78bd"> | <img width="217" alt="" src="https://github.com/elastic/eui/assets/549407/9c219314-81ec-4dbc-afcb-4d3b9d01b679"> |
| [production link](https://eui.elastic.co/v88.4.1/#/templates/super-date-picker) | [staging link](https://eui.elastic.co/pr_7217/#/templates/super-date-picker) |
See above staging vs production links
- Browser QA
- Code quality checklist - N/A - CSS only change (although ideally we'll have screenshot …
=> [EuiSuperDatePicker] Fix quick select button icon spacing

src-docs/src/views/date_picker/states.js, src/components/date_picker/date_picker.test.tsx, src/components/date_picker/date_picker.tsx, upcoming_changelogs/7218.md
- closes https://github.com/elastic/eui/issues/7195
- closes #4572 (note: does not compress the actual calendar popup itself, but neither does EuiSuperDatePicker, so IMO this is fine)
- Go to https://elastic.eui.co/pr_7218/#/forms/date-picker#date-picker-states
- Click "Display toggles", and check the "compressed" switch
- Browser QA
- Docs site QA
=> [EuiDatePicker] Add `compressed` input styling

src/components/markdown_editor/plugins/markdown_default_plugins/processing_plugins.tsx, upcoming_changelogs/7221.md
While investigating TypeScript issues in Kibana, I stumbled over an issue that stemmed from EUI:
```shell
error TS2742: The inferred type of 'processingPlugins' cannot be named without a reference to '@elastic/eui/node_modules/mdast-util-to-hast'. This is likely not portable. A type annotation is necessary.
```
The origin of this error is `getDefaultEuiMarkdownProcessingPlugins` which does not define an explicit return type. In this PR, I'm adding the return type which should resolve the issue in Kibana. (in the meantime, I'm importing `DefaultEuiMarkdownProcessingPlugins` through the EUI source but I'll clean that up once this PR lands in Kibana)
=> [EuiMarkdownEditor] Fix default processing plugins type

src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_body_footer.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/collapsible_nav_beta/collapsible_nav_body_footer.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_body_footer.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_body_footer.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/index.ts, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/index.ts, src/components/collapsible_nav_beta/index.ts
This PR does multiple different things:
Old prop API:
```tsx
<EuiCollapsibleNavItem items={[
{ isGroupTitle: true, title: 'something' },
}] />
```
New prop API:
```tsx
<EuiCollapsibleNavItem items={[
{ renderItem: () => <EuiTitle size="xxxs"><div>something</EuiTitle></div> },
{ renderItem: () => <EuiSpacer size="m" /> },
{ renderItem: WhateverOtherCustomComponentYouWant },
}] />
```
I'm opting for this API over the old one because 1. it's simpler code and type-wise, and 2. it places the onus of consistent title and spacing styling directly on Kibana and not on EUI, and 3. it's a potential escape hatch for future customization (e.g. a button that toggles another flyout).
This new API should address https://github.com/elastic/kibana/issues/167326
Old API:
```tsx
<EuiCollapsibleNavBeta> …
```
=> [EuiCollapsibleNavBeta] Various API updates and cleanups

src/components/combo_box/combo_box.spec.tsx, src/components/combo_box/combo_box_input/combo_box_input.tsx, upcoming_changelogs/7240.md
😬 I introduced this bug in #7215... but at least I caught it fairly quickly, right?
- Go to https://eui.elastic.co/v88.5.1/#/forms/combo-box
- In the first example, type some really long sentence that goes past the width of the input, e.g `You must add an accessible label to each instance of EuiComboBox` 
- Press enter to add the custom option
- Delete the custom added option, and notice that the input caret is still incorrectly on the next line when it shouldn't be, and that the input width is still large even though it does not contain content:
- Go to https://eui.elastic.co/pr_7240/#/forms/combo-box
- In the first example, type some really long sentence that goes past the width of the input, e.g `You must add an accessible label to each instance of EuiComboBox`
- Press enter to add the …
=> [EuiComboBox] Fix new input size util not resetting correctly

package.json, scripts/jest/setup/enzyme.js, src/components/combo_box/combo_box.test.tsx, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap, src/components/drag_and_drop/__snapshots__/draggable.test.tsx.snap, src/components/drag_and_drop/__snapshots__/droppable.test.tsx.snap, src/components/form/range/dual_range.test.tsx, yarn.lock
PR provides script commands to run `.ts` and `.tsx` tests against React `[16]` with no errors. This PR will be combined with a few others to split our Buildkite `test` job to run in parallel.
- Docs site QA
Best way to QA will be to run the following commands after pulling the branch and `yarn` to ensure latest dependencies:
=> [Tech debt] Fix Jest unit tests to run on React 16

src/components/color_picker/color_palette_picker/__snapshots__/color_palette_picker.test.tsx.snap, src/components/date_picker/auto_refresh/__snapshots__/auto_refresh.test.tsx.snap, src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/form/range/__snapshots__/range.test.tsx.snap, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/popover/input_popover.spec.tsx, src/components/popover/input_popover.tsx, src/components/suggest/__snapshots__/suggest.test.tsx.snap
I'm working on pulling out some logic that `EuiComboBox` needs directly into `EuiInputPopover` for #7192, and was struggling to understand and work around some of the existing logic. Since I saw several things that bothered me/that could stand to be cleaned up, I decided to do my favorite thing - refactor and write missing tests 😅  
I've opted to make this refactor separate/standalone from my `EuiComboBox` work in order to make code review less of a headache. As always, I **strongly** recommend [following along by commit](https://github.com/elastic/eui/pull/7241/commits) and [hiding whitespace changes](https://github.com/elastic/eui/pull/7241/files?w=1) (the scary LOC diffs on this PR are literally just from indentation changes on snapshots).
- Removes an extra unnecessary `<div>` in the …
=> [EuiInputPopover] Refactor & clean ups

src/components/icon/__snapshots__/icon.test.tsx.snap, src/components/icon/icon.test.tsx
@1Copenut is attempting to parallelize our React tests, and icons appear to be failing/flaky. Our current hunch is that the silenced act warnings/async nature of the icon component is causing those failures. This PR should (🤞) hopefully address that
N/A, tech debt only
=> [EuiIcon] Fix silenced test errors

.storybook/preview.tsx, .storybook/utils.test.ts, .storybook/utils.ts, scripts/jest/config.js, src/components/button/button_empty/button_empty.stories.tsx, src/components/button/button_group/button_group.stories.tsx, src/components/button/button_icon/button_icon.stories.tsx, src/components/collapsible_nav/collapsible_nav.stories.tsx, src/components/collapsible_nav/collapsible_nav_group/collapsible_nav_group.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/empty_prompt/empty_prompt.stories.tsx, src/components/error_boundary/error_boundary.stories.tsx, src/components/filter_group/filter_button.stories.tsx, src/components/header/header.stories.tsx, src/components/header/header_alert/header_alert.stories.tsx, src/components/header/header_links/header_links.stories.tsx, src/components/header/header_logo/header_logo.stories.tsx, src/components/key_pad_menu/key_pad_menu_item.stories.tsx, src/components/page/page.stories.tsx, src/components/page/page_body/page_body.stories.tsx, src/components/page/page_header/page_header.stories.tsx, src/components/page/page_section/page_section.stories.tsx, src/components/page/page_sidebar/page_sidebar.stories.tsx, src/components/panel/split_panel/split_panel_inner.stories.tsx, src/components/panel/split_panel/split_panel_outer.stories.tsx, src/components/resizable_container/resizable_button.stories.tsx, src/components/resizable_container/resizable_collapse_button.stories.tsx, src/components/side_nav/side_nav.stories.tsx, src/components/text_truncate/text_truncate.stories.tsx
This PR is a general cleanup/consistency pass on our existing stories. The way we've written stories has evolved as we've learned more tips and tricks of Storybook's API, and this attempts to elevate all existing stories to the same level.
1. Adds new `hideStorybookControls()` and `disableStorybookControls()` utils so we're not copying the same `{ table: { disable: true } }` or `{ control: false }` over and over again
- This has the main DRY benefit of future-proofing, if someday Storybook changes the API they use to render the controls table, we can quickly update it in one place instead of find+replacing hundreds of lines
2. Standardizes how and where we list component defaults - this should now always be in the initial component `meta.args` as opposed to defining them as separate …
=> [Storybook] General consistency pass

.buildkite/pipelines/pipeline_pull_request_test.yml, .buildkite/scripts/pipeline_test.sh, src/components/icon/icon.test.tsx
This PR is a second attempt to split our Buildkite `test` job and run the linter, unit tests, and Cypress tests in parallel. It switches back to using `npm` instead of `yarn`. This allows us to allocate more resources in Node to prevent test failures. See https://github.com/elastic/eui/pull/7209 for the previous iteration of this PR. I will close the previous PR when this one merges.
This improved version will split Jest TSX tests and Cypress tests to run against React version `[16, 17, 18]`.
QA will be done manually by verifying the test runs on Buildkite UI.
=> [INFRA] Parallelize Buildkite test job, take 3

src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap, src/components/flyout/__snapshots__/flyout.test.tsx.snap, src/components/flyout/flyout.stories.tsx, src/components/flyout/flyout.styles.ts, src/components/flyout/flyout.test.tsx, src/components/flyout/flyout.tsx, upcoming_changelogs/7239.md
closes #7205
- Go to https://eui.elastic.co/pr_7239/storybook/index.html?path=/story/euiflyout--push-flyouts
- Toggle the `pushAnimation` control to "True"
- Browser QA
- Docs site QA
- Designer checklist - skipped - IIRC Figma doesn't have animations?
=> [EuiFlyout] Allow push flyouts to have slide in animations

src/components/flex/flex_grid.styles.ts, src/components/flex/flex_group.styles.ts, upcoming_changelogs/7251.md
Regressed in #6270. Should be `16px` and not `12px`. closes #7244
- Browser QA
- Code quality checklist - N/A, if only we had visual screenshot regression tests :')
=> [EuiFlexGroup][EuiFlexGrid] Fix `m` gutter size spacing

src/components/flyout/flyout.tsx, upcoming_changelogs/7259.md
The first commit is the primary one needed to resolve https://github.com/elastic/kibana/issues/168164, the other following commits are just extra nice-to-haves.
Here's what I _think_ is happening: the unmemoized `focusTrapProps` is causing `<EuiFocusTrap>` the underlying focus trap library to re-mount fully when it shouldn't, which then causes the focus issues because the focus trap will auto-focus the flyout wrapper on mount.
The remount is occurring because Security's flyouts are wrapped in a `<Formik>` lib that, on validation, cascades the state update down to the wrapped `EuiFlyout` and rerenders it.
Fix testing
- Go to https://cee-chen-branch-main.kbndev.co/app/management/security/api_keys
- Log in with dev/local elastic credentials
- Click the "Create API key" button
- Once the …
=> [EuiFlyout] Memoize various internals to reduce rerenders

src-docs/src/views/tables/auto/auto.tsx, src/components/basic_table/table_types.ts, src/components/table/__snapshots__/table_row_cell.test.tsx.snap, src/components/table/table_row_cell.test.tsx, src/components/table/table_row_cell.tsx, upcoming_changelogs/7254.md
> As always, I recommend [reviewing by commit](https://github.com/elastic/eui/pull/7254/commits) to sort out feature work from cleanups.
closes #7226
Proposed API:
```tsx
<EuiBasicTable
columns={[
{
field: 'myField',
name: 'My field',
truncateText: { lines: 2 },
}
]}
/>
```
Single (`true`) vs multi-line truncation:
- Go to https://eui.elastic.co/pr_7254/#/tabular-content/tables#table-layout
- Browser QA
- Docs site QA
~- [ ] If applicable, added the **breaking change** issue label (and filled out the breaking change …
=> [EuiBasicTable][EuiInMemoryTable] Add new `truncationText` line API

src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
See https://github.com/elastic/kibana/issues/168301
N/A, this is a beta component
=> [EuiCollapsibleNavItem] Prevent DOM errors about `accordionProps` being passed to non-accordions

src-docs/src/views/elastic_charts/accessibility_sunburst.js, src-docs/src/views/elastic_charts/pie.js, src-docs/src/views/elastic_charts/pie_example.js, src-docs/src/views/elastic_charts/pie_slices.js, src-docs/src/views/elastic_charts/treemap.js
This PR fixes errors in partition chart coloring due to `fillColor` api changes in [`v54.0.0`](https://github.com/elastic/elastic-charts/releases/tag/v54.0.0) (from https://github.com/elastic/elastic-charts/pull/1956).
We missed this change in updating chart in https://github.com/elastic/eui/pull/6641 with 6 breaking changes. Also we have become accustom to typescript flagging errors like this but all errors in this case were in js files 😭.
This changed the API where the first param of the `fillColor` function is the `Key` of the layer and not the entire `Node`. The second param is now the `sortIndex` used in many places in the EUI docs.
```diff
- export type NodeColorAccessor = (d: ShapeTreeNode, index: number, array: HierarchyOfArrays) => string;
+ export type NodeColorAccessor = (key: …
```
=> fix: color errors due to `fillColor` changes in `v54.0.0`

src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/_mixins.scss, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_actions.test.tsx, src/components/datagrid/body/data_grid_cell_actions.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/utils/__mocks__/row_heights.ts, src/components/datagrid/utils/row_heights.test.ts, src/components/datagrid/utils/row_heights.ts
This PR _started_ as just updating EuiDataGrid to use the new `EuiTextBreakTruncate` component... and then I kept staring at the code going "ugh this is so hard to read/understand" and then several hours later I'd done my favorite thing, which is cleaning up code (and discovering a bug or two along the way) 🤣
I split up the commits by emoji to signify which items were refactors (🔥). I also recommend reading the commit messages as I tried to explain my reasoning for certain changes as I went along.
- Text truncation work:
- 92a7d1eb811148468dd4c7f7b10e4ca45dc9ed2c
- 953e6f7a3387351a552aa8338f24e5cd0aa3bd1d
- 901a3aae3918ddceb1e1808760796337a32c0b8e
- 5957ca22ed6fa33e55d70f239c9d2eeaecbc985e
- 7ed08d06400f253fac05c603931dd9998ce3c543
- Opinionated cell DOM/CSS cleanup:
- …
=> [EuiDataGrid] Update to use `EuiTextBreakTruncate` + cell DOM & CSS cleanup

src-docs/src/components/guide_rule/guide_rule_example.js, src-docs/src/views/app_context.js, src-docs/src/views/app_view.js, src/components/form/field_password/field_password.tsx, src/components/popover/input_popover.tsx
See https://github.com/elastic/eui/issues/7287 (NOTE: Does not close the issue fully - we need https://github.com/elastic/eui/pull/7296 for that as well)
React 18 is deprecating support for `defaultProps` - this PR removes all instances of function component `defaultProps`, and also checks that all props tables in our docs work as expected.
- Go to https://eui.elastic.co/pr_7297/#/forms/form-controls#password-field 
- Go to https://eui.elastic.co/pr_7297/#/layout/popover#popover-attached-to-input-element 
- Docs site QA
- Code quality checklist - N/A, current tests passing should suffice
- Release checklist - N/A, this should not have any consumer or user facing impact
=> [Tech debt] Remove `defaultProps` from function components

src-docs/src/views/datagrid/basics/datagrid.js, src/components/datagrid/body/data_grid_row_manager.test.ts, src/components/datagrid/body/data_grid_row_manager.ts, upcoming_changelogs/7301.md
closes https://github.com/elastic/eui/issues/7292 (+ fixes a few other row manager issues I noticed while here - I recommend [reviewing by commit](https://github.com/elastic/eui/pull/7301/commits) to make the separate fixes easier to follow)
- Go to https://eui.elastic.co/pr_7301/#/tabular-content/data-grid
(The other fixes I consider adequately covered by unit tests, and shouldn't need manual QA)
- Browser QA - N/A, almost purely a logical or visual (CSS) fix
- Docs site QA
=> [EuiDataGrid] Various row manager fixes

src/components/page/page_header/__snapshots__/page_header.test.tsx.snap, src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, src/components/tabs/__snapshots__/tab.test.tsx.snap, src/components/tabs/__snapshots__/tabs.test.tsx.snap, src/components/tabs/tab.tsx, src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, upcoming_changelogs/7309.md
This has been broken since #6311 (viewable by browsing EUI at <v60.x)
| <img width="458" alt="" src="https://github.com/elastic/eui/assets/549407/9348e61d-eb38-43d7-94e0-bc4e84e3d4b5"> | <img width="461" alt="" src="https://github.com/elastic/eui/assets/549407/4643648d-678b-438d-8800-c7eec02b8d24"> | 
- Go to https://eui.elastic.co/pr_7309/#/navigation/context-menu#using-panels-with-mixed-items-content
- Click the last/bottom-most button
- Click the `See more` item
- Browser QA
- Code quality checklist - N/A, although we do need visual regression tests
~- [ ] If applicable, …
=> [EuiTabs] Fix incorrectly wrapping tab content

src/components/date_picker/super_date_picker/date_popover/_date_popover_content.scss, upcoming_changelogs/7313.md
I broke this in #6795 🥲 We have got to get visual regression tests y'all
| Before | After (same as  [EUI v80.x](https://eui.elastic.co/v80.0.0/#/templates/super-date-picker))  |
| <img width="300" alt="" src="https://github.com/elastic/eui/assets/549407/6629f8a4-4a3b-42ba-a977-eef5779dab7c"> | <img width="300" alt="" src="https://github.com/elastic/eui/assets/549407/59b541b0-a9b6-4781-bec2-95c7f7743d20"> |
- Go to https://eui.elastic.co/pr_7313/#/templates/super-date-picker
- Click `Last 30 minutes` of the first example, switch to the `Absolute` tab
- Browser QA
=> [EuiSuperDatePicker] Fix inline date picker width

src/components/accordion/accordion.spec.tsx, src/components/accordion/accordion.tsx, src/components/accordion/accordion_children/accordion_children.tsx, upcoming_changelogs/7314.md
Required for https://github.com/elastic/kibana/issues/167330
I (partially) regressed this in #7161 when I converted EuiAccordion's constituent parts into sub-functional components. Specifically, this logic:
https://github.com/elastic/eui/blob/fb7c3975efb71720641bbd04241979702bedaed1/src/components/accordion/accordion_children/accordion_children.tsx#L86-L92
I thought was more React-y rather than calling a declarative `.focus()` when the trigger button was clicked. However, I now realize that the click behavior is necessary to determine user open vs programmatic open for predictable focus behavior. It does not necessarily make any sense for focus to jump to the accordion just because it was opened on the page by another event (e.g. async loading) - but it always makes sense for focus to …
=> [EuiAccordion] Fix focus behavior on user interaction open/close vs `forceState` open/close

src/components/datagrid/_data_grid_data_row.scss, upcoming_changelogs/7320.md
This PR will close https://github.com/elastic/kibana/issues/169757 once it's merged into Kibana main.
| Before (avatar in left column is cut off at the bottom) | After |
| <img width="635" alt="" src="https://github.com/elastic/eui/assets/549407/b9ac3478-5450-44ca-b6d7-53c6879be93e"> | <img width="637" alt="" src="https://github.com/elastic/eui/assets/549407/f3ce959b-ce9b-442c-9b7e-c70623611097"> | 
This was regressed in #7255, although interestingly enough, this behavior was already semi-broken prior to that PR, but _only_ for row heights set to `lineCount` or a static number. You can see this in [previous EUI releases](https://eui.elastic.co/v80.0.0/#/tabular-content/data-grid-style-display) when you change the grid density setting to `lineCount: 1` (as opposed to …
=> [EuiDataGrid] Fix over-eager visual cutoff on cell contents

src/components/form/field_number/__snapshots__/field_number.test.tsx.snap, src/components/form/field_number/field_number.spec.tsx, src/components/form/field_number/field_number.stories.tsx, src/components/form/field_number/field_number.test.tsx, src/components/form/field_number/field_number.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, upcoming_changelogs/7291.md
closes https://github.com/elastic/eui/issues/7281
> ⚠️ NOTE: There is a slight gotcha to this PR in that our current version jsdom (11.x) incorrectly thinks that any input with a `step` passed to it is natively invalid. Upgrading to jsdom v15+ will fix this issue (and a few of our snapshots) in the future.
- Go to https://eui.elastic.co/pr_7291/storybook/?path=/story/euifieldnumber--controlled-component
- Scroll down to the `value` prop control and change it to, e.g. 5
- Change the `min` prop, to, e.g. 10
- Change the `value` prop to satisfy `min`, e.g. 100
- (Optional) Test other props that would affect validity (e.g. `max`, `step`) as well to confirm that updating those props will correctly update the input's invalid state
- Browser QA
- …
=> [EuiFieldNumber] Fix native validity state when controlled `value` changes

src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_beta.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/collapsible_nav_beta/collapsible_nav_body_footer.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_button/__snapshots__/collapsible_nav_button.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_button/collapsible_nav_button.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx, src/components/collapsible_nav_beta/context.ts
closes https://github.com/elastic/eui/issues/7318
- Go to https://eui.elastic.co/pr_7319/storybook/?path=/story/euicollapsiblenavbeta--kibana-example
- Resize your window or set the storybook viewport to small mobile
- Resize your window back to desktop
- Browser QA
- Docs site QA - N/A, beta component
- Release checklist - N/A, beta component
=> [EuiCollapsibleNavBeta] Store mobile overlay open/close state separately from desktop collapsed/expanded state

src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts
> ⚠️ Quick note about this bug: it **only** occurs when toggling an EuiAccordion that's the **last** item in the `items` array.
| Note the "Get started" item jumping on every open | "Get started" item does not jump |
| ![before](https://github.com/elastic/eui/assets/549407/0ad82a7c-1aee-4c02-a829-801a49d4d273) | ![after](https://github.com/elastic/eui/assets/549407/d23e5503-570c-4da7-84df-40e058d503ee) | 
- Go to http://eui.elastic.co/pr_7317/?path=/story/euicollapsiblenavbeta--kibana-example
- Click the `Observability` accordion arrow
- Scroll down to `AIOps` and click that accordion arrow
- Browser QA
- Docs site QA …
=> [EuiCollapsibleNavBeta] Fix accordion open animation bug

src-docs/src/views/guidelines/writing_guidelines.js
This PR is a follow-up to https://github.com/elastic/eui/pull/7300.
It adds a mention of tiers and subscription levels to the capitalization rules of the writing section.
=> Add tiers and subscription levels to capitalization rules

src-docs/src/views/tables/in_memory/in_memory_selection_controlled.tsx, src-docs/src/views/tables/in_memory/in_memory_selection_section.js, src-docs/src/views/tables/in_memory/in_memory_selection_uncontrolled.tsx, src-docs/src/views/tables/selection/selection_controlled.tsx, src-docs/src/views/tables/selection/selection_section.js, src-docs/src/views/tables/selection/selection_uncontrolled.tsx, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/basic_table/table_types.ts, upcoming_changelogs/7321.md
closes https://github.com/elastic/eui/issues/6184
The bulk of this PR is primarily docs - the actual logic change is relatively small 😅  I recommend code-reviewing the [first two commits](https://github.com/elastic/eui/pull/7321/commits) and only QAing the last [docs] commit. Feedback on the new docs copy would also be appreciated!
> ⚠️ This PR also marks using table refs and internal `setSelection` APIs as deprecated. See changelog
- (**EuiBasicTable**) Go to https://eui.elastic.co/pr_7321/#/tabular-content/tables#adding-selection-to-a-table
- In the top left hand corner of the demo, click the `Controlled selection` switch
- Browser QA
~- [ ] Checked for **accessibility** …
=> [EuiBasicTable][EuiInMemoryTable] Support controlled `selection` API

src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/accordion/accordion_children/accordion_children.tsx, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.tsx, src/components/notification/__snapshots__/notification_event.test.tsx.snap, upcoming_changelogs/7326.md
closes https://github.com/elastic/eui/issues/7316 - please see the link for more discussion/reasoning as to why EUI defaults to the less SR-intrusive `group` role over `region` (TL;DR, since we cannot know what content our consumers are using in accordions, we should allow them to determine for themselves whether their accordion content is significant enough to be a landmark region).
This PR also (in a separate commit) updates the **beta** `EuiCollapsibleNavGroup` components to follow a similar `role="group"` and aria-labelledby markup.
- Open a screen reader and test:
- Browser QA
- Docs site QA
=> [EuiAccordion] Add configurable `role` prop and change default role to `group`

src/components/button/button_display/_button_display.test.tsx, src/components/button/button_display/_button_display.tsx, src/components/button/button_group/__snapshots__/button_group.test.tsx.snap, src/components/button/button_group/button_group.test.tsx, src/components/button/button_group/button_group.tsx, src/components/button/button_group/button_group_button.styles.ts, src/components/button/button_group/button_group_button.tsx, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting_draggable.test.tsx.snap, src/components/datagrid/controls/column_sorting_draggable.test.tsx, src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/data_grid.test.tsx, src/global_styling/mixins/__snapshots__/_states.test.ts.snap, src/global_styling/mixins/_states.test.ts, src/global_styling/mixins/_states.ts, upcoming_changelogs/7325.md
closes https://github.com/elastic/eui/issues/7101
See https://lea.verou.me/blog/2022/07/button-group/ - per recent a11y/industry discussion, using `<input type="radio">` buttons for single selection/exclusive button groups is no longer recommended.
No functionality should have regressed as a result of this change, although potentially some consumers' test selectors or CSS that were targeting `label` instead of `button` will need to be updated.
FYI, I grabbed this work because it's needed to unblock the `link or button` service/logic I'm shortly going to be implementing.
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7325/commits) - I tried to separate things out atomically to make changes easier to understand.
Mostly regression testing - ensure the …
=> [EuiButtonGroup] Remove radio group markup/behavior

src/components/toast/__snapshots__/global_toast_list.test.tsx.snap, src/components/toast/global_toast_list.test.tsx, src/components/toast/global_toast_list.tsx, upcoming_changelogs/7328.md
#7316 got me searching through EUI for more `region` roles that didn't feel quite right to me. I found this one, and then I found the [log role on MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/log_role) that seems to far more closely fit the bill!
[`role="alert"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role) could also qualify, but since we can't guarantee toast content, we should default to the less aggressive role and allow consumers to set their own role if they know their toasts will only be used for notifications that require immediate action.
- https://eui.elastic.co/pr_7328/#/display/toast
- Browser QA
- Docs site QA
~- [ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/docum …
=> [EuiGlobalToastList] Add configurable `role` prop and default to `log` role

src-docs/src/views/scroll/full_height.tsx, src-docs/src/views/scroll/scroll.tsx, src-docs/src/views/scroll/scroll_example.js, src-docs/src/views/scroll/scroll_x.tsx, src-docs/src/views/scroll/scroll_y.tsx, src/components/datagrid/controls/__snapshots__/column_selector.test.tsx.snap, src/components/datagrid/controls/__snapshots__/column_sorting.test.tsx.snap, src/components/datagrid/controls/column_selector.tsx, src/components/datagrid/controls/column_sorting.tsx, upcoming_changelogs/7327.md
See https://github.com/elastic/eui/issues/7316 for more discussion and sources on why not to overuse `role="region"`. Also see individual git commit messages for more rationale on specific changes.
Note: most of the line diffs in this PR come from indentation, so please [turn off whitespace changes](https://github.com/elastic/eui/pull/7327/files?w=1).
- Start a screenreader
- Go to https://eui.elastic.co/pr_7327/#/tabular-content/data-grid
- Click the `Sort fields` button in the datagrid toolbar
- Pick at least 2 fields to sort by
- Tab back to the drag handles on those fields and re-order one of them
- Go to https://eui.elastic.co/pr_7327/#/utilities/scroll
- Browser QA
- Docs site QA
~- [ ] If applicable, added the **breaking change** issue …
=> [a11y] More `role="region"` cleanup

src/components/datagrid/controls/display_selector.test.tsx, src/components/datagrid/controls/display_selector.tsx, upcoming_changelogs/7338.md
closes https://github.com/elastic/eui/issues/7336
The current EuiDataGrid lines per row number input doesn't allow users to clear it to empty before entering a new value.
I recommend [following along by commit](https://github.com/elastic/eui/pull/7338/commits), as I did some minor variable renaming while here.
- Go to https://eui.elastic.co/pr_7338/#/tabular-content/data-grid
- Click the display settings icon in the datagrid toolbar
- Click the "Custom" button
- Browser QA
- Docs site QA - N/A, not a consumer-facing API
=> [EuiDataGrid] Allow clearing the "Lines per row" input

src-docs/src/views/selectable/selectable_templates/sitewide_search.tsx, src/components/selectable/selectable_templates/__snapshots__/selectable_template_sitewide.test.tsx.snap, src/components/selectable/selectable_templates/selectable_template_sitewide.test.tsx, src/components/selectable/selectable_templates/selectable_template_sitewide.tsx, upcoming_changelogs/7339.md
The Support Portal folks (CC @pickypg) have a selectable sitewide search button in an always-dark `EuiHeader`, and they need to be able to wrap an `<EuiThemeProvider colorMode="dark">` to replace the now removed `color="ghost"` prop (#7296).
But it turns out because the sitewide component was using `React.cloneElement`, this would break the popover toggle behavior. This PR fixes that bug by always wrapping the mobile popover toggle in a span wrapper that has the desired click/keyboard events set.
| Before (clicking does nothing) | After |
| ![sitewide_before](https://github.com/elastic/eui/assets/549407/086f67ad-f19c-483c-8161-5866f20e0db1) | ![sitewide_after](https://github.com/elastic/eui/assets/549407/50b75f36-329b-4524-893c-287e2eb9b6cc) | 
- Go to …
=> [EuiSelectableTemplateSitewide] Fix React wrappers breaking `popoverButton` behavior

src/components/date_picker/super_date_picker/date_popover/_absolute_tab.scss, src/components/date_picker/super_date_picker/date_popover/absolute_tab.test.tsx, src/components/date_picker/super_date_picker/date_popover/absolute_tab.tsx, src/components/i18n/__snapshots__/i18n.test.tsx.snap, src/components/i18n/i18n.test.tsx, src/components/i18n/i18n.tsx, upcoming_changelogs/7341.md
> As always, I recommend [reviewing by commit](https://github.com/elastic/eui/pull/7341/commits), as there was an incidental i18n fix/missing feature that was needed along the way 
Follow up to #7331 - @mjaggard had some further excellent points/discussions that led me to revisit the UX once again. I removed the type debouncer with an `Enter` keypress UX event instead (and added more helpful hint text on user type). I also added an `onPaste` handler to automatically parse pasted timestamps without requiring the extra Enter keypress.
All in all, this ideally should be a solid win for users with multiple flows:
- Pasting in timestamps (no extra 1 second of wait time or keypress needed)
- Typing in a timestamp manually (no shenanigans for either slow or fast typers, and information about the …
=> [EuiSuperDatePicker] Improve `Absolute` tab input UX further

src-docs/src/components/guide_page/guide_page_header.tsx, src-docs/src/components/guide_page/version_switcher.tsx
It occurred to me on a whim today that our PR staging instances (e.g. https://eui.elastic.co/pr_7347) should likely show some affordance for what they are (a staging server) rather than using the plain old version switcher (#7298). Here's my proposal for the different environments:
Check it out! https://eui.elastic.co/pr_7347/#/
N/A, docs only
=> [docs] Add header badge for PR staging instances

src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_body_footer.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_body_footer.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_group/collapsible_nav_group.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_popover.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_accordion.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_group.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_link.tsx
closes https://github.com/elastic/kibana/issues/168484
Hover/mouse states:
Focus/keyboard states:
- https://eui.elastic.co/pr_7337/storybook/?path=/story/euicollapsiblenavbeta--kibana-example
- Go to https://eui.elastic.co/pr_7337/storybook/?path=/story/euicollapsiblenavitem--edge-case-testing
- Browser QA
- Docs site QA - N/A, beta component
- Release checklist - N/A, beta component
=> [EuiCollapsibleNavBeta] Remove ability for accordion/group titles to contain links

changelogs/upcoming/7360.md, src/components/text/__snapshots__/text.styles.test.ts.snap, src/components/text/text.styles.ts
closes #7356
The removed `margin-bottom` CSS was inadvertently affecting `EuiIcon`s with custom SVG content (which generate `<img>` tags rather than `<svg>` tags).
I opted to make this opinionated change because it was affecting a production Kibana usage of custom SVGs in an `EuiCallOut` ([example CodeSandBox](https://codesandbox.io/s/old-shadow-vlxpgt?file=/demo.tsx)). In comparison, the number of production usages of images within `EuiText` in Kibana is very likely none.
Consumers who want this extra margin bottom back on images within EuiText can do any of the following:
1. Use an `<EuiImage width="fullSize" margin="l" />` component
2. Use an `<EuiSpacer />`
3. Wrap your `<img>` in a `<p>` tag
- Browser QA - N/A, skipping because this change is straightforward
- Docs site QA - N/A, …
=> [EuiText] Remove opinionated styles on child `img` tags

changelogs/upcoming/7361.md, src-docs/src/views/tables/actions/actions.tsx, src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap, src/components/basic_table/__snapshots__/custom_item_action.test.tsx.snap, src/components/basic_table/action_types.ts, src/components/basic_table/collapsed_item_actions.test.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/custom_item_action.tsx, src/components/table/_responsive.scss
Flagged in Slack today - on production, both basic and memory tables are incorrectly rendering double wrapping `<button>`s, which is definitely an axe/a11y violation.
| <img width="512" alt="" src="https://github.com/elastic/eui/assets/549407/4a471544-7eb2-4adc-9571-d4037d45c63d"> | <img width="521" alt="" src="https://github.com/elastic/eui/assets/549407/785338e6-5f8d-48dc-8720-b7eb1da276fe"> |
⚠️ **Please follow along by commit** - the first 3 commits are the only required fixes, everything else is tech debt (rewriting tests to RTL, removing some totally unnecessary logic I noticed while here, then converted the files from class to function components because why not).
I also noticed that the mobile UI/UX of custom actions looked pretty meh, and …
=> [EuiBasicTable][EuiInMemoryTable] Fix collapsed custom actions rendering an extra `<button>` wrapper + cleanup

changelogs/upcoming/7362.md, src-docs/src/views/super_select/super_select_basic.js, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.test.tsx, src/components/form/super_select/super_select.tsx, src/components/form/super_select/super_select_control.test.tsx, src/components/form/super_select/super_select_control.tsx
closes #7359
| ![before](https://github.com/elastic/eui/assets/549407/0e99937d-d33e-42f9-9521-b618001106fd) | ![after](https://github.com/elastic/eui/assets/549407/84181e10-bfb4-4fb9-950d-a0ca4451d023) | 
As always, [review by commit](https://github.com/elastic/eui/pull/7362/commits) and check out the commit messages - while here, I noticed the generic typing on the component was flawed / didn't fully allow for booleans, so I decided to fix that and then clean up/rewrite a bunch of tests while here 😅 
- Browser QA
~- …
=> [EuiSuperSelect] Allow rendering falsy but not nullish values

changelogs/upcoming/7375.md, src-docs/src/views/breadcrumbs/popover_content.tsx, src/components/breadcrumbs/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap, src/components/breadcrumbs/breadcrumb.styles.ts, src/components/breadcrumbs/breadcrumb.tsx
I noticed this visual bug while suggesting a workaround to Anton for serverless breadcrumbs 😬 (https://github.com/elastic/eui/issues/7349#issuecomment-1818267121)
| <img width="429" alt="" src="https://github.com/elastic/eui/assets/549407/6f67362d-6c8f-48a2-9d3d-a05ee935ae6f"><br>missing arrow on truncated text | <img width="450" alt="" src="https://github.com/elastic/eui/assets/549407/4907e25c-40f2-46d8-bd93-3c74bb263677"> |
| <img width="368" alt="" src="https://github.com/elastic/eui/assets/549407/8e14a8a2-4b59-4f35-9c81-c9b82ec66055"><br>broken truncation at small container widths | <img width="367" alt="" src="https://github.com/elastic/eui/assets/549407/4674fbc6-6638-4de3-965c-fef613a940e2"> | 
- Go to …
=> [EuiBreadcrumbs] Fix broken truncation for breadcrumbs that toggle popovers

changelogs/upcoming/7373.md, scripts/jest/setup/throw_on_console_error.js, src-docs/src/views/tables/actions/actions.tsx, src-docs/src/views/tables/actions/actions_section.js, src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap, src/components/basic_table/__snapshots__/default_item_action.test.tsx.snap, src/components/basic_table/action_types.ts, src/components/basic_table/collapsed_item_actions.test.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/default_item_action.test.tsx, src/components/basic_table/default_item_action.tsx, src/components/basic_table/expanded_item_actions.tsx, src/components/context_menu/__snapshots__/context_menu_item.test.tsx.snap, src/components/context_menu/context_menu_item.styles.ts, src/components/context_menu/context_menu_item.test.tsx, src/components/context_menu/context_menu_item.tsx, src/components/table/_table.scss
@alvarezmelissa87 is working on a table that needs conditional action descriptions. She was previously attempting to use custom `render`ed actions to achieve this, but it would be much cleaner all around for their use case for EUI to simply allow `actions.description` to be a callback which we pass the current `item` to.
I also added this functionality to the `href` and `data-test-subj` keys while here, because why not/it seems useful! Example usage:
```tsx
<EuiBasicTable
columns={[
// ... columns
{
name: 'Actions',
actions: [{
name: (item) => `Delete ${item.name}`,
description: (item) => item.someCondition ? 'This does X' : 'This does Y',
href: (item) => `/delete/${item.id}`,
'data-test-subj': (item) => `delete-${item.id}`,
}],
},
]}
/>
```
While here, I noticed that the action …
=> [EuiBasicTable][EuiInMemoryTable] Enable more action props to accept an optional callback + fix missing tooltips on collapsed actions

changelogs/upcoming/7343.md, cypress/support/component-index.html, src/components/combo_box/combo_box.spec.tsx, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/_mixins.scss, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/data_grid_cell.test.tsx, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_actions.test.tsx, src/components/datagrid/body/data_grid_cell_actions.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx, src/components/datagrid/body/footer/data_grid_footer_row.test.tsx, src/components/datagrid/body/header/_data_grid_header_row.scss, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid_types.ts, src/components/datagrid/utils/row_heights.test.ts, src/components/datagrid/utils/row_heights.ts, src/components/datagrid/utils/scrolling.spec.tsx, src/components/popover/popover.tsx, src/components/text_truncate/text_truncate.spec.tsx, src/components/text_truncate/utils.spec.tsx
- closes https://github.com/elastic/eui/issues/5828, https://github.com/elastic/kibana/issues/133739, and https://github.com/elastic/kibana/issues/99312
- closes https://github.com/elastic/eui/issues/5686
This PR redesigns the cell actions UI/UX to sit outside the cell instead of inside (which resolves several issues with actions clipping content), and additionally repositions the cell popover to sit on top of the cell instead of next to it or below it.
> ⚠️ Worth noting: this change enabled us to remove an extra DOM wrapper within the `<EuiDataGridCell>`, specifically the `.euiDataGridRowCell__contentWrapper` node. While this is good news in terms of relatively cleaner HTML/CSS, it may also cause breakages to datagrid CSS overrides in Kibana.
| Hover state | Focus state | Cell popover | …
=> [EuiDataGrid] Cell actions redesign

changelogs/upcoming/7371.md, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap, src/components/datagrid/body/header/_data_grid_header_row.scss, src/components/datagrid/body/header/data_grid_header_cell.test.tsx, src/components/datagrid/body/header/data_grid_header_cell.tsx
- Closes https://github.com/elastic/eui/issues/7137
This PR updates styles of `EuiDataGrid` header cells:
- Action icon is changed to `boxesVertical` and it will appear on hover
- Sorting icon is moved to after the title
- Right-alignment of header cells content for numeric columns
Before:
After:
- Browser QA
- Code quality checklist - N/A - snapshots only, since this is mostly just DOM/CSS changes
=> [EuiDataGrid] Redesign grid header

changelogs/upcoming/7380.md, src/components/form/form_row/_form_row.scss
Thank you to @zinckiwi for pointing this out! 🏅 
| <img width="733" alt="before" src="https://github.com/elastic/eui/assets/549407/e434f85d-86a7-4f30-9fe3-b8f75b182769"> | <img width="730" alt="after" src="https://github.com/elastic/eui/assets/549407/16ec1d51-6844-4fbf-99b4-4d50e3d633fb"> | 
- Browser QA
- Code quality checklist - N/A, CSS only change
~- [ ] Updated the …
=> [EuiFormRow] Fix `hasEmptyLabelSpace` being off by 2px

src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/body/data_grid_cell.tsx, src/components/datagrid/body/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/data_grid_cell_popover.test.tsx, src/components/datagrid/body/data_grid_cell_popover.tsx
I noticed this bug while working on another (already in production) datagrid focus bug. Clicking anywhere outside the cell popover should auto close the popover; but right now in latest main it does not. This bug was introduced by #7343, so I want to get the fix in before the next release. I've added several E2E tests for it as well so it doesn't regress again.
| ![before](https://github.com/elastic/eui/assets/549407/a02a4917-4586-4932-a1c9-0f2faa09d930) | ![after](https://github.com/elastic/eui/assets/549407/dfc9bc32-b823-4af9-b06d-23bb01fa5fc1) | 
- Go to https://eui.elastic.co/pr_7387/#/tabular-content/data-grid
- Click on any cell, then click the expand cell action icon
- Go to https://eui.elastic.co/pr_7387/#/tabular-content/data-grid-cells-popov …
=> [EuiDataGrid] Fix cell popovers not closing on outside grid click

changelogs/upcoming/7388.md, src-docs/src/views/combo_box/combo_box_example.js, src-docs/src/views/selectable/selectable_example.js, src-docs/src/views/selectable/selectable_truncation.tsx, src/components/auto_sizer/auto_sizer.testenv.tsx, src/components/combo_box/combo_box.tsx, src/components/selectable/__snapshots__/selectable.test.tsx.snap, src/components/selectable/selectable.spec.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx, src/components/selectable/selectable_list/selectable_list_item.tsx, src/components/selectable/selectable_option.tsx, src/components/text_truncate/text_truncate.test.tsx, src/components/text_truncate/text_truncate.tsx
closes https://github.com/elastic/eui/issues/7351
As always, please [review by commit](https://github.com/elastic/eui/pull/7388/commits) 🙏 
- https://eui.elastic.co/pr_7388/#/forms/selectable#truncation
- Browser QA
- Docs site QA
=> [EuiSelectable] Add configurable truncation

changelogs/upcoming/7392.md, src-docs/src/views/selectable/selectable_truncation.tsx, src/components/selectable/selectable.spec.tsx, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx
closes https://github.com/elastic/eui/issues/7391 (NOTE: This will need another backport release to make it into 8.12 FF)
| <img width="489" alt="" src="https://github.com/elastic/eui/assets/549407/a8d5c972-cdb2-4930-b1a6-935161d526e0"> | <img width="489" alt="" src="https://github.com/elastic/eui/assets/549407/697708db-1593-4390-850d-614f57d27ef6"> | 
- Go to https://eui.elastic.co/pr_7392/#/forms/selectable#truncation
- Browser QA
~- [ ] If applicable, added the **breaking change** issue label (and filled out the …
=> [EuiSelectable] Fix text truncation when a scrollbar is present

catalog-info.yaml, package.json, scripts/release.js, scripts/tests/update-versions-log.test.js, scripts/update-changelog.js, scripts/update-token-changelog.js, scripts/update-versions-log.js, wiki/eui-team-processes/releasing-versions.md
- Adds scripts specifically for backport and prerelease releases
- Updates the `release` script to handle the above special release
- Adds regex filter to our `eui-release-deploy-docs` job so we do not deploy the main docs site for backports or release candidates (backports will now be `vx.x.x-backport.0` instead of patches)
QA will be done manually in Buildkite. We'll verify the release docs job doesn't run when `backport` or `rc` branches are tagged.
=> Better backport and prerelease DX

scripts/deploy/deploy_docs, wiki/eui-team-processes/releasing-versions.md
PR adds conditional logic to our `deploy_docs` shell script to listen for `DEPLOY_ROOT` env variable. If this variable is added to the release deploy docs job, it will trigger the build without pushing a new tag / release. PR closes #7396.
Manually triggering the job assumes two key pieces of information:
1. The job will be run against the `main` branch. Selected by default in Buildkite UI.
2. The job will be run against the `HEAD` commit on main. Selected by default in Buildkite UI.
QA will be done in two parts, all in Buildkite:
=> [CHORE] Adding env var to trigger docs deploy manually from Buildkite UI

scripts/deploy/build_docs, scripts/deploy/deploy_docs, website/docusaurus.config.ts
This PR resolves #7402 by updating `build_docs` and `deploy_docs` to build the new docs site and deploy it under `new-docs` directory.
=> build: deploy new docs

src-docs/src/views/list_group/list_group_example.js
=> Fix #7412: Add missing closing quotes on line 110 of `src-docs\src\views\list_group\list_group_example.js`.

src-docs/src/views/breadcrumbs/breadcrumbs_example.js, src-docs/src/views/tabs/tabs_example.js, src-docs/src/views/tabs/tabs_guidance.js
We made some decisions about the `EuiBreadcrumbs` component in a [design discussion](https://github.com/elastic/eui/discussions/7345) in before UX Summit. One of the recommended actions was to document best practices for using tabs, based on my [comment about tabs updating breadcrumb links](https://github.com/elastic/eui/discussions/7345#discussioncomment-7567709).
This PR adds a `Guidelines` tab to `EuiTabs` and cross-links the new guidance from our `EuiBreadcrumbs` page. Screenshots attached below QA criteria. PR closes #7367.
- Browser QA
- Docs site QA
=> [DOCS] Add guidance for `EuiTabs` around higher-order navigation

src-docs/src/views/flex/flex_example.js
Thanks to @julianrosado for pointing out that our flex documentation randomly had the `wrap` example in the middle of the justify/align examples! 
- https://eui.elastic.co/pr_7414/#/layout/flex#justify-and-align
N/A, docs only
=> [docs][EuiFlexGroup] Fix example order/organization

src-docs/src/views/datagrid/basics/datagrid.js, src-docs/src/views/datagrid/schema_columns/footer_row.js, src-docs/src/views/list_group/list_group_example.js
closes https://github.com/elastic/eui/issues/7418
=> Fix #7418: Two instances of incorrect 2nd parseFloat parameter

changelogs/upcoming/7427.md, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/data_grid_body_custom.spec.tsx, src/components/datagrid/body/header/__snapshots__/data_grid_header_cell.test.tsx.snap, src/components/datagrid/body/header/data_grid_header_cell.tsx
Follow up to #7371 - several Kibana E2E tests were clicking the `data-test-subj` previously attached to the SVG icon, which is creating interactivity errors in Selenium/Cypress etc. due to the icon now only being visible on hover/focus (https://github.com/elastic/kibana/pull/173569).
This PR moves the `data-test-subj` to the parent `<button>` instead of the SVG icon, for easier hooking/clickability.
=> [EuiDataGrid] Move `dataGridHeaderCellActionButton` data-test-subj hook to button

changelogs/upcoming/7428.md, src-docs/src/views/tables/actions/actions.tsx, src-docs/src/views/tables/actions/actions_section.js, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/basic_table/collapsed_item_actions.test.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/expanded_item_actions.test.tsx, src/components/basic_table/expanded_item_actions.tsx
#7361 / #7373 regressed this UX (I think either during the conversion from a class to a function component, or when I was fixing the broken keyboard/hover visibility), and wasn't caught during QA mostly because the intended UX was both completely undocumented and untested 🥲 which should have been fixed in this PR.
| ![before](https://github.com/elastic/eui/assets/549407/e3fb827c-c502-4d20-9486-c35990eaa1e7) | ![after](https://github.com/elastic/eui/assets/549407/2b25aa39-6b3b-40dd-956e-5aef0894cb80) | 
| See https://eui.elastic.co/v91.2.0/#/tabular-content/tables#adding-actions-to-table for the regressed UX | See https://eui.elastic.co/v90.0.0/#/tabular-content/tables#adding-actions-to-table for the previous non-regressed UX |
- Go to …
=> [EuiBasicTable] Fix regressed disabled actions UX when selecting rows

changelogs/upcoming/7340.md, src-docs/src/views/theme/color/_contrast_js.tsx, src-docs/src/views/theme/color/_contrast_sass.tsx, src/components/basic_table/action_types.ts, src/components/basic_table/basic_table.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/default_item_action.tsx, src/components/basic_table/expanded_item_actions.tsx, src/components/basic_table/in_memory_table.tsx, src/components/basic_table/table_types.ts, src/components/common.ts, src/components/markdown_editor/markdown_editor.tsx, src/components/page_template/bottom_bar/page_bottom_bar.tsx, src/components/search_bar/query/date_format.ts, src/components/search_bar/query/execute_ast.ts, src/components/search_bar/query/query.ts, src/components/selectable/selectable_list/selectable_list_item.tsx, src/components/side_nav/side_nav.tsx, src/components/table/table_row_cell.tsx, src/components/tree_view/tree_view.tsx, src/services/sort/comparators.ts, src/utils/prop_types/is.ts
This PR adds the code changes needed for TypeScript v5 to work with EUI and not report any type errors.
I'm not upgrading to `typescript` version 5 here. It requires additional work to get `prop-loader.js` updated to use the new compiler API and will be added in a separate PR.
- Docs site QA
=> feat: TypeScript v5 prep work

changelogs/upcoming/7442.md, src-docs/src/views/range/range.tsx, src/components/form/range/__snapshots__/dual_range.test.tsx.snap, src/components/form/range/dual_range.test.tsx, src/components/form/range/dual_range.tsx, src/components/form/range/range.spec.tsx, src/components/form/range/range.tsx, src/components/form/range/range_slider.tsx
closes https://github.com/elastic/eui/issues/6846
This PR adds a resize observer to both **EuiRange** and **EuiDualRange** components, instead of only obtaining the `trackWidth`/`rangeWidth` on ref mount. TBH, I probably should have taken this approach in #7305 in the first place, as it allows us to simplify a good chunk of logic in **EuiDualRange**
| ![before_accordion](https://github.com/elastic/eui/assets/549407/75e8eed3-4ac5-4387-a8b6-154af9f44991) | ![after_accordion](https://github.com/elastic/eui/assets/549407/a8cd95be-f3f2-4bee-99ed-6e7b7b4d9d35) |
| ![before_fullwidth](https://github.com/elastic/eui/assets/549407/3fdbc27d-c8b4-4574-8000-25a766f1d748) | ![after_fullwidth](https://github.com/elastic/eui/assets/549407/fe3b1a7c-ca0a-40dd-9589-6db …
=> [EuiRange][EuiDualRange] Respond to resizing/layout changes

.buildkite/pipelines/pipeline_release.yml, catalog-info.yaml
This PR adds a new Backstage resource to handle the automatic EUI (pre)release process on merges to `main` and a placeholder Buildkite pipeline setup so that it can be tested safely using the `build/test-automatic-releases` branch.
Additional QA will be done manually by @tkajtoch after merging this PR to `main` and letting the changes propagate to Backstage and Buildkite.
=> build: add prerelease resource

changelogs/upcoming/7444.md, src/components/filter_group/__snapshots__/filter_button.test.tsx.snap, src/components/filter_group/filter_button.styles.ts, src/components/filter_group/filter_button.test.tsx, src/components/filter_group/filter_button.tsx, src/components/search_bar/__snapshots__/search_bar.test.tsx.snap, src/components/search_bar/__snapshots__/search_filters.test.tsx.snap, src/components/search_bar/filters/__snapshots__/field_value_toggle_filter.test.tsx.snap, src/components/search_bar/filters/__snapshots__/field_value_toggle_group_filter.test.tsx.snap, src/components/search_bar/filters/__snapshots__/is_filter.test.tsx.snap
In https://github.com/elastic/eui/pull/7369 / https://github.com/elastic/eui/pull/7369/commits/bb8cca07db55025c8076fbfc3127d09469ab8f14, I added the ability to disable `EuiButtonEmpty`'s text wrapper DOM node via `textProps={false}`.
Since `EuiFilterButton` already adds its own custom text wrapper `<span>` element, we can clean up/go down from two `<span>` text wrappers to just one, by using the above API.
- Go to https://eui.elastic.co/pr_7444/#/forms/filter-group
- Browser QA
- Docs site QA - N/A, tech debt
=> [EuiFilterButton] DOM text wrapper cleanup

changelogs/upcoming/7449.md, src-docs/src/views/form_controls/text_area.js, src/components/form/text_area/text_area.spec.tsx, src/components/form/text_area/text_area.tsx
Added text area clearable and icon options , motivation is to replace this custom implementation in widely used kibana component https://github.com/elastic/kibana/blob/main/src/plugins/unified_search/public/query_string_input/query_string_input.tsx#L860
when `invalid` and `isClearable` both props are provided, both icons overlaps each other. 
- Browser QA
- Docs site QA
- ~[ ] Updated …
=> [EuiTextArea] Add `isClearable` and `icon` props

changelogs/upcoming/7439.md, src-docs/src/views/flyout/flyout_example.js, src-docs/src/views/flyout/flyout_resizable.tsx, src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_beta.test.tsx.snap, src/components/flyout/flyout.tsx, src/components/flyout/flyout_resizable.spec.tsx, src/components/flyout/flyout_resizable.styles.ts, src/components/flyout/flyout_resizable.tsx, src/components/flyout/index.ts
closes https://github.com/elastic/eui/issues/287
- **API** - does adding a new `<EuiFlyoutResizable />` component (as opposed to, e.g. `<EuiFlyout resizable={true} />`) make sense? I leaned this way because it felt the cleanest in terms of implementation (as opposed to adding Yet More Code to the existing logic-heavy flyout file), but definitely would like to hear feedback on this.
- **UI/UX** - do we need more visual indicators or UI hints that the edge is resizable? Or does the existing appearance feel sufficient?
- **Documentation** - especially with our new focus on patterns, I would really like feedback on the copy I wrote. I cribbed text from the above issue on _why_ using resizable flyouts might be a good idea, but I think we should also consider adding some copy on when _not_ to …
=> [EuiFlyoutResizable] Add resizable flyout

packages/eslint-plugin/index.js, packages/eslint-plugin/rules/href_or_on_click.js
Relax the eslint rule `href-or-on-click` from `error` to `warn` because there are valid use cases for supplying both properties to navigation components.
=> Relax href-or-on-click rule to warning

website/docs/02_components/layout/flyout/overview.mdx
Add the new flyout docs (from #7439) to our new docs
=> [EuiFlyout] Add resizable flyout docs section copy

changelogs/upcoming/7452.md, src/components/tree_view/tree_view.tsx
#7340 made some type changes to EuiTreeView (adding `context` to the `constructor()` - [link](https://github.com/elastic/eui/pull/7340/files#diff-091725c0c3c4b9e1f82f2b5ae31d04ab61cf5be90f2404a86da17e6d90230d55)) that unfortunately broke the typing for the component in Kibana (https://github.com/elastic/kibana/pull/174487/commits/621cb79f45db71d17a0b1caf3d76b4e3b30239d3).
The error is also visible in EUI when viewing `tree_view.tsx` in VSCode, but doesn't come up in CLI linting for some reason:
Adding a `?` optional type to the `context` usage in `constructor()` appears to appease the JSX component instantiation error.
https://github.com/facebook/react/issues/13944#issuecomment-1183693239 implies that there is no production React 'fix' for this, since usage is deprecated, so this PR is …
=> [EuiTreeView] JSX Typescript error

src/components/collapsible_nav_beta/__snapshots__/collapsible_nav_body_footer.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_body_footer.styles.ts, src/components/collapsible_nav_beta/collapsible_nav_body_footer.tsx
I swear I saw and fixed this at some point, but apparently that was a holiday fever dream 🤦 
| <img width="297" alt="" src="https://github.com/elastic/eui/assets/549407/fc172969-17df-4bd4-92fb-f3f7211bd7ce"> | <img width="302" alt="" src="https://github.com/elastic/eui/assets/549407/02f58d74-7f7d-4a03-9dc5-06f2cd5a4c6f"> | 
This bug requires adding another div wrapper to work correctly (as `EuiFlyoutBody` currently does) because ✨ flex shenanigans ✨ 💀 
- https://eui.elastic.co/pr_7453/storybook/?path=/story/euicollapsiblenavbeta--kibana-example (compared against [production](https://eui.elastic.co/storybook/?path=/story/euicollapsiblenavbeta--kibana-example))
- Browser QA …
=> [EuiCollapsibleNavFooter] Fix broken flex/overflow height

src/components/accessibility/screen_reader_live/screen_reader_live.stories.tsx, src/components/accessibility/screen_reader_only/screen-reader_only.stories.tsx, src/components/accessibility/skip_link/skip_link.stories.tsx, src/components/accordion/accordion.stories.tsx, src/components/aspect_ratio/aspect_ratio.stories.tsx, src/components/aspect_ratio/aspect_ratio.test.tsx, src/components/aspect_ratio/aspect_ratio.tsx, src/components/auto_sizer/auto_sizer.stories.tsx, src/components/avatar/avatar.stories.tsx
Adds playground storybooks for all EUI components beginning with the letter A (+ accessibility components). Only 25 more letters to go!
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiaccordion--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiaspectratio--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiautosizer--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiavatar--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiscreenreaderlive--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiscreenreaderonly--playground
- https://eui.elastic.co/pr_7457/storybook/?path=/story/euiskiplink--playground
N/A, docs only
=> [Storybook] Add playground stories for components beginning with the letter A

changelogs/upcoming/7456.md, src/components/flyout/flyout_resizable.spec.tsx, src/components/flyout/flyout_resizable.tsx, src/components/resizable_container/helpers.ts, src/components/resizable_container/resizable_container.test.tsx, src/components/resizable_container/resizable_container.tsx
closes https://github.com/elastic/eui/issues/4931
This PR updates `EuiResizableContainer` to use window event listeners for `mouseup`/`mousemove`, which is also how **EuiFlyoutResizable** works (#7439). Event listeners are created on mousedown and removed on mouseup.
The net result is that users can now drag outside resizable containers and not have their drag event abruptly ended. IMO, this provides a user experience with less friction and matches many other drag/resize experiences around the web.
| ![resizable_container_drag_before](https://github.com/elastic/eui/assets/549407/6d6f5786-a0dc-4314-a0ed-ea4811ba9aef) [Production UX](https://eui.elastic.co/v92.0.0/#/layout/resizable-container) | …
=> [EuiResizableContainer] Mouse drags outside of the container no longer lose dragging state

changelogs/upcoming/7455.md, src-docs/src/views/resizable_container/resizable_button_indicator.tsx, src-docs/src/views/resizable_container/resizable_container_example.js, src/components/flyout/flyout_resizable.styles.ts, src/components/flyout/flyout_resizable.tsx, src/components/resizable_container/__snapshots__/resizable_button.test.tsx.snap, src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap, src/components/resizable_container/resizable_button.stories.tsx, src/components/resizable_container/resizable_button.styles.ts, src/components/resizable_container/resizable_button.test.tsx, src/components/resizable_container/resizable_button.tsx
closes https://github.com/elastic/eui/issues/7447
This PR updates `<EuiResizableButton />` to accept a `indicator={handle|border}` prop, which allows rendering either the default grab handle or a thin subdued border. It also updates `<EuiFlyoutResizable />` to use this new prop.
- https://eui.elastic.co/pr_7455/#/layout/resizable-container#resizable-button-indicator
- https://eui.elastic.co/pr_7455/storybook/?path=/story/euiresizablebutton--playground
- Browser QA
- Docs site QA
~- [ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui …
=> [EuiResizableButton] Add new `indicator` style prop

changelogs/upcoming/7465.md, src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_custom.test.tsx.snap, src/components/datagrid/body/__snapshots__/data_grid_body_virtualized.test.tsx.snap, src/components/datagrid/body/cell/__snapshots__/data_grid_cell.test.tsx.snap, src/components/datagrid/body/cell/data_grid_cell.test.tsx, src/components/datagrid/body/cell/data_grid_cell.tsx, src/components/datagrid/body/cell/data_grid_cell_popover.spec.tsx, src/components/datagrid/body/footer/data_grid_footer_row.spec.tsx, src/components/datagrid/data_grid.test.tsx, src/components/datagrid/data_grid_types.ts
Fixes datagrid performance issues caused by https://github.com/elastic/eui/pull/7448
This is particularly noticeable when comparing toggling between fullscreen and non-fullscreen mode:
- Worse perf: https://eui.elastic.co/v92.1.0/#/tabular-content/data-grid (noticeable tearing/ghosting in cell positions)
- Before refactor: https://eui.elastic.co/v92.0.0/#/tabular-content/data-grid
- Go to https://eui.elastic.co/pr_7465/#/tabular-content/data-grid#data-grid-adapts-to-its-container
- Browser QA
~- [ ] If applicable, added the **breaking change** issue label (and …
=> [EuiDataGrid] Fix cell performance

src/components/badge/badge.stories.tsx, src/components/badge/badge_group/badge_group.stories.tsx, src/components/badge/beta_badge/beta_badge.stories.tsx, src/components/badge/notification_badge/badge_notification.stories.tsx, src/components/beacon/beacon.stories.tsx, src/components/bottom_bar/bottom_bar.stories.tsx, src/components/bottom_bar/bottom_bar.tsx, src/components/breadcrumbs/breadcrumbs.stories.tsx, src/components/button/button.stories.tsx, src/components/button/button.tsx, src/components/button/button_display/_button_display.tsx, src/components/button/button_empty/button_empty.stories.tsx, src/components/button/button_empty/button_empty.tsx, src/components/button/button_group/button_group.tsx, src/components/button/button_icon/button_icon.tsx
> ⚠️ I skipped `EuiBasicTable` for this PR, as our tabular content components are heckin' complex and probably deserve their own dedicated PR where we consider what exactly we want out of those stories/embeds
Note: `EuiButton` had some shenanigans that required a type workaround (shouldn't affect actual end-types, will verify with the docs props table) to get Storybook to read extended types as controls. Everything else was straightforward.
I also DRYed out the `type` type (ha) for our button components in https://github.com/elastic/eui/pull/7459/commits/0bc375da5c540430b44c082d5e2a1f5a363a6d71, which was somewhat all over the place.
- https://eui.elastic.co/7459/storybook/?path=/story/euibadge--playground
- https://eui.elastic.co/7459/storybook/?path=/story/euibadgegroup--playground
- …
=> [Storybook] Add playground stories for components beginning with the letter B 

.storybook/manager-head.html, changelogs/upcoming/7460.md, src/components/call_out/call_out.stories.tsx, src/components/card/card.stories.tsx, src/components/card/checkable_card/checkable_card.stories.tsx, src/components/code/code.stories.tsx, src/components/code/code_block.stories.tsx, src/components/color_picker/color_palette_display/color_palette_display.stories.tsx, src/components/color_picker/color_palette_picker/color_palette_picker.stories.tsx, src/components/color_picker/color_picker.stories.tsx, src/components/color_picker/color_picker_swatch.stories.tsx, src/components/color_picker/index.ts, src/components/copy/copy.stories.tsx
There's a lot of C components, and some are fairly complex, so I decided to split this batch up into multiple PRs 🍪 
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicard--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicardcheckable--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicode--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicodeblock--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicolorpicker--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicolorswatch--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicolorpalettepicker--playground
- https://eui.elastic.co/pr_7460/storybook/?path=/story/euicolorpalettedisplay--playground
- …
=> [Storybook] Add playground stories for basic C components

changelogs/upcoming/7473.md, src-docs/src/views/form_controls/text_area.js, src/components/form/text_area/text_area.spec.tsx, src/components/form/text_area/text_area.tsx
@shahzad31 caught this when trying to implement the new `<EuiTextArea isClearable />` functionality in Kibana 🙏 I should have 1. written better tests and 2. followed the [existing **EuiFieldSearch** implementation](https://github.com/elastic/eui/blob/1e90096ea684223cbad134ba3fd250ba7960e7dc/src/components/form/field_search/field_search.tsx#L128-L154) more closely, as we need to call the prototype `.call()` after all (as opposed to setting `.value = ''`) in order for consumer `onChange` callbacks to correctly fire.
Both of the above are now fixed in this PR.
- Go to https://eui.elastic.co/pr_7473/#/forms/form-controls#textarea
- Click the `Display toggles` button, and toggle `clearable` to true
- Open your browser devtools to the console
- Type in a single character into the textarea, and …
=> [EuiTextArea] Fix consumer `onChange`s not firing on `isClearable` button click

changelogs/upcoming/7464.md, src-docs/src/views/flyout/flyout_resizable.tsx, src/components/flyout/flyout_resizable.spec.tsx, src/components/flyout/flyout_resizable.tsx
Per recent EUI feedback - adds an `onResize` callback where the latest flyout width is passed, which allows consumers to do things like, e.g. save user preference by storing the flyout width in `localStorage`
- Go to https://eui.elastic.co/pr_7464/#/layout/flyout#resizable-flyouts
- Open your browser devtools and go to the console
- Docs site QA
=> [EuiFlyoutResizable] Add optional `onResize` callback

changelogs/upcoming/7489.md, src-docs/src/views/context_menu/context_menu.js, src/components/context_menu/context_menu.stories.tsx, src/components/context_menu/context_menu.tsx, src/components/context_menu/context_menu_item.test.tsx, src/components/context_menu/context_menu_item.tsx
See https://github.com/elastic/eui/pull/7373 and our [deprecation schedule](https://github.com/elastic/eui/issues/1469).
Consumers should use `toolTipProps.title` and `toolTipProps.position` instead.
- Docs site QA
=> [EuIContextMenuItem] Remove deprecated `toolTipTitle` and `toolTipPosition` props

changelogs/upcoming/7488.md, src/components/popover/__snapshots__/popover.test.tsx.snap, src/components/popover/popover.test.tsx, src/components/popover/popover.tsx
See https://github.com/elastic/eui/pull/7311, and our [deprecation schedule](https://github.com/elastic/eui/issues/1469)
- Use `popoverRef` instead of `buttonRef`
- Use `className` instead of `anchorClassName`
- Docs site QA 
=> [EuiPopover] Deprecate `anchorClassName` and `buttonRef`

changelogs/upcoming/7495.md, src/components/text_truncate/text_truncate.test.tsx, src/components/text_truncate/text_truncate.tsx
The component could unmount before the timeout to mark the component as `ready` is resolved and update the state.
React has a specific error for this scenario, which is occurring in one of the consuming apps:
A defensive timer clean-up on the side effect removes the error and cleans the memory the timer uses.
- Browser QA
- ~[ ] If applicable, added the **breaking change** issue label (and filled out the breaking change checklist)~
=> [EuiTextTruncate] Fix timeout clean-up when component unmounts

changelogs/upcoming/7497.md, src/components/beacon/__snapshots__/beacon.test.tsx.snap, src/components/beacon/beacon.tsx, src/components/tour/__snapshots__/tour_step.test.tsx.snap, src/components/tour/_tour_footer.styles.ts, src/components/tour/_tour_footer.tsx, src/components/tour/_tour_header.styles.ts, src/components/tour/_tour_header.tsx, src/components/tour/tour.styles.ts, src/components/tour/tour_step.test.tsx, src/components/tour/tour_step.tsx
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7497/commits)!
- Applies EuiTourStep `className`s to the anchor element instead of to the popover panel
- This change was made to be consistent with `EuiPopover` behavior (consumers cannot otherwise apply styles to the anchor since we deprecated the  `anchorClassName` prop).
- Existing usages should be converted to `panelClassName` instead
- Applies EuiTourStep's `style` prop to the anchor element instead of to the popover panel
- Also for popover consistency. Existing usages should be converted to `panelStyle` instead.
- See also https://github.com/elastic/eui/pull/5897#discussion_r873837342 for previous discussion/confusion about this prop
- Converts all Enzyme tests for EuiTourStep to RTL and …
=> [EuiTourStep] `className` consistency with EuiPopover + performance/cleanups

src-docs/src/views/theme/color/_contrast_js.tsx, src-docs/src/views/theme/color/_contrast_sass.tsx, src-docs/src/views/theme/color/_contrast_slider.tsx, src-docs/src/views/theme/color/contrast.tsx, src-docs/src/views/theme/color/tokens.tsx
closes https://github.com/elastic/eui/issues/7500
The text color broke in #7298, as part of this changelog item:
> - Fixed `EuiListGroupItem` to pass `style` props to the wrapping `<li>` element alongside `className` and `css`. All other props will be passed to the underlying content.
The contrast page was passing `style` to EuiListGroupItem and relying it to go onto the `<button>` element instead of the `<li>`. This broken the inherited color styling of the various button(s).
While here I also noticed a whole lot of other things going wrong with this page (😅) and pushed up several fixes - see the [commit history](https://github.com/elastic/eui/pull/7506/commits).
- https://eui.elastic.co/pr_7506/#/theming/colors/contrast looks correct/non-broken compared to …
=> [docs] Fix Colors > Contrast docs page

changelogs/upcoming/7504.md, src-docs/src/views/super_date_picker/super_date_picker.tsx, src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap, src/components/date_picker/super_date_picker/date_popover/__snapshots__/date_popover_button.test.tsx.snap, src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx, src/components/date_picker/super_date_picker/super_date_picker.tsx
closes https://github.com/elastic/eui/issues/7503
- Go to https://eui.elastic.co/pr_7504/#/templates/super-date-picker, scroll down to the first example
- Browser QA
- Code quality checklist - I skipped this as I felt the fix was fairly straightforward in terms of native browser behavior+implementation, but if you strongly feel this needs a test, LMK
=> [EuiSuperDatePicker] Fix usage within `<form>`s

changelogs/upcoming/7510.md, src-docs/src/views/context_menu/context_menu_example.js, src-docs/src/views/context_menu/context_menu_with_content.js, src/components/context_menu/context_menu.stories.tsx, src/components/context_menu/context_menu.test.tsx, src/components/context_menu/context_menu.tsx
closes https://github.com/elastic/eui/issues/7507
Example usage:
```jsx
const CustomComponent = () => (
<div data-test-subj="custom">Hello world</div>
);
<EuiContextMenu
initialPanelId={1}
panels={[
{
id: 1,
title: 'Testing renderItem',
items: [
// Default context menu item
{
name: 'Renders an EuiContextMenuItem',
panel: 2,
},
// Custom items
{
renderItem: () => <h3>Subtitle</h3>,
},
{
key: 'custom',
renderItem: CustomComponent,
},
],
},
]}
/>
```
This API intentionally matches `EuiCollapsibleNavBeta.Item`'s API (see #7228 and https://github.com/elastic/kibana/issues/167326).
- Go to https://eui.elastic.co/pr_7510/#/navigation/context-menu#using-panels-with-mixed-items-content
- Browser QA
- Docs site QA
- ~[ ] Props have proper **autodocs** (using `@default` if default values are …
=> [EuiContextMenu] Support new `renderItem` custom content in `items` arrays

changelogs/upcoming/7513.md, src-docs/src/views/tree_view/playground.js, src/components/index.scss, src/components/tree_view/__snapshots__/tree_view.test.tsx.snap, src/components/tree_view/_index.scss, src/components/tree_view/_tree_view_item.styles.ts, src/components/tree_view/_tree_view_item.tsx, src/components/tree_view/tree_view.a11y.tsx, src/components/tree_view/tree_view.scss, src/components/tree_view/tree_view.spec.tsx, src/components/tree_view/tree_view.stories.tsx, src/components/tree_view/tree_view.styles.ts, src/components/tree_view/tree_view.test.tsx, src/components/tree_view/tree_view.tsx
closes https://github.com/elastic/eui/issues/6416
Opinionated changes as part of this conversion:
- Removes `.euiTreeView__wrapper` (unnecessary extra div wrapper)
- Icons are now better vertically aligned/centered with text, and a consistent `icon` width/height is now enforced based on `display`/compressed sizing
As always, I recommend [reviewing by commit](https://github.com/elastic/eui/pull/7513/commits).
https://github.com/elastic/kibana/blob/432a5d7734f127c321f75679be913a87bc3c71a6/x-pack/plugins/kubernetes_security/public/components/tree_view_container/dynamic_tree_view/index.tsx
The above is the highest-lift impact in Kibana that will need updating once this upgrade lands. They're apparently using the styles of EuiTreeView but not the actual component, which is partially why I …
=> [Emotion] Convert EuiTreeView

changelogs/upcoming/7516.md, src/components/date_picker/auto_refresh/auto_refresh.test.tsx, src/components/date_picker/auto_refresh/auto_refresh.tsx, src/components/date_picker/auto_refresh/refresh_interval.tsx, src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap, src/components/date_picker/super_date_picker/super_date_picker.tsx
closes #7512
This PR adds a `refreshMinInterval` prop to **EuiSuperDatePicker** and an `minInterval` prop to **EuiAutoRefresh** and **EuiRefreshInterval**, which primarily does the following:
- Adds a browser `min` property to the number input, which affects the stepper and shows an invalid state/icon if the user types in a value below that min
- Updates the `onRefreshChange` callback to never send back a `refreshInterval` value lower than than the passed `minInterval` value
- Go to https://eui.elastic.co/pr_7516/#/templates/super-date-picker
- Click the **Playground** button
- ctrl+f for and toggle the `isPaused` prop to false
- ctrl+f for and set the `refreshMinInterval` prop to, e.g. `20000`
- Docs site QA
- Designer …
=> [EuiSuperDatePicker][EuiAutoRefresh][EuiRefreshInterval] Allow setting a minimum interval in milliseconds

changelogs/upcoming/7525.md, src/components/page_template/page_template.tsx
Some SSR environments (e.g., Next.js) don't provide the `CSS` utilities object, and the currently used `CSS.escape` static function is undefined.
This PR replaces the `CSS.escape` usage with a regular string replace. The `useGeneratedHtmlId` uses `React.useId` that may return a string containing colons, and these will now be escaped with the `\` character.
- Browser QA
=> fix(EuiPageTemplate): replace `CSS.escape` usage with string replace to fix SSR support

src-docs/src/views/popover/popover_example.js, src-docs/src/views/tool_tip/tool_tip_example.js
Updated documentation for a11y callouts to use `info` styles in the `EuiTooltip` and `EuiPopover` components based on Cee's [suggestion from previous PR](https://github.com/elastic/eui/pull/7527#discussion_r1489782214). Screenshots attached at the bottom.
- Browser QA
- Docs site QA
---
---
=> [CHORE] Update Tooltip and Popover callouts to info style.

changelogs/upcoming/7529.md, src/components/beacon/beacon.tsx, src/components/code/code.styles.ts, src/components/code/code.tsx, src/components/code/code_block.styles.ts, src/components/code/code_block.tsx, src/components/code/code_block_controls.styles.ts, src/components/code/code_block_controls.tsx, src/components/code/code_block_full_screen.tsx, src/components/code/code_syntax.styles.ts, src/services/theme/index.ts, src/services/theme/provider.tsx, src/services/theme/style_memoization.test.tsx, src/services/theme/style_memoization.tsx
> ⚠️ As always, I strongly recommend [reviewing by commit](https://github.com/elastic/eui/pull/7529/commits).
This PR is an initial setup PR for memoizing a component's Emotion styles **per theme** (instead of **per component**). This should (hopefully) greatly improve the performance of our Emotion styles/object generation, especially for components used repeatedly in many places, e.g. EuiCode, EuiButton, etc.
I replaced the memoization used in #7486 with this new architecture as a proof of concept; this PR should maintain the performance improvements of the linked PR while being easy to swap in and replace across all of EUI's existing components, e.g.
```ts
const euiTheme = useEuiTheme();
const styles = euiComponentStyles(euiTheme);
// becomes
const styles = …
```
=> [Emotion] Create hook utility for memoizing component styles per-theme

changelogs/upcoming/7534.md, src/components/datagrid/utils/grid_height_width.ts
The component could unmount before the timeout to set the virtualized `clientWidth` update the state.
React has a specific error for this scenario, which is occurring in one of the consuming apps:
**Console screen**
**Reproduction**
https://github.com/elastic/eui/assets/34506779/b3cac963-ca90-40ae-84fd-4eadaebae483
A defensive timer clean-up on the side effect removes the error and cleans the memory the timer uses.
- Browser QA
- ~[ ] If applicable, added the **breaking change** issue label (and filled out the breaking change checklist)~
=> [EuiDataGrid] Fix timeout clean-up when component unmounts

changelogs/upcoming/7538.md, src/components/progress/progress.styles.ts
closes https://github.com/elastic/eui/issues/7523
I missed a template literal while converting the component from Sass to Emotion (#5986) 🤦 Also I never noticed this because I work primarily in Firefox and apparently [progress animations have never worked in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=662351) 😭 
In a webkit browser:
- [On production](https://eui.elastic.co/v93.1.0/#/display/progress#progress-with-values), and click `Toggle Progress` - it should not animate smoothly (compared to [pre-Emotion conversion](https://eui.elastic.co/v37.0.0/#/display/progress#progress-with-values))
- [Go to staging](https://eui.elastic.co/pr_7538/#/display/progress#progress-with-values) and click `Toggle Progress`
- Open your System settings and check the `Reduce motion` option under …
=> [EuiProgress] Fix broken transition CSS

src/components/button/button_display/_button_display.tsx, src/components/button/button_empty/button_empty.tsx, src/components/button/button_group/button_group.styles.ts, src/components/button/button_group/button_group.tsx, src/components/button/button_icon/button_icon.styles.ts, src/components/button/button_icon/button_icon.tsx, src/themes/amsterdam/global_styling/mixins/__snapshots__/button.test.ts.snap, src/themes/amsterdam/global_styling/mixins/button.test.ts, src/themes/amsterdam/global_styling/mixins/button.ts
This PR is a performance enhancement (+ one missing Emotion animation conversion) on the `EuiButton` component(s) and should not regress or change any output UI or generated classNames.
As always, I recommend [code reviewing by commit](https://github.com/elastic/eui/pull/7541/commits).
- Go to https://eui.elastic.co/pr_7541/#/navigation/button
- Browser QA
- ~[ ] A **[changelog](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/changelogs.md)** entry exists and is marked appropriately.~ - Skipping the changelog on these PRs as they shouldn't affect either end-users or consumers
=> [Emotion][perf] Memoize `EuiButton` styles & mixins

changelogs/upcoming/7549.md, src-docs/src/views/datagrid/styling/row_classes.js, src/components/datagrid/_data_grid_data_row.scss, src/components/datagrid/body/data_grid_row_manager.ts
closes https://github.com/elastic/eui/issues/7548 (fix is in first commit, other commits are bonus/cleanup)
This bug primarily affects our docs example, and likely has very minimal impact on consumers (given that it's unlikely that they're naming their own custom `className`s with `.euiDataGridRow`).
**Reproducing the bug**
- Go to https://eui.elastic.co/pr_/#/tabular-content/data-grid-style-display#grid-row-classes
- Select any row, and then unselect it
- The highlight CSS is not removed when it should be
**QAing the fix** 
- Go to https://eui.elastic.co/pr_7549/#/tabular-content/data-grid-style-display#grid-row-classes
- Select any row and then unselect it
- Browser QA
- …
=> [EuiDataGrid] Fix "Grid row classes" docs example

changelogs/upcoming/7555.md, src-docs/src/views/breadcrumbs/breadcrumbs_example.js, src-docs/src/views/breadcrumbs/popover_content.tsx, src/components/breadcrumbs/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumbs/breadcrumb.test.tsx, src/components/breadcrumbs/breadcrumb.tsx
@sebelga pinged me with the request for serverless nav work to be given the ability to optionally control EUI's breadcrumb popover state. His use case is for consumer popover content that does something/takes the user somewhere and then closes the popover, e.g.
The approach I decided to take here was to allow `popoverContent` to be a render function that passes the `closePopover` callback to consumers. Example usage:
```tsx
<EuiBreadcrumbs
breadcrumbs={[
{
text: 'My deployment',
popoverContent: (closePopover) => (
<EuiButtonEmpty
onClick={() => {
goSomewhere();
closePopover();
}}
>
Go to some deployment
</EuiButtonEmpty>
),
},
{ text: 'Another breadcrumb' },
]}
/>
```
I'm open to feedback as to whether we think this is the best approach in terms of giving consumers more flexibility vs …
=> [EuiBreadcrumb] Allow popover content to close the breadcrumb popover

src/components/header/header_breadcrumbs/header_breadcrumbs.stories.tsx, src/components/header/header_links/header_link.stories.tsx, src/components/health/health.stories.tsx, src/components/highlight/highlight.stories.tsx, src/components/horizontal_rule/horizontal_rule.stories.tsx, src/components/responsive/hide_for.stories.tsx
closes #7478 
This PR adds "Playground" stories for the following components:
* EuiHeaderBreadcrumbs
* EuiHeaderLink
* EuiHealth
* EuiHighlight
* EuiHorizontalRule
* EuiHideFor
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euiheaderbreadcrumbs--playground
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euiheaderlink--playground
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euihealth--playground
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euihighlight--playground
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euihorizontalrule--playground
- https://eui.elastic.co/pr_7553/storybook/index.html?path=/story/euihidefor--playground
=> [Storybook] Add Playground stories for components with letter H

src-docs/src/views/theme/typography/_text_numbers.tsx, src/components/facet/facet_button.styles.ts, src/components/link/external_link_icon.tsx, src/components/link/link.styles.ts, src/components/link/link.tsx, src/components/text/text.tsx, src/components/text/text_align.styles.ts, src/components/text/text_align.tsx, src/components/text/text_color.tsx, src/components/title/title.styles.test.ts, src/components/title/title.styles.ts, src/components/title/title.tsx, src/global_styling/mixins/_typography.test.ts, src/global_styling/mixins/_typography.ts
This PR is a performance enhancement (+ opinionated removals of several unused CSS functions that were exported from component style files only and not as top-level APIs) on `EuiText`, `EuiTitle`, and `EuiLink` components (+ typography mixins).
No UI or classNames should have changed/regressed as part of this PR.
As always, I recommend [code reviewing by commit](https://github.com/elastic/eui/pull/7543/commits).
- Browser QA
- ~[ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testin …
=> [Emotion] Memoize typography styles & mixins

src/components/icon/icon.styles.ts, src/components/icon/icon.tsx, src/services/theme/index.ts, src/services/theme/style_memoization.test.tsx, src/services/theme/style_memoization.tsx
This PR is a performance enhancement (+ minor code cleanup) on the `EuiIcon` component, and should not regress or change any output UI or generated classNames.
As always, I recommend [code reviewing by commit](https://github.com/elastic/eui/pull/7544/commits).
- https://eui.elastic.co/pr_7544/#/display/icons looks the same as [production](https://eui.elastic.co/#/display/icons)
- Browser QA
- ~[ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/cypress-testing.md) tests**~ Should be fine if tests pass
- Release checklist - N/A
- ~[ ] A …
=> [Emotion] Add HOC util for memoized styles + memoize `EuiIcon` styles

src/components/skeleton/skeleton_circle.tsx, src/components/skeleton/skeleton_rectangle.tsx, src/components/skeleton/skeleton_text.tsx, src/components/skeleton/skeleton_title.tsx
Pulled out the original work/impetus from Kevin's PR (#7374) for PR atomic-ness and also because it dovetails nicely into our existing Emotion perf/memoization work (see #7561)
- Browser QA
- Release checklist - Skipping as this should not impact consumers or end users
=> [Emotion] Memoize `EuiSkeleton` components

changelogs/upcoming/7568.md, src/components/toast/__snapshots__/global_toast_list.test.tsx.snap, src/components/toast/__snapshots__/toast.test.tsx.snap, src/components/toast/global_toast_list.tsx, src/components/toast/toast.styles.ts, src/components/toast/toast.tsx
closes #7566
| <img width="597" alt="" src="https://github.com/elastic/eui/assets/549407/09619f3e-c5ba-4e98-a50b-3c597256d754"> | <img width="586" alt="" src="https://github.com/elastic/eui/assets/549407/5bc44b80-1550-4a45-9ef2-a1bc34a21173"> | 
I recommend [reviewing by commit](https://github.com/elastic/eui/pull/7568/commits) and hiding whitespace changes as there's a good deal of perf optimizations in this PR as well.
- Go to https://eui.elastic.co/pr_7568/#/display/toast/guidelines
- Browser QA
- Docs site QA - N/A for this PR, copy team will revisit [toast …
=> [EuiToast] Wrap overflowing text in titles + perf optimizations

changelogs/upcoming/7575.md, src/components/observer/resize_observer/resize_observer.tsx
See @davismcphee's comment in https://github.com/elastic/eui/pull/7462#issuecomment-1977616140:
> It looks like `useResizeObserver` relies on `getBoundingClientRect` because `contentRect` only provides the content sizing for elements instead of box sizing:
https://github.com/elastic/eui/blob/635f860520e8cd981175438748705f27a51eb0ac/src/components/observer/resize_observer/resize_observer.tsx#L106-L109
> But I assume this code is old and isn't actually needed anymore since [`ResizeObserverEntry`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry) now supports [`borderBoxSize`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/borderBoxSize) to access box sizing.
This is definitely a refactor/perf improvement we want across the board in our resize …
=> [EuiResizeObserver] Remove reflow/`getBoundingClientRect()` usage on resize

.github/workflows/community_contribution.yml
We had an automated PR submitted earlier that didn't present the community contribution message. Looking through the logs I deduced it was related to the URL structure including a bracket. I updated the `curl` command to remediate the issue.
https://curl.se/docs/manpage.html#-g
PR closes #7573.
I recreated the `curl` command locally, created a single-use token, and hardcoded the URL we were looking to validate. The test returned the correct data after adding the `-g` flag. I tested for negative and affirmative org membership.
Will retest with my QA account after PR merges to confirm the community message has not had any regression.
=> [BUG] Fixed community GHA curl command.

changelogs/upcoming/7580.md, src/components/breadcrumbs/__snapshots__/_breadcrumb_content.test.tsx.snap, src/components/breadcrumbs/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap, src/components/breadcrumbs/_breadcrumb_content.styles.ts, src/components/breadcrumbs/_breadcrumb_content.test.tsx, src/components/breadcrumbs/_breadcrumb_content.tsx, src/components/breadcrumbs/breadcrumb.styles.ts, src/components/breadcrumbs/breadcrumb.test.tsx, src/components/breadcrumbs/breadcrumb.tsx, src/components/breadcrumbs/breadcrumbs.stories.tsx, src/components/breadcrumbs/breadcrumbs.tsx, src/components/breadcrumbs/index.ts, src/components/breadcrumbs/types.ts, src/components/header/__snapshots__/header.test.tsx.snap, src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap, src/components/header/header_breadcrumbs/header_breadcrumbs.tsx
closes https://github.com/elastic/eui/issues/7577
| <img width="323" alt="" src="https://github.com/elastic/eui/assets/549407/453c9855-67bd-4e9d-a7da-ee5d7c0f43e6"> | <img width="328" alt="" src="https://github.com/elastic/eui/assets/549407/e39eeb75-197f-4a2f-a862-a23334cf0239"> |
The underlying fix is to separate out the breadcrumb CSS from the truncation CSS and passing them to separate DOM elements for breadcrumbs with popovers. The final diff is a bit hard to follow because I ended up just pulling out breadcrumbs with popovers to a separate subcomponent, apologies for that 😬 
- Go to https://eui.elastic.co/pr_7580/storybook/?path=/story/navigation-euibreadcrumbs--playground&args=type:application
- Change the `max` control to `2`
- Expand the …
=> [EuiBreadcrumb] Fix styling on `application` types with popovers + perf improvements

src-docs/src/components/guide_theme_selector/guide_theme_selector.tsx
closes https://github.com/elastic/eui/issues/7588
Removes this popover/beacon:
- Go to https://eui.elastic.co/pr_7595/
- Clear your site cookies/local storage data
N/A, docs only
=> [Docs] Remove tour beacon/notification notifcation about Amsterdam theme

changelogs/upcoming/7603.md, src-docs/src/views/header/header_links.tsx, src/components/header/header_links/__snapshots__/header_links.test.tsx.snap, src/components/header/header_links/header_links.test.tsx, src/components/header/header_links/header_links.tsx
closes #7587
Utilizes the same API/structure as #7555 - consumers can use a render function to which a `closePopover` callback will be passed, allowing them to fully control which link(s) and interactions in their `EuiHeaderLinks` close the mobile popover and which don't.
- Go to https://eui.elastic.co/pr_7603/#/layout/header#header-links
- Reduce your window screen to mobile/tablet
- Click the menu icon to see the header links
- Docs site QA
=> [EuiHeaderLinks] Allow consumers to close the mobile popover from within the popover content

changelogs/upcoming/7606.md, src/components/icon/icon.test.tsx, src/components/icon/icon.tsx, src/components/tool_tip/icon_tip.tsx
closes #7400
Empty and loading icons can still have perfectly valid `aria-label` attributes that should be made available to screen reader users and not hidden - we should not apply `aria-hidden` unless there is no meaningful text to read out.
| <img width="612" alt="" src="https://github.com/elastic/eui/assets/549407/c9162a21-8ee4-455e-878f-a7a0b86d88d6"> | <img width="624" alt="" src="https://github.com/elastic/eui/assets/549407/70b0ef27-8ffd-45a9-9e9e-db647bbaef7d"> | 
I also noticed while here that `EuiIconTip`'s default aria-label isn't correctly `i18n`ed, and can be bypassed by consumers passing an empty string, so I tweaked both of those things while here.
To QA `EuiIconTip` specifically:
- `gh pr checkout 7606`
- Open …
=> [EuiIcon] Remove logic that applies `aria-hidden` to empty/loading icons; [EuiIconTip] Fix non-i18n'd default `aria-label`

src-docs/src/views/code/code_example.js
Thanks to @julianrosado for pointing this out!
- Go to https://eui.elastic.co/pr_7608/#/editors-syntax/code
N/A, docs only
=> [docs][EuiCode] Fix moved Kibana repo link

changelogs/upcoming/7607.md, src/components/form/text_area/_text_area.scss
@yansavitski super awesomely pointed out to us in Slack that `inline-block` displays produce [struts](http://www.w3.org/TR/CSS2/visudet.html#strut), which make room for descenders, hence the extra 2-3px. [Another helpful comment from StackOverflow](https://stackoverflow.com/a/27536461/4294462):
> The default `vertical-align` is to have the bottom edge of the `inline-block` box lined up with the baseline of the surrounding text. Even if there is no surrounding text, the layout engine still has to make room for an entire line of text.
Setting `vertical-align: top` works for Chrome but not for Firefox. Since our textarea component doesn't need descender logic at all, or inline behavior (since it's already wrapped in a `<div>` form control wrapper), the easiest solution is to simply set …
=> [EuiTextArea] Fix extra 2-3px of height caused by `display: inline-block`

changelogs/upcoming/7609.md, src-docs/src/views/selectable/selectable_example.js, src/components/selectable/selectable.spec.tsx, src/components/selectable/selectable_list/__snapshots__/selectable_list.test.tsx.snap, src/components/selectable/selectable_list/_selectable_list.scss, src/components/selectable/selectable_list/selectable_list.test.tsx, src/components/selectable/selectable_list/selectable_list.tsx
@jeramysoucy pointed out this missing functionality/feature request in the ability to turn off virtualization in `EuiSelectable` - it should continue to support scrolling as necessary. This is fairly trivial for EUI to do and it's not totally clear to me why it wasn't implemented in the first place when `isVirtualized={false}` was added as a prop, so I've gone ahead and added support for that in this PR.
| <img width="423" alt="screenshot" src="https://github.com/elastic/eui/assets/549407/b11e6cae-8193-44fb-8696-1b8b760f74fc"> | <img width="427" alt="screenshot" src="https://github.com/elastic/eui/assets/549407/d36aa018-9306-4b6d-a119-14363c91d48d"> | 
- Go to https://eui.elastic.co/pr_7609/#/forms/selectable#rendering-the-options
- Switch the …
=> [EuiSelectable] Support scrolling in non-virtualized lists

changelogs/upcoming/7618.md, src/components/selectable/selectable_list/selectable_list.tsx
This is happening on `activeOptionIndex` change only. jsdom doesn't support or stub `scrollIntoView` (and we don't need it to be called in Jest tests) so adding a conditional check for it fixes several Kibana Jest failures:
- https://github.com/elastic/kibana/pull/179363#issuecomment-2018584834
- https://github.com/jsdom/jsdom/issues/1695
N/A, tests only
- ~[ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/cypress-testing.md) tests**~ Skipping this to speed up the patch/upgrade process, unless someone thinks it's really important to do
~- [ ] If …
=> [EuiSelectable] Fix non-virtualized lists causing Jest errors

src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.tsx, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/table.styles.ts, src/components/table/table.tsx
Basic setup PR, nothing too fancy going on here (_yet_, see the fun TODO message ✨)
⚠️ Class name removals that may affect consumers (but no usages in Kibana):
- `.euiTable--auto`
- `.euiTable--compressed`
- Browser QA
- Release checklist - Skipping the Emotion changelog until the final feature branch, probably
=> [EuiTable] Initial table styles setup

changelogs/upcoming/7625.md, src-docs/src/views/provider/provider_component_defaults.tsx, src-docs/src/views/tables/mobile/mobile.tsx, src-docs/src/views/tables/mobile/mobile_section.js, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.tsx, src/components/basic_table/in_memory_table.test.tsx, src/components/provider/component_defaults/component_defaults.tsx, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/_index.scss, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/mobile/__snapshots__/table_header_mobile.test.tsx.snap, src/components/table/mobile/__snapshots__/table_sort_mobile.test.tsx.snap, src/components/table/mobile/_index.scss, src/components/table/mobile/_mobile.scss, src/components/table/mobile/responsive_context.ts, src/components/table/mobile/table_header_mobile.styles.ts, src/components/table/mobile/table_header_mobile.test.tsx, src/components/table/mobile/table_header_mobile.tsx, src/components/table/mobile/table_sort_mobile.tsx, src/components/table/table.styles.ts, src/components/table/table.test.tsx, src/components/table/table.tsx, src/components/table/table_row_cell.tsx
This PR sets up a new `responsiveBreakpoint` prop for all table components (`EuiTable`, `EuiBasicTable`, and `EuiInMemoryTable` that allows consumers to customize the breakpoint at which tables collapse, and also cascades the dynamic responsive/mobile state down to all child cells/rows via context.
This PR only **very minimally** converts Sass responsive styles to Emotion - it's primarily just set up and JS proof-of-concept for now to help make PR review more bite-sized.
ℹ️ The line diff #s look, scary but it's 80% indentation from snapshots - make sure you [view with whitespace changes off](https://github.com/elastic/eui/pull/7625/files?diff=split&w=1). As always, I also strongly recommend [reviewing by …
=> [EuiTable] New `responsiveBreakpoint` prop + initial setup for mobile vs desktop styles

.storybook/preview.tsx, changelogs/upcoming/7626.md, src-docs/src/views/app_context.js, src/services/theme/style_memoization.test.tsx, src/services/theme/style_memoization.tsx
The catch I added in https://github.com/elastic/eui/pull/7529#discussion_r1489868842 has backfired, in that it's producing a false negative on staging (but not local??) in https://github.com/elastic/eui/pull/7625#pullrequestreview-1962844728.
To work around prod false negatives but preserve the intended goal of catching anonymous style functions in development, I'm tweaking the thrown error to use our internal EUI provider warning utility, which allows us (and consumers) to configure the warning level used. In this case, I'm setting it to `error` for local docs dev and for storybook, but to just `warn` for staging/prod.
As always, I recommend [following along by commit](https://github.com/elastic/eui/pull/7626/commits).
I think QA is already pretty well covered by our tests, so IMO a …
=> [Emotion] Allow configuring style memoization error/warning level

changelogs/upcoming/TBD.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/__snapshots__/table_row.test.tsx.snap, src/components/table/_mixins.scss, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/_variables.scss, src/components/table/table.styles.ts, src/components/table/table_row.stories.tsx, src/components/table/table_row.styles.ts, src/components/table/table_row.tsx, src/components/table/table_row_cell.tsx
This doesn't convert _all_ table row styles to Emotion, but it converts (what I consider) to be the majority of row-related CSS (enough to get a mostly functional Storybook up). There are still some styles that I consider belong to cells, rather than rows, which I will target in the next cell-focused PR.
As mentioned in #7625, staging itself will still look broken until _all_ CSS is converted over (at which point I'll do another prod vs staging QA pass and also hopefully have more Storybooks written by then for easier QA).
⚠️ Removals/changes that will affect consumers (checked for zero usages in Kibana):
-  Removed Sass `@euiTableActionsBackgroundMobile` mixin
-  Removed Sass `$euiTableActionsBorderColor` variable (+ updated mobile usages to use the theme-wide border color token, …
=> [EuiTableRow] Convert to Emotion

changelogs/upcoming/7631.md, changelogs/upcoming/TBD.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/__snapshots__/table_footer_cell.test.tsx.snap, src/components/table/__snapshots__/table_header_cell.test.tsx.snap, src/components/table/__snapshots__/table_header_cell_checkbox.test.tsx.snap, src/components/table/__snapshots__/table_row.test.tsx.snap, src/components/table/__snapshots__/table_row_cell.test.tsx.snap, src/components/table/__snapshots__/table_row_cell_checkbox.test.tsx.snap, src/components/table/_index.scss, src/components/table/_mixins.scss, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/table.styles.ts, src/components/table/table_cells_shared.styles.ts, src/components/table/table_footer_cell.tsx, src/components/table/table_header_cell.tsx, src/components/table/table_header_cell_checkbox.tsx, src/components/table/table_row.styles.ts, src/components/table/table_row.tsx, src/components/table/table_row_cell.styles.ts, src/components/table/table_row_cell.tsx, src/components/table/table_row_cell_checkbox.tsx
- Converts the following components to Emotion:
- EuiTableRowCell
- EuiTableHeaderCell
- EuiTableFooterCell
- EuiTableRowCellCheckbox
- EuiTableHeaderCellCheckbox
- Does **not** convert `.euiTableCellContent` to Emotion because that is going to be its own large PR - I plan on very judiciously refactoring the heck out of that 😅 
As always, this is a lot, and there was a lot of CSS cleanups that happened, so I recommend [following along by commit](https://github.com/elastic/eui/pull/7631/commits)!
- Sass mixin removals: `euiTableCell` and `euiTableCellCheckbox` (**no usages**)
- DOM `className` changes (1065b0b): (**4 usages to manually QA during the upgrade**):
- …
=> Convert cell styles to Emotion (row cells, header/footer cells, & cell checkboxes)

changelogs/upcoming/7625.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.tsx, src/components/basic_table/in_memory_table.tsx, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/table.tsx
I figured since we're already breaking/removing table props in #7632 and we're going to have to update a bunch of Kibana usages anyway, I should go ahead and just remove the `responsive` prop entirely that was only deprecated in #7625.
Typescript will help us catch most of these, but here's a quick list from searching (~10 found instances):
- [basic/memory tables, `responsive={false}`](https://github.com/search?q=repo%3Aelastic%2Fkibana+EuiBasicTable+EuiInMemoryTable+%22responsive%3D%7Bfalse%7D%22&type=code)
QA will not look entirely correct until all Sass styles have been converted to Emotion. Also, QA should have already occurred as part of #7625 / will have another pass in the final feature branch
- …
=> [EuiTable][EuiBasicTable][EuiInMemoryTable] Remove `responsive` prop completely in favor of `responsiveBreakpoint`

changelogs/upcoming/7632.md, changelogs/upcoming/TBD.md, src-docs/src/views/tables/actions/actions.tsx, src-docs/src/views/tables/custom/custom.tsx, src-docs/src/views/tables/expanding_rows/expanding_rows.tsx, src-docs/src/views/tables/footer/footer.tsx, src-docs/src/views/tables/in_memory/in_memory_selection_controlled.tsx, src-docs/src/views/tables/in_memory/in_memory_selection_uncontrolled.tsx, src-docs/src/views/tables/mobile/mobile.tsx, src-docs/src/views/tables/mobile/mobile_section.js, src-docs/src/views/tables/selection/selection_controlled.tsx, src-docs/src/views/tables/selection/selection_uncontrolled.tsx, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/basic_table/in_memory_table.tsx, src/components/table/_index.scss, src/components/table/_table.scss, src/components/table/_variables.scss, src/components/table/table_row.styles.ts, src/components/table/table_row.tsx
Removes 3 props for basic/memory tables that were apparently literally just there to make styling works on responsive - this isn't an API we really want to perpetuate and we have all the information we need without consumers having to pass extra props, so I'm just going to yeet them out as part of the Emotion conversion.
also closes #7515 while here (adds a new `hasSelection` prop to EuiTableRow that replaces `isSelectable`, and only passes `isSelectable` if the selection checkbox is not disabled).
Typescript will help us catch most of these, but here's a quick list from searches (there are many pages, but it should at least be quick removals):
- [isSelectable](https://github.com/search?q=repo%3Aelastic%2Fki …
=> [EuiBasicTable][EuiInMemoryTable] Remove need for `isSelectable`, `isExpandable`, and `hasActions` props

src/components/button/button_display/_button_display_content.tsx, src/components/button/button_group/button_group_button.styles.ts, src/components/button/button_group/button_group_button.tsx
I missed these in #7541!
- Browser QA
- Release checklist - N/A, skipping changelog due to this being perf tech debt that shouldn't impact consumers
=> [Emotion][perf] Remaining unmemoized button styles 

src-docs/src/views/text_truncate/text_truncate_example.js
Per our deprecation schedule (#1469)
`EuiTextTruncate` is fairly stable at this point, and several fixes/perf enhancements have been implemented during its beta phase. I feel fairly confident in its current docs & usage as-is without the warning.
N/A, mostly a docs change only. AFAIK we've never noted beta status in our changelog?
=> [EuiTextTruncate] Remove beta status in docs

changelogs/upcoming/7640.md, src-docs/src/views/tables/actions/actions.tsx, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/expanded_item_actions.test.tsx.snap, src/components/basic_table/action_types.ts, src/components/basic_table/basic_table.styles.ts, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/basic_table/expanded_item_actions.test.tsx, src/components/basic_table/expanded_item_actions.tsx, src/components/table/__snapshots__/table_row_cell.test.tsx.snap, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/table_row.tsx, src/components/table/table_row_cell.styles.ts, src/components/table/table_row_cell.test.tsx, src/components/table/table_row_cell.tsx
Involves mostly a lot of cleanup (both of CSS and of the props/APIs used 🫠) as there's a lot of legacy code here that I don't love and some styles that (AFAICT) no longer apply. As always, please [follow along by commit](https://github.com/elastic/eui/pull/7640/commits).
The first commit I apparently fixed for `EuiBasicTable` in https://github.com/elastic/eui/pull/6538, but should've applied at a lower level to `EuiTableRowCell` itself. Now's as good a time for that as any!
`showOnHover` API change:
- 2 usages ([1](https://github.com/elastic/kibana/blob/2f9b90a9ea5a3f3dffecb9caec05db2066870b00/x-pack/plugins/observability_solution/infra/public/components/asset_details/tabs/metadata/table.tsx#L89), [2](https://github.com/elastic/kibana/blob/2f9b90a9ea5a3f3dffecb9caec05db2066870b00/x-pack/pl …
=> Convert table actions hover UX/behavior

changelogs/upcoming/7641.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, src/components/basic_table/basic_table.test.tsx, src/components/basic_table/basic_table.tsx, src/components/basic_table/in_memory_table.test.tsx, src/components/basic_table/table_types.ts, src/components/index.scss, src/components/table/__snapshots__/table.test.tsx.snap, src/components/table/__snapshots__/table_footer_cell.test.tsx.snap, src/components/table/__snapshots__/table_header_cell.test.tsx.snap, src/components/table/__snapshots__/table_row.test.tsx.snap, src/components/table/__snapshots__/table_row_cell.test.tsx.snap, src/components/table/_index.scss, src/components/table/_responsive.scss, src/components/table/_table.scss, src/components/table/_table_cell_content.styles.ts, src/components/table/_table_cell_content.tsx, src/components/table/table_cells_shared.styles.ts, src/components/table/table_footer_cell.tsx, src/components/table/table_header_cell.tsx, src/components/table/table_row.tsx, src/components/table/table_row_cell.styles.ts, src/components/table/table_row_cell.test.tsx, src/components/table/table_row_cell.tsx
As always this is A Lot so I recommend [following along by commit](https://github.com/elastic/eui/pull/7641/commits)!
`EuiTableRowCell`, `EuiTableHeaderCell`, and `EuiTableFooterCell` were all manually creating and setting internal `<div/span className="euiTableCellContent">` and `.euiTableCellContent__text` nodes.
This PR DRYs out the cell content wrapper (and its text child) to a new internal `EuiTableCellContent` subcomponent, and also simplifies/removes some `React.cloneElement` shenanigans that was very unclear was needed or not (I leaned not).
With this PR, the last of the Sass files are now fully converted/deleted! 🎉 (there will be 1 more PR after this with some extra cleanup, tests, storybooks for …
=> DRY out new `EuiTableCellContent` internal subcomponent & convert to Emotion

src/components/badge/badge.tsx, src/components/badge/badge_group/badge_group.tsx, src/components/badge/beta_badge/beta_badge.tsx, src/components/badge/notification_badge/badge_notification.tsx, src/components/call_out/call_out.styles.ts, src/components/call_out/call_out.tsx, src/components/context_menu/__snapshots__/context_menu.test.tsx.snap, src/components/context_menu/context_menu.tsx, src/components/context_menu/context_menu_panel.tsx, src/components/description_list/description_list.tsx, src/components/description_list/description_list_description.tsx, src/components/description_list/description_list_title.tsx, src/components/empty_prompt/empty_prompt.tsx, src/components/horizontal_rule/__snapshots__/horizontal_rule.test.tsx.snap, src/components/horizontal_rule/horizontal_rule.tsx, src/components/tabs/tab.tsx, src/components/tabs/tabs.tsx
Part of #7561 efforts
These were fairly straightforward memoizations of the following components and their subcomponents:
- EuiContextMenu
- EuiBadge (and all sibling badge components)
- EuiTabs/Tab
- EuiDescriptionList/Title
- EuiEmptyPrompt
- EuiHorizontalRule (+ removes modifier classes with no usages/references in Kibana)
- EuiCallOut (slightly more judicious use of `useMemo` and inline JSX here)
- Browser QA
- Code quality checklist - N/A, tests should pass as before with no regressions
- Release checklist - N/A, skipping a changelog as this is mostly tech debt and shouldn't affect either consumers or end-users
=> [Emotion][perf] Memoize simpler medium-impact components

src/components/loading/__snapshots__/loading_chart.test.tsx.snap, src/components/loading/loading_chart.styles.ts, src/components/loading/loading_chart.tsx, src/components/loading/loading_elastic.styles.ts, src/components/loading/loading_elastic.tsx, src/components/loading/loading_logo.styles.ts, src/components/loading/loading_logo.tsx, src/components/loading/loading_spinner.stories.tsx, src/components/loading/loading_spinner.tsx
Part of #7561 efforts
This PR:
- Memoizes all `EuiLoading*` components
- Refactors how `EuiLoadingChart` styles are written/generated to use static `:nth-child` CSS instead of dynamic JS styles (98ebe26). Also removes its `--mono` className modifier - no usages in Kibana
- All other components were fairly straightforward
- Browser QA
- Code quality checklist - N/A, all tests should pass
- Release checklist - N/A, skipping a changelog as this is mostly tech debt and shouldn't affect either consumers or end-users
=> [Emotion][perf] Memoize loading components

changelogs/upcoming/7643.md, src/components/breadcrumbs/__snapshots__/breadcrumb.test.tsx.snap, src/components/breadcrumbs/_breadcrumb_content.styles.ts, src/components/breadcrumbs/_breadcrumb_content.tsx, src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap, src/components/header/header_breadcrumbs/header_breadcrumbs.stories.tsx
closes #7514 
This PR updates the styles of `EuiBreadcrumb` with `type="application"` to increase color contrast to ensure the required [contrast minimum level (AA)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum) of `4.5` 
* uses `primary` button colors for interactive breadcrumbs
* replaces `transparentize` with `tintOrShade` on non-interactive breadcrumb styles and adjusts values to result in contrast above `4.5`
_light mode_
https://github.com/elastic/eui/assets/44670957/7e726543-d451-475e-90e7-04ff6d388c12
_dark mode_
https://github.com/elastic/eui/assets/44670957/4527d7eb-dd66-4a3f-acbc-d3a8deeba178
- Browser QA
- Code quality …
=> [EuiBreadcrumb] Update color to ensure min. color contrast

changelogs/upcoming/7650.md, src-docs/src/views/super_select/super_select_basic.js, src/components/form/super_select/__snapshots__/super_select.test.tsx.snap, src/components/form/super_select/super_select.spec.tsx, src/components/form/super_select/super_select.test.tsx, src/components/form/super_select/super_select.tsx, src/components/form/super_select/super_select_control.tsx
The year was 2021, and a younger and much more foolish Cee thought they were squashing bugs and taking names in #5097.
But as it turns out, EuiSuperSelect is kind of an a11y tire fire and needed _much_ more than that!
Fixes in this PR:
- `EuiSuperSelect` now announces parent `EuiFormRow` labels, the same way an `EuiSelect` component would  (thank you @cleydyr for pointing this out to us!)
- `EuiSuperSelect` no longer strands keyboard focus on popover close 😬 
- `EuiSuperSelect`'s popover can now also be opened on `Space` keypress (same as `EuiSelect`)
- `EuiSuperSelect`'s options can now be selected via `Tab` keypress (same as `EuiSelect`)
- `EuiSuperSelect` no longer cycles through its options when pressing arrow up or arrow down at the top or bottom of the options list (same as …
=> [EuiSuperSelect] Fix various focus and accessibility issues: The Sequel, Part Two

src-docs/src/index.js
We've gotten a few reports recently that apparently our (far too long-lived) PR staging links are getting indexed by Google. The longevity of our PR docs sites will be addressed separately, but for now let's at least tell the googs to stop stalking us.
EDIT: second commit also removes releases (e.g. https://eui.elastic.co/v90.0.0/#) from being indexed as well. Although it's not retroactive :/ Not totally sure if we need to re-push a bunch of stuff to our host
- Open https://eui.elastic.co/pr_7657/#/
- Open DOM inspector, look at `<head>`
N/A
=> [Docs] Add `noindex` and `nofollow` to dev & staging

changelogs/upcoming/7658.md, src-docs/src/views/combo_box/combo_box_example.js, src-docs/src/views/combo_box/groups.js, src/components/combo_box/combo_box.test.tsx, src/components/combo_box/combo_box.tsx
closes https://github.com/elastic/eui/issues/7653
See the below QA steps
- Go to https://eui.elastic.co/pr_7658/#/forms/combo-box#groups
- Type in the **full text** (in **lower case**) for any of the options within groups (e.g. `red` or `pop`)
- Once the matching option is the only match aside from its group label (see below example screenshot), press `Enter`
- For comparison against [current production](https://eui.elastic.co/v93.5.2/#/forms/combo-box#groups) - this works but adds the **lower case** text (instead of the actual original option) due to the existing `onCreateOption` callback.
- Browser QA
- Docs site QA …
=> [EuiComboBox] Fix `Enter`ing to select items within groups

.buildkite/pipelines/pipeline_release.yml, .buildkite/scripts/release/step_update_version.sh
This PR adds testing steps to the `eui-release` pipeline, which is triggered on every change of the `main` or `build/test-automatic-releases` branches. When all test steps pass, it proceeds to bump the version number to the next prerelease version as described in the [architecture](https://docs.google.com/document/d/1C9p71SnuUecZ236kYa9ZF-wU-Be6pcmoajkvQPouRq8/edit) doc.
There are several protections in place to ensure `elastic/eui` git history never gets overridden. It also fails early when the new version is already published on npm.
With all that said, I disabled the version update step on the `main` branch for testing purposes and will enable it in a follow-up PR after manual QA.
Manual QA will be done by @tkajtoch after merging changes to `main`.
=> CI: configure `eui-release` pipeline to test merged changes and bump package versions

changelogs/upcoming/7656.md, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/table/__snapshots__/table_header_cell.test.tsx.snap, src/components/table/table_cells_shared.styles.ts, src/components/table/table_header_cell.test.tsx, src/components/table/table_header_cell.tsx
closes https://github.com/elastic/eui/issues/7610
- Go to https://eui.elastic.co/pr_7656/#/tabular-content/tables#adding-sorting-to-a-table
- Toggle the `enableAllColumns` switch
- Toggle the `readOnly` switch
- Browser QA
~- [ ] Checked in **mobile**~ N/A, header cells don't show on mobile
=> [EuiTableHeaderCell] Add a subdued `sortable` icon for columns that can be sorted

scripts/docker-ci/README.md, wiki/contributing-to-eui/testing/automated-accessibility-testing.md, wiki/eui-team-processes/upgrading-node.md
These two scripts [were removed](https://github.com/elastic/eui/pull/7379) from our Repository, but our README and Wiki content was not updated accordingly. I removed references from both places.
There is a Chore in our backlog to [replace these scripts](https://github.com/elastic/eui/pull/7379).
=> Remove unused scripts

changelogs/upcoming/7667.md, src/components/basic_table/action_types.ts, src/components/basic_table/collapsed_item_actions.test.tsx, src/components/basic_table/collapsed_item_actions.tsx, src/components/basic_table/default_item_action.test.tsx, src/components/basic_table/default_item_action.tsx
This PR passes back an `event` to `onClick` callbacks passed to basic/memory tables' `actions` buttons. This allows consumers to do things like `event.preventDefault()` and `event.stopPropagation()`.
In particular, Kibana needs `event.preventDefault()` for their react router utilities that add both a href and SPA routing onClick. This will let us also get rid of Kibana style overrides/workarounds to match our default actions (see https://github.com/elastic/kibana/pull/118434#discussion_r749691551)
(Optional, tests should cover behavior sufficiently)
- Open `src-docs/src/views/tables/actions/actions.tsx` in your IDE and the following code below line 197 (the `User profile` action):
```
onClick: (item, event) => {
event.preventDefault();
event.stopPropagation();
console.log(item);
},
```
- …
=> [EuiBasicTable] Pass click events to `actions` onClick

changelogs/upcoming/7666.md, src/components/color_picker/__snapshots__/color_picker.test.tsx.snap, src/components/color_picker/_color_picker.scss, src/components/color_picker/color_picker.tsx, src/components/form/field_number/field_number.tsx, src/components/form/field_text/field_text.stories.tsx, src/components/form/field_text/field_text.tsx, src/components/form/form_control_layout/_num_icons.test.ts, src/components/form/form_control_layout/_num_icons.ts, src/components/form/form_control_layout/form_control_layout_icons.tsx
@dplumlee helped us identify a visual bug with customizing `EuiFieldText` and `EuiFieldNumber`'s `icon` prop using object configuration to configure the icon side. While here, I found Even More Bugs (yay!)
| <img width="485" alt="" src="https://github.com/elastic/eui/assets/549407/7dd2cea0-8237-4034-af6e-a3c1659bef3d"> | <img width="485" alt="" src="https://github.com/elastic/eui/assets/549407/60ff4f98-db73-4613-bcfa-5f79ce53ecbd"> | 
Right side icon fix:
- Go to https://eui.elastic.co/pr_7666/storybook/?path=/story/forms-euifieldnumber--icon-shape
- In the control panel, change the side to `'right'`
Control only fix:
- Go to https://eui.elastic.co/pr_7666/storybook/?path=/story/forms-euifieldnumber--playground
- Toggle `controlOnly` to true
- Type …
=> [EuiFieldText][EuiFieldNumber] Various `icon` related fixes

package.json, yarn.lock
Bumped the `axe-core` library to latest `v4.9.0` to ensure we're using the latest ruleset in CI to match browser plugin.
* Ran the `yarn test-cypress-a11y` suite locally all tests passed.
* CI server should pass as well
@bhavyarm is working on bringing Kibana up to the newest version as well. She's got two PRs in progress on this front. Should have them finished the week of 22 April.
* https://github.com/elastic/kibana/pull/180694
* https://github.com/elastic/kibana/pull/178763
=> [CHORE]: Bump axe-core to latest v4.9.0

changelogs/upcoming/7681.md, src-docs/src/views/tables/auto/auto.tsx, src/components/table/table_row_cell.styles.ts
> [!note]
> Reported in https://github.com/elastic/kibana/pull/180514#pullrequestreview-1997600737. This PR will need to be a backport/patch release for the tables release.
| <img width="422" alt="" src="https://github.com/elastic/eui/assets/549407/7b35b1f5-3fe5-444f-b75a-8cada543cf25"> | <img width="439" alt="" src="https://github.com/elastic/eui/assets/549407/dcfe4f2c-91ac-45db-9845-b633fba63957"> | 
`th` cells default to `font-weight: bold; text-align: center` ([source](https://www.w3schools.com/cssref/css_default_values.php)) and row cells that are row headers via `setScopeRow` need to have that CSS unset.
This wasn't caught by / didn't affecting our demo examples because our `textOnly` wrapper sets a display flex which automatically justifies to …
=> [EuiTableRowCell] Fix `th scope="row"` text alignment

changelogs/upcoming/7672.md, i18ntokens.json, src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, src/components/basic_table/basic_table.tsx
Closes: https://github.com/elastic/eui/issues/7542
We've received reports of a few accessibility (a11y) issues concerning the table component and the select/deselect row functionality. Could we consider adding an aria-label attribute to address these checkbox-related concerns?
Historically, this has been an old [issue](https://github.com/elastic/eui/pull/2043), and attempts have already been made to fix it by adding a `selectableMessage`. Unfortunately, we can't motivate everyone to override a default message. I suggest simply correcting the default values of `aria-label/title`
- `aria-label`  and `title` attributes were updated.
=> [EuiTable][a11y] select row Checkbox elements must have correct labels

changelogs/upcoming/7676.md, src-docs/src/views/markdown_editor/markdown_editor.js, src-docs/src/views/markdown_editor/markdown_editor_example.js, src-docs/src/views/markdown_editor/markdown_editor_no_plugins.js, src/components/markdown_editor/plugins/markdown_default_plugins/parsing_plugins.ts, src/components/markdown_editor/plugins/markdown_default_plugins/plugins.test.ts, src/components/markdown_editor/plugins/markdown_default_plugins/plugins.ts, src/components/markdown_editor/plugins/markdown_default_plugins/processing_plugins.tsx, src/components/markdown_editor/plugins/markdown_default_plugins/ui_plugins.ts
This PR adds a way to exclude the `line-breaks` plugin from what `getDefaultEuiMarkdownPlugins()` defaults and revive the original line-breaking by two trailing spaces in markdown.
Closes #7673
- Go to https://eui.elastic.co/pr_7676/#/editors-syntax/markdown-editor#unregistering-plugins
- Browser QA
- Docs site QA
~~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/playgrounds.md)**~~
~~- [ ] If applicable, added the **breaking change** issue label (and filled out the breaking change checklist)~~
- Designer checklist - …
=> [EuiMarkdownEditor] Allow more plugins to be excludable

.buildkite/pipelines/pipeline_pull_request_test.yml
Our Cypress tests are semi-flaky (notably around truncation and data grid cell popovers), and have recently been requiring more manual re-tries at times. Let's just make it automatic as they usually pass after a single retry.
=> [ci] Automatically retry flaky Cypress tests

scripts/jest/config.js, src/components/datagrid/body/data_grid_row_manager.test.ts, src/components/datagrid/utils/col_widths.test.ts, src/components/datagrid/utils/ref.test.ts, src/components/datagrid/utils/sorting.test.ts, src/components/date_picker/super_date_picker/pretty_interval.test.ts, src/components/markdown_editor/markdown_format.styles.test.ts, src/components/progress/progress.styles.test.ts, src/components/text/text.styles.test.ts, src/components/title/title.styles.test.ts, src/global_styling/mixins/_color.test.ts, src/global_styling/mixins/_padding.test.ts, src/global_styling/mixins/_responsive.test.ts, src/global_styling/mixins/_states.test.ts, src/global_styling/mixins/_typography.test.ts, src/global_styling/utility/utility.test.ts, src/services/hooks/useDeepEqual.test.ts, src/themes/amsterdam/global_styling/mixins/button.test.ts
Merging in the #7646 work somehow triggered a chain of events that resulted in our `renderHook` usage in jest tests to fail when running on React <18. The `renderHook` has to be imported conditionally from `@testing-library/react` for React 18 or `@testing-library/react-hook` for React 16 and 17, which is done in `src/test/rtl/render_hook.ts`.
I'm not 100% sure why the tests importing `renderHook` directly from `@testing-library/react` weren't failing on React 16 and 17 for the past 6+ months, but the important thing is that this PR fixes all of these LOL
Ensure CI is passing and unit tests are passing on all React versions.
=> fix: `renderHook` imports

src/components/collapsible_nav_beta/_kibana_solution/__snapshots__/collapsible_nav_kibana_solution.test.tsx.snap, src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.stories.tsx, src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.styles.ts, src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.test.tsx, src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.tsx, src/components/collapsible_nav_beta/_kibana_solution/index.ts, src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_beta.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_item.stories.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.stories.tsx, src/components/popover/input_popover.spec.tsx, src/components/popover/input_popover.tsx
closes #7655
Renames `EuiCollapsibleNavBeta.Group` to `EuiCollapsibleNavBeta.KibanaSolution` (to reflect that this component is now fairly opinionated and Kibana-specific).
```tsx
<EuiCollapsibleNavBeta>
<EuiCollapsibleNavBeta.Body>
<EuiCollapsibleNavBeta.KibanaSolution
title: 'Security',
icon: 'logoSecurity',
solutions: [
{ title: 'Observability', icon: 'logoObservability' },
{ title: 'Switch to classic', icon: 'logoKibana', isSecondary: true, },
],
items: [...], // Regular nav links/items
/>
</EuiCollapsibleNavBeta.Body>
</EuiCollapsibleNavBeta>
```
- https://eui.elastic.co/pr_7693/storybook/?path=/story/navigation-euicollapsiblenav-beta-kibanasolution--playground
- Browser QA
- Docs site QA - N/A, beta component
- Release checklist - N/A, beta component and …
=> [EuiCollapsibleNavBeta] `KibanaSolution` component

changelogs/upcoming/7698.md, src/components/datagrid/body/header/column_actions.test.tsx, src/components/datagrid/body/header/column_actions.tsx, src/components/datagrid/body/header/data_grid_header_cell.tsx
Should resolve both https://github.com/elastic/kibana/issues/177527 and https://github.com/elastic/kibana/pull/180064
I apparently attempted to resolve this in https://github.com/elastic/eui/pull/5530 but past-me didn't account for two things:
1. Leading control column count
2. The popover's focus trap's `returnFocus` logic interfering with `setFocusedCell`
- I actually assume this is [why our docs work](https://eui.elastic.co/v93.6.0/#/tabular-content/data-grid-schema-columns#control-columns) and Kibana doesn't(??)
| ![before](https://github.com/elastic/eui/assets/549407/781ca8f0-aefd-4cff-aff6-57287d5bd58c) | ![after](https://github.com/elastic/eui/assets/549407/b4ef47de-54fb-462b-82d6-2e3900963465) | 
Since I can't seem to repro this at all in …
=> [EuiDataGrid] Fix column header move left focus bug

changelogs/upcoming/7699.md, src/components/steps/__snapshots__/step_horizontal.test.tsx.snap, src/components/steps/__snapshots__/steps_horizontal.test.tsx.snap, src/components/steps/step_horizontal.tsx
PR closes #7686. This pull request adds an `aria-hidden` boolean attribute to the `EuiHorizontalStep` component. It allows us to better inform screen reader users when a button is temporarily unavailable while keeping the button in the tab order. Screen reader users get a more informative message, sighted users get the same UX as in production now.
I tested locally with axe browser plugin, keyboard navigation, and Safari + VO screen reader combination. Will test in NVDA and JAWS before merging.
---
- Browser QA
- Docs site QA
=> [EuiStepsHorizontal] Added `aria-disabled` attribute when status is "disabled"

changelogs/upcoming/7696.md, src/components/accordion/__snapshots__/accordion.test.tsx.snap, src/components/accordion/accordion.spec.tsx, src/components/accordion/accordion.test.tsx, src/components/accordion/accordion.tsx, src/components/accordion/accordion_children/accordion_children.tsx, src/components/collapsible_nav/collapsible_nav_group/__snapshots__/collapsible_nav_group.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_accordion.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap
This PR updates the `EuiAccordion` component to **not** move focus to the child component when the expand/collapse button is clicked. This came about from an accessibility audit that moving focus in this instance is in violation of [SC 3.2.2: On Input (Level A)](https://www.w3.org/WAI/WCAG22/Understanding/on-input.html).
Specifically, moving focus to the child container caused a [change of context](https://www.w3.org/WAI/WCAG22/Understanding/on-input.html#dfn-changes-of-context) by resetting focus.
I don't **believe** this is a breaking change, but would ask reviewers to speak up early and loudly if they feel it might be a breaking change.
I checked in all four browsers. I reviewed the `EuiAccordion` and `EuiCollapsibleNavGroup` …
=> [EuiAccordion] Update component logic to retain focus on `<button>` when clicked

changelogs/upcoming/7702.md, src/components/search_bar/query/default_syntax.test.ts, src/components/search_bar/query/default_syntax.ts
@iverase's team needs the ability to search for more special characters in `EuiInMemoryTable`'s search bar (uses `EuiSearchBar` under the hood). They primarily need the special characters `*` (already supported) and `@` (in this PR).
(See also https://github.com/elastic/eui/issues/7160#issuecomment-1724175485)
- Go to https://eui.elastic.co/pr_7702/#/forms/search-bar
- Confirm that typing `test@` (and enter) into the search bar does not generate an error
- Go to https://eui.elastic.co/pr_7702/#/tabular-content/in-memory-tables#in-memory-table-with-search
- Confirm typing `test@` (and enter) into the search bar does not generate an invalid warning icon (should show no results instead)
- Browser QA - N/A, not a frontend/UI change
- Docs site QA - N/A, not documented …
=> [EuiSearchBar] Allow `@` special character in query string searches

changelogs/upcoming/7708.md, src/components/date_picker/super_date_picker/date_popover/_date_popover_content.scss
closes #7706
| <img width="439" alt="" src="https://github.com/elastic/eui/assets/549407/e823c9f0-bfc1-4ab8-972c-156643a763cf"> | <img width="417" alt="" src="https://github.com/elastic/eui/assets/549407/5e50e097-343d-42e4-a82d-82cea5d515eb"> | 
- Go to https://eui.elastic.co/pr_7708/#/templates/super-date-picker
- Make your browser window smaller than 574px
- Scroll down to the first super date picker, click the date, then click the `Absolute` tab
- Browser QA
- Code quality checklist - N/A, CSS-only change
- Designer checklist - N/A, bugfix
=> [EuiSuperDatePicker] Fix absolute tab for small mobile screens

changelogs/upcoming/7705.md, src-docs/src/views/super_date_picker/super_date_picker_example.js, src-docs/src/views/super_date_picker/super_date_picker_locale.tsx, src/components/date_picker/super_date_picker/date_popover/absolute_tab.test.tsx, src/components/date_picker/super_date_picker/date_popover/absolute_tab.tsx
This PR fixes EuiSuperDatePicker's date validation to be locale-aware.
Closes #7704
- Browser QA
- Docs site QA
=> [EuiSuperDatePicker] Fix date validation to be locale-aware

changelogs/upcoming/7698.md, src/components/datagrid/body/header/data_grid_header_cell_wrapper.tsx
(Note: #7698 fixed the issue for Kibana, but the underlying issue still persists for CRA and likely CodeSandbox - potentially due to various prod vs dev bundled race conditions)
| ![before](https://github.com/elastic/eui/assets/549407/c0e11b13-b9bd-458f-901c-ad93ad1951d3) | ![after](https://github.com/elastic/eui/assets/549407/999a02bb-9d7d-48b7-8118-eb0f5d3535a5) |
We noticed that focus was not updating visually after moving columns left or right in certain environments in this PR: https://github.com/elastic/eui/pull/7698.
If you initiate a "Move left" from column 4 -- you're essentially swapping columns. Column 4 becomes moves to position 3 and column 3 moves to position 4.
When you click on the header cell to initiate that action, the column 4 …
=> [EuiDataGrid][CRA] Fix header cell focus when moving columns left/right

changelogs/upcoming/7709.md, src-docs/src/views/combo_box/combo_box_example.js, src-docs/src/views/combo_box/option_matcher.tsx, src-docs/src/views/selectable/selectable_example.js, src-docs/src/views/selectable/selectable_option_matcher.tsx, src/components/combo_box/combo_box.stories.tsx, src/components/combo_box/combo_box.tsx, src/components/combo_box/index.ts, src/components/combo_box/matching_options.test.ts, src/components/combo_box/matching_options.ts, src/components/combo_box/types.ts, src/components/selectable/matching_options.ts, src/components/selectable/selectable.tsx, src/components/selectable/selectable_search/selectable_search.test.tsx, src/components/selectable/selectable_search/selectable_search.tsx
This PR resolves #2199 by allowing passing a custom matcher function to `EuiComboBox` and `EuiSelectable` using the new optional `optionMatcher` prop.
I kept the tests the same, just moved code around to extract the specific filtering logic while keeping component internals intact and not overridable (like `isPreFiltered` logic), so consumers don't have to reimplement them.
The default option matcher should behave exactly as before the prop was introduced. 
- Docs site QA
=> feat: Add `optionMatcher` prop to `EuiSelectable` and `EuiComboBox` components

changelogs/upcoming/7688.md, src-docs/src/views/flex/flex_example.js, src/components/flex/flex_group.test.tsx, src/components/flex/flex_group.tsx, src/components/flex/flex_item.test.tsx, src/components/flex/flex_item.tsx
This resolves https://github.com/elastic/eui/issues/7612 by updating `EuiFlexGroup` and `EuiFlexItem` to support dynamic prop type resolution with generics. It also cleans up the code and adds ref forwarding to `EuiFlexItem` to keep these two consistent.
The generic argument falls back to `'div'` to keep the API backward compatible in cases where a customer would import and use the `EuiFlexGroupProps` or `EuiFlexItemProps` type.
There are a couple of type casts added to ensure TypeScript and IDEs can resolve the full complex type and provide meaningful code suggestions.
- Docs site QA
=> feat: `EuiFlexGroup` and `EuiFlexItem` component prop type improvements

changelogs/upcoming/7718.md, src/components/search_bar/filters/field_value_selection_filter.tsx
Closes https://github.com/elastic/eui/issues/7714
The `EuiSelectable` component already handles `i18n` for the empty and loading states, so I figured it was easiest to simply let that component handle things instead - note that the empty state text will be changed from "No options found" to "No options available" because of this change which, IMO, is actually better copy for this scenario anyway :+1: 
- Docs site QA
- The `FieldValueSelectionFilter` doesn't seem to have direct documentation since it's all part of the `EuiSearchBar` component - so not sure how to handle documentation in this case? LMK if something should be changed documentation-wise though :+1: 
=> [FieldValueSelectionFilter] [i18n] Let `EuiSelectable` handle default loading and empty messages

changelogs/upcoming/7719.md, package.json
Needed for https://github.com/elastic/kibana/pull/182023. This is causing several `@testing-library/user-event` related failures in Kibana due to the them being on v13 and not v14 
N/A, test/deps change
- Code quality checklist 
=> Fix `@storybook/test` - should be in `devDependencies`, not `dependencies`

.buildkite/scripts/pipelines/pipeline_prune_staging_docs.sh
Per recent discussion, keeping only the latest 50 staging docs will prune PRs from as recent as 3 weeks ago - let's increase it to 100 to give ourselves a bit more of a buffer (at least a month).
N/A, infra only
=> [CI] Increase the # of kept PR staging docs to 100

src/services/format/format_date.test.ts
This PR fixes the following unit test failure at +9 and -9 hours of timezone offset.
```console
sakurai@wsl:~/git/eui$ yarn test-unit src/services/format/format_date.test.ts
yarn run v1.22.22
$ node ./scripts/test-unit src/services/format/format_date.test.ts
cross-env NODE_OPTIONS="" NODE_ENV=test REACT_VERSION=18 jest --config ./scripts/jest/config.js src/services/format/format_date.test.ts
Running tests on React v18
FAIL  src/services/format/format_date.test.ts
formatDate
✓ no config - date value (2ms)
✓ no config - number value
✓ no config - string value (1ms)
✓ no config - no value
✓ with config - no value (1ms)
✓ with config - "date" format
✓ with config - "longDate" format
✓ with config - "shortDate" format
✓ with config - "dateTime" format
✓ with config - "longDateTime" format
✓ …
```
=> Fix failure of yarn test-unit at 9 hours offset

generator-eui/changelog/index.js, generator-eui/changelog/templates/changelog.md
The discussion in https://github.com/elastic/eui/pull/7740#discussion_r1592660797 inspired me to update our `yarn yo-changelog` generator util to include a prompt and generated heading for a11y improvements, now that we have more folks contributing to that area! 🎉 🥳 
We've historically already been using the `**Accessibility**` heading in any case for changelog, this just makes it more official and easier for new contributors to find.
N/A, dev only change
=> [changelogs] Add an accessibility prompt/heading to `yo` generator

changelogs/upcoming/7740.md, src/components/collapsible_nav_beta/_kibana_solution/__snapshots__/collapsible_nav_kibana_solution.test.tsx.snap, src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.test.tsx, src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_button.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_item.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/__snapshots__/collapsed_nav_popover.test.tsx.snap, src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_button.tsx
Closes: https://github.com/elastic/security-team/issues/8947
The Security icon popover announces "Security, button", then "Security, description" to screen readers. This is caused by the aria-label and tooltip aria-describedby text being the same. Screen reader users do not have context that this will open the Security Solution quick navigation popover (with just the top-level links). We can improve this by updating the information in the EUI Tooltip content prop. Screenshot and linked CodeSandbox below.
1. aria-label attribute was updated
- Browser QA
- Docs site QA
=> [EuiCollapsedNavButton][a11y] Update `aria-label` for enhanced screen reader navigation

.github/workflows/changelog.yml
This fixes the path to changelogs directory defined in the changelog Github action.
QA must be done manually after merging this change
=> build: fix changelog github action

packages/eui/changelogs/upcoming/7751.md, packages/eui/src/components/tool_tip/tool_tip.spec.tsx, packages/eui/src/components/tool_tip/tool_tip.tsx
closes https://github.com/elastic/eui/issues/7741
- Go to https://eui.elastic.co/pr_7751/#/display/tooltip
- Keyboard tab to the first tooltip link
- Browser QA
- Docs site QA - Skipped docs - see below conversation with Trevor
~- [ ] Props have proper **autodocs** (using `@default` if default values are missing) and **[playground toggles](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting/playgrounds.md)**~
~- [ ] If applicable, added the …
=> [EuiToolTip] Close tooltips on escape keydown

wiki/eui-team-processes/releasing-versions.md
We've recently run into issues attempting to unpublish erroneous releases of EUI, so we're now documenting the correct step to take instead.
N/A, wiki only
=> [Wiki] Document deprecating/unpublishing releases

wiki/contributing-to-eui/running-eui-locally.md
📄 This PR adds a "Troubleshooting" section to our `running-eui-locally.md` docs and adds steps on how to deal with errors due to missing config files for the [VSCode ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) since the recent changes towards a monorepo setup.
=> [Wiki] Add troubleshooting section

packages/eui/changelogs/upcoming/7759.md, packages/eui/src/components/flyout/flyout_resizable.spec.tsx, packages/eui/src/components/flyout/flyout_resizable.tsx
closes https://github.com/elastic/eui/issues/7536
Currently, `size` stops updating/being respected after the first time a user resizes the flyout. I've tweaked the `useEffect`s of the resizable flyout component slightly to allow consumers to control/override the internal flyout width state.
- Go to https://eui.elastic.co/pr_7759/storybook/?path=/story/layout-euiflyout-euiflyoutresizable--playground
- Resize the flyout (mouse, keyboard focus, etc). That should work normally/as expected
- Scroll down in the controls pane to the `size` prop, and change it (e.g. to `s`, `l`, `2000px`, `400`, etc)
- Browser QA - N/A, logical/state JS changes only
- Docs site QA - N/A, I skipped extra docs for this as this is likely how it should have worked all along 🙈 
- Release …
=> [EuiFlyoutResizable] Allow consumers to update the `size` prop

packages/eui/changelogs/upcoming/7767.md, packages/eui/src/components/form/range/dual_range.test.tsx, packages/eui/src/components/form/range/dual_range.tsx
closes https://github.com/elastic/eui/issues/7764
| <img width="690" alt="invalid" src="https://github.com/elastic/eui/assets/549407/9f92f1b1-6230-42b6-8880-096191928717"> | <img width="702" alt="valid" src="https://github.com/elastic/eui/assets/549407/37617a3e-5942-4f10-afbd-8da5c2a12f73"> | 
`Number('')` evals to `0` which is why the bug was happening. The new code checks for `value === ''` and more manually falls back to the min/max if so. Sadly we can't DRY this out in the getter because the getter is used too many other places / we do actually need to render `''` for the value.
Added a unit regression test to check for the correct applied `min`/`max` props when values are empty strings.
- Go to …
=> [EuiDualRange] Fix incorrect input min/max values when empty string values exist

packages/eui/changelogs/upcoming/7726.md, packages/eui/src/components/date_picker/react-datepicker/src/time.js
closes https://github.com/elastic/eui/issues/6687
- https://eui.elastic.co/pr_7726/#/templates/super-date-picker
- Browser QA
- Code quality checklist - N/A, technically a 3rd party library?...
~- [ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/cypress-testing.md) tests**~
=> [EuiDatePicker][a11y] Fix screen reader announcements on time selection and intermittently broken up/down navigation on NVDA/JAWS

NOTICE.txt, README.md, packages/eui/LICENSE.txt, packages/eui/NOTICE.txt, packages/eui/README.md, packages/eui/licenses/ELASTIC-LICENSE-2.0.md, packages/eui/licenses/SSPL-LICENSE.md, packages/eui/scripts/release.js, packages/eui/scripts/update-token-changelog.js
This fixes a few issues I encountered while releasing EUI after converting the repo to a monorepo structure. I recommend reviewing commit-by-commit to get more context.
As soon as we integrate a monorepo manager, we won't need the copied files, as they'll be automatically included from the root directory. For the time being, though, copying them to `packages/eui` is the simplest solution.
1. Checkout this PR locally
2. Go to `packages/eui`
3. Ensure you're logged out from npm as an extra precaution by running `npm logout`
4. [x] Run `npm run release -- --type=prerelease --dry-run` and confirm that it doesn't throw any errors and that the `Updated changelog` commit is created
5. [x] Run `npm run pack` and confirm `README.md`, `LICENSE.txt` and the `licenses` directory are included in the …
=> build: fix releases in monorepo project structure

packages/eui/changelogs/upcoming/7776.md, packages/eui/src/components/form/field_text/field_text.stories.tsx, packages/eui/src/components/form/field_text/field_text.styles.ts, packages/eui/src/components/form/form.styles.test.tsx, packages/eui/src/components/form/form.styles.ts
This request was sparked from a Slack conversation from the Observability folks. Chrome sets a custom light blue autofill color on inputs that doesn't obey EUI's light/dark mode theme - we can hackily override this background color via some `-webkit-box-shadow` trickery.
| Light mode | Dark mode |
| <img width="428" alt="" src="https://github.com/elastic/eui/assets/549407/45936ce8-87bf-4bd2-8ebb-f571df72d76e"> | <img width="424" alt="" src="https://github.com/elastic/eui/assets/549407/631cd5a0-7576-46fe-9f16-920f5ae49c34"> |
| <img width="428" alt="" src="https://github.com/elastic/eui/assets/549407/b98a289f-fadb-40f2-ae00-69c808f03176"> | <img width="427" alt="" src="https://github.com/elastic/eui/assets/549407/5287d288-b430-4bc7-9aec-2a5aecb435fa"> |
More resources: …
=> Update form autofill colors on webkit browsers

packages/eui/changelogs/upcoming/7784.md, packages/eui/src-docs/src/views/date_picker/date_picker.js, packages/eui/src/components/date_picker/date_picker.test.tsx, packages/eui/src/components/date_picker/date_picker.tsx, packages/eui/src/components/date_picker/react-datepicker/src/index.js
@shahzad31 reported this issue to us in Slack - passing an invalid `moment()` date to the `selected` prop causes a maximum update depth exceeded React error. We should be more gracefully handling and alerting consumers to this issue without just blanket crashing JS.
| <img width="500" alt="" src="https://github.com/elastic/eui/assets/549407/41f9afcf-ef9f-478c-bf18-43f93890c884"> | ![fix](https://github.com/elastic/eui/assets/549407/86db81b6-bf66-4472-9bb2-68fa1d6ab927) | 
- Go to https://eui.elastic.co/pr_7784/#/forms/date-picker
- Browser QA
~- [ ] If applicable, added the **breaking change** issue …
=> [EuiDatePicker] Handle invalid `selected` moment formats

packages/eui/changelogs/upcoming/7792.md, packages/eui/scripts/dtsgenerator.js, packages/eui/src/components/flex/flex_group.tsx, packages/eui/src/components/flex/flex_item.tsx
Fixes https://github.com/elastic/eui/issues/7783
This PR optimizes types used in `EuiFlexItem` and `EuiFlexGroup` to be resolved faster and more reliably.
We recently found out that the introduction of https://github.com/elastic/eui/pull/7688 caused a significant increase in type-checking times in Kibana. The reason wasn't clear at first, but profiling `tsc` and running type checking with various type simplifications highlighted the primary error. The generic typing of these two components isn't at fault. It's actually the type inferencing and distributive conditionals used multiple times in the type resolution path and EUI types being combined into a single big `eui.d.ts` all added to the type checking execution time.
This PR addresses all of these by simplifying these types and fixes a …
=> fix: Simplify EuiFlex generic types

packages/eui/changelogs/upcoming/7799.md, packages/eui/src-docs/src/views/form_controls/form_controls_example.js, packages/eui/src/components/date_picker/date_picker.tsx, packages/eui/src/components/form/field_text/field_text.tsx, packages/eui/src/components/form/form_control_layout/_form_control_layout.scss, packages/eui/src/components/form/form_control_layout/_num_icons.ts, packages/eui/src/components/form/form_control_layout/form_control_layout.tsx
> [!NOTE]  
> This PR is merging into a feature branch.
Follow up refactor from CSS variable architecture set up in https://github.com/elastic/eui/pull/7770/commits/4ddc0ef3e2073d3417b360b3f47c2931429b541d, and addresses a quick TODO from https://github.com/elastic/eui/pull/7770/commits/e13aa418469edd0eada395f8aa69063d653837f9 (#7770 was already getting unwieldy, hence this separate PR).
This PR sets icon affordance variables on the `EuiFormControlLayout` wrapper, which cascades down to inner `<input>`s and child form controls. Once all form controls are on Emotion, they'll automatically inherit the right # of icons to account for in their inner padding.
| <img width="485" alt="" src="https://github.com/elastic/eui/assets/549407/3a751574-481a-4013-b20 …
=> [EuiFormControlLayout] Automatically handle icon affordance via CSS variables

packages/eui/changelogs/upcoming/7805.md, packages/eui/src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap, packages/eui/src/components/badge/beta_badge/beta_badge.tsx
Closes: https://github.com/elastic/eui/issues/7791
Remove `role=button` for cases when the user doesn't provide an `onClick` or `href` attribute. In that mode, the component only shows the tooltip
=> [EuiBetaBadge] Improved the accessibility experience of EuiBetaBadge component

packages/eui/src/components/collapsible_nav_beta/_kibana_solution/__snapshots__/collapsible_nav_kibana_solution.test.tsx.snap, packages/eui/src/components/collapsible_nav_beta/_kibana_solution/collapsible_nav_kibana_solution.tsx, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_beta.stories.tsx, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_item.test.tsx.snap, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.styles.ts, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.test.tsx, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/collapsible_nav_item.tsx
Requested by @sebelga and @ryankeairns. ~Updates all top-level `items` to have the same reduced padding of `EuiCollapsibleNavBeta.KibanaSolution`.~ See comment thread below for final design choices
| <img width="270" alt="" src="https://github.com/elastic/eui/assets/549407/603f8816-c55d-48cb-956f-99a79b67e6f9"> | <img width="449" alt="" src="https://github.com/elastic/eui/assets/549407/908082f0-6fe6-4129-9c64-340d8df12b70"> | 
NOTE: `EuiCollapsibleNavBeta.KibanaSolution` is no longer slated to be used in Kibana, but we're holding off for another little while (to let decision making settle) before removing it fully.
- https://eui.elastic.co/pr_7796/storybook/?path=/story/navigation-euicollapsiblenav-beta-euicollapsiblenavbeta--playground
=> [EuiCollapsibleNavBeta] Tweak styles per latest Kibana directives

packages/eui/changelogs/upcoming/7808.md, packages/eui/src-docs/src/views/flyout/flyout_example.js, packages/eui/src/services/color/eui_palettes.ts, packages/eui/src/services/color/index.ts, packages/eui/src/services/index.ts
See https://github.com/elastic/eui/issues/1469
- Removes beta status on **EuiFlyoutResizable**
- Removes `euiPalettePositive` and `euiPaletteNegative` (https://github.com/elastic/eui/pull/7570)
=> June deprecations

packages/eui/changelogs/upcoming/7806.md, packages/eui/src-docs/src/views/search_bar/props_info.js, packages/eui/src/components/search_bar/filters/field_value_selection_filter.spec.tsx, packages/eui/src/components/search_bar/filters/field_value_selection_filter.tsx
closes #2259
- N/A - I'm leaning towards the written  Cypress tests being thorough enough to suffice, but LMK if you disagree!
- Browser QA - N/A, JS logic change only
=> [EuiSearchBar][FieldValueSelectionFilter] Fix `autoClose: false` to always be respected regardless of `multiSelect`

packages/eui/src-docs/src/views/form_controls/prepend_append.js, packages/eui/src/components/form/form_control_layout/form_control_layout.tsx
> [!NOTE]
> This PR merges into a feature branch.
This tech debt will allow us to more easily use hooks for Emotion styles in a future PR.
N/A, tech debt only
=> [EuiFormControlLayout] Convert from class to function component

packages/eui/changelogs/upcoming/7814.md, packages/eui/src-docs/src/views/tables/custom/custom.tsx, packages/eui/src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, packages/eui/src/components/basic_table/basic_table.tsx, packages/eui/src/components/form/checkbox/__snapshots__/checkbox.test.tsx.snap, packages/eui/src/components/form/checkbox/_checkbox.scss, packages/eui/src/components/form/checkbox/checkbox.stories.tsx, packages/eui/src/components/form/checkbox/checkbox.test.tsx, packages/eui/src/components/form/checkbox/checkbox.tsx, packages/eui/src/components/form/radio/_radio.scss
> [!NOTE]
> This PR **is** merging into main and not a feature branch - I wanted the breaking `type inList` change in at the same time as our other June deprecations
- Discussed in https://github.com/elastic/eui/pull/7781#discussion_r1619783789
- Related Kibana PR removing usages: https://github.com/elastic/kibana/pull/184881
- Browser QA
- ~[ ] Added **[documentation](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/documenting)**~ - N/A, not documented
- Code quality checklist - N/A, tests should pass as before
=> [EuiCheckbox] Remove `type`/`inList` prop

packages/eui/changelogs/upcoming/7817.md, packages/eui/src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, packages/eui/src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, packages/eui/src/components/basic_table/basic_table.test.tsx, packages/eui/src/components/basic_table/basic_table.tsx
| ![before](https://github.com/elastic/eui/assets/549407/3e9af24f-62c8-47c9-a9f3-2d4b0f8541fc) | ![after](https://github.com/elastic/eui/assets/549407/22a04b5a-af74-48dc-a488-029f0bb1ca28) |
I implemented this kind of on a whim while looking at our indeterminate EuiCheckboxes in https://github.com/elastic/eui/pull/7814, and realizing we don't really utilize them 👀  UX is based off of Gmail's select all behavior.
- [EuiBasicTable](https://eui.elastic.co/pr_7817/#/tabular-content/tables#adding-selection-to-a-table)'s header checkbox selection:
- Browser QA
~- [ ] If applicable, added the **breaking change** …
=> [EuiBasicTable] Support indeterminate checkboxes in header row

packages/eui/changelogs/upcoming/7818.md, packages/eui/src-docs/src/views/selection_controls/checkbox.js, packages/eui/src/components/form/checkbox/__snapshots__/checkbox_group.test.tsx.snap, packages/eui/src/components/form/checkbox/_checkbox_group.scss, packages/eui/src/components/form/checkbox/_index.scss, packages/eui/src/components/form/checkbox/checkbox.stories.tsx, packages/eui/src/components/form/checkbox/checkbox.tsx, packages/eui/src/components/form/checkbox/checkbox_group.styles.ts, packages/eui/src/components/form/checkbox/checkbox_group.tsx, packages/eui/src/components/form/radio/__snapshots__/radio_group.test.tsx.snap, packages/eui/src/components/form/radio/_index.scss, packages/eui/src/components/form/radio/_radio_group.scss, packages/eui/src/components/form/radio/radio.stories.tsx, packages/eui/src/components/form/radio/radio.tsx, packages/eui/src/components/form/radio/radio_group.styles.ts, packages/eui/src/components/form/radio/radio_group.tsx
> [!NOTE]
> This PR is merging into **main** and not a feature branch because it contains a breaking change that I want to roll into June's deprecations.
Discussed in https://github.com/elastic/eui/pull/7781#discussion_r1619790000
The `compressed` prop by itself on `EuiCheckbox` and `EuiRadio` does nothing visually - it only has an impact on parent `EuiCheckboxGroup`/`EuiRadioGroup`s. We should remove it from the individual components as it's misleading API, and have the parent groups handle spacing via flex and gap instead.
While here I also noticed that EuiCheckboxGroup and EuiRadioGroup are missing EUI classNames and added those as well 🤷 
- Browser QA
- Docs site QA
~- [ ] Added …
=> [EuiCheckbox][EuiRadio] Remove `compressed` props

packages/eui/scripts/release.js
Yarn Berry doesn't commit or tag created versions. This updates our release script to commit and tag the updated `package.json` the same way Yarn Classic [did](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/version.js#L190).
=> build: update release script for yarn berry

packages/eui/changelogs/upcoming/7804.md, packages/eui/src/components/context_menu/context_menu_item.tsx
This PR includes changes to the type definition for `EuiContextMenuItemIcon` so that support for valid EUI `IconType` is explicit.
This change would be transparent to the end user, and is more a DX improvement.
=> Explicitly support EUI Icons in EuiContextMenuItemIcon type definition

packages/eui/src/services/accessibility/html_id_generator.test.tsx, packages/eui/src/services/hooks/useDependentState.test.tsx, packages/eui/src/services/hooks/useForceRender.test.tsx, packages/eui/src/services/hooks/useLatest.test.tsx, packages/eui/src/services/hooks/useUpdateEffect.test.tsx, packages/eui/src/services/window_event/window_event.test.tsx
Should be pretty straightforward! Was spurred into grabbing this as a small mental break when Tomasz recently mentioned our Enzyme tech debt 👀
=> [tech debt] Convert remaining Enzyme tests in `src/services` to RTL

packages/eui/src/components/basic_table/__snapshots__/custom_item_action.test.tsx.snap, packages/eui/src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, packages/eui/src/components/basic_table/basic_table.behavior.test.tsx, packages/eui/src/components/basic_table/custom_item_action.test.tsx, packages/eui/src/components/basic_table/in_memory_table.test.tsx
Grabbing various Enzyme tech debt tests as tech debt for fix-it-Fridays.
See git commit messages for slightly more detailed reasoning behind certain changes
=> [tech debt] Convert remaining table Enzyme tests to RTL

packages/eui/src-docs/src/views/avatar/avatar.js, packages/eui/src-docs/src/views/avatar/avatar_disabled.js, packages/eui/src-docs/src/views/avatar/avatar_example.js, packages/eui/src-docs/src/views/card/card_example.js, packages/eui/src-docs/src/views/card/card_image.tsx, packages/eui/src-docs/src/views/comment/comment_avatar.tsx, packages/eui/src-docs/src/views/datagrid/cells_popovers/cell_popover_rendercellpopover.tsx, packages/eui/src-docs/src/views/image/playground.js, packages/eui/src-docs/src/views/page_header/playground.js
Unsplash recently deprecated their source API, so we're moving onto Lorem Picsum instead (which we were already using in `EuiImage` docs I believe).
- https://eui.elastic.co/pr_7851/#/display/avatar
- https://eui.elastic.co/pr_7851/#/display/comment-list#timeline-avatar
- https://eui.elastic.co/pr_7851/#/display/card#images
- https://eui.elastic.co/pr_7851/#/tabular-content/data-grid-cells-popovers#completely-customizing-cell-popover-rendering
=> [Docs] Update Unsplash image URLs to point at picsum.photos instead

packages/eui/changelogs/upcoming/7855.md, packages/eui/src-docs/src/views/modal/modal.tsx, packages/eui/src/components/modal/modal.styles.ts, packages/eui/src/global_styling/mixins/_helpers.ts, packages/eui/src/global_styling/mixins/_shadow.scss, packages/eui/src/global_styling/utility/__snapshots__/utility.test.ts.snap
This bug was originally addressed in https://github.com/elastic/eui/issues/6328 / https://github.com/elastic/eui/pull/6343, but it turns out that it's affecting more components than just EuiModal (at least EuiFlyout as well - see https://github.com/elastic/kibana/issues/180828). The browser-level bug in question is being tracked in https://issues.chromium.org/issues/40778541.
The amazing @kqualters-elastic helped us look into the issue and came up with an excellent workaround. Chromium appears to be not correctly applying a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) to `mask-image`s with linear gradients and certain other children/properties. Using `transform: translateZ(0)` forces that stacking context …
=> Chromium workaround for CSS mask-image bug

.buildkite/pipelines/pipeline_pull_request_deploy_docs.yml, .buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml, .buildkite/pipelines/pipeline_release_deploy_docs.yml, .buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh, packages/docusaurus-theme/src/components/theme_context/index.tsx, packages/eui/scripts/deploy/deploy_docs
Resolves https://github.com/elastic/eui-private/issues/93.
This adds a script to build and deploy the new documentation website to the existing PR deploy pipeline.
=> ci: add buildkite step to build new docs website

packages/eui/changelogs/upcoming/7860.md, packages/eui/src/components/form/file_picker/file_picker.tsx
Closes: https://github.com/elastic/observability-dev/issues/3641
**Accessibility**
- Updated the `aria-label` attribute for the `EuiFilePicker` remove file button 
**Screen**
=> [EuiFilePicker] update aria-label for `Remove` button

packages/eui/changelogs/upcoming/7862.md, packages/eui/src-docs/src/views/theme/breakpoints/_breakpoints_js.tsx, packages/eui/src-docs/src/views/theme/breakpoints/breakpoints.tsx, packages/eui/src/components/provider/provider.tsx, packages/eui/src/services/breakpoint/current_breakpoint.tsx, packages/eui/src/services/theme/provider.test.tsx, packages/eui/src/services/theme/provider.tsx
closes https://github.com/elastic/eui/issues/7829
I originally started this work hoping it would be a quick fix/workaround solution to the broken docs example, but I quickly realized that `EuiThemeProvider` needed to be updated to handle `modify={{ breakpoint }}` overrides because it was currently not doing anything with that configuration.
We've also recently seen some dialogue in Slack with Fleet about needing to set custom breakpoints for certain screens/views/flyouts as opposed to entire plugins, so this work would strongly facilitate the ability to do that (currently difficult or not possible).
> [!NOTE]
> **Not addressed in this PR:**
> "I would still consider adding guidelines to flyout in our design system. it's important so when designers use 1200 version, they know what design …
=> [EuiThemeProvider] Allow nested `modify.breakpoint` overrides

packages/docusaurus-theme/src/components/call_out/index.tsx, packages/docusaurus-theme/src/components/theme_context/theme_overrides.ts, packages/docusaurus-theme/src/theme/Admonition/Type/Danger.tsx, packages/docusaurus-theme/src/theme/Admonition/Type/Info.tsx, packages/docusaurus-theme/src/theme/Admonition/Type/Note.tsx, packages/docusaurus-theme/src/theme/Admonition/Type/Tip.tsx, packages/docusaurus-theme/src/theme/Admonition/Type/Warning.tsx, packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx, packages/docusaurus-theme/src/theme/Footer/index.tsx, packages/docusaurus-theme/src/theme/MDXComponents/A.tsx, packages/docusaurus-theme/src/theme/MDXComponents/Code.tsx, packages/docusaurus-theme/src/theme/MDXComponents/Heading.tsx, packages/docusaurus-theme/src/theme/MDXContent/index.tsx, packages/docusaurus-theme/src/theme/Root.styles.ts, packages/docusaurus-theme/src/theme/Root.tsx, packages/website/docs/01_guidelines/testing/introduction.mdx, packages/website/docs/01_guidelines/testing/recommendations.mdx
closes: #7795 
relates to #7822 
>[!IMPORTANT]
> ~Parts of this PR (anything related to the ColorModeToggle) was added as a separate PR [here](https://github.com/elastic/eui/pull/7846) but kept in this PR as well for testing purposes. That previous PR for ColorModeToggle should be reviewed and merged before this one.~ Update: The PR was merged and this PR rebased.
This PR updates the base global styles for the new EUI+ docs and additionally adds the first style updates for doc content components.
- swizzles `MDXContent` (wrap) and updates it to use `EuiText` + custom EUI+ adjustments to ensure markdown content styling (text, lists etc)
- swizzles `DocItem/Content` (wrap) and adds custom styles for the document heading
- swizzles `MDXComponents/A` and `MDXComponents/Code` (wrap) and uses …
=> [EUI+] Initial typography and doc content updates

packages/eui/.storybook/addons/code-snippet/decorators/utils.ts
After merging the [Storybook code-snippet addon](https://github.com/elastic/eui/pull/7716) feature and right after the [EUIColorPicker Emotion conversion](https://github.com/elastic/eui/pull/7859) updates, an issue emerged in the `code-snippet` where Storybook previews render an error due to fewer rendered (conditional) hooks. (see an affected component [here](https://eui.elastic.co/storybook/index.html?path=/story/forms-euicolorpicker-euicolorpicker--playground))
This is due to the functionality within the `code-snippet` addon that checks for the story's defaultProps and has to evaluate components where needed to get to the right react element (recursively checking children until the story element is found).
This can be fixed (and optimized) by making sure we only check for the default …
=> [FIX] prevent errors around fewer/more hooks in Storybook

packages/eui/changelogs/upcoming/7864.md, packages/eui/src/components/stat/__snapshots__/stat.test.tsx.snap, packages/eui/src/components/stat/stat.tsx
Closes: https://github.com/elastic/observability-dev/issues/3630
Closes: https://github.com/elastic/observability-dev/issues/3634
Closes: https://github.com/elastic/observability-dev/issues/3633
Closes: https://github.com/elastic/observability-dev/issues/3632
Closes: https://github.com/elastic/observability-dev/issues/3631
**Summary:**
1. improved the accessibility experience of `EuiStat` by removing extra `aria-hidden=true` attribute
2. removed extra `eui-screen-reader`
=> [EuiStat] Accessibility - removed `aria-hidden=true` attribute

packages/eui/.storybook/addons/code-snippet/components/panel.tsx, packages/eui/.storybook/addons/code-snippet/constants.ts, packages/eui/.storybook/addons/code-snippet/decorators/jsx_decorator.tsx, packages/eui/.storybook/addons/code-snippet/types.ts
This PR adds an additional `try/catch` wrapper on the main functionality of the Storybook `code-snippet` addon to prevent any potential errors in the code snippet from crashing the Storybook preview and making local development impossible. The addon will return no code snippet if an error occurred and log the error to the console.
This does not actually affect any story currently but would be an issue if code is changed/added to a version that the code snippet doesn't support yet. E.g. the functionality to resolve the Emotion `css` prop is currently not fully supporting all cases, and can break otherwise.
There is not actual way to QA this in the existing Storybook
=> [FIX] Prevent Storybook code-snippet errors crashing the story preview

packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx, packages/docusaurus-theme/src/theme/MDXContent/index.tsx, packages/website/README.md, packages/website/docusaurus.config.ts, packages/website/package.json, yarn.lock
This resolves #7877 by integrating `docusaurus-lunr-search` and adding a data attribute to inform it what content to index.
=> feat: add search to the new documentation website

packages/docusaurus-theme/src/theme/DocBreadcrumbs/Items/Home/index.tsx, packages/docusaurus-theme/src/theme/DocBreadcrumbs/Items/item.styles.ts, packages/docusaurus-theme/src/theme/DocBreadcrumbs/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Layout/index.tsx, packages/docusaurus-theme/src/theme/DocItem/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Main/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/ExpandButton/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/index.tsx, packages/docusaurus-theme/src/theme/DocVersionBadge/index.tsx, packages/docusaurus-theme/src/theme/DocVersionBanner/index.tsx, packages/docusaurus-theme/src/theme/DocVersionRoot/index.tsx, packages/docusaurus-theme/src/theme/theme.d.ts
closes #7882 
- ejects more Docusaurus components to ensure nested ejected components work (they need to shared the same context)
- this is a bit of a snowball because the higher up we need to eject the more we need to eject with it if the components use provider hooks
- adds ejected breadcrumbs components and updates styles to align with current initial [design](https://www.figma.com/design/g5Vk0k2DgeQPCPBoWmun2U/EUI%2B-docs?node-id=20-37183&m=dev)
=> [EUI+] Implement Breadcrumbs design changes

packages/eui/src/components/date_picker/react-datepicker/src/index.d.ts
There was no description for the `yearDropdownItemNumber` prop on [EuiDatePicker](http://localhost:8030/#/forms/date-picker). I added a description. This was prompted by https://github.com/elastic/eui/issues/7869.
Make sure the prop description looks good on this page: https://eui.elastic.co/pr_7887/index.html#/forms/date-picker
=> Updated yearDropdownItemNumber prop description

.yarn/patches/@types-jsdom-npm-20.0.1-5bb899e006.patch, package.json, yarn.lock
This fixes a recently introduced issue in https://github.com/elastic/eui/pull/7821, causing EUI to fail to build. The upgraded `@types/jsdom` used by Jest v29 is incompatible with TypeScript 4 and it needs to be [patched](https://github.com/microsoft/vscode-jupyter/pull/7987/files) in order to work properly.
=> fix: patch `@types/jsdom` to work with TypeScript 4.x

.yarnrc.yml, packages/eui/package.json
This PR enables dependency hoisting on root level via `nmHoistingLimits: none` in the `.yarnrc.yml`.
This ensures that the `/docusaurus-theme` and `/website` packages resolve shared dependencies properly.
To not break the existing build of the `/eui` package, this package is excluded from the hoisting by setting `"hoistingLimits": "workspaces"` in it's `package.json` which ensures its dependencies are not hoisted beyond its workspace scope.
>[!NOTE]
> This update fixes the issue we encountered with Docusaurus ejected components for EUI+ that were relying on a specific context and were incorrectly using a different instance of the expected provider, resulting in errors like: `Hook useNavbarMobileSidebar is called outside the <NavbarMobileSidebarProvider>. `
- `yarn start`
- `yarn …
=> [BUILD] Support dependency hoisting

packages/docusaurus-theme/src/components/demo/code_transformer.ts, packages/docusaurus-theme/src/components/demo/demo.tsx, packages/docusaurus-theme/src/components/demo/editor/editor.tsx, packages/docusaurus-theme/src/components/demo/preview/preview.tsx, packages/docusaurus-theme/src/components/demo/scope.ts, packages/website/docs/02_components/navigation/button/overview.mdx
Resolves #7866.
This adds a custom code transformer to our `<Demo>` component that makes the existing component examples work with `react-live`. The major factor was that `react-live` only supports code that's just a JSX component or render function declaration. There's no way to define variables outside of the render function or have import/export statements.
The new code transformer removes any import statements because all externals should always come from the `scope`, and wraps the source code in an IIFE to support defining variables and functions outside of the render function as we often do in our examples.
=> feat: add code transformer to `<Demo>` component

packages/eui/changelogs/upcoming/7905.md, packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx, packages/eui/src/components/date_picker/super_date_picker/super_date_picker.tsx
Following the addition of the new `refreshMinInterval` prop to `EuiSuperDatePicker` in #7516, we missed passing this prop to `EuiQuickSelectPopover`
Notice changing the interval from `EuiAutoRefreshButton` properly validates against the `minInterval`. But when changing the interval from within `EuiQuickSelectPopover`, the validation is skipped.
Related to https://github.com/elastic/kibana/pull/188881
- ~[ ] Added or updated **[jest](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/unit-testing.md) and [cypress](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/cypress-testing.md) tests**~ - Skipped, just a basic prop pass
=> fix: `refreshMinInterval` for use in `EuiQuickSelectPopover`

packages/eui/src-docs/src/views/form_controls/form_control_layout_range.tsx
https://eui.elastic.co/#/forms/form-controls#form-control-layout-delimited was showing broken styling on raw `<input type="number">`s due to changes in Emotion conversions. Switching these to `<EuiFieldNumber />`s fixes the styling.
N/A, docs only
=> [Docs] Fix EuiFormControlLayoutDelimited examples with broken input styles

.yarn/patches/react-live-npm-4.1.7-7b41625faa.patch, packages/docusaurus-theme/package.json, packages/docusaurus-theme/src/components/demo/context.ts, packages/docusaurus-theme/src/components/demo/demo.tsx, packages/docusaurus-theme/src/components/demo/editor/editor.tsx, packages/docusaurus-theme/src/components/demo/preview/preview.tsx, packages/docusaurus-theme/src/components/demo/scope.ts, packages/docusaurus-theme/src/components/demo/source/get_source_from_children.ts, packages/docusaurus-theme/src/theme/CodeBlock/index.tsx, packages/docusaurus-theme/src/theme/MDXComponents/Code.tsx, packages/docusaurus-theme/src/theme/theme.d.ts, packages/website/docs/02_components/navigation/button/overview.mdx, yarn.lock
Resolves https://github.com/elastic/eui/issues/7899.
This PR adds support for creating interactive component examples without the need to wrap code blocks with `<Demo>` in MDX. Now we can define simple interactive examples like this (ignore `//` at the beginning of each line):
```markdown
// ```tsx interactive
// <EuiButton>Button</EuiButton>
// ```
```
An added benefit to that is greatly increased Github preview readability
=> feat: Add support for simplified interactive demo syntax using code blocks

packages/docusaurus-theme/package.json, packages/website/package.json, yarn.lock
This PR updates previously conflicting dependency versions in `docusaurus-theme` and `website` packages to properly access `docusaurus-theme`-initialized `EuiProvider` overrides in `website` pages.
1. Checkout this branch locally
2. Run `yarn` to install dependencies
3. Edit `packages/docusaurus-theme/src/components/theme_context/theme_overrides.ts` and apply any overrides
4. Build `docusaurus-theme`
5. Edit `packages/website/src/pages/index.tsx` to add `console.log(useEuiTheme())` in the render function
6. Run `yarn start` in the website package directory
7. Confirm the console.log contains values overridden in the theme
=> build: unify website dependencies

packages/eui/src-docs/src/views/markdown_editor/markdown_link_validation.js, packages/eui/src-docs/src/views/markdown_editor/markdown_plugin_example.js
The previous example code was polluting the default link validator plugin, leading to https://eui.elastic.co/v94.2.0/#/editors-syntax/markdown-format#link-validation-for-security incorrectly not parsing `http` links. This PR fixes the example to use the new `exclude` configs we added in #7676, and is overall a significantly cleaner approach in any case.
N/A, docs only change
=> [Docs] Fix EuiMarkdownEditor plugin example polluting other examples

.yarn/patches/infima-npm-0.2.0-alpha.43-8d3b77b44d.patch, package.json, packages/docusaurus-theme/src/components/prop_table/extended_types.tsx, packages/docusaurus-theme/src/components/prop_table/extended_types_info.ts, packages/docusaurus-theme/src/components/prop_table/prop_table.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx, packages/eui-docgen/src/process_component.ts, packages/website/README.md, packages/website/docs/docgen_demo.mdx, yarn.lock
This PR improves on the existing PoC `PropTable` component. It cleans it up, fixes styles and data rendering, and adds unique IDs to all props so we can easily link to them.
=> feat: Add `PropTable` component to EUI docusaurus theme

.buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh, packages/website/docusaurus.config.ts
Resolves https://github.com/elastic/eui-private/issues/108
This PR adds Google Tag Manager integration to the new documentation site.
=> feat(website): setup google tag manager

packages/eui/src/components/combo_box/combo_box.spec.tsx, packages/eui/src/components/datagrid/body/cell/data_grid_cell_popover.spec.tsx, packages/eui/src/components/form/range/range.spec.tsx, packages/eui/src/components/selectable/selectable.spec.tsx, packages/eui/src/components/text_truncate/text_truncate.spec.tsx, packages/eui/src/components/text_truncate/utils.spec.tsx
This fixes an issue caused by differences in text rendering in the latest Chrome v127.
This is certainly a hotfix. Ultimately, we should adjust our types to not be as sensitive, or refactor them to check the sizes in a more stable manner.
=> hotfix: update pixel size values in cypress tests to correct for Chrome 127 text rendering changes

packages/website/docusaurus.config.ts
This PR ensures that Docusaurus can run locally as expected when no GTM `containerId` is available. This is a small update to the changes done in [this PR](https://github.com/elastic/eui/pull/7933).
This affects both dev environment and production build BUT **locally** only.
There is no issue with the production build in CI as the `containerId` is provided in the pipeline from the vault.
- `gh pr checkout 7938`
- go to `/packages/website`
- install all local dependencies `yarn workspaces foreach -Rpti --from @elastic/eui-website run build` 
- start the local dev environment `yarn start`
- build production locally and run it: `yarn build && yarn serve`
=> [Eui+] Fix docusaurus containerId for local environment

packages/eui/changelogs/upcoming/7935.md, packages/eui/src/components/empty_prompt/empty_prompt.stories.tsx, packages/eui/src/components/empty_prompt/empty_prompt.styles.ts
@kpatticha reported an issue in APM  where EuiEmptyPrompt stops displaying with desktop/larger styles. This is because APM uses a custom `xxl: 1600` breakpoint, and EuiEmptyPrompt's styles previously used an `euiBreakpoint('l', 'xl')` which was not accounting for larger breakpoints.
Switching the component to `euiMinBreakpoint` resolves the issue for consumers with custom larger breakpoints.
- Go to https://eui.elastic.co/pr_7935/storybook/?path=/story/display-euiemptyprompt--page-template
- Inspect `.euiEmptyPrompt__main` in devtools
- Browser QA
- Code quality …
=> [EuiEmptyPrompt] Fix styles to work correctly with custom larger breakpoints

packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.styles.ts, packages/eui/src/components/flyout/flyout.styles.ts, packages/eui/src/components/form/form.styles.ts, packages/eui/src/components/list_group/list_group.styles.ts, packages/eui/src/components/popover/input_popover.tsx, packages/eui/src/components/search_bar/search_bar.styles.ts
As we've established in #7486, color computations are expensive to recalculate repeatedly and should be memoized where possible. This is fine for component styles (#7529), but our various `euiComponentVariables` utilities are not getting memoized except as part of component styles.
`euiFormVariables` is particularly chonky and likely bears examining more closely, but in the interim I'm solving this particular microperf irritant by creating a separate utility just to grab the `maxWidth` size for components that _only_ need this token (a surprisingly high number).
My upcoming EuiComboBox conversion will be utilizing this PR as well for cleaner and more performant code ✨ 
- Browser QA - N/A, fairly straightforward PR that doesn't need excessive cross-browser testing
- …
=> [Emotion][microperf] Separate form max-width variable to its own utility

packages/website/src/components/homepage/banner/index.tsx, packages/website/src/pages/index.tsx
This PR implements a welcome banner to highlight the new docs page.
>[!IMPORTANT]
> This PR is currently still a DRAFT as the design and content of the banner needs alignment.
=> [EUI+] Implement welcome banner

packages/website/docs/patterns/pre_ga_badges.mdx, packages/website/package.json, yarn.lock
This PR fixes the issue caused by failing `crypto` library used in docusaurus to process images when used on Node 18+ with the latest OpenSSL.
More specifically, the `crypto` library is used for base64 encoding of generated image placeholders.
=> feat(website): enable legacy openssl provider

packages/eui/changelogs/upcoming/7970.md, packages/eui/src/components/form/field_search/field_search.tsx, packages/eui/src/components/search_bar/__snapshots__/search_bar.test.tsx.snap, packages/eui/src/components/selectable/__snapshots__/selectable.test.tsx.snap, packages/eui/src/components/selectable/selectable_search/__snapshots__/selectable_search.test.tsx.snap
This pull request addresses issue [#138](https://github.com/elastic/observability-accessibility/issues/138) by updating the `aria-label` attribute of the clear button. The previous label, `Clear input` has been enhanced to `Clear search input` to provide more specific context for users who rely on screen readers. This change improves accessibility by making the button's function clearer, ensuring that all users have a more intuitive experience.
1. Updated the `aria-label` attribute from `Clear input` to `Clear search input` to enhance clarity for screen reader users.
fyi: @dave-gus and @1Copenut
=> [EuiFieldSearch] update clear button `aria-label`

packages/eui/src/components/form/switch/switch.styles.ts
This is blocking/causing FTR failures in https://github.com/elastic/kibana/pull/190752 😬 It has no effect on actual browsers/productions, just on Selenium 💀 
N/A, skipping because it doesn't affect end-users or consumers, just Kibana, and we have another item in the changelog queue to release from
=> [EuiSwitch] Re-add `pointer-events: none` to switch button children

.buildkite/scripts/pipelines/pipeline_test.sh, packages/eui/cypress.config.ts, packages/eui/package.json, packages/eui/scripts/jest/config.js, yarn.lock
This PR configures [Buildkite Test Analytics](https://buildkite.com/test-analytics) for EUI's cypress and jest tests.
=> ci: setup buildkite test analytics for cypress and jest tests

packages/eui/src/components/form/form_control_layout/index.ts
Required by https://github.com/elastic/kibana/pull/190752
Kibana's unified search query string input was using a direct className to get form control icon styling:
https://github.com/elastic/kibana/blob/74d88580a5e3d24c6421942f2c96a8dfd56d39d1/src/plugins/unified_search/public/query_string_input/query_string_input.tsx#L854-L856
Which will no longer work with its Emotion conversion. I had assumed I could reach into `@elastic/eui/lib/components` directly to import `EuiFormControlLayoutIcons`, but Kibana's optimizer is throwing build errors when I attempt to do so (related to importing EuiIcon 💀)
N/A
N/A, backport only and a Kibana-only concern
=> Export EuiFormControlLayoutIcons

packages/eui/src/components/form/checkbox/checkbox.styles.ts, packages/eui/src/components/form/checkbox/checkbox.tsx, packages/eui/src/components/form/form.styles.test.tsx, packages/eui/src/components/form/form.styles.ts, packages/eui/src/components/form/radio/radio.styles.ts, packages/eui/src/components/form/radio/radio.test.tsx, packages/eui/src/components/form/radio/radio.tsx
This PR is needed for Cloud's latest Kibana upgrade: https://github.com/elastic/cloud/pull/130938
The error output is something like `+label` isn't a valid selector. This test failure afects Cloud's RTL tests and does not affect browsers, only jsdom's test environment, due to nwsapi's spotty `:has()` selector support.
This was reproducible in local EUI as well (first commit will fail tests without the second commit), and appears to primarily affect the `getByRole` API with the `name` option parameter (although in Cloud it affects `getByLabelText` as well).
This PR can and should be reverted when https://github.com/dperini/nwsapi/issues/123 is fixed and a new version of nwsapi is available.
=> Workaround for `:has` CSS selector that nwsapi/jest can't parse

packages/eui/src-docs/src/views/call_out/warning.tsx
I updated the callout example to use a primary button rather than a secondary button, to provide better contrast.
I don't think this is a pattern we want to inadvertently encourage via our docs.
https://eui.elastic.co/#/display/callout
Before:
After:
=> Updated callout example

packages/eui/changelogs/upcoming/7987.md, packages/eui/src-docs/src/views/date_picker/states.js, packages/eui/src/components/date_picker/date_picker.stories.tsx, packages/eui/src/components/date_picker/date_picker.styles.ts, packages/eui/src/components/date_picker/date_picker.test.tsx, packages/eui/src/components/date_picker/date_picker.tsx, packages/eui/src/components/date_picker/date_picker_range.styles.ts
I discovered an inline EuiDatePicker border regression while investigating #5958, and I also discovered some very incorrect usages of `EuiFormControlLayout` while grepping for the component in Kibana.
Adding `append`/`prepend` nodes to EuiDatePicker will help with a significant amount of those use cases, as people were using the layout wrapper just for appending/prepending info to the date picker input.
- Go to https://eui.elastic.co/pr_7987/#/forms/date-picker#date-picker-inline
| <img width="456" alt="" src="https://github.com/user-attachments/assets/aaa462a8-d1ea-4fb2-a119-0aba436199f9"> | <img width="449" alt="" src="https://github.com/user-attachments/assets/be6b8b9e-1e09-4fc4-a1a7-5850d59e3b3c"> | 
- Go to …
=> [EuiDatePicker] Fix `inline` rendering + add `append`/`prepend` support

packages/eui/changelogs/upcoming/7999.md, packages/eui/src/components/datagrid/body/header/_data_grid_header_row.scss
This PR fixes an issue that was introducede with this previously merged [PR](https://github.com/elastic/eui/pull/7898) that updated `EuiDataGrid` header cells to support interactive content. As part of that PR the size of the actions button was increased via `padding` to satisfy the min. target size accessibility requirements.
This causes the header cells to increase in height when the actions button is visible on hover/focus for small cell fontSize/lineHeight settings.
- adds negative margin for the action button that is equivalent the added padding to ensure the button still uses the same vertical space
_issue_
https://github.com/user-attachments/assets/33d779de-5289-4e2e-9373-fc705687814c
_fixed_
https://github.com/user-attachments/assets/27180c31-dfa2-460b-b097-5bf63c6e507f
- open the …
=> [EuiDataGrid] Fix header actions button causing cell height changes

packages/eui/changelogs/upcoming/7993.md, packages/eui/src/components/text/text.stories.tsx, packages/eui/src/components/text/text.test.tsx, packages/eui/src/components/text/text.tsx, packages/eui/src/components/text/text_align.stories.tsx, packages/eui/src/components/text/text_align.test.tsx, packages/eui/src/components/text/text_align.tsx, packages/eui/src/components/text/text_color.test.tsx, packages/eui/src/components/text/text_color.tsx, packages/eui/src/components/text/types.ts
closes #7975 
This PR adds support for a `component` prop on `EuiText` and related components `EuiTextColor` and `EuiTextAlign` to support rendering different root elements. Currently `EuiText` always outputs a `div` element, which results in invalid html issues where `EuiText` is not the wrapper but used in a composition where the div would be a child of a `p` for example.
- adds prop `component` with values `p`, `div` and `span` (default value stays `div` for parity) for `EuiText` and `EuiTextAlign`
- updates `component` prop on `EuiText` to match the same values as for the other two text components
- [EuiText](https://eui.elastic.co/pr_7993/storybook/index.html?path=/story/display-euitext-euitext--playground)
- [EuiTextColor](https://eui.elastic.co/pr_7993/storybook/index.html?path=/sto …
=> [EuiText] Support component prop

packages/eui/changelogs/upcoming/7994.md, packages/eui/i18ntokens.json, packages/eui/src/components/basic_table/__snapshots__/collapsed_item_actions.test.tsx.snap, packages/eui/src/components/basic_table/basic_table.tsx, packages/eui/src/components/basic_table/collapsed_item_actions.test.tsx, packages/eui/src/components/basic_table/collapsed_item_actions.tsx
closes #7883 
This PR updates the `aria-label` on the `CollapsedItemActions` used in `EuiBasicTable` to add a reference to the current row to ensure the `aria-label` is unique and provides context. 
- passes current row index as new prop `displayedRowIndex` on `CollapsedItemActions` to use in the `aria-label` on the actions button
- refactors usages of `<EuiI18n>` to use the `useEuiI18n` hook instead
- [EuiBasicTable](https://eui.elastic.co/pr_7994/storybook/index.html?path=/story/tabular-content-euibasictable--playground)
- [EuiInMemoryTable](https://eui.elastic.co/pr_7994/storybook/index.html?path=/story/tabular-content-euiinmemorytable--kitchen-sink)
- Browser QA
- Docs site QA
=> [EuiBasicTable] Ensure action button aria-label is unique

packages/eui/changelogs/upcoming/8010.md, packages/eui/src/components/flyout/flyout_resizable.stories.tsx, packages/eui/src/components/flyout/flyout_resizable.styles.ts, packages/eui/src/components/flyout/flyout_resizable.tsx
closes https://github.com/elastic/eui/issues/7988
This PR fixes the scenario where the content to the left of the resizable flyout has a scrollbar (or any other clickable element that butts up against the flyout), and the placement of the resize border/indicator button prevents the thing it's overlaying from being clicked:
| <img width="336" alt="" src="https://github.com/user-attachments/assets/e22e1b5b-c9a3-4dfe-9ed3-7d3ba2870d35"> | <img width="322" alt="" src="https://github.com/user-attachments/assets/5818b837-da10-44ce-8443-847f5adf88d2"> | 
FYI that I kept the centered styling on flyouts with overlay masks, because those overlays will close the entire flyout on outside click which feels super disruptive - I felt the extra space there would be …
=> [EuiFlyoutResizable] Do not extend resize click area past flyout for flyouts with no overlays

packages/docusaurus-theme/package.json, packages/docusaurus-theme/src/theme/DocBreadcrumbs/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Footer/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Layout/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Metadata/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Paginator/index.tsx, packages/docusaurus-theme/src/theme/DocItem/TOC/Desktop/index.tsx, packages/docusaurus-theme/src/theme/DocItem/TOC/Mobile/index.tsx, packages/docusaurus-theme/src/theme/DocItem/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Main/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/index.tsx, packages/docusaurus-theme/src/theme/DocSidebarItem/Category/index.tsx, packages/docusaurus-theme/src/theme/DocSidebarItem/Link/index.tsx, packages/docusaurus-theme/src/theme/DocSidebarItems/index.tsx, packages/website/package.json, yarn.lock
This upgrades `docusaurus` and related dependencies to version 3.5.2. There are a few changes that needed updating our code, specifically:
* `@docusaurus/theme-common` shouldn't depend on docs content ([original commit](https://github.com/facebook/docusaurus/commit/026a317fc4300e6ae1817404519d229d2ca684a4))
* replace `@theme/Unlisted` with `@theme/ContentVisibility` ([original commit](https://github.com/facebook/docusaurus/commit/95ab9f8ee4f58edb03da8d408e9583a681e6ef14))
=> chore: upgrade to docusaurus 3.5.2

packages/eui/changelogs/upcoming/8020.md, packages/eui/src/components/date_picker/date_picker.test.tsx, packages/eui/src/components/date_picker/date_picker.tsx
I noticed this minor bug when fixing form control layouts in Kibana (https://github.com/elastic/kibana/pull/192779).
| <img width="484" alt="" src="https://github.com/user-attachments/assets/ec96c69c-8ee0-401c-b6da-8243e86988f7"> | <img width="479" alt="" src="https://github.com/user-attachments/assets/8e1c8689-2deb-43bd-8057-724c9e464e31"> | 
All other clearable inputs (e.g. EuiFieldSearch, EuiFilePicker, EuiColorPicker) hide the clear button when disabled - this component is following suit.
- Go to https://eui.elastic.co/pr_8020/storybook/?path=/story/forms-euidatepicker--playground&args=disabled:!true
- Go to https://eui.elastic.co/pr_8020/storybook/?path=/story/forms-euidatepicker--playground
- Browser QA
~- [ ] …
=> [EuiDatePicker] Fix clear button appearing when input is disabled

packages/eui/changelogs/upcoming/8021.md, packages/eui/src-docs/src/views/resizable_container/resizable_button_indicator.tsx, packages/eui/src-docs/src/views/resizable_container/resizable_container_basic.tsx, packages/eui/src-docs/src/views/resizable_container/resizable_container_callbacks.tsx, packages/eui/src-docs/src/views/resizable_container/resizable_container_reset_values.tsx, packages/eui/src-docs/src/views/resizable_container/resizable_container_vertical.tsx, packages/eui/src-docs/src/views/resizable_container/resizable_panel_collapsible_options.tsx, packages/eui/src/components/resizable_container/__snapshots__/resizable_button.test.tsx.snap, packages/eui/src/components/resizable_container/__snapshots__/resizable_container.test.tsx.snap, packages/eui/src/components/resizable_container/resizable_button.stories.tsx, packages/eui/src/components/resizable_container/resizable_button.styles.ts, packages/eui/src/components/resizable_container/resizable_button.tsx, packages/eui/src/components/resizable_container/resizable_container.stories.tsx
Follow up to https://github.com/elastic/eui/pull/8010#issuecomment-2338811662 and https://github.com/elastic/eui/issues/7988
This PR adds the `accountForScrollbars` prop to EuiResizableButton, which allows consumers to conditionally remove the negative margins behavior on the button if it causes the button to block scrollbars.
| <img width="633" alt="" src="https://github.com/user-attachments/assets/c23765ab-e89d-47a8-a58c-de2c365e8776"> | <img width="644" alt="" src="https://github.com/user-attachments/assets/1cb2f48a-5faa-439c-aa87-1e73900c0eea"> | 
- Go to https://eui.elastic.co/pr_8021/#/layout/resizable-container
- Go to https://eui.elastic.co/pr_8021/storybook/?path=/story/layout-euiresizablecontainer-subcomponents-euiresizablebutton--playground …
=> [EuiResizableButton] Add new prop to allow consumers to account for overlap with scrollbars

packages/eui/changelogs/upcoming/8040.md, packages/eui/src/components/provider/system_color_mode/system_color_mode_provider.server.test.tsx, packages/eui/src/components/provider/system_color_mode/system_color_mode_provider.tsx
Follow up to https://github.com/elastic/eui/pull/8026
This is causing issues in the [latest Kibana upgrade](https://github.com/elastic/kibana/pull/193805) and will require a backport 😬 
I wrote a SSR unit test for this that highlighted the issue (fails without the `typeof window` check) and should fail if it regresses again in the future 🤞 
N/A, test coverage should be sufficient
- Browser QA - N/A, affects SSR only
=> [EuiProvider] Fix SSR crashing during new system color mode detection

packages/eui/changelogs/upcoming/8047.md, packages/eui/src/components/search_bar/search_box.tsx
Close https://github.com/elastic/eui/issues/8018
As discussed https://github.com/elastic/eui/issues/8018, while trying to upgade Kibana to React@18 so far we've found a single place where EUI doesn't work nicely with React@18 in legacy mode. 
The workarond we've found is to use `useLayoutEffect` in this component. Hopefull this won't have significant downsides.  
Here is the React issue I filed: `https://github.com/facebook/react/issues/31023`
I was running Kibana tests with this change and there was no issues discovered 
=> [EuiSearchBox][React@18 Legacy Mode] `useLayoutEffect` in `search_box`

packages/docusaurus-theme/src/theme/Root.tsx, packages/eui/changelogs/upcoming/8045.md, packages/eui/cypress/support/component-index.html, packages/eui/cypress/webpack.config.js, packages/eui/scripts/compile-scss.js
Our compiled/exported `dist/*.css` files no longer contain any meaningful CSS, just `@keyframes` animations that have zero usage in Kibana. We should go ahead and remove the file(s) fully at this point.
| <img width="457" alt="" src="https://github.com/user-attachments/assets/eb6060a1-2231-43d3-b831-7c930702f569"> | <img width="468" alt="" src="https://github.com/user-attachments/assets/66178c3b-6cfd-4c0c-b9b2-f0f7ed668a9c"> | 
Pending PRs:
- https://github.com/elastic/kibana/pull/194082 (failed)
- https://github.com/elastic/kibana/pull/194237
- https://github.com/elastic/cloud/pull/132101
N/A, if CI/`yarn build-pack` passes, we should be set
- Docs site QA - N/A, already handled in #8029
- Release …
=> [Emotion] Delete distributed `*.css` files

.github/workflows/stale_issues.yml
Fixes the required permissions for the GitHub actions in charge of managing the stale issues or PRs
There are some missing permissions and some error annotations in the GitHub workflow:
I discovered these errors as part of the CICD Observability for GitHub actions that we enabled some time ago and with some alerting when searching for `Resource not accessible by integration`
For further details please see https://github.com/actions/stale/issues/840
N/A, internal only
=> github-actions: add missing permissions

packages/eui/README.md
I pruned the duplicate READMEs in #8029 (between `/` and `/packages/eui/` without realizing that `/packages/eui/` is what determines what renders in https://www.npmjs.com/package/@elastic/eui, so we now have a very sad looking NPM package 🤦 
I've brought back some of the higher level content with links without going so far as to duplicate the FAQ and more detailed docs/copy from the root README.
- https://github.com/elastic/eui/blob/f75285ffd17aa119a700276828b0101782601b94/packages/eui/README.md
N/A, internal only
=> Re-add more of a README to `packages/eui/`

packages/eui/changelogs/upcoming/8065.md, packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/__snapshots__/collapsible_nav_link.test.tsx.snap, packages/eui/src/components/link/__snapshots__/link.test.tsx.snap, packages/eui/src/components/link/external_link_icon.test.tsx, packages/eui/src/components/link/external_link_icon.tsx, packages/eui/src/components/list_group/list_group_item.test.tsx
Closes: https://github.com/elastic/eui/issues/8063
Links should be announced clearly for screen reader users using the visible text on the page. Adding extra words or descriptions can create confusion for users relying on assistive technologies.
1. `EuiExternalLinkIcon` Component: Added `role="presentation"` to the external icon, ensuring it is ignored by screen readers.
2. `EuiExternalLinkIcon` Component: Updated the screen reader-only text to properly handle both cases—external links and links that open in a new tab (_blank).
=> fix: Additional word is being announced by screen reader for the external links

packages/eui/src/components/button/button_display/_button_display.styles.ts
> [!note]
> This doesn't fundamentally affect any actual visuals, because flex CSS was already handling centering button content for us. But it's nice not to have buggy CSS-in-JS in our codebase 😅 
This was missed during EuiButton's original Emotion conversion. Just for funsies, I'm going to dive into what was causing the bug:
- Our `logical*Style` utilities output **objects** of CSS key/values, e.g. `{ color: red }`
- Our `logical*CSS` utilities output **strings** of CSS, e.g. `'color: red;'`
- Emotion CSS that uses the ``` css`` ``` template literal can parse **both**.
- Regular template literals (``` `` ```), like the one being used in `euiButtonBaseCSS` (to avoid generating an extra emotion label, presumably), **cannot** parse objects, only strings. So the previous code was generating …
=> [EuiButtonDisplay] Fix missing text-align CSS

packages/eui/changelogs/upcoming/8061.md, packages/eui/src/components/date_picker/date_picker_range.styles.ts
Between the latest [v95.10.1](https://eui.elastic.co/v95.10.1/#/forms/date-picker#date-picker-range) and [v95.7.0](https://eui.elastic.co/v95.7.0/#/forms/date-picker#date-picker-range) the `fullWidth` prop stopped working as expected.
**Current behaviour:**
https://github.com/user-attachments/assets/7686b997-b2b1-495f-b892-b4d78cf89eae
**Expected behaviour:** 
https://github.com/user-attachments/assets/bc90b5ba-7844-48dd-a7d5-d441f5b03624
Because both controls (the start and end date) are within a flex parent, we can use `flex: 1` to make them take all the available space equally. I added a comment to highlight that it's important for `fullWidth` functionality because it's not applied conditionally based on the `fullWidth` value.
- Browser QA
- Docs site QA
- …
=> fix(date-picker-range): make inputs take the whole available space

packages/eui/cypress/support/setup/mount.tsx
In this [previous PR](https://github.com/elastic/eui/pull/8026) we removed the default `colorMode` on **EuiProvider** in favor of listening to system settings.
This causes issues in testing environments because our tests assert on LIGHT mode (e.g. color values). Tests will fail when the system setting is set to DARK mode because of this.
- adds static `colorMode="light"` on the wrapping **EuiProvider** for cypress tests
- checkout this PR
- set the local system setting for color mode to "dark"
- run `yarn test-cypress-dev` and run the test for `data_grid_cell.styles.spec.ts`
- verify the test does not fail
=> [Cypress] Add static colorMode for test environment

.github/workflows/stale_issues.yml
Essentially reverts #8059 and leaves more explicit notation as to why we do not want each individual job to have permissions - it's because we have separate jobs for issues vs PRs and separate stale/close durations.
N/A, dev/internal only
=> Fix stalebot config

.buildkite/scripts/lifecycle/pre_command.sh
Resolves https://github.com/elastic/eui-private/issues/122
This updates the path for where the Github PAT is stored in our vault. The updated path is already used in other places but wasn't used in the `pre_command` hook.
=> ci: update github PAT token secret path

packages/eui/changelogs/upcoming/8079.md, packages/eui/src/components/header/header_links/__snapshots__/header_links.test.tsx.snap, packages/eui/src/components/header/header_links/header_links.styles.ts, packages/eui/src/components/header/header_links/header_links.tsx
Will be used in Kibana for a scalable app menu bar related to One Discover
- https://eui.elastic.co/pr_8079/storybook/?path=/story/layout-euiheader-euiheaderlinks--playground&args=gutterSize:xxs
- Browser QA
- Docs site QA
~- [ ] Updated **[visual regression tests](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/visual-regression-testing.md)**~
~- [ ] If …
=> [EuiHeaderLinks] Add `xxs` gutterSize

packages/eui/changelogs/upcoming/8086.md, packages/eui/src/components/datagrid/utils/col_widths.test.ts, packages/eui/src/components/datagrid/utils/col_widths.ts
This PR reverts [changes done in this PR](https://github.com/elastic/eui/pull/8015/commits/fb3ff84f90b8a41e05a81ede5e3c60ac56e38c98) to store column widths after resize. While the change works for uncontrolled `EuiDataGrid`s, it currently does not allow for controlled usages to override saved widths anymore.
This is an issue in Kibana where column widths can be reset. 
We decided to revert the change for now and address it separately, as the issue was not specific to the [draggable column update](https://github.com/elastic/eui/pull/8015) but existed before.
=> [EuiDataGrid] Revert column width changes

packages/eui/changelogs/upcoming/8085.md, packages/eui/src/components/datagrid/controls/data_grid_toolbar.styles.ts
I recently noticed that the alerts table toolbar in security has items that were not vertically centered. I created fixes for that in Kibana but I think the actual fix would be to add `align-items: center;` to the actual wrapper classes, hence this PR. [[Kibana PR]](https://github.com/elastic/kibana/pull/196804)
Alerts table before:
Alerts table after:
TODO:
=> [EuiDataGrid] Vertically center toolbar `additionalControls` items

packages/eui/changelogs/upcoming/8089.md, packages/eui/src/components/comment_list/comment.tsx
closes https://github.com/elastic/eui/issues/8090
@jpcarey pinged us to let us know that `<EuiComment id="...">` was being incorrectly flagged via types, when in fact the component passes all attributes down to the HTMLElement node. I've fixed the typing of component to correctly reflect that / extend to all valid & accepted props.
| <img width="538" alt="" src="https://github.com/user-attachments/assets/280be951-160c-445e-aa93-41d3708cb31e"> | <img width="521" alt="" src="https://github.com/user-attachments/assets/8db15476-f1be-4819-9bcf-b5822a17e106"> | 
- Go to https://eui.elastic.co/pr_8089/#/display/comment-list#comment
- Click the `Props` tab
- Docs site QA
~- [ ] If …
=> [EuiComment] Fix typing to accurately reflect `...rest` spread

packages/docusaurus-theme/src/theme/DocItem/Content/index.tsx, packages/docusaurus-theme/src/theme/MDXContent/index.tsx, packages/website/src/components/homepage/header/index.tsx
This PR fixes EUI+ search by re-adding the necessary `markdown` class name to `DocItemContent` and setting the `data-search-children` attribute to a truthy value to allow proper heading recognition.
=> Fix EUI+ search not indexing heading elements

packages/eui/changelogs/upcoming/8101.md, packages/eui/src/components/context_menu/context_menu_panel.spec.tsx, packages/eui/src/components/context_menu/context_menu_panel.tsx
closes https://github.com/elastic/eui/issues/8094
This functionality allows consumers with, e.g. inputs (or other custom items that they may want to receive auto focus) to disable `EuiContextMenuPanel`'s initial focus logic via setting the index to `-1`.
Storybook arg testing:
- [`initialFocusedItemIndex={-1}`](https://eui.elastic.co/pr_8101/storybook/iframe.html?args=initialFocusedItemIndex:-1&showSnippet=undefined&id=navigation-euicontextmenu-euicontextmenupanel--playground&viewMode=story) should not focus anything
- [`initialFocusedItemIndex={0}`](https://eui.elastic.co/pr_8101/storybook/iframe.html?args=initialFocusedItemIndex:0&showSnippet=undefined&id=navigation-euicontextmenu-euicontextmenupanel--playground&viewMode=story) should focus the first context menu item on page load
- …
=> [EuiContextMenuPanel] Allow consumers to disable initial focus via `initialFocusedItemIndex={-1}`

packages/eui/changelogs/upcoming/8100.md, packages/eui/src/components/header/header.stories.tsx, packages/eui/src/components/header/header.styles.ts
This bug is reproducible in local Kibana by typing and searching for "api keys" and then clicking the result - the border goes away because the `append` label is not being passed:
| <img width="723" alt="" src="https://github.com/user-attachments/assets/6d04a0e0-7bb1-46c1-981f-d624d4c68e2c"> | <img width="716" alt="" src="https://github.com/user-attachments/assets/971251a0-0f0f-459f-b2bd-c4f53b3d5dec"> | 
Note: I regression-tested that append labels still look as before visually via VRT.
- Go to https://eui.elastic.co/pr_8100/storybook/?path=/story/layout-euiheader-euiheader--dark-theme-with-sitewide-search
- Browser QA …
=> [EuiSelectableTemplateSitewide] Fix border bug in Kibana when used in dark-themed EuiHeaders

packages/website/docs/components/theming/colors/utilities/use_eui_background_color_css_preview.tsx, packages/website/docs/components/theming/colors/utilities/use_eui_background_color_preview.tsx, packages/website/docs/components/theming/colors/utilities/use_eui_background_color_table.tsx
This replaces the auto-suggested imports from `@elastic/eui/src` with the correct `@elastic/eui` ones and fixes the new docs site builds.
=> docs: fix broken imports in color utilities

packages/eui/changelogs/upcoming/8105.md, packages/eui/src/components/combo_box/combo_box.spec.tsx, packages/eui/src/components/combo_box/combo_box.tsx
closes https://github.com/elastic/eui/issues/8104
closes https://github.com/elastic/eui/issues/7289
- Go to https://eui.elastic.co/pr_8105/storybook/?path=/story/forms-euicombobox--playground
- Tab to the X button next to the selected `Item 1`
- Select all items in the dropdown menu (arrow key and enter key to select items should still work as expected)
- Tab to the round X button
- Browser QA
~- [ ] Updated **[visual regression tests](https://github.com/elastic/eui/blob/main/wiki/contributing-to-eui/testing/visual-regression-testing.md)**~
~- [ ] If applicable, added the **breaking change** issue label (and filled out the breaking change …
=> [EuiComboBox] Fix enter key not working correctly on selection clear/deletion buttons

packages/eui-theme-borealis/src/variables/_font_weight.scss, packages/eui-theme-borealis/src/variables/_index.scss, packages/eui-theme-borealis/src/variables/_typography.scss, packages/eui-theme-borealis/src/variables/_typography.ts
closes https://github.com/elastic/eui-private/issues/129
This PR adds updates to the typography scale for the new theme. These changes are directly taken from this [PR](https://github.com/elastic/eui/pull/7942) that proposed the changes.
>[!IMPORTANT]
>[!NOTE]
Changes to the legacy JSON tokens will be done separately as part of this [task](https://github.com/elastic/eui-private/issues/138).
>[!NOTE]
This PR does not use the new theme yet in the docs, but the changes can be seen on this testing [PR](https://eui.elastic.co/pr_8083/index.html#/theming/typography/values)
=> [Visual Refresh] Update Typography scale

packages/eui/scripts/release.js
I noticed this issue in our release script while doing a few backports for 8.16. It likely started when we upgraded from Yarn Classic to Yarn Berry, but I couldn't find a recent bug report in the yarn repo about it.
- In CLI, run `yarn version v97.3.0-backport.0` - `package.json` should update correctly as expected:
- Now run `yarn version v97.3.0-backport.1` - notice that `package.json` _does not_ update as expected:
- Rerun `yarn version v97.3.0-backport.1` again and confirm that the second time, package.json is correct for whatever reason 🤷
N/A, internal/dev only
=> Fix `yarn version` bug with backports

packages/eui-theme-borealis/.babelrc.js, packages/eui-theme-borealis/package.json, packages/eui-theme-borealis/tsconfig.cjs.json, packages/eui-theme-borealis/tsconfig.types.json, packages/eui-theme-common/package.json, yarn.lock
This PR updates the builds for the new theme packages that ensure Kibana CI runs as expected:
- ensure core-js polyfills are handled as expected
- align `eui-theme-borealis` package build with `eui-theme-common` build to ensure both esm and cjs packages are available
=> [Visual Refresh] Fix theme package builds

packages/website/docs/components/editors_and_syntax/code.mdx, packages/website/docs/components/editors_and_syntax/markdown_editor.mdx, packages/website/docs/components/editors_and_syntax/markdown_format.mdx, packages/website/docs/components/forms/auto_refresh.mdx, packages/website/docs/components/forms/color_selection.mdx, packages/website/docs/components/forms/combo_box.mdx, packages/website/docs/components/forms/date_picker.mdx, packages/website/docs/components/forms/expression.mdx, packages/website/docs/components/forms/filter_group.mdx, packages/website/docs/components/forms/form_controls/overview.mdx, packages/website/docs/components/forms/form_layouts/overview.mdx, packages/website/docs/components/forms/form_validation/overview.mdx, packages/website/docs/components/forms/inline_edit.mdx, packages/website/docs/components/forms/range_sliders.mdx, packages/website/docs/components/forms/search_bar.mdx, packages/website/docs/components/forms/selectable.mdx, packages/website/docs/components/forms/selection_controls/overview.mdx, packages/website/docs/components/forms/super_select.mdx, packages/website/docs/components/navigation/pagination/overview.mdx, packages/website/docs/components/navigation/tree_view.mdx, packages/website/docs/components/tabular_content/in_memory_tables.mdx, packages/website/docs/components/tabular_content/tables.mdx, packages/website/docs/components/templates/page_template/overview.mdx, packages/website/docs/components/templates/sitewide_search.mdx, packages/website/docs/components/templates/super_date_picker.mdx
I added missing props tables to EUI+ pages. Check the issue for the whole list: [#139](https://github.com/elastic/eui-private/issues/139)
If you notice any more let me know, I can add them as part of this PR.
Use the staging link from the comment below. Cross-reference with the list in the issue ☝🏻
=> fix(website): add missing props tables

packages/docusaurus-theme/src/components/codesandbox_icon/codesandbox_icon.tsx, packages/website/README.md
The Codesandbox icon in the footer of each example in EUI+ doesn't change the color depending on the theme (dark / light mode).
1. Open the [new docs](https://eui.elastic.co/pr_8127/new-docs/index.html).
2. Navigate to any component page (e.g. [Accordion](https://eui.elastic.co/pr_8127/new-docs/docs/layout/accordion/)).
3. Notice the component preview. In the footer, there's a Codesandbox icon.
4. Switch themes using the toggle in the top right of the page.
5. Verify that the Codesandbox icon is visible. In light mode it should be black, in dark mode white.
https://github.com/user-attachments/assets/989811da-3fcd-4384-9bc1-d810cea331ca
=> fix(docusaurus-theme): fill Codesandbox icon with currentColor

packages/eui/changelogs/upcoming/8135.md, packages/eui/src-docs/src/views/datagrid/schema_columns/column_dragging.js, packages/eui/src/components/datagrid/body/header/draggable_columns.spec.tsx, packages/eui/src/components/datagrid/body/header/draggable_columns.tsx
closes #8119 
This PR fixes an issue for `EuiDataGrid` with `columnVisibility.canDragAndDropColumns` enabled and used inside `EuiModal` where the column actions would not be clickable.
This was caused by a custom "blur"/"clickAway" event being fired (added [here](https://github.com/elastic/eui/pull/8015/commits/96f325ed7e534b201209f910a73f0efed24d0afa#diff-27ccea893ced8c90d7c620365b116fb988720f4c4a0311bf748f529e7ac637cfR172)) because the [selector](https://github.com/elastic/eui/pull/8015/commits/96f325ed7e534b201209f910a73f0efed24d0afa#diff-27ccea893ced8c90d7c620365b116fb988720f4c4a0311bf748f529e7ac637cfR162) for this condition was selecting the modal focus trap instead of the column action one.
- updates the condition to check for all focus traps and exclude modal focus traps that …
=> [EuiDataGrid] Fix column actions not working for draggable datagrid inside modals

packages/eui/src/components/collapsible_nav_beta/collapsible_nav_item/collapsed/collapsed_nav_popover.tsx
Addresses https://github.com/elastic/kibana/issues/198870
| ![before](https://github.com/user-attachments/assets/151fcb16-0e90-41cd-bc79-96e49c97cc5a) | ![after](https://github.com/user-attachments/assets/7478ba10-5907-42c9-8c5f-51491cd24173) | 
N/A, beta component
=> [EuiCollapsibleNavBeta] Fix bug with long/scrolling pages

packages/eui-theme-borealis/src/variables/_borders.scss, packages/eui-theme-borealis/src/variables/_index.scss, packages/eui-theme-common/src/global_styling/variables/_borders.scss, packages/eui/src/global_styling/mixins/__snapshots__/_color.test.ts.snap, packages/eui/src/global_styling/mixins/_color.ts, packages/eui/src/themes/amsterdam/global_styling/variables/_borders.ts, packages/eui/src/themes/amsterdam/global_styling/variables/_colors.ts
>[!NOTE]
This PR merges into a feature branch
This PR fixes an issue with border token mappings for the `Amsterdam` theme, where references to the `border.color` are not actually available in the `colors` definitions yet.
The tokens use the underlying computed token now instead.
_before_
_after_
=> [Visual Refresh] Fix computed border token mapping

packages/eui/changelogs/upcoming/8116.md, packages/eui/src/components/page/page_header/__snapshots__/page_header.test.tsx.snap, packages/eui/src/components/page/page_header/__snapshots__/page_header_content.test.tsx.snap, packages/eui/src/components/tabs/__snapshots__/tab.test.tsx.snap, packages/eui/src/components/tabs/__snapshots__/tabs.test.tsx.snap, packages/eui/src/components/tabs/tab.tsx, packages/eui/src/components/tabs/tabbed_content/__snapshots__/tabbed_content.test.tsx.snap, packages/eui/src/components/tabs/tabs.spec.tsx, packages/eui/src/components/tabs/tabs.tsx
Both the [WCAG](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) and [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role) specifications for tabs specify that they should be within a tab group and traversed via arrow keys.
https://github.com/user-attachments/assets/00716ddb-542d-4139-b8e6-442223a915e3
I've noticed there are 2 ways the tabs are used:
1. either with **EuiTabbedContent** (that provides a `tabpanel`; **EuiTabs** and **EuiTab** accessible from the same level),
2. or using **EuiTabs** + **EuiTab** directly (composition through children prop).
I decided to put the logic inside **EuiTabs** as its the common point between the 2 use cases and it makes sense for that wrapper to traverse the nodes within and manipulate the DOM (as opposed to traversing …
=> feat(tabs): traverse tabs with arrow keys

packages/eui/changelogs/upcoming/8177.md, packages/eui/src-docs/src/views/badge/beta_badge.tsx, packages/eui/src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap, packages/eui/src/components/badge/beta_badge/beta_badge.styles.ts, packages/eui/src/components/badge/beta_badge/beta_badge.tsx, packages/website/docs/components/display/badge.mdx
I added a "warning" value to the color prop, updated both documentation websites and updated snapshot tests.
In the new docs, the warning beta badge doesn't display as expected even after rebuilding dependencies. Not sure if it's a problem with the Docasaurus theme?
closes #8138
- Browser QA
- Docs site QA
=> feat(beta_badge): support warning color value

packages/eui-theme-borealis/src/variables/colors/_colors_light.scss
>[!NOTE]
This PR fixes a wrong Sass variable mapping. `euiColorFullShade` in light color mode should be mapped to `euiColorPlainDark` as it's the darkest (legacy) shade. It having been mapped to `euiColorPlainLight` (which is white) was a mistake, likely due to copying.
There is no actual output of this in EUI. The EUI docs [here](https://eui.elastic.co/pr_8178/#/theming/colors/values#shades) use the legacy JSON tokens as output.
=> [Visual Refresh] Fix euiColorFullShade Sass variable mapping

packages/eui/changelogs/upcoming/8140.md, packages/eui/src/components/flyout/flyout.spec.tsx, packages/eui/src/components/tool_tip/tool_tip.spec.tsx, packages/eui/src/components/tool_tip/tool_tip.tsx
When we have `EuiIconTip` (consequently, `EuiTooltip`) within `EuiFlyout` and with the tooltip open we click "Escape" key, the flyout gets closed. The reason is, the escape keydown event is propagated from the tooltip and captured by the flyout as its parent. Simple `event.stopPropagation()` inside `EuiTooltip` seemed to do the trick.
closes #8130
**Test path:**
1. Run Storybook locally: `yarn storybook`.
2. Find the component `EuiFlyout`.
3. Close the flyout with the escape key.
4. Change the `EuiFlyoutBody` to contain a `EuiToolTip` as children.
5. Focus the tooltip and close it with the Escape key. The flyout should not close, the tooltip - yes.
6. With the tooltip closed, click Escape key again to close the flyout.
https://github.com/user-attachments/assets/34b833bd-9c62-4f9c-9810-8442 …
=> fix(tool_tip): stop propagation on escape key down

packages/eui/changelogs/upcoming/8195.md, packages/eui/src/components/code/__snapshots__/code_block.test.tsx.snap, packages/eui/src/components/code/code_block.test.tsx, packages/eui/src/components/code/code_block.tsx, packages/eui/src/components/code/code_block_copy.tsx, packages/eui/src/components/code/code_block_full_screen.tsx, packages/eui/src/services/copy/index.ts, packages/eui/src/services/copy/tabular_copy.tsx
closes #8175.
This PR aims to improve the accessibility of the `EuiCodeBlock` component, especially the expandable/fullscreen functionality.
1. focusable code blocks did not have any semantic information (the code block is focusable when a `height` is set to provide scrolling via arrow keys - similar to a listbox pattern)
2. entering fullscreen mode (expanded code block) did not announce the change to screen reader users
3. closing the fullscreen mode via the collapse button did not return the focus to the toggle button
> 1. focusable code blocks did not have any semantic information
`<pre>` elements don't have any semantic information (without adding a specific `role`) and hence also don't support `aria-label` to add additional semantic information directly. `<code>` elements [don't …
=> [EuiCodeBlock] Improve accessibility of expandable code blocks

packages/eui/changelogs/upcoming/8036.md, packages/eui/src-docs/src/components/guide_theme_selector/guide_theme_selector.tsx, packages/eui/src-docs/src/views/theme/high_contrast_mode/high_contrast_mode_example.js, packages/eui/src/services/theme/provider.test.tsx, packages/eui/src/services/theme/provider.tsx, packages/eui/src/services/theme/utils.test.ts, packages/eui/src/services/theme/utils.ts, packages/website/docs/components/theming/high_contrast_mode.mdx
> [!note]
> This PR merges into a feature branch.
The impetus for this PR stems from this earlier conversation: https://github.com/elastic/eui/pull/8193#discussion_r1866168485
Essentially, our use of `forced-color-adjust: none` can cause visibility issues with `fullShade/emptyShade`, if we don't respect high contrast themes that force light/dark mode.
At this point, we need to treat forced colors/high contrast themes as superceding any application setting (since they do in reality) - hence this architectural change.
- Go to https://eui.elastic.co/pr_8200/#/theming/high-contrast-mode
- Use Chrome/Edge devtools > rendering to emulate both forced colors and prefers color scheme media queries
- Browser QA
- (_[emulate forced colors](https://devtoolstips.org/tips/en/emulate-forced-colors/) if …
=> [High Contrast Mode] Allow forced high contrast themes to also force color mode

packages/website/package.json, yarn.lock
When working with the new docs page, local changes to the EUI library are not reflected. That's because `website` package doesn't use workspace version of `eui`. 
**For context:** [Slack](https://elastic.slack.com/archives/C04UK0RDL2J/p1732293051350609)
1. Run `yarn` to install deps.
2. Run `yarn workspaces foreach -Rpti --from @elastic/eui-website run build` to build all local dependency packages.
3. Run `yarn workspace @elastic/eui-website start` to run the new docs website.
4. Choose any component doc page. Change that component's source code (e.g. color).
5. Run `yarn workspace @elastic/eui build` and reload the page. The changes should be visible.
(context: https://github.com/elastic/eui/pull/8177)
=> chore(website): use workspace version of eui

packages/eui-theme-borealis/src/eui_theme_borealis_light.json, packages/eui-theme-borealis/src/variables/colors/_colors_light.scss, packages/eui-theme-borealis/src/variables/colors/_colors_light.ts, packages/eui/src-docs/src/views/theme/_json/eui_theme_borealis_light.json, packages/eui/src/components/breadcrumbs/_breadcrumb_content.styles.ts
Closes https://github.com/elastic/platform-ux-team/issues/563
^ This change stemmed from a contrast check on breadcrumbs.
@ek-so proposed we change the shade for subdued text, globally.
>[!NOTE]
- updates subdued text with darker shade
Shade95 translates to hex #516381 
- This can be seen on the Colors > Text colors page
- Contrast for the last breadcrumb can be seen on the Header page
- This only impact light mode; contrast on dark mode was sufficient
=> [Visual Refresh] Set darker shade for subdued text

packages/eui/src-docs/src/views/badge/beta_badge.tsx, packages/eui/src/components/badge/__snapshots__/badge.test.tsx.snap, packages/eui/src/components/badge/badge.styles.ts, packages/eui/src/components/badge/badge.tsx, packages/eui/src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap, packages/eui/src/components/badge/beta_badge/beta_badge.styles.ts, packages/eui/src/components/badge/beta_badge/beta_badge.tsx, packages/eui/src/components/badge/notification_badge/__snapshots__/badge_notification.test.tsx.snap, packages/eui/src/components/badge/notification_badge/badge_notification.styles.ts, packages/eui/src/components/badge/notification_badge/badge_notification.tsx
>[!NOTE]
This PR removes support for the `accentSecondary` variant of badges.
This was initially added while `accentSecondary` was still being considered a regular usage, but latest design discussions are moving away from `accentSecondary` as a color for e.g. Buttons and [Badges](https://www.figma.com/design/FHys7gLzyvD1gc9DrJM6D8/%5BVR%5D-Elastic-UI-New-Library-%5BTEST%5D?node-id=6259-60641&t=VycQ1C4s2TIR5MYt-4).
To proactively prevent further usage of it, we're removing it again.
This change was discussed with @ek-so.
=> [Visual Refresh] Remove support for accentSecondary badges

packages/eui-theme-borealis/src/variables/colors/_colors_vis.ts, packages/eui-theme-common/src/global_styling/variables/colors.ts, packages/eui/src/themes/amsterdam/global_styling/variables/_colors_vis.ts
>[!NOTE]
This PR introduces new theme tokens for severity colors as part of `euiTheme.colors.vis` as proposed by @gvnmagni 
```ts
euiColorSeverity0
euiColorSeverity1
euiColorSeverity2
euiColorSeverity3
euiColorSeverity4
euiColorSeverity5
euiColorSeverity6
euiColorSeverity7
euiColorSeverity8
euiColorSeverity9
euiColorSeverity10
euiColorSeverity11
euiColorSeverity12
euiColorSeverity13
euiColorSeverity14
```
| Amsterdam | Borealis |
|-------------|---------|
| ![image](https://github.com/user-attachments/assets/4169fced-fa52-4886-a98f-672c9f020417) | ![image](https://github.com/user-attachments/assets/d1fe8463-ba45-458c-9dbd-a059899ca6b7) |
These new tokens are not used anywhere so far, we introduce them for usage in Kibana.
As long as the CI passes and …
=> [Visual Refresh] Add severity vis colors

packages/eui-theme-borealis/src/variables/_components.ts, packages/eui-theme-borealis/src/variables/colors/_semantic_colors.ts
>[!IMPORTANT]
This PR merges into a feature branch
This PR fixes the values for transparent colors calculated using `chroma` as added [here](https://github.com/elastic/eui/pull/8211).
The usage was not correct and still returned a hex code, which does not work as value used in `rgba()`.
I complete missed that 😭 
Additionally it reverts a change of the EuiDatagrid border color from `plain` to `subdued`.
- ensure that transparent colors are output properly in Borealis, e.g. here for the following examples:
- verify [EuiDataGrid](https://eui.elastic.co/pr_8249/storybook/index.html?path=/story/tabular-content-euidatagrid--playground) uses `borderBasePlain` borders in Borealis
=> [Visual Refresh] Fix transparent color variable definitions

packages/eui/src/components/token/token.styles.ts, packages/eui/src/components/token/token_map.ts
Related to https://github.com/elastic/platform-ux-team/issues/561
Closes https://github.com/elastic/kibana/issues/202760
During QA of Borealis for Discover, it was noted that the `EuiToken` colors were too light in the field list.
This was reviewed with the theme designers and the following recommendations were made:
1. (this PR) adjust the colors for greater contrast in the border and icon
2. (future) discontinue using EUI vis color palette and, instead, create a palette specific for EuiToken use
(screenshots also found in the design [issue](https://github.com/elastic/platform-ux-team/issues/561))
**In EUI**
Running EUI docs locally, `EuiToken` should look like:
**In Kibana**
For reference, this was also run locally in Kibana which looked like:
=> [Visual Refresh] Update `EuiToken` colors

packages/eui/src/components/date_picker/super_date_picker/date_popover/absolute_tab.test.tsx
This PR updates the `EuiSuperdatePicker` `absolute_tab.test.tsx` test by adding a year to the passed date string to prevent tests breaking on yearly changing week days.
Example failing test:
```
EuiAbsoluteTab › date parsing › parses date string in locale › {"dateString": "lun. janv. 1er", "locale": "fr-FR"}
```
The issue was that January 1st was a Monday in 2024, but is not a Monday in 2025.
We should fix the date to the year to ensure the test works generally.
- checkout this PR
- move to `packages/eui` and run `yarn test-unit src/components/date_picker/super_date_picker/date_popover/absolute_tab.test.tsx`
=> [EuiSuperDatePicker] Fix locale date string test

packages/eui-theme-borealis/src/variables/colors/_colors_vis.ts, packages/eui-theme-common/src/global_styling/variables/colors.ts, packages/eui/src/themes/amsterdam/global_styling/variables/_colors_vis.ts
>[!NOTE]
This PR adds `_behindText` vis color tokens. These have not been part of the theme, as they are not in usage in the new theme.
During upgrades to the new theme, we realized that it's rather cumbersome for teams to migrate these JSON token usages properly to the `euiTheme` tokens without a 1:1 equivalent.
These tokens are temporary for the purpose of making migration easier for Kibana teams. We will need to remove those tokens again at some point as they are not be used in Borealis.
```ts
euiColorVisBehindText0
euiColorVisBehindText1
euiColorVisBehindText2
euiColorVisBehindText3
euiColorVisBehindText4
euiColorVisBehindText5
euiColorVisBehindText6
euiColorVisBehindText7
euiColorVisBehindText8
euiColorVisBehindText9
```
These tokens are not used …
=> [Visual Refresh] Add behindText vis color tokens

packages/eui-theme-borealis/src/variables/colors/_colors_dark.scss, packages/eui-theme-borealis/src/variables/colors/_colors_light.scss, packages/eui/src/themes/amsterdam/_colors_dark.scss, packages/eui/src/themes/amsterdam/_colors_light.scss
We noticed that there seems to have been some typos in the `borderStrong` SCSS tokens 🫠 
This causes the variables to not actually be available for use.
- renames SCSS `borderStrong` tokens for Borealis dark
- adds missing `!default` flag (since we're here 🤷‍♀️)
- checkout this PR
- use the border tokens, e.g. `$euiColorBorderStrongSuccess` in our EUI docs, e.g. in `packages/eui/src-docs/src/views/home/_home.scss` to add a background color somewhere
```css
// example
.guideSideNav {
background-color: $euiColorBorderStrongSuccess !important;
}
```
=> [Visual Refresh] Fix strong border token naming

packages/eui/src/components/panel/panel.styles.ts
>[!IMPORTANT]
This PR updates the implementation of the floating border on `EuiPanel` to fix the issue of the transparent border on light mode showing with colored full-width content (e.g. for `EuiSplitPanel`)
Instead of adding the floating border on the panel element directly, this PR adds a pseudo element for the border.
This will:
- prevent transparent borders from showing as the border overlaps the content instead of sitting around the content
- ensures layout parity between light and dark mode (having a conditional border on dark mode would otherwise mean that light and dark mode have slightly different dimensions for panels as borders add to the size)
| before | after|
|-------|------|
| ![Screenshot 2025-01-13 at 10 52 …
=> [Visual Refresh] Update floating border on EuiPanel

packages/eui/changelogs/upcoming/8278.md, packages/eui/src-docs/src/views/stat/stat_colors.js, packages/eui/src/components/stat/__snapshots__/stat.test.tsx.snap, packages/eui/src/components/stat/stat.styles.ts, packages/eui/src/components/stat/stat.tsx, packages/website/docs/components/display/stat.mdx
This PR adds support for `warning` as value for the `titleColor` prop.
This was requested and approved by design.
Additionally this PR adds a tiny layout change to the docs for displaying `titleColor` variants of `EuiStat` to ensure flex items wrap to improve the layout arrangement on smaller (non-mobile) viewports.
_before_
_after_
- Browser QA
- Docs site QA
=> [EuiStat] Support warning variant

packages/eui/src-docs/src/views/badge/beta_badge.tsx, packages/website/docs/components/display/badge/beta_badge.mdx
Closes #8295 
Update docs example to follow more closely our guidelines while keeping the component as-is for non-Elastic use cases.
**Change included**
- Show 'DEPRECATED' for `subdued` and `warning`
- Do not display icon-only versions for `subdued` and `warning`
**Unrelated tweaks**
- Section headings
- Spacing
**Preview**
_Current site_
_New site_
- Browser QA
- Docs site QA
=> Update to reflect guidelines

packages/eui/changelogs/upcoming/8303.md, packages/eui/src-docs/src/views/call_out/accent.tsx, packages/eui/src-docs/src/views/call_out/call_out_example.js, packages/eui/src/components/call_out/__snapshots__/call_out.test.tsx.snap, packages/eui/src/components/call_out/call_out.styles.ts, packages/eui/src/components/call_out/call_out.tsx, packages/website/docs/components/display/callout.mdx
Related to #8102 
This PR enables the first, bespoke example seen in the related issue by adding an `accent` color option to `EuiCallOut`.
An additional solution may be needed for more complex banners containing illustrations (or use EuiEmptyPrompt).
- Browser QA
- Docs site QA
=> [EuiCallOut] Add `accent` color callout

packages/eui/changelogs/upcoming/8311.md, packages/eui/src/components/date_picker/super_date_picker/date_popover/absolute_tab.test.tsx, packages/eui/src/components/date_picker/super_date_picker/date_popover/absolute_tab.tsx
Related Kibana issue: https://github.com/elastic/kibana/issues/205633
This PR fixes an issue on `EuiSuperDatePicker` where pasting a date would sometimes result in the date being appended instead of being replaced.
The issue was that the `onPaste` event would trigger the `onChange` event on the `EuiFieldText` input which clashed with the controlled value update. This seemed to be a race condition as depending on application this resulted either in a duplicated value or not, depending on which state was updated first.
This behavior is not reproducible on EUI (neither docs not Storybook), but it can be observed by checking the value of the internally used `EuiFieldText` which showed the duplication.
The solution is to `preventDefault` on `onPaste` and just let the controlled value update …
=> [EuiSuperDatePicker] Fix duplicate value when pasting absolute value

packages/eui/changelogs/upcoming/8307.md, packages/eui/src/components/inline_edit/inline_edit_form.tsx
This PR updates the type definition for  `EuiInlineEditForm`s `onCancel` prop to support using it for non-controlled usage next to the already available controlled usage. 
When the component is in edit mode, we have two actions: "Save" and "Cancel" and currently only the "Save" action provides a callback for non-controlled usage.
Instead we should also allow `onCancel` to be always allowed considering that the action is always available too. 
The main purpose of the `onCancel` callback is to reset the `value` in controlled usage, but there might be a need to use `onCancel` for non-controlled usages as well to handle other side effects.
>[!NOTE]
No functional changes have been made in this PR. The callback was already always technically available, just that the type definition prohibited …
=> [EuiInlineEditForm] Support onCancel callback for non-controlled usage

packages/eui/changelogs/upcoming/8327.md, packages/eui/src/components/accordion/__snapshots__/accordion.test.tsx.snap, packages/eui/src/components/accordion/accordion.tsx, packages/eui/src/components/accordion/accordion_children/accordion_children.styles.ts, packages/eui/src/components/accordion/accordion_children/accordion_children.tsx
closes #8299 
This PR updates `EuiAccordion` to disable transitioning the content on initial render when `initialIsOpen=true`. 
The transition should only happen on open/close toggle, not initial render.
_before_
https://github.com/user-attachments/assets/f1a0227a-92a3-4805-894a-27f12ef74abb
_after_
https://github.com/user-attachments/assets/d4800913-19d7-492e-a26b-673759cc35b4
- Browser QA
- Docs site QA
=> [EuiAccordion] Disable transition on initial render when initialsOpen

packages/eui/changelogs/upcoming/8333.md, packages/eui/src/components/combo_box/__snapshots__/combo_box.test.tsx.snap, packages/eui/src/components/combo_box/combo_box.stories.tsx, packages/eui/src/components/combo_box/combo_box.tsx, packages/eui/src/components/combo_box/combo_box_input/combo_box_input.tsx, packages/eui/src/components/combo_box/combo_box_options_list/combo_box_options_list.tsx, packages/eui/src/components/filter_group/__snapshots__/filter_select_item.test.tsx.snap, packages/eui/src/components/filter_group/filter_select_item.tsx, packages/eui/src/components/popover/popover.tsx
closes https://github.com/elastic/eui/issues/8267
This PR updates `EuiComboBox` adding/updating it's markup to ensure expected output for screen readers.
The updates are based on the common web pattern for a combobox ([ref](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/))
---
**Unexpected behavior:**
- the appended items being read out by the screen reader because the panel has an aria-live="assertive" applied
- the list size is updated
- the item position index is updated correctly
- navigated/focused options are marked as selected
_NVDA (Windows) & Chrome_
https://github.com/user-attachments/assets/93eb50f7-51c6-44c9-b3fc-d5941813e8ac
_VoiceOver (macOS) & Chrome_
https://github.com/user-attachments/assets/b0fcf8e6-3a33-4378-86a4-7926edda7f8a
---
**Expected behavior:**
- the appended …
=> [EuiComboBox] Improve accessibility of virtualized listbox

packages/eui/src-docs/src/views/tables/basic/basic.tsx, packages/eui/src-docs/src/views/tables/basic/basic_section.js, packages/eui/src/components/basic_table/table_types.ts, packages/website/docs/components/tabular_content/tables/basic_tables.mdx
This PR adds a small paragraph to *EuiBasicTable* documentation regarding the recently added `nameTooltip` API.
Check new texts display properly in old and new docs:
=> [EuiBasicTable] Better document `columns.nameTooltip`

.yarnrc.yml, package.json, packages/eui-docgen/package.json, packages/release-cli/.gitignore, packages/release-cli/package.json, packages/release-cli/src/cli.ts, packages/release-cli/src/errors.ts, packages/release-cli/src/git_utils.ts, packages/release-cli/src/index.ts, packages/release-cli/src/logger.ts, packages/release-cli/src/npm_utils.ts, packages/release-cli/src/release.ts, packages/release-cli/src/steps/build_packages.ts, packages/release-cli/src/steps/check_workspaces.ts, packages/release-cli/src/steps/init_checks.ts, packages/release-cli/src/steps/publish.ts, packages/release-cli/src/steps/run_pre_post_scripts.ts, packages/release-cli/src/steps/update_versions.ts, packages/release-cli/src/update_changelog.ts, packages/release-cli/src/version.ts, packages/release-cli/src/workspace.ts, packages/release-cli/src/yarn_utils.ts, packages/release-cli/tsconfig.json, scripts/release.js, yarn.lock
Resolves https://github.com/elastic/eui-private/issues/136.
This PR adds a new release CLI for EUI monorepo. It reuses changelog calculation and versioning logic from the old release script and comes with a bunch more safety checks as well as monorepo workspaces awareness.
1. Checkout this PR - `gh pr checkout 8308`
2. Install dependencies and build release CLI (to be automated) - `yarn workspace @elastic/eui-release-cli run build`
3. Make sure you're **logged out** from npm - `npm logout` and double check with `npm whoami`
4. Run a custom npm registry locally in a new terminal session - `docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio`
* The UI is available on http://localhost:4873/
5. Update your local yarnrc to use the local registry for testing. Add the following …
=> Add CLI for monorepo releases

packages/website/docs/components/utilities/error_boundary.mdx
Added the Error Boundary page to the new documentation site.
It's worth to point out that locally the error gets caught and the red screen appears when accessing Utilities > Error Boundary. This likely won't happen in staging and production because it's not a development environment, therefore doesn't display the red screen. For better DX though, this could be improved to not be caught by the upper-most Error Boundary.
**Checklist:**
=> feat(website): add Utilities > Error Boundary page

packages/website/docs/components/utilities/highlight_and_mark.mdx
Added the Highlight and Mark to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Highlight and Mark page

packages/website/docs/components/utilities/auto_sizer.mdx
Added the Auto Sizer page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Auto Sizer page

packages/eui/changelogs/upcoming/8380.md, packages/eui/src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx, packages/eui/src/components/date_picker/super_date_picker/super_date_picker.test.tsx, packages/eui/src/components/date_picker/super_date_picker/super_date_picker.tsx
This PR adds support for the props `quickSelectButtonProps` on `EuiSuperDatePicker` to allow passing additional props to the button, e.g. for handling custom events.
- Browser QA
- Docs site QA
=> [EuiSuperDatePicker] Add support for quickSelectButtonProps

.yarnrc.yml, packages/eui-theme-borealis/package.json, packages/eui-theme-common/package.json, packages/eui/package.json, packages/release-cli/src/steps/update_versions.ts, packages/release-cli/src/version.ts, yarn.lock
This PR improves the way snapshot releases (`yarn release snapshot`) are versioned. Previously, both `official` and `snapshot` releases used the regular changelog-based new version calculation. It wasn't correct since snapshot releases are meant for testing, and they should not use the same versioning scheme, even if suffixed with `-snapshot`.
The updated code builds and publishes packages with a timestamp-based versioning, for example:
* `99.4.0` -> `99.4.0-snapshot.1741123162416`
* `1.2.3-borealis.0` -> `1.2.3-snapshot.1741123163100`
With this change, the updated `package.json` versions will not be committed. Keep in mind, though, that the file is still edited, and will be marked as modified by git. There's no reset logic to get them back to the original state yet but it may be …
=> Update release versioning for snapshot releases

packages/website/docs/components/forms/selection/combo_box.mdx, packages/website/docs/components/utilities/html_id_generator.mdx
Added the HTML ID Generator page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > HTML ID Generator page

packages/website/docs/components/utilities/inner_text.mdx
Added the Inner Text page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Inner text page

packages/website/docs/components/utilities/mutation_observer.mdx
Added the Mutation Observer page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Mutation Observer page

packages/website/docs/components/utilities/outside_click_detector.mdx
Added the Outside Click Detector page to the new documentation site.
Added a ticket to M2 for improving page UX: https://github.com/elastic/eui/issues/8346
**Checklist:**
=> feat(website): add Utilities > Outside Click Detector page

packages/website/docs/components/utilities/pretty_duration.mdx
Added the Pretty Duration page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Pretty Duration page

packages/website/docs/components/utilities/resize_observer.mdx
Added the Resize Observer page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Resize Observer page

packages/website/docs/components/utilities/text_diff.mdx
Added the Text Diff page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Text diff page

packages/website/docs/components/utilities/focus_trap/_category_.yml, packages/website/docs/components/utilities/focus_trap/form_compressed.tsx, packages/website/docs/components/utilities/focus_trap/overview.mdx
Added the Focus Trap page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Focus Trap page

packages/website/docs/components/utilities/scroll/_category_.yml, packages/website/docs/components/utilities/scroll/overview.mdx, packages/website/docs/components/utilities/scroll/previews.tsx, packages/website/docs/components/utilities/scroll/scroll_content.tsx
Adds the Scroll page to the new documentation site. I removed the dynamic section for Sass as it's something we're trying to migrate away from.
**Checklist:**
=> feat(website): add Utilities > Scroll page

packages/website/docs/components/utilities/window_events/_category_.yml, packages/website/docs/components/utilities/window_events/modal_example.tsx, packages/website/docs/components/utilities/window_events/overview.mdx
Adds the Windows Events page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Window Events page

packages/website/docs/components/utilities/scroll/previews.tsx
The `euiTheme` argument in `verticalBaseCss` (`packages/website/docs/components/utilities/scroll/previews.tsx`) is undefined, therefore trying to access `base` results in an error. `verticalBaseCss` is passed to the `css` prop but it doesn't pass the `euiTheme`, so the simplest fix is to use `useEuiTheme` instead.
I tried using the `@emotion/babel-plugin` ([source](https://github.com/emotion-js/emotion/blob/HEAD/docs/css-prop.mdx#babel-preset)) to make the `css` prop work as expected but it still failed. I might be missing something there but I don't want to keep digging, considering there's a simple fix available and that the pipeline is blocked for all PRs.
=> fix(website): use useEuiTheme instead of css prop function argument

packages/eui/src-docs/src/views/datagrid/schema_columns/column_dragging.js
This PR updates an import for the `EuiDataGrid` "draggable columns" example in our current EUI docs.
This link was unexpectedly updated in this [previous PR](https://github.com/elastic/eui/pull/8183) ([code](https://github.com/elastic/eui/pull/8183/commits/786bb804317e4a00ea0fa8e7658af9ff18507c56#diff-93a6d3a89919e5af82640a23ba3034507da0536e395cbf45ca2fe19053ac4707R4)).
=> [Docs] Fix EuiDataGrid draggable column example import

packages/docusaurus-theme/src/components/prop_table/prop_table.tsx, packages/eui/src/components/provider/component_defaults/component_defaults.tsx, packages/website/docs/components/guidelines/getting_started.mdx, packages/website/docs/components/utilities/provider.mdx
Added the Provider page to the documentation site.
Possible improvement in M2: https://github.com/elastic/eui/issues/8344
**Checklist:**
=> feat(website): add Utilities > Provider page

packages/website/docs/components/forms/selection/combo_box.mdx, packages/website/docs/components/forms/selection/selectable.mdx, packages/website/docs/components/utilities/text_truncation.mdx, packages/website/package.json, yarn.lock
Added the Text Truncation page to the new documentation site.
**Checklist:**
=> feat(website): add Utilities > Text Truncation page

packages/website/docs/components/utilities/color_palettes/_category_.yml, packages/website/docs/components/utilities/color_palettes/color_palettes_components.tsx, packages/website/docs/components/utilities/color_palettes/overview.mdx, packages/website/docs/data_visualization/theming.mdx
Removed the "Sass variables" section from Utilities > Color palettes page and created a task to document vis color palette tokens on the Theming > Colors page: https://github.com/elastic/eui/issues/8340
**Checklist:**
=> feat(website): add Utilities > Color Palettes page

packages/website/docs/components/layout/flyout/flyout.mdx, packages/website/docs/components/utilities/overlay_mask.mdx
Closes https://github.com/elastic/eui/issues/8190
Added the Overlay Mask page to the new documentation site.
Possible improvement in M2: https://github.com/elastic/eui/issues/8347
**Checklist:**
=> feat(website): add Utilities > Overlay Mask page

packages/docusaurus-theme/package.json, packages/website/package.json, yarn.lock
Not much changed in [v3.6](https://docusaurus.io/blog/releases/3.6) and [v3.7](https://docusaurus.io/blog/releases/3.7) that we would need to upgrade but the changes are exciting, among them:
- tooling changed to Rust-based, it's an opt-in breaking change, the project is called [Docusaurus Faster](https://github.com/facebook/docusaurus/issues/10556),
- [Rsdoctor plugin](https://docusaurus.io/blog/releases/3.6#rsdoctor-plugin), something to consider in terms of EUI+ analytics and metrics,
- support for React v19, as of Docusaurus v4 the support for React v18 will be dropped.
Closes #8420
=> [EUI+] Update the Docusaurus versions

packages/website/docs/components/display/skeleton.mdx, packages/website/docs/components/utilities/overlay_mask.mdx, packages/website/docs/components/utilities/portal.mdx, packages/website/docs/components/utilities/provider.mdx, packages/website/docs/patterns/error_messages/error_validation.mdx, packages/website/docs/patterns/help_content.mdx, packages/website/docs/patterns/pre_ga_badges.mdx
I fixed all the warnings regarding redirections that Docusaurus reported except for the missing Typography page:
Closes #8421
=> [EUI+] Fix markdown link warnings

packages/eui/changelogs/CHANGELOG_2025.md, wiki/eui-team-processes/releasing-versions.md
This PR is a [follow-up](https://github.com/elastic/eui/pull/8308#discussion_r1967994872) to this previous [PR](https://github.com/elastic/eui/pull/8308) that introduced a new release process for the EUI monorepo.
- updates docs on how to release EUI packages
- adds a section on how to release testing packages (local & npm registry)
- removes an unexpected heading in the latest changelog file, that was manually added [here](https://github.com/elastic/eui/pull/8386/commits/3bce120f0dba33aa65983941a7d87d82219f6e20#diff-a1392da8a874e4590e118d618bb9822169055eaf03d008b95af2a18360d95581R1) by mistake
=> [Wiki] Update monorepo release docs

packages/eui/src-docs/src/components/codesandbox/link.js
Codesandbox was complaining about not finding the dependency: `@elastic/eui-theme-borealis`.
The solution was pretty simple but there's one caveat. I cannot use `getVersion(pkg)` for `@elastic/eui-theme-borealis` because it'll set to `workspace:^` and that's not something that Codesandbox will be able to resolve. Therefore, `latest` seems more appropriate and maintainable.
The only downside is we won't be able to see the local changes in Codesandbox, only until we release the package. But at the same time, I don't see a way in which we **could** allow for Codesandbox to build with the local state of `@elastic/eui-theme-borealis`.
Closes #8434
=> fix(src-docs): add @elastic/eui-theme-borealis dependency

packages/eui/changelogs/upcoming/8441.md, packages/eui/src-docs/src/views/loading/loading_chart.tsx, packages/eui/src-docs/src/views/loading/loading_example.tsx, packages/eui/src/components/loading/__snapshots__/loading_chart.test.tsx.snap, packages/eui/src/components/loading/loading_chart.stories.tsx, packages/eui/src/components/loading/loading_chart.styles.ts, packages/eui/src/components/loading/loading_chart.test.tsx, packages/eui/src/components/loading/loading_chart.tsx, packages/website/docs/components/display/loading.mdx
This PR **removes** `EuiLoadingChart` non-mono version (which is the default). I decided to **remove** instead of **deprecate** it and consulted the decision with @ek-so. We only need to update the code on the next Kibana upgrade by removing all mentions of `mono` prop. See the details below.
Closes #8275
There are **3 usages**, all use the **non-mono version**, they do not pass the `mono` prop, they **don't require an update**:
- `cloud-ui/apps/monolith/public/components/User/BillingUsage/components/CostsChart/index.tsx`
- `cloud-ui/apps/monolith/public/components/User/BillingUsage/components/CostsChartByInstance/index.tsx`
- `cloud-ui/apps/monolith/public/components/User/BillingUsage/components/ProductChart/index.tsx`
<details><summary>24 times mono or mono={true} (requires code …
=> feat(eui): remove EuiLoadingChart non-mono version

packages/website/docs/components/theming/colors/data_vis_colors_table.tsx, packages/website/docs/components/theming/colors/values.mdx
We are moving away from supporting SCSS in the direction of Emotion, therefore any mentions of SCSS should be removed in the new docs. In case somebody needs to check SCSS variables, they can go back in docs version.
There was a section in the [Utilities > Color palettes](https://eui.elastic.co/#/utilities/color-palettes#sass-variables) page called "Sass variables" that enumerated the data vis "tokens". We don't have an equivalent section in the Theming > Colors page. This PR adds the section.
Closes #8340
| Light mode | Dark mode |
| ----------- | ----------- |
| ![Screenshot 2025-03-19 at 11 58 26](https://github.com/user-attachments/assets/1228cb6f-4b7c-4bb6-adeb-0c9f973f9456) | ![Screenshot 2025-03-19 at 11 58 20](https://github.com/user-attachments/assets/ba8c450a-dab9-4523-9210-57e95 …
=> feat(website): add data vis tokens section to Colors page

packages/website/src/components/homepage/header/index.tsx, packages/website/src/components/homepage/highlights/index.tsx, packages/website/src/components/homepage/users/index.tsx
Closes #8465
I fixed the **hero button and links** that were not clickable due to an overlapping decor wrapper. I also fixed **several broken links** across the page. Additionally, I updated external links to **open in a new tab** for improved user experience.
<details><summary>Screenshots</summary>
<p>
</p>
</details> 
For cases where the topic spanned multiple pages, I chose the page I thought would be most useful:
- "Form" card > "Basic text controls" page
- "All components" button > "Getting Started" page
- "Tokens" card > "Colors" page
=> fix(website): fix broken homepage links

packages/website/README.md, packages/website/package.json
I updated the README to reflect the actual steps you need to take to run EUI+.
Additionally, I updated the `build:workspaces` script to run commands in parallel and use `topological-dev` flag instead of just `topological`. Sometimes, `eui-theme-borealis` is built before `eui-theme-common` which causes the process to error out, that's because `eui-theme-common` is a peer dependency. Now, [the docs](https://yarnpkg.com/cli/workspaces/foreach#details) don't specifically mention `peerDependencies` and the [implementation](https://github.com/yarnpkg/berry/blob/3c8a90ace15092a6e51c965b3dcb5f4c6c814d6c/packages/plugin-workspace-tools/sources/commands/foreach.ts#L380-L393) does indeed use `dependencies` and `devDependencies` but with `topological-dev` the command works consistently.
Closes #8437
=> chore(website): update README

packages/eui-theme-borealis/changelogs/upcoming/8444.md, packages/eui-theme-common/changelogs/upcoming/8444.md, packages/eui/changelogs/upcoming/8490.md, wiki/eui-team-processes/releasing-versions.md
This PR is a cleanup after #8444.
With the new release workflow in place we now have to add changes as changelogs to all internal packages that will be released (this currently means `eui` as well as `eui-theme-borealis` and `eui-theme-common`)
This PR adds the missing changelogs for the changes added in #8444 
Additionally this PR fixes a small mistake in the previously added release documentation ([PR](https://github.com/elastic/eui/pull/8396)).
=> Fix: Add missing changelogs for theme packages

packages/eui/src-docs/src/components/guide_section/guide_section.tsx, packages/eui/src-docs/src/views/tour/fullscreen.js, packages/eui/src-docs/src/views/tour/managed.js, packages/eui/src-docs/src/views/tour/managed_hook.js, packages/eui/src-docs/src/views/tour/not_action_driven.tsx, packages/eui/src-docs/src/views/tour/step.js, packages/eui/src-docs/src/views/tour/step_dom.js, packages/eui/src-docs/src/views/tour/tour.js, packages/eui/src-docs/src/views/tour/tour_example.js, packages/website/docs/components/display/tour/overview.mdx
A busted design no more!
The issues with the current Tour page speak for themselves. This PR...
- introduces a manual 'Begin tour' trigger versus having tour steps initially open,
- sets a `z-index` so that tour steps go below the top nav bar, and
- a number of copy improvements.
>[!NOTE]
>The **Tour Demo** section is commented out for now on the new site as `ExampleContent` does not appear to be included in the **@elastic/eui** package
**Before**
_Shenanigans_
**After**
_This pattern was applied to each section_
- Browser QA
- Docs site QA
- Designer …
=> [Docs] Improve tour page

packages/docusaurus-preset/README.md, packages/docusaurus-preset/package.json, packages/docusaurus-preset/src/index.ts, packages/docusaurus-preset/src/options.ts, packages/docusaurus-preset/tsconfig.json, packages/docusaurus-theme/src/components/theme_context/index.tsx, packages/docusaurus-theme/src/theme/Footer/index.tsx, packages/docusaurus-theme/src/theme/Root.tsx, packages/docusaurus-theme/src/theme/TOCItems/Tree.tsx, packages/docusaurus-theme/src/theme/infima.styles.ts, packages/website/docs/components/display/comment_list_props.tsx, packages/website/docusaurus.config.ts, packages/website/package.json, packages/website/src/components/homepage/header/index.tsx, yarn.lock
This fixes EUI components having incorrect styles because of Docusaurus' defaults applied by their `infima` CSS library. That library defines quite a few global styles we need to programmatically remove. Until now we were patching them with `yarn patch` but that's not a reliable solution, and unfortunately, there's no way to let docusaurus not include these styles.
This PR adds a custom webpack configuration that omits any `infima` styles from being bundled, and re-applies some of the safe styles we actually need for the base docusaurus theme to render properly.
=> feat(website): no global docusaurus styles

packages/eui/src-docs/src/views/button/button.js, packages/eui/src-docs/src/views/button/button_icon.js, packages/website/docs/components/navigation/button/button_basic.mdx, packages/website/docs/components/navigation/button/button_icon.mdx
TL;DR - Hide `accentSecondary` from docs examples until it gets removed from the component
While `accentSecondary` is currently an available color option, it is not recommended for use. In essence, it exists as a 'backward compatible' option where the teal color from the viz palette was previously used. These instances should ultimately be replaced with `primary`, `accent`, or `success` depending on the use case. This color will very likely be deprecated once the color used for `accent` is re-evaluated.
=> [Docs] Remove `accentSecdondary` from button examples

packages/website/docs/components/guidelines/accessibility.mdx, packages/website/docs/components/guidelines/getting_started.mdx, packages/website/docs/components/guidelines/testing/introduction.mdx, packages/website/docs/components/guidelines/testing/recommendations.mdx, packages/website/docs/components/guidelines/writing/examples.mdx, packages/website/docs/components/guidelines/writing/guidelines.mdx
On this PR:
- I replace all external links with `<Link>` component from `@docusaurus/Link` which opens them in a new tab, handles `noopener noreferrer`, supports prefetching, preloading and build-time broken link detection ([source](https://docusaurus.io/docs/docusaurus-core#link)),
- I fix broken links,
- I removed the "Customize themes" redirection because the page is currently missing. [The task](https://github.com/elastic/eui-private/issues/244) to add it back / consider adding it is planned for M2.
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the …
=> [EUI+] Fix all broken links in the Guidelines section

packages/docusaurus-theme/src/components/theme_context/theme_overrides.ts, packages/docusaurus-theme/src/theme/Navbar/Layout/index.tsx
Resolves https://github.com/elastic/eui/issues/8154
This PR removes the hardcoded custom `subdued` color from `packages/docusaurus-theme` and updates `--ifm-navbar-background-color` to use the same color value but coming from an official EUI color token. This should fix all remaining invisible `subdued` color issues.
=> fix: remove docusaurus theme global body color override

packages/website/docs/components/display/tour/overview.mdx
This PR fixes the "require is not defined" error in the fullscreen example on the Tour page. The issue was the import:
`import { ExampleContext } from '../../services';`
that couldn't be resolved to anything. I removed it alongside the "Exit fullscreen demo" button because it's non-functional (see how it works in prod [here](https://eui.elastic.co/#/display/tour#fullscreen-demo)). The example works as expected now, even without the fullscreen mode.
> [!NOTE]
> Fullscreen demos will be rethought on https://github.com/elastic/eui/issues/8151, this PR only aims to fix the error and make the preview display.
Closes #8480
**Steps:**
1. Run the docs locally and / or access the staging environment.
2. Go to the Display > Tour page.
3. Scroll down to the Fullscreen demo section.
4. Verify that …
=> fix(website): remove button in EuiTour fullscreen example

packages/website/docs/components/theming/colors/utilities.mdx, packages/website/docs/components/theming/colors/values.mdx, packages/website/docs/components/theming/sizing.mdx, packages/website/docs/components/theming/theme_provider.mdx
On this PR:
- I replace all external links with `<Link>` component from `@docusaurus/Link` which opens them in a new tab, handles `noopener noreferrer`, supports prefetching, preloading and build-time broken link detection ([source](https://docusaurus.io/docs/docusaurus-core#link)),
- I fix broken links,
- I removed the "Customize themes" redirection because the page is currently missing. [The task](https://github.com/elastic/eui-private/issues/244) to add it back / consider adding it is planned for M2.
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the …
=> [EUI+] Fix all broken links in the Theming section

packages/eui/changelogs/upcoming/8498.md, packages/eui/src/components/table/table_row.styles.ts, packages/eui/src/global_styling/functions/supports.ts
We recently introduced a styling updated on `EuiTableRow` that makes use of the "previous sibling" selector `:has(+ )` (original code [here](https://github.com/elastic/eui/pull/8226/files#diff-94fe0817d4294ace9f97d5146cecf6a6389cc1ec4488534bfcd9a07f56977d53R89), merged [here](https://github.com/elastic/eui/pull/8444))
<details>
<summary>See screenshots of the style here</summary>
| before | after |
|-------|-------|
| ![Screenshot 2025-03-24 at 20 30 05](https://github.com/user-attachments/assets/9efccc97-be1f-4918-9d01-3a437bcd79e3) | ![Screenshot 2025-03-24 at 20 29 53](https://github.com/user-attachments/assets/0d508650-9f01-4008-a376-2aa9cfb0d688) |
</details>
This selector will currently break tests in CloudUI as their current `jsdom` version (20.0.0) does not support the newer CSS …
=> [EuiTable] Add util to check if previous sibling selector is supported

packages/docusaurus-preset/.gitignore
This adds a `.gitignore` file to the new `docusaurus-preset` package, so the lib folder isn't tracked.
=> chore(docusaurus-preset): missing .gitignore file

package.json, packages/eui/changelogs/upcoming/8506.md, yarn.lock
closes https://github.com/elastic/eui-private/issues/217
This PR updates our `prismjs` dependency to the latest version `1.30.0` ([release](https://github.com/PrismJS/prism/releases/tag/v1.30.0)) which includes a fix for an "Arbitrary Code Injection vulnerability"
- Browser QA
- ~(_[emulate forced colors](https://devtoolstips.org/tips/en/emulate-forced-colors/) if you do not have access to a Windows machine_.)~
- Docs site QA
=> Update `prismjs` to 1.30.0

packages/eui/src-docs/src/views/guidelines/_index.scss, packages/eui/src-docs/src/views/theme/color/_color_js.tsx, packages/eui/src-docs/src/views/theme/color/_color_sass.tsx, packages/eui/src-docs/src/views/theme/color/tokens.tsx, packages/website/docs/components/theming/colors/data_vis_colors_preview.tsx, packages/website/docs/components/theming/colors/data_vis_colors_table.tsx, packages/website/docs/components/theming/colors/values.mdx
Previously we added the data vir color tokens to the new EUI+ docs in [this PR](https://github.com/elastic/eui/pull/8462) but we currently don't showcase them in our current docs.
For the time being we still want to add them in the current docs to document them until the new docs are released.
>[!NOTE]
We purposefully only add docs for the base data vis color tokens.
Once other tokens are more stable we can add those as needed.
- adds a section for current data vis color tokens in the EUI docs
| Borealis | Amsterdam |
|-----|----|
| ![Screenshot 2025-03-27 at 11 08 37](https://github.com/user-attachments/assets/4e49cbfc-6642-4d54-874b-c38f8f6a9b3f) | ![Screenshot 2025-03-27 at 11 08 53](https://github.com/user-attachments/assets/71cfe63d-3a8e-423b-b1e7-1a5f9672ec3f) |
- updates the …
=> [Docs] Add data vis color tokens to EUI docs

packages/docusaurus-theme/src/components/demo/demo.tsx, packages/docusaurus-theme/src/theme/CodeBlock/index.tsx, packages/docusaurus-theme/src/theme/DocItem/Layout/index.tsx, packages/docusaurus-theme/src/theme/DocItem/TOC/Mobile/index.tsx, packages/docusaurus-theme/src/theme/DocRoot/Layout/Sidebar/index.tsx, packages/docusaurus-theme/src/theme/Root.styles.ts
Resolves #8161 
This improves the layout for "middle" breakpoints by showing the desktop TOC (content menu on the right hand side) at a greater breakpoint than by default, while keeping the mobile TOC.
In summary: more space for content, TOC is _always_ visible.
It also fixes the problem with the desktop TOC wrapping down the content (original issue).
<details>
<summary>Improved inline spacing for sidebar navigation</summary>
</details>
Reviewing [by commit](https://github.com/elastic/eui/pull/8505/commits) is recommended.
<details>
<summary>List of pages with wide content that could be problematic</summary>
&nbsp;
- [guidelines/writing](https://eui.elastic.co/pr_8505/new-docs/docs/guidelines/writing/)
- [guidelines/writing/examples](https://eui.elastic.co/pr_8505/new-docs/docs/guidelines/ …
=> fix(website): responsiveness of TOC

packages/eui/changelogs/upcoming/8508.md, packages/eui/src/components/tool_tip/tool_tip.stories.tsx, packages/eui/src/components/tool_tip/tool_tip.test.tsx, packages/eui/src/components/tool_tip/tool_tip.tsx, packages/eui/src/components/tool_tip/tool_tip_anchor.tsx
Relates to https://github.com/elastic/kibana/issues/214104#issuecomment-2752091195
Relates to https://github.com/elastic/eui/issues/8429
This PR enables `EuiToolTip` to optionally disable the automatic linking of trigger and tooltip element via `aria-describedby`. In most cases this should not be used, as we want the tooltip content to be available for screen reader users when focusing the trigger element.
There are use cases though were this automatic screen reader output for the tooltip content is an issue because it creates duplication. In those cases the tooltip is used solely as visual text alternative, not as accessible one.
**Example use cases:**
- the trigger element already has a descriptive `aria-label` which is identical to the tooltip content (e.g. when used with an icon …
=> [EuiToolTip] Support conditional screen reader output

packages/website/docs/components/templates/page_template/overview.mdx, packages/website/docs/components/templates/sitewide_search.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/templates`).
Closes [#8468](https://github.com/elastic/eui/issues/8469)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Templates section

packages/docusaurus-theme/src/theme/reset.styles.ts
Resolves https://github.com/elastic/eui/issues/8165
This resets a `height: 100%` in the `<body>` introduced by the [theme's `Layout` component](https://github.com/facebook/docusaurus/blob/e64e0e7c96f695f9d63b22c0d0ee2e4001852ac6/packages/docusaurus-theme-classic/src/theme/Layout/styles.module.css#L8-L11).
=> fix(website): `EuiBottomBar` displacement demo

packages/eslint-plugin/src/rules/no_css_color.ts
Pipeline is failing at the [linting stage](https://buildkite.com/elastic/kibana-pull-request/builds/288757) on the PR: https://github.com/elastic/kibana/pull/210082 because we're trying access `init` in `undefined` in the `@elastic/eui/no-css-color`.
Related to https://github.com/elastic/eui-private/issues/275
1. Checkout this branch: `gh pr checkout `
2. Build the ESLint plugin: `yarn workspace @elastic/eslint-plugin-eui build`
3. Publish locally: `cd packages/eslint-plugin && yalc publish`
Then, in Kibana:
1. Install the local ESLint plugin version: `yalc add @elastic/eslint-plugin-eui`
2. Reinstall dependencies: `yarn kbn bootstrap --no-validate`
Test files:
There should be no errors in the ESLint output. Other warnings should display as appropriate.
=> fix(eslint-plugin): add optional chaining in no_css_color

packages/website/docs/components/layout/accordion.mdx, packages/website/docs/components/layout/bottom_bar.mdx, packages/website/docs/components/layout/flex/flex.mdx, packages/website/docs/components/layout/flex/flex_group.mdx, packages/website/docs/components/layout/flex/flex_item.mdx, packages/website/docs/components/layout/flyout/flyout.mdx, packages/website/docs/components/layout/header.mdx, packages/website/docs/components/layout/modal/overview.mdx, packages/website/docs/components/layout/page_components/overview.mdx, packages/website/docs/components/layout/page_header.mdx, packages/website/docs/components/layout/panel/overview.mdx, packages/website/docs/components/layout/panel/split_panel.mdx, packages/website/docs/components/layout/popover.mdx, packages/website/docs/components/layout/resizable_container.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/layout`).
Closes [#8470](https://github.com/elastic/eui/issues/8470)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Layout section

packages/website/docs/components/navigation/breadcrumbs.mdx, packages/website/docs/components/navigation/button/button_basic.mdx, packages/website/docs/components/navigation/button/button_group.mdx, packages/website/docs/components/navigation/button/overview.mdx, packages/website/docs/components/navigation/collapsible_nav.mdx, packages/website/docs/components/navigation/context_menu.mdx, packages/website/docs/components/navigation/key_pad_menu.mdx, packages/website/docs/components/navigation/link.mdx, packages/website/docs/components/navigation/pagination/guidelines.mdx, packages/website/docs/components/navigation/pagination/overview.mdx, packages/website/docs/components/navigation/tabs/overview.mdx, packages/website/docs/components/navigation/tree_view.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/navigation`).
Closes [#8471](https://github.com/elastic/eui/issues/8471)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Navigation section

packages/website/docs/components/display/badge/beta_badge.mdx, packages/website/docs/components/display/badge/notification_badge.mdx, packages/website/docs/components/display/card.mdx, packages/website/docs/components/display/comment_list.mdx, packages/website/docs/components/display/empty_prompt/overview.mdx, packages/website/docs/components/display/list_group.mdx, packages/website/docs/components/display/loading.mdx, packages/website/docs/components/display/progress.mdx, packages/website/docs/components/display/skeleton.mdx, packages/website/docs/components/display/timeline.mdx, packages/website/docs/components/display/toast/overview.mdx, packages/website/docs/components/display/tooltip.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/display`).
Closes [#8472](https://github.com/elastic/eui/issues/8472)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Display section

packages/website/docs/components/forms/date_time/auto_refresh.mdx, packages/website/docs/components/forms/date_time/date_picker_range.mdx, packages/website/docs/components/forms/date_time/super_date_picker.mdx, packages/website/docs/components/forms/form_layouts/_form_row_callout.mdx, packages/website/docs/components/forms/form_layouts/compressed_forms.mdx, packages/website/docs/components/forms/form_layouts/form_row.mdx, packages/website/docs/components/forms/numeric/range_sliders.mdx, packages/website/docs/components/forms/other/color_picker.mdx, packages/website/docs/components/forms/other/file_picker.mdx, packages/website/docs/components/forms/search_filter/filter_group.mdx, packages/website/docs/components/forms/search_filter/search_bar.mdx, packages/website/docs/components/forms/selection/checkboxes_radios/switch.mdx, packages/website/docs/components/forms/selection/combo_box.mdx, packages/website/docs/components/forms/selection/select.mdx, packages/website/docs/components/forms/selection/selectable.mdx, packages/website/docs/components/forms/selection/super_select.mdx, packages/website/docs/components/forms/text/inline_edit.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/forms`).
Closes [#8473](https://github.com/elastic/eui/issues/8473)
**Checklist**
**Pages**
Optionally, the rest of the pages in the section. I just removed the bold `**` from around the components.
=> fix(website): fix broken links in the Forms section

packages/website/docs/components/tabular_content/data_grid/container_constraints.mdx, packages/website/docs/components/tabular_content/data_grid/style_and_display.mdx, packages/website/docs/components/tabular_content/tables/basic_tables.mdx, packages/website/docs/components/tabular_content/tables/custom_tables.mdx, packages/website/docs/components/tabular_content/tables/in_memory_tables.mdx, packages/website/docs/components/tabular_content/tables/overview.mdx
On this PR:
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/tabular_content`).
Closes [#8474](https://github.com/elastic/eui/issues/8474)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Tabular content section

packages/website/docs/components/editors_and_syntax/code.mdx, packages/website/docs/components/editors_and_syntax/markdown/editor.mdx, packages/website/docs/components/editors_and_syntax/markdown/format.mdx, packages/website/docs/components/editors_and_syntax/markdown/plugins.mdx
On this PR:
- I fix broken links,
- I used `<Link>` from Docusaurus in an example `packages/website/docs/components/editors_and_syntax/markdown/editor.mdx#error-handling-and-feedback`.
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/editors_and_syntax`).
Closes [#8475](https://github.com/elastic/eui/issues/8475)
**Checklist**
**Pages**
=> fix(website): fix broken links in the Editors & Syntax section

packages/website/docs/components/utilities/css_utility_classes.mdx
On this PR:
- I changed a relative link to file path as recommended in [Markdown links | Docusaurus](https://docusaurus.io/docs/markdown-features/links),
- I fix a broken link.
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/components/utilities`).
Closes [#8476](https://github.com/elastic/eui/issues/8476)
**Checklist**
**Pages**
Optionally, check other pages.
=> fix(website): fix broken links in the Utilities section

packages/website/docs/content/overview.mdx
On this PR:
- I change relative links to file paths as recommended in [Markdown links | Docusaurus](https://docusaurus.io/docs/markdown-features/links),
> [!TIP]
> I use `\[(.*?)\]\((.*?)\)|<a\s+[^>]*href=["'](.*?)["'][^>]*>(.*?)<\/a>` regexp to find all Markdown links and anchor tags in the specific section (e.g. `website/docs/content`).
Closes [#8478](https://github.com/elastic/eui/issues/8478)
**Checklist**
=> fix(website): fix a broken link on the Content page

packages/website/docs/components/display/skeleton.mdx, packages/website/docs/components/display/stat.mdx
Resolves #8150
Resolves #8152 
Improves the examples in Stat, and fixes a little bug in a Skeleton example regarding the size of an image.
> [!IMPORTANT]
> in the Skeleton component, the issue with the spacing between bars being different is related to the component CSS itself, not any globals in Docusaurus; namely the value for `margin-block-start: 0.8571rem;` is different from the one in production, I'm guessing there's something in the tokens?
=> fix(website): Stat and Skeleton examples

packages/eui/changelogs/upcoming/8550.md, packages/eui/src/global_styling/mixins/_button.ts
This PR fixes a visual issue for disabled `EuiButton` with `filled={true}` where the wrong color token was applied for text and border colors in high contrast mode.
| colorMode | before | after |
|---|---|---|
| LIGHT | ![Screenshot 2025-04-04 at 13 13 10](https://github.com/user-attachments/assets/72fb2207-06f0-4e90-aa99-a8cd19eac789) | ![Screenshot 2025-04-04 at 13 13 31](https://github.com/user-attachments/assets/4442ee57-2d56-439f-9003-ad9bd07f3666) |
| DARK | ![Screenshot 2025-04-04 at 13 13 16](https://github.com/user-attachments/assets/f2d93489-cc5b-46d1-9c58-75fa3ed1aba9) | ![Screenshot 2025-04-04 at 13 13 36](https://github.com/user-attachments/assets/182bf42b-f4ee-4af3-b162-937469f523f8) |
- Browser QA
- (_[emulate forced …
=> [EuiButton][HCM] Fixes color of disabled buttons in high contrast mode

packages/docusaurus-theme/src/components/prop_table/prop_table.tsx
On this PR, I use the Docusaurus' `Heading` component that contains the copy anchor icon button and I pass an `id` so that the prop table title becomes an anchor.
Closes https://github.com/elastic/eui/issues/8556
1. Checkout the branch: `gh pr checkout 8557` or access the staging environment.
2. Access any component page, e.g. [Accordion](https://eui.elastic.co/pr_8557/new-docs/docs/layout/accordion/).
3. Scroll down (or use TOC) to "Props" section.
=> feat(docusaurus-theme): use the Heading component in prop table

.buildkite/pipelines/deploy_docs.yml, .buildkite/pipelines/pipeline_pull_request_deploy_docs.yml, .buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh, catalog-info.yaml
Resolves https://github.com/elastic/eui-private/issues/118.
This PR adds a new `eui-deploy-docs` pipeline configuration and descriptor to enable building the new documentation site from `main` and publish it under https://eui.elastic.co/next. It adds to the existing `pipeline_deploy_new_docs.sh` script we've used for a while now to build and deploy the new documentation site.
There's no way to test the pipeline without merging it to `main`. Please check the correctness of the bash script and `catalog-info.yml` configuration changes.
=> Add `eui-deploy-docs` pipeline to build and deploy new documentation website 

.buildkite/pipelines/deploy_docs.yml
This PR fixes placement of the `image` setting introduced in https://github.com/elastic/eui/pull/8569
There's no real way to live test these changes before merging.
=> Fix `eui-deploy-docs` pipeline agent image configuration

.buildkite/pull-requests.json
This PR adds a buildkite job trigger when PR is open or changed. It runs the `eui-deploy-docs` job added in an earlier PR today and uses the same configuration as the other `eui-pull-request-test-and-deploy` job.
There's no way to check this live before merging. Check the correctness of JSON formatting. You may also compare it to the other job trigger defined above in the same file
=> Add pull request job trigger

packages/eui/src-docs/src/views/i18n/i18n_example.js, packages/eui/src-docs/src/views/package/i18n_tokens.js, packages/website/docs/getting_started/utilities/i18n.mdx
Resolves https://github.com/elastic/eui-private/issues/268
This PR adds a couple of paragraphs and a warning to the `i18n` utilities page, in order to make it clearer for what it is and what it isn't.
It also fixes a broken link to GitHub in the `i18n tokens` package page (old site). Source code e.g. `src/components/basic_table/basic_table.tsx:320:6` links point to the previous project structure before the monorepo.
>[!WARNING]
> A couple of links are missing for the new docs, waiting for #8547 
Staging links:
- [Old docs](https://eui.elastic.co/pr_8554/#/utilities/i18n)
- [Old docs, tokens package → GitHub links](https://eui.elastic.co/pr_8554/#/package/i18n-tokens)
- [New site](https://eui.elastic.co/pr_8554/new-docs/docs/utilities/i18n/)
=> docs: improve `i18n` section

packages/eui/changelogs/upcoming/8565.md, packages/eui/src/components/expression/expression.styles.ts, packages/eui/src/components/expression/expression.tsx, packages/eui/src/components/facet/__snapshots__/facet_button.test.tsx.snap, packages/eui/src/components/facet/facet_button.styles.ts, packages/eui/src/components/facet/facet_button.tsx, packages/eui/src/components/facet/facet_group.styles.ts, packages/eui/src/components/facet/facet_group.tsx, packages/eui/src/components/filter_group/__snapshots__/filter_button.test.tsx.snap, packages/eui/src/components/filter_group/filter_button.tsx, packages/eui/src/components/filter_group/filter_group.tsx, packages/eui/src/components/header/header.tsx, packages/eui/src/components/header/header_alert/header_alert.tsx, packages/eui/src/components/header/header_links/header_links.tsx, packages/eui/src/components/header/header_logo/header_logo.tsx, packages/eui/src/components/header/header_section/__snapshots__/header_section_item_button.test.tsx.snap, packages/eui/src/components/header/header_section/header_section_item.tsx, packages/eui/src/components/header/header_section/header_section_item_button.tsx, packages/eui/src/components/image/image.tsx, packages/eui/src/components/image/image_button.tsx, packages/eui/src/components/image/image_caption.tsx, packages/eui/src/components/image/image_fullscreen_wrapper.tsx, packages/eui/src/components/image/image_wrapper.tsx, packages/eui/src/components/list_group/list_group.tsx, packages/eui/src/components/list_group/list_group_item.styles.ts, packages/eui/src/components/list_group/list_group_item.tsx, packages/eui/src/components/list_group/list_group_item_extra_action.test.tsx, packages/eui/src/components/list_group/list_group_item_extra_action.tsx, packages/eui/src/components/list_group/pinnable_list_group/pinnable_list_group.tsx
This PR contains cherry-picked commits from Cee's PR https://github.com/elastic/eui/pull/8172 in order to make it more straightforward to review and omit some of the changes incompatible with post-Borealis EUI source.
- Browser QA
- Docs site QA
=> [Emotion] Cherry pick style memoization commits

packages/eui/changelogs/upcoming/8591.md, packages/eui/src/components/collapsible_nav/__snapshots__/collapsible_nav.test.tsx.snap, packages/eui/src/components/flyout/__snapshots__/flyout.test.tsx.snap, packages/eui/src/components/flyout/flyout.tsx
This PR ensures that for overlay flyouts (that essentially behave as modals with `role="dialog"`) also have the appropriate `aria-modal` applied.
- Browser QA
- Docs site QA
=> [EuiFlyout] Add `aria-modal` to overlay flyouts

packages/website/docs/components/display/text.mdx
Closes https://github.com/elastic/eui/issues/8566
This PR updates the "Text can come in various sizes" example on the Text page on the new documentation site. I was failing because was trying to access `focus` in `undefined`. The reason is we were relying on `euiTheme` supplied to the `css` callback function but we cannot do that in Demo context.
=> fix(website): use euiTheme from useEuiTheme hook

packages/eui/src/components/header/header.tsx, packages/eui/src/components/key_pad_menu/key_pad_menu.tsx, packages/eui/src/components/list_group/pinnable_list_group/pinnable_list_group.tsx, packages/eui/src/components/selectable/selectable.tsx, packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide.tsx, packages/eui/src/components/selectable/selectable_templates/selectable_template_sitewide_option.tsx
Closes https://github.com/elastic/eui/issues/8555
This PR updates anchor links to have exact names (like the interface / type, not the prop table header).
> [!IMPORTANT]
> This will break prop table description redirections at times.
=> chore(eui): update anchor links to have exact names

packages/eui/changelogs/upcoming/8597.md, packages/eui/src/components/basic_table/__snapshots__/basic_table.test.tsx.snap, packages/eui/src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap, packages/eui/src/components/basic_table/basic_table.test.tsx, packages/eui/src/components/datagrid/__snapshots__/data_grid.test.tsx.snap, packages/eui/src/components/pagination/__snapshots__/pagination.test.tsx.snap, packages/eui/src/components/pagination/pagination.tsx, packages/eui/src/components/pagination/pagination_button.tsx, packages/eui/src/components/table/table_pagination/__snapshots__/table_pagination.test.tsx.snap
Closes https://github.com/elastic/eui/issues/8521
This PR removes aria attributes from the `ul` element as they are not necessary and lead to a duplicate `aria-label` and screen reader output in the Pagination component.
Additionally, I made `aria-current` more specific by passing [page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-current#page).
- Browser QA
- Docs site QA
=> fix(eui): remove duplicated aria-label in pagination

packages/website/docs/components/layout/horizontal-rule.mdx
Fixes the Margins demo not rendering for the `EuiHorizontalRule` component.
=> fix(website): `EuiHorizontalRule` margins demo

packages/eui-theme-borealis/changelogs/upcoming/8606.md, packages/eui-theme-borealis/package.json, yarn.lock
closes https://github.com/elastic/eui/issues/8599
This PR updates the `eui-theme-common` dependency in the `eui-theme-borealis` package from `peer dependency` to `dependencies` as `borealis` fully depends on the `common` package.
This also solves the current issue that the version for the `peer dependency` is not automatically updated when creating releases.
=> Make `@elastic/eui-theme-common` a full dependency on `@elastic/eui-theme-borealis`

packages/eslint-plugin/changelogs/upcoming/8613.md, packages/eslint-plugin/src/rules/no_restricted_eui_imports.test.ts, packages/eslint-plugin/src/rules/no_restricted_eui_imports.ts
Closes https://github.com/elastic/eui/issues/8612
This PR removes the mention of removing JSON tokens as per the deprecation schedule from the `no-restricted-eui-imports` warning message. We still need to support them for server-side / non-React.
=> chore(eui): change the `no-restricted-eui-imports` warning message

.buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh
This fixes the `gcloud storage cp` command to perform a regular upload copy instead of "copy in the cloud" copy that fails due to the recursive flag being passed. Going with a regular copy is safer for now.
=> Fix tagged release copy method in the `eui-deploy-docs` pipeline

.buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh
This hotfixes the base path when performing a tagged release deployed to `/`. Currently tagged releases are published to `/v<version>` and to `/` but the package is built only once with base URL set to `/v<version>` which causes an issue with docusaurus routing.
This PR skips the `/v<version>` copy, uses `/` base URL and deploys only to `/`. I'm going to fix deploying to `v<version>` in a follow-up PR.
=> Fix latest release base path

packages/website/docs/components/index.mdx
Fixed broken links on https://eui.elastic.co/docs/components/
For the Tabular Data link, I linked to Basic Table instead. I feel like that a better page to land on, even though it's not first.
Clink on all of the links on the Overview page in the preview site and make sure they work.
=> Fixed broken links on Components Overview page

packages/website/docs/components/display/beacon.mdx, packages/website/docs/components/display/code.mdx, packages/website/docs/components/display/empty-prompt/types_of_empty_states/use_cases.tsx, packages/website/docs/dataviz/theming.mdx, packages/website/docs/dataviz/types/metric-chart.mdx, packages/website/docs/getting-started/theming/utilities/typography.mdx, packages/website/docs/patterns/index.mdx
Readme link
EuiTour link
CodeEditor link
EuiCard link
"use EuiText or EuiTextColor" link
EuiStat
Contributions and join the discussion links
=> Fixed links on docs site

packages/website/docs/utilities/error-boundary.mdx
Fixes https://github.com/elastic/eui/issues/8379
I added more guidance for using [EuiErrorBoundary](https://eui.elastic.co/docs/utilities/error-boundary/).
I also found a unique opportunity to cross-link the Error messages pattern.
Just review the text and check out the page in the preview environment.
=> Updated Error Boundary docs with more guidance

packages/yarn-plugin-validate-env/package.json
This fixes hoisting limits for yarn-plugin-validate-env that made the release-cli build fail due to package version conflicts after merging https://github.com/elastic/eui/pull/8450. `yarn-plugin-validate-env` is a whole separate utility package that isn't built often and can have hoisting limits set to `workspaces`.
=> Fix broken hoisting limits in yarn-plugin-validate-env

packages/website/docs/components/display/icons/index.mdx
This question came up during support week. I thought it would be worthwhile to document it, as part of our `support-duty-flywheel`. I've labeled it as such.
Just review the wording and double check it in the preview deployment.
=> Added background image guide to icons page

packages/website/docs/components/forms/date-and-time/super-date-picker.mdx
On this PR, I add a `EuiSwitch` and `EuiSelect` to control the `compressed` and `width` props of the `EuiSuperDatePicker` component in the Sizing example on the documentation website.
<details><summary>Testing video</summary>
<p>
https://github.com/user-attachments/assets/dc4aa817-5940-4658-891e-3aba63aa5bf7
</p>
</details>
=> fix(website): fix the EuiSuperDatePicker Sizing example

packages/eui-theme-borealis/changelogs/CHANGELOG_2025.md, packages/eui-theme-common/changelogs/CHANGELOG_2025.md, packages/eui/changelogs/CHANGELOG_2025.md, packages/release-cli/src/update_changelog.ts
This PR updates the`update_changelog.ts` script in our `release-cli` package to ensure that nested children won't have a PR link attached. The parent bullet point will have the link, anything else that's nested is too verbose.
_output before the update_
The update assumes that anything with +2 spaces followed by a `-` or  `*` is a nested item
_output after the update_
- add a changelog item in `packages/eui/changelogs/upcoming` that has nested items:
```
- Testing multiple nested levels
- level 1
- level 2
- level 3
* level 1.1
```
- make sure you're logged out from any registry: `yarn npm logout` and if needed `npm logout`
- run a local npm registry with `docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio`
- update the `.yarnrc.yml` with
```
npmRegistryServer: …
```
=> [Changelog] Update release script to not add PR link on nested children

.github/actions/check-changelog/action.yml, .github/actions/check-changelog/entrypoint.sh, .github/workflows/changelog.yml
This PR updates the changelog PR check. It adds a custom action with a bash script that matches `packages/*/upcoming/${pr_number}`.
[`changelog-enforcer`](https://github.com/dangoslen/changelog-enforcer) doesn't work with monorepo.
In the future, we could use something like [changesets](https://github.com/changesets/changesets). For the time being, we can use this simple solution.
<details><summary>Screenshots</summary>
<p>
</p>
</details>
=> chore: verify changelog in all packages

packages/release-cli/src/cli.ts, packages/release-cli/src/release.ts, packages/release-cli/src/steps/init_checks.ts, packages/release-cli/src/steps/update_versions.ts
Resolves https://github.com/elastic/eui-private/issues/273
This adds support for custom official releases to the release CLI. We need these releases for the `classic`/`amsterdam` backport releases we do weekly to support the old Amsterdam theme in Kibana 8.x.
The way we create these releases is manual and requires cherry picking specific commits on top of branched out `main`. They follow the regular EUI release versioning, but are suffixed with an `amsterdam` prerelease identifier (preid) for easy distinction. This process will stay manual since managing branches and cherry picks in a script is quite painful and can easily lead to an unpredictable state.
The point of this update is to allow releasing these custom backport releases with the release CLI instead of having to manually build …
=> feat(release-cli): Support custom (classic) releases

packages/website/docs/getting-started/theming/tokens/colors/background_colors_table.tsx, packages/website/docs/getting-started/theming/tokens/colors/border_colors_table.tsx, packages/website/docs/getting-started/theming/tokens/colors/index.mdx, packages/website/docs/getting-started/theming/tokens/colors/severity_background_colors_table.tsx, packages/website/docs/getting-started/theming/tokens/colors/severity_text_colors_table.tsx, packages/website/docs/getting-started/theming/tokens/colors/text_colors_table.tsx, packages/website/docs/patterns/severity.mdx
This is, hopefully, a small addition to our documentation. Within Patterns, I have included a new Health & Severity dedicated page with descriptions of Severity Levels with a list of available tokens and a few guidelines on how to use them.
First time making a PR for EUI so please feel free to suggest changes or fixes
=> Severity pattern page

packages/website/package.json, packages/website/scripts/update-versions.js
Closes https://github.com/elastic/eui-private/issues/316
This PR adds a `postrelease` script to `@elastic/eui-website` package so that on each EUI release, a new version is added to the `versions.json` file, and subsequently to the version switcher.
Only official releases following the semantic versioning `vX.Y.Z` are added. Snapshot and backport releases are skipped.
1. Checkout this branch: `gh checkout pr 8638`
2. Ensure you're logged out of npm: `yarn npm logout`
3. Run a local registry to which the packages are publish instead of npm: `docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio`
4. Update the root `.yarnrc.yml` file by adding:
```yaml
npmRegistryServer: "http://localhost:4873"
unsafeHttpWhitelist:
- localhost
- "localhost:4873"
```
5. Login to the local …
=> chore(website): add postrelease script

packages/eui/changelogs/upcoming/8626.md, packages/eui/package.json, packages/eui/src/components/comment_list/comment_timeline.tsx, packages/eui/src/components/datagrid/body/header/draggable_columns.tsx, packages/eui/src/components/form/field_password/field_password.tsx, packages/eui/src/services/accessibility/html_id_generator.test.tsx, yarn.lock
Closes https://github.com/elastic/eui/issues/7344
On this PR, I update from `typescript@v4.5.3` to `typescript@v5.8.3`. It can be merged after https://github.com/elastic/eui/pull/8624. Currently, it blocks https://github.com/elastic/eui/pull/8543.
=> chore(eui): update to typescript@v5.8.3

packages/docusaurus-theme/src/theme/MDXComponents/Blockquote.tsx, packages/docusaurus-theme/src/theme/MDXComponents/index.ts, packages/website/docs/getting-started/theming/tokens/borders/border_radii_table.tsx, packages/website/docs/getting-started/theming/tokens/borders/border_widths_table.tsx, packages/website/docs/getting-started/theming/tokens/borders/borders_table.tsx, packages/website/docs/getting-started/theming/tokens/borders/index.mdx
- Add missing Blockquote component in MDX 1603cf11ff4b92e0c755289ef73c1298679880c8
- Add info regarding border radius size in Tokens section 853c71f8ce2679bd9d0a248dbe168fda3c5b0224
Closes https://github.com/elastic/eui-private/issues/325
=> docs: blockquotes in MDX / `border.radius.medium` info

packages/eui/changelogs/upcoming/8640.md, packages/eui/src/components/datagrid/utils/scrolling.test.tsx, packages/eui/src/components/datagrid/utils/scrolling.tsx
Closes #8484
On this PR, I fix the issue where the actions menu gets hidden under the header in the `EuiDataGrid` when scrolling into view (when clicking on the cell) in the top direction.
The offset is applied conditionally to the top because as you can see below, the down direction doesn't need any adjustment.
I thought about accessing the actions menu height programmatically which would make it more robust BUT we don't plan on changing the height or supporting customizing the height of the actions menu. Any logic that'd calculate the height is at a performance cost. A simple constant is enough for now.
**Before**
https://github.com/user-attachments/assets/1c0cbfb3-6849-47cd-8bbf-14744d71735f
**After**
https://github.com/user-attachments/assets/a4c7a092-f369-4d32-b1ea-343c3eb85fea
- …
=> fix(eui): add scroll offset for actions menu in EuiDataGrid

packages/eui/changelogs/upcoming/8692.md, packages/eui/src/components/toast/global_toast_list.tsx
closes https://github.com/elastic/eui/issues/8611
This PR updated `EuiGlobalToastList` to save all dismissable toasts as array, instead of only the last one.
This ensures that all toasts are properly cleaned up when multiple toasts are added and dismissed at exactly the same time.
_before_
_after_
- wait until all toasts are dismissed automatically after the default timeout
- inspect the DOM and verify all elements have been removed from the log list
- Browser QA
- Docs site QA
=> [EuiGlobalToastList] Ensure all toasts are removed after the timeout is cleared

packages/eui/changelogs/upcoming/8688.md, packages/eui/src/components/datagrid/body/data_grid_body_virtualized.test.tsx, packages/eui/src/components/datagrid/body/data_grid_body_virtualized.tsx, packages/eui/src/components/datagrid/data_grid.stories.tsx, packages/eui/src/components/datagrid/data_grid_types.ts, packages/website/docs/components/tabular-content/data-grid/container-constraints.mdx
closes https://github.com/elastic/eui/issues/8422
This PR updates the `virtualizationOptions.onScroll` prop on `EuiDataGrid` by passing additional scroll position data as callback arguments. This allows consumers to handle additional checks based on scroll position, e.g. identify when a user has scrolled to the end of the grid.
- open the "Virtualization" story and scroll
- review the `onScroll` arguments output in the "Actions" tab and confirm the values update correctly
- Browser QA
- Docs site QA
=> [EuiDataGrid] Pass scroll position data as args in onScroll

packages/eui/changelogs/upcoming/8701.md, packages/eui/src/services/theme/hooks.test.tsx, packages/eui/src/services/theme/hooks.tsx, packages/eui/src/services/theme/index.ts, packages/website/docs/getting-started/theming/color-mode.mdx
closes https://github.com/elastic/eui/issues/8693
This PR introduces the small utility hook `useIsDarkMode` to reduce the boilerplate for consumers to add conditional `colorMode` checks manually.
- Browser QA
- Docs site QA
=> [Feat] Add `useIsDarkMode` hook

packages/docusaurus-theme/src/components/index.ts, packages/docusaurus-theme/src/components/theme_context/index.tsx, packages/website/package.json, packages/website/src/theme/Root.tsx, yarn.lock
Fixes https://github.com/elastic/eui/issues/8713
This PR upgrades `@elastic/charts` to the latest version and uses the correct value from app theme context to determine what charts stylesheet should be injected. This was likely broken when we introduced theme switching in docs a while ago.
=> Upgrade and fix @elastic/charts in docs

packages/eui/changelogs/upcoming/8705.md, packages/eui/src/components/filter_group/filter_button.stories.tsx, packages/eui/src/components/filter_group/filter_button.tsx, packages/website/docs/components/forms/search-and-filter/filter-group.mdx
Resolves #8695
This PR extends the type of `numActiveFilters` to accept percentage values as strings. For simplicity, there's no fancy string type checking - instead, we trust the user and save a little bit of time during type resolution.
- Browser QA
- Docs site QA
=> feat(EuiFilterButton): accept percentages in `numActiveFilters` prop

packages/docusaurus-preset/src/index.ts
This PR excludes a specific style file from being loaded in our docs, as it interferes with EUI focus styles.
The style rule ([code](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/hooks/styles.css)) has a higher specificity than regular styles and causes issues for the upcoming input design changes.
```
body:not(.navigation-with-keyboard) *:not(input):focus {
outline: none;
}
```
Since EUI handles focus outline styling and uses the `outline` property for it, this style is causing issues as it overrides EUI.
Taken on input VR changes on `eui-theme/borealis-v2-poc` (not merged)
_before_
_after_
- renames`ignoreInfimaPlugin` to `ignoreInheritedStylesPlugin` to indicate it's generally about ignoring applied styles instead of only infima styles
-  adds an …
=> [Docs] Remove Docusaurus global focus outline styles

packages/eui-theme-borealis/changelogs/upcoming/8764.md, packages/eui-theme-borealis/package.json, packages/eui-theme-borealis/tsconfig.cjs.json, packages/eui-theme-borealis/tsconfig.json, packages/eui-theme-borealis/tsconfig.types.json, packages/eui-theme-common/changelogs/upcoming/8764.md, packages/eui-theme-common/package.json, packages/eui-theme-common/tsconfig.cjs.json, packages/eui-theme-common/tsconfig.json, packages/eui-theme-common/tsconfig.types.json
Resolves https://github.com/elastic/eui/issues/8699
Based on a recent discussion, we've decided not to include sourcemaps in published packages.
The reason is primarily based on the fact that our distribution files aren't minified, and having source maps pointing to TypeScript source files that we don't include in published packages leads to "file not found" warnings reported for some bundler configurations.
1. Checkout this branch locally
2. Install all dependencies - `yarn`
3. Build related packages - `yarn workspace @elastic/eui-theme-borealis build && yarn workspace @elastic/eui-theme-common build`
4. Confirm the dist directories (`packages/eui-theme-borealis/lib` and `packages/eui-theme-common/lib`) contain no `.map` files
=> Disable generation of sourcemaps for @elastic/eui-theme-borealis and @elastic/eui-theme-common

packages/eui-theme-borealis/changelogs/upcoming/8725.md, packages/eui/changelogs/upcoming/8725.md
Initially [this PR](https://github.com/elastic/eui/pull/8725) was marked as non-breaking but after discussion we decided to consider those type of visual changes as breaking too.
While the changes are not technically breaking, they require updates to be used the way we intent them to.
=> [Changelog] Update #8725 changelogs

packages/website/docs/getting-started/theming/tokens/colors/index.mdx
I updated guidance for Data Visualization colors as well as Health and Severity colors to recommend some guidance mentioned in various channels.
Also, Fixes https://github.com/elastic/eui/issues/8738 with https://github.com/elastic/eui/commit/2439190fa867c26e23e77db1b7efa976728db6ce
Once the build preview is available below, you can review this on the colors page at docs/getting-started/theming/tokens/colors/
**Screenshots**
=> [Docs] Updated colors page with data vis contrast and usage guidance

packages/website/src/components/homepage/highlights/index.tsx
Fixed broken "Forms" link on the home page of docs.
Fixes https://github.com/elastic/eui/issues/8738
=> [Docs] Fixed form link on home page

packages/website/docs/content/index.mdx, packages/website/docs/content/language.mdx, packages/website/docs/content/style.mdx
This PR adds a few details and missing pieces to the updated content guidelines. These details are retrieved from obsolete files deleted in https://github.com/elastic/eui/pull/8683.
Closes: https://github.com/elastic/platform-docs-team/issues/674
=> [Content] Adds relevant content guidelines and examples from obsolete files

packages/eui-theme-borealis/src/variables/_overrides.ts, packages/eui-theme-common/changelogs/upcoming/8742.md, packages/eui-theme-common/src/utils.ts, packages/eui/changelogs/upcoming/8742.md, packages/eui/src/components/button/button.stories.tsx
This PR fixes a small mistake in the theme overrides functionality (introduced in [this commit](https://github.com/elastic/eui/pull/8558/commits/95fe71de26c5aefdb731b9fd3ffa4b3b4b5cd79d)) which resulted in overrides not being applied 🫠 
The issue was that a wrong variable was used which would not hold all expected override values.
Checkout the PR and in Storybook:
- set HCM in the Storybook top toolbar
- verify that both light and dark mode overrides are applied
- Browser QA
- Docs site QA
=> [HCM] Fix theme high contrast overrides

packages/eui/changelogs/upcoming/8780.md, packages/eui/src/themes/amsterdam/global_styling/variables/_colors_vis.ts
This PR fixes a circular dependency on the legacy Amsterdam theme that was introduced [here](https://github.com/elastic/eui/pull/8725). This would cause the usage of `EuiThemeAmsterdam` as theme to break.
Fixes broken legacy theme.
This currently impacts the release of `eui-theme/amsterdam`.
- Browser QA
- Docs site QA
=> [Amsterdam] Fix circular import

.github/config/label_commenter_config.yml
Breaking change label commenter links to the wrong pre-release instructions ([example](https://github.com/elastic/eui/pull/8758#issuecomment-2949485657)). I updated it to: https://github.com/elastic/eui/blob/main/wiki/eui-team-processes/releasing-versions.md#pre-release-process
=> chore: update pre-release link for breaking changes

packages/website/docs/components/forms/selection/selectable.mdx, packages/website/docs/components/navigation/side-nav.mdx
On this PR, I update the docs to offer more guidance and reflect the current state.
- [feat(docs): add a warning for EuiSelectable virtualization in jsdom](https://github.com/elastic/eui/commit/4c2c72fd96e46841bef5121234b8348cf959094b)
- [feat(website): remove mention about old docs in EuiSideNav](https://github.com/elastic/eui/commit/764ac6dceb4373eb121ba46dc109bf724cb63cff)
=> feat(docs): add a warning for EuiSelectable virtualization in jsdom

packages/eui/changelogs/upcoming/8786.md, packages/eui/src/components/card/checkable_card/checkable_card.spec.tsx, packages/eui/src/components/card/checkable_card/checkable_card.tsx, packages/eui/src/components/form/checkbox/checkbox.tsx, packages/website/docs/components/containers/card.mdx
closes https://github.com/elastic/eui/issues/8782
This PR fixes an unexpected behavior where the `onChange` event would be triggered twice on click of the checkbox within `EuiCheckableCard`. This would result in the checkbox being unchecked instead of checked.
This was due to the wrapper having a separate click handler to enlarge the clickable area. 
The fix applied is to only trigger the wrapper click handler if the wrapper is clicked, not the checkbox.
Scenario: After a single click on the checkbox:
**before: checkbox is unchecked**
**after: checkbox is checked**
- checkout this PR and open the added "TESTING_EXAMPLE" story and:
- Browser QA
- Docs site …
=> [EuiCheckableCard] Fix onChange handler being invoked twice

packages/eui/src/themes/amsterdam/_colors_dark.scss, packages/eui/src/themes/amsterdam/_colors_light.scss, packages/eui/src/themes/amsterdam/global_styling/variables/_colors.ts, packages/eui/src/themes/json/eui_theme_amsterdam_dark.json, packages/eui/src/themes/json/eui_theme_amsterdam_light.json, packages/website/docs/getting-started/theming/tokens/colors/border_colors_table.tsx
In https://github.com/elastic/eui/pull/8769 there was the need to update the color token used for the selected outline in the Data Grid, to be `border-strong-primary`. In order to make this work in Amsterdam, the value for the token also had to be updated.
In this PR all `border-strong-*` tokens get an adequate value so they could actually useful beyond the change in the [aforementioned PR](https://github.com/elastic/eui/pull/8769).
Because it's needed for https://github.com/elastic/eui/pull/8769 and it made sense to make a separate PR.
The [codesandbox](https://codesandbox.io/p/sandbox/naughty-sea-wkcxj8) used to generate and "test" the colors.
The `border-strong` color is the second in each block e.g. `tint(accent, 0.1)`.
| Light | Dark |
| ----- | ---- |
| …
=> [Amsterdam] Update values for `border-strong-*` tokens

packages/eui/changelogs/upcoming/8758.md, packages/eui/src/components/copy/copy.test.tsx, packages/eui/src/components/copy/copy.tsx, packages/website/docs/components/display/icons/index.mdx, packages/website/docs/components/navigation/buttons/guidelines_context_menu.tsx, packages/website/docs/components/navigation/context-menu.mdx
> [!IMPORTANT]
> This is a **breaking change**.
Closes https://github.com/elastic/eui/issues/8382
On this PR, I:
- [feat(eui): add tooltipProps prop to EuiCopy](https://github.com/elastic/eui/commit/6f125458541afd497d2066765ec2b1a5bc0c9e96)
- [chore(eui): rewrite EuiCopy tests to RTL](https://github.com/elastic/eui/commit/9fc6b39965ee4108f66ab09ac1a41ded711d7d17)
- [chore(eui): add a test for tooltipProps in EuiCopy](https://github.com/elastic/eui/commit/6a78cfd7e0f8ebc2da88183aa7840c1608e44cef)
- [refactor(website): use tooltipProps for EuiCopy](https://github.com/elastic/eui/commit/2fcd641eb44d0d04de9ff9e52de3d09fc1801b3f)
Control displays correctly:
No VRT references difference that could be a result of the changes on this PR.
| Production | Localhost |
| ----------- | --------- |
| …
=> feat(eui): add tooltipProps prop to EuiCopy

packages/eui/changelogs/upcoming/8819.md, packages/eui/src/themes/json/eui_theme_borealis_dark.json, packages/eui/src/themes/json/eui_theme_borealis_dark.json.d.ts, packages/eui/src/themes/json/eui_theme_borealis_light.json, packages/eui/src/themes/json/eui_theme_borealis_light.json.d.ts
This PR is a follow-up fix to [this previous PR](https://github.com/elastic/eui/pull/8769). It adds missing JSON token exports.
This fixes typescript errors when using the JSON tokens.
=> [Fix] Add missing JSON token exports

packages/website/docs/getting-started/setup.mdx
Closes https://github.com/elastic/eui-private/issues/205
On this PR, I add a section regarding supported environments to our docs. For quick reference:
| Environment                | Supported?  | Details |
|----------------------------|:-----------:|---------|
| **React 16**               |     ✅      | Fully supported (plans to [deprecate support for React 16](https://github.com/elastic/eui/issues/8578)) |
| **React 17**               |     ✅      | Fully supported |
| **React 18**               |     ✅      | Fully supported (recommended) |
| **React 19**               |     ❌      | Not supported (plans to [introduce support for React 19](https://github.com/elastic/eui/issues/8720)) |
| **Webpack**                |     ✅      | Fully supported |
| **Vite**                   |     ⚠️ …
=> feat(website): add a supported environments section

packages/website/docs/components/display/empty-prompt/index.mdx, packages/website/docs/components/tables/in-memory.mdx
An time-based state change in a demo causes a page to jump, below the demo. This PR fixes that by adding a fixed height to the container.
The bug being fixed:
https://github.com/user-attachments/assets/a4661be5-3b47-4f47-8346-f54f82ed9a74
(thank you @MiriamAparicio)
=> [Docs] Fix page jump for Empty Prompt page

packages/eui/changelogs/upcoming/8839.md, packages/eui/src/components/progress/__snapshots__/progress.test.tsx.snap, packages/eui/src/components/progress/progress.stories.tsx, packages/eui/src/components/progress/progress.tsx
closes https://github.com/elastic/eui/issues/8837
This PR updates **EuiProgress** to ensure that progress updates are announces to screen reader users. Previously users would only be able to know the current progress of the element by manually navigating to it in the DOM.
- adds a `aria-live` region in **EuiProgress** that mirrors the values of `label` and `value`, reading on progress update e.g. `Loading 10%`
- ℹ️ Due to the native behavior of `aria-live` with `aria-atomic` the initial value will not be output, only updates will trigger an output. This is expected as we don't want the value to be read on mount but only on update. This means we can support static value display as well as loading states.
- removes the visible `label` and `valueText` output from the accessibility tree with …
=> [EuiProgress][A11y] Announce determinate progress update to screen readers

packages/eslint-plugin/README.md, packages/eslint-plugin/changelogs/upcoming/8843.md, packages/eslint-plugin/src/index.ts, packages/eslint-plugin/src/rules/a11y/consistent_is_invalid_props.test.ts, packages/eslint-plugin/src/rules/a11y/consistent_is_invalid_props.ts, packages/eslint-plugin/src/utils/get_attr_value.ts
This PR introduces a new ESLint rule to improve form validation consistency in EUI:
This rule ensures that form control components within `EuiFormRow` components have matching `isInvalid` prop values. This maintains consistent validation state between parent form rows and their child form controls, leading to a more predictable and accessible user experience.
Form controls nested within `EuiFormRow` components can have mismatched `isInvalid` props
=> feat(eslint-plugin): add new @elastic/eui/consistent-is-invalid-props rule

packages/eui/changelogs/upcoming/8846.md, packages/eui/src/components/flyout/index.ts, packages/eui/src/components/flyout/sessions/README.md, packages/eui/src/components/flyout/sessions/flyout_provider.stories.tsx, packages/eui/src/components/flyout/sessions/flyout_provider.tsx, packages/eui/src/components/flyout/sessions/flyout_reducer.ts, packages/eui/src/components/flyout/sessions/index.ts, packages/eui/src/components/flyout/sessions/types.ts, packages/eui/src/components/flyout/sessions/use_eui_flyout.test.tsx, packages/eui/src/components/flyout/sessions/use_eui_flyout.ts
This PR is part of a series of atomic PRs to improve and evolve the `EuiFlyoutChild` component and its state management. This PR focuses on state management improvements.
These changes refactor the `EuiFlyoutSessionProvider` component and related files to ensure that unserializable data does not pollute the provider's state.
* Remove the `onUnmount` callbacks from various flyout configurations
* Consolidate unmount behavior with a single `onUnmount` prop at the provider level.
The changes are not considered breaking since the flyout state management is a non-public preview component for Kibana purposes only.
* Removed `onCloseFlyout` and `onCloseChildFlyout` from the flyout render context.
* Fixed the `canGoBack` logic in `packages/eui/src/components/flyout/sessions/use_eui_flyout.ts`.
* …
=> [EuiFlyoutSessionProvider] Fix `onUnmount` handler and `goBack` functionality

packages/eui/changelogs/upcoming/8847.md, packages/eui/src/components/flyout/_flyout_close_button.styles.ts, packages/eui/src/components/flyout/flyout_child.stories.tsx, packages/eui/src/components/flyout/flyout_child.styles.ts, packages/eui/src/components/flyout/flyout_child.tsx
This PR is part of a series of atomic PRs to improve and evolve the EuiFlyoutChild component and its state management. This PR focuses on state management improvements.
This pull request introduces a new background styling option enhancement to the `EuiFlyoutChild` component. 
* Remove redundant styling.
* Provide storybook example for developers.
Part of https://github.com/elastic/kibana-team/issues/1606 - Kibana SharedUX Flyout System. When demoing this project, we had feedback about there not being enough contrast between the child flyout and the underlying page background.
UI of a child flyout can have a background color that serves to better distinguish the flyout with the underlying page.
- Browser QA
~~- [ ] Checked in …
=> [EuiFlyoutChild] default / shaded background style

scripts/build_docs_versions.sh
It adds a simple Bash script that checks out each tag provided, runs all necessary build scripts and constructs a deployment folder: Docusaurus website files, `/storybook` folder with the static Storybook content, and up-to-date `versions.json`, while adding appropriate environmental variables.
Purely to help out maintainers.
Preparing manually the deployment folders when the pipeline is not working is a chore, especially when building for many different versions.
We should aim for a **functioning** CI pipeline but in cases where it isn't working or we want to add a change retroactively, it may be necessary to upload the folders directly to the GCP bucket.
=> chore: build deployment folders for tags

packages/eui/scripts/compile-icons.js
This PR updates the `compile-icons` script to ensure that the svg file paths are correct after an update to the `glob` dependency in [this PR](https://github.com/elastic/eui/pull/8694) ([change](https://github.com/elastic/eui/pull/8694/files#diff-108f1387bbecf39d15ec8e99a63d9a6963acf6c7d4bb8fc01cecb989c4b6c18aR204)).
Fixes the currently broken script that compiles icons.
- checkout this PR and manually add a new icon (e.g. by copying and renaming an existing one) in `/packages/eui/src/components/icon/svgs` and adding it to `/packages/eui/src/components/icon/icon_map.ts`
=> [Fix] Ensure correct file paths in `compile-icons`

packages/eui/changelogs/upcoming/8856.md, packages/eui/src/components/progress/__snapshots__/progress.test.tsx.snap, packages/eui/src/components/progress/progress.a11y.tsx, packages/eui/src/components/progress/progress.test.tsx, packages/eui/src/components/progress/progress.tsx
When passing a node e.g. `<EuiText>Label<EuiText>` in the `label` prop in `EuiProgress`, the text is not correctly rendered in the screen-reader-only output e.g. `[object Object]`.
This PR also removes `title` attribute for both label and value text. They're not needed for accessibility and can cause trouble (like when using a delayed tooltip, e.g. https://github.com/elastic/kibana/pull/226882#discussion_r2201246292)
It's a bug fix. Related to https://github.com/elastic/eui/pull/8829
No visual changes and no breaking changes. This change ensure the screen reader output works as well when passing something different than plain text into the `label` prop of `EuiProgress`.
- Browser QA
- ~~(_[emulate forced …
=> [EuiProgress] Handle nodes in label prop

.buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh, packages/website/package.json
On this PR, I:
- [chore: deploy both to root and version subfolder](https://github.com/elastic/eui/commit/948c610319aae63b31798faf7a56702316f7a5d7)
- The reason why we had previous version deployments missing on the documentation website is because the pipeline logic was: if it's the latest tagged release on main, deploy to root. If it's a tagged release, deploy under a version subfolder. The issue is, what happens when we make the next release? Its files just overwrite the previous version in the root folder but the version subfolder is not created.
- To fix this, if it's the latest tagged release on main, we will deploy both to the root folder and the version subfolder.
- [chore: deploy Storybook](https://github.com/elastic/eui/commit/00aa74276175e98aeccc2f0d204e0f1f13c1d2fa)
- I added …
=> chore: deploy both to root and version subfolder

packages/eui/scripts/compile-eui.js
This fixes an issue introduced in my recent https://github.com/elastic/eui/pull/8694 PR causing `dts-generator` to replace imports with an absolute path instead of a path relative to the `src` directory.
Because of a bug introduced in https://github.com/elastic/eui/pull/8694
No user-facing impact expected
=> build: fix dts-generator directory paths

packages/docusaurus-theme/src/theme/MDXComponents/Table.tsx, packages/docusaurus-theme/src/theme/MDXComponents/TableBody.tsx, packages/docusaurus-theme/src/theme/MDXComponents/TableDataCell.tsx, packages/docusaurus-theme/src/theme/MDXComponents/TableHeader.tsx, packages/docusaurus-theme/src/theme/MDXComponents/TableHeaderCell.tsx, packages/docusaurus-theme/src/theme/MDXComponents/TableRow.tsx, packages/docusaurus-theme/src/theme/MDXComponents/index.ts, packages/website/docs/components/forms/selection/overview.mdx, wiki/contributing-to-eui/documenting/writing-documentation.md
Resolves #8682
Resolves https://github.com/elastic/eui-private/issues/224
Resolves https://github.com/elastic/eui-private/issues/287
This PR adds custom table components to `MDXComponents` so that markdown tables can be rendered using `EuiTable`.
Because the native look and feel of the tables doesn't look very good.
Native markdown tables will be rendered using EUI components making them more readable and look similar to the rest of the site.
=> feat(docusaurus-theme): Support markdown tables

wiki/contributing-to-eui/testing/testing-in-kibana.md
This PR updates our wiki section on "local testing in Kibana" to include missing information about adding the `eui-theme-common` dependency in the Kibana `package.json`.
Additionally it adds information about changes required when running local packages in Kibana CI.
Improving our docs to ensure users have a clear and easy to follow guide to run local EUI testing in Kibana.
=> [Wiki] Update local Kibana testing guide with missing information about `eui-theme-common`

packages/eui/changelogs/upcoming/8864.md, packages/eui/src/components/tree_view/tree_view.stories.tsx, packages/eui/src/components/tree_view/tree_view.tsx
This PR makes it possible to add a `css` key to any node in the `items` object passed to `EuiTreeView`.
The `EuiTreeViewItem` component that renders each node, supports the `css` prop (and this is in fact [documented](https://eui.elastic.co/docs/components/navigation/tree-view/#EuiTreeViewItem)) but the prop was not being passed down.
This is a bug fix.
No action required, it will just work as expected.
=> [EuiTreeView] Fix support for `css` key in Node

packages/eui/changelogs/upcoming/8882.md, packages/eui/src/components/popover/popover.spec.tsx, packages/eui/src/components/popover/popover.tsx
closes https://github.com/elastic/eui/issues/8879
This PR aims to fix an issue on `EuiPopover` where rapid clicking of the popover toggle element would result in the popover not being closable via click outside or `Escape` key press. 
If the click interval is big enough to account for the `closingTransitionTimeout` then the popover would be closable as expected. If the interval is too short though, it would result in both `isOpening` and `isClosing` state being `true`.
https://github.com/user-attachments/assets/8d66c56c-ea2b-45b6-a690-1d628dcb0947
Ensuring that `isClosing` state is reset when opening a popover resolves this issue.
Fixing a bug on EuiPopover to ensure the popover is always closable.
| before | after |
|---|---|
| <img width="1471" height="677" alt="Screenshot 2025-07-18 at …
=> [EuiPopover] Reset `isClosing` state on opening a popover

packages/eslint-plugin/src/index.ts, packages/eui/changelogs/upcoming/8888.md
On the previous PR (https://github.com/elastic/eui/pull/8877), an issue was introduced into the ESLint plugin. An entry was added to `rules`: `no-css_color`.
I caught it on https://github.com/elastic/kibana/pull/228828.
=> fix(eslint-plugin): remove duplicate rules key

wiki/contributing-to-eui/testing/testing-in-kibana.md
This PR updates the `testing-in-kibana.md` wiki page, namely the part where it explains how to create cloud deployments for Kibana PRs. The related to the docs for getting the credentials was broken. I made it a bit more foolproof in general.
To keep internal docs up-to-date.
Internal, only relevant to contributors.
=> [Wiki] Update guideline for cloud deployments

packages/eui/changelogs/upcoming/8887.md, packages/eui/src/components/code/__snapshots__/code_block.test.tsx.snap, packages/eui/src/components/code/code_block.tsx, packages/eui/src/components/code/code_block_virtualized.tsx
relates to https://github.com/elastic/kibana/issues/205331#issuecomment-2963080851
This PR adds missing accessible labels for `EuiCodeBlock` when `isVirtualized`. We previously added accessible labels in https://github.com/elastic/eui/issues/8195 but they were not applied to the virtualized output.
Fixing an Accessibility issue for missing role and name information on `EuiCodeBlock`.
🔗 [WCAG 4.1.2: Name, Role, Value (Level A)](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html)
| before | after |
|---|---|
| <video src="https://github.com/user-attachments/assets/92c0ad4e-f13d-4181-a20e-b07329fda902" /> | <video src="https://github.com/user-attachments/assets/9de81d9e-e4ae-4b37-be14-642732e659db" /> |
🟢 There are no updates required on consumer side.
- open …
=> [EuiCodeBlock] Add accessible labels for virtualized code blocks

packages/website/docs/components/navigation/buttons/button.mdx
Resolve https://github.com/elastic/eui/issues/8855
The guideline example on the Button page didn't align with what the guideline said.
We are making this change because the current example goes against the guideline:
> Stick to the default pattern: a filled, primary button paired with an empty, but same-colored button.
`EuiButton` uses color `primary` and `EuiButtonIcon` uses color `danger`.
We settled with the designers on changing the icon to `gear` and color to `primary`.
| ------ | ------ |
| <img width="819" height="437" alt="Screenshot 2025-07-23 at 11 00 53" src="https://github.com/user-attachments/assets/1c913b97-ef4d-44c6-8aef-ba00e56a7573" /> | <img width="832" height="440" alt="Screenshot 2025-07-23 at 10 59 19" …
=> fix(website): update the button icon to align with the guideline

packages/website/docs/components/containers/modal/index.mdx
I updated the wording on the [EuiModal page](https://eui.elastic.co/pr_8905/docs/containers/modal) and highlighted that it cannot be dismissed by clicking outside (by design).
There was an internal request. Kibana developer asked about creating a custom positioned overlay and wanted to use `EuiModal` as one of the options, and was asking how we can dismiss it on clicking outside.
I think it's useful to highlight that by design, modals cannot be dismissed that way.
🟢 Just a docs fix. No impact on the library users.
=> fix(website): improve modal overview wording

packages/website/docs/components/tables/basic.mdx
On this PR, I:
- [feat(website): simplify wording on the basic table page](https://github.com/elastic/eui/pull/8908/commits/cca48e13a4ea4a10bee6746e7c06d48a07de7a9c)
- [feat(website): add a warning admonition for unique identifiers](https://github.com/elastic/eui/pull/8908/commits/c590dc65abdb1c4fc0b9dd982d0593b7b801ecd8)
There was an internal request to debug `EuiBasicTable`. When sorting, it was showing 20 items instead of 30. Finally, it turned out it was because of duplicate identifiers.
I thought we should use this opportunity to make it clear in the docs that **unique identifiers** are essential for the correct `EuiBasicTable` behavior.
🟢 Just a docs change. No impact for users.
=> feat(website): add a warning admonition for unique identifiers

packages/eui/src/components/call_out/call_out.tsx
I improved the `size` prop type in `EuiCallout` so that `react-docgen` picks it up correctly, just like for `heading` and `color` which are local types.
It was an internal request. A Kibana developer raised the issue on Slack.
| [Prod](https://eui.elastic.co/docs/components/display/callout/#EuiCallOut-prop-size) | [Staging](https://eui.elastic.co/pr_8917/docs/components/display/callout/#EuiCallOut-prop-size) |
| ----- | ------- |
| <img width="833" height="914" alt="Screenshot 2025-07-28 at 14 43 38" src="https://github.com/user-attachments/assets/0c1f2b59-aa80-400e-97ee-125124eefba9" /> | <img width="833" height="914" alt="Screenshot 2025-07-28 at 14 43 44" src="https://github.com/user-attachments/assets/655a9b1e-d8d1-41ef-aee7-567baf4422bc" /> |
🟢 Just a docs change. No impact for …
=> chore(eui): improve EuiCallout `size` prop type

packages/eui/changelogs/upcoming/8916.md, packages/eui/src/components/accessibility/index.ts, packages/eui/src/components/accessibility/live_announcer/__snapshots__/live_announcer.test.tsx.snap, packages/eui/src/components/accessibility/live_announcer/index.ts, packages/eui/src/components/accessibility/live_announcer/live_announcer.stories.tsx, packages/eui/src/components/accessibility/live_announcer/live_announcer.test.tsx, packages/eui/src/components/accessibility/live_announcer/live_announcer.tsx, packages/eui/src/components/accessibility/screen_reader_live/screen_reader_live.stories.tsx, packages/eui/src/components/accessibility/screen_reader_live/screen_reader_live.tsx, packages/eui/src/components/call_out/call_out.stories.tsx, packages/eui/src/components/call_out/call_out.test.tsx, packages/eui/src/components/call_out/call_out.tsx, packages/website/docs/components/display/callout.mdx, packages/website/docs/utilities/accessibility/index.mdx
closes https://github.com/elastic/eui/issues/8821
This PR introduces a new component: `EuiLiveAnnouncer`. This component aims to provide an alternative way (to `EuiScreenReaderLive`) of handling live region announcements.
It's not feasible for us to test all possible screen reader and browser combinations but we can determine a set that covers the majority of users. Based on the [latest screen reader survey](https://webaim.org/projects/screenreadersurvey10/#browsers) we can make some generic assumptions:
If we test the following combinations we can cover ~ 74% of usages:
- JAWS/Chrome
- NVDA/Chrome
- JAWS/Edge (Chromium based)
- NVDA/Firefox
- VoiceOver/Safari
The limitation of `aria-live` regions is that they have to be loaded and available in the DOM before content changes are being …
=> [EuiLiveAnnouncer][A11y] Support live announcements on mount

packages/eui-theme-borealis/changelogs/upcoming/8922.md, packages/eui-theme-borealis/src/variables/_index.scss, packages/eui-theme-common/changelogs/upcoming/8922.md, packages/eui-theme-common/src/global_styling/variables/_typography.scss, packages/eui/changelogs/upcoming/8922.md
This PR updates the shared  SCSS typography definitions in `eui-theme-common` and how they are imported in `eui-theme-borealis`.
>[!IMPORTANT]
EUI does not officially support SCSS styling anymore. The existing files remain to support Kibana while it migrates off SCSS.
Based on the import order and variable definition the previous setup would result in the function `lineHeightFromBaseline` to return unexpected values. This was due to the dependency function `convertToRem` relying on `$euiFontSize` which is defined in the same file combined with the order of imports of the SCSS files.
- remove duplicated shared typography SCSS in `eui-theme-common` which is defined specifically per theme in the themes themselves
- leave only actually shared typography SCSS
- ensure shared typography SCSS is …
=> [Theme] Fix typography scss order

packages/docusaurus-theme/src/theme/Navbar/Content/index.tsx, packages/eui-theme-common/src/global_styling/mixins/_form.scss, packages/eui-theme-common/src/global_styling/mixins/_range.scss, packages/eui-theme-common/src/global_styling/mixins/_typography.scss, packages/eui/changelogs/upcoming/8940.md, packages/eui/src/components/date_picker/react-datepicker/src/stylesheets/datepicker.scss, packages/eui/src/components/form/field_password/field_password.styles.ts, packages/eui/src/components/form/form.styles.test.tsx, packages/eui/src/components/form/form.styles.ts, packages/eui/src/components/form/range/range.styles.ts, packages/eui/src/global_styling/mixins/_typography.scss, packages/eui/src/services/emotion/prefixer.ts, packages/eui/src/themes/amsterdam/global_styling/mixins/_typography.scss
Resolves #8897
This PR removes IE-specific CSS properties, pseudo-elements, and other features. EUI doesn't support any Internet Explorer version anymore, and these `-ms-`-prefixed properties were causing browser errors to be printed out in the console. 
To reduce the number of errors printed out in the console.
No user impact expected. EUI doesn't support any Internet Explorer version anymore, and this PR is just a cleanup.
- Browser QA
=> Remove obsolete `-ms-` CSS prefixes

packages/website/docs/getting-started/theming/utilities/preview_utilities.tsx, packages/website/docs/getting-started/theming/utilities/typography.mdx
I'm adding a documentation for:
- `euiFontSizeFromScale`
- `euiLineHeightFromBaseline`
- `euiTextShift`
There was an internal request from a Kibana developer. They were migrating Sass and wanted to replace `lineHeightFromBaseline` with `euiLineHeightFromBaseline`. 
I noticed that there is no documentation around those utilities we export and they confirmed it would help them if there was documentation.
🟢 Just a docs change. No impact on users.
=> feat(website): add typography utilities documentation

packages/eui/changelogs/upcoming/8950.md, packages/eui/src/components/form/range/types.ts, packages/eui/src/components/popover/input_popover.spec.tsx, packages/eui/src/components/popover/input_popover.stories.tsx, packages/eui/src/components/popover/input_popover.tsx
If `disableFocusTrap` is `false`, regardless of `ownFocus`, the active item is the last tabbable item in the `EuiInputPopover` overlay and if we press <kbd>Shift + Tab</kbd>, the popover will close. It's expected to close only on pressing <kbd>Tab</kbd> because it will mean circling back to the first tabbable element. But in the other direction, it should not close.
Resolves https://github.com/elastic/eui/issues/8949
This PR comes out of a triage, so I kept the changes to the minimum, only to address the issue that the consumer is struggling with.
That being said, the keyboard navigation in this component feels weird to me. It seems that only some combination of `disableTrapFocus` and `ownFocus` produces the expected result. From my perspective, it's best if the keyboard navigation in …
=> fix(EuiInputPopover): close popover on Tab, not Shift Tab

packages/eui-theme-borealis/changelogs/upcoming/8966.md, packages/eui-theme-borealis/src/variables/colors/_semantic_colors.scss, packages/eui/changelogs/upcoming/8966.md, packages/eui/src/themes/amsterdam/_colors_dark.scss, packages/eui/src/themes/amsterdam/_colors_light.scss
This PR fixes invalid `transparent` values in SCSS. The usage of strings `'transparent'` is not correct and leads to invalid css output.
Affected SCSS variables: `$euiColorTransparent`.
Fixing incorrect SCSS variables to prevent broken style output.
| before | after |
|---|---|
| <img width="1378" height="199" alt="Screenshot 2025-08-13 at 19 15 35" src="https://github.com/user-attachments/assets/684a2f20-9c9f-47a8-9b02-68a406d3db4d" /> | <img width="1407" height="235" alt="Screenshot 2025-08-13 at 19 23 06" src="https://github.com/user-attachments/assets/4218de19-11b0-47e3-bc41-6191aa57bb7f" /> |
🟢 There are no updates needed on consumer side
🔗 [Testing codesandbox](https://codesandbox.io/p/sandbox/agitated-haze-7glrkg)
- update the `package.json` entires to `latest` to switch back to …
=> [SCSS] Fix `transparent` variable values

packages/website/scripts/update-versions.js
I remove `[skip ci]` from `chore: update versions.json [skip ci]` commit message to trigger the `eui-deploy-docs` pipeline and fix main documentation release.
The `versions.json` version append was automated on https://github.com/elastic/eui/pull/8895. The message includes `[skip ci]` so the documentation website is not released. See `eui-deploy-docs` [main history](https://buildkite.com/elastic/eui-deploy-docs/builds?branch=main&query=).
We do want the CI to run on that commit: `chore: update versions.json [skip ci]`.
For the last 2 versions that are missing, I will retroactively add it.
You can run the similar steps as on the PR ☝🏻 as a sanity check:
1. cd `eui/packages/eui`
2. Temporarily change `@elastic/eui` version: `npm version 106.1.1 --no-git-tag-version`
3. cd `../website`
4. …
=> fix(website): remove skip ci from update `versions.json`

packages/website/docs/components/display/badge/index.mdx
There is a misleading reference mentioning **EuiBadges** as a countable which actually doesn't exist referred to the React component which is uncountable **EuiBadge**. In order to avoid a weird output like this: **EuiBadge**s (with the "s" not applying the bold style) I suggest to change a bit the sentence to become: 
> EuiBadge is used to focus on important ...
- Browser QA
- Docs site QA
=> Fix typo in EuiBadge reference

packages/eui-theme-borealis/src/variables/_components.ts, packages/eui/changelogs/upcoming/8983.md, packages/eui/src/components/datagrid/data_grid.styles.ts
This PR adds a visual change to EuiDataGrid related to the background color of rows on hover, specifically when using stripes (`stripes` prop equals `true`).
The original design spec within the Visual Refresh effort removed the hover state color change for stripes. After further alignment with teams, this has been ~~reverted~~ reworked.
To make sure the design spec is implemented equally and consistently.
Related PRs:
- https://github.com/elastic/kibana/pull/229928
- https://github.com/elastic/eui/pull/8769
- https://github.com/elastic/eui-private/issues/360 🔒 
<details>
<summary>Hover states for striped data grids, in light and dark mode.</summary>
</details>
🟢 No direct impact. These visual changes ensure UI remains almost the same while encouraging consistency.
Remove or strikethrough …
=> [EuiDataGrid] Enable row background color on hover for `stripes={true}`

packages/website/docs/components/containers/flyout/_flyout_push.mdx, packages/website/docs/utilities/provider.mdx
This PR is a follow-up to https://github.com/elastic/eui/pull/8849 and https://github.com/elastic/eui/pull/8872 and adds/updates documentation for:
- `EuiFlyout`'s global CSS variables `--euiPushFlyoutOffsetInlineStart` and `--euiPushFlyoutOffsetInlineEnd`
- `EuiFlyout` specific component defaults on `EuiProvider`
To ensure available features are documented and discoverable.
🟢 There are no updates needed on consumer side. This affects EUI docs only.
=> [Docs] Add EuiFlyout CSS vars and component default documentation

packages/eui/changelogs/upcoming/9030.md, packages/eui/src/components/datagrid/controls/column_selector.tsx, packages/eui/src/components/datagrid/data_grid.spec.tsx
closes https://github.com/elastic/eui/issues/8196
This PR fixes a bug in `EuiDataGrid` when the order of `columns` and `columnVisibility.visibleColumns` are not in sync. This resulted in unexpected reordering behavior for columns where the initial `column` order would differ from the internal sorting order. The issue came from the columns selector where the states for rendering the actual `columns` and the state for rendering the column selector list items was using different non-dependent arrays.
This resulted in the columns updating unexpectedly on drag, from the column selector as well as via the cell menu "move left/right" buttons.
Instead, we need to ensure that the order in which `columns` are rendered initially depends on the order provided by `columnVisibility.visibleColumns` to …
=> [EuiDataGrid] Fix column reordering

wiki/contributing-to-eui/documenting/writing-documentation.md
Just fixing a typo that I noticed while checking our documentation wiki. I opened this PR from GitHub UI, hence it's a branch in the original repo.
=> Fix typo in documenting components section

packages/eslint-plugin/changelogs/upcoming/9046.md, packages/eslint-plugin/src/rules/a11y/no_unnamed_interactive_element.test.ts, packages/eslint-plugin/src/rules/a11y/no_unnamed_interactive_element.ts
This rule was originally introduced in #8973. 
However, `EuiButtonEmpty` already receives meaningful content as a child, which effectively serves the purpose of a role or `aria-label`. Therefore, explicitly requiring an additional accessibility attribute is unnecessary in this case.
```tsx
<EuiButtonEmpty
color="text"
onClick={handleCancelOnClick}
data-test-subj="protectionUpdatesCancelButton"
disabled={isUpdating}
>
<FormattedMessage
id="xpack.securitySolution.endpoint.protectionUpdates.cancel"
defaultMessage="Cancel"
/>
</EuiButtonEmpty>
````
=> fix: exclude `EuiButtonEmpty` from the `@elastic/eui/no-unnamed-interactive-element` rule.

packages/eui-theme-common/src/global_styling/variables/typography.ts, packages/eui-theme-common/src/services/theme/types.ts, packages/eui/src/components/header/header.stories.tsx
Some links in the docs and examples point to the old site. I've found some of them and fixed them. There are more items using relative paths, which I can address in a future PR.
We need to clean up the code base from broken links.
Broken links can be frustrating if users looking for information click on them and are redirected to the home page or a 404.
- Browser QA
- Docs site QA
=> fix: correct some jsdoc links that pointed to old docs

package.json
After the change, the color prints correctly:
`echo` is not suitable for printing formatted text. `printf` is. I used [ANSI-C quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html).
=> chore: improve root scripts output

packages/eui/changelogs/upcoming/9059.md, packages/eui/src/components/basic_table/in_memory_table.test.tsx, packages/eui/src/components/basic_table/in_memory_table.tsx
Fixes #9019 
It's possible to control the search logic from outside in `EuiInMemoryTable` by providing a `onChange` callback in the `search` prop. This works as expected by default, for `eql`. But it does not for plain text, that is enabled by passing `searchFormat="text"`.
To unblock a bug from being fixed (https://github.com/elastic/observability-dev/issues/4787).
Also for correctness.
💚 No impact, the change should be safe.
- Browser QA
- ~~(_[emulate forced colors](https://devtoolstips.org/tips/en/emulate-forced-colors/) if you do not have access to a Windows machine_.)~~
- Docs site QA
=> [EuiInMemoryTable] fire `search.onChange` for plain text (`searchFormat="text"`)

packages/website/docs/components/display/tour/index.mdx
Change the `EuiTour` docs examples to use `EuiText` as a `content` wrapper and set `size="s"`.
We want the `content` in `EuiTour` to use this composition:
```tsx
<EuiText>
<p>
{content}
</p>
</EuiText>
```
as outlined by [our docs](https://eui.elastic.co/v106.6.0/docs/components/display/text/index.html):
> **EuiText** is a generic catchall wrapper that will apply our standard typography styling and spacing to naked HTML.
That composition yields undesirable `font-size`, specifically `16px`. The hierarchy between the title and the content seems off:
Therefore, we want all our docs examples to use `size="s"`:
```tsx
<EuiText size="s">
<p>
{content}
</p>
</EuiText>
```
🟢 None. It's a website change.
=> feat(website): add size="s" to all content EuiText wrappers
